xamarin/Xamarin.Forms

Xamarin.Forms.Core.UnitTests/ShellTests.cs
Xamarin.Forms.Core/Shell/ShellContent.cs
Xamarin.Forms.Core/Shell/ShellUriHandler.cs

- fix it so you can navigate back with GotoASync("..?param=thing") and the param will pass
- fix it so renavigating to the same route will pass any new parameters
- if query string parameter is removed then set the mapped property to null
- fixes #9975

Fix query string for ".." and renavigating

---

Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/RadioButtonRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/TableViewRenderer.cs
Xamarin.Forms.Platform.iOS/ViewRenderer.cs

By implementing #9840 for some controls that override `TraitCollectionDidChange` support for iOS <13 was broken. Added code to check if we're running on iOS13 to fix this.
- Related to #9840
None
- iOS
None
Not applicable
UI Tests broken on #9840 as well as randomly clicking through the Control Gallery, especially in the areas from the changed files should now work.

Fix iOS <13 support 

---

Xamarin.Forms.ControlGallery.WindowsUniversal/App.xaml
Xamarin.Forms.Platform.UAP/FormsAutoSuggestBoxStyle.xaml
Xamarin.Forms.Platform.UAP/FormsTextBoxStyle.xaml

Fix minor styling in the UWP `TextBox` to support the adoption of Dark Theme. The only control that stood out was the `TextBox` which would get a white background and black text when focused. 
This fix uses the background determined by the system as well as the font.
From what I can tell the `TextBox` also doesn't play nicely on pure native UWP. Maybe it's intended if I read this; https://github.com/microsoft/microsoft-ui-xaml/issues/2068 but I disagree 😬 
- related to #9804
None
- UWP
In itself; none. When combined with the template fix that is coming _or_ when users remove the fixed `RequestedTheme="Light"` from the App.xaml (in UWP project, like in the changes of this PR) the Dark theme will be applied and now also to the `Entry`
For light theme no change
Open gallery app and find …

[UWP] Fix TextBox styling to adopt Dark Theme

---

Xamarin.Forms.Platform.Tizen/Native/Watch/FormsMoreOptionItem.cs
Xamarin.Forms.Platform.Tizen/Renderers/PageRenderer.cs

This PR is allow you to use `ToolbarItem` on Tizen wearable devices including Galaxy Watch series.
Previously, nothing happend even if you add a `ToolbarItem`to the `Page` on `TargetIdiom.Watch`.
Now with this PR you can use `ToolbarItem` as shown below.
If you add `ToolbarItem` to the page, it will look like this:
You can check the items by clicking the corresponding ("...") button :
> **Remark**
> This screenshot is from Tizen 5.5 version. According to the platform UX policy, in Tizen 5.0 and earlier, it is seen as a circular selector (called `Rotary Selector`) rather than a list.
None
None
- Tizen
`ToolbarItem` is now works properly on TargetIdom.Watch.

[Tizen] Enable Page.ToolbarItem on Watch

---

Xamarin.Forms.Controls/CoreGalleryPages/RadioButtonCoreGalleryPage.cs
Xamarin.Forms.Core/RadioButton.cs
Xamarin.Forms.Platform.Android/AppCompat/RadioButtonRenderer.cs

Removes the `RadioButton.ButtonSource` API for now. 
This functionality was only implemented on Android and needs implementation on iOS, UWP and MacOS.
- fixes #9948
Removed:
- `public static readonly BindableProperty ButtonSourceProperty`
- `public ImageSource ButtonSource { get; set; }`
- Android
Android users on the 4.6-pre1 version will lose the ability to use a custom image for the radiobutton. When already in use, there will be a compilation error since the API has been removed.
Not applicable
N/A

Remove RadioButton.ButtonSource API

---

Xamarin.Forms.Platform.UAP/NavigationPageRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs

Dispose() method is not called for a custom view added to  TitleView on iOS and UWP
- fixes #9939 
- iOS
- UWP

Fix 9939 [iOS][UWP] Dispose method not called when adding control inside the NavigationPage.TitleView

---

Xamarin.Forms.Platform.Tizen/Native/ListView.cs
Xamarin.Forms.Platform.Tizen/Renderers/ListViewRenderer.cs

This PR enables `Xamarin.Forms.ListView.Scrolled` event which has not been invoked on Tizen platform.
- Invoking `ListView.Scrolled` event was missing on Tizen. This PR resolves the issue.
None
- Tizen
`ListView.Scrolled` event now invoked when a `ListView` is scrolled.

[Tizen] Enable ListView.Scrolled event

---

Xamarin.Forms.Controls/GalleryPages/RefreshViewGalleries/IsEnabledRefreshViewGallery.xaml
Xamarin.Forms.Controls/GalleryPages/RefreshViewGalleries/IsEnabledRefreshViewGallery.xaml.cs
Xamarin.Forms.Controls/GalleryPages/RefreshViewGalleries/RefreshCollectionViewGallery.xaml
Xamarin.Forms.Controls/GalleryPages/RefreshViewGalleries/RefreshViewGallery.cs
Xamarin.Forms.Platform.iOS/Renderers/RefreshViewRenderer.cs

If you have a RefreshView with a ScrollView (or other scrollable content) inside and `IsEnabled` on the RefreshView is set to False you can't scroll anymore on iOS. This PR fix the scroll issues disabling a RefreshView.
- fixes #9232 
None
- iOS
None
Launch Core Gallery and navigate to RefreshView samples. Select the "RefreshView IsEnabled Gallery". Enable/disable the RefreshView and verify that the interaction with the list continues working.

[iOS] Fixed scroll issue disabling a RefreshView

---

Xamarin.Forms.Controls/GalleryPages/RefreshViewGalleries/RefreshScrollViewGallery.xaml.cs
Xamarin.Forms.Controls/GalleryPages/RefreshViewGalleries/RefreshViewGallery.cs
Xamarin.Forms.Platform.iOS/Renderers/RefreshViewRenderer.cs

Fix initial wrong RefreshColor in RefreshView.
- fixes #8940
None
- iOS
None
Launch Core Gallery and navigate to the RefreshView samples. Select the sample using a ScrollView and verify that the initial RefreshColor is not the default one (black).

[iOS] Fix initial wrong RefreshColor in RefreshView

---

Xamarin.Forms.Platform.UAP/FontImageSourceHandler.cs

Testing this PR https://github.com/xamarin/Xamarin.Forms/pull/9915 I have found an exception creating FontIcons.
Fixed exception creating a FontFamily with an empty font name using a **FontIcon** in **UWP**.
None
- UWP
None
Not applicable
Launch Core Gallery and go to the Shell Store sample. Open the Flyout menu. If no exception is thrown by opening the Flyout the test has passed.

[UWP] Fix FontIcon issue using a empty font name

---

Xamarin.Forms.Core.UnitTests/ShellLifeCycleTests.cs
Xamarin.Forms.Core.UnitTests/ShellModalTests.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellSection.cs
Xamarin.Forms.Platform.Android/Renderers/ShellSectionRenderer.cs

- Inject the shell proxy into the modal pages so that the shell navproxy handles navigation
- wire up the back button pressed to navigating
- Cancel Top Nav Bar navigation
- fixes #10108

Shell fix modal onappearing and hardware back button

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Github1625.cs
Xamarin.Forms.Platform.Android/Renderers/SliderRenderer.cs

Changes here https://github.com/xamarin/Xamarin.Forms/pull/1756 made it so the slider value would only update when physically interacted with. When TalkBack is on the progressbar is updated via the volume buttons which won't trigger those listeners. 
This PR changes the listener to check the `fromUser` to determine whether it should update or not. I tested the scenarios outlined on the issue that regressed this and the talkback scenario. It seems like using `fromUser` is reliable in all relevant scenarios.
The material slider already works like this as well.
- fixes #2800 
- Android
- test any slider with talk back on. The included issue has a slider.

Slider value updates with Talk Back activated and volume buttons correctly

---

Xamarin.Forms.Platform.Android/CollectionView/CarouselSpacingItemDecoration.cs
Xamarin.Forms.Platform.Android/CollectionView/SpacingItemDecoration.cs

Right now, there is no way to extend the functionality of ```SpacingItemDecoration``` and ```CarouselSpacingItemDecoration```. You have to manually copy and paste them and make your own changes by extending ```RecyclerView.ItemDecoration```.
- Android

[Android] Make ItemDecoration implementations accessible

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9951.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/AppCompat/SwitchRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/SwitchRenderer.cs

- fixes #9951
None
- Android
It shows Switch without squares when OnColor and ThumbColor is set
Before:
After:
Create a switch and set OnColor and ThumbColor.

Fixed #9951 -  Setting ThumbColor on Switch causes a square block

---

Xamarin.Forms.Core/FontRegistrar.cs
Xamarin.Forms.Platform.iOS/EmbeddedFontLoader.cs

iOS verifies a font is installed, if it fails to register the font.
FontLoader now caches the lookups to prevent double looking, and is faster for subsequent lookups since it no longer hits native after the first lookup.
- fixes #10208
- fixes #10226
- iOS
None
Not applicable

Embedded font's now cache lookup to prevent double setups. fixes #10208

---

Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
Xamarin.Forms.ControlGallery.iOS/_9767CustomRenderer.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9767.cs
Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs

Fix issue in NavBar setting a custom BackgroundImage on iOS. 
- fixes #9767 
None
- iOS
None
Not applicable
Launch Core Gallery and navigate to the issue 9767. Press the "Navigate· button. We use a custom renderer where a background image is set for UINavigationBar. If you can see the gradient, the test has passed. Test the same in a device (or simulator) with iOS 13 and iOS 12!.

[iOS] Fix issue in NavBar setting a custom BackgroundImage

---

Stubs/Xamarin.Forms.Platform.cs
Xamarin.Forms.ControlGallery.Tizen/ControlGallery.Tizen.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/CollectionView.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/GridLayoutManager.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/ICollectionViewLayoutManager.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/IndicatorView.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/LinearLayoutManager.cs
Xamarin.Forms.Platform.Tizen/Properties/AssemblyInfo.cs
Xamarin.Forms.Platform.Tizen/Renderers/CarouselViewRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/IndicatorViewRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/ItemsViewRenderer.cs
Xamarin.Forms.Platform.Tizen/StaticRegistrar.cs

1. Invoke ItemsView.Scrolled event.
2. Changed the CarouselView Tizen renderer scroll logic.
3. Add IndicatorView for Tizen.
- Tizen
Xamarin.Forms.ControlGallery - CarouselView Gallery - IndicatorView Gallery

[Tizen] Changed CarouselView scroll logic according to the Core change.

---

Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs

Fixed exception in iOS NavigationRenderer getting the parent ViewController.
- fixes #10250 
None
- iOS
None
Not applicable

[iOS] Fix NRE in NavigationController

---

Xamarin.Forms.Platform.Tizen/IRotaryInteraction.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/CollectionView.cs
Xamarin.Forms.Platform.Tizen/Native/ListView.cs
Xamarin.Forms.Platform.Tizen/Native/Scroller.cs
Xamarin.Forms.Platform.Tizen/Native/Watch/WatchListView.cs
Xamarin.Forms.Platform.Tizen/Native/Watch/WatchScroller.cs
Xamarin.Forms.Platform.Tizen/Renderers/EditorRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/ListViewRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/ScrollViewRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/ViewRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs

This PR includes two features. 
The first one is to change native UI controls to suitable for watch when the application is running on watch, and it activates bezel interaction of the widgets when it takes a focus.
(To turn off this interaction, you can check this API #10083  )
The second one is to support `VerticalScrollBarVisibility` and `HorizontalScrollBarVisibility`  of `Listview` on Tizen.
None
None
- Tizen
- Bezel interaction applied UI Controls are
- CollectionView
- ListView
- CarouselView
- ScrollView
`ListView` wil be displayed same with `CircleListView` provided from `Tizen.CircularUI`.
`CircularUI` provides a rotary event handling API that allows you to activate which widget to get the rotary interaction. Therefore, you use `CircularUI` to selectively decide which widget to …

[Tizen] Enhances ListView on Tizen 

---

Xamarin.Forms.Platform.iOS/ViewRenderer.cs

There are some cases like `RefreshView` where `Control` is null at this point for some reason. Added a null check to prevent an NRE when this happens.
- fixes #10245 
None
- iOS
None
Not applicable
This was specifically breaking with `RefreshView` so try if that still works whenever you switch over the appearance mode. You can also pull down the NuGet associated with this build and try that on the reproduction from the issue.

[iOS] Add null-check to prevent possible NRE

---

Xamarin.Forms.Core/Expander.cs

Do not run animation if IsExpanded changed due to BindingContext change.
- fixes #10229 
None
- Core
The issue has gone.
AFTER:
Test sample attached to the issue ticket.

[Bug] Expander + CollectionView: Expander content keeps reopening

---

Xamarin.Forms.Core.UnitTests/ShellTests.cs
Xamarin.Forms.Core/MenuItem.cs
Xamarin.Forms.Core/Shell/BaseShellItem.cs
Xamarin.Forms.Core/Shell/IShellController.cs
Xamarin.Forms.Core/Shell/MenuShellItem.cs
Xamarin.Forms.Core/Shell/NavigableElement.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRecyclerAdapter.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewSource.cs

The initial implementation that moved flyout item templates up into the xplat layer didn't take into account the general templates that you can assign to shell.
This PR also breaks the ability to change the StyleClass after the template has been realized because I'm not really sure how to propagate the StyleClass from a `BaseShellItem` to the template that was created from it
- fixes #10238
StylesClass on BaseShellItem's no longer support changing
https://github.com/xamarin/Xamarin.Forms/issues/10251
- run control gallery and make sure the flyout replaced everything as expected

Fix default Shell flyout item templates

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10222.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs

Make sure to dispose the delegator so it doesn't fire the scrolled when we are disposing the page while scrolling 
- fixes #10222 
None
- iOS
None
Not applicable

[iOS] Fix CollectionView disposing of Delegator 

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10234.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewController.cs

Make sure to unsubscribe the Scrolled event on CarouselViewRenderer
- fixes #10234 
None
- iOS
None
Not applicable
Added UITest, go to a CarouselVIew and scroll 2 times should work.

[iOS]Fix dispose of all events on CarouselViewRenderer

---

Stubs/Xamarin.Forms.Platform.cs
Xamarin.Forms.Platform.Tizen/Properties/AssemblyInfo.cs
Xamarin.Forms.Platform.Tizen/Renderers/RadioButtonRenderer.cs
Xamarin.Forms.Platform.Tizen/StaticRegistrar.cs

This PR is a Tizen implementation of RadioButton (#8910).
- Mobile
- Weaarable
- `Text` property is ignored on Tizen 4.0 wearable profile.
- fixes #2404 for Tizen
**` namespace Xamarin.Forms.Platform.Tizen `** 
Added:
- public class RadioButtonRenderer
- Tizen
Go `RadioButtonGallery`

[Tizen] Adds RadioButton

---

UWP.Build.props
UWP.Build.targets
Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
Xamarin.Forms.Controls/GalleryPages/TwoPaneViewGalleries/TwoPanePropertiesGallery.xaml
Xamarin.Forms.Controls/GalleryPages/TwoPaneViewGalleries/TwoPanePropertiesGallery.xaml.cs
Xamarin.Forms.DualScreen/DualScreenHelper.uwp.cs
Xamarin.Forms.DualScreen/DualScreenInfo.android.cs
Xamarin.Forms.DualScreen/DualScreenInfo.netstandard.cs
Xamarin.Forms.DualScreen/DualScreenInfo.shared.cs
Xamarin.Forms.DualScreen/DualScreenInfo.uwp.cs
Xamarin.Forms.DualScreen/DualScreenService.android.cs
Xamarin.Forms.DualScreen/DualScreenService.uwp.cs
Xamarin.Forms.DualScreen/Xamarin.Forms.DualScreen.csproj
Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj

- Setup UWP projects to be ready for SDK 19***
- Added Hinge Angle getter for UWP
- Added Hinge Angle Events
Added:
```C#
public class HingeAngleChangedEventArgs : EventArgs
{
public HingeAngleChangedEventArgs(double hingeAngleInDegrees)
{
HingeAngleInDegrees = hingeAngleInDegrees;
}
public double HingeAngleInDegrees { get; }
}
```
```C#
public class DualScreenInfo
{
public event EventHandler<HingeAngleChangedEventArgs> HingeAngleChanged
}
```
- iOS
- Android
- UWP
- test through two pane view gallery

Dualscreen updates to new apis and add hinge angle for UWP

---

Xamarin.Forms.Core/AdaptiveTrigger.cs
Xamarin.Forms.Core/CompareStateTrigger.cs
Xamarin.Forms.Core/OrientationStateTrigger.cs
Xamarin.Forms.Core/StateTrigger.cs
Xamarin.Forms.Core/StateTriggerBase.cs
Xamarin.Forms.Core/VisualElement.cs
Xamarin.Forms.DualScreen/SpanModeStateTrigger.shared.cs
Xamarin.Forms.DualScreen/WindowSpanModeStateTrigger.shared.cs

When creating a custom State Trigger (Example https://github.com/jsuarezruiz/XamarinFormsStateTriggers) we may need to register or subscribe events. In this PR we change the  StateTriggerBase OnAttached and OnDetached methods to be public. This will help to create more complex StateTriggers in an easy way.
None
- Core
None
Not applicable

Change StateTriggerBase OnAttached and OnDetached methods to be public

---

Xamarin.Forms.Core.UnitTests/MockPlatformServices.cs
Xamarin.Forms.Core/AppThemeChangedEventArgs.cs
Xamarin.Forms.Core/AppThemeColor.cs
Xamarin.Forms.Core/Application.cs
Xamarin.Forms.Core/IPlatformServices.cs
Xamarin.Forms.Core/OSAppTheme.cs
Xamarin.Forms.Core/OnAppTheme.cs
Xamarin.Forms.Core/Page.cs
Xamarin.Forms.Core/VisualElement.cs
Xamarin.Forms.DualScreen.UnitTests/MockPlatformServices.cs
Xamarin.Forms.Platform.Android/Forms.cs
Xamarin.Forms.Platform.GTK/GtkPlatformServices.cs
Xamarin.Forms.Platform.Tizen/TizenPlatformServices.cs
Xamarin.Forms.Platform.UAP/WindowsBasePlatformServices.cs
Xamarin.Forms.Platform.WPF/WPFPlatformServices.cs
Xamarin.Forms.Platform.iOS/Forms.cs
Xamarin.Forms.Xaml.UnitTests/OnPlatformTests.cs
Xamarin.Forms.Xaml/MarkupExtensions/OnAppThemeExtension.cs

To prevent name clashing with Essentials, rename our enum
Changed:
- enum AppTheme => enum OSAppTheme
None
No more naming conflicts (thus build errors) when upgrading to 4.6 and Essentials installed using their `AppTheme`

Rename AppTheme enum to OSAppTheme

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9580.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9686.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/CollectionView/ObservableGroupedSource.cs
Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs

On iOS, a CollectionView with all empty groups is crashing when adding the first item; UICollectionView internal accounting gets confused.
These changes check for that circumstance and tell the UICollectionView to do a data reload instead, which allows it to get the internal accounting correct (and prevent the crash).
This also adds a check to prevent UICollectionView full reloads while the UICollectionView is in the process of animating other changes (which results in a garbled cell arrangement).
- Fixes #9580
- Fixes #9686
None
- iOS
None
Not applicable
Automated test (Issue 9580)
Automated test (Issue 9686)

Handle "groups but no actual cells" cases for reloading UICollectionView

---

Xamarin.Forms.Core/PlatformConfiguration/TizenSpecific/IVideoOutput.cs
Xamarin.Forms.Platform.Tizen/Native/EmbeddingControls.cs
Xamarin.Forms.Platform.Tizen/Native/MediaPlayerImpl.cs
Xamarin.Forms.Platform.Tizen/Properties/AssemblyInfo.cs

This PR fix `MediaPlayerImpl` dependency service registration correctly.
None
Below methods are added into `Xamarin.Forms.PlatformConfiguration.TizenSpecific.IMediaPlayer` interface.
- Task<bool> Start();
- void Stop();
- void Pause();
- Tizen
None
Not applicable

[Tizen] Fix dependency service registration correctly

---

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ObservableCodeCollectionViewGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ObservableCollectionGallery.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewRenderer.cs

The ItemsViewRenderer on iOS will now update the ItemsUpdatingScrollMode upon loading the element. 
- fixes #7788
None
- iOS
The ItemsViewRenderer on iOS will now update the ItemsUpdatingScrollMode upon loading the element. 
There seems to be a timing issue where setting the ItemsUpdatingScrollMode right after creating the CollectionView doesn't fire the OnElementPropertyChanged method in the ItemsViewRenderer. 
Not applicable
I've added the different ItemsUpdatingScrollMode modes to the ObservableCodeCollectionViewGallery

Update ItemsUpdatingScrollMode when element loaded on iOS

---

Xamarin.Forms.Core/PlatformConfiguration/TizenSpecific/Application.cs
Xamarin.Forms.Platform.Tizen/FormsApplication.cs

This PR is about overlay content view of application. Some application want to use overlay content view that is a view for hosting layered content on top of the application view. (e.g. Floating Button)
To support this, this PR adds a Tizen Specific API. 
This Tizen platform-specific is used to host layered content on top of the application. It's consumed in XAML by setting the `Application.OverlayContent` bindable property.
```xml
<Application ...
xmlns:tizen="clr-namespace:Xamarin.Forms.PlatformConfiguration.TizenSpecific;assembly=Xamarin.Forms.Core"">
<tizen:Application.OverlayContent>
<AbsoluteLayout VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
<Image Source="favorite.png" AbsoluteLayout.LayoutBounds=".5, .5, 64, 64" …
```

[Tizen] Adds OverlayContent to Application

---

Xamarin.Forms.Core.UnitTests/BindingBaseUnitTests.cs
Xamarin.Forms.Platform.UAP.UnitTests/BackgroundColorTests.cs
Xamarin.Forms.Platform.UAP.UnitTests/FlowDirectionTests.cs
Xamarin.Forms.Platform.UAP.UnitTests/IsEnabledTests.cs
Xamarin.Forms.Platform.UAP.UnitTests/PlatformTestFixture.cs
Xamarin.Forms.Platform.UAP.UnitTests/RendererTests.cs
Xamarin.Forms.Platform.UAP.UnitTests/RotationTests.cs
Xamarin.Forms.Platform.UAP.UnitTests/ScaleTests.cs
Xamarin.Forms.Platform.UAP.UnitTests/Xamarin.Forms.Platform.UAP.UnitTests.csproj
Xamarin.Forms.Platform.UAP/EditorRenderer.cs
Xamarin.Forms.Platform.UAP/FlowDirectionExtensions.cs
Xamarin.Forms.Platform.iOS.UnitTests/FlowDirectionTests.cs
Xamarin.Forms.Platform.iOS/Renderers/AlignmentExtensions.cs
Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs

For 9022, updates the text alignment extensions on iOS to return Right instead of Natural when determining text alignment for an RTL Entry.
For 5860, Entry was already working. Editor was still having issues because the attempts to set the TextAlignment were at odds with the FlowDirection, which handles the alignment automatically if we let it.
Part of 3359 is a duplicate of 9022. The Android parts of that report already seem to be fixed.
- fixes #9022
- fixes #5860
- fixes #3359
None
- iOS
- UWP
None
Not applicable
Automated tests

Entry and Editor RTL fixes

---

azure-pipelines.yml
build.cake
build/steps/build-android.yml
build/steps/build-osx.yml
build/steps/build-windows.yml

- Set the OS demand for all the pools so that everything uses the correct operating system to build. 
- Added conditional windows steps so it would use demands when using our bots opposed to pipelines
- added a check for xcode version so it'll install the correct sdks
- Turn on the bots that are confusing the builds and make sure everything still builds
Internal
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3642726&view=results
Hosted 10.15
https://dev.azure.com/xamarin/public/_build/results?buildId=16940&view=logs&j=be1d3261-c4d2-5528-aad8-51398c05403f
Bot turned on with 10.15
https://dev.azure.com/xamarin/public/_build/results?buildId=16939&view=results
Hosted 10.14 (normal run without modifying parameters)
https://dev.azure.com/xamarin/public/_build/results?buildId=16938 …

Set agent os for all pools

---

Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
Xamarin.Forms.ControlGallery.Android/Tests/PlatformTestFixture.cs
Xamarin.Forms.ControlGallery.Android/Tests/RendererTests.cs
Xamarin.Forms.Platform.Android/AppCompat/ImageButtonRenderer.cs
Xamarin.Forms.Platform.Android/ButtonLayoutManager.cs
Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs
Xamarin.Forms.Platform.Android/FastRenderers/ImageElementManager.cs
Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs
Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
Xamarin.Forms.Platform.Android/ILayoutChanges.cs
Xamarin.Forms.Platform.Android/Platform.cs

Regressed as part of https://github.com/xamarin/Xamarin.Forms/pull/9629
If the control hasn't performed a layout cycle yet then just allow it to set initial parameters
- fixes #10102 
- fixes #10290
- fixes #10197
- Android
- UI Tests included

[Android] Set native properties from element if layout hasn't occurred 

---

Xamarin.Forms.Platform.UAP/FormsAutoSuggestBoxStyle.xaml
Xamarin.Forms.Platform.UAP/FormsTextBoxStyle.xaml

Makes sure the clear and search button on UWP also get the right color when switching between light and dark
- related #10150 (this issue was mentioned in a comment there)
None
- UWP
None
Open gallery app, switch Windows to dark and see if the icons in the entry still are visible when focused, not focused etc.

Fix coloring of UWP Entry buttons

---

Xamarin.Forms.Platform.iOS/CollectionView/GridViewLayout.cs

These changes adjust the grid layout on iOS to correct for some edge cases. 
For vertical grids with a single item, the single item was centered rather than left-aligned. These changes detect the situtation and fix the item alignment.
For horizontal grids where the items can have varying sizes, a situation can occur where larger items added lower down in a column _should_ realign the itemsw further up the column, but the initial layout would fail to update the items higher up in the column. These changes detect that situation and adjust the centering of the items.
- fixes #5455
- fixes #6851
None
- iOS
Issue 5455 Before:
Issue 5455 After:
Issue 6851 Before:
Issue 6851 After:
Navigate to Control Gallery -> CollectionView Gallery -> DataTemplate Galleries -> Vertical Grid (Code)
Update the …

Alignment fixes for CollectionView grid layouts on iOS

---

Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeItemIsEnabledGallery.cs
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeItemIsVisibleGallery.cs
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeViewGallery.cs
Xamarin.Forms.Core/ISwipeItem.cs
Xamarin.Forms.Core/SwipeItem.cs
Xamarin.Forms.Core/SwipeItemView.cs
Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs

Added IsEnabled and IsVisible properties to SwipeItem.
- fixes #9881 
None
- iOS
- Android
- UWP
None
Launch Core Gallery and navigate to the SwipeView demos. Now, you can find two new demos to test the SwipeItem `IsEnabled` and `IsVisible` properties.

[SwipeView] Added IsEnabled and IsVisible properties to SwipeItem

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4606.cs
Xamarin.Forms.Platform.Android/Renderers/BorderDrawable.cs

Don't inset the clipping path by the border width
- fixes #10269 
- Android
- Check included ui test

[Android] Fix border clipping calculations

---

Xamarin.Forms.Platform.Tizen/Cells/SwitchCellRenderer.cs

There used to be only one `SwitchCell` style on Tizen platform which has no fish-eye effect and no text sliding when the text is longer than a cell size.
This PR is about applying a new `SwitchCell` style to `Watch` target idiom. This style includes the fish-eye effect and text sliding effect.
- N/A
None
- Tizen
Now the `SwitchCell` on Watch target idiom has fish-eye and text sliding effects as default.
|As-is|To-be|
|--|--|
|Fisheye Effect Off & Text slide Off | Fisheye Effect On & Text slide On|
|![switchcell_default2](https://user-images.githubusercontent.com/14328614/79452424-1bfd0980-8023-11ea-8e4a-a9a907aa84da.gif) |![switchcell_styleonwatch](https://user-images.githubusercontent.com/14328614/79452463-28816200-8023-11ea-8c3e-a12d719f118c.gif)|

[Tizen] Applying new style on SwitchCell

---

Xamarin.Forms.Controls/GalleryPages/MapGallery.xaml
Xamarin.Forms.Controls/GalleryPages/MapGallery.xaml.cs
Xamarin.Forms.Maps.Android/MapRenderer.cs

Call the UpdateVisibleRegion when the map loads
- fixes #10146
None
- Android
Map region should be available when map loads
Not applicable
Go to map gallery and click the Map Region button, it should show the values for lat/long and MapSpan

[Android,Maps] Set initial MapRegion when map is ready

---

Xamarin.Forms.Platform.Tizen/FormsApplication.cs

This PR fixes the corner case of https://github.com/xamarin/Xamarin.Forms/pull/10310 which can occur an exception when `OverlayContent` is empty.
- fixes the possible corner case of https://github.com/xamarin/Xamarin.Forms/pull/10310.
None
- Tizen
None
Not applicable

[Tizen] Fix exception updating empty OverlayContent

---

Xamarin.Forms.Material.Tizen/MaterialDatePickerRenderer.cs
Xamarin.Forms.Material.Tizen/MaterialEditorRenderer.cs
Xamarin.Forms.Material.Tizen/MaterialPickerRenderer.cs
Xamarin.Forms.Material.Tizen/MaterialTimePickerRenderer.cs
Xamarin.Forms.Material.Tizen/Native/MEditor.cs
Xamarin.Forms.Material.Tizen/Native/MPicker.cs
Xamarin.Forms.Platform.Tizen/Native/EditfieldEntry.cs
Xamarin.Forms.Platform.Tizen/Native/Entry.cs
Xamarin.Forms.Platform.Tizen/Native/IEntry.cs
Xamarin.Forms.Platform.Tizen/Renderers/DatePickerRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/EditorRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/PickerRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/TimePickerRenderer.cs

This PR includes two commits. The one is to add material renderers for `Editor`, `Picker`, `DatePicker`, `TimePicker`, and the other one is to fix the renderes for picker to hide a cursor.
None
The APIs in Tizen backend has been changed as follows:
(`Xamarin.Forms.Platform.Tizen` and `Xamarin.Forms.Material.Tizen`)
Added:
- Entry
protected virtual OnTextBlockFocused();
protected virtual OnTextBlockUnfocused();
protected virtual OnEntryLayoutFocused();
protected virtual OnEntryLayoutUnfocused(); 
- IEntry
event EventHandler TextBlockFocused
event EventHandler TextBlockUnfocused
event EventHandler EntryLayoutFocused
event EventHandler EntryLayoutUnfocused
- EditorRenderer
protected virtual EEntry CreateNativeControl()
- TimePickerRenderer
protected virtual EEntry CreateNativeControl()
- …

[Tizen] Add material renderers for Editor and Picker

---

Xamarin.Forms.Platform.iOS/Extensions/FontExtensions.cs
Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs

FontImageSource now uses the embedded font loader on iOS
fixes #10312 
None
- iOS

FontImageSource now uses Embedded Fonts on iOS

---

Xamarin.Forms.Platform.Android/VisualElementTracker.cs

Don't use the global layout listener if you're in designer mode. The designer just goes nuts and disposes of everything so global listeners will sometimes cause disposal exceptions
- Android
- tests pass
- pull down the nuget and test the previewer on vsmac and vs windows

Fix previewer flakiness on Android

---

Xamarin.Forms.Core.UnitTests/ShellTests.cs
Xamarin.Forms.Core/Shell/BaseShellItem.cs
Xamarin.Forms.Core/Shell/ShellItem.cs

Give the elements created for the flyout template a namescope so you can set them on the VSM
- fixes #10382

Give elements inside flyout a namescope for VSM

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellItemIsVisible.cs
Xamarin.Forms.Core.UnitTests/ShellTests.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellContentCollection.cs
Xamarin.Forms.Core/Shell/ShellItem.cs
Xamarin.Forms.Core/Shell/ShellSection.cs
Xamarin.Forms.Platform.Android/Renderers/ShellSectionRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootHeader.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewController.cs

- iOS ShellSectionRenderers aren't reacting to clear properly
- iOS ShellSectionRenderers weren't reacting to elements being removed and then updating to the proper renderer correctly
- Shell Elements weren't updating current item properly when the Current Item became non visible
- iOS
- test the included gallery page for different permutations of hiding and showing things

[iOS] Shell fix clear of ShellSection 

---

Xamarin.Forms.Core.UnitTests/ShellTests.cs
Xamarin.Forms.Core/Shell/BaseShellItem.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Platform.UAP/Shell/ShellFlyoutItemRenderer.cs

StyleClass set on ShellItem wasn't propagating from the ShellItem to the template correctly
- fixes #10382
- iOS

Propagate StyleClass from Items correctly

---

Xamarin.Forms.Core/AnimationExtensions.cs
Xamarin.Forms.Core/Tweener.cs

Adds support for the `rate` parameter for `Animation`. This parameter existed but was unused.
fixes #5322
Added:
- `public Tweener(uint length, uint rate)`
- `uint Tweener.Rate { get; }`
The existing constructor of `Tweener` is also kept and defaults `rate` to `1`. This way existing code which uses the `Tweener` does not have to be updated.
None
Below are three GIFs for an example animation with 50ms, 200ms and 500ms rate.

Add support for animation rate parameter

---

Xamarin.Forms.Platform.iOS.UnitTests/ImageButtonTests.cs
Xamarin.Forms.Platform.iOS.UnitTests/PlatformTestFixture.cs
Xamarin.Forms.Platform.iOS.UnitTests/Xamarin.Forms.Platform.iOS.UnitTests.csproj
Xamarin.Forms.Platform.iOS/Renderers/ImageButtonRenderer.cs

When GIF changes were rolled back from the ImageButtonRenderer the UIButtonType used for creating the UIButton wasn't correct. 
- fixes #9112
- iOS
- test included
- click on any image buttons in the gallery and make sure the animation matches the expectation in the referenced issue #9112

Create ImageButton with correct Button Type

---

Environment.Build.props
azure-pipelines.yml
build.cake
build/provisioning/provisioning.csx
build/provisioning/xcode.csx
build/steps/build-android.yml
build/steps/build-osx.yml
build/steps/build-windows.yml

- Setup a pipeline variable we can use to provision the specific version of XCode we want to use
- Switch provisionator file to work off of stable/release channels when provisioning sdk stuff
verify builds

Setup Xcode provisioning through variables and switch to channels

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10438.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems

I have been able to verify the issue in the reproduction sample but after testing in 4.5 branch it seems that the issue have been fixed in recent changes. For that reason, this PR only include the sample in Core Gallery.
- fixes #10438
None
- iOS
None
Launch Core Gallery and navigate to the Issue 10438. Verify that you can hide and show the NavigationBar separator.

[iOS] NavigationPage.HideNavigationBarSeparator doesn't work on iOS 13

---

Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
Xamarin.Forms.Platform.Android/Resources/values/styles.xml

Reverts the changes of #8090. Caused too much regression on other controls inside of a `ScrollView`. Reverting the changes for now and reopening #8015 to find a new solution for the initial problem.
- fixes #9591
- fixes #9423
- fixes #9019
- fixes #8986
None
- Android
No more scrollbar flashes on controls in a `ScrollView`. On the other hand, the `ScrollView` scrollbar visibility will be broken again,
Not applicable
There are multiple scenarios where you can find this. You can go to the Material Entry gallery and whenever you focus one entry you see the scrollbar flash on the right.
If you go to the label gallery and go through the `MaxLines` cases you will also see a scrollbar flash.
With this change, that should not be visible anymore

Revert #8090 Android scrollbar flashes

---

Xamarin.Forms.Core.UnitTests/VisualStateManagerTests.cs
Xamarin.Forms.Core/VisualElement.cs
Xamarin.Forms.Core/VisualStateManager.cs
Xamarin.Forms.Platform.Android.UnitTests/ButtonTests.cs
Xamarin.Forms.Platform.Android.UnitTests/Xamarin.Forms.Platform.Android.UnitTests.csproj

VisualStateGroupsProperty has a defaultValueCreator which makes IsSet unreliable. 
- Convert the HasVSG check over to not using IsSet so that if someone retrieves the property the toggling of isSet to true won't change behavior
- fixes #10040
- Android

Fix has VSM check to not use IsSet

---

Xamarin.Forms.Controls/CoreGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselItemsGallery.cs
Xamarin.Forms.Controls/GalleryPages/IndicatorViewGalleries/IndicatorGalleries.cs
Xamarin.Forms.Controls/GalleryPages/IndicatorViewGalleries/IndicatorsSample.xaml.cs
Xamarin.Forms.Controls/GalleryPages/IndicatorViewGalleries/IndicatorsSampleMaximumVisible.xaml
Xamarin.Forms.Controls/GalleryPages/IndicatorViewGalleries/IndicatorsSampleMaximumVisible.xaml.cs
Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
Xamarin.Forms.Core/IndicatorView.cs
Xamarin.Forms.Platform.Android/CollectionView/IndicatorViewRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/IndicatorViewRenderer.cs

Adds functionality to coerce the `MaximumVisible` and `ItemsSource.Count` value. If `ItemsSource.Count` is lower than `MaximumVisible` it will show `MaximumVisible` and vice versa.
In addition rearranged some pages in the gallery app to make it more logical and added this specific case.
- fixes #9826
None
Users already using this should see the right amount of maximum indicators after updating. This _can_ be less than they would see before, because before it would _always_ show the number set in `MaximumVisible` even thought there weren't even that many items.
Not applicable
Go to the `IndicatorView` gallery and choose the "Indicator MaxVisible Gallery" option. There is a button to decrease the `MaximumVisible` value and a button to set the `MaximumValue` to …

Indicator shows # of indicators = MaximumVisible even when there are fewer items

---

Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
Xamarin.Forms.sln

- Add some additional conditions on the UAP project to help vsmac out
- Remove all the project dependencies associated with the dual screen info project. Just let VS figure it out
- from a clean git make sure you can launch and build each of the projects on windows/vsmac
- make sure whatever issue @rmarinho and @jfversluis weren't seeing isn't seen anymore

Fix vsmac uwp targets

---

Xamarin.Forms.Core/WebView.cs
Xamarin.Forms.Platform.Android/Renderers/FormsWebViewClient.cs
Xamarin.Forms.Platform.UAP/WebViewRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/WebViewRenderer.cs

Added a new bound property that controls whether or not Xamarin Forms manages web view cookies on iOS, Android, and UAP.
- fixes #10318 
Added:
- bool WebView.ShouldManageCookies { get; set; } // Bindable Property
- Core
This will impact users on the pre-release 4.6.0 version of Forms; the cookie management behavior introduced in #8169 will no longer be automatic; it is now opt-in.
I was unable to build Xamarin Forms on my MacBook, so I wasn't able to build a test case; a simple project with a webview that requires cookies would suffice.

Make managed cookies opt-in

---

Xamarin.Forms.Core/Expander.cs

Please firstly look through #10449 
Collapse and Expand animation are being cut off when "Spacing" property has a value.t seems that the Spacing just moves down the content by the value in the Spacing property and just leaves an empty space between the Content and Header. I do not see any use case for this. (Spacing can easily be managed by Margin/Padding and it won't cause UI glitches).
I didn't mark it as Obsolete because stable 4.6.0 is not released yet.
- fixes #10449 
Removed:
- double Expander.Spacing
- Core
N/A
Not applicable
The sample is attached to the bug ticket.

Removed useless Expander.Spacing property (Bug fix)

---

Xamarin.Forms.Controls/GalleryPages/AppThemeGalleries/AppThemeCodeGallery.cs
Xamarin.Forms.Controls/GalleryPages/AppThemeGalleries/AppThemeXamlGallery.xaml
Xamarin.Forms.Controls/GalleryPages/AppThemeGalleries/AppThemeXamlGallery.xaml.cs
Xamarin.Forms.Core.UnitTests/AppThemeTests.cs
Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
Xamarin.Forms.Core/Application.cs
Xamarin.Forms.Core/BindableObjectExtensions.cs
Xamarin.Forms.Core/OnAppTheme.cs
Xamarin.Forms.Core/VisualElement.cs
Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
Xamarin.Forms.Xaml.UnitTests/OnPlatformTests.cs
Xamarin.Forms.Xaml/MarkupExtensions/OnAppThemeExtension.cs

This implements the runtime updating of AppTheme values.
- fixes #10391
Added:
- void BindableObject.SetOnAppTheme<T>(T Light, T Dark, T Default = default);
- void BindableObject.SetAppThemeColor(Color Light, Color Dark, Color Default = default);
The `INotifyPropertyChanged` was removed from the API. It doesn't make much sense to have that on there (anymore). People that were using that might see breaks.
Go to the right gallery page(s) and switch appearance

Runtime updating of AppTheme values

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10300.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs
Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs

I found that #9911 introduced a new concept of Reload the CollectionView if it wasn't visible and an update to the items was in progress.
Seems this approach doesn't work well when we push a modal on top of the CollectionView  and then on dispose we add/remove items from the CollectionView. This was actually preventing the item from being removed. So my first try was to remove the check for `_collectionViewController.View.Window == null` , this worked but was going around the real problem.
It seems that also the `_batchUpdating.WaitAsync()` on the Reload method isn't working as expected, it was getting stuck because there were no available threads on the `_batchUpdating` semaphore. The problem was after a BatchUpdates was executed (for example add a item) the semaphore wasn't releasing …

[iOS, Android] Fix when we call ReloadData on CollectionView, Fix issue adding item to start of Collection on ANdroid

---

Xamarin.Forms.Platform.Android/Extensions/ToolbarExtensions.cs

The spannable string coloring only appears to work on API >= 26
- Android
- run the platform tests on API 19,25,26,29 and whatever else will make you sleep better at night

Change API check to Oreo for coloring TextViews on ToolBar

---

Xamarin.Forms.Core.UnitTests/ShellTestBase.cs
Xamarin.Forms.Core.UnitTests/ShellTests.cs
Xamarin.Forms.Core/Shell/ShellItem.cs
Xamarin.Forms.Core/Shell/ShellSection.cs

If the user doesn't specify all elements in the hierarchy of a Shell
```XAML
<Shell
<ShellContent Route="route1"
<ShellContent Route="route2"
```
Then in code behind they should be allowed to do this
```C#
shell.CurrentItem = route2;
```
When a BaseShellItem is implicitly being converted up to a ShellItem these changes make it so if a BaseShellItem has already been parented than just return the parent instead of creating a new BaseShellItem
- fixes #10308 

If Shell Element is already wrapped up just return the implicit parent

---

Xamarin.Forms.Core/Registrar.cs
Xamarin.Forms.Platform.Android/Forms.cs
Xamarin.Forms.Platform.Tizen/Forms.cs

There is code that uses System.Reflection over a big list of these:
[assembly: StyleProperty("background-color", typeof(VisualElement), nameof(VisualElement.BackgroundColorProperty))]
Two changes here:
1. Let's make sure nothing happens at all if your app isn't using CSS.
2. I refactored a smidge to take advantage of `GetCustomAttributesSafe`.
Testing a Blank Forms app template on a Pixel 3 XL:
Before:
12-20 17:04:36.397  1490  1517 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +590ms
12-20 17:04:40.129  1490  1517 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +585ms
12-20 17:04:43.844  1490  1517 I ActivityTaskManager: Displayed …

[core] lazy load Assembly-level attributes for CSS

---

Xamarin.Forms.Platform.Tizen/Renderers/PageRenderer.cs

This PR is provide a way to handle when Page.ToolbarItems was opened or closed on Tizen Wearable devices
On Tizen wearable devices, ToolbarItems was represent as below
and It was opened when (...) was clicked 
And it will closed when toolbar item was clicked or back button was pressed.
We provide a virtual method to handle open and close on PageRenderer and App developer can use custom renderer and override default behavior
None
None
- Tizen
None
Not applicable

[Tizen] Provide way to handle when Page.ToolbarItems was opened/closed

---

Xamarin.Forms.Platform.UAP.UnitTests/BackgroundColorTests.cs
Xamarin.Forms.Platform.UAP/BoxViewBorderRenderer.cs

In the move from using a Rectangle to a Border for UWP's BoxView renderer, the Color property (which does the same thing as the BackgroundColor) was lost. This change restores that property.
- fixes #10535
None
- UWP
None
Not applicable
Automated test

Make Color property work on UWP BoxView

---

Xamarin.Forms.ControlGallery.Android/Nuget2019.Build.targets
azure-pipelines.yml
build.cake
build/provisioning/provisioning.csx
build/steps/build-android.yml
build/steps/build-nuget.yml
build/steps/build-osx.yml

- Add build 2017 stage so we can build android CG with 2017 to run through UI Tests
- update provisionator to use passed in URLS for sdks
- copy 2017 apk/ipas to separate folder for their own lane
- make sure test lanes all run successfully

Setup more specific 2017 apk/ipas for testing lanes

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6738.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellItemIsVisible.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
Xamarin.Forms.Core.UnitTests/ShellTests.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellItem.cs
Xamarin.Forms.Core/Shell/ShellSection.cs
Xamarin.Forms.Platform.Android/Renderers/ShellSectionRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellItemRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootHeader.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewController.cs

- re-adding items wasn't correctly resetting CurrentItem up the hierarchy
- don't propagate structure changes from items that aren't visible
- null check renderer on iOS in case it's already been disposed of
Changes aren't perfect. The Collections should more conservatively propagate themselves to the renderers while they are in flux, but that's a different PR for the next official release.
This should fix some additional rough edges on 4.6 for now
- iOS
- click around on the shell is visible tests

Set Current Item correctly after items cleared

---

Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
Xamarin.Forms.ControlGallery.iOS/_10337CustomRenderer.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10337.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs

We are using `UINavigationBar.Appareance` to infer settings that were already set to navigation bar in older versions of iOS. This way we don't break old Custom Renderers.
- fixes #10337 
- fixes #10338
None
- iOS
None
Launch Core Gallery and navigate to the Issue 10337. Verify that ShadowImage and BackIndicatorImage can be customized (in the sample we are hiding both).

[iOS] Fix NavBar issues on iOS 13

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/issue3262.cs
Xamarin.Forms.Core/WebView.cs
Xamarin.Forms.Platform.Android/Renderers/FormsWebViewClient.cs
Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs
Xamarin.Forms.Platform.UAP/WebViewRenderer.cs
Xamarin.Forms.Platform.iOS/Extensions/CookieExtensions.cs
Xamarin.Forms.Platform.iOS/Renderers/WebViewRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs
Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj

- UWP wasn't deleting cookies at all or updating cookies on refresh
- Android was just deleting all the cookies no matter what
- iOS was only deleting when cookies > 0
Determining how to do handle Cookies on each platform was different. This PR brings all the platforms in line. If the user never sets the Cookies property than nothing ever happens.
This PR also removes the API `ShouldManageCookies` which isn't public yet. Because if the CookieContainer is null that will already act as if `ShouldManageCookies` is set false. Android was the only platform that was totally destructive even when Cookies was null
This PR keeps the Cookies property in sync with the webview cookies. After the first load of a url the Cookies container (if set) will fill with cookies. At this point if you add/remove …

Make cookie handling consistent and non destructive

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8958.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8958.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems

The problem more than in the IndicatorView is in an error updating the position of the CarouselView. We did changes in the logic to update the CarouselView Position and CurrentItem from 4.4 to 4.6. The issue is fixed in 4.6. Therefore this PR only include a sample to validate the case. @rmarinho Should we update the logic related with CarouselView Position in 4.4 to fix the issue in a 4.4 release?. I have a branch prepared with those changes if necessary.
- fixes #8958 
None
- iOS
- Android
- UWP
None
Launch Core Gallery and navigate to the issue 8958. Change the CarouselView Position and verify that the IndicatorView position is updated too.

 IndicatorView not updating to current page when CarouselView is bound to custom DataType

---

Xamarin.Forms.Core/FontFile.cs

Just move FontFile.cs from Xamarin.Forms.Core namespace to Xamarin.Forms.
- fixes #10495
None
- Core
None
Not applicable

Fix FontFile namespace

---

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ExampleTemplates.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/TemplateCodeCollectionViewGallery.cs
Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs

On an orientation change, NavigationPageRenderer is calling the base layout method before actually updating the size information for the current page; this results in an extra layout pass with incorrect size information. In most cases, this is corrected by a later layout pass, but some controls which are still a valid size in the new constraints won't be remeasured and rearranged. This results in controls remaining portrait-sized and aligned to the left of the screen.
This change moves the layout update after the child control size updates.
- fixes #6869
None
- Android
None
Not applicable
With the device in portrait orientation, navigate to 
CollectionView Gallery -> DataTemplate Galleries -> Vertical List (Code)
Rotate the device to landscape. If the images are not centered or the red …

Finish updating Forms layout information before invoking native layout

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10134.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5470.cs

- Set the Page title to not match the tab title so when trying to detect if the tab title is off screen we don't keep getting the page title
- changed Issue5470 to not use async because it looks like the vsmac running has issues with void async and nunit
- just make sure ui tests pass

Add title to test and change async to Thread Sleep

---

Xamarin.Forms.Core/NamedPlatformColor.cs
Xamarin.Forms.Platform.iOS/Forms.cs

While implementing the platform dynamic colors I seem to have forgotten SystemOrange on iOS
N/A
None
- iOS
None
Not applicable
Use `GetNamedColor` to find the `systemOrange` color on iOS and see that it works!

Added OrangeColor

---

Xamarin.Forms.Core/PlatformConfiguration/TizenSpecific/Application.cs
Xamarin.Forms.Platform.Tizen/Renderers/ViewRenderer.cs

This PR enables you to know which view is currently interact with bezel.
It can be consumed from C# using the fluent API:
```cs
using Xamarin.Forms.PlatformConfiguration;
using Xamarin.Forms.PlatformConfiguration.TizenSpecific;
...
var view = Application.Current.On<Tizen>().GetActiveBezelInteractionElement()
```
> **Remark**
> Make sure that `GetActiveBezelInteractionElement()` returns null if `TargetIdiom` is not `Watch` or there is no active bezel interactive elements. As of now, only `CollectionView`, `ListView`, and `ScollView` in Xamarin.Forms are bezel-interactive view in the Samsung Galaxy Watch. When these views gain focus, `ActiveBezelInteractionElement` is set by default.
None
```namespace Xamarin.Forms.PlatformConfiguration.TizenSpecific```
Added:
- View …

[Tizen] Adds ActiveBezelElement to Application

---

Xamarin.Forms.Platform.iOS/Renderers/TabletShellFlyoutRenderer.cs

On an iPad the PresentsWithGesture is being incorrectly re-enabled when the flyout behavior was set to disabled
- iOS
- On an iPad run the store shell or go to the "shell Flyout Behavior" issue and play with disabling the flyout. Once you've disable it try to swipe it open with a gesture

PresentsWithGesture incorrectly toggled back to true when Flyout Disabled

---

azure-pipelines.yml
build/provisioning/provisioning.csx
build/steps/build-android.yml

- variables to set the android pool specifically
- increase the timeout of the osx job when running on devdiv
- change provisioning.csx to only use channels if sdks aren't specified
- add beta channel ios for local install
- make sure builds run

Increase pool timeout, provision less for osx builds, specify Android pools

---

Xamarin.Forms.Core/NamedPlatformColor.cs

Noticed a typo in one of the `NamedPlatformColor` identifiers
N/A
None
While this is in core, it only affects iOS 
- iOS
People that use the actual string value for this will now not get a color returned. But I guess if someone was using it like this they would've reported the weird looking identifier 🤷‍♂️
Not applicable
N/A

[iOS] Fix NamedPlatformColor typo

---

Xamarin.Forms.Controls/GalleryPages/AppThemeGalleries/AppThemeGallery.cs
Xamarin.Forms.Controls/GalleryPages/AppThemeGalleries/NamedPlatformColorGallery.cs
Xamarin.Forms.Core/NamedPlatformColor.cs
Xamarin.Forms.Platform.iOS/Forms.cs

Implements new `GetNamedColor` for macOS.
Additionally added a gallery page to show this _and_ added some OS version checks to prevent NREs
N/A
None
- macOS
- iOS
None
Not applicable
I have created a new gallery app that shows all the named colors for each platform, go there and check it out!

[macOS] Implement GetNamedColor

---

Xamarin.Forms.Core/PlatformConfiguration/TizenSpecific/Application.cs

Fix  the read-only bindable property `ActiveBezelInetractionElement` (introduced in #10644) correctly.
None
None
- Tizen
None

[Tizen] Make ActiveBezemElement as readonly

---

Xamarin.Forms.Platform.WPF/WPFPlatformServices.cs

Added a Null Reference Check on WPFPlatformServices IsInvokeRequired property.
Sometimes, on closing the app on WPF Platform, a null reference exception is thrown on IsInvokeRequired property on WPFPlatformServices, i've added a null reference check to that to prevent this exception from ocurring.
Changed:
public bool IsInvokeRequired
{
get { return System.Windows.Application.Current == null ? false : !System.Windows.Application.Current.Dispatcher.CheckAccess(); }
}
WPF
None
Not applicable

[WPF] Added null check on IsInvokeRequired on WPFPlatformServices.cs

---

Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs
Xamarin.Forms.Core/Application.cs

- I removed the Fake_Flags getting set because I think this had relevance before we had other flags we were setting. It's better to have the UI tests run with no flags set as that's the default
- Check for null flags inside `OnRequestedThemeChanged`
- fixes #10712 
- iOS
- Android
- UWP
- Run Control Gallery and rotate the device see if it crashes
- install the nuget into a clean app and rotate the device

Fix flag check inside OnRequestedThemeChanged

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10672.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10672.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/CollectionView/CarouselViewRenderer.cs
Xamarin.Forms.Platform.UAP/CollectionView/ScrollHelpers.cs

Fixed NullReferenceException resizing the Window using the CarouselView (getting the UIElement child to update the position).
- fixes #10672 
- fixes #10673 
- fixes #10674 (2 of 3 linked issues).
None
- UWP
None
Not applicable
Launch Core Gallery and navigate to the issue 10672. Then resize the Window size several times and verify that everything continue working as expected (no exception).

[UWP] Fix NRE resizing Window using CarouselView

---

Xamarin.Forms.Platform.MacOS/NativeToolbarTracker.cs

Fixed NavigationPage.BackButtonTitle for macOs
- fixes #10424 
None
- macOs
Now BackButtonTitle changes the back button text as it should.
See the test-cases attached to the original bug-ticket.

[Bug] NavigationPage.BackButtonTitle doesn't work with MacOS

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10110.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/CollectionView/StructuredItemsViewRenderer.cs

Fixed CollectionView EmptyView not working with Horizontal Layouts. The problem was that when using HorizontalLayout, UWP ListView did not implement `IEmptyView`.
- fixes #10110
None
- UWP
None
Launch Core Gallery and navigate to the Issue 10110. If you can see the EmptyView in Vertical and Horizontal CollectionView, the test has passed.

[UWP] Fix CollectionView EmptyView in Horizontal Layouts

---

build.cake

- Moved mono down to be the last sdk installed as it can mess up provisioning other sdks if it's updated too early
- Add cake provisioning task that will install all needed windows sdk
- Add cake provisioning task that will install all needed net framework sdks
- These only run when you're provisioning locally
- verify CI builds everything alright

Fix Mono provisioning on Cake to happen last

---

Xamarin.Forms.Platform.WPF/FormsTimePicker.cs

The TimeFormat can't be set to lower , because casing is important for example to get 24H values 
- fixes #10758
None
- WPF
Show allow to set a TimeFormat like HH:mm
Not applicable
add 
```
new TimePicker {
Time = new TimeSpan(19,00,00),
Format = "HH:mm"
}
```
And it should renderer 19:00

[WPF] Fix TimeFormat on TimePicker

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4714.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/VisualElementTracker.cs

UWP don't fire second `Tapped` event on double tap as documented here: [UIElement.DoubleTapped](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.doubletapped#remarks)
> If a user interaction also fires DoubleTapped, Tapped will fire first to represent the first tap, but the second tap won't fire an additional Tapped. 
To fix this and have the same behavior on all platforms, the `TapGestureRecognizer` is also called during the `DoubleTap` event.
- fixes #4714
None
- UWP
None
Not applicable
Launch Control Gallery on UWP and navigate to the Issue4714. Double tap on label. If the label text ends with 2, the test has passed.

[UWP] SingleTapGesture called once on DoubleTap

---

Xamarin.Forms.Platform.MacOS/EmbeddedFontLoader.cs
Xamarin.Forms.Platform.MacOS/Extensions/FontExtensions.cs
Xamarin.Forms.Platform.MacOS/Properties/AssemblyInfo.cs
Xamarin.Forms.Platform.MacOS/Xamarin.Forms.Platform.macOS.csproj

Added ExportFont implementation for mac OS
fixes issue #10360
- macOS
Control Gallery

[macOS] ExportFont functionality for macOS

---

Xamarin.Forms.Platform.Android/Renderers/MotionEventHelper.cs

Fixes NullReferenceException that was reported by our Application Monitoring solution Raygun. Unfortunately we were never able to reproduce this but adding this null check fixed the exception for us.
None
Android
None
Not applicable
Tested by implementing the fix into custom XF nuget package and verifying that exception is not thrown anymore.

Fixing NullReferenceException in MotionEventHelper for Android

---

Xamarin.Forms.Core.UnitTests/ShellTestBase.cs
Xamarin.Forms.Core.UnitTests/ShellTests.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellItem.cs

When using a TabBar or FlyoutItem the implicit behavior of the Flyout is different on one vs the other. This was implemented by just setting the attached property on the Item. The problem with doing it that way is that it doesn't let the user set the FlyoutItem at the Shell level
- Play with setting in Control Gallery

Use FlyoutBehavior on Shell if user sets it

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8870.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewLayout.cs
Xamarin.Forms.Platform.iOS/CollectionView/GroupableItemsViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/HeightConstrainedTemplatedCell.cs
Xamarin.Forms.Platform.iOS/CollectionView/HorizontalDefaultCell.cs
Xamarin.Forms.Platform.iOS/CollectionView/HorizontalDefaultSupplementalView.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
Xamarin.Forms.Platform.iOS/CollectionView/TemplatedCell.cs
Xamarin.Forms.Platform.iOS/CollectionView/VerticalDefaultCell.cs
Xamarin.Forms.Platform.iOS/CollectionView/VerticalDefaultSupplementalView.cs
Xamarin.Forms.Platform.iOS/CollectionView/WidthConstrainedTemplatedCell.cs
Xamarin.Forms.Platform.iOS/VisualElementPackager.cs

The iOS CollectionView controller and layout have a race condition during rotation where the controller can generate a cell for layout while the layout is in prototyping mode. Because the prototype cell isn't properly constrained, if it contains a control which happens to return zero-width measurements in the right circumstances (e.g., a `Label` with `TextType.Html`) the UICollectionView's layout process can hang, which either hangs or crashes the entire application.
This change eliminates the issue and prevents the application hang/crash.
- fixes #8870
None
- iOS
None
Not applicable
Automated test (8870)

Prevent crash/hang when rotating CollectionView with HTML Labels

---

Xamarin.Forms.Platform.Android.UnitTests/ToolbarExtensionsTests.cs
Xamarin.Forms.Platform.Android/Extensions/ToolbarExtensions.cs

In 4.6 we improved the Menu Item tinting to use a SpannableString instead of searching for a textview but this caused the default foreground color (white) to get applied to the secondary menu items. Which causes white on white text for the secondary menu.
- fixes #10617 
- Android
- test included

Don't apply foreground color to secondary menu items

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10744.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs
Xamarin.Forms.Platform.UAP/WebViewRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs

- when creating a url for cookies just parse it down to 2000 characters if it's over 2000 characters so that new Url() doesn't throw an exception
- stop firing navigating on android for eval requests. Android was the only platform firing Eval
- UWP I added a try catch for the InvokeScript since it's async/void to avoid total failure
- fixes #10744
- iOS
- Android
- UWP
- When you call EVAL on Android it will no longer fire the navigating event which brings it inline with ios and uwp

Parse URL  for cookie processing just in case URL is too long

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Controls/XamStore/Views/StorePages.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellAppearance.cs
Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRenderer.cs
Xamarin.Forms.Platform.UAP/Shell/ShellRenderer.cs
Xamarin.Forms.Platform.UAP/Shell/ShellSplitView.cs
Xamarin.Forms.Platform.UAP/Shell/ShellStyles.xaml
Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/SlideFlyoutTransition.cs

Add Flyout Backdrop Color to Shell Appearance structure so users can change the color of the overlay
The attached property only takes hold when applied to Shell and ShellItem
This also makes the behavior of closing the flyout when clicking off the flyout on iOS more reliable
Added:
- Color ShellAppearance.FlyoutBackdropColor
- Shell.FlyoutBackdropColor // Attached Property
None
- iOS
- Android
- UWP 
On iOS there is a subtle change for the Default Behavior. The opacity is now animated by default whereas before the opacity was just set immediately when the progress > 0
Play with the added BackdropColor button on the Store Shell

Add FlyoutBackdrop Color for Shell

---

Xamarin.Forms.Core.UITests.Shared/Tests/CarouselViewUITests.cs
Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs

Fix a regression when trying to set initial position , 
We should only set the variable `_gotoPosition`  if we need to scroll to the position.
- fixes #10745 
None
- Android
should be able to go change the CurrentItem and have the item scroll to it
Not applicable
Added UITest - `CarouselViewGoToNextCurrentItem`

[Android] Fix changing CarouselView using CurrentItem

---

Xamarin.Forms.Core/ResourceDictionary.cs

[C] avoid unnecessary allocation in RD
- fixes #10834
None
None
Not applicable

[C] avoid unnecessary allocation in RD

---

Xamarin.Forms.Core/Application.cs
Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs

The event `Xamarin.Forms.Application.RequestedThemeChanged` is fired when the device rotates. 
Fire the event `Xamarin.Forms.Application.RequestedThemeChanged` only when the theme change
- fixes #
none
- Android
None
Not applicable
- On the App.cs subscribe to the event `Xamarin.Forms.Application.RequestedThemeChanged`
- Rotate the device
- The event will be fired

On requested theme changed android

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9827.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9827.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs
Xamarin.Forms.Platform.Android/CollectionView/IndicatorViewRenderer.cs
Xamarin.Forms.Platform.Android/CollectionView/RecyclerViewScrollListener.cs
Xamarin.Forms.Platform.Android/Extensions/RecyclerExtensions.cs

A couple of fixes, getting the real centered item. If we were using the PeakAreaInsets there were some times that center item wasn't found since it was using just 1 centered coordiante, it should use both, x and y for CarouselView.
Fix state that was blocking update CurrentItem when swiping. Fix introduced in 4.6.0 to fix scrolling to the item when added was blocking the current item to be update when swiping.
Contains also fix #10838 
- fixes #9827 
- fixes #10775
None
- Android
None
Not applicable
Go to test case 9827, swipe to next item, check the SearchBar text is updated to "Item1 with some additional text"

[Android] Update CurrentItem when swiping

---

Xamarin.Forms.Platform.MacOS/Renderers/SliderRenderer.cs

Guard a couple of colors in the min and max track colors for Slider because they are only available on Mojave (10.14) and up
The color usage here need to be updated when #8864 is implemented
- fixes #10581
None
- macOS
None, fix NRE while running on pre-10.14 macOS
Not applicable
Ideally test on macOS pre10.14 and see it doesn't crash

[macOS] Fix NRE when using Slider min/mac track color

---

Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs

After doing some tests I have not been able to reproduce the issue. Probably the problem is that the Context is null. This PR avoids the crash in this case.
- fixes #10854 
None
- iOS
None
Not applicable

[iOS] Fix crash using an empty button image (unverified)

---

build.cake

Updating mono while the cake script is running can cause issues for later sdks. 
This moves mono to being installed last which fixes occasional CI errors
- make sure this builds on devdiv and public

Provision Mono Last to fix CI provisioning errors

---

Xamarin.Forms.Platform.UAP/CollectionView/StructuredItemsViewRenderer.cs

Fixed incorrect CollectionView item padding on UWP.
- fixes #10547 
None
- UWP
None
Launch Core Gallery and navigate to the CollectionView samples gallery. Select the "Datatemplate Gallery" and verify that the red background color of every CollectionView Item have no spaces left or right.

[UWP] Fixed incorrect CollectionView item padding

---

Xamarin.Forms.Core/ColumnDefinitionCollectionTypeConverter.cs
Xamarin.Forms.Core/Grid.cs
Xamarin.Forms.Core/RowDefinitionCollectionTypeConverter.cs
Xamarin.Forms.Xaml.UnitTests/DefinitionCollectionTests.xaml
Xamarin.Forms.Xaml.UnitTests/DefinitionCollectionTests.xaml.cs

Simplify Grid Column and Row Definitions by using markup extensions.
- fixes #7302
- closes #4997
Added:
- ColumnDefinitionCollectionTypeConverter
- RowDefinitionCollectionTypeConverter
None
Not applicable

[X] TypeConverter on Grid Col/Row Definitions

---

Xamarin.Forms.Core.UnitTests/ShellTestBase.cs
Xamarin.Forms.Core.UnitTests/ShellTests.cs
Xamarin.Forms.Core/Page.cs
Xamarin.Forms.Core/Shell/Shell.cs

Propagate OnBackButtonPressed from Shell down to currently displayed page
- fixes #7072
- iOS
- Android
- UWP

Fire OnBackButtonPressed on the currently Displayed Page

---

Xamarin.Forms.Platform.iOS/Extensions/ColorExtensions.cs

Using the right value with the right overload in `UIColor.FromRGBA(255, 0, 0, 255);` to make ContextAction.IsDestructive red again on pre-iOS13.
- fixes #10612 
None
- iOS
None
Not applicable
Go to the ContextActions gallery page on a pre-iOS13 device and notice that the destructive ones have a red background once more

[iOS] Reinstate ContextAction IsDestructive red bg

---

Xamarin.Forms.Core.UnitTests/StyleTests.cs
Xamarin.Forms.Core/Style.cs

Creating styled elements off of the main thread can, in the right circumstances, crash when the Style attempts to clean up references to old elements which are no longer in use. This change makes the cleanup of the old reference thread-safe to avoid crashing.
- fixes #10561
None
None
Not applicable
Unit test

Prevent styled element creation off the main thread from crashing application

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9833.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs

Propagate CollectionView BindingContext to EmptyView.
_NOTE: Tested on Android and iOS and it is working correctly._
- fixes #9833
None
- UWP
None
Launch Core Gallery and navigate to the Issue 9833. Verify that the EmptyView BindingContext is not null.

[UWP] Propagate CollectionView BindingContext to EmptyView

---

Xamarin.Forms.Controls/GalleryPages/ExpanderGalleries/ExpanderGallery.xaml
Xamarin.Forms.Controls/GalleryPages/ExpanderGalleries/ExpanderGallery.xaml.cs
Xamarin.Forms.Core/Expander.cs

Change the visual appearance of disabled Expander
- fixes #10362 
None
- Core
The disabled state of Expander is different from the regular one.
Now Disabled Expander looks grayed out.
Set IsEnabled to False fo expander and compare enabled and disabled expanders.

[Bug] Disabled Expander doesn't change its visual appearance

---

Xamarin.Forms.Platform.Tizen/Renderers/ButtonRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/ImageButtonRenderer.cs

This PR is improving image loading from file for `Button.ImageSource` and `ImageButton.Source`.
In Tizen, sync file image loading is 2 to 3 times faster than async file image loading.
None
None
- Tizen
None

[Tizen] Load image sync in case of FileImageSource

---

Xamarin.Forms.Platform.Tizen/Native/ListView.cs
Xamarin.Forms.Platform.Tizen/Native/Watch/WatchListView.cs
Xamarin.Forms.Platform.Tizen/Renderers/ListViewRenderer.cs

This PR fixes Header/Footer padding issue on Tizen Wearable device
- A first Item of ListView was not selected on Tizen Wearable devices
Internal API was changed
Changed:
- bool Native.ListView.HasHeader() => bool Native.ListView.HasHeaderContext()
- bool Native.ListView.HasFooter() => bool Native.ListView.HasFooterContext()
- void Native.ListView.RemoveHeader() => void Native.ListView.RemoveHeaderItemContext()
- void Native.ListView.RemoveFooter() => void Native.ListView.RemoveFooterItemContext()
Added:
- void UpdateHeader();
- void UpdateFooter();
- Tizen
None
Not applicable

[Tizen] Fix ListView header/footer padding issue

---

Xamarin.Forms.Build.Tasks/XamlGTask.cs
Xamarin.Forms.Build.Tasks/XamlGenerator.cs

no longer crash on missing XmlnsDefinitionAttribute
Report StackTrace on XamlG failures (verbose mode)
- fixes #10777
None
Not applicable

[X] Better error handling and reporting in XamlG

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8836.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/EntryRenderer.cs
Xamarin.Forms.Platform.UAP/FormsTextBox.cs
Xamarin.Forms.Platform.UAP/FormsTextBoxStyle.xaml

Modifies the UWP EntryRenderer, FormsTextBox and FormsTextBoxTemplate to support optionally hiding the Delete Button as support by the other platforms.
Method used to implement this is to extract the ButtonVisible visual state and remove it from the control template when the entry is set to not display the delete button.  If it is changed back the ButtonVisible state is added back to the control template.
- Fixes #8836
None
- UWP
Delete button will be shown or not shown based on the Entry's ClearButtonVisibility value.
Default Behavior
Updated behavior when clear button is set to never
Open the issue 8836 page in the control gallery and follow the instructions.  Just clicking the toggle button will flip the state back and forth.

[Bug] Fix ClearButtonVisibility.Never does not take effect on UWP

---

Xamarin.Forms.Platform.UAP/CollectionView/SelectableItemsViewRenderer.cs

Navigating away from a page on UWP with a CollectionView which has selected items is crashing.
This change adds the missing null check to prevent that.
None
- UWP
None
Not applicable
Navigate to Control Gallery -> CollectionView Galleries -> Selection Galleries -> Multiple Selection, Bound. Then navigate back. If the app doesn't crash, this fix is working.

Add null check when tearing down element in UWP SelectableItemsViewRenderer

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10909.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/TimePickerRenderer.cs

Open DatePicker and TimePicker Popup getting the focus on UWP. In this way the behavior is the same as in Android and iOS.
- fixes #10909 
None
- iOS
- Android
- UWP
Not applicable
Launch Core Gallery and navigate to the issue 10909. If pressing the buttons opens the popup of both DatePicker and TimePicker, the test has passed.

[UWP] Open DatePicker and TimePicker Popup getting the focus

---

Xamarin.Forms.Platform.Tizen/Cells/CellRenderer.cs
Xamarin.Forms.Platform.Tizen/Native/ListView.cs
Xamarin.Forms.Platform.Tizen/Native/Watch/WatchListView.cs

This PR adds extension point of `CellRenderer` for the sake of extensibility. In addition, it fixes footer related bug.
None
```namespace Xamarin.Forms.Platform.Tizen```
Added:
- void CellRenderer.OnCreated()
- void CellRenderer.SendCreatedCell();
- Tizen
None
Not applicable

[Tizen] Update the CellRenderer for extensibility

---

Xamarin.Forms.Core/Stepper.cs

Made StepperPositionProperty field public for Stepper control
- fixes #10148
Changed:
private static readonly BindableProperty StepperPositionProperty => public static readonly BindableProperty StepperPositionProperty 

[Enhancement] Public StepperPositionProperty 

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla32871.cs

The output of this test on API27 was causing the xml to be bad generated. And only reporting back just the first 38 tests.
- none
None
- Android
None
Not applicable
API27 regressions test run should show more than 38 tests

[UITests] Comment out  Bugzilla32871 

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/VisualControlsPage.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/VisualControlsPage.xaml.cs
Xamarin.Forms.Material.Android/MaterialButtonRenderer.cs
Xamarin.Forms.Platform.Android/VisualElementPackager.cs

When you set the material button to disabled the Elevation on it gets set to zero. AFAICT if you set it to disabled before it draws then it looks like a shadow still gets drawn on the parent control even though the elevation is zero. On the test case if you remove the button that's on the left the issue doesn't happen. If you make a change the XAML so it reloads the control then on the second load the button looks fine. It looks like a very specific timing issue. 
With this change if a control is initialized as disabled then I delay setting it to disabled until the first draw and then I set it to disabled. 
Before
After
- I've included a manual test

Fix incorrect shadow draw with disabled button

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7856.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7856_1.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7856_1.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellBackButtonBehavior.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs

- fixes #7856
None
- iOS
It now shows back button behaviours as it should.
Create a Shell and with one page and set BackButton Override. Navigate to another page and check that the back button is shown as you overrode it.
Video:
[7856.mp4.zip](https://github.com/xamarin/Xamarin.Forms/files/3978657/7856.mp4.zip)

7856 - Shell BackButtonBehaviour TextOverride breaks back navigation

---

Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
Xamarin.Forms.Build.Tasks/XamlCTask.cs
Xamarin.Forms.Xaml.UnitTests/Issues/Gh10803.xaml
Xamarin.Forms.Xaml.UnitTests/Issues/Gh10803.xaml.cs
Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
Xamarin.Forms.Xaml/CreateValuesVisitor.cs
Xamarin.Forms.Xaml/XamlLoader.cs

Register SourceInfo before triggering VisualStateChanged events.
Note that this flips a coin on a previously sketchy behaviour for types being ValuesProvider. Before this the value provided was registered (but doesn't match to any actual xaml element), now the xaml element is registered (and it doesn't match objects in the visual tree). This affects very little real life cases anyway.
previous behaviour was to register source info on the actual binding, now this will 
- fixes #10803
None
None
Not applicable
> VS bug [#1135102](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1135102)

[HR] register sourceinfo before triggering change

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10699.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/RefreshViewRenderer.cs

We were removing the RefreshControl from the SuperView but not clearing the `RefreshControl` property on the `UIScrollView`, 
- fixes #10699 
None
- iOS
None
Not applicable
RefreshView should work after disable and enable it on ScrollView.
Gto to Issue 10699
Pull to refresh
Uncheck and check the checkox (this will toggle the RefreshView to Disable and Enable)
Try Pull to refresh again

[iOS] Fix disable and enable RefreshView

---

Xamarin.Forms.Platform.Tizen/Cells/SwitchCellRenderer.cs

This PR improves `SwitchCell` performance by caching the item for reuse. As a result, the scrolling performance of `ListView` using `SwitchCell` has been improved from about 20~30 FPS to about 60 FPS. (when measured on a Galaxy Watch).
None
None
- Tizen
None
Not applicable

[Tizen] Improve the SwitchCell performance

---

Xamarin.Forms.Platform.iOS/CollectionView/GroupableItemsViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs

On iOS 10 the UICollectionViewFlowLayout erroneously attempts to retrieve layout attributes for supplementary views (i.e., group headers and footers) when we retrieve supplementary cells in order to measure the header/footer sizes. This crashes. 
These changes avoid that situation by manually constructing measurement cells for headers and footers on iOS 10 and skipping the dequeue method during measurement entirely.
Side benefit: this also fixes an issue where group headers/footers on iOS 10 would initially layout out at 0,0 instead of above/below their groups.
- fixes failing test for Issue 9686 on 4.7.0.
None
- iOS
None
Not applicable
Automated test 9686.

Avoid using the dequeue mechanism to retrieve header/footer measurement cells on iOS 10

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9711.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9711.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs

Crash appears to be occurring due to the premature disposal of a `HeaderWrapperView` instance.
Crash occurs in `VisualElementRenderer::UpdateParentPageAccessibilityElements()`. As it walks up the superview chain from the `UILabel` that was tapped on in the test, it arrives at a superview whose `NSObject` cannot be retrieved. That superview happens to be a `HeaderWrapperView` instance. In `Runtime.cs:1249`, the call to `TryGetNSObject()` to retrieve this `HeaderWrapperView` returns `null`.  In the debugger, I manually called `TryGetNSObject()` with `true` for the `evenInFinalizerQueue` parameter, which returned the expected instance -- confirming that the instance has been unexpectedly garbage collected.
The resulting exception claims that it was not "possible to create a new managed …

Fix #9711 Failed to marshal HeaderWrapperView

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10961.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7015.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/ImageElementManager.cs
Xamarin.Forms.Platform.UAP/ImageRenderer.cs

The placeholder image changes broke local image loading on UWP; these changes:
- use the local image loading error handler to load the error image
- a check for a null return from a remote image and display the error image
which makes the error/loading placeholder images work while also allowing local images to load.
- fixes #10961
None
- UWP
None
Not applicable
Control Gallery Issues 7015 and 10961

Fix local image loading on UWP

---

Xamarin.Forms.Platform.UAP/CollectionView/FormsListView.cs

Changed default ScrollBarVisibility in CollectionView on UWP. 
In FormsGridView the default value of `VerticalScrollBarVisibility` is `Auto` while in FormsListView it is `Visible` (it will always be visible, even when it is not necessary). This PR changes the FormsListView behavior to be the same as FormsGridView.
- fixes #10817
None
- UWP
None
Not applicable
Launch Core Gallery and navigate to the CollectionView galleries. Select a gallery with a small number of items (scroll no necessary). Verify that the scroll is not visible if is not necessary by default.

[UWP] Changed default ScrollBarVisibility in CollectionView

---

Xamarin.Forms.Core.UnitTests/BindingUnitTests.cs
Xamarin.Forms.Core/BindingExpression.cs
Xamarin.Forms.Core/TypedBinding.cs

[C] Catch typeconverter exceptions on bindings
this doesn't apply to TypedBindings as you wouldn't be able to create a typed binding in this situation
- fixes #10405

[C] Catch typeconverter exceptions on bindings

---

Xamarin.Forms.Controls/GalleryPages/AppThemeGalleries/AppThemeXamlGallery.xaml

Fixed issue with nonexistent resource in AppTheme XAML sample. MyColor was:
<AppThemeColor x:Key="MyColor" Light="HotPink" Dark="Yellow" />
And now, this has changed. Changed to use `AppThemeBinding`.
- fixes #10968
None
None
Not applicable
Launch Core Gallery and navigate to the AppThemes Galleries. Select the AppTheme XAML Gallery and verify that the Label is using different colors by theme.

Fixed issue with nonexistent resource in AppTheme XAML sample

---

Xamarin.Forms.Core/Shapes/RectangleGeometry.cs

Using `RectangleGeometry` instantiated an incorrect `Rectangle` type (shape vs struct type).
None
None
Launch Core Gallery and navigate to the Shapes Gallery. Select the Clip sample and verify that everything works without problems.

Fixed wrong Rectangle type used in RectangleGeometry (Shapes)

---

Xamarin.Forms.Core.UnitTests/ShellModalTests.cs
Xamarin.Forms.Core.UnitTests/ShellUriHandlerTests.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellUriHandler.cs

- Fix the check that prevents relative routes to shell parts so that it correctly takes into account contextual routes
- collapse the route path down when using a contextual route
for example if I am at
`//Animals/monkeys` 
And there's a registered route with
`monkeys/details`
Then the route path should be 
`//Animals/monkeys/details` 
- fixes #10970

Fix check for contextual routing with global pages

---

Xamarin.Forms.Core/MultiBinding.cs

[C] MultiBinding throw on missing conv or format
throw if none of StringFormat or Converter are assigned.
- fixes #11019
None
None
Not applicable

[C] MultiBinding throw on missing conv or format

---

Xamarin.Forms.Core.UITests.Shared/PlatformQueries.cs
Xamarin.Forms.Core.UITests.Shared/Queries.cs
Xamarin.Forms.Core.UITests.Shared/Tests/RadioButtonUITests.cs
Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs
Xamarin.Forms.Core.UITests.Shared/Xamarin.Forms.Core.UITests.projitems
Xamarin.Forms.Platform.iOS/Renderers/RadioButtonRenderer.cs

Adds a preserve attribute to `RadioButtonRenderer` so it doesn't crash when linking is enabled. Additionally adds a UI test that loads the gallery to make sure this never ever happens again.
- fixes #10868
None
- iOS
None
Not applicable
If the UI Test runs is successful and the RadioButton test is actually in there, hooray! It worked! You might double check by taking the NuGets and add them to a new project where linking is enabled

[iOS] Add preserve to RadioButton

---

Xamarin.Forms.Controls/GalleryPages/AppThemeGalleries/AppThemeCodeGallery.cs
Xamarin.Forms.Core.UnitTests/AppThemeTests.cs
Xamarin.Forms.Core/AppThemeBinding.cs
Xamarin.Forms.Core/VisualElementExtensions.cs
Xamarin.Forms.Xaml/MarkupExtensionParser.cs
Xamarin.Forms.Xaml/MarkupExtensions/AppThemeBindingExtension.cs

the internal OnAppTheme class name was confusing, and not indicating
what it actually was (a binding). renaming to AppThemeBinding makes
sense.
also dropping the generic arg as it's not really used.
None
None
Not applicable

[C/X] rename and ungenerify OnAppTheme

---

.nuspec/Xamarin.Forms.targets
Xamarin.Forms.Build.Tasks/XamlGenerator.cs
Xamarin.Forms.Controls/GalleryPages/ShapesGalleries/EllipseGallery.xaml
Xamarin.Forms.Xaml.UnitTests/Issues/GH2691.xaml.cs
Xamarin.Forms.Xaml.UnitTests/MSBuild/MSBuildTests.cs
Xamarin.Forms.Xaml.UnitTests/XamlgTests.cs

[X] fix error with x:Name on shapes
None
None
Not applicable

[X] fix error with x:Name on shapes

---

Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
Xamarin.Forms.ControlGallery.Android/_10940CustomRenderer.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10940.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems

CustomRenderer object was created twice for single control when add custom control in SwipeView item. The issue is present in Xamarin.Forms 4.5 but fixed since the last 4.6 version. This PR therefore only adds the sample test to Core Gallery.
- fixes #10940 
None
- Android
None
Launch Core Gallery and navigate to the issue 10940. Verify that the `CustomEntry` is only created once when opening the SwipeView.

[Android] CustomRenderer object was created twice using SwipeView

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11031.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS.UnitTests/BackgroundColorTests.cs
Xamarin.Forms.Platform.iOS.UnitTests/CornerRadiusTests.cs
Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs

Fix `BackgroundColor` issue with Frame on iOS.
Caused by #11001 and #10469
- fixes #11031
None
- iOS
None
Launch Core Gallery and navigate to the issue 11031. Verify that the Frame BackgroundColor is clipped by the CornerRadius.

[iOS] Fix BackgroundColor issue with Frame

---

Xamarin.Forms.Platform.Tizen/Renderers/PageRenderer.cs

This PR allows you to add/remove the ToolbarItem to the page at runtime on the Tizen wearable devices.  
None
None
- Tizen
None

[Tizen] Enhance the Page.ToolbarItem

---

Stubs/Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS (Forwarders).csproj
Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
Xamarin.Forms.Maps.iOS/Xamarin.Forms.Maps.iOS.csproj
azure-pipelines.yml
build.cake
build/provisioning/provisioning.csx
build/steps/build-android.yml
build/steps/build-osx.yml
build/steps/build-windows.yml

- add missing parameters to android yaml task
- fix ios build to use release configuration correctly
- fix cg-ios cake build
- switch yaml to use cake for ios CG build
- set MtouchExtraArgs to linkout out forms by default so things are caught quicker during development
- added a few additional .net sdks to the provisioning installer file
- make sure cg android tests run
- make sure cake build works from command line

Add additional parameters to android build and fix iOS cake build

---

Xamarin.Forms.Core.UnitTests/MultiBindingTests.cs
Xamarin.Forms.Core/MultiBinding.cs

Convert values (and fallback) to target type to avoid cast exception (like BindingExpression is doing)
- fixes #11058
None
None
Not applicable

[C] convert value on multibindings before apply

---

Xamarin.Forms.Core/Shapes/FillRule.cs
Xamarin.Forms.Core/Shapes/PenLineCap.cs
Xamarin.Forms.Core/Shapes/PenLineJoin.cs
Xamarin.Forms.Platform.Android/Shapes/ShapeRenderer.cs
Xamarin.Forms.Platform.UAP/Shapes/ShapeRenderer.cs
Xamarin.Forms.Platform.iOS/Shapes/ShapeRenderer.cs

Moved classes to Xamarin.Forms.Shapes:
- `FillRule`
- `PenLineCap`
- `PenLineJoin`
(Also moved to the Shapes folder)
None
None
Not applicable

Moved classes to Xamarin.Forms.Shapes

---

Xamarin.Forms.Platform.WPF/FormsPanel.cs
Xamarin.Forms.Platform.WPF/Renderers/EntryRenderer.cs
Xamarin.Forms.Platform.WPF/WPFPlatformServices.cs

Implements CursorPosition on WPF Platform
Fixes #10548 Entry.CursorPosition not implemented on WPF
Modify EntryRenderer.cs on WPF Platform to include CursorPosition Property Changes
OnElementChanged()
{
Control.SelectionChanged += TextBoxOnSelectionChanged;
UpdateCursorPosition();
}
OnElementPropertyChanged()
{
else if (e.PropertyName == Entry.CursorPositionProperty.PropertyName)
UpdateCursorPosition();
}
void TextBoxOnSelectionChanged(object sender, RoutedEventArgs e)
{
if (Control != null && Element != null)
Element.CursorPosition = Control.CaretIndex;
}
void UpdateCursorPosition()
{
if (Control.CaretIndex != Element.CursorPosition)
Control.CaretIndex = Element.CursorPosition;
}
- WPF
None
Not applicable
- Add an Entry to a Xamarin.Forms Project;
- Run WPF platform;
- Add some text to …

[WPF] Implements CursorPosition on WPF Platform

---

Xamarin.Forms.Core.UnitTests/StyleTests.cs
Xamarin.Forms.Core/Style.cs

If a Style is removed off of the UI thread, it's possible to create a situation where the Style.Unapply method throws a NullReferenceException when accessing a WeakReference.
This change adds a null check to avoid the exception.
- fixes #10697
None
None
Not applicable
Unit test `ApplyAndRemoveStyleOffMainThreadShouldNotCrash()`.

Null check WeakReference in UnapplyStyle

---

Xamarin.Forms.Platform.iOS/Renderers/MediaElementRenderer.cs

When video playing to end. It will check IsLooping to play again or not.
But if we pop page or something else that release MediaElement when video almost play to end.
MediaElementRender will still receive IOS event to call `PlayedToEnd`, and there is no null check.
Then a null reference exception will throw when access `Element.IsLooping`.
- fixes #11071 
None
- iOS
None
Not applicable
Launch Core Gallery and navigate to the MediaElement Gallery. Reproduce the video and move the position almost at the end. Then, navigate back. Without any exception the test has passed.

[iOS] Fix exception checking Element.IsLooping 

---

.nuspec/Xamarin.Forms.targets
Xamarin.Forms.Build.Tasks/XamlGenerator.cs
Xamarin.Forms.Xaml.UnitTests/MSBuild/MSBuildTests.cs

- regressed by #11021 
- fixes #11101
None
None
Not applicable

[X] find xmlns in Core at design time

---

Xamarin.Forms.Platform.UAP.UnitTests/ShellTests.cs
Xamarin.Forms.Platform.UAP.UnitTests/Xamarin.Forms.Platform.UAP.UnitTests.csproj
Xamarin.Forms.Platform.UAP/Shell/ShellRenderer.cs
Xamarin.Forms.Platform.UAP/Shell/ShellSplitView.cs

When initializing shell with the flyoutbehavior set to locked the `LightDismissLayer` doesn't exist
- fixes #11096 
- UWP
- added unit test
- click around in the store shell

Null check for LightDismissLayer on UWP Shell

---

Xamarin.Forms.Platform.iOS.UnitTests/AssertionExtensions.cs
Xamarin.Forms.Platform.iOS.UnitTests/ColorComparison.cs
Xamarin.Forms.Platform.iOS.UnitTests/HtmlLabelTests.cs
Xamarin.Forms.Platform.iOS.UnitTests/Xamarin.Forms.Platform.iOS.UnitTests.csproj
Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs

Setting AttributedText on a UILabel clears out other formatting properties. So when a user sets the `TextColor` and `Font` properties of a `Label` and subsequently sets the `Label`'s `TextType` to HTML, the properties are wiped out. 
This change re-applies the TextColor and Font properties (if they have been set) after setting the HTML text. 
- fixes #10588
None
- iOS
None 
Not applicable
Automated platform tests.

Retain TextColor and Font properties when using HTML Label on iOS

---

Xamarin.Forms.Platform.iOS/ContextActionCell.cs

Fix NRE clearing ListView ContextActions on iOS.
- fixes #10934 
None
- iOS
None
Not applicable

[iOS] Fix NRE clearing ListView ContextActions 

---

Xamarin.Forms.Core/Shapes/Matrix.cs

```
Facilitate the use of Matrix (Intellisense). Example:
<Path>
<Path.RenderTransform>
<MatrixTransform>
<MatrixTransform.Matrix>
<Matrix OffsetX="10"
OffsetY="100"
M11="3"
M12="2" />
</MatrixTransform.Matrix>
</MatrixTransform>
</Path.RenderTransform>
</Path>
```
- fixes #11088
Remove _EditorBrowsableState.Never_ from `Matrix` struct.
None
Not applicable
Can use Intellisense creating something like:

 Remove EditorBrowsableState.Never from Matrix struct

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9929.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SpacingGalleries/SpacingGallery.cs
Xamarin.Forms.Platform.iOS/CollectionView/GridViewLayout.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs

Setting the item spacing in a GridItemsLayout on iOS can cause the CollectionView to throw an internal consistency exception because the spacing forces the individual item size below zero.
These changes prevent the actual layout size of the items from going below zero, even if the item spacing is set to a very large value.
- fixes #9929
None
- iOS
None
Not applicable

[iOS] Prevent CollectionView exception when item spacing is too large 

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11106.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/VisualElementTracker.cs

Fix interaction issue with ScrollView on UWP.
- fixes #11106 
- fixes #11174 
None
- UWP
None
Launch Core Gallery and navigate to the issue 11106. Scroll to the end and try to set focus to the last Entry. If you can tap the Entry and set the focus, the test has passed.

[UWP] Fix interaction issue with ScrollView

---

Xamarin.Forms.Core.UnitTests/ShellTestBase.cs
Xamarin.Forms.Core.UnitTests/ShellTests.cs
Xamarin.Forms.Core/Page.cs
Xamarin.Forms.Core/Shell/Shell.cs

The logic for interpreting SendBackButtonPressed needs to be inverted. Currently it's treating false as handled.
- fixes #7072

Invert logic for SendBackButtonPressed on Shell

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11107.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/ShellItemRenderer.cs

Update the tab bar visibility before the layout of the subviews
- fixes #11107
- fixes #10126
- iOS
- test tab bar visibility in CG

Update the tab bar visibility before the layout of the subviews

---

Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs
Xamarin.Forms.ControlGallery.Android/Issue10182Activity.cs
Xamarin.Forms.ControlGallery.Android/MultiWindowService.cs
Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10182.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Controls/IMultiWindowService.cs
Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
Xamarin.Forms.Platform.Android/AppCompat/Platform.cs

If the MainPage is set while the app is paused, then Android delays setting the actual page at the platform level and just delays it until the app is actually resumed
https://github.com/xamarin/Xamarin.Forms/blob/b5b6f85a46b738f2682cfa1d5ce4dadddc8e00a8/Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs#L400
If this combination of events happens
- new main page set
- app paused
- new main page set
- app resumed
Then the previous app model wasn't being cleaned up properly
- fixes #10182
- Android
- still need to figure this out. Creating PR so I can give people a nuget to test

Call Setting Page if SetPage has been delayed

---

Xamarin.Forms.Platform.iOS/Shapes/EllipseRenderer.cs
Xamarin.Forms.Platform.iOS/Shapes/LineRenderer.cs
Xamarin.Forms.Platform.iOS/Shapes/PathRenderer.cs
Xamarin.Forms.Platform.iOS/Shapes/PolygonRenderer.cs
Xamarin.Forms.Platform.iOS/Shapes/PolylineRenderer.cs
Xamarin.Forms.Platform.iOS/Shapes/RectangleRenderer.cs

Recently we set the  experimental linker flag: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj#L18
This PR add a default constructor in the Shapes renderer with a preserve attribute to avoid any issue.
Example: 
`System.MissingMethodException: Default constructor not found for type Xamarin.Forms.Platform.iOS.PathRenderer`
None
- iOS
None
Not applicable
Launch Core Gallery and navigate to any of the Shapes Gallery samples. If you can navigate and see the Shapes, the test has passed.

[iOS] Added preserve default constructor in Shapes renderers

---

Xamarin.Forms.Platform.UAP/Platform.cs

When there's a Modal Page on UWP and you swap out the main page the background page needs to be removed and cleaned up otherwise it still exists and is still visible
Regressed as part of this PR
https://github.com/xamarin/Xamarin.Forms/pull/8551
Because with that PR the page is kept around when there's a modal page opposed to just being removed.
This is causing the UI Tests on UWP to break
- UWP
- Run Bugzilla B44476 and then hit ESC to reset Main Page. You should see no artifacts from the previously loaded page

[UWP] Cleanup _modalBackgroundPage

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11137.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/Shapes/ShapeRenderer.cs

Fixed issue in UWP Shapes getting a negative value for the height or width.
- fixes #11137 
None
- UWP
None
Not applicable
Launch Core Gallery and navigate to the issue 11137. Reduce the Window size to a minimum, without exceptions the test has passed.

[UWP] Fix Shapes issue using big margins

---

Xamarin.Forms.Core/Shell/ShellItem.cs
Xamarin.Forms.Platform.Android/Renderers/ShellItemRenderer.cs

When the logic for determining tab visibility was moved into the xplat code it wasn't correctly returning false if there was only one tab present
- iOS
- ui test Issue11107 passes

Hide tabbar if only one tab is present

---

Xamarin.Forms.Platform.UAP/CollectionView/ItemContentControl.cs

ItemContentControl is currently re-creating the hosted Element and its children when it's reused, rather than using the previously created content.
This change fixes that issue, so the CollectionView won't create new elements for every single item as it scrolls. 
- fixes #9051
None
- UWP
None
Not applicable
Control Gallery -> CollectionView Galleries -> DataTemplate Gallery -> DataTemplateSelector Gallery
If you scroll around and the weekday items remain the same while the weekend items are different, then this is working.

[UWP] Reuse the element when recycling an ItemContentControl

---

Xamarin.Forms.Platform.iOS/VisualElementTracker.cs

Fixed NRE checking if `ShouldUpdateClip` on iOS. The Mask Name could be null and raise an exception when comparing using Equals.
- fixes #11274 
None
- iOS
None
Not applicable
Launch Core Gallery, navigate to the Shapes gallery, rotate the device and touch the Shape.

[iOS] Fixed NRE checking if ShouldUpdateClip

---

Xamarin.Forms.Material.iOS/MaterialActivityIndicatorRenderer.cs

Under some conditions, possibly related to `ActivityIndicator` visibility, `Control` may be null at time of call to `LayoutSubviews()`. This caused crash due to `NullReferenceException`. This null check avoids that problem.
Note: this is the second PR for the same; was accidentally merging from master to 4.6.0 on the first one.
Null check for `Control` in `Xamarin.Forms.Material.iOS.MaterialActivityIndicatorRenderer.LayoutSubviews()` 
I noticed that at times I was seeing crashes due to `NullReferenceException` following Shell's `GoToAsync` method. On further investigation it was due to attempted access on a null `Control`. This null check solved the problem.
None.
- iOS only
Resolution of `NullReferenceException` crashes
Not applicable
I wasn't able to come up with a simple repro, however …

Avoid NullReferenceException for MaterialActivityIndicatorRenderer

---

Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs

Several parts of the iOS `PickerRendererBase` call `UpdateCharacterSpacing` after calling `UpdatePicker`. But `UpdatePicker` already calls `UpdateCharacterSpacing`.
- None, just saving some cycles
None
- iOS
None
Not applicable
Whatever tests we already have for the Picker.

Remove rendundant calls to UpdateCharacterSpacing

---

Xamarin.Forms.Controls/CoreGalleryPages/EditorCoreGalleryPage.cs
Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs

Makes the `UILabel` that fakes the placeholder functionality resize properly to prevent unexplained horizontal scrolling and also implemented the placeholder line break. The latter was actually the root cause for the scrolling.
- fixes #8569
- fixes #4291
- iOS
No more excessive horizontal scrolling for the Editor on iOS and the placeholder does proper line breaks.
Before
After
Go to Gallery app > Editor Gallery and find the 3rd FontSize option which has the 48pt font. Notice how it does not scroll horizontally when you land on the page. It does without this fix. Then remove the text and notice how the placeholder text goes multiline as well.

[iOS] Fix Editor excessive horizontal scroll and placeholder line break

---

Xamarin.Forms.Controls/GalleryPages/ShapesGalleries/AnimateShapeGallery.cs
Xamarin.Forms.Controls/GalleryPages/ShapesGalleries/ShapesGallery.cs
Xamarin.Forms.Platform.Android/Shapes/ShapeRenderer.cs

Fix issue animating StrokeDashOffset.
- fixes #11052
None
- Android
None
Animation did not work on Android.
Launch Core Gallery and navigate to the Shapes Gallery. Select the "Animate Shape Gallery" and verify that the shape is animating.

[Android] Fix issue animating StrokeDashOffset

---

Xamarin.Forms.Platform.iOS/PageLifecycleManager.cs
Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs
Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj

Handle calling appearing and disappearing of pages when the Application is going to background and restored.
- fixes #4986 
```
internal class PageLifecycleManager : IDisposable
{
public PageLifecycleManager(IPageController pageController)
protected virtual void Dispose(bool disposing)
public void Dispose()
public void HandlePageAppearing()
public void HandlePageDisappearing()
}
```
- iOS
When the app is restored the current page should have the Appearing event being called, like on Android.
Not applicable
use `new NavigationPage(new ContentPage52318())`in the MainPage

[iOS] Call page appearing when restoring app from background

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11272.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Extensions/ColorExtensions.cs

Fix crash setting the default Label color using Span.
- fixes #11272 
- fixes #11248
None
- macOS
None
Crash

[macOS] Fix crash setting the default Label color using Span

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11120.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11120.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11291.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs

Fix Frame IsClippedToBounds issue on iOS.
- fixes #11120
- fixes #11091
- fixes #11278
- fixes #11291
None
- iOS
None
_(The gif quality is low to keep a small size)_
Launch Core Gallery and navigate to issue 11120. Toggle the CheckBox to use or not `IsClippedToBounds` in the Frame. If using `IsClippedToBounds` clip the buttons, the test has passed.

[iOS] Fix Frame IsClippedToBounds issue 

---

Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs

- fixes #10679 
None
Added:
None
Changed:
Added an if statement to the SwipeViewRenderer on iOS to prevent a crash described on bug #10679 
Removed:
None
-->
None
- iOS
None
Not applicable
Run this code on the sample provided on the bug #10679 and you'll see the bug is solved on iOS.

Fix SwipeView crash with NullReferenceException [BUG #10679]

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4915.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/ScreenshotConditionalApp.cs
Xamarin.Forms.Controls/TestCases.cs
Xamarin.Forms.Core.Windows.UITests/WinDriverApp.cs
Xamarin.Forms.Platform.UAP.UnitTests/ShellTests.cs
Xamarin.Forms.Platform.UAP/FormsTextBox.cs

Removes call to Focus added in #11140 that caused regression #11348
#8787 should be reopened as it is no longer resolved with this change.
- fixes #11348
- fixes #11352
None
- UWP
Entry was getting focus when a page loaded and it should not be.  This restores the original behavior.
Not applicable
Check issue pages 2172, 8503, 8222, and then Entry Gallery Focus page

[UWP] Remove Focus call when setting FormsTextBox Vertical Alignment

---

.Xamarin.Forms.Android.slnf
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8797.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core.UnitTests/GridTests.cs
Xamarin.Forms.Core/GridCalc.cs
Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs

The Grid attempts to contract columns/rows to fit into the targeted layout. When doing this, it uses the same logic for contracting Star columns/rows as it does for Auto columns/rows. However, Star columns/rows are supposed to equally divide the remaining space; i.e., all 1* columns/rows should be the same size. 
The algorithm for contracting Auto columns/rows does so proportionally based on the difference between the current size and the minimum size of the contents. This is fine for Auto columns/rows, but for Stars this causes a problem. If the minimum sizes of the contents of the columns/rows vary, then the amount of contraction applied also varies; this means that the Star columns/rows can end up with different sizes.
In addition to violating the definition of Star columns/rows, this …

Apply uniform contractions to starred rows/columns

---

Xamarin.Forms.Core/Shapes/Shape.cs
Xamarin.Forms.Platform.Android/Shapes/ShapeRenderer.cs
Xamarin.Forms.Platform.UAP/Shapes/ShapeRenderer.cs
Xamarin.Forms.Platform.iOS/Shapes/ShapeRenderer.cs

Added `StrokeMiterLimit` property in Shape.
Added:
- `double  Shape.StrokeMiterLimit{ get; set; } //Bindable Property`
Gets or sets a limit on the ratio of the miter length to half the StrokeThickness of a Shape element.
- iOS
- Android
- macOS
- UWP
- WPF
None
Not applicable

Added StrokeMiterLimit property in Shape

---

Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs

The addition of the following override
https://github.com/xamarin/Xamarin.Forms/pull/9237/files#diff-8222d0783ad0aa5666a6d9d008a474b6R109
Is triggering a mono interpreter bug that causes hot restart to crash when navigating on shell
- fixes #10519
- iOS
- download the nuget, create a xamarin forms shell template, install this nuget, verify hot restart works

Export animationControllerForOperation to fix hot restart

---

Xamarin.Forms.Core.UnitTests/StepperUnitTests.cs
Xamarin.Forms.Core/Stepper.cs

Round stepper values so we can pretend they're not FP numbers but obey
the decimal logic. Rounding happen at n+4 position, n being the position
of the most significant digit of the increment. That gives up to 4
significant digit to the increment.
- reverts #7383
- reverts #10941
- fixes #5168 (for good)
- fixes #10032
- fixes #11169
Obsoleted:
- `double Stepper.StepperPosition {get; set;}`
- `BindableProperty Stepper.StepperPositionProperty;`
StepperPosition is no-op
Not applicable

[C] Round Stepper.Value

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellItemIsVisible.cs
Xamarin.Forms.Core.UnitTests/ShellTests.cs
Xamarin.Forms.Core/Shell/BaseShellItem.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellContentCollection.cs
Xamarin.Forms.Core/Shell/ShellElementCollection.cs
Xamarin.Forms.Core/Shell/ShellItem.cs
Xamarin.Forms.Core/Shell/ShellUriHandler.cs
Xamarin.Forms.Core/ViewExtensions.cs
Xamarin.Forms.Platform.UAP/Shell/ShellRenderer.cs

- Add IsVisible property to BaseShellItem which will hide that particular shell element from all UI structures and the element will be treated as if it doesn't exist
- Add FlyoutItem.IsVisible which will just hide the item from the flyout menu
- partially fixes #5232
Added:
```C#
public class FlyoutItem
{
public new bool IsVisible //BP
}
```
```C#
public class BaseShellItem
{
public bool IsVisible //BP
}
```
- iOS
- Android
- UWP
- Automated Tests included

BaseShellItem IsVisible and FlyoutItem.IsVisible

---

Xamarin.Forms.Core.UnitTests/ShellTests.cs
Xamarin.Forms.Core/Routing.cs
Xamarin.Forms.Core/Shell/Shell.cs

When the code was added to collapse down routes when navigating to nested registration it was removing default routes for the current state when navigating to a page. If the user hasn't specified any routes themselves we have to keep the default around on the URL so shell can know where it is.

[Shell] Don't remove default routes if that's all there is

---

Xamarin.Forms.ControlGallery.iOS/_11132CustomRenderer.cs
Xamarin.Forms.Platform.iOS/VisualElementTracker.cs

Not sure why the gallery doesn't crash when the mask name is null, but this should be the last of the required null checks 🤞 
- fixes #11132
None
- iOS
None
Not applicable
Test with the project included in #11132

[iOS] Null check Mask.Name

---

Xamarin.Forms.Platform.GTK/Controls/ImageControl.cs
Xamarin.Forms.Platform.GTK/Renderers/ImageRenderer.cs

This PR adds support for rotation and scaling of the Image Control  on the GTK Platform.
fixes #8732 
- GTK
Below is a GIF of a rotating and scaling image as per the issue above. 
_The GIF is a bit wonky because of low capture framerate. In reality the animation is smooth._

Add support for scale and rotation of images on GTK

---

Xamarin.Forms.Platform.UAP/CompositionHelper.cs

Fixed validation to check if can use Composition Clip on UWP.
- fixes #11265 
None
- UWP
None
Not applicable
Use the generated NuGet package with a Xamarin.Forms App. Use 1734 as target in UWP App and launch it. Without error, the test has passed.

[UWP] Fixed validation to check if can use Composition Clip 

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla36802.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla53834.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1436.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1909.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2775.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2894.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue342.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3884.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4879.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5830.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5831.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8004.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8766.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue968.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellGestures.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellInsets.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/ScreenshotConditionalApp.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/_Template.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/_TemplateMarkup.xaml.cs
Xamarin.Forms.Core.UITests.Shared/Tests/Legacy-CellsUITests.cs
Xamarin.Forms.Platform.iOS.UnitTests/FrameTests.cs
Xamarin.Forms.Platform.iOS.UnitTests/Xamarin.Forms.Platform.iOS.UnitTests.csproj
Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs
build.cake

These changes let us keep the same actualview without instantiating it everytime
- When calling AddSubView on the framerenderer just forward those calls to ActualView
- When calling removefromparentview on ActualView just forward those to the views added to ActualView
Instead of forwarding the Gesture Recognizers just set UserInteractionEnabled to false on the inserted middle view. 
I ran tests with this to make sure content inside the frame still worked and APIs like InputTranparent still function correctly. Issue10422.xaml.cs has a PanGestureRecognizer you can test with
- fixes #11266
- iOS
- Test all the issues here https://github.com/xamarin/Xamarin.Forms/pull/10469 make sure nothing regressed. One of the tests in there doesn't clip quite right but that's fixed by a PR @jsuarezruiz …

[iOS] Fix controls added to Frame multiple times when container is recycled on ListView

---

Xamarin.Forms.Platform.UAP/BootstrapHelper.cs

Enable C++ code to simulate ICLRRuntimeHost2::ExecuteAssembly on top of ICLRRuntimeHost2::CreateDelegate in .net core 2.
None
None
- UWP
None
Not applicable
Validated locally that C++ code can use BoostrapHelper.Bootstrap to load a managed dll.
> VS bug [#1156448](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1156448)

Add BoostrapHelper

---

Xamarin.Forms.Platform.iOS/Renderers/MediaElementRenderer.cs

Fix issue with duplicated played to end observer in `MediaElement` on **iOS**.
- fixes #11315 
None
- iOS
None
Not applicable
Launch Core Gallery and navigate to the MediaElement Gallery. Reproduce the video and move the time to the end. MediaEnded must be invoked only one time.

[iOS] Fix issue with duplicated played to end observer in MediaElement

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11244.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8529.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellBackButtonBehavior.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs

Changes in 4.7 incorrectly ignored BackButtonBehavior if the flyoutbehavior was set to disabled.
This combination was also causing android to incorrectly toggle the flyout menu when it's disabled but the text is set. 
- fixes #11244
- fixes #11102
- iOS
- Android

Update Left Tool Bar Item even if flyout is disabled

---

Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs

When the back button is being replaced it was always opening the flyout instead of navigating back when not on the root page
- fixes #7856 
- iOS
- open the Back Button page and play around make sure it all acts as you'd expect

[iOS] Pop when on second page and BackButton is replaced

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla36802.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla53834.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1436.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1909.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2775.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2894.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue342.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3884.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4879.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5830.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5831.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8004.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue968.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellGestures.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellInsets.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/_Template.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/_TemplateMarkup.xaml.cs
Xamarin.Forms.Core.UITests.Shared/Tests/Legacy-CellsUITests.cs
Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs

The frame code that regressed frame on iOS was cherry picked down to 4.5
This cherry picks the fix down to 4.5
fixes #11266
- iOS
- make sure ui tests run

[iOS] Fix controls added to Frame multiple times when container is recycled on ListView (#11375)

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Helpers/UITestHelper.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11259.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11259.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/ScreenshotConditionalApp.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core.UITests.Shared/BaseTestFixture.cs
Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs
Xamarin.Forms.Core.Windows.UITests/WinDriverApp.cs
Xamarin.Forms.Core.Windows.UITests/WindowsTestBase.cs
Xamarin.Forms.Core.Windows.UITests/WindowsTestServer.cs
Xamarin.Forms.Platform.UAP/FormsTextBox.cs
Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs

Updates VisualElementRenderer to delay calling Packager.Load until the Loaded event fires.
PR #11350 should be merged first
I'm not sure I completely understand the layout pipeline of the UWP backend, so I'm not 100% sure of all the possible effects of this change could have.  It should be noted that the code to call Packager.Load in the Loaded event was previously commented out for causing an unhandled exception.  I have not experienced any exceptions during testing, but I can find no other reference to the issue other than the comment left in the code.  That comment pre-dates the import into GitHub, so it's rather old at this point.
My working theory is that the text not showing initially sometimes in the FormsTextBox is a timing issue of when the element is added to the visual tree …

[UWP] Fixes 8787 Entry text not visible until focus or window resize

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11262.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11262.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/VisualElementRenderer.cs

Fix an issue using SwipeView with BindableLayout and removing items (dispose issue).
- fixes #11262 
- fixes #11407
None
- Android
None
Crash
Launch Core Gallery and navigate to the issue 11262. Swipe and remove an item from the list. Without errors, the test has passed.

[Android] Fix SwipeView dispose issue

---

Xamarin.Forms.Platform.MacOS/Renderers/ButtonRenderer.cs

Fix Button issues with BackgroundColor, BorderColor, etc on macOS.
In this change https://github.com/xamarin/Xamarin.Forms/commit/bfe7b7450a8f63e8e6bf3cb147976b5548991f5f#diff-ba4df52c80dd304b5fc99f852c2a04d7 we changed the `BezelStyle` affecting some properties like the background or border color.
- fixes #11431
None
- macOS
None
Launch Core Gallery on macOS and navigate to the Button Gallery. Select the Button Gallery and test properties like the BackgroundColor and the BorderColor.

[macOS] Fix Button issues with BackgroundColor, BorderColor, etc

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11523.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs

If the user has disabled the flyout but they are on the second page then we still need to render the back button
- fixes #11523
- Android

Show backarrow if FlyoutBehavior is set to disabled

---

Xamarin.Forms.Core/RectTypeConverter.cs
Xamarin.Forms.Xaml.UnitTests/Issues/Gh11541.xaml
Xamarin.Forms.Xaml.UnitTests/Issues/Gh11541.xaml.cs

Fix inheritance of RectTypeConverter from RectangleTypeConverter, as the
child isn't precompiled, even if the parent has the attribute...
- fixes #11541
None
None
Not applicable

[Shapes] Fix RectTypeConverter

---

Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
Xamarin.Forms.Xaml.UnitTests/Issues/Gh11061.xaml
Xamarin.Forms.Xaml.UnitTests/Issues/Gh11061.xaml.cs

There was a `TODO: check parameter type` in this code, like if past me
knew that, at some point in time, what was only a potential edge case
bug, would explode in my face and ruin my faith in humanity.
Those FIXMEs... they are bottled 'I TOLD YOU SO' little time capsules
- fixes #11061
None
None
Not applicable

[X] throw on mismatching param type for Add()

---

Xamarin.Forms.Platform.iOS/Renderers/FormattedStringExtensions.cs

Fix Entry PlaceholderColor issue using a global Span TextColor Style on iOS. Internally, in iOS the placeholder is a `FormattedString` with one `Span`. By applying the global Span style, we were overwriting the placeholder color. Added validation to fix the issue.
- fixes #11425 
None
- iOS
None

[iOS] Fix Entry PlaceholderColor issue using a global Span TextColor Style

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11247.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core/Shell/MenuShellItem.cs
Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRecyclerAdapter.cs
Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRenderer.cs
Xamarin.Forms.Platform.iOS/Extensions/AccessibilityExtensions.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewSource.cs

- If the FlyoutIsPresented toggles while animation is active just cancel the animation
- Set AutomationIds for flyout menu
- Fix issue when setting FlyoutIsPresented to true during load
- fixes #11247
- iOS
- Android

Fix FlyoutIsPresented when set from Navigating

---

Xamarin.Forms.Platform.UAP/FormsTextBox.cs
Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs

Changing to safe casting when pulling elements out of the control template incase the template changes.  Per a suggestion in this comment on PR https://github.com/xamarin/Xamarin.Forms/pull/11140#discussion_r448810684
I also removed the code pulling out the BorderElement from the template.  The variable was not referenced, other than to be set and windows phone is no longer supported.
None, housekeeping only
None
- UWP
None
Not applicable
I retest all issues from PR 11140 and all tested good.

[UWP] FormsTextBox clean up OnApplyTemplate

---

Xamarin.Forms.Core.UnitTests/RectUnitTests.cs
Xamarin.Forms.Core/Rect.cs
Xamarin.Forms.Core/Rectangle.cs
Xamarin.Forms.Xaml.UnitTests/Issues/Gh11541.xaml
Xamarin.Forms.Xaml.UnitTests/Issues/Gh11541.xaml.cs
Xamarin.Forms.Xaml.UnitTests/Issues/Gh11551.xaml

- move both implicit operator to the same type (Rectangle)
- remove setters on convenience properties
- fixes #11557
- fixes #11555
- fixes maybe #11542 (to be confirmed)
Removed:
- `Rect.ctor(Rectangle)`
- `double Rect.Top {set;}`
- `double Rect.Bottom {set;}`
- `double Rect.Right {set;}`
- `double Rect.Left {set;}`
-  `static implicit operator Rect.Rect(Rectangle rectangle)`
Added:
-  `static implicit operator Rectangle.Rect(Rectangle rectangle)`
None

[C] Some Rect API changes

---

Xamarin.Forms.Core.UnitTests/PathSegmentTests.cs
Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
Xamarin.Forms.Core/Shapes/PolyQuadraticBezierSegment.cs
Xamarin.Forms.Core/Shapes/RotateTransform.cs
Xamarin.Forms.Core/Shapes/ScaleTransform.cs
Xamarin.Forms.Core/Shapes/SkewTransform.cs
Xamarin.Forms.Core/Shapes/TranslateTransform.cs

Added missing shapes constructors with parameters. Useful creating Shapes using C#.
Added Shapes Segments and Transformations constructors
None
Not applicable
Must pass the added unit tests. Can create shapes transformations and segments using a constructor with parameters.

[Core] More Shapes constructors

---

Xamarin.Forms.Controls/XamStore/StoreShell.xaml.cs
Xamarin.Forms.Controls/XamStore/Views/StorePages.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellAppearance.cs
Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRenderer.cs
Xamarin.Forms.Platform.UAP/Shell/ShellRenderer.cs
Xamarin.Forms.Platform.UAP/Shell/ShellSplitView.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutRenderer.cs

Add FlyoutBackdrop back into Shell but now based on Brushes
https://github.com/xamarin/Xamarin.Forms/pull/10511
Added:
- Brush ShellAppearance.FlyoutBackdrop
- iOS
- Android
- UWP
- play with store shell

Shell FlyoutBackdrop now with Brushes!!

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11430.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/ButtonElementManager.cs
Xamarin.Forms.Platform.iOS/Renderers/ButtonRenderer.cs

Change Button state (to Normal state) if the touch-up event occurs outside on iOS.
- fixes #11430 
None
- iOS
None
Not applicable

[iOS] Change Button state if the touch-up event occurs outside

---

Xamarin.Forms.Platform.UAP/Shell/ShellRenderer.cs

If appearance is null than don't set the backdrop
- UWP
- ui tests pass
- backdrop still works on uwp

Check for null appearance before setting backdrop

---

Xamarin.Forms.Core/Shapes/Transform.cs

The `ValueProperty` bindable field of the new `Xamarin.Forms.Shapes.Transform` is marked `internal` which prevents accessing the BindableProperty from the code and use things like `ClearValue` to reset the property to its default value.
Since all other BindableProperty fields are marked public, I don't see any reason not to for this one as well.
I changed it to public too.
- Didn't created a linked issue. Let me know if you want me to.
Changed:
- internal static readonly BindableProperty ValueProperty => public static readonly BindableProperty ValueProperty
None
Not applicable
None

Mark Transform.ValueProperty as public

---

Xamarin.Forms.Platform.Android/Renderers/BottomNavigationViewUtils.cs
Xamarin.Forms.Platform.Android/Resources/values/strings.xml

Move the hardcoded "More" for the overflow tab on Android to the `strings.xml` so it's overridable by the user
- fixes #7849
None
- Android
None
Not applicable
Pull down the nugets and install them on an app where you have a "More" tab. in your `strings.xml` file add `<string name="overflow_tab_title">Meer</string>` and see if the value changes.
You can also do this in the gallery app and switch to the "Shell Store" root page and look in the bottom right

[AND] Make Shell overflow tab title "More" overridable

---

Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs
Xamarin.Forms.ControlGallery.WindowsUniversal/App.xaml.cs
Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs
Xamarin.Forms.Controls/GalleryPages/AppThemeGalleries/AppThemeGallery.cs
Xamarin.Forms.Core.UnitTests/AppThemeTests.cs
Xamarin.Forms.Core/Application.cs
Xamarin.Forms.Core/BindableObjectExtensions.cs
Xamarin.Forms.Core/ExperimentalFlags.cs
Xamarin.Forms.Xaml.UnitTests/OnAppThemeTests.cs
Xamarin.Forms.Xaml/MarkupExtensions/AppThemeBindingExtension.cs

Drop the AppTheme Flag
none
None
- iOS
- Android
- UWP
None
Not applicable

Drop AppTheme flag

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10608.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/Renderers/ShellSectionRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootHeader.cs

- the ios page renderer when disappearing was still propagating its inset information to shell which was causing a ping pong effect
- Automation properties weren't being set on top tabs
- fixes #10608
- iOS
- Android

Don't update safe area offset on non visible page

---

Xamarin.Forms.Core.UnitTests/LinearGradientBrushTests.cs
Xamarin.Forms.Core/LinearGradientBrush.cs

Unify LinearGradientBrush default **EndPoint** value with WPF.
- fixes #11569 
Changed the LinearGradientBrush EndPoint default value.
The default LinearGradientBrush will be a diagonal gradient.
Not applicable
Launch Core Gallery and navigate to the brushes samples. The default LinearGradientBrush should be a a diagonal gradient.

[Core] Unify LinearGradientBrush default values with WPF

---

Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11185.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs

We create a custom horizontal and need to pass it properties users set on custom renderers , properties like `HorizontalFadingEdgeEnabled`  and `HorizontalFadingEdgeLength`
- fixes #11185
None
- Android
Should be able to see fading edge  on scrollviewer
Not applicable
Manual visit issue 11185 and see if it shows the fading edges

[Android] Pass fading properties to HorizontalScrollViewContainer

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9525.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/MediaElementRenderer.cs
Xamarin.Forms.sln

Removed line that pauses player before setting it to null.
I think the pause is there to stop background playback of the media element, but since the next line also seems to stop it, I removed the line.
I appreciate there is probably a lot more going on here though @peterfoot .
I'm not sure how to handle the video source, there has to be one for the exception to occur. It's currently taking a hard-coded URL source.
- fixes #9525 
None
- iOS
Will now not give an exception on Dispose.
Not applicable
Have a page in iOS with a media element. Change page so that the media element is disposed.

[MediaElement] Removed line that pauses player before setting it to null.

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2447.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2447.xaml.cs
Xamarin.Forms.Platform.Android/Renderers/LabelRenderer.cs

The FlowDirection property now has an effect on label controls. 
- fixes #2447
None
- Android
None
Before:
After:
1. Create new project
2. Add Two labels to a page
3. Write English text in the first label and Kurdish/Arabic (نووسینی کوردی) text in the other
4. Set Page FlowDirection to RightToLeft

[Android] FlowDirection property now has an effect on label controls

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10608.cs
Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs

`VisualElementRenderer.LayoutSubviews` is sometimes called after the `VisualElementRenderer` has been disposed of so we should null check Element inside LayoutSubviews 
- fixes #11664 
- iOS
- Android
- run the UI tests and just click really fast between flyout items

Null check Element in VisualElementRenderer.LayoutSubviews

---

.nuspec/Xamarin.Forms.targets
Xamarin.Forms.Xaml.UnitTests/MSBuild/MSBuildTests.cs

I was reviewing a customer's build logs, and saw the following:
32953 ms  XamlC                                     34 calls
This was a build log where they changed one line of C# code in a
project that is referenced by many other projects. This is a fairly
large solution with ~63 projects.
Digging deeper, there were 5 instances of:
No compiled resources. Skipping writing assembly.
Looking at the `XamlG` target, these had no `.xaml` files at all:
Target Name=XamlG
Target Name=_FindXamlGFiles
Skipping target "XamlG" because it has no outputs.
Though the target has declared its outputs, the output specification only references empty properties and/or empty item lists.
Yet `XamlC` still ran and took ~667ms in one instance.
If we *skipped* `XamlC` when there no `.xaml` files, it would have …

[msbuild] skip XamlC target if no xaml files

---

Xamarin.Forms.Build.Tasks/CompiledConverters/EasingTypeConverter.cs
Xamarin.Forms.Core.UnitTests/EasingTests.cs
Xamarin.Forms.Core/BindableProperty.cs
Xamarin.Forms.Core/Easing.cs
Xamarin.Forms.Core/EasingTypeConverter.cs
Xamarin.Forms.Xaml.UnitTests/TypeConverterTests.xaml
Xamarin.Forms.Xaml.UnitTests/TypeConverterTests.xaml.cs

Added EasingTypeConverter for convenient use Easings with xaml.
Added:
- EasingTypeConverter
**BEFORE**
```xaml
<Expander ExpandAnimationEasing="{x:Static Easing.CubicIn}"
CollapseAnimationEasing="{x:Static Easing.CubicOut}">
</Expander>
```
**AFTER**
```xaml
<Expander ExpandAnimationEasing="CubicIn"
CollapseAnimationEasing="Easing.CubicOut">
</Expander>
```
Not applicable
Run unit test **TestEasingTypeConverter** test case.

Easing type converter

---

.gitignore
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla46363_2.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Github5623.xaml.cs
build.cake

- set environment variables for test results
- ignore UWP test related to context menus
- UWP
- make sure UI Tests run
- make sure @rmarinho is happy 👍

Set environment variables for UWP test results

---

Xamarin.Forms.Core.Design/EasingDesignTypeConverter.cs
Xamarin.Forms.Core.Design/Xamarin.Forms.Core.Design.csproj

@StephaneDelcroix  Here is my attempt to create Easing Xaml "hints".
Since that's impossible to build Design.dll on Mac, I can't verify that the project builds, but I hope it should.
None
None
Not applicable
Not sure about the flow, but the end goad to provide "hints" when using Easing in xaml.

EasingDesignTypeConverter

---

Xamarin.Forms.Platform.WPF/Renderers/ListViewRenderer.cs

When we changed the Element with empty HeaderElement, the ListViewRenderer will enter UpdateHeader method to update the `_headerRenderer` field. But the `UpdateHeader` method will only call the `_headerRenderer.Dispose()` and do not release the reference.
This means that the old "_headerRenderer" object will be referenced by "ListViewRenderer" resulting in a memory leak
None
- WPF
None
Not applicable

Fix the memory leak problem of ListViewRenderer _headerRenderer

---

Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs

Add blur effect view to the view instead of view's superview. (I assume it's a mistake/typo)
- fixes #9720
None
- iOS
The blur effect has the same coordinates with the view that it's applied for.
BEFORE:
AFTER:
The sample is attached in the original bug ticket.

[Bug] [iOS] platform-specific VisualElement Blur is misaligned

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11573.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11573.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Extensions/BrushExtensions.cs

Fix `RadialGradientBrush` position issue on iOS. We were limiting the maximum value for the `EndPoint`.
- fixes #11573 
None
- iOS
None
Launch Core Gallery on iOS simulator or device and navigate to the issue 11573. If the RadialGradientBrush Radius is the same in all cases, the test has passed.

[iOS] Fix RadialGradientBrush position issue

---

Xamarin.Forms.Platform.iOS/Renderers/ActivityIndicatorRenderer.cs

I'm not even sure this is the best way at the moment, but it's a conversation point to move towards a resolution.
The issue comes from having an ActivityIndicator in a CarouselView or UICollectionViewFlowLayout in this case.
You can't call StartAnimating until it has been added to the top UIView (its Superview), otherwise it doesn't do anything. It seems to affect any cell based view, where the cell might not be visible, when the Activity starts its animation.
I found this issue locally, in scanning open issues, these could be related
fixes #10377
fixes #1989
None
- iOS
None
Not applicable
Issue:
Put an ActivityIndicator in a CarouselView (not the first one), and when you move to it, it won't be visible, even if running.
With Fix:
It now will keep showing, even if you go away and come …

[iOS] ActivityIndicator starting animation only when attached to superview

---

Xamarin.Forms.Platform.MacOS/Cells/CellNSView.cs
Xamarin.Forms.Platform.MacOS/Cells/CellRenderer.cs
Xamarin.Forms.Platform.MacOS/Cells/EntryCellRenderer.cs
Xamarin.Forms.Platform.MacOS/Cells/TextCellRenderer.cs
Xamarin.Forms.Platform.MacOS/Cells/ViewCellNSView.cs
Xamarin.Forms.Platform.MacOS/Renderers/DatePickerRenderer.cs
Xamarin.Forms.Platform.MacOS/Renderers/EntryRenderer.cs
Xamarin.Forms.Platform.MacOS/Renderers/ListViewRenderer.cs
Xamarin.Forms.Platform.MacOS/Renderers/PageRenderer.cs
Xamarin.Forms.Platform.MacOS/Renderers/SearchBarRenderer.cs
Xamarin.Forms.Platform.iOS/Extensions/ColorExtensions.cs
Xamarin.Forms.Platform.iOS/Forms.cs
Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs

Add necessary bits to support both native Dark Mode from 10.14 and up and the Forms xplat APIs
- fixes #8864 
- fixes #3777
- added on macOS project: `public class FormsNSView`
- macOS
Some colors might be different than before when running on 10.14+. Colors where changed to use dynamic colors so the values might be different than the hard-coded ones earlier.
Switch your Mac to Dark Mode and run the gallery app. Everything should look easy on the eyes.
When switching while the app is running, everything should transition back and forth

[macOS] Dark Theme support

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6417.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Controls/GalleryPages/ListViewDemoPage.cs
Xamarin.Forms.Core/IListViewController.cs
Xamarin.Forms.Core/ListView.cs
Xamarin.Forms.Platform.GTK/Controls/ListView.cs
Xamarin.Forms.Platform.GTK/Controls/TableView.cs
Xamarin.Forms.Platform.GTK/Renderers/ListViewRenderer.cs
Xamarin.Forms.Platform.WPF/Renderers/ListViewRenderer.cs

- fixes #3659
- fixes #3660
None
- WPF
- GTK
None
Not applicable

#3659 #3660 WPF/GTK ListView ContextMenu, SelectionBehavior fix

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems

Removed duplicated entry in Xamarin.Forms.Controls.Issues.Shared.projitems
None
None
Not applicable
Can compile Core Gallery without compilation errors.

Removed duplicated entry in Xamarin.Forms.Controls.Issues.Shared.projitems

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6472.cs

Issue6472 occasionally crashes when running on AppCenter. This test deals with ListView which is being replaced by CollectionView so for now I'm reopening the issue connected to the test (#6472) and ignoring the UI test
Failure:
https://dev.azure.com/xamarin/public/_releaseProgress?releaseId=2131&_a=release-environment-extension&environmentId=84004&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab
- iOS
- run the iOS tests a few times and ensure they pass

Ignore Issue6472 and reopened associated issue

---

Xamarin.Forms.Platform.Tizen/Native/CollectionView/CarouselView.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/CollectionView.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/EmptyItemAdaptor.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/GridLayoutManager.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/ICollectionViewLayoutManager.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/ItemAdaptor.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/ItemTemplateAdaptor.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/LinearLayoutManager.cs
Xamarin.Forms.Platform.Tizen/Renderers/CarouselViewRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/IndicatorViewRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/ItemsViewRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/StructuredItemsViewRenderer.cs

CollectionView enhancement on Tizen platform
- Implement Header/footer on CollectionView
- Implement VisibleViews on CarouselView
- Implement RemainingItemsThreshold on ItemsView
- Fix ItemsView.Scrolled Event behavior
- ItemsView.Scolled event was raised when scrolling was completed
- fixes #
Added:
- object StructuredItemsView.Header
- object StructuredItemsView.Footer
- DataTemplate StructuredItemsView.HeaderTemplate
- DataTemplate StructuredItemsView.FooterTemplate
- ObservableCollection<View> CarouselView.VisibleViews
- int ItemsView.RemainingItemsThreshold
- ICommand ItemsView.RemainingItemsThresholdReachedCommand
- object ItemsView.RemainingItemsThresholdReachedCommandParameter
- Tizen
None
Not applicable

[Tizen] CollectionView enhancement

---

Xamarin.Forms.Platform.Tizen/Shell/ShellSectionNavigation.cs

`Shell` is only for `ContentPage`.
But an `ArgumentNullException` has occured when used with multi-page.
This patch is intended to prevent a crash in the following cases on `Tizen` platform.
`Shell` with `CarouselPage`, `TabbedPage`, `NavigationPage`, `MasterDetailPage`.
- fixes #
None
- Tizen
None
Not applicable
`Shell` with `CarouselPage`, `TabbedPage`, `NavigationPage`, `MasterDetailPage`.

[Tizen] Fix ShellSectionNavigation

---

Xamarin.Forms.Core/ImageSource.cs

The default overload for `ImageSource.FromStream` does 2 things which may not be desirable:
- starts a new background task
- requires a blocking operation
If I have some local caching system for images, I might already have a task cache or does other bad things when forcing a synchronous execution.
Here is an example with some "HTTP cache" 😄  - I know about the URI image source, but this is an example that is also exciting to write.
```csharp
var imageSource = ImageSource.FromStream(async token =>
{
var client = new HttpClient();
var msg = await client.GetAsync("http://example.org", token);
if (!msg.IsSuccessStatusCode)
return null;
return await msg.Content.ReadAsStreamAsync();
});
```
- fixes a case where I have to take an async operation and call `.Result` 😱
Added:
- public static …

[Core] Add an overload for async ImageSource

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellStoreTests.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Controls/CoreGallery.cs
Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs
Xamarin.Forms.Core.Windows.UITests/WindowsTestBase.cs
Xamarin.Forms.Platform.UAP/Shell/ShellPageWrapper.xaml
Xamarin.Forms.Platform.UAP/Shell/ShellPageWrapper.xaml.cs
Xamarin.Forms.Platform.UAP/Shell/ShellSectionRenderer.cs
Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
build.cake
build/steps/build-windows.yml

- Convert the Shell holder page for frame navigation to a XAML page because it appears that when in release mode that's required
- Change the Windows UI Tests to build and deploy using a release build with native tool chain bits
- fixes #11736
- UWP
- UI Tests pass
- Control GAllery deploys in release mode and works

Create a specific XAML page for the ShellPageWrapper used for Shell Navigation

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11869.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/Renderers/ShellItemRenderer.cs

Androids ShellItemRenderer is using the wrong data structures for pulling in Visible Items
- fixes #11869
- Android

[Android] Fix Bottom Tab IsVisible with Shell

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11723.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/EventTracker.cs
Xamarin.Forms.Platform.iOS/Platform.cs
Xamarin.Forms.Platform.iOS/Renderers/IDisconnectable.cs
Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellItemRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellItemTransition.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootRenderer.cs
Xamarin.Forms.Platform.iOS/VisualElementPackager.cs
Xamarin.Forms.Platform.iOS/VisualElementTracker.cs
Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj

When you navigate between FlyoutIItems on shell it uses a transition which doesn't dispose of the previous items until after the transition. If the user navigates between Flyout Items too quickly the previous animation hasn't completed so the renderer stack hasn't disposed. Because the renderer stack hasn't disposed the old renderers are still part of the old pages which causes a doubling up of renderers on the same page.
This PR attempts to disconnect all the communication points between the xplat components and the native components so that the native components can just finish their business in isolation without triggering any behavior from the xplat side of the code.
- fixes #11784
- fixes #11777
- iOS

When navigating between Shell Items disconnect the renderers from the xplat elements

---

Xamarin.Forms.Platform.Tizen/FormsApplication.cs

This PR prevents unnecessary `Application.OnResume()` calls in a specific case, and invokes `Application.OnResume()` exactly according to the lifecycle of native Tizen Application.
None
None
- Tizen

[Tizen] Fix the lifecycle of application

---

Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs

Fixed the position of the placeholder of an Editor control on iOS.
- fixes #11889
None
- iOS
The position of the placeholder of an Editor control on iOS should be correct now.
Check CoreGalleryPages/EditorCoreGalleryPage.cs

[iOS] Fix position of placeholder (#11889)

---

Xamarin.Forms.Platform.Tizen/PopupManager.cs
Xamarin.Forms.Platform.Tizen/ThemeConstants.cs
Xamarin.Forms.Platform.Tizen/ThemeManager.cs

This PR is to allow DisplayAlert's message to be null. 
```cs
this.DisplayAlert("DisplayAlert Test", null, "OK", "Cancel");
```
Previously, `NullReferenceException` has been occured. But now it work fine just like other platforms.
Additionally, this change includes applying `ThemeManager`.
None
None
- Tizen

[Tizen] Fix the behavior of the DisplayAlert

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11865.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs

Fixed NRE in SearchBarRenderer OnSearchButtonClicked on iOS.
- fixes #11865 
None
- iOS
None
Launch Core Gallery and navigate to the issue 11865. Type something in the SearchBar and tap the search button. If can navigate without any crash (disposed Control), the test has passed.

[iOS] Fixed NRE in SearchBarRenderer OnSearchButtonClicked

---

Xamarin.Forms.Controls/GalleryPages/DragAndDropGalleries/DragAndDropBetweenLayouts.xaml
Xamarin.Forms.Controls/GalleryPages/DragAndDropGalleries/DragAndDropBetweenLayouts.xaml.cs
Xamarin.Forms.Controls/GalleryPages/DragAndDropGalleries/DragAndDropEvents.xaml
Xamarin.Forms.Controls/GalleryPages/DragAndDropGalleries/DragAndDropEvents.xaml.cs
Xamarin.Forms.Controls/GalleryPages/DragAndDropGalleries/DragAndDropGallery.cs
Xamarin.Forms.Controls/GalleryPages/DragAndDropGalleries/DragPaths.xaml
Xamarin.Forms.Controls/GalleryPages/DragAndDropGalleries/DragPaths.xaml.cs
Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
Xamarin.Forms.Core.UnitTests/DragGestureRecognizerTests.cs
Xamarin.Forms.Core.UnitTests/DropGestureRecognizerTests.cs
Xamarin.Forms.Core/DragAndDrop/DataPackageOperation.cs
Xamarin.Forms.Core/DragAndDrop/DragGestureRecognizer.cs
Xamarin.Forms.Core/DragAndDrop/DropGestureRecognizer.cs
Xamarin.Forms.Platform.Android/DragAndDropGestureHandler.cs
Xamarin.Forms.Platform.UAP/VisualElementTracker.cs
Xamarin.Forms.Platform.iOS/DragAndDropDelegate.cs

- Added additional samples
- wired up DragLeave event
- fixed various timing issues if an element loses its renderer before a drop is complete
- Changed drag and drop to have EnableDrag/AllowDrop enabled by default so it all just works by default when adding the recognizers
- Fixed a few issues on Android with processing clip data from an external app
- partially fixes #11663
- fixes #11833
Added:
- public static readonly BindableProperty DragLeaveCommandProperty;
- public static readonly BindableProperty DragLeaveCommandParameterProperty;
- public event EventHandler<DragEventArgs> DragLeave;
- iOS
- Android
- UWP
- unit tests and UI tests all pass
- Gallery additions work as expected (FYI The Cat doesn't drag super well on UWP but this is most likely a bug …

First round of Drag and drop fixes

---

.nuspec/Xamarin.Forms.nuspec
DualScreen/DualScreen.UWP/DualScreen.UWP.csproj
EmbeddingTestBeds/Embedding.UWP/Embedding.UWP.csproj
UWP.Build.targets
Xamarin.Forms.DualScreen/Xamarin.Forms.DualScreen.csproj

The version of `Microsoft.NETCore.UniversalWindowsPlatform` should be settable by the application developer. By default we'll have our templates always pointing at the latest tested version 
Having this in our nuspec and inside the templates just leads to nuget dependency confusions
- UWP
- UI tests pass
- make sure you can install this nuget into a new UWP app and it runs

Remove Microsoft.NETCore.UniversalWindowsPlatform From nuspec

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10307.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Controls/GalleryPages/EmbeddedFonts.xaml.cs
Xamarin.Forms.Core/ExportFontAttribute.cs
Xamarin.Forms.Core/FontRegistrar.cs
Xamarin.Forms.Platform.UAP/FontExtensions.cs
Xamarin.Forms.Platform.UAP/FontImageSourceHandler.cs

Embedded fonts on UWP don't work when the font name does not match the file name of the font, which is the case with many Google fonts (and FontAwesome icons)
To fix this, the font family name has to be extracted from the font file and appended to the font name when the font is created from the font file.
- fixes #10307 
None
- UWP
None (fixes bug #10307)
Before:
After:
Not applicable

Fix for issue #10307, embedded fonts not working on UWP

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11496.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11496.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs

Since Xamarin.Forms 4.8 the content gesture works, this PR manages the closing of the SwipeView when tapping the content.
- fixes #11496
None
- Android
None
Launch Core Gallery and navigate to the issue 11496. If tapping an item appear a dialog, the test has passed.

[Android] Fix SwipeView with gestures issue

---

Xamarin.Forms.Platform.Tizen/Extensions/TextAlignmentExtensions.cs
Xamarin.Forms.Platform.Tizen/Native/EditfieldEntry.cs
Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs

This PR is to enhance `CursorPosition` / `SelectionLength` and support `VerticalTextAlignment` of `Entry`.  Plus, I've adjusted the height of entry appropriately. (Previously, it was too big unnecessarily.)
Before| After
---- | ----
None
None
- Tizen
None
See above description
Run ControlGallery - [Issue3343](https://github.com/xamarin/Xamarin.Forms/blob/a8bcaa9a609cfa6f3026775b26ab7adfb4947772/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3343.cs#L9)

[Tizen] Enhances the EntryRenderer

---

Xamarin.Forms.Core/AbsoluteLayout.cs
Xamarin.Forms.Core/Cells/ViewCell.cs
Xamarin.Forms.Core/Element.cs
Xamarin.Forms.Core/ElementEventArgs.cs
Xamarin.Forms.Core/Items/ItemsView.cs
Xamarin.Forms.Core/Layout.cs
Xamarin.Forms.Core/ListView.cs
Xamarin.Forms.Core/Page.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellContent.cs
Xamarin.Forms.Core/Shell/ShellItem.cs
Xamarin.Forms.Core/Shell/ShellSection.cs
Xamarin.Forms.Core/TemplatedPage.cs
Xamarin.Forms.Core/TemplatedView.cs
Xamarin.Forms.Core/VisualElement.cs
Xamarin.Forms.Core/Xaml/Diagnostics/VisualDiagnostics.cs
Xamarin.Forms.Xaml.UnitTests/Issues/Gh11334.xaml
Xamarin.Forms.Xaml.UnitTests/Issues/Gh11334.xaml.cs
Xamarin.Forms.Xaml.UnitTests/Issues/Gh11335.xaml
Xamarin.Forms.Xaml.UnitTests/Issues/Gh11335.xaml.cs
Xamarin.Forms.Xaml/XamlLoader.cs

- send index on VTChange.Add and Remove
- register LV cells as LogicalChildren
- fixes #11334
- fixes #11335
- fixes [AB#1152749](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1152749)
- fixes [AB#1152814](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1152814)
None
None
Not applicable
> VS bug [#1173455](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1173455)

[C] index on VTChanges

---

build/steps/build-osx.yml

When the YML file from 4.6 was merged up to 4.7 the duplicate 'Copy iOS Files for UITest' wasn't removed which is removing the dSYM files that were already copied up 
- iOS
- Ensure that the dsyms folder is over 60 MBs or so and actually has the dSYM files in it

[yml] Remove second copy of UI Tests that deletes dsyms

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11769.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core.UnitTests/ShellUriHandlerTests.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellUriHandler.cs
Xamarin.Forms.Platform.UAP/Shell/ShellItemRenderer.cs
Xamarin.Forms.Platform.UAP/Shell/ShellRenderer.cs
Xamarin.Forms.Platform.UAP/Shell/ShellSectionRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellRenderer.cs

Don't hard crash if user hasn't specified Items for Shell and make that behavior work more consistently across all platforms
- fixes #11769
- iOS
- Android
- UWP

Fix Shell to better handle delayed setting of Items

---

Xamarin.Forms.Controls/GalleryPages/GradientGalleries/GradientsGallery.cs
Xamarin.Forms.Controls/GalleryPages/GradientGalleries/UpdateGradientColorGallery.xaml
Xamarin.Forms.Controls/GalleryPages/GradientGalleries/UpdateGradientColorGallery.xaml.cs
Xamarin.Forms.Core/GradientBrush.cs
Xamarin.Forms.Core/VisualElement.cs

Detect GradientStop changes and update the Brush.
- fixes #11898 
None
None
Launch Core Gallery and navigate to the brushes gallery. Select the Gallery "Update Brush Colors Gallery" and tap the "Update Colors" Button. If the GradientBrush is updated, the test has passed.

[Core] Notify changes in a GradientStop (Color, Offset) 

---

Xamarin.Forms.Build.Tasks/XamlCTask.cs
Xamarin.Forms.Core/Internals/ResourceLoader.cs

Context: https://github.com/jonathanpeppers/Xamarin.Forms.Benchmarks
I noticed a C# binding by hand is still a bit faster than bindings
written in Xaml in various forms:
|         Method |     Mean |     Error |    StdDev |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|--------------- |---------:|----------:|----------:|-------:|-------:|------:|----------:|
|  ByHandOneTime | 3.210 us | 0.0836 us | 0.0553 us | 0.5531 | 0.0038 |     - |   3.42 KB |
|   TypedOneTime | 4.087 us | 0.0560 us | 0.0370 us | 0.8163 | 0.0076 |     - |   5.05 KB |
| RegularOneTime | 5.375 us | 0.0117 us | 0.0077 us | 0.9079 | 0.0076 |     - |   5.61 KB |
|         ByHand | 5.552 us | 0.6508 us | 0.4305 us | 0.5951 | 0.1450 |     - |   3.71 KB |
|          Typed | 6.992 us | 0.4679 us | 0.3095 us | 0.9155 | 0.3052 |     - …

[xamlc] add a new ResourceLoader.IsEnabled check

---

Xamarin.Forms.Build.Tasks/DebugXamlCTask.cs
Xamarin.Forms.Build.Tasks/XamlCTask.cs
Xamarin.Forms.Build.Tasks/XamlTask.cs
Xamarin.Forms.Xaml.UnitTests/MockCompiler.cs

I was building the Control Gallery and saw:
XamlCTask
Compiling Xaml, assembly: obj\Debug\netstandard2.0\Xamarin.Forms.Controls.dll
Adding searchpath C:\Users\jopepper\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref
Adding searchpath C:\Users\jopepper\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref
Adding searchpath C:\Users\jopepper\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref
Adding searchpath C:\Users\jopepper\.nuget\packages\newtonsoft.json\12.0.3\lib\netstandard2.0
Adding searchpath C:\Users\jopepper\.nuget\packages\nunit\3.12.0\lib\netstandard2.0
Adding searchpath C:\Users\jopepper\.nuget\packages\xam.plugin.deviceinfo\3.0.2\lib\netstandard1.0
Adding searchpath C:\Users\jopepper\.nuget\packages\xam.plugin.deviceinfo\3.0.2\li …

[xamlc] fix duplicate Mono.Cecil search paths

---

build.cake
build/provisioning/xcode.csx

Switch to using the XCode method
Ensure XCode provisions successfully

Remove references to XreItem when using XCODE on Provisionsator

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8836.cs
Xamarin.Forms.Platform.UAP/FormsTextBox.cs

Clear Button Visibility set before the control is loaded, in code or XAML wasn't being honored.
This change adds updating the visibility based on the ClearButtonVisible state during OnApplyTemplate since that is the first time the clear button could be removed.
- fixes #11946 
None
- iOS
- Android
- UWP
None
Not applicable
Open issue page 8836 and follow the instructions

[UWP] Fix 11946 Entry Clear Button Visibility initial value not honored

---

Xamarin.Forms.Platform.iOS/Extensions/UIViewExtensions.cs
Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs

Block the scroll if is swiping a SwipeView on iOS (same behavior as in Android).
- fixes #11651 
- fixes #11932
None
- iOS
None
Launch Core Gallery and navigate to the SwipeView Galleries. Select the CollectionView (or any other gallery using a parent with scroll like a ListView or ScrollView), and scroll. Verify that you can scroll without problems, and also open a SwipeView. Try to scroll swiping the SwipeView and must not be possible.

[iOS] Block the scroll if is swiping a SwipeView 

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11209.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11209.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs

Fix Gesture issue with SwipeView.
- fixes #11209 
None
- iOS
None
Launch Core Gallery and navigate to the issue 11209. Tap any item from the list. If navigate to another page, the test has passed.

[iOS] Fix Gesture issue with SwipeView

---

Xamarin.Forms.Platform.iOS/ContextActionCell.cs

Fix another NRE when trying to clear ContextActions of a ListView (on iOS)
- fixes #11943
None
- iOS
None
Not applicable
See #11943 for repro steps

[iOS] Fixing another NRE in ContextActionCell

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9682.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9682.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellBackButtonBehavior.cs

- retry text request on API 19
- change monkeys to load all from internal URLS
- iOS
- Android
- UWP
run the android tests a few times against this PR to see if any failures happen from 
- MonkiesShouldLoad
- CommandTest
- CommandWorksWhenItsTheOnlyThingSet

UI Test reliability updates

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7823.cs
Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs
Xamarin.Forms.Platform.Android/ViewExtensions.cs
Xamarin.Forms.Platform.Android/VisualElementTracker.cs

PR #8032 broke Labels inside of Frames in ListView ViewCells - this can be seen by running UI test for issue #1415; the ListView items should have text in them, and after #8032 they do not.
These changes restore the functionality used in the #1415 test while preserving the corner radius clipping changes from #8032.
Text not displaying inside of Frames used as the DataTemplate for a ListView's ViewCells.
None
- Android
None
Not applicable
Automated test for #7823 (should still pass); also make sure to run #1415 (sadly, manual) and verify that text displays in the ListView items.

Make Frames with Labels work in ListViews again

---

Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
Xamarin.Forms.Core/Xaml/ValueConverterProvider.cs
Xamarin.Forms.Xaml.UnitTests/Issues/Gh11711.xaml
Xamarin.Forms.Xaml.UnitTests/Issues/Gh11711.xaml.cs

Wrap FormatException while Parsing built-in types, and wrap the exception into a XamlParseException, or BuildException, with additional information about line info
- fixes #11711
None
None
Not applicable

[X] Wrap FormatException with lineInfo

---

Xamarin.Forms.ControlGallery.WPF/Issue11923.cs
Xamarin.Forms.ControlGallery.WPF/Xamarin.Forms.ControlGallery.WPF.csproj
Xamarin.Forms.Platform.WPF/Controls/FormWindow.cs
Xamarin.Forms.Platform.WPF/Properties/AssemblyInfo.cs

Fixed NRE in FormsWindow on WPF.
- fixes #11923 
None
- WPF
None
Not applicable
To test the issue should uncomment the code from the Issue11923.cs and change the WPF App entry point. Execute the App and a Window without any exception must appear.

[WPF] Fixed NRE in FormsWindow

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/PerformanceGallery/PerformanceGallery.cs

Stop running the performance rendering tests. These are slow and not producing reliable results.

[Tests] Stop running the performance rendering tests

---

Xamarin.Forms.Platform.Android/Extensions/BrushExtensions.cs

Fixed incorrect border applying a SolidColorBrush in some cases on Android.
None
- Android
None
Launch Core Gallery and navigate to the brushes gallery. Select the SolidColorBrushConverterGallery and verify that applying a `Color` or a `SolidColorBrush` has exactly the same result in Layouts.

[Android] Fixed incorrect border applying a SolidColorBrush in some cases

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8279.cs
Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs

As requested in the ticket #8279, I've enhanced ListView ScrollTo method to scroll to a group with no child and also handled other use-cases discussed here: https://github.com/xamarin/Xamarin.Forms/issues/8279#issuecomment-547885319
- fixes #8279
My initial idea was to change the `GetGroupAndIndexOfItem()` method of `TemplatedItemsList.cs` to return corresponding group if there's no child or item found (we should be sending item index as zero instead of -1 to consider the groups with no child or no item found). The existing implementation returns `new Tuple<int, int>(groupIndex, -1);` which was the problem. But I noticed that `GetGroupAndIndexOfItem()` method is being used by other platform's ListViewRenderer and this approach also required further changes in the corresponding renderer to …

Fixed - 8279 - [Enhancement] ListView ScrollTo with empty groups - Android

---

Xamarin.Forms.ControlGallery.WPF/Xamarin.Forms.ControlGallery.WPF.csproj
Xamarin.Forms.Platform.WPF/Properties/AssemblyInfo.cs

There are currently assembly version missmatches when working with the WPF .NET Core backend. 
The modifications to the assembly version information in this PR solve these issues when running the control gallery application. This is more of a workaround currently and I hope this could help in finding a longterm solution.
Some things I currently dont understand:
* Why is the control gallery explicitly asking for Version 2.0.0.0 of the WPF platform assembly. I could not find a reference to this version anywhere and a runtime error occures when I change the version to something else.
* In the Xamarin.Forms.Platform.WPF project we have to set `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>`, otherwise the following compile error will show up: "The specified version string does not conform …

[WPF] Fix assembly version conflicts

---

Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs

Changes in CollectionViewSource dispose logic on UWP.
- fixes #11908 
None
- UWP
None
Not applicable
Launch Core Gallery and navigate to the CollectionView galleries. Use the profiler to debug and verify that the CollectionViewSource is disposed.

[UWP] Changes in CollectionViewSource dispose logic

---

Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs

The move to WKWebView on iOS broke the ability to load local html documents. These changes reinstate that ability.
- (re)fixes Bugzilla 32033
None
- iOS
None
Not applicable
Manual test 32033 (the first option).

Reinstate loading of local HTML files in WKWebViewRenderer

---

Xamarin.Forms.Core/ListView.cs

https://github.com/xamarin/Xamarin.Forms/commit/975577e837983d5fe656e2bf9caed893c42ffe97#diff-629e73745c456d7bcf063b0fb1290d62R18
Added LogicalChildren to ListView. 
On iOS when measuring a row the ListViewRenderer will descend the hierarchy of LogicalChildren and then dispose of all renderers on those LogicalChildren. 
ListView can have LogicalChildren that aren't VisualElements (SwitchCell) so this can cause an exception when trying to dispose. AFAICT this is a very specific issue related to running the application while Xamarin.UITest is observing it. When we retrieve the AccessibilityLabel from the nested UITableView this causes the nested UITableView to saturate with data. But this only happens when running from a state where the app is being observed by Xamarin.UITest
If you …

Check if Logical Child is VE in ListViewRenderer

---

Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs

This is addendum of #11933 for Tizen. 
With this PR, I've confirmed that the transformation of views works well as follows.
**BEFORE** | **AFTER**
--- | ---

[Tizen] Fix the order of the scale and rotation

---

Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs

As per #11965 there is a bug causing a NullReference NRE, but is only seen in App Center logs. Therefore, I haven't been able to reproduce. This seems to be the only place for the root cause, and I guess it doesn't hurt to add a null check here and see if this fixes it.
If you think differently, feel free to close this one :)
- fixes #11965
None
- iOS
None
Not applicable
Also none; this is the worst PR ever.

[iOS] Add null-check to Entry

---

Xamarin.Forms.Xaml.UnitTests/Issues/Bz47950.xaml.cs
Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs

Add a `TrySetPropertyValue()` that doesn't require the parsing and hydration context. For most case, it will be enough if the serviceProvider contains an `IValueConverterProvider` and a default `IValueConverterProvider`. (see https://github.com/xamarin/Xamarin.Forms/blob/main/Xamarin.Forms.Xaml/XamlServiceProvider.cs). More complex cases might require extra services.
- fixes [AB#1192221](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1192221)
None
None

[X] Add a TrySetPropertyValue overload for HR

---

Xamarin.Forms.Platform.Android/Platform.cs

While we still can't seem to reproduce #10801 under controlled conditions to find a root cause, it's clear that it's occurring when the platform attempts to measure a renderer which has already been disposed. These changes add a disposal check before rendering to avoid crashing; if the renderer has already been disposed, the method returns a size of zero. 
- fixes #10801
None
- Android
None
Not applicable
Still can't reproduce the issue locally, so no tests at the moment.

If the element's renderer has already been nulled or disposed, request zero space for it

---

Xamarin.Forms.Platform.Tizen/FormsApplication.cs

This PR fixes below Tizen 4.0 regression issue.
- In Tizen 4.0, `Application.Properties` did not work properly due to an issue related to `IsolatedStorageFile` support.  Thus, if you used ` Application.Properties`  (or on exiting the app), you will find the following exception in the log:
```
W/Xamarin ( 8668): XamarinLogListener.cs: Warning(15) > [Application] Exception while saving Application Properties: System.AggregateException: One or more errors occurred. (Access to the path '/opt/usr/home/owner/IsolatedStorage/inhsmjuv.isa/skix3szd.kzj' is denied.) ---> System.UnauthorizedAccessException: Access to the path '/opt/usr/home/owner/IsolatedStorage/inhsmjuv.isa/skix3szd.kzj' is denied. ---> System.IO.IOException: Permission denied
W/Xamarin ( 8668):    --- End of inner exception stack …
```

[Tizen] Fixed Tizen 4.0 regression issue

---

Xamarin.Forms.Platform.Tizen/Forms.cs

Since, the SystemInfo API key to get the type of device (```http://tizen.org/system/device_type```) is not available on Tizen 4.0, we uses profile to decide the type of device for Tizen 4.0.
None
None
- Tizen
None

[Tizen] Fixed getting the device type

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11311.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/CollectionView/StructuredItemsViewController.cs

If the UICollectionView hasn't actually been loaded yet (e.g., if it's on a not-yet-visible tab), when the footer attempts to determine its vertical position (and asks the UICollectionView for the height of its content), the UICollectionView will throw an exception. 
This change adds a check to see if the UICollectionView has been loaded and attached to a window yet; if not, it reports a height of zero for the purposes of positioning the footer.
- fixes #11311
None
- iOS
None
Not applicable
Automated test (Issue11311)

Check UICollectionView visibility before asking it for content height

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
azure-pipelines.yml
build/steps/build-nuget.yml

Change nightlies and nugets to generate from main-xf
Update related documentation
- Make sure @rmarinho is happy

Shift YAML and contributor documents to reference main-xf in preparation for handler branches

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11081.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11081.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems

Disable animation scrolling to initial position in CarouselView. With a high number of items, the time to complete the animation is noticeable.
- fixes #11081
Added `AnimateInitialPosition` property to `CarouselView`.
- iOS
- Android
- UWP
None
Not applicable
Launch Core Gallery and navigate to the issue 11081. If the selected Item is the Item 2, directly without animations, the test has passed.

Disable animation scrolling to initial position in CarouselView

---

Stubs/Xamarin.Forms.Platform.cs
Xamarin.Forms.ControlGallery.iOS/RegistrarValidationService.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Helpers/ViewHelper.cs
Xamarin.Forms.Platform.iOS/Renderers/PhoneFlyoutPageRenderer.cs

- Test All Pages failing on gallery load which was causing gallery to never load so all tests were showing green
- add constructor for iOS renderers so they don't get linked out
- fix NonAppCompat on android for MDP
- iOS
- Android
- make sure iOS tests run

Fix iOS Gallery

---

Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/HorizontalSwipeThresholdGallery.xaml
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/HorizontalSwipeThresholdGallery.xaml.cs
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeThresholdCustomSwipeItemGallery.xaml
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeThresholdCustomSwipeItemGallery.xaml.cs
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeThresholdGallery.cs
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeViewGallery.cs
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/VerticalSwipeThresholdGallery.xaml
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/VerticalSwipeThresholdGallery.xaml.cs
Xamarin.Forms.Core/SwipeView.cs
Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs

Add **Threshold** BindableProperty to SwipeView.
- fixes #8941
- fixes #8974
```
public class SwipeView 
{
public double Threshold { get; set; }
}
```
- iOS
- Android
None
Launch Core Gallery and navigate to the SwipeView samples. Select the added Threshold samples to test with horizontal and vertical swipes.

Add Threshold BindableProperty to SwipeView

---

Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/SlideFlyoutTransition.cs

The UISplitView implementation of Shell on iOS doesn't really conform to how a UISplitView works on iOS. For example #8527.
The UISplitView is a hierarchical navigation controller that will collapse the left pane and the right pane into a stack of ViewControllers inside a UINavigationController when the user goes into SplitView mode. This breaks the app because the shell isn't configured to react to this type of change
If we want Shell to react this way then we should implement this at the xplat level so that it works this way across all platforms. 
-  partially fixes #8527
- iOS
There shouldn't be any. This should result in a users application staying more consistent when the app is used on an iPad and we don't have to implement everything twice on iOS
One of these is a …

[Shell] Don't use SplitView for iPad

---

Xamarin.Forms.Controls/GalleryPages/ShapesGalleries/ClipCornerRadiusGallery.xaml
Xamarin.Forms.Controls/GalleryPages/ShapesGalleries/ClipCornerRadiusGallery.xaml.cs
Xamarin.Forms.Controls/GalleryPages/ShapesGalleries/ShapesGallery.cs
Xamarin.Forms.Core.UnitTests/GeometryTests.cs
Xamarin.Forms.Core.UnitTests/Markup/DefaultBindablePropertiesTests.cs
Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
Xamarin.Forms.Core/Shapes/EllipseGeometry.cs
Xamarin.Forms.Core/Shapes/GeometryGroup.cs
Xamarin.Forms.Core/Shapes/LineGeometry.cs
Xamarin.Forms.Core/Shapes/PathGeometry.cs
Xamarin.Forms.Core/Shapes/RectangleGeometry.cs
Xamarin.Forms.Core/Shapes/RoundRectangleGeometry.cs
Xamarin.Forms.Core/VisualElement.cs

Added `RoundRectangleGeometry` Geometry.
- fixes #11151
Added `RoundRectangleGeometry`.
```
<Image
Source="crimson.jpg">
<Image.Clip>
<RoundRectangleGeometry
CornerRadius="12"
Rect="0, 0, 150, 150"/>
</Image.Clip>
</Image>
```
- iOS
- Android
- UWP
None
Launch Core Gallery and navigate to the shapes gallery. Select the "Clip CornerRadius Gallery", modify the corner radius and verify that everything works as expected.

[Core] Added RoundRectangleGeometry

---

Xamarin.Forms.Core/VisualElement.cs

Updates the constructor of the `VisualElement` from `internal` to `protected internal`. This allows external code to inherit directly from the `VisualElement` instead of the `View`.
The Xamarin Community Toolkit requires access to some of the internal objects of the Xamarin.Forms platform. I am currently working on migrating the Popup Control Pull Request (#9616) to the Xamarin Community Toolkit (Xamarin/XamarinCommunityToolkit#292) as I discussed with @PureWeen @jsuarezruiz and @jfversluis the other week. In the original Pull Request (#9616) to Xamarin.Forms @myroot suggested we have the `BasePopup` inherit from `VisualElement` instead of `View`. This would prevent developers from adding the `BasePopup` to a `StackLayout` since it's children accept a standard `View`. This feedback made a …

Add protected Accessor to VisualElement Constructor

---

Xamarin.Forms.Core/Shapes/Shape.cs

Changed the `StrokeThickness` default value to 1.0d, as in other frameworks (UWP, etc).
- fixes #12081 
- fixes #12082
- fixes #12083
None
None
Launch Core Gallery on iOS 14. Navigate to the Shapes Gallery and select the Line sample. If all the lines are rendering (see attached screenshot), the test has passed.

Fix Shapes drawing issue on iOS 14

---

Xamarin.Forms.Platform.Tizen/PopupManager.cs
Xamarin.Forms.Platform.Tizen/Renderers/EditorRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/LabelRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/RadioButtonRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/SearchBarRenderer.cs
Xamarin.Forms.Platform.Tizen/ThemeConstants.cs
Xamarin.Forms.Platform.Tizen/ThemeManager.cs

This PR includes two changes as below
- Fix DisplayActionSheet to be displayed properly on Mobile(F-hub)
- Add null check for Text value
None
None
- Tizen
| F-hub(Before) | F-hub(After) |
|--|--|
| <img src="https://user-images.githubusercontent.com/20968023/93738163-0f0ec280-fc20-11ea-8586-72a766072798.png" width="250" /> | <img src="https://user-images.githubusercontent.com/20968023/93738168-10d88600-fc20-11ea-876e-6987c3bfe341.png" width="250" /> |
And, It will be displayed on other profiles as following.
- TV 
- Mobile
- Wearable
The action items will be shown as a button without any style.

[Tizen] Fix the DisplayActionSheet

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11963.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Forms.cs
Xamarin.Forms.Platform.iOS/Renderers/TimePickerRenderer.cs

Fix the TimePicker crash on iOS14 by forcing the PreferredDatePickerStyle to UIDatePickerStyle.Wheels.
- fixes #11963
None
- iOS
None
Not applicable
Use Xcode12, iOS14 device, and Xamarin.iOS for IOS14.
Go to issue 11943, click on the date , make sure the time picker wheels appear and you able to select a time.
make sure it also works on iOS13

[iOS] Fix crash with TimePicker on iOS14 

---

build.cake
build/provisioning/provisioning.csx
build/provisioning/xcode.csx
build/steps/build-osx.yml

Pin 4.8.0 OSX build lane to Xcode 11.7
The nugets from this lane will still build using Xcode 12.0 but if there are Xcode 11.7 incompatible APIs the OSX lane will fail
- builds are green

Pin 4.8.0 Xcode

---

Xamarin.Forms.Core/Device.cs
Xamarin.Forms.Core/IPlatformInvalidate.cs
Xamarin.Forms.Core/Layout.cs
Xamarin.Forms.Core/VisualElement.cs
Xamarin.Forms.Platform.Android/Forms.cs
Xamarin.Forms.Platform.Android/Platform.cs
Xamarin.Forms.Platform.Android/VisualElementTracker.cs
Xamarin.Forms.Platform.UAP/Forms.cs
Xamarin.Forms.Platform.UAP/LayoutRenderer.cs
Xamarin.Forms.Platform.UAP/WindowsBasePlatformServices.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Xamarin.Forms.Platform.iOS/Forms.cs
Xamarin.Forms.Platform.iOS/Platform.cs

To avoid excessive re-layouts, any property changes which trigger a layout in a Forms Layout (StackLayout, FlexLayout, etc.) are currently batched up and executed later on the UI thread. While this avoids "layout storms", it also introduces a slight delay in layout changes in the UI and in some rare cases can cause consistency issues. It also means that for many UI changes the native layout engine ends up being invoked an extra time to handle the queued layout changes.
These changes handle the queued layout changes as part of the next measure/layout pass of the native engine on the supported platforms (UWP, iOS, and Android) rather than queueing them up on the UI thread for later processing. This reduces the number of measure/layout passes on those platforms, and eliminates some of the …

Resolve Layout changes during native measure/arrange pass

---

.nuspec/Xamarin.Forms.targets

This only warns for UWP class library projects if you target less than 14393. Class libraries doesn't require being built for 17763. That's a requirement for an app. 
- fixes #10368
None
- UWP
No useless warning that can't otherwise be disabled/removed
Not applicable
Build a UWP class library that targets 10.0.17134 and observe the build error before/after.
Build a UWP app, and notice there's no change in warnings.

Only require  14393+ for UWP class libraries #10368

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12153.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/FontExtensions.cs
Xamarin.Forms.Platform.UAP/FontImageSourceHandler.cs

Fix crash on UWP that was introduced by PR #11741. The crash happened when fonts were used on UWP that were not embedded.
- fixes #12153 
None
- UWP
None
Not applicable

[UWP] Fix crash when specifying non-embedded font families (fixes #12153)

---

Xamarin.Forms.ControlGallery.Tizen/Xamarin.Forms.ControlGallery.Tizen.csproj
Xamarin.Forms.Material.Tizen/Xamarin.Forms.Material.Tizen.csproj

This PR is to update Tizen.NET.MaterialComponents package to [0.9.9-pre2](https://github.com/TizenAPI/Tizen.NET.MaterialComponents/releases/tag/beta-0.9.9-pre2) for supporting mobile(F-hub).
None
None
- Tizen
| Mobile | Mobile(F-hub) |
|--|--|
| <img src="https://user-images.githubusercontent.com/20968023/94402862-8ce64700-01a7-11eb-814e-0bec5edd9f22.png" width="300" /> | <img src="https://user-images.githubusercontent.com/20968023/94402832-82c44880-01a7-11eb-99c5-9582cfb99958.png" width="300" /> |
Not applicable

[Tizen] Update Tizen.NET.MaterialComponents

---

Xamarin.Forms.Platform.Tizen/Native/CollectionView/CarouselView.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/CollectionView.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/ItemAdaptor.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/ItemTemplateAdaptor.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/ViewHolder.cs
Xamarin.Forms.Platform.Tizen/ThemeConstants.cs

* This PR support VisualState to Items in CollectionView.
On Tizen Platform , CollectionView has visual effect about focused and selected, but it can't be customized by App developer. 
This changes make support VisualState on Items of CollectionView. so app developer can define visual state about focused and selected
- fixes #12225 
None
- Tizen
None
|before|after|
|-|-|
|![visualstate-old](https://user-images.githubusercontent.com/1029155/94379680-f09f4e80-016c-11eb-98fd-add69b4cd3f2.gif)|![visualstate](https://user-images.githubusercontent.com/1029155/94379684-f7c65c80-016c-11eb-83a5-e6d52289f097.gif)|

[Tizen] Support VisualState on Items of CollectionView

---

Stubs/Xamarin.Forms.Platform.cs
Xamarin.Forms.Platform.Tizen/Native/FlyoutPage.cs
Xamarin.Forms.Platform.Tizen/Properties/AssemblyInfo.cs
Xamarin.Forms.Platform.Tizen/Renderers/FlyoutContainer.cs
Xamarin.Forms.Platform.Tizen/Renderers/FlyoutPageRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/MasterDetailPageRenderer.cs
Xamarin.Forms.Platform.Tizen/StaticRegistrar.cs

This PR is an addendum of #12073 for Tizen.
- fixes #11857 (tizen)
Added:
```namespace Xamarin.Forms.Platform.Tizen```
- class FlyoutContainer
- class FlyoutPageRenderer
Changed:
```namespace Xamarin.Forms.Platform.Tizen.Native```
- class MasterDetailPage => class FlyoutPage
- Tizen
None
Not applicable

[Tizen] Replace MDP to FlyoutPage

---

Xamarin.Forms.Platform.iOS/ViewRenderer.cs

**NSInternalInconsistencyException**: NSWindow: -_oldFirstResponderBeforeBecoming is not a valid message outside of a responder's implementation of -becomeFirstResponder.
https://developer.apple.com/documentation/appkit/nsresponder/1526750-becomefirstresponder?language=objc
https://developer.apple.com/documentation/appkit/nsresponder/1532115-resignfirstresponder?language=objc
Use the **NSWindow makeFirstResponder:** method, not this method, to make an object the first responder. Never invoke this method directly.
None
- MacOS
None
Not applicable

MacOS - Fix crash when invoking VisualElement.Focus()

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11963.cs
Xamarin.Forms.Platform.iOS/Renderers/DatePickerRenderer.cs

Fix the DatePicker crash on iOS14 by forcing the PreferredDatePickerStyle to UIDatePickerStyle.Wheels.
- fixes #11963
None
- iOS
None
Not applicable
Use Xcode12, iOS14 device, and Xamarin.iOS for IOS14.
Go to issue 11943, click on the date , make sure the date picker wheels appear and you able to select a time.
make sure it also works on iOS13

[iOS] Fix DatePicker on iOS14

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11962.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12134.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/issue3262.cs
Xamarin.Forms.Platform.iOS/Forms.cs
Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs

- fixed WkWebViewRenderer to check for double dispose
- fixed WkWebViewRenderer to properly remove and dispose of associated renderers
- After I started cleaning up the WkWebViewRenderer the UI tests around cookie management started failing on iOS11 so I had to add less then ideal hacks to make all that work. WkWebView and Cookie management on iOS 11 is really really quirky. I'm guessing that it was working fine before the dispose because the leaked WkWebView probably was keeping around a reference to the process pool which caused it to all just work. 
- fixes #11962 
- fixes #12134
- iOS
- ui tests pass

Fix WkWebViewRenderer to properly dispose and clear renderers

---

Xamarin.Forms.Platform.UAP/Shell/ShellRenderer.cs

On the first initial opening of the side pane UWP resets the light layer back to the default color. This sets the color after the pane has opened just to ensure the back drop color has propagated to the light layer
- fixes #12018 
- UWP
- test setting back drop layer on uwp

Set Backdrop Color after Pane Opened

---

Xamarin.Forms.Controls/CoreGalleryPages/RadioButtonCoreGalleryPage.cs
Xamarin.Forms.Controls/GalleryPages/RadioButtonGalleries/RadioButtonGalleries.cs
Xamarin.Forms.Core.UnitTests/DragGestureRecognizerTests.cs
Xamarin.Forms.Core.UnitTests/DropGestureRecognizerTests.cs
Xamarin.Forms.Core.UnitTests/RadioButtonTests.cs
Xamarin.Forms.Core/ExperimentalFlags.cs
Xamarin.Forms.Core/RadioButton.cs

Removed RadioButton Experimental flag.
It is no longer necessary to use the experimental flag to use RadioButton.
Launch Core Gallery and navigate to the RadioButton Gallery. Select any sample. If can navigate to the sample, the test has passed.

Removed RadioButton Experimental flag

---

Xamarin.Forms.Controls/GalleryPages/ShapesGalleries/ClipGallery.xaml
Xamarin.Forms.Core/Shapes/RoundRectangleGeometry.cs

Fixed wrong RoundRectangleGeometry calculation (Top Left Corner).
- fixes #12285 
None
None
Launch Core Gallery and navigate to the shapes gallery. Select the Clip Gallery and verify that the Clip using RoundRectangleGeometry is correct.

[Core] Fixed wrong RoundRectangleGeometry calculation

---

Xamarin.Forms.Platform.UAP/ViewToRendererConverter.cs

ViewToRendererConverter was triggering a cross-platform layout pass from its MeasureOverride ... override, which resulted in a layout cycle. This change removes that layout pass, which appears to now be unnecessary. 
The original layout call was added here:
https://github.com/xamarin/Xamarin.Forms/pull/2586/files#diff-70db430b24c262668bdb1ee9c4ad76ccR96
The call was added to address TitleView layout issues which I _suspect_ may have been a symptom of deferring layout changes on the UI thread; or they may have been a symptom of some other bug entirely. Either way, after removing this line the TitleView layout still appears to be correct.
- fixes failing test 57910 on UWP
None
- UWP
None
Not applicable
Automated test 57910

Fix layout cycle in ViewToRendererConverter

---

Xamarin.Forms.Core/Element.cs
Xamarin.Forms.Core/Internals/INameScope.cs
Xamarin.Forms.Core/Internals/NameScope.cs

[C] INamescope.UnregisterName
note that it only unregister the name, and do not even try to invalidate
the references to this name.
- fixes #12401
Added:
- void INamescope.UnregisterName(string name);
None
Not applicable

[C] INamescope.UnregisterName

---

Xamarin.Forms.Core/FlyoutPage.cs
Xamarin.Forms.Core/IFlyoutPageController.cs

Separate out IMasterDetailPageController  from IFlyoutPageController so it's not an ABI break
- fixes #12224
- iOS
- Android
- UWP
- I'll reach out to user to verify

Leave IMasterDetailPageController intact

---

Xamarin.Forms.Core.UnitTests/ShellNavigatingTests.cs
Xamarin.Forms.Core.UnitTests/ShellTestBase.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellSection.cs
Xamarin.Forms.Platform.Android/Renderers/ShellItemRendererBase.cs
Xamarin.Forms.Platform.UAP/Shell/ShellSectionRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs

This PR adds a number of optimization for interpreting a new route and trying to minimize the amount of operations that happen 
- When popping multiple pages on Shell via `GotoAsync("../..")` just remove the middle pages before popping the currently visible page. This way OnAppearing won't fire on pages being removed and they won't appear and then disappear
- If you're at `/page1/page2' and then you want to navigate to `/page1/page3' it will now first push page3 and then remove page2 so that you never see page 1
- If you're at `/page1/page2/page3` and you navigate to `/page1/page3' it'll just remove page2 
- iOS
- Android
- UWP
Users will no longer see the middle when the user is requesting that multiple pages pop. The middle pages will no longer throw …

When popping multiple pages remove middle pages first

---

Xamarin.Forms.Core/RadioButton.cs
Xamarin.Forms.Platform.WPF/Renderers/RadioButtonRenderer.cs

RadioButton is no longer implementing `IButtonController`.
- fixes #12405 
None
- WPF
None
Not applicable
Launch Core Gallery and navigate to the RadioButton Galleries. Select any sample and then tap any RadioButton. Without exceptions the test has passed.

[WPF] Fix RadioButton crash

---

Xamarin.Forms.Core/PlatformConfigurationRegistry.cs

This PR changes the visibility of the ` PlatformConfigurationRegistry<TElement>` class to public decorated with the `EditorBrowsableState.Never` attribute. We need this into the XCT.
- Related to #12136

Make OnPlatform helpers public

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12246.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Material.iOS/MaterialTextManager.cs

If we are on iOS 14, and we have multiple material text entry fields of the same color, and any of them are password fields, setting them to the same TextColor value will cause the application to hang when a password field loses focus. 
So to work around this, we make an imperceptible adjustment to the alpha value of the color each time we set it; that way, none of the text entry fields have _exactly_ the same color and we avoid running into the bug. 
This is a temporary fix until the underlying iOS/Material issues are fixed. 
- fixes #12246
None
- iOS
None
Not applicable
Automated UI test

Workaround for iOS material entry application freeze

---

Xamarin.Forms.Platform.MacOS/Renderers/BoxViewRenderer.cs

Fix BoxView Background issue in macOS.
- fixes #12430 
None
- macOS
None
Launch Core Gallery in macOS and navigate to the BoxView Gallery. If renders correctly, the test has passed.

[macOS] Fix BoxView Background issue

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12222.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.MacOS/Renderers/ButtonRenderer.cs

Change Bordered in NSButton in case necessary (using a background a border color).
- fixes #12222 
None
- macOS
None
Launch Core Gallery and navigate to the issue 12222. If the button renders correctly in all cases, the test has passed.

[macOS] Change Bordered in NSButton in case necessary

---

Xamarin.Forms.Platform.Tizen/Extensions/EntryExtensions.cs
Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
Xamarin.Forms.Platform.Tizen/ThemeConstants.cs

This PR is to fix entry cursor position issue
None
None
- Tizen

[Tizen] Fix the text selection issue of Entry

---

Xamarin.Forms.Core/PlatformConfiguration/TizenSpecific/ScrollView.cs
Xamarin.Forms.Platform.Tizen/Renderers/ScrollViewRenderer.cs

This PR is about supporting the scroll step (both vertical and horizontal) to move `ScrollView` by key event on Tizen. This can be especially useful when moving the scroll of the scroll view on a remote control keystroke based TV device. As you can see in the screenshot below, you can adjust the `VerticalScrollStep` to make the scroll view move smoother.
- **Before (default)**
- **After (adjust the vertical scroll step properly)**
This Tizen platform-specific is used to set the scroll step to move `ScrollView` by key event. It can be consumed from XAML and C# as follows.
- XAML
```xml
<ContentPage ...
xmlns:tizen="clr-namespace:Xamarin.Forms.PlatformConfiguration.TizenSpecific;assembly=Xamarin.Forms.Core">
<ScrollView tizen:VerticalScrollStep="500">
....
</ScrollView>
</ContentPage>
```
- …

[Tizen] Support Vertical/HorizontalScrollStep to ScrollView

---

.nuspec/Xamarin.Forms.nuspec
Xamarin.Forms.Platform.Tizen/Extensions/BrushExtensions.cs
Xamarin.Forms.Platform.Tizen/Forms.cs
Xamarin.Forms.Platform.Tizen/Native/Box.cs
Xamarin.Forms.Platform.Tizen/Renderers/LayoutRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/PageRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs
Xamarin.Forms.Platform.Tizen/SkiaSharp/BoxViewRenderer.cs
Xamarin.Forms.Platform.Tizen/SkiaSharp/CanvasViewRenderer.cs
Xamarin.Forms.Platform.Tizen/SkiaSharp/FrameRenderer.cs
Xamarin.Forms.Platform.Tizen/SkiaSharp/IBackgroundCanvas.cs
Xamarin.Forms.Platform.Tizen/SkiaSharp/ImageRenderer.cs
Xamarin.Forms.Platform.Tizen/StaticRegistrar.cs
Xamarin.Forms.Platform.Tizen/Xamarin.Forms.Platform.Tizen.csproj

This PR adds Brushes (#9220) Tizen implementation. 
This change also allows the user to choose whether to use the SkiaSharp-based renderer via the init option. Comparing the existing renderers, SkiaSharp-based renderer will bring huge functional advantages including Shapes, Brush, BorderElement and enhancing limited features which has been existed on default renderers.
To enable the SkiaSharp-based renderers, use `Forms.Init()` as shown below. (The default is `false`.)
```cs
var option = new InitializationOptions(app) { UseSkiaSharp = true }; 
Forms.Init(option);
```
Currently available SkiaSharp-based renderers are as follows.
- LayoutRenderer (StackLayout, AbsoluteLayout, Grid, ...)
- PageRenderer (ContentPage)
- FrameRenderer
- BoxViewRenderer
- ImageRenderer
- fixes (partially) #2452 …

[Tizen] Support Brushes to Tizen

---

Xamarin.Forms.Core/ContentPropertyAttribute.cs

fix attribute usage on ContentProperty

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12126.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12320.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/ShellItemRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs

When replacing the back button with your own image `[Export("navigationBar:shouldPopItem:")]` no longer fires on the UINavigationController so we need to trigger it as part of our own logic
- fixes #12126 
- fixes #12144 
- fixes #6485
- fixes #12505
- iOS

Trigger pop logic when you replace back button with icon

---

Xamarin.Forms.Core.UnitTests/GridTests.cs
Xamarin.Forms.Core/GridCalc.cs

Fixes for some regressions on 4.8 with Grid layout. Unconstrained star rows affected by star columns now constrain Labels correctly when measuring to allow the text to grow vertically by the correct amount. Star row/column computations no longer include "unmeasured" (i.e. -1) values in size calculations. Star column calculations now account for absolute column widths and partial star column (e.g. "0.7*") when measuring elements where width/height are interdependent (e.g., Labels).
Also adds automated tests for the regressed scenarios.
- fixes #12001
- fixes #12175
- fixes #12462
- fixes #12363
- fixes #12292
None
None
Not applicable
Automated tests

Fix Grid regressions with text in star rows/columns

---

Stubs/Xamarin.Forms.Platform.cs
Xamarin.Forms.Platform.Tizen/Extensions/BrushExtensions.cs
Xamarin.Forms.Platform.Tizen/Extensions/GeometryExtensions.cs
Xamarin.Forms.Platform.Tizen/Extensions/TransformExtensions.cs
Xamarin.Forms.Platform.Tizen/Forms.cs
Xamarin.Forms.Platform.Tizen/Properties/AssemblyInfo.cs
Xamarin.Forms.Platform.Tizen/Renderers/DefaultRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/PageRenderer.cs
Xamarin.Forms.Platform.Tizen/Shapes/EllipseRenderer.cs
Xamarin.Forms.Platform.Tizen/Shapes/LineRenderer.cs
Xamarin.Forms.Platform.Tizen/Shapes/PathRenderer.cs
Xamarin.Forms.Platform.Tizen/Shapes/PolygonRenderer.cs
Xamarin.Forms.Platform.Tizen/Shapes/PolylineRenderer.cs
Xamarin.Forms.Platform.Tizen/Shapes/RectangleRenderer.cs
Xamarin.Forms.Platform.Tizen/Shapes/ShapeRenderer.cs
Xamarin.Forms.Platform.Tizen/Shapes/ShapeView.cs
Xamarin.Forms.Platform.Tizen/StaticRegistrar.cs

This PR adds Shapes Tizen implementation.
The implementation has been done with SkiaSharp which has been added to Tizen by https://github.com/xamarin/Xamarin.Forms/pull/12501 .
Users have to add a `InitializationOptions.UseSkiaSharp` option to enable Shapes renderers.
```c#
var option = new InitializationOptions(app)
{
UseSkiaSharp = true
};
Forms.Init(option);
```
N/A
None
- Tizen
None
[Shapes Demo](https://docs.microsoft.com/ko-kr/samples/xamarin/xamarin-forms-samples/userinterface-shapesdemos/)

[Tizen] Added Shapes Tizen implementation

---

Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs

I have not managed to reproduce the issue. Checking the code, the drawable that define the SwipeItem icon can become null. This PR has changes to protect this possible NRE.
- fixes #12458 
None
- Android
None
Not applicable

[Android] Protect NRE setting SwipeItem Drawable

---

Xamarin.Forms.Core/BindableObject.cs
Xamarin.Forms.Core/Binding.cs
Xamarin.Forms.Core/BindingExpression.cs
Xamarin.Forms.Core/CompressedLayout.cs
Xamarin.Forms.Core/ImageSource.cs
Xamarin.Forms.Core/Interactivity/BindingCondition.cs
Xamarin.Forms.Core/Interactivity/Condition.cs
Xamarin.Forms.Core/Interactivity/DataTrigger.cs
Xamarin.Forms.Core/Interactivity/EventTrigger.cs
Xamarin.Forms.Core/Interactivity/PropertyCondition.cs
Xamarin.Forms.Core/Interactivity/Trigger.cs
Xamarin.Forms.Core/Interactivity/TriggerBase.cs
Xamarin.Forms.Core/Layout.cs
Xamarin.Forms.Core/ListView.cs
Xamarin.Forms.Core/LockableObservableListWrapper.cs
Xamarin.Forms.Core/MultiBinding.cs
Xamarin.Forms.Core/NavigationModel.cs
Xamarin.Forms.Core/ResourceDictionary.cs
Xamarin.Forms.Core/TemplateBinding.cs
Xamarin.Forms.Core/TypedBinding.cs

Replace _"can not"_ to _"cannot"_ in error messages.
- fixes #12560 
None
None
Not applicable
Not applicable

[Core] Replace "can not" to "cannot" in error messages

---

Xamarin.Forms.Platform.iOS/Renderers/TableViewRenderer.cs

iOS 13 introduced a new style for the UITableView: [InsetGrouped](https://developer.apple.com/documentation/uikit/uitableview/style/insetgrouped). However, Xamarin.Forms developers are not able to use this new style because the style can only be set in the constructor of the UITableView. Once a UITableView is constructed, the style cannot be changed.
In the [current implementation of the TableViewRenderer](https://github.com/xamarin/Xamarin.Forms/blob/6d9a4b0d80501b98c524ae1baf21c543c60f2953/Xamarin.Forms.Platform.iOS/Renderers/TableViewRenderer.cs#L67), the style gets chosen by the table's intent. There, the intent is mapped to the styles `Plain` and `Grouped`. The developer has no way to intercept this mapping.
Next, the TableViewRenderer instantiates a new UITableView after the style …

Let developers choose the UITableViewStyle (enable developers to use the new iOS13 style InsetGrouped)

---

Xamarin.Forms.Platform.Android/Renderers/FormsWebViewClient.cs

On Android, Navigated event args contain wrong status of "Failed" when an asset request receives an error even though the page itself is loaded successfully. Instead, OnReceivedError should check if the request url of the OnReceivedError method is equal to the navigated url. (issue #11988)
This PR fixes the issue by adding the necessary url check.

Fix WebView Navigated Status Bug In Android

---

Xamarin.Forms.Core.UnitTests/ShellNavigatingTests.cs
Xamarin.Forms.Core.UnitTests/ShellParameterPassingTests.cs
Xamarin.Forms.Core.UnitTests/ShellTestBase.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellItem.cs
Xamarin.Forms.Core/Shell/ShellSection.cs
Xamarin.Forms.Core/Shell/ShellUriHandler.cs

- Fix ShellNavigationSource so it's correctly calculated based on diff of source/dest
- When popping using ".." don't clear parameters on previous page 
- unit tests pass
- UI tests pass

Calculate Nav Source and fix popping params

---

Xamarin.Forms.Platform.Tizen/Native/ListView.cs
Xamarin.Forms.Platform.Tizen/ThemeConstants.cs
Xamarin.Forms.Platform.Tizen/ThemeManager.cs

This change is for fixing `ListView` (especially, using `ImageCell` or `SwitchCell`) not working properly on Tizen 6.0 or higher version of Tizen TV.
None
None
- Tizen
None
**Before**
**After**

[Tizen] Fix ListView cell rendering on TV

---

.nuspec/Xamarin.Forms.targets

VS 16.8 now sets TargetPlatformMinVersion to `7.0` on the shared project which is causing the UWP specific target to run and give a bogus warning message
This PR checks that the TargetPlatformIdentifier matches UAP so it only runs for UAP projects
This PR also updates the Target and Min Target to match WinUI 2.4 suggestions
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1237998
- UWP
- create a new Xamarin.Forms project  with UWP
- add this nuget
- make sure the warning doesn't show up for the shared project. Set the UWP project min version to < 17763 and make sure you still get the warning

Check TargetPlatformIdentifier for UAP

---

Xamarin.Forms.Platform.UAP/CollectionView/CarouselViewRenderer.cs

The CarouselView use in UWP the `FormsListView` control. In the constructor of the control we are setting the default scrollbar behavior. This PRs applies changes to set the correct scroll behavior using a Horizontal and Vertical CarouselView.
- fixes #12349
None
- UWP
None
Not applied
Launch Core Gallery and navigate to the CarouselView Gallery. Select the Horizontal/Vertical CarouselView Gallery and try to swipe to the next item. If can navigate to the next item, the test has passed.

[UWP] Fix CarouselView scroll issue

---

Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
Xamarin.Forms.ControlGallery.Android/DisposeLabelRenderer.cs
Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs
Xamarin.Forms.ControlGallery.Android/Issue10182Activity.cs
Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
Xamarin.Forms.ControlGallery.Android/_1909CustomRenderer.cs
Xamarin.Forms.ControlGallery.Android/_5724CustomRenderers.cs
Xamarin.Forms.ControlGallery.Android/_60122ImageRenderer.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/PerformanceGallery/PerformanceGallery.cs
build.cake

- Replaced the "TEXT_EXPERIMENTAL_RENDERERS" constant with "LEGACY_RENDERERS" as that's a more accurate indicator of the current state of the renderers
- Fixed CI to default to Fast Renderers instead of Legacy Renderers
- Android
- Make sure a Legacy Renderer and Fast Renderer APK is built
- Even if the tests are failing we should merge this PR in and then fix the tests on other PRs

Fix APK to build with Fast Renderer switch when running on CI

---

Xamarin.Forms.Platform.Android/ButtonLayoutManager.cs

Fix a issue when using non FastRenderers the ButtonLayoutManager was throwing a NRE because it was trying to access the NativeView (Control) before it's created on `SetNativeControl`
- Fixes failing tests
None
- Android
None
Not applicable
Android UITEsts should pass (green) but should show also 100% (number of tests passing)

[Android] Fix NRE when trying to access the renderer View

---

Xamarin.Forms.Platform.UAP/RefreshViewRenderer.cs

Check if Element or control is null before attemping to change their status
Null reference exception on UpdateIsRefreshing when the window is resized
- UWP
None
Not applicable

Fix Null reference exception on UpdateIsRefreshing when the window is resized

---

Xamarin.Forms.Platform.iOS/Renderers/IndicatorViewRenderer.cs

Fixed IndicatorView rendering issue on iOS 14.
In iOS 14, We have a new styling option for a UIPageControl called `BackgroundStyle`. This is an enum with three values:
- Automatic: The default background style that adapts based on the current interaction state.
- Prominent: The background style that shows a full background regardless of the interaction
- Minimal :The background style that shows a minimal background regardless of the interaction
Apple also has provided a new way to manage the interaction for the UIPageControl in iOS14 called InteractionState. `AllowsContinuousInteraction` allow us in a. simple way to manage if we want continuous interaction or not.
To maintain the IndicatorView behavior, this PR introduce changes using the previous properties only in iOS 14.
- fixes #12028 …

[iOS] Fixed IndicatorView rendering issue on iOS 14

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10897.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10897.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/CollectionView/CarouselViewRenderer.cs

Fixed crash in CarouselView resizing the Window on UWP.
- fixes #10897 
None
- UWP
None
Not applicable
Launch Core Gallery and navigate to the issue 10897. Resize several times the App Window. If everything works without any exception, the test has passed.

[UWP] Fixed crash in CarouselView resizing the Window

---

Xamarin.Forms.Core/ListView.cs

Validate item exists by index
Fixes: #12533
Run Gallery WPF. Search "list". Select GroupedList Gallery - Legacy. Click on white space (do not click on row)

Fix NRE on List Click

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewBoundSingleSelection.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/SingleBoundSelection.xaml
Xamarin.Forms.Platform.Android/CollectionView/SelectableViewHolder.cs
Xamarin.Forms.Platform.Android/CollectionView/TemplatedItemViewHolder.cs
Xamarin.Forms.Platform.iOS/CollectionView/TemplatedCell.cs

NOTE: This was orginally https://github.com/xamarin/Xamarin.Forms/pull/11604 from @ronymesquita. We had to re-create the PR due to some CI and merging issues. 
The key idea is to resolve the problem of CollectionView with selected item color on Android and iOS.
- fixes #7790
- fixes #9590
- fixes #11421
None
- iOS
- Android
The platform will check if exists a `Visual State` with `Selected` and not use the default color. In this manner, the background color of the `Visual State` will not be overridden by Android. On iOS, the background color is cleaned when the `Selected` state exists. 
The default behavior still works.
The test was manual.

Correction of CollectionView to work properly with selected item color

---

Xamarin.Forms.Maps.Android/Properties/AssemblyInfo.cs

Write_External_storage is no longer needed if you are targeting 23+ 
https://developers.google.com/maps/documentation/android-sdk/config#external-storage-permission
You're required to target API 29 to release to the play store. If for some reason a user needs to target lower than 23 they can just add the permission in themselves
- fixes #12680 
- Android
- Ensure that the release nuget package loads maps correctly without having to set the WRITE_EXTERNAL_STORAGE permission

Remove WRITE_EXTERNAL_STORAGE from maps

---

Xamarin.Forms.Core/BindingExpression.cs
Xamarin.Forms.Core/MultiBinding.cs
Xamarin.Forms.Core/TypedBinding.cs
Xamarin.Forms.Core/Xaml/Diagnostics/BindingDiagnostics.cs
Xamarin.Forms.Core/Xaml/Diagnostics/BindingErrorEventArgs.cs

This is the follow-up for the initial XAML BindingDiagnostics PR by @StephaneDelcroix:
#10523 
See the bug I logged:
#12645 
The change I'm making allows binding failures to show up properly in VS's binding failures pane:
* The Message string didn't always exactly match the debug output for the binding failure
* In order to de-dupe the BindingFailed event against debug output, I need the failure messages to _exactly_ match. This change ensures that the messages must match
- fixes #12645
Changed:
- BindingBaseErrorEventArgs.ErrorCode gets a value of "Binding" or "MultiBinding" depending on what gets written to debug output (instead of not ever having a value). VS will need to know that in order to reconstruct the failure message and de-dupe against debug output. …

EventArgs for BindingFailed must match Log.Warning

---

Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs

On changing the layout of collection at runtime, the iOS app gets crashed showing an null reference exception on invalidate layout which clearly mentioned that CollectionView is getting null here. Whereas in Android it works just fine without any issue/exception.
None
- iOS

iOS: CollectionView: ItemsViewLayout: Fix null reference on invalidate layout

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Controls/App.cs
Xamarin.Forms.Platform.MacOS/Renderers/ScrollViewRenderer.cs

Since ScrolViewRenderer on macOS uses a FlipClippedView we don't need to invert the coordinates. 
- fixes #12543
None
- macOS
Should scroll to the correct position 
Not applicable
use the scrollview gallery , check ScrollTo 100 works.

[macOS] Fix ScrollTo on NSScrollView

---

Xamarin.Forms.Material.Tizen/MaterialSliderRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/SliderRenderer.cs

This PR is to fix an issue on material style slider.
None
None
- Tizen
None
|--|--|
| <img width="300" src="https://user-images.githubusercontent.com/20968023/97841662-abe97300-1d29-11eb-8aa6-ee3804cbc442.gif" /> | <img width="300" src="https://user-images.githubusercontent.com/20968023/97841667-ad1aa000-1d29-11eb-8ba4-2c3ef6ae4fa7.gif" /> |

[Tizen] Fix material style slider issue

---

Xamarin.Forms.Platform.Tizen/EmbeddedFontLoader.cs
Xamarin.Forms.Platform.Tizen/Extensions/FontExtensions.cs

This PR is to fix custom font issue.
https://github.com/Samsung/TizenFX/issues/2120
None
- Tizen
|--|--|
| <img width="300" src="https://user-images.githubusercontent.com/20968023/97840782-fa960d80-1d27-11eb-99ea-aafd0766f532.png" /> | <img width="300" src="https://user-images.githubusercontent.com/20968023/97840786-fc5fd100-1d27-11eb-9638-e4a4d77127fd.png" /> |

[Tizen] Fix custom font issue

---

Xamarin.Forms.Platform.Tizen/Shell/NavigationDrawer.cs

This PR is to modify orders of elements of `NaviagitonDrawer`.
This change is to solve entry selection issue caused from `NavigationDrawer` by putting the navigation drawer(Panel) below the main container(Box).
None
None
- Tizen
|--|--|
| <img width="300" src="https://user-images.githubusercontent.com/20968023/97840245-092ff500-1d27-11eb-8689-490bccda16ee.gif" /> |  <img width="300" src="https://user-images.githubusercontent.com/20968023/97840213-f74e5200-1d26-11eb-9bb4-b883c710edc3.gif" /> |

[Tizen] Modify NavigationDrawer to fix Entry issue

---

Xamarin.Forms.Platform.Tizen/Extensions/GeometryExtensions.cs
Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs
Xamarin.Forms.Platform.Tizen/SkiaSharp/CanvasViewRenderer.cs
Xamarin.Forms.Platform.Tizen/SkiaSharp/IClipperCanvas.cs

This PR added `VisualElement.Clip` Tizen implementation.
Clip feature is enabled on SkiaSharp render mode which is added on https://github.com/xamarin/Xamarin.Forms/pull/12501 .
Clip is currently provided on following renderers
- CanvasViewRenderer
- ImageRenderer
- BoxViewRenderer
- None
None
- Tizen
None

[Tizen] Added Clip Tizen implementation

---

Xamarin.Forms.Core.UnitTests/BindableLayoutTests.cs
Xamarin.Forms.Core/BindableLayout.cs

Wrong BindableProperty being set inside of BindableLayout.SetEmptyViewTemplate 
- fixes #12683
- fixes #9905
- Unit test included

Fix BL.SetEmptyViewTemplate to use correct Bindable Property

---

Xamarin.Forms.Platform.Android/ButtonLayoutManager.cs

Conflicting TextTransform code was causing the following tests to fail on main:
* Issue11703Test
* StyleTextAllCapsSettingIsRespected
These were resolved in `ButtonLayoutManager.cs` by adding the update TextTransform code after the LineBreak code (which also happens to affect TextTransform). The relevant code was also extracted into a new method. Tests are no longer failing!
#12170 updated TextTransform code
#11147 updated LineBreakMode code
- Android

Address failing TextTransform tests on Android

---

Xamarin.Forms.Core.UnitTests/FlyoutPageUnitTests.cs
Xamarin.Forms.Core.UnitTests/NotifiedPropertiesTests.cs
Xamarin.Forms.Core.UnitTests/PlatformSpecificsTests.cs
Xamarin.Forms.Core.UnitTests/TabIndexTests.cs
Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
Xamarin.Forms.Core/FlyoutPage.cs

- Reusing the FlyoutLayoutBehavior Property for MasterBehavior Property was the wrong approach since the types don't match. This creates a new bindable property specific to MasterDetailPage and then propagates that up to FlyoutPage
- Add copy of all MasterDetailPage tests to FlyoutPage
- Add `ContentPropertyAttribute ` for Detail on the FlyoutPage type
- fixes #12490 
Added ContentPropertyAttribute to FlyoutPage
```C#
[RenderWith(typeof(_FlyoutPageRenderer))]
[ContentProperty("Detail")]
public class FlyoutPage : Page, IFlyoutPageController, IElementConfiguration<FlyoutPage>
{
```
- Test various permutations of setting MasterBehavior and make sure that the app reacts accordingly

Fix MasterBehavior to propagate correctly to FlyoutPage

---

Xamarin.Forms.Platform.UAP/Shell/ShellRenderer.cs
Xamarin.Forms.Platform.UAP/Shell/ShellStyles.xaml

Adds UWP support for #4765
- fixes #7913
None
- UWP
None
Not applicable
Launch UWP Gallery, go to test page 4765.  Add enough shell items to make the nav flyout need to scroll.  Change the scroll mode and verify behavior.
When scrolling is disabled, the scroll bar will also be hidden.

Fixes 7913 Add UWP shell flyout scroll mode support

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewGrouping.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewItemsUpdatingScrollMode.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Github5623.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10300.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11224.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5354.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5376.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5535.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7102.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7803.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8964.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9686.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9827.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9929.cs
Xamarin.Forms.Core.UITests.Shared/Tests/CarouselViewUITests.cs
Xamarin.Forms.Core.UITests.Shared/Tests/CollectionViewUITests.cs
build.cake

We can pick through and leave only the passing tests in place but this will mean we have to be productive with any new tests added. Are we ready for this with CV?
- make sure all the UI tests are 💚

Add CV back into UWP tests

---

Xamarin.Forms.Core/PlatformConfiguration/TizenSpecific/ItemsView.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/CollectionView.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/GridLayoutManager.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/ItemTemplateAdaptor.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/LinearLayoutManager.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/ViewHolder.cs
Xamarin.Forms.Platform.Tizen/Renderers/ItemsViewRenderer.cs

* This PR optimize `CollectionView` for TV profile
- ScrollStep of CollectionView was increased to item size, it improve scrolling of items
- Focused items was raised to the top, it fix focus effect issue on some apps
- VisibleItemIndex on Scrolled event was not correct with header/footer, it was fixed
- Add FocusedItemScrollPosition property in ItemsView as TizenSpecific, useful for controlling with focus.
- fixes #
Added:
``` c#
public static void Xamarin.Forms.PlatformConfiguration.TizenSpecific.ItemsView.SetFocusedItemScrollPosition(BindableObject element, ScrollToPosition position)
public static ScrollToPosition Xamarin.Forms.PlatformConfiguration.TizenSpecific.ItemsView.GetFocusedItemScrollPosition(BindableObject element)
```
- Tizen
None
* FocusedItemScrollPosition

[Tizen] CollectionView optimize for TV profile

---

Xamarin.Forms.Platform.Tizen/GestureDetector.cs

In modern Xamarin.Forms mobile app development, `TapGestures` are used very frequently. However, `Tapped` event couldn't be used in non-touch-based products such as TV.
This PR allows the `TapGestureRecognizer.Tapped` event to be activated even through the remote control keystroke (e.g.,`OK` or `Enter` Key) on the TV devices.
- None
None
- Tizen
`Tapped` event occurs through not only touch gesture, but also through remote controller on the TV devices.(`TargetIdiom.TV`)

[Tizen] Allow Tap gesture using remote control on TV

---

Xamarin.Forms.Platform.Android/Forms.cs

Changed checking the `UiMode` enum using HasFlag  to use  ==. Based on this changes https://github.com/xamarin/Essentials/commit/b937b1292840d8267969d6fe6f34a312aa6f9a36 from Xamarin Essentials.
- fixes #11166
- fixes #11177
None
- Android
None
Not applicable

[Android] Changes in the logic to detect Device.Idiom

---

Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs
Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10744.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12134.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2354.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4597.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9682.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/ScreenshotConditionalApp.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/issue3262.cs
Xamarin.Forms.Core.UITests.Shared/Tests/Legacy-CellsUITests.cs
Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs
Xamarin.Forms.Core.Windows.UITests/WinDriverApp.cs

- Categorize tests that require internet access that are currently failing on App Center
- Before these tests run verify if the device has a valid internet connection. If it doesn't then just mark the test as Inconclusive
- For the most part tests inside of AppCenter run without issue but the internet connection on the device seems to fail enough that we need to detect for this and not fail the whole group but just mark a given set inconclusive
- iOS
- Android
- UWP
- Make sure UI tests all pass

Check for Internet Connection before running tests that Require an Internet Connection

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8836.cs
Xamarin.Forms.Platform.UAP/FormsTextBox.cs

UWP Entry ClearButtonVisiblity was not being honored when set to WhileEditing prior to loading.
- fixes #12731 
None
- UWP
None
Not applicable
Open the 8836 issue page and make sure the clear buttons work as expected.

[UWP] Fix 12731 The ClearButton is no longer displayed in the entry

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11691.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11691.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11911.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11911.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core.UnitTests/BrushUnitTests.cs
Xamarin.Forms.Core/Brush.cs
Xamarin.Forms.Core/GradientBrush.cs
Xamarin.Forms.Core/GradientStop.cs
Xamarin.Forms.Core/Shapes/Shape.cs
Xamarin.Forms.Core/VisualElement.cs

Changed Brush and GradientStop from BindableProperty to Element and propagate correctly the Parent.
- fixes #11907
- fixes #11911
- fixes #11691
None
None
Launch Core Gallery and navigate to the issues 11696 and 11911. Verify that the expected colors are rendered (read issue instructions).

[Core] Brushes working with DynamicResource

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60787.xaml
Xamarin.Forms.Platform.UAP/FrameRenderer.cs

Changes behavior of UWP FrameRenderer default background color to match iOS and Android.
I would consider this a breaking change and suggest 5.0 as the target for it.
- fixes #11513 
None
- UWP
The default background color of a Frame on UWP will now be white.
Before
After
Open Issue B60787 and ensure the last Frame has a white background.

[Bug] [UWP] Fix GitHub 11513 - UWP Frame default Background color not consistent with other platforms

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12193.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/CollectionView/CarouselTemplatedCell.cs
Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewLayout.cs
Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewRenderer.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewRenderer.cs

Removes unnecessary constraints update calls during InvalidateLayout which were causing auto-layout errors for CarouselView (and making HTML Labels occasionally disappear). 
Also removes some unecessary overrides from CarouselView Layout/Controller (deferring to ItemsView Layout/Controller). 
- fixes #12193
None
- iOS
None
Not applicable
Automated test

Remove unnecessary UpdateConstraints calls when rotating

---

Xamarin.Forms.Core/Grid.cs
Xamarin.Forms.Core/GridCalc.cs

Issue #6247, issue #10470, and https://forums.xamarin.com/discussion/88367/nullreferenceexception-on-grid-calculateautocells-only-xf-ios describe NullReferenceExceptions accessing the `_rows` and `_columns` members during Grid layouts. These members are lists of RowDefinition and ColumnDefinition information used during the measurement and layout of the Grid. The information in these lists is not for caching purposes; lists are reset during every measurement and layout operation, and also when computing constraints for the Grid. 
Because the lists are nullable, certain layout and update conditions (which are very difficult to consistently reproduce) can result in the lists being null while a measurement operation is taking place, crashing the application. 
In …

Snapshot grid structure info instead of modifying it in place

---

UWP.Build.props

Visual Studio 16.8 doesn't seem to like having a multi targeted UWP project as much as 16.7 did. This change makes it so both UWP targets are only built when building from the command line and just builds the 16299 target when building in the IDE
- Make sure the produced nuget still has both of the UWP targets

Only build one UWP target when using IDE

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12714.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs

An initially invisible CollectionView on iOS attempts to layout at a tiny size, which causes autolayout errors and other assorted mayhem, hanging the application.
These changes prevent the intial layout from occurring until the CollectionView is actually visible, avoiding the problem.
- fixes #12714
None
- iOS
None
Not applicable
Automated test 12714

Prevent layout hang on iOS when CollectionView is initially invisible

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7181.cs
Xamarin.Forms.Platform.UAP/AccessibilityExtensions.cs
Xamarin.Forms.Platform.UAP/Shell/ShellStyles.xaml
Xamarin.Forms.Platform.UAP/Shell/ShellToolbarItemRenderer.cs

Toolbar Items in UWP shell are bound to the commands and firing the click events from code behind which is causing the Command bound to ToolbarItem to fire multiple times. This PR removes the command binding since the Click event in the code behind handles the firing of the Command.
- UWP
- UI Tests included
- This was originally found on the Shell templates for Visual Studio. When clicking "Add new item" two pages were being pushed.

Fix multiple events on toolbar items

---

Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs

If users have the non AndroidX layouts that come with the Forms template and they upgrade to AndroidX then we fallback to AndroidX layouts included with our binaries. We were checking that the targetSdk >= 29 but in some rare cases users might have targetSdk set to 28 and the compile target set to 29. This removes the requirement for targetSdk > 28 for it to trigger our fallbacks.
The Android team is going to work on putting together some better warning messages around this mismatch with the 16.9 release
- fixes #12690 
- Android
- download these nugets and run them against the project referenced in the fix

Remove TargetSdkVersion check for AndroidX fallback

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/DateTimePickerLocalizationTests.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12574.cs

It appears that when running UWP tests on the hosted agent that the selectors don't popup after being interacted with.
For now we'll ignore these tests when they are being ran on the CI
- make sure UWP tests are all passing

Ignore Locale tests and one CV test on UWP

---

UWP.Build.props
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4597.cs
build.cake

This completely removes the 14393 targets from our csproj files and only builds them as part of our nuget build process. The command line build was also having the same issue building 14393 together with 16299 so this PR just removes the multi targeting completely
- UWP
- Run the build.cmd and ensure that it builds all the nugets

Build 14393 targets separately

---

Xamarin.Forms.Core/BoundsTypeConverter.cs
Xamarin.Forms.Core/CornerRadiusTypeConverter.cs
Xamarin.Forms.Core/FlexEnums.cs
Xamarin.Forms.Core/FontSizeConverter.cs
Xamarin.Forms.Core/GridLengthTypeConverter.cs
Xamarin.Forms.Core/PointTypeConverter.cs
Xamarin.Forms.Core/RectTypeConverter.cs
Xamarin.Forms.Core/RectangleTypeConverter.cs
Xamarin.Forms.Core/Shapes/MatrixTypeConverter.cs
Xamarin.Forms.Core/SizeTypeConverter.cs
Xamarin.Forms.Core/ThicknessTypeConverter.cs

[X] ConvertToInvariant is invariant
- fixes #12828
None
None
Not applicable

[X] ConvertToInvariant is invariant

---

Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs

Fixed flickering NavBar color issue on iOS 13 or higher. 
In iOS 13 important changes were introduced in the management of the `UINavigationBar` (appareaances, etc).
The behavior in iOS 12 in different versions of Xamarin.Forms 4.x and 5.0 is as follows:
Using  iOS 13, without setting `BarBackgroundColor`, the default color changed from white (or black in DarkTheme) to gray (`ConfigureWithDefaultBackground`) and the problem was the noticeable flickering when navigating:
This PR include changes to apply in iOS 13 or higher the same behavior we have in iOS 12:
- fixes #9943 
None
- iOS
None
Not applicable
Launch Core Gallery, and navigate anywhere. Pay attention to the navigation bar, for a very brief moment the background flicker.

[iOS] Fixed flickering NavBar color issue on iOS 13 or higher

---

Xamarin.Forms.Platform.Tizen/SkiaSharp/FrameRenderer.cs

Changes the default background color of Frame to `Transparent`. Plus, fix the clipper correctly.
None
None
- Tizen
None
Not applicable

[Tizen] Fix the FrameRender

---

Xamarin.Forms.Platform.Tizen/Native/CollectionView/ItemTemplateAdaptor.cs
Xamarin.Forms.Platform.Tizen/Renderers/ItemsViewRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs

This PR fix the control of the ItemsView's LogicalChild. a Instantiated view that created by `ItemTemplate` should be added on `ItemsView` as logical child, but did't, now logical child is updated when item was shown on `ItemsView`
- fixes # 
None
- Tizen
None

[Tizen] Fix ItemsView LogicalChild issue

---

Xamarin.Forms.Platform.MacOS/Renderers/RadioButtonRenderer.cs

Removed unnecessary SendClicked logic in macOS RadioButtonRenderer
- fixes #12880 
None
- macOS
None
Not applicable
Launch Core Gallery on macOS and navigate to the RadioButton Gallery. Then, tap any RadioButton. Without exceptions, the test has passed.

[macOS] Fix InvalidCastException tapped RadioButton

---

azure-pipelines.yml
build.cake
build/steps/build-windows.yml

16.8.1 seems to require an additional restore operation against the SLN file. I've also removed the nuget restore inside the YAML we'll see if that survives the CI :-) 
- make sure builds work on public/private CI

Extra restore to fix 16.8 builds

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12512.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs

The issue is in fact an iOS feature. Is doing multiple snapshots of the app's UI that will be presented in the App Switcher. And since the user could change to Dark Mode while your app is in the background, iOS does snapshots in both interface styles to always show the correct one.
Happens something like: The system takes a screenshot of your Light UI, switches to Dark (first trigger), takes a screenshot (off-screen), and switches back to Light (second trigger). And we have raised twice `RequestedThemeChanged`.
This PR include changes to only raise `RequestedThemeChanged` if the App is not in Background. Why?. To avoid raise the event  while app snapshots are being taken when going to background. In that way, the App raise the event just 1 time when pass from background to foreground.
- …

[iOS] Fixed RequestedThemeChanged raised twice issue

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12084.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12084.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems

Tested on iOS 14 in simulator and device. Cannot reproduce the issue. For that reason, this PR only include a sample where validate the issue.
- fixes #12084 
None
- iOS
None
Launch Core Gallery and navigate to the issue 12084. If can tap the track of the Slider and see the selection change, the test has passed.

[iOS] Slider not responding to taps in iOS 14

---

Xamarin.Forms.Platform.UAP/Shell/ShellItemRenderer.cs
Xamarin.Forms.Platform.UAP/Shell/ShellSectionRenderer.cs

The `ShellSectionRenderer` for UWP doesn't expose any virtual method to override, closing a lot of possibilities expecially for plugin authors.
This PR comes after a conversation on Twitter with @PureWeen and adds a bunch of `protected virtual` methods to the navigation process (splitting up the `NavigateToContent` method in submethods).
Also i also made the `GetTransitionInfo` method virtual so we can change the animation transition between pages.
Please note that i also made virtual the `NavigateToContent` method, so we have the ability to to jump in the navigation process before the destination page has been created (or after with the new virtual methods).
Added:
- `protected void OnPopRequested(ShellNavigationSource source)`
- `protected void OnPopToRootRequested(ShellNavigationSource …

[UWP] [Shell] Make Navigation and Transition overridable for Shell

---

Xamarin.Forms.Core/BindableObject.cs
Xamarin.Forms.Core/Setter.cs
Xamarin.Forms.Core/Style.cs
Xamarin.Forms.Xaml.UnitTests/Issues/Gh12874.xaml
Xamarin.Forms.Xaml.UnitTests/Issues/Gh12874.xaml.cs

When a BP is cleared, (re)apply the style value
- fixes #12874
None
- iOS
- Android
- UWP
None
Before
After

[C] Keep the Style value as backup

---

build.cake
build/steps/build-windows.yml

For 16.8.* we had to add a "/restore" call to the msbuild operation we use to build the nugets. This seems to put the ControlGallery appx files into a weird state where they can't be deployed because of some dependency confusion.
This PR moves the APPX build part to happen before the nugets are packaged which seems to work
- ensure UWP UI Tests run

Build AppX packages before doing Solution Restore to fix UWP UI tests

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11090.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/CollectionView/SelectableItemsViewRenderer.cs

Fix crash PopAsync in ColllectionView SelectionChanged on UWP.
- fixes #11090 
None
- UWP
None
Crash
Launch Core Gallery and navigate to the issue 11090. Press the button to navigate to a new page, and after navigate, select an item from the CollectionView. If navigate back without exceptions, the test has passed.

[UWP] Fix crash PopAsync in CollectionView SelectionChanged

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8988.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/DisposeHelpers.cs
Xamarin.Forms.Platform.iOS/ModalWrapper.cs
Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs

There's a issue on iOS13  that pushing a modal using your app in split mode, (side by side with other app),  it causes issues rendering the second time. 
The particular issue is also related with retaining the pushed page , it keeps it's bounds, and we need to force the layout.
Workaround could be to just reset is bounds when is popped.
- fixes #8988
None
- iOS
None
Go to Issue8988 , click Next, check the page loaded, click Go Back, then click again Next and make sure the page loads fine.

[iOS] Fix pushing same page as a modal on iOS13 in split mode

---

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewRTLGallery.xaml
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewRTLGallery.xaml.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewRenderer.cs

The EmptyView using RightToLeft was flipped and does not update the position of the views. This PR include changes to fix the issue.
- fixes #12892 
None
- iOS
None
Launch Core Gallery and navigate to the CollectionView Galleries. Select the EmptyView RTL sample and check that the EmptyView looks correctly both LeftToRight and RightToLeft.

[iOS] Fix CollectionView EmptyView RTL issue

---

Xamarin.Forms.ControlGallery.WindowsUniversal/NavPageOverrideRenderer.cs
Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/NavPageOverrideUWP.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/NavigationPageRenderer.cs

The `NavigationRenderer` for UWP doesn't expose any virtual method to override, closing a lot of possibilities expecially for plugin authors.
This PR comes after a conversation on Twitter with @PureWeen and adds the `protected virtual` access level to the following, existing, methods:
`OnPopRequested`
`OnPopToRootRequested`
`OnPushRequested`
`OnElementChanged`
Bringing the UWP NavigationRenderer in par with iOS & Android.
Plus i created a new method `SetupPageTransition` to override the default transition (but making sure to maintain the `_transition `cache for the default transition).
Added:
- `void SetupPageTransition(Transition transition, bool isAnimated, bool isPopping)`
*isPopping is needed to create a custom transition based on push or pop*
Changed:
- `protected virtual void …

[UWP] Make Navigation and Transition overridable for NavigationPage

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11244.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6878.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
Xamarin.Forms.Controls/XamStore/StoreShell.xaml.cs
Xamarin.Forms.Platform.UAP/Shell/ShellRenderer.cs
Xamarin.Forms.Platform.UAP/Shell/ShellSectionRenderer.cs
build.cake

- Removed shell filter from UWP UI tests
- When the FlyoutBehavior is set to disabled make sure to still show backbutton
- When switching shell sections synchronize frame to current navigation stack 
- Fix Top Tabs so they hide and show correctly as top tabs are removed and shown
- UWP
- UWP tests pass

Enable Shell tests on UWP and fix a few bugs

---

.nuspec/Xamarin.Forms.nuspec
Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
Xamarin.Forms.Platform.UAP/Forms.cs
Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj

With the addition of 14393 we setup the ShellStyles resource file to only get included when Min Target is 16299 and removed the reference from the Resources.xaml file. This appears to work fine if you have target framework set to >= 18632 but if you have it set to 17763 or 16299 then it fails to load the resource.
- fixes #11505
- UWP
- Pull down the project on the related issue and test the included nuget

Add Shell Resource file explicitly

---

Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj

Update to the latest Xamarin.UITest so we can run tests against iOS 14 and Xcode 12
- tests all pass in appcenter and you are able to run iOS tests locally

Update to latest Xamarin.UITest

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10300.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12574.cs
Xamarin.Forms.Core.UITests.Shared/Tests/CarouselViewUITests.cs
Xamarin.Forms.Platform.iOS.UnitTests/ObservableItemsSourceTests.cs
Xamarin.Forms.Platform.iOS.UnitTests/Xamarin.Forms.Platform.iOS.UnitTests.csproj
Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/IndexPathHelpers.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
Xamarin.Forms.Platform.iOS/CollectionView/LoopObservableItemsSource.cs
Xamarin.Forms.Platform.iOS/CollectionView/ObservableGroupedSource.cs
Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs
Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj

When adding test for #12574 I saw that when we are removing the current last item sometimes the scroll to the previous position wasn't happening, this was related to ReloadingVisibleItems that is need when using the Loop feature, so we can update the UI when cell is removed. Adding a small delay will make the collection reload and then set the CollectionView to the correct position
None
- iOS
Remove the last item should then show the previous item
Not applicable
Issue12574 should pass on iOS

[iOS] Fix when removing current last Item on CarouselView

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2447.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2448.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2448.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core/ActionSheetArguments.cs
Xamarin.Forms.Core/AlertArguments.cs
Xamarin.Forms.Core/Page.cs
Xamarin.Forms.Platform.Android/PopupManager.cs
Xamarin.Forms.Platform.UAP/FormsFlyout.xaml.cs
Xamarin.Forms.Platform.UAP/Platform.cs

Added a Flow Direction Property to action sheets and alert dialogs. Also, changed the default flow direction of action sheets and alert dialogs to follow the page's effective flow direction.
- fixes #2448
- fixes #7065 
Added:
- FlowDirection AlertSheetArguments.FlowDirection { get; set; }
- DisplayActionSheet(string title, string cancel, string destruction, FlowDirection flowDirection, params string[] buttons)
- DisplayAlert(string title, string message, string cancel, FlowDirection flowDirection)
- Android
- UWP
The action sheets and alert dialogs may change depending on the flow direction of the parent page.
Before (no flow direction):
After (RTL flow direction):
Create an alert dialog and action sheet on Android and UWP and set the FlowDirection property to right-to-left and …

Added a Flow Direction Property to action sheets and alert dialogs

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12642.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core/Shell/ShellItem.cs
Xamarin.Forms.Core/Shell/ShellSection.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootRenderer.cs

On iOS when transitioning really quickly the animations would start to overlap which would cause all the UIViews to become removed once the animations resolved. I converted over to using a UIViewPropertyAnimator so that I can cancel the animation if the user clicks quickly enough that it has resolved.
Once the animation concludes the code now just figures out who should be visible instead of using messy closures from whoever started the animation. 
- fixes #12642
- iOS

Convert ShellContent transitions to use animators and be smarter about selecting visible content

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10623.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11050.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12685.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/EventTracker.cs

Fix issue using TapGesture on iOS.
- fixes #10623
- fixes #12685
- fixes #13020
None
- iOS
None
Launch Core Gallery and navigate to the issue 10623. Tap the rating control. If you can modify the number of selected stars, the test has passed.

[iOS] Fix issue using TapGesture

---

Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs

When the activity is destroyed an event remain attached, if the application is a singleton this cause a memory leak of the activity.
Memory leak
None
- Android
None
Not applicable
None

[Android] Add missing unsubscribe on activity destroy

---

build/steps/build-osx.yml

It looks like a bad merge doubled up some iOS tasks which is causing the iOS simulator files to get wiped out from the publish directories. These files are needed for deploying to simulator devices
- make sure tests are still able to run

Fix double up of YAML tasks

---

Xamarin.Forms.Platform.Android/Platform.cs

The NonAppCompat version of MDP was trying to cast its renderer to FlyoutPageRenderer but that's not a valid renderer for the Non AppCompat version of MDP. This changes the cast to be to a DrawerLayout which is the actual type trying to be achieved
- Android
Here's the code from the gallery I was using to test this code
```C#
SetMainPage(new MasterDetailPage()
{
IconImageSource = "coffee.png",
Master = new NavigationPage(new ContentPage()
{
Title = "test",
Content = new Button()
{
Text = "hello",
Command = new Command(() =>
{
(Application.Current.MainPage as MasterDetailPage)
.Detail = new NavigationPage(new ContentPage() { Title = "test" });
}
)
}
})
{
IconImageSource = "coffee.png",
Title = "Master Page"
},
Detail = new ContentPage() { Title = "test" },
});
```

Fix cast of non appcompat renderer to DrawerLayout

---

Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs

Fix NRE in PageRenderer
- fixes #12989 
None
- iOS
None
Not applicable

[iOS] Fix NRE in PageRenderer

---

Xamarin.Forms.Controls/GalleryPages/ShapesGalleries/ShapeAppThemeGallery.xaml
Xamarin.Forms.Controls/GalleryPages/ShapesGalleries/ShapeAppThemeGallery.xaml.cs
Xamarin.Forms.Controls/GalleryPages/ShapesGalleries/ShapesGallery.cs

To verify issue #13093,  I have added more Shapes examples in the Core Gallery. The button to add the experimental flag no longer necessary is also removed.
None
- iOS
- Android
None
Launch Core Gallery and navigate to the Shapes samples.

[Housekeeping] Added more shapes samples to CoreGallery

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12910.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12910.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs

Cannot access a disposed object exception using CollectionView EmptyView.
I cannot reproduce the issue neither in the repro sample created, nor using the 5.0.0 branch with the example attached in #12776 (see attached gif). Using Xamarin.Forms 5.0-pre4 can reproduce the issue.@hartez has submitted a few CollectionView fixes recently, but I cannot associate a direct change related to EmptyView that may have fixed the issue. For now, I created this PR as a draft to investigate more.
- fixes #12910 
- fixes #12894 
None
- iOS
None
Launch Core Gallery and navigate to the issue 12910. Pull to Refresh. Without exceptions, the test has passed.

[iOS] Cannot access a disposed object using CollectionView EmptyView

---

Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellFlyoutSizing.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Controls/XamStore/Views/StorePages.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellAppearance.cs
Xamarin.Forms.Platform.Android/Renderers/ContainerView.cs
Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRenderer.cs
Xamarin.Forms.Platform.UAP/Shell/ShellRenderer.cs
Xamarin.Forms.Platform.UAP/Shell/ShellSplitView.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutContentRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/SlideFlyoutTransition.cs

Allow users to specify the Width and Height of the flyout on shell. This let's you expand the flyout to git across the entire screen or raise the flyout up for DualScreen cases or if you want it to be just above the TabBar
Added:
- double Shell.FlyoutWidth { get; set; } //Bindable Property
- double Shell.FlyoutHeight {get; set;}  //Bindable Property
- iOS
- Android
- UWP
Default
Modified WxH
Default
Modified WxH
Default
Modified WxH
- Shell store has a demo of these properties that you can play with

Shell FlyoutWidth and FlyoutHeight

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8814.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/CollectionView/ItemContentControl.cs

Hosting a CollectionView in Shell on UWP could result in a race condition where the items in the CollectionView were not fully loaded (in the UWP Loaded event sense) before a containing layout needed to measure the CollectionView (because items inside a ListViewBase can load asynchronously). This meant that the descendant controls might have IsNativeStateConsistent set to `false`, which then meant that the layout was skipped. This would result in a blank Layout, and could only be corrected by forcing another full layout pass (e.g., by resizing the window). 
This change forces the IsNativeStateConsistent flag to `true` for the contents of an ItemContentControl inside of a CollectionView, so that the layout step can complete. 
- fixes #8814
None
- UWP
None
Not applicable
Automated test …

Allow CollectionView on UWP to layout even if items are not loaded 

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12079.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/SwipeViewRenderer.cs

Fix SwipeItem NRE no setting the Text in UWP.
- fixes #12079 
None
- UWP
None
Not applicable
Launch Core Gallery and navigate to the Issue12079. Swipe to the right, if can open the SwipeView the test has passed.

[UWP] Fix SwipeItem NRE no setting the Text 

---

Xamarin.Forms.Core.UnitTests/GridTests.cs
Xamarin.Forms.Core/Grid.cs
Xamarin.Forms.Core/GridCalc.cs

Fixes regressions in the calculation of starred row/columns sizes introduced in 4.8. Column/row size values for starred columns/rows were being applied proportionally across requested space of the columns/rows, rather than taking into account the size of the largest column/row. This resulted in larger columns/rows being "squashed" and grid cells with StackLayouts overlapping other grid cells. 
- fixes #12961
- fixes #12725
- fixes #12900
None
None
Not applicable
Automated unit tests

Apply maximum starred column/row size for all starred columns/rows

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13136.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13136.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.MacOS/Renderers/BoxViewRenderer.cs
Xamarin.Forms.Platform.MacOS/Renderers/EditorRenderer.cs
Xamarin.Forms.Platform.MacOS/Renderers/EntryRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/BoxRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ButtonRenderer.cs

Fix NRE in ButtonRenderer in iOS.
- fixes #13136 
None
- iOS
- macOS
None
Not applicable
Launch Core Gallery and navigate to the issue 13136. Scroll quickly the list. Without crash, the test has passed.

[iOS/macOS] Fix NRE in ButtonRenderer

---

Xamarin.Forms.Controls/GalleryPages/GradientGalleries/GradientBrushDefaultOffsetGallery.xaml
Xamarin.Forms.Controls/GalleryPages/GradientGalleries/GradientBrushDefaultOffsetGallery.xaml.cs
Xamarin.Forms.Controls/GalleryPages/GradientGalleries/GradientsGallery.cs
Xamarin.Forms.Platform.MacOS/Extensions/BrushExtensions.cs
Xamarin.Forms.Platform.MacOS/Xamarin.Forms.Platform.macOS.csproj
Xamarin.Forms.Platform.iOS/Extensions/BrushExtensions.cs
Xamarin.Forms.Platform.iOS/Extensions/BrushExtensions.shared.cs
Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj

On Android, using a `GradientDrawable` renders the gradient even without setting the offsets. On iOS (or macOS), the gradient does not render without setting the offsets.
This PR adds changes to set the default values in case of not having any offset set in the Brush. In this way, we have the same behavior between different platforms.
- fixes #13092 
None
- iOS
- macOS
None
Launch Core Gallery and navigate to the Brushes samples. Select the new "GradientBrush Offsets Gallery" to verify that the gradient is rendered in the same way on iOS (and macOS) as on Android.

[iOS/macOS] Same offsets behavior in GradientBrush between platforms

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10608.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/ShellItemTransition.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootRenderer.cs

When the user was rapidly changing Flyout Item it would occasionally cause the content to become blank. These changes better stream line processing ShellItem changes relative to the animation used to process those changes. If the user changed back to a previous FlyouItem mid transition then a second renderer would get created for a flyout item that hadn't yet been removed. 
- fixes #13068
- iOS
- automated test included

More efficiently process rapid Flyout Item Changes

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10086.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10086.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8833.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8833.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/PositionGallery.cs
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeItemPositionGallery.xaml
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeItemPositionGallery.xaml.cs
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeItemViewPositionGallery.xaml
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeItemViewPositionGallery.xaml.cs
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeViewGallery.cs
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeViewMarginGallery.xaml
Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeViewMarginGallery.xaml.cs
Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs

The problem that 10086 describes is due to the default behavior applied when using Execute Mode.
The SwipeItem size is different based on the Mode.
- Reveal: A default width is applied to the SwipeItem, and in the case of SwipeItemView the same happens unless a WidthRequest is set.
- Execute: The width of the SwipeItem is the width of the SwipeView. If there are multiple elements, each element takes the proportional width.
However, using the **Threshold** property, this behavior can be modified.
This PR only include a new sample to validate that the issue could be fixed using the Threshold property, but not includes any changes.
- fixes #10086
- fixes #8833
None
- None
None
Launch Core Gallery and navigate to the issue 10086.

[Android / iOS] SwipeItem positioning issues fixes 

---

Xamarin.Forms.Core.UnitTests/GridTests.cs
Xamarin.Forms.Core/GridCalc.cs

The problems displayed in issue 13127 were a combination of the issues addressed in #13085, plus an additional missing scale by the appropriate star value when determining the dominant star row/column value. These changes apply the scaling.
- fixes #13127
- fixes #13034
None
None
Not applicable
Automated test

Scale potential star row/column values by the appropriate star value

---

.nuspec/Xamarin.Forms.AppLinks.nuspec
.nuspec/Xamarin.Forms.Visual.Material.nuspec
.nuspec/Xamarin.Forms.nuspec
DualScreen/DualScreen.Android/DualScreen.Android.csproj
EmbeddingTestBeds/Embedding.Droid/Directory.Build.targets
Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj
Xamarin.Forms.ControlGallery.Android/Directory.Build.targets
Xamarin.Forms.ControlGallery.Android/Nuget.Build.targets
Xamarin.Forms.DualScreen/Xamarin.Forms.DualScreen.csproj
Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
Xamarin.Forms.Material.Android/MaterialColors.cs
Xamarin.Forms.Material.Android/MaterialEntryRenderer.cs
Xamarin.Forms.Material.Android/MaterialFormsEditTextManager.cs
Xamarin.Forms.Material.Android/MaterialFormsTextInputLayoutBase.cs
Xamarin.Forms.Material.Android/Resources/Layout/MaterialPickerTextInput.axml
Xamarin.Forms.Material.Android/Resources/Layout/TextInputLayoutFilledBox.axml
Xamarin.Forms.Material.Android/Resources/values/styles.xml
Xamarin.Forms.Material.Android/Xamarin.Forms.Material.Android.csproj
Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj
Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
Xamarin.Forms.Platform.Android/ColorExtensions.cs
Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj

Update Xamarin.Google.Android.Material 1.1.0-rc3
- fixes #12858 
- Android
In theory there shouldn't be any. Compare the Visual Gallery on the previous version to this one
- open visual gallery, compare to ios, and compare to previous version

Androidx material bump

---

.Xamarin.Forms.iOS.slnf
Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11224.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11853.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11853.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
Xamarin.Forms.Platform.iOS/CollectionView/ObservableGroupedSource.cs
Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs

This is a partial backport of the fixes from PR #12837; some of the changes necessary for that fix also addressed the problems pointed out in #11853. These changes apply those fixes to version 4.8.
- fixes #11853
- fixes #12080
None
- iOS
None
Not applicable
Automated UI test

Fix semaphore issues updating CollectionView on iOS

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10578.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10578.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems

Cannot reproduce the issue with Xamarin.Forms 5.0-pre NuGet package nor in the 5.0.0 branch. For that reason, this PR only include a sample where validate the issue.
- fixes #10578 
None
- iOS
None
Launch Core Gallery and navigate to the issue 10578. If the NavigationBar Separator is hidden, the test has passed.

[iOS] NavigationPage.HideNavigationBarSeparator="true"

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/HeaderFooterShellFlyout.cs
Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutTemplatedContentRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/ShellItemRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/ShellViewRenderer.cs

- Open up a few renderer APIs to make it easier to customize parts of the Shell Flyout
- Fix measuring on the footer to pass in double.Infinity instead of -1. 
- Set the bottom margin on the content inside the flyout so it doesn't flow behind the footer view
Added:
- protected virtual ShellFlyoutTemplatedContentRenderer.ShellContext
- protected virtual ShellFlyoutTemplatedContentRenderer.FooterView
- protected virtual ShellFlyoutTemplatedContentRenderer.View
- protected virtual ShellFlyoutTemplatedContentRenderer.UpdateFlyoutHeader()
- protected virtual ShellFlyoutTemplatedContentRenderer.UpdateFlyoutFooter()
- protected virtual ShellItemRenderer.UpdateTabBarVisibility()
- Android
- UI Test included

Fix Flyout Footer measuring and Content Margin

---

Xamarin.Forms.Core/RadioButtonGroup.cs

Added setters to `RadioButtonGroup` `GroupName` and `SelectedValue`.
- fixes #12313
None
None
Not applicable

[Core] Added setters to RadioButtonGroup GroupName and SelectedValue

---

Xamarin.Forms.Platform.Tizen/Native/ListView.cs
Xamarin.Forms.Platform.Tizen/Renderers/ListViewRenderer.cs

This PR supports `ListView.SeparatorColor` and `ListView.SeparatorVisibility` in Tizen. 
- According to the product UX policy, the separator of `ListView` is not supported in  Galaxy Watch series (`TargetIdiom.Watch`) and and Samsung Smart TV model (`TargetIdiom.TV`), and nothing happens when using these properties.
None
**```namespace Xamarin.Forms.Platform.Tizen.Native```**
Added:
- Color ListView.BottomLineColor { get; set; } 
- Tizen
None

[Tizen] Support to ListView.SeparatorColor and SeparatorVisibility

---

Xamarin.Forms.Platform.WPF/Extensions/FontExtensions.cs

We should not re-splice a font file uri
- fixes #11789
None
- WPF
Before the change, the application will display the square, and after the change, the application will display the correct font
Before Screenshots
After Screenshots：

Fix miss font 

---

Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellFlyoutItemIsVisible.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellFlyoutItemIsVisible.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellItemIsVisible.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core.UnitTests/ShellFlyoutItemGroupTests.cs
Xamarin.Forms.Core.UnitTests/ShellTests.cs
Xamarin.Forms.Core/Shell/BaseShellItem.cs
Xamarin.Forms.Core/Shell/MenuShellItem.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellItem.cs

The idea here was to have an attached property called `FlyoutItem.IsVisible` that users could use to indicate when they wanted to hide just the FlyoutItem. This works great in code but in XAML when binding to "IsVisible" on a FlyoutItem that will now gets routed to the Attached property that's shadowing the non attached property. 
Added:
- Shell.FlyoutItemIsVisible //Attached BP
- BaseShellItem.FlyoutItemIsVisible //Attached BP that allows for easy access to this property on each BaseShellItem
Removed:
- FlyoutItem.IsVisible //Attached BP
- Removed the attached property FlyoutItem.IsVisible. Users wanting to just hide something in the Flyout will need to use Shell.FlyoutItemIsVisible.  
None
- unit tests modified
- UI Test Included

Fix poor choice for FlyoutItem BP Name

---

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselViewGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselXamlGallery.xaml.cs
Xamarin.Forms.Core.UITests.Shared/Tests/CarouselViewUITests.cs
Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs

There could be a issue where the position is being set and we are then also calling `UpdateIntialPosition`, we should reset the _goToPosition because we aren't using the animate scroll on `UpdateIntialPosition` 
- fixes #13122 
None
- Android
None
Not applicable
Added UITest

[Android] On UpdateInitialPosition reset _gotoPosition state

---

Xamarin.Forms.Core.UnitTests/ShellNavigatingTests.cs
Xamarin.Forms.Core.UnitTests/ShellTests.cs
Xamarin.Forms.Core.UnitTests/ShellUriHandlerTests.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellNavigatingEventArgs.cs
Xamarin.Forms.Core/Shell/ShellNavigationManager.cs
Xamarin.Forms.Core/Shell/ShellSection.cs
Xamarin.Forms.Platform.Android/Renderers/ShellSectionRenderer.cs

The deferral code was naively assuming there would be a delay between `GetDeferral` and `Complete` so the DeferralTask was never getting created. 
- Moved all of the shell navigation code into a specific ShellNavigationManager class so it's easier to follow
- Streamlined the Deferral flow so the execution flow is more linear
- fixes #13131

Fix NRE if user immediately completes Deferral

---

Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
Xamarin.Forms.ControlGallery.WindowsUniversal/_13109IssueHelper.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13109.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/FileImageSourceHandler.cs

Fixed NRE load image from ImageSource in UWP.
- fixes #13109
None
- UWP
None
Not applicable
Launch Core Gallery and navigate to the issue 13109. Without exceptions, the test has passed.

[UWP] Fixed NRE load image from ImageSource

---

Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs

With this PR, **Layout Compression**, which is only available on iOS and Android platforms, can also be available on Tizen. 
The usage is also the same.
In XAML, layout compression can be enabled by setting the `CompressedLayout.IsHeadless` attached property to true on a layout class:
```xml
<StackLayout CompressedLayout.IsHeadless="true">
...
</StackLayout>   
```
Alternatively, it can be enabled in C# by specifying the layout instance as the first argument to the `CompressedLayout.SetIsHeadless` method:
```cs
CompressedLayout.SetIsHeadless(stackLayout, true);
```
Please visit [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/layout-compression) for more information on a **Layout Compression**.
None
None
- Tizen
None

[Tizen] Support to Layout Compression

---

Xamarin.Forms.Platform.Tizen/Forms.cs
Xamarin.Forms.Platform.Tizen/Native/EvasBox.cs
Xamarin.Forms.Platform.Tizen/Native/EvasFormsCanvas.cs
Xamarin.Forms.Platform.Tizen/Native/Page.cs
Xamarin.Forms.Platform.Tizen/Renderers/FastLayoutRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/ScrollViewRenderer.cs
Xamarin.Forms.Platform.Tizen/StaticRegistrar.cs

This PR is for improving layouting (especially on scrolling) performance. Previously, we were using `ElmSharp.Box` internally for layouting. In normal case this works fine, but we found an issue where scrolling performance degrades as more controls are included in the `ScrollView` and the layout hierarchy gets more complex. For target devices with severe resource constraints, scrolling performance decreases more noticeably.
To solve this problem, this PR implements and uses `EvasBox` (from evas) instead of `Box` (from elementary) to optimize unnecessary coordinate calculation during layout. As a result, it was confirmed that the scroll performance was improved by about 1 to 2 times compared to the previous one.
You can use `FastLayoutRenderer` through opt-in as shown below. (The default …

[Tizen] Added Fast Layout Opt-in

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11214.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core/Shell/IShellController.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellGroupItem.cs
Xamarin.Forms.Core/Shell/ShellItem.cs
Xamarin.Forms.Core/Shell/ShellSection.cs
Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRecyclerAdapter.cs
Xamarin.Forms.Platform.UAP/Shell/ShellRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewController.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewSource.cs

- Added an event to IShellController that can specifically be used to indicate FlyoutItems have changed. Currently this is based on the StructureChanged event but as of 4.6 the StructureChanged event only fires for currently visible pages. This was changed in 4.6 because it was sending a "StructureChanged" event every time you added a new Shell Element which was causing some performance issues and visual artifacts. These changes also for intelligently fire the FlyoutItem changed event when it detects that the list of Flyout Items has actually changed opposed to just firing it off all of the time
- Converted the Flyout Items on UWP shell to use an ObservableCollection. NavigationView doesn't really do very well if you just swap out the Source.
- fixes #11214
Added:
- event EventHandler …

Add new xplat event to to propagate FlyoutItemsChanged events to the platforms

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11969.xaml.cs

The PopUp from test 11969 remains on the screen after navigating to the next test which makes the next test fail. 
- iOS
- iOS tests all pass

Close popup before exiting test

---

.Xamarin.Forms.iOS.slnf
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/DataTemplateGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/DataTemplateSelectorGalleries/VariedSizeDataTemplateSelectorGallery.xaml
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/DataTemplateSelectorGalleries/VariedSizeDataTemplateSelectorGallery.xaml.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ItemSizeGalleries/ChatExample.xaml
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ItemSizeGalleries/ChatExample.xaml.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ItemSizeGalleries/ItemsSizeGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ItemsSourceGenerator.cs
Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
Xamarin.Forms.Platform.iOS.UnitTests/ObservableItemsSourceTests.cs
Xamarin.Forms.Platform.iOS/CollectionView/CarouselTemplatedCell.cs
Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/HorizontalCell.cs
Xamarin.Forms.Platform.iOS/CollectionView/HorizontalTemplatedHeaderView.cs
Xamarin.Forms.Platform.iOS/CollectionView/IndexPathHelpers.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewDelegator.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
Xamarin.Forms.Platform.iOS/CollectionView/LayoutAttributesChangedEventArgs.cs
Xamarin.Forms.Platform.iOS/CollectionView/TemplatedCell.cs
Xamarin.Forms.Platform.iOS/CollectionView/VerticalCell.cs
Xamarin.Forms.Platform.iOS/CollectionView/VerticalSupplementaryView.cs
Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj

CollectionView on iOS utilizes the UICollectionViewFlowLayout's EstimatedItemSize property to allow virtualization; for items which have not yet been realized, the EstimatedItemSize is used for calculating properties like the UICollectionView's content size (for scrollbars, etc). 
When the layout is invalidated, this size is also used for newly inserted items (which have not yet had their actual sizes determined by a cell) and for any items invalidated by insertion/removal. For single DataTemplate scenarios, this is generally fine, since the estimated size calculated from the first item is likely to be close to or exactly the size of subsequent items. 
These changes now cache the size of each cell as they are updated from the initial estimated size, and reuses the cached values during …

Cache cell sizes after resize from estimates

---

Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/StructuredItemsViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/TemplateHelpers.cs

Somewhere along the way the CollectionView's EmptyView on iOS regressed and no longer could display the header, footer, and EmptyView at the same time (the EmptyView would sit on top of the header, obscuring it).
These changes undo the changes which caused the regression and fix the problem a different way, leaving the EmptyView and Header intact.
No automated test for the regression here, because it's already included in #13032.
- fixes #8326 (again)
- fixes #13252
None
- iOS
None
Not applicable
Control Gallery -> Issue 8326; the header, footer, and empty view should all be visible when the test loads.
Control Gallery -> CollectionView Gallery -> EmptyView Gallery -> EmptyView RTL; the empty view text should only shift alignment when the page is set to RTL, rather than horizontally …

Restore ability to display header, footer, and empty view simultaneously

---

Stubs/Xamarin.Forms.Platform.cs
Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
Xamarin.Forms.Platform.Android/Renderers/FlyoutPageRendererNonAppCompat.cs

As part of the shift to FlyoutPage from MasterDetailPage we only moved over the AppCompat renderers so if someone is still on non appcompat and tries to use FlyoutPage they will just get a blank screen. This PR will give them a more useful message. 
- Android
- Make sure Flyout Page still works with AppCompat (and other platforms)
- Verify Exception Message when switching to non appcompat

Add Exception Message when trying to use FlyoutPage with NonAppCompat

---

Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellWithCustomRendererDisabledAnimations.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core/Shell/ShellNavigationManager.cs
Xamarin.Forms.Platform.Android/Renderers/ShellContentFragment.cs

ShellItemRenederer on Android let's users override `SetupAnimation` to define custom animations.  The navigation code on android subscribes to "AnimationFinished" to know when the animation has finished and complete the navigation Task. The problem here is that if the SetupAnimation doesn't actually setup an animation then "AnimationFinished" never gets called from ShellContentFragment.  The real fix here will be to add a better API for the SetupAnimation override. Currently it's just
```C#
SetupAnimation(ShellNavigationSource navSource, AndroidX.Fragment.App.FragmentTransaction t, Page page)
```
But it should really be something like
```C#
SetupAnimation(ShellNavigationSource navSource, AndroidX.Fragment.App.FragmentTransaction t, Page page, Action callMeWhenAnimationHasFinished)
```
Or …

Invoke AnimationFinished from fragment if no animation has been added

---

Xamarin.Forms.ControlGallery.Android/_12484CustomRenderer.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12484.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/RadioButtonTemplateFromStyle.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/Platform.cs
Xamarin.Forms.Platform.UAP/Platform.cs
Xamarin.Forms.Platform.iOS/Platform.cs

Isolate the TemplatedView check inside Platform.cs to just RadioButton for now to accommodate the two fixes referenced in this issue. The issue with the changes inside Platform.cs means that if someone inherits from TemplatedView and registers a custom renderer it won't use that CustomRenderer it will just use a DefaultRenderer. 
- fixes #12484
- fixes #13261
- Android
- UI Test included
- Test Templating with RadioButton (Automated test incoming)

Isolate the TemplatedView check inside Platform.cs to just RadioButton until we can provide a more generalized fix

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellFlyoutBackground.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellFlyoutContentOffest.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellFlyoutContentWithZeroMargin.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutContentRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutLayoutManager.cs

With the Shell Flyout Content PR the Flyout Content started getting inserted behind the FlyoutBackground Image. These changes ensure that all the UIView's that are part of Flyout Content more deterministically get inserted into the Flyout
- fixes #13295
- iOS
- included UI Tests for some offset validation
- When the background image overlaps the content the content is still clickable so there isn't a great way to automate the test

Make sure all the UIViews is iOS are added at the correct hierarchy

---

Xamarin.Forms.Platform.iOS.UnitTests/DatePickerTests.cs
Xamarin.Forms.Platform.iOS.UnitTests/PlatformTestFixture.cs
Xamarin.Forms.Platform.iOS.UnitTests/TimePickerTests.cs
Xamarin.Forms.Platform.iOS.UnitTests/Xamarin.Forms.Platform.iOS.UnitTests.csproj
Xamarin.Forms.Platform.iOS/Renderers/DatePickerRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/TimePickerRenderer.cs

The check for iOS 14 and setting of the "wheels" style date/time pickers was behind an XCode 11 check which is no longer used. So both controls were defaulting to the new inline style (which the renderers do not know how to handle yet). 
These changes revert the style to the "wheels" style on iOS 14, and add tests to ensure that style remains until we're ready to revamp the renderers for inline styles.
- fixes #13331
None
- iOS
None
Not applicable
Automated platform tests

[iOS] Restore wheels date/time picker styles in 5.0

---

Xamarin.Forms.Platform.Tizen/Cells/EntryCellRenderer.cs
Xamarin.Forms.Platform.Tizen/Cells/ViewCellRenderer.cs
Xamarin.Forms.Platform.Tizen/FormsApplication.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/EmptyItemAdaptor.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/ItemTemplateAdaptor.cs
Xamarin.Forms.Platform.Tizen/Native/ListView.cs
Xamarin.Forms.Platform.Tizen/Native/TitleViewPage.cs
Xamarin.Forms.Platform.Tizen/PopupManager.cs
Xamarin.Forms.Platform.Tizen/Renderers/FastLayoutRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/ILayoutRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/LayoutRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/RefreshViewRenderer.cs
Xamarin.Forms.Platform.Tizen/Renderers/SwipeViewRenderer.cs
Xamarin.Forms.Platform.Tizen/Shell/NavigationView.cs
Xamarin.Forms.Platform.Tizen/Shell/SearchResultList.cs
Xamarin.Forms.Platform.Tizen/Shell/ShellNavBar.cs

This PR is to fix incorrect layout when applying FastLayout (introduced in #13221 ).
None
**```namespace Xamarin.Forms.Platform.Tizen```**
Added:
- interface ILayoutRenderer
- Tizen
None

[Tizen] Fix bug to the FastLayoutRenderer

---

Xamarin.Forms.Platform.Tizen/SkiaSharp/FrameRenderer.cs

This PR fixes `Frame` not creating unused clipper.
The clipper only needs to be created when `Frame` has `Content`.
Otherwise, white color clipper will be unexpectedly drawn in `Frame` as background.
- N/A
- None
- Tizen
Before:
1) Frame without Content : This includes white background which is unexpected.
2) Frame with BackgroundColor which has alpha : The background blends with white background which is unexpected.
3) Frame with Content : Proper behavior.
After:
1) Frame without Content : This includes empty background. (Proper behavior.)
2) Frame with BackgroundColor which has alpha : The background blends with real background. (Proper behavior.)
3) Frame with Content : (Proper behavior.)

[Tizen] Fix Frame show clipper canvas issue

---

Xamarin.Forms.Platform.iOS/Forms.cs

Moves use of NSApplication EffectiveAppearance property inside of Mojave or later check.
- fixes #13071
None
- macOS
None
Not applicable
Run this on High Sierra, see if it crashes. (It shouldn't.)

Fix 'effectiveAppearance' crash on pre-Mojave

---

Xamarin.Forms.Core/Shell/Shell.cs

Like it's related properties (FlyoutHeader/FlyoutFooter) the FlyoutContent should be returning type object and not View
- tests run

FlyoutContent should return type object

---

Xamarin.Forms.Platform.iOS/ViewRenderer.cs

Protect against Element being null and causing trouble like it did in #13136. 
Changed:
- `if(Control != null)` => `if(Control != null && Element != null)`
- iOS
None
Not applicable
I was not able to duplicate this locally but my clients could repeatedly duplicate it on certain devices. After pushing this change to them the crashes stopped.

[iOS] Fix NRE in ViewRenderer.LayoutSubviews

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellTitleView.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutContentRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutHeaderContainer.cs
Xamarin.Forms.Platform.iOS/Renderers/UIContainerView.cs
Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj

The same UIContainerView code is used to render the TitleView and the Flyout Header View. In 5.0 the code used to layout the view slightly changed which is causing the TitleView to add a margin equal to the SafeArea. The changes here create a subclass of UIContainerView for the FlyoutHeader so the FlyoutHeader can set a margin that doesn't interfere with the TitleView on iOS 
- fixes #13310
- fixes #13306
- iOS

Fix margin on Shell TitleView

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13203.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs

If the CollectionView is the root Content element for a page on iOS and IsVisible transitions from false to true, the CollectionView's layout is not invalidating. This change invalidates the layout so that the CollectionView is refreshed.
Note that this isn't an issue if the CollectionView is inside some other view (e.g., a StackLayout); it's only an issue if it's the root of the page Content.
- fixes #13203
None
- iOS
None
Not applicable
Automated UI test

Invalidate CollectionView Layout on transition to IsVisible = true

---

Xamarin.Forms.ControlGallery.WindowsUniversal/SecondaryWindowService.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2482.cs
Xamarin.Forms.Platform.UAP/FontExtensions.cs

When using multiple windows we need to take in account that each CoreApplicationView has it's own thread so caching items doesn't work if they are shared. Like FontFamilies for example
We also need to relayout our contents when the window is resized.
- fixes #11705
None
- UWP
None
Not applicable
Try open 2 our 3 windows from the control gallery

[UWP] Fixes for font when using MultiWindow

---

Xamarin.Forms.Core/RadioButton.cs

The ContentPresenter inside the Frame for the default RadioButton template was centered, rather than filling the Frame as expected. These changes make the ContentPresenter fill the Frame.
- fixes #13374
None
- iOS
None
Before:
After:
Control Gallery -> RadioButton Gallery -> RadioButton Content
The "Option A" text on the first RadioButton should be left-aligned, not centered.

Make RadioButton default template's ContentPresenter fill the Frame

---

Xamarin.Forms.Core.UnitTests/ShellTestBase.cs
Xamarin.Forms.Core.UnitTests/ShellUriHandlerTests.cs
Xamarin.Forms.Core/Shell/BaseShellItem.cs
Xamarin.Forms.Core/Shell/NavigationRequest.cs
Xamarin.Forms.Core/Shell/RequestDefinition.cs
Xamarin.Forms.Core/Shell/RouteRequestBuilder.cs
Xamarin.Forms.Core/Shell/ShellNavigationManager.cs
Xamarin.Forms.Core/Shell/ShellSection.cs
Xamarin.Forms.Core/Shell/ShellUriHandler.cs

Fixed Hierarchical Global Route Registration so that it would correctly apply the route registered to the current state of shell
If a user is registering full route path  `Route.Register("path1/path2/path3")` and Shell is currently at `"path1/path2"`
Then the user should be able to navigate to that route via
- `GotoAsync("path3")` or `Route.Register("path1/path2/path3")`
- fixes #13328
- fixes #11237

Fix Shell Navigation for Hierarchally registered Global Routes

---

Xamarin.Forms.Core/Grid.cs

We invalidate when the items of the row/col def are modified. With this,
we also invalidate when the full collection is swapped.
- fixes #13154
None
None
Not applicable

[C] Invalidate Grid when row/col def is replaced

---

Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs

Recently, fixing a TabView issue https://github.com/xamarin/XamarinCommunityToolkit/issues/630 (which internally uses CarouselView) in the Xamarin Community Toolkit, I noticed some unexpected behavior with the initial position of the CarouselView.
The problem is that the casting:
`var items = Carousel.ItemsSource as IList;`
It is not correct in all cases. This PR adds changes to use an enumerator.
None
- Android
None
Not applicable

[Android] Changes in CarouselView initial position 

---

build.cake

When running UI Tests against iOS and Android via cake the nunit where isn't parsing correctly. This fixes the issue
- make sure iOS 14 tests and UWP tests run and are filtered correctly

Fix parsing of azure devops unit test filters

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13436.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13436.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems

The issue is a crash in `CarouselView` adjusting `PeekAreaInsets` in `OnSizeAllocated`. However, cannot reproduce the issue in 5.0.0 branch. For that reason, this PR only include the test.
@rmarinho The exception comes from `UpdateFromCurrentItem` method. It could be fixed with one of the last PRs like https://github.com/xamarin/Xamarin.Forms/pull/13182?
- fixes #13436 
None
- Android
None
Launch Core Gallery and navigate to the issue 13436. Without exceptions, the test has passed.

[Android] Crash in CarouselView adjusting PeekAreaInsets in OnSizeAllocated

---

Xamarin.Forms.Platform.iOS/Extensions/AccessibilityExtensions.cs
Xamarin.Forms.Platform.iOS/ViewRenderer.cs

The original comment says this
```
// UIKit UIViews created via storyboard default IsAccessibilityElement to true, BUT	
// UIViews created programmatically default IsAccessibilityElement to false.	
// We need to default to true to allow all elements to be accessible by default and	
// allow users to override this later via AutomationProperties.IsInAccessibleTree
```
I don't feel like that's completely accurate. If you inspect IsAccessibilityElement directly after instantiating a control then it is indeed false but by the time the control is rendering it is set to the correct value for the given control. If you breakpoint SetAccessibilityElement inside the Automation Extensions you will see that IsAccessibilityElement is true when it should be true and false when it should be false
There …

Don't set IsAccessibilityElement for everything

---

Xamarin.Forms.Core.UnitTests/ResourceDictionaryTests.cs
Xamarin.Forms.Core/ResourceDictionary.cs
Xamarin.Forms.Xaml.UnitTests/AppResources/RD13209.xaml
Xamarin.Forms.Xaml.UnitTests/Issues/Gh13209.xaml
Xamarin.Forms.Xaml.UnitTests/Issues/Gh13209.xaml.cs

treat elements from the "Source" RD like if they were part of the actual
dictionary, for Count, and Remove
- fixes #13209
None
- iOS
- Android
- UWP
None
Not applicable

[C] elements from Source are like items

---

Xamarin.Forms.Core.UnitTests/ShellTests.cs
Xamarin.Forms.Core/Page.cs
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellTemplatedViewManager.cs
Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRecyclerAdapter.cs
Xamarin.Forms.Platform.UAP/Shell/ShellFlyoutItemRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSearchResultsRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewSource.cs
Xamarin.Forms.Platform.iOS/Renderers/UIContainerCell.cs

Shift Shell over so it returns everything from the Logical Children structure which plays into Hot Reload and the Live Visual Tree better. Initially I didn't use LogicalChildren because Page (the base class of Shell) makes a bunch of assumptions against its LogicalChildren. This PR intercepts those assumptions and just lets Shell manage its logical children 
- fixes #13171 
- Validate that Live Visual Tree displays flyout items/flyoutheader/flyoutfooter/flyoutcontent

Setup Shell to only use the LogicalChildren for reporting its LogicalChildren

---

Xamarin.Forms.Build.Tasks/CompiledConverters/RDSourceTypeConverter.cs
Xamarin.Forms.Controls/AppResources.xaml
Xamarin.Forms.Core/ResourceDictionary.cs
Xamarin.Forms.Xaml.UnitTests/ResourceDictionaryWithSource.xaml
Xamarin.Forms.Xaml.UnitTests/ResourceDictionaryWithSource.xaml.cs

[X] Accept RD.Source with assembly
this also always add the assembly part in the Source url
- fixes #13187
- fixes #2660
None
- iOS
- Android
- UWP
None
Not applicable

[X] Accept RD.Source with assembly

---

Xamarin.Forms.ControlGallery.iOS/CustomRenderers.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13390.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/SlideFlyoutTransition.cs

ShellFlyoutRenderer wasn't correctly checking for scenarios where users are implementing a Custom Slide Flyout Transition class which was causing an NRE.  I've also set the `LayoutViews` method to be virtual and add made `UpdateFlyoutSize` public so users can reuse SlideFlyoutTransition
- fixes #13390 
Added:
```C#
public class SlideFlyoutTransition 
public virtual bool UpdateFlyoutSize(double height, double width)
```
Changed:
```C#
public class SlideFlyoutTransition 
public virtual void LayoutViews(CGRect bounds, nfloat openPercent, UIView flyout, UIView shell, FlyoutBehavior behavior)
```
- iOS

Fix NRE when using Custom Slide Transition

---

src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/AbstractViewHandlerTests.cs
src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/Layouts/ConstraintTests.cs
src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/Layouts/HorizontalStackLayoutManagerTests.cs
src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/Layouts/LayoutExtensionTests.cs
src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/Layouts/VerticalStackLayoutManagerTests.cs
src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/PropertyMapperTests.cs
src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/TestCategory.cs
src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/TestClasses/HandlerStub.cs
src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/Xamarin.Platform.Handlers.UnitTests.csproj
src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/xUnitCustomizations.cs

Move core tests from NUnit -> xUnit for consistency.
Also added a couple of custom xUnit attributes to make the test output nicer and make categories easier:
FactAttribute - defaults the display name of the test to the method name, rather than the full namespace + method.
TheoryAttribute - same thing, but for Theory
CategoryAttribute - Convenience attribute for setting a Trait with the name "Category" on test classes and methods. Handles multiple categories at once.

Move core tests to xUnit

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/LabelFormattedTextHtmlPadding.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS.UnitTests/HtmlLabelTests.cs
Xamarin.Forms.Platform.iOS/Extensions/LabelExtensions.cs

Prevent app crashing when there's a label with FormattedText, TextType=Html, and Padding properties.
- iOS
App no longer crashes
Set main page to LabelFormattedTextHtmlPadding
Ensure app doesn't crash > Test passes

Fix formatted text text type crash

---

Xamarin.Forms.Platform.Tizen/Forms.cs
Xamarin.Forms.Platform.Tizen/TizenPlatformServices.cs

This PR modifies to use [System.AppDomain](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain?view=netcore-2.1#properties) instead of local AppDomain implementation to get assemblies.
- fixes https://github.com/xamarin/MobileBlazorBindings/issues/307 (partially)
None
- Tizen
None

[Tizen] Use System.AppDomain on Init

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8701.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Controls/App.cs
Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs

TalkBack would read back button as 'Unlabeled button' even when a back button title is set.
Now, TalkBack will read the back button title when it is set.
- fixes #8701
- Android
- Set main page to Issue8701 > Run on Android > Follow on-screen instructions

[Android] Fix TalkBack to read back button title when it is set

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12642.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12848.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5500.cs

- 12848 deals with the CarouselView so the behavior being tested on 12848 for the CV will need to be fixed
- 5500 is testing a bug on iOS with visual so the test isn't relevant for UWP. It's occasionally failing on UWP because the win app driver sometimes won't type the first letter of text
- UWP
- UWP tests pass

Ignore tests that are currently irrelevant for UWP

---

Xamarin.Forms.Platform.Android/Renderers/ButtonRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/CarouselPageRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/MasterDetailRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/RefreshViewRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/SearchBarRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/SliderRenderer.cs

When disposing renderers the framework need to unsubscribe events,
because of the different lifetime between the two parts this often cause memory leaks and dispose issues.
For the DotNet part the form is an event with +=/-=, in several past PR I fixed some missing calls of this form.
But for Android part the form is different, it's SetListener or AddListener, and RemoveListener.
I have checked Android renderers code and found that some renderers lack the removal of the setted listeners.
The goal of this PR is to add the missing ones.
- fixes #
None
- Android
None
Not applicable
As always with dispose and memory leaks issues, not possible to directly test it, just check if current tests not regress.

[Android] Remove listeners on dispose

---

Xamarin.Forms.Core.UnitTests/ShellModalTests.cs
Xamarin.Forms.Core.UnitTests/ShellTestBase.cs
Xamarin.Forms.Core/Shell/ShellUriHandler.cs

When processing a ".." operation to recalculate the new shell path query strings were incorrectly being processed as part of the path. The changes in this PR properly process only the path part when recalculating the destination path 
- fixes #13506

Fix popping with ".." and QueryString

---

Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs

Fix Page BackgroundColor issue using DarkTheme on iOS.
- fixes #12406 
- fixes  #12865
- fixes #13088
None
- iOS
None
Launch Core Gallery, then change the theme and verify that the page background color changed.

[iOS] Fix Page BackgroundColor issue using DarkTheme

---

Xamarin.Forms.Platform.iOS/Renderers/DatePickerRenderer.cs

Fixed date formatter issue with different timezone on iOS. From this changes: https://github.com/xamarin/Xamarin.Forms/commit/938700b28f500ae0beb7967e10516199b03b2b71#diff-e232660a1722e87a9febc4d293b145e11c6b707d432ae3f637d208e92d70a27d
We use a `NSDateFormatter`. Since we didn’t specify otherwise, the date formatter uses the system time zone, which is set to the location.
The fix is specify a time zone with a fixed temporal offset instead of a location.
- fixes #13366 
None
- iOS
None
Not applicable
1. Set the system datetime to 01/07/21 19:01h and timezone GMT+5. 
2. Launch Core Gallery.
3. Look at the DatePicker, the date must be 01/07/21.

[iOS] Fixed date formatter issue with different timezone

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43161.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12685.cs
Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs

Fix iOS 14 broken tests.
None
- iOS
None
Not applicable
The build should pass.

[Housekeeping] Fix iOS 14 broken tests

---

Xamarin.Forms.Core.UnitTests/ShellNavigatingTests.cs
Xamarin.Forms.Core.UnitTests/ShellNavigationStateTests.cs
Xamarin.Forms.Core.UnitTests/ShellUriHandlerTests.cs
Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellNavigationManager.cs
Xamarin.Forms.Core/Shell/ShellNavigationState.cs
Xamarin.Forms.Core/Shell/ShellSection.cs

Fix string constructor for ShellNavigationState so it sets both Location and FullLocation
- fixes #13422 

Fix string constructor for ShellNavigationState

---

.nuspec/Xamarin.Forms.Visual.Material.nuspec
.nuspec/Xamarin.Forms.nuspec
DualScreen/DualScreen.Android/DualScreen.Android.csproj
EmbeddingTestBeds/Embedding.Droid/Directory.Build.targets
Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj
Xamarin.Forms.ControlGallery.Android/Directory.Build.targets
Xamarin.Forms.ControlGallery.Android/Nuget.Build.targets
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/VisualControlsPage.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/VisualControlsPage.xaml.cs
Xamarin.Forms.DualScreen/Xamarin.Forms.DualScreen.csproj
Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
Xamarin.Forms.Material.Android/MaterialEditorRenderer.cs
Xamarin.Forms.Material.Android/Xamarin.Forms.Material.Android.csproj
Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj

It looks like the latest material libraries only partially fixes the duplicated place holder. If you are using a multi line editor then the place holder shows as duplicate until you start typing. After you start typing the hint text disappears.
- fixes #13541
- Android
- open the visual gallery and verify that the place holder and other controls look to render correctly

Google material bump and set hint to transparent for multi line

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13203.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13551.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/Platform.cs
Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
Xamarin.Forms.Platform.UAP/LayoutRenderer.cs
Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs
Xamarin.Forms.Platform.iOS/CollectionView/GridViewLayout.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
Xamarin.Forms.Platform.iOS/Platform.cs
Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs

The change to on-demand layout resolution in 5.0.0-pre2 moved the layout resolution to the layout renderers. Unfortunately, this meant that some ContentView uses (13492) and any custom renderer which replaced the layout renderers (13418) would not update their layout changes properly. 
These changes move the layout resolution call to the base VisualElementRenderer class on each platform; this way, they encompass content views and any custom layout renderers. 
- fixes #13418
- fixes #13492
- fixes #13551 
- fixes #13126
None
- iOS
- Android
- UWP
None
Not applicable
Unfortunately, this one is hard to write a test for without breaking all of Control Gallery. Best we can do is load up the repro projects from #13418 and #13492, apply the NuGet package from this PR, and verify that the …

Move layout change resolution calls up to VisualElementRenderer

---

build/provisioning/provisioning.csx

I removed this , but we actually need it for new machines. 
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable

[Provisioning] Install mono for fresh machine

---

Xamarin.Forms.Platform.Tizen/Native/CollectionView/CollectionView.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/GridLayoutManager.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/ItemTemplateAdaptor.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/LinearLayoutManager.cs

This PR fixes several `CollectionView` issue
- `Scrolled` event was not fired when scroll animation was not started, it was resolved
- At first rendering, raise `Scrolled` event to send items layouting information
- On MeasureFirstItem option, item that including image, layouting was wrong, it was resolved
- Provide a default header/footer template
- fixes
None
- Tizen
None
Not applicable

[Tizen] Fix several CollectionView issue on Tizen

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13126.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13126_2.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewRenderer.cs
Xamarin.Forms.Platform.iOS/CollectionView/ObservableGroupedSource.cs
Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs

Fix timing issue where CollectionView items are added to ObservableSource before CollectionView is visible, and CollectionView is later made visible via Binding.
- fixes #13126
None
- iOS
None
Not applicable
Automated UI test.

[iOS] Allow observable source update while CollectionView is not visible

---

Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRecyclerAdapter.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewController.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewSource.cs
Xamarin.Forms.Platform.iOS/Renderers/UIContainerCell.cs

Currently on iOS and Android when you scroll the Flyout the Flyout Items will clear and recreate renderers. They will also clear and recreate renderers if you remove items or rearrange. This causes a lot of churn. This PR disables cell recycling on iOS and Android since we're not dealing with massive lists. If users want full virtualization for the FlyoutItems they should use a custom FlyoutContent with a CollectionView. These changes also keep track of FlyoutItems so when the list is modified that cells/renderers are reused instead of recreating everything. 
These changes are optimized around a small to medium sized list
- iOS
- Android
- make sure the store shell flyout scrolls nicely
- Test a few of the UI tests that involve flyout visibility to make sure items show and vanish

Fix FlyoutItem recycling

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3840.cs
Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs

Try fix UITEst failing on AppCenter for iOS14
None
- iOS
- Android
- UWP
None
Not applicable

[UITestst] Add QueryUntilNotPresent

---

Xamarin.Forms.Platform.Tizen/DragGestureHandler.cs
Xamarin.Forms.Platform.Tizen/DropGestureHandler.cs
Xamarin.Forms.Platform.Tizen/Extensions/DragDropExtensions.cs
Xamarin.Forms.Platform.Tizen/GestureDetector.cs
Xamarin.Forms.Platform.Tizen/Properties/AssemblyInfo.cs
Xamarin.Forms.Platform.Tizen/Shapes/ShapeView.cs
Xamarin.Forms.Platform.Tizen/SkiaSharp/CanvasViewRenderer.cs
Xamarin.Forms.Platform.Tizen/SkiaSharp/ICanvasRenderer.cs

This PR is to add handlers for DragGestureRecognizer and DropGestureRecognizer.
Available UI Controls for Dragging
- Label
- Entry
- CheckBox
- RadioButton
- TimePicker
- Image
- Shape
Available UI Controls for Drop
- Label
- BoxView
- Frame (when it has background color or content)
- Image 
- Entry
None 
None
- Tizen
None

[Tizen] Add drag and drop gesture handlers

---

Xamarin.Forms.Controls/GalleryPages/IndicatorViewGalleries/IndicatorGalleries.cs
Xamarin.Forms.Controls/GalleryPages/IndicatorViewGalleries/IndicatorsSample.xaml
Xamarin.Forms.Controls/GalleryPages/IndicatorViewGalleries/IndicatorsSampleMaximumVisible.xaml
Xamarin.Forms.Controls/GalleryPages/IndicatorViewGalleries/IndicatorsSampleMaximumVisible.xaml.cs
Xamarin.Forms.Controls/GalleryPages/IndicatorViewGalleries/IndicatorsTemplateSample.xaml
Xamarin.Forms.Controls/GalleryPages/IndicatorViewGalleries/IndicatorsTemplateSample.xaml.cs
Xamarin.Forms.Core/IndicatorStackLayout.cs

When using item template call the VisualStateManager selected state
- fixes #13515 
None
- Core
Should be able to use VisualStateManger select state 
Not applicable
Test using `IndicatorsTemplateSample` on IndicatorsGallery

[Core] Add Selected VisualState for IndicatorView

---

Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs

Under the right layout circumstances, the UICollectionView's size can repeatedly change by very, very small amounts (height differences less than 0.0001). The layout cell sizes cache was blindly invalidating even for very small changes, which caused layout jumps and incorrect scrollbar positions.
These changes prevent cache invalidation in those scenarios.
- fixes #13719
None
- iOS
None
Not applicable
Grab the repro project from #13231 and update it to this PR; the CollectionView should scroll smoothly and should scroll all the way to the bottom of the last item. If the last item will no scroll fully into view, this PR is failing.

Prevent overeager cache invalidation when the CollectionView height changes by very small amounts

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13684.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13684.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems

Can reproduce the issue using Xamarin.Forms 5.0 Nuget Package but, everything works as expected in 5.0 branch. For that reason, this PR only include the repro sample to validate the issue.
- fixes #13684
None
- Android
None
Launch Core Gallery and navigate to the issue 13684. If the text of each item has two lines in addition to do tail truncation, the test has passed.

[Android] LineBreakMode incompatible with MaxLines

---

src/Forms/src/Xamarin.Forms.Core/Layout/Layout.cs
src/Forms/test/Xamarin.Forms.Core.UnitTests/Layouts/LayoutTests.cs
src/Forms/test/Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj

Fix it so Arrange isn't called if the measure is invalid. 
As is the arrange was getting called and then the measure but then not another arrange so nothing would layout
- Run the new .net maui galleries on CG. Without this change the pages are blank
- Automated unit tests

If the measure is invalid don't perform an arrange

---

Xamarin.Forms.Platform.Tizen/Renderers/SwipeViewRenderer.cs

This PR fixes an issue that `SwipeItemView`'s Command is executed twice.
-  N/A
None
- Tizen
None

[Tizen] Fix SwipeView Command issue

---

src/Platform.Handlers/tests/Xamarin.Platform.Handlers.DeviceTests/Handlers/Slider/SliderHandlerTests.Android.cs

The Progress value on SeekBar is an int so we need to cast the expected value to int inside the test to account for the loss of precision
- Device Tests pass

Cast Slider expected value to int

---

Xamarin.Forms.Platform.Tizen/Native/CollectionView/EmptyItemAdaptor.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/ItemTemplateAdaptor.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/LinearLayoutManager.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/ViewHolder.cs
Xamarin.Forms.Platform.Tizen/Properties/AssemblyInfo.cs
Xamarin.Forms.Platform.Tizen/Shell/ShellItemRenderer.cs
Xamarin.Forms.Platform.Tizen/Shell/ShellNavBar.cs
Xamarin.Forms.Platform.Tizen/Shell/ShellRenderer.cs
Xamarin.Forms.Platform.Tizen/Shell/ShellSectionRenderer.cs
Xamarin.Forms.Platform.Tizen/Shell/ShellSectionStack.cs
Xamarin.Forms.Platform.Tizen/Shell/TV/FlyoutItemTemplateAdaptor.cs
Xamarin.Forms.Platform.Tizen/Shell/TV/FlyoutItemTemplateSelector.cs
Xamarin.Forms.Platform.Tizen/Shell/TV/TVNavigationDrawer.cs
Xamarin.Forms.Platform.Tizen/Shell/TV/TVNavigationView.cs
Xamarin.Forms.Platform.Tizen/Shell/TV/TVShellItemRenderer.cs
Xamarin.Forms.Platform.Tizen/Shell/TV/TVShellRenderer.cs
Xamarin.Forms.Platform.Tizen/Shell/TV/TVShellSectionRenderer.cs
Xamarin.Forms.Platform.Tizen/Shell/TV/TVShellSectionStack.cs
Xamarin.Forms.Platform.Tizen/StaticRegistrar.cs
Xamarin.Forms.Platform.Tizen/ThemeManager.cs

This PR is to optimize Shell navigation UI for Tizen TV.
None
None
- Tizen
On TV, users navigate pages using remote controller that limits movement to up, down, left, right.  `Flyout` and `Tabs` are updated to be easily controlled by remote controller as below.
- `Flyout`
`Flyout` is displayed on the far left of the screen. It will be minimized while the user is browsing the `ShellContent` area. The user can open `Flyout` by moving the focus to the left pressing left button or changing the IsPresented property to true.
- Bottom tabs
Button tabs are not displayed on TV. Tab items will not be displayed on Flyout if `FlyoutDisplayOptions` value is `AsSingleItem`. (if the user want to represent tab items, it should be set `AsMultipleItems`)
- Top tabs
If `FlyoutItem` or `Tab` item contains on …

[Tizen] Optimize Shell Flyout for TV

---

src/Compatibility/Core/src/Android/HandlerToRendererShim.cs
src/Compatibility/Core/src/iOS/HandlerToRendererShim.cs
src/Core/src/Handlers/View/AbstractViewHandler.MaciOS.cs
src/Core/tests/DeviceTests/Handlers/Slider/SliderHandlerTests.cs

Fix issue with UISlider (and possibly other controls) misbehaving when calling SizeThatFits with infinite width.
If the control tries to claim infinite width or height, call SizeToFit and return the frame instead. (This is basically the same fix Forms has for SliderRenderer).
- (hopefully) fixes broken 7361 test in CG
None
- iOS
Automated device test

Fix infinite slider width issue

---

src/Core/src/Handlers/Button/ButtonHandler.Android.cs
src/Core/src/Handlers/Button/ButtonHandler.iOS.cs
src/Core/src/Handlers/Label/LabelHandler.Android.cs
src/Core/src/Handlers/Label/LabelHandler.iOS.cs
src/Core/src/Handlers/Slider/SliderHandler.Android.cs
src/Core/src/Handlers/Slider/SliderHandler.iOS.cs
src/Core/src/Handlers/Switch/SwitchHandler.Android.cs
src/Core/src/Handlers/Switch/SwitchHandler.iOS.cs
src/Core/src/Handlers/View/ViewHandler.cs

Removes the CheckParameters method from ViewHandler.
The null checks it does are unnecessary; the calls to the mapping methods all come from UpdatePropertyCore, and the only callers of it already check the IView for null. And both callers are only called from AbstractViewHandler, so the IViewHandler property is necessarily non-null.
If we ever decide in the future that null-checking these parameters is necessary, we can do so in UpdatePropertyCore rather than adding boilerplate code to every mapping.

Remove the CheckParameters boilerplate method from handlers

---

eng/pipelines/common/build-windows.yml

Make sure the tests are running after the rename.
This just "enables" the tests and do not fix it. This PR does that: https://github.com/xamarin/Xamarin.Forms/pull/13864

Fix test filenames in yaml after the rename

---

src/Controls/src/Core/HandlerImpl/VisualElement.Impl.cs
src/Controls/src/Core/Layout.cs
src/Controls/src/Core/Layout/Layout.cs
src/Controls/tests/Core.UnitTests/Layouts/LayoutCompatTests.cs
src/Core/src/Platform/iOS/MauiUIApplicationDelegate.cs

- No longer sets IsArrangeValid from Layout. If Layout is called by legacy code that shouldn't stop the Arrange call
- Override GetSizeRequest on Layout2 to forward calls to measure because even though GetSizeRequest has been obsolete forever it's still called from different parts of the code
- Added tests for different arrangement scenarios of mixing Layout2 layouts and Controls layouts 
- unit tests pass
- test different variations of layouts/controls in the sample appp

Additional changes to propagate measures and arranges between layouts

---

Xamarin.Forms.Platform.Tizen/Native/CollectionView/CollectionView.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/ViewHolder.cs

The focus on the item in the CollectionView interfered scrolling triggered by snap, this PR fixes this issue, 
When touch swipe was used on CollectionView, each item disable focus and recover focus when key input was used
- None
None
- Tizen
None
|Before|After|
|-|-|
|![focus-item-before](https://user-images.githubusercontent.com/1029155/109576032-58036500-7b36-11eb-9a3c-2aa92cfec352.gif)|![focus-item-after](https://user-images.githubusercontent.com/1029155/109576036-5df94600-7b36-11eb-98c2-c953abedf1a1.gif)|

[Tizen] Disable focus on item when touch swipe was used

---

Xamarin.Forms.Platform.GTK/Renderers/EntryRenderer.cs

Correctly wires `Entry` focus/unfocus events in GTK.
None
- Gtk
`Entry` now correctly triggers `IsFocused` `true` and `false` states and corresponding events.
Not applicable
1. Run `ControlGallery.GTK`.
2. Open `Entry Gallery`.
3. Set/unset focus on the tested element (`Entry`). Observe the now correct `IsFocused?` label updates.

[GTK] Fix Entry focus behavior

---

Xamarin.Forms.Platform.Tizen/Native/CollectionView/CollectionView.cs
Xamarin.Forms.Platform.Tizen/Renderers/ItemsViewRenderer.cs

This PR fixes
1. Add guard for invalid reference
- Prevent access to values before they are assigned
2. Fix CollectionView re-layouting issue
- Reset `LogicalChild` items so that re-layout can occur when `Element` is reused.
3. Fix adaptor for CollectionView
- Clean up adaptor when they change
- N/A
None
- Tizen
None
Not applicable

[Tizen] Fix CollectionView layout issue

---

Xamarin.Forms.Platform.Tizen/Shapes/RectangleRenderer.cs
Xamarin.Forms.Platform.Tizen/SkiaSharp/BoxViewRenderer.cs

This PR fixes
- `BoxView.CornerRadius` which has not been working properly.
- `Rectangle.RadiusX` and `Rectangle.RadiusY` which are not applied at first time.
- N/A
None
- Tizen
None
- Setting `Rectangle.RadiusX` and `Rectangle.RadiusY` values at app code.
- Setting `Rectangle.RadiusX` and `Rectangle.RadiusY` values dynamically.
- Testing `BoxView.CorenerRadius`.

[Tizen] Fix CornerRadius on BoxView and Rectangle

---

Xamarin.Forms.Core/PlatformConfiguration/TizenSpecific/ItemsViewScrolledExtendedEventArgs.cs
Xamarin.Forms.Core/PlatformConfiguration/TizenSpecific/ItemsViewScrolledExtenedEventArgs.cs
Xamarin.Forms.Platform.Tizen/Native/CollectionView/CollectionView.cs

Application want to know how long scroll area was remained, 
On Tizen platform, extend `ItemsViewScrolledEventArgs` and add CanvasSize property that indicate entire scrolling area
``` c#
var itemsView = new ItemsView();
itemsView.Scrolled += (s, e) => {
if (e is Xamarin.Forms.Core.PlatformConfiguration.TizenSpecific.ItemsViewScrolledExtendedEventArgs extend) {
if (extend.CanvasSize.Width - extend.HorizontalOffset - itemsView.Width < 10) {
// reached edge of last item
}
}
}
```
- fixes
Added:
- `class Xamarin.Forms.Core.PlatformConfiguration.TizenSpecific.ItemsViewScrolledExtendedEventArgs`
- `Size CanvasSize { get; set; }`
- Tizen
None
Not applicable

[Tizen] Extend ItemsViewScrolledEventArgs

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8282.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8282.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/CollectionView/StructuredItemsViewController.cs
Xamarin.Forms.Platform.iOS/Renderers/RefreshViewRenderer.cs

Fix incorrect refresh indicador position using RefreshView with CollectionView with Header on iOS.
- fixes #8282
None
- iOS
None
Launch Core Gallery and navigate to the issue 8282. Pull to Refresh. If the loading indicator appears above the CollectionView header, the test has passed.

[iOS] Fix incorrect refresh indicador position using RefreshView with CollectionView Header

---

Xamarin.Forms.Platform.Android/Cells/ViewCellRenderer.cs

When switching to a new renderer for the ViewCell, Dispose() is called on the Android View but not on the IVisualElementRenderer itself. 
This change calls Dispose on the IVisualElementRenderer, giving it an opportunity to handle full cleanup before it's released.
Possibly a memory leak or two.
None
- Android
None
Not applicable
None

Call Dispose on the VisualElementRenderer, rather than the Android View

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellTitleView.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs

Shell's Title View is incorrectly setting the width of the titleview to the width of the status bar so the content is overflowing. 
Regression here
https://github.com/xamarin/Xamarin.Forms/commit/0e708d0f5e2b1177d5414798075e31c84b7a1124#diff-2f88e95da9bc5f5ca84db7e94d89f0382947623bd11d414cc4cd02ce452fe558R427
- fixes #13949
- fixes #13795
- iOS
- UI Tests included

Don't set the width of the TitleView to the width of the status bar

---

.nuspec/Xamarin.Forms.nuspec
Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs
Xamarin.Forms.Core/ExperimentalFlags.cs
Xamarin.Forms.Platform.Android/AccessibilityDelegateAutomationId.cs
Xamarin.Forms.Platform.Android/AppCompat/PickerRenderer.cs
Xamarin.Forms.Platform.Android/EntryAccessibilityDelegate.cs
Xamarin.Forms.Platform.Android/FastRenderers/AutomationPropertiesProvider.cs
Xamarin.Forms.Platform.Android/Flags.cs
Xamarin.Forms.Platform.Android/PlatformRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/PageRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/PickerRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/SearchHandlerAppearanceTracker.cs
Xamarin.Forms.Platform.Android/Renderers/ShellSectionRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs
Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj

- added Xamarin.AndroidX.Navigation.UI so I can use the resource id for reading the back button as "Navigate up"
- added AccessibilityDelegateAutomationId so that if you set an AutomationId and the HelpText it'll read back the HelpText instead of the AutomationID
- When setting AutomationId on controls that aren't implicitly accessible we need to turn "ImportantForAccessibility" off so that TalkBack doesn't start reading it
- Disable extracting the defaults for hint and CD
- Remove the "Touch" settings on the PlatformRenderer
- Remove Clickable on the PageRenderer
- Fix Shell so that it doesn't read out the ViewPager if the page has no top tabs
Added:
- Accessibility_Experimental Flag so that you can toggle these changes on and off. 
- Android
- Turn this flag on and then click around in …

Fix up Android Accessibility behind a flag

---

.nuspec/Xamarin.Forms.AppLinks.nuspec
.nuspec/Xamarin.Forms.Visual.Material.nuspec
.nuspec/Xamarin.Forms.nuspec
DualScreen/DualScreen.Android/DualScreen.Android.csproj
EmbeddingTestBeds/Embedding.Droid/Directory.Build.targets
Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj
Xamarin.Forms.ControlGallery.Android/ContentDescriptionEffectRenderer.cs
Xamarin.Forms.ControlGallery.Android/Directory.Build.targets
Xamarin.Forms.ControlGallery.Android/Nuget.Build.targets
Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6878.cs
Xamarin.Forms.DualScreen/Xamarin.Forms.DualScreen.csproj
Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj
Xamarin.Forms.Platform.Android/AccessibilityDelegateAutomationId.cs
Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
Xamarin.Forms.Platform.Android/AppCompat/FormsFragmentPagerAdapter.cs
Xamarin.Forms.Platform.Android/EntryAccessibilityDelegate.cs
Xamarin.Forms.Platform.Android/Renderers/ShellContentFragment.cs
Xamarin.Forms.Platform.Android/Renderers/ShellFragmentPagerAdapter.cs
Xamarin.Forms.Platform.Android/Renderers/ShellRenderer.cs
Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj

Bump to latest Android X nugets
- fixes #13843
- Android

Bump Android X

---

Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13916.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
Xamarin.Forms.Core.UnitTests/ShellNavigatedArgsTests.cs
Xamarin.Forms.Core.UnitTests/ShellNavigatingTests.cs
Xamarin.Forms.Core.UnitTests/ShellTestBase.cs
Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
Xamarin.Forms.Core/Shell/Shell.cs
Xamarin.Forms.Core/Shell/ShellNavigationManager.cs
Xamarin.Forms.Core/Shell/ShellSection.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs

When you set the ViewControllers property on UINavigationController it doesn't take right away. If you retrieve the ViewControllers it will still contain the ViewController you just removed. This means if you do something like
```C#
ViewControllers = ViewControllers.Remove(vc1)
ViewControllers = ViewControllers.Remove(vc2)  // This will add back in vc1 
```
So when processing a navigation with removes/inserts we now save local copy of pending changes.
- fixes #13916
- iOS
- UI Tests included

Fix iOS so if you remove more than one page it's able to remove them successfully

---

azure-pipelines.yml

Fix nuget signing 
None
None
- iOS
- Android
- UWP
None
Not applicable

Ensure an older NuGet is installed

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4143.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4143.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core/Region.cs
Xamarin.Forms.Platform.Android/Extensions/TextViewExtensions.cs

There are a lot of problems that are connected to the incorrect calculation of the region of a Span, especially on Android. This causes diffferent effects like calling two commands with one tap due to overlapping regions or the reacting area for the tap is not where it is supposed to be.
This PR is an attempt to fix those problems currently for Android only. To completely fix #4143 some problems on iOS need to be fixed to and I am willing to fix them too, but I would like to discuss my Android approach here first with this PR.
- fixes #4143 (on Android)
- fixes #6992
- fixes #11650
- fixes #7655 (on Android)
- fixes #11657
- fixes #10520 (on Android) (not tested)
- fixes #4829 (on Android)
Added:
- static Region Region.FromRectangles(IEnumerable<Rectangle> rectangles)
Some regions now …

Fix 4143: improved Span region calculation

---

.nuspec/Xamarin.Forms.targets

The UWP/WinUI .wapproj also uses netfx, but actually does not build with Xamarin.Forms. So skip the check here as well.
- fixes #13957
None
- iOS
- Android
- UWP
None
Not applicable

Only check for netfx when not in a wapproj

---

Xamarin.Forms.Platform.MacOS/Renderers/SwitchRenderer.cs

Replaces NSButton with NSSwitch in macOS Switch renderer.
- Closes #14313
None
- macOS
Changes Switch Ui in macOS from CheckBox to an actual native Switch.
Before:
After:
Add a Switch element.
Click on it and verifying it's working.

[macOS] Update Switch renderer

---

Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs

Fix to Issue #12762
Java.Lang.IndexOutOfBoundsException: setSpan (nn ... nn) ends beyond length n-1

[Android] Fix to Issue Java.Lang.IndexOutOfBoundsException: setSpan

---

Xamarin.Forms.Platform.iOS.UnitTests/ItemsViewControllerLeakTest.cs
Xamarin.Forms.Platform.iOS.UnitTests/Xamarin.Forms.Platform.iOS.UnitTests.csproj
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs

When a CollectionView is removed from a layout or removed from view hierarchy (My use case is the following: when the user rotate the screen the layout changes. So, in my code, I recreate a new layout with a new CollectionView), the BindingContext is set to null, hence the ItemsSourceProperty is set to null and the ItemsSource property in the  Xamarin.Forms.Platform.iOS.ItemsViewController will be updated (through ItemsViewRenderer.OnElementPropertyChanged).
The problem is, if the IItemsViewSource is an Xamarin.Forms.Platform.iOS.ObservableItemsSource , the dispose method on the old ItemsSource value is not called and that dispose method is supposed to unsubscribe from the event delegate.
In the end, that object is still subscribed on the ObservableCollection in my ViewModel that has not …

fix memory leak (and some crashes) in ItemsViewController (iOS)

---

Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/ObservableGroupedSource.cs
Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs

If a CollectionView is not visible and an ObservableCollection notifies about changes the CollectionView doesn't react.
Also, after changing the CollectionView's visibility to visible and making any changes in the ObservableCollection we can get exceptions like this: https://github.com/xamarin/Xamarin.Forms/issues/14045#issuecomment-869204559
- fixes #14045 (not sure about this, but it looks similar)
None
- iOS
None
Not applicable
- Create a page with CollectionView and bind ItemsSource to ObservableCollection
- Set IsVisible to false for the CollectionView
- Add some items into the ObservableCollection
- Set IsVisible to true for CollectionView
- You will se, that the CollectionView doesn't show new items

[iOS] Fix: CollectionView was not updating when it was invisible

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12150.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/AppCompat/SwitchRenderer.cs
Xamarin.Forms.Platform.Android/Extensions/DrawableExtensions.cs

Fix shadow in Thumb setting a custom color on Android **Switch**.
- fixes #12150 
None
- Android
None
Launch Core Gallery and navigate to the issue 12150. If each Switch has a shadow on the Thumb, the test has passed.

[Android] Fix shadow in Thumb setting a custom color

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12300.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/ModalWrapper.cs

Removed some ancient workaround for a (presumed) bug in iOS. As far as I can tell this was implemented for [this test case](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44500.cs), which still works fine after removing this code. This is what is causing the weird behavior with the new modals today. I don't think there is much risk in removing this.
Original Bugzilla ticket [here](https://bugzilla.xamarin.com/44/44500/bug.html) and PR implementing this [here](https://github.com/xamarin/Xamarin.Forms/pull/951).
- fixes #12300
None
- iOS
Before there was a crash/unexpected behavior (closing underlaying modal as well as the top one) when there was a tap outside of the modal FormSheet or PageSheet and then closing …

[iOS] Fix crash/closing wrong modal with FormSheet and tap outside

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14426.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14426.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs

Fix Frame Background issue with transparent color.
- fixes #14426 
None
- iOS
None
Launch Core Gallery and navigate to the issue 14426. If the first Frame Background is transparent, the test has passed.

[iOS] Fix Frame Background issue with transparent color

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14428.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14428.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/Resources.xaml

Fix broken disabled Button visual state in UWP.
- fixes #14428 
None
- UWP
None
Not applicable
Launch Core Gallery on Windows and navigate to the issue 14428. If can distinguish between enabled and disabled buttons, the test has passed.

[UWP] Fix broken disabled Button visual state

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8218.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/Forms.cs

Update `Device.Idiom` when flipping tablet mode state on UWP.
- fixes #8218
None
- UWP
None
Not applicable
Launch Core Gallery and navigate to the issue 8218. Switch to the tablet mode and tap the button. If the Idiom value is Tablet, the test has passed.

[UWP] Update Device.Idiom when flipping tablet mode state

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13726.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13726.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs

Fix occasional wrong touch interception in SwipeView Content on Android.
- fixes #13726 
None
- Android
None
Not applicable
Launch Core Gallery and navigate to the issue 13726. Tap several times the Button. If the counter is always updated, the test has passed.

[Android] Fix occasional wrong touch interception in SwipeView Content 

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14523.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14523.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs

Fix Entry issue using TextColor and ClearButton in iOS < 13
- fixes #14523
- fixes #14479
- closes #14526
None
- iOS
None
Not applicable
Launch Core Gallery on iOS device or simulator and navigate to the issue 14523. Without exceptions, the test has passed.

[iOS] Fix Entry issue using TextColor and ClearButton in iOS < 13

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12590.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12590.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs

Fix issue using FormattedString and LineBreakMode on iOS.
- fixes #12590 
None
- iOS
None
Launch Core Gallery and navigate to the issue 12590. If the string is trimmed in in both cases,the test has passed.

[iOS] Fix issue using FormattedString and LineBreakMode

---

Xamarin.Forms.Controls/GalleryPages/GradientGalleries/GradientNavigationPageGallery.xaml
Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs

Align NavBar BarBackground behavior between Android and iOS.
Actually we have two properties to set a background, `BackgroundColor` and `Background`. Since both can be set, having set color and brush, the Brush must take precedence.
This PR include changes to align the behavior using `BarBackground` between Android and iOS.
- fixes #13491 
None
- iOS
- Android
None
Launch Core Gallery and navigate to the Brushes gallery. Select the "NavigationPage Brush Gallery". Having set color and brush in the NavBar, the Brush must take precedence.

[Android] Align NavBar BarBackground behavior between Android and iOS

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11795.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11795.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Material.Android/MaterialFrameRenderer.cs
Xamarin.Forms.Platform.Android/Extensions/BrushExtensions.cs
Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs
Xamarin.Forms.Platform.Android/GradientStrokeDrawable.cs
Xamarin.Forms.Platform.Android/Renderers/BoxRenderer.cs

Update gradients based on offset changes in Frame and BoxView on Android.
The problem was that both BoxView and Frame in Android used a **GradientDrawable** (it did not allow setting offsets except in API >= 29).
- fixes #11795 
- fixes #13493
None
- Android
None
_NOTE: It is difficult to see the changeS well with this gif quality, but to see it correctly the size is larger than allowed._
Launch Core Gallery and navigate to the issue 11795.

[Android] Update gradients based on offset changes in Frame and BoxView

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14544.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core/RadioButton.cs

The RadioButton control used on iOS was not listening for changes to the IsEnabled state to add the tap gesture recogniser needed to toggle the control's checked state.
UpdateIsEnabled was previously only called once when the control was first created, so if a RadioButton was created in an initially disabled state, there was nothing in place to add the tap gesture recogniser at a later point. This PR listens for changes to IsEnabled via OnPropertyChanged to call UpdateIsEnabled which will add/remove the tap gesture recogniser based on the enabled state.
This doesn't affect Android as that uses the built in radio button views rather than the Xamarin Forms implementation of one.
Fixes #14544 
None
- iOS
Before, adding a RadioButton control to a page with IsEnabled set to false meant that …

[iOS] Fix inability to check an initially disabled RadioButton after enabling it

---

Xamarin.Forms.Core/Shell/ShellNavigationManager.cs

Fix Exception "Can only be called on ui thread!" navigating using Shell.
- fixes #14366
None
None
Not applicable

[Core] Fix exception navigating using Shell

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14433.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14433.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems

This PR just validate the issue 14433 and that a gradient with transparencies is working on iOS.
- fixes #14433
None
- iOS
None
Not applicable
Launch Core Gallery and navigate to the issue 14433. If gradient renders correctly, the test has passed.

Validate issue 14433

---

Xamarin.Forms.Platform.iOS/Cells/SwitchCellRenderer.cs
Xamarin.Forms.Platform.iOS/Extensions/LabelExtensions.cs
Xamarin.Forms.Platform.iOS/Extensions/UIViewExtensions.cs
Xamarin.Forms.Platform.iOS/Renderers/ActivityIndicatorRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/SliderRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/StepperRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/SwitchRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs
Xamarin.Forms.Platform.iOS/VisualElementTracker.cs

Avoid using types from System.Drawing in the iOS platform code. This was already done in half of the files but some of them were missing. Due to some legacy incompatibilities the references to these types were incorrectly resolved to System.Drawing.Common where they don't really exist outside of legacy Xamarin platforms. This allows limited usage of the Xamarin.Forms on net6.0 platforms as a transition step to migrating to MAUI.
None
- iOS
None
Not applicable
Manually recompiled the platform assembly, verified that there are no more references to System.Drawing.Common. The assembly now loads on net6.0-ios without an error.

[iOS] Remove usage of System.Drawing types

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8129.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/VisualElementPackager.cs

Orders (Z ordering) the child soon after adding it to the view, reducing the complexity from N^2 to N
- fixes #8129 
None
- iOS
None
Not applicable
Followed the same repro that was reported in the bug.
Added 2000 elements to a Stack View
Test Cases -> G8129
Should not lock the UI considerably.

Ordering children while adding

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14286.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14286.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Shapes/ShapeRenderer.cs

If stroke is null avoid render shape stroke.
- fixes #14286 
None
- iOS
None
Not applicable

[iOS] If stroke is null avoid render shape stroke

---

Xamarin.Forms.Platform.MacOS/Renderers/RadioButtonRenderer.cs

Allows RadioButton in macOS to respond to the Activated event, thus propagating the necessary property changes.
- closes #13984
None
- macOS
Radio buttons within a group get exclusively activated, as intended.
Before:
After:
1. Add a group of RadioButton elements.
2. Click on each one of them, verifying only one is active at a time.

[macOS] Fix RadioButton activated behaviour

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Github5623.xaml.cs
Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs

The implementation  of CollectionView RemainingItemsThreshold for UWP
- fixes #5623
None
- UWP
None
Not applicable
The automated test created by @adrianknight89 now works on UWP.
Launch Control Gallery and navigate to issue G5623. Scroll items down until you reach item 99.

[UWP] Implement CollectionView RemainingItemsThreshold

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/FrameBackgroundIssue.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/FrameBackgroundIssue.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs

Fix Frame black background issue (with zero CornerRadius) on Android.
None
- Android
None
Not applicable
Launch Core Gallery and navigate to the issue called "Frame Background issue". If the Frame background is not black in all the conditions (using Background and BackgroundColor, different CornerRadius etc), the test has passed.

[Android] Fix Frame black background issue (with zero CornerRadius)

---

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselCodeGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/IndicatorCodeGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ItemSizeGalleries/DynamicItemSizeGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ItemSizeGalleries/VariableSizeTemplateGridGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ItemsSourceGenerator.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ObservableCodeCollectionViewGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ObservableCollectionResetGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ObservableMultiItemCollectionViewGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/PropagateCodeGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ScrollToCodeGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SnapPointsCodeGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SpacingGalleries/SpacingGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/TemplateCodeCollectionViewGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/TemplateCodeCollectionViewGridGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/TextCodeCollectionViewGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/TextCodeCollectionViewGridGallery.cs
Xamarin.Forms.Core/TemplatedItemsList.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/TemplatedCell.cs

Event handlers on the TemplatedCell are not being removed which results in the control to be left in memory which keeps the page where it is loaded also to stay behind in memory.
I added an unbind method on the TemplatedCell and unbind the event handlers in the ItemsViewController.
Also the TemplatedItemsList had a collectionchanged event which was not removed so I removed that as well.
If there is a better way to achieve this, please let me know and I will fix it in a better way.
Xamarin.Forms.Core/TemplatedItemsList.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Xamarin.Forms.Platform.iOS/CollectionView/TemplatedCell.cs
All the other files are eventhandler fixes in the Gallery code.
- fixes #9787
Added: Unbind() on TemplatedCell.cs to remove events
- iOS
- Android …

Fixed the memory leak in the collectionview and gallery

---

Xamarin.Forms.Platform.Android/CollectionView/SpacingItemDecoration.cs

CollectionView threw ArgumentOutOfRangeException when removing the item if there is only one item in only one group.
- #13562
None
- Android
None
Not applicable

[Android] Fix CollectionView threw ArgumentOutOfRangeException

---

Xamarin.Forms.ControlGallery.Android/Resources/values/styles.xml
Xamarin.Forms.Platform.Android/AppCompat/PickerRenderer.cs
Xamarin.Forms.Platform.Android/Resources/values/styles.xml

Fixes the weird visuals of the Picker and DatePicker on Android
- fixes #9033
None
- Android
TBD
TBD

Fix (Date)Picker Dark Theme Support

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14192.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14192.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs

Fix Exception using ListView inside CarouselView.
- fixes #14192
None
- iOS
None
Launch Core Gallery and navigate to the issue 14192. Swipe the CarouselView. Without exceptions, the test has passed.

[iOS] Fix NRE using ListView inside CarouselView

---

Xamarin.Forms.Core/IndicatorView.cs

Fix incorrect check in IndicatorView.
- fixes #14654 
None
None
Not applicable

[Core] Fix incorrect check in IndicatorView 

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13818.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13818.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems

Cannot reproduce the issues in 5.0.0 branch. Added sample to validate UWP CarouselView DivideByZeroException.
- fixes #13818
None
- UWP
None
Not applicable
Launch Core Gallery and navigate to the issue 13818. Without exceptions, the test has passed.

[UWP] Validate CarouselView DivideByZeroException

---

Xamarin.Forms.Platform.iOS/Forms.cs
Xamarin.Forms.Platform.iOS/Renderers/TimePickerRenderer.cs

This changes blocks showing the keyboard input when you tap the time picker on an iPad. While ideally we should allow the user to input a time with a numeric keyboard, this blocks the keyboard as a whole as an intermediate solution. Effectively this reverts the functionality to what it was before iOS 15 so nothing was lost nor added.
Note: only happens on iOS 15 and an iPad
- fixes #14673 
None
- iOS
Right now when you tap on a time in the TimePicker you will get a full keyboard in a too small popup making it look weird. On top of that, it's not even functional. 
With this change when you tap a time in the TimePicker, nothing happens as it was before.
**Before**
**After**
Go to the TimePicker in the gallery, pick any property, open the TimePicker wheels and tap on the selected time. …

Block keyboard for iOS 15 time picker

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14528.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems

The issue seems to be fixed by a recent PR merge. This PR only include a sample to validate it.
- fixes #14528 
- fixes #14325 
- 
None
- iOS
None
Not applicable

[iOS] Wrong SwipeView position if rapidly swipe multiple times

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8384.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8384.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs

RefreshAllowed is bound to ListView.RefreshCommand.CanExecute(). Often an implementation of RefreshCommand might update its CanExecute status after execution starts, e.g. to disable button when action starts. This caused ListViewRenderer to immediately disable the SwipeRefreshLayout, thereby cancelling the refresh/activity indicator on top of the list view.
The solution is to NOT disable it while refreshing, but waiting for the next chance when current refresh activity/command is done.
- fixes #8384
None
- Android
None
Not applicable
Launch Xamarin.Forms.ControlGallery.Android and navigate to issue 8384. Follow the steps there to test the issue.

ListView: avoid that disabling RefreshAllowed cancels refresh indicator on Android, fixes #8384

---

Xamarin.Forms.Platform.MacOS/Extensions/NSMenuExtensions.cs

Because of a faulty if statement in the code it was not possible to add just 1 modifier key to trigger a menu item on macOS, this is now fixed.
- fixes #1749
None
- macOS
Now 1 modifier key can be added to trigger a `MenuItem` instead of having to use multiple
Not applicable

Allow 1 modifier key to be added on macOS

---

Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs

- fixes #14804
- fixes #14788
- closes #14790
- Refactors #14526 
None
- iOS
No more crash on older iOS versions
Not applicable

Refactor Entry ClearButton observer lifecycle to prevent NRE on older iOS versions

---

Xamarin.Forms.Platform.Android/FastRenderers/VisualElementRenderer.cs

Avoid update native control enabled if is already disposed on Android.
- fixes #14738 
None
- Android
None
Not applicable

[Android] Avoid update native control enabled if is already disposed

---

Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs

The fix in #14828 caused, again, issues unfortunately. I have now taken the changes from Javier in #14790 which do seem to work better. Reverted the one commit and added Javiers fix.
- fixes #14788
None
- iOS
None
Not applicable

Fix hangs and NREs with Entry Observer

---

Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs

Wait for initial page to be loaded before push new pages inside the navigation stack.
- Fix #4729
- Fix #3528
- Fix #3923
- Android

[Android] Fix first navigation race condition with main page affectation

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13236.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13236.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/VisualElementTracker.cs

Fix crash animate two times the Frame scale on Android.
- fixes #13236
None
- Android
None
Not applicable
Launch Core Gallery and navigate to the issue 13236. Tap the button to animate the Frame Scale 2 times. Without exceptions, the test has passed.

[Android] Fix crash animate two times the Frame scale

---

Xamarin.Forms.Platform.iOS/Renderers/SearchHandlerAppearanceTracker.cs

Change property to set background color in iOS13 or newer.
- fixes #13774
- fixes #9887 
- iOS
Search handler will show the right background color.
Before:
After:

[iOS] Fix shell search handler background color for iOS 13 or newer

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13573.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13573.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/FormsTextBoxStyle.xaml

Maintain Editor BackgroundColor when focused. Removed unwanted behavior from `FormsTextBoxStyle`.
- fixes #13573 
None
- UWP
None
Launch Core Gallery and navigate to the issue 13573. Put the focus on the Editor, if the background color remains white, the test has passed.

[UWP] Maintain Editor BackgroundColor when focused 

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7671.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7671.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.WPF/Controls/FormsContentPage.cs
Xamarin.Forms.Platform.WPF/FormsContentLoader.cs
Xamarin.Forms.Platform.WPF/Renderers/PageRenderer.cs

`PageRenderer` renderes the first child instead of the `Content`.
Sorry, I destroyed the branch #7672.
- fixes #7671
None
- WPF
ControlTemplate gets rendered in wpf.
Before:
After:

[Bug] ContentPage.ControlTemplate gets not rendered in Wpf (#7671)

---

Xamarin.Forms.Platform.Android/EmbeddedFontLoader.cs

Check if a stored fontfile has a different size as the the embedded fontstream. If only the name is checked, changes in the embedded font are not taken into account.
- fixes #11843
None
- Android
None
Not applicable

Check font file length Android

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14805.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core/Shell/ShellSection.cs

Fix backwards navigation fails using Shell on iOS.
- fixes #14805 
- fixes #14830
None
None
Not applicable
Use the package from this PR with https://github.com/DiogoSemedo/xamarin or, launch Core Gallery and pass the UITest from Issue 4805.

[iOS] Fix backwards navigation fails using Shell

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14897.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14897.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs

Fix issue interacting with a SwipeView inside a ScrollView on a TabbedPage.  With IsSwipePagingEnabled="false" was re-enabling page swiping. This PR introduce changes to fix the issue.
- fixes #14897 
None
- Android
None
Not applicable
Launch Core Gallery and navigate to the issue 14897. Interact with the SwipeView available in Page 2 and then, try to swipe to move between tabs. If the page not swipe, the test has passed.

[Android] Fix issue interacting with a SwipeView inside a ScrollView on a TabbedPage

---

Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
Xamarin.Forms.Platform.iOS/Renderers/SafeShellTabBarAppearanceTracker.cs
Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs

This fixes issue #14773, for both iOS 14 and 15. A PR for this [already existed ](https://github.com/xamarin/Xamarin.Forms/pull/14789) but didn't account for iOS 14.
- fixes #14773
- closes #14789
None
- iOS
Fixes the layout of a TabbedPage when using Shell navigation.
Please use the repo gently provided by @federicobenedetti in #14773 and follow the steps there.

Fix tabs layout on iOS when using Shell navigation - #14773

---

Xamarin.Forms.Core/ExportFontAttribute.cs

Removed unused property in ExportFontAttribute.
- fixes #10183
None
None
Not applicable

[Housekeeping] Removed unused property in ExportFontAttribute

---

Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs

Avoid reset ListView adapter in TabbedPage if ListView is already disposed.
- fixes #14194 
None
- Android
None
Not applicable

[Android] Avoid reset ListView adapter in TabbedPage if is already disposed

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11829.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs

Fix issue on iOS Label using TextDecoration Strikethrough together with LineHeight.
- fixes #11829 
None
- iOS
None
Launch Core Gallery and navigate to the issue 11928. If text is underline, the test has passed.

[iOS]  TextDecoration Strikethrough not working on iOS together with LineHeight

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11954.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs

Instead of using the UILabel.Text property, we now only use the UILabel.AttributedText property. This makes sure that no formatting or markup is left behind. The label is drawn differently depending on which property you set. This change is the last reference to UILabel.Text.
We should test very well if this doesn't break anywhere!11!!
- fixes #11954 
None
- iOS
None
Not applicable
Go to issue 11954 and follow the instructions. Label should successfully enable/disable strikethrough

[iOS] Fix setting text decorations and text at the same time and respect changes

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14552.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14552.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/DragAndDropGestureHandler.cs

Fix crash dropping item using ListView on Android.
- fixes #14552
None
- Android
None
Not applicable
Launch Core Gallery using an Android device and navigate to the issue 14552. Drag and drop several times elements. Without exceptions, the test has passed

[Android] Fix crash dropping item using ListView (happens occasionally)

---

Xamarin.Forms.Core.UnitTests/BindableObjectUnitTests.cs
Xamarin.Forms.Xaml.UnitTests/AttachedProperties.xaml
Xamarin.Forms.Xaml.UnitTests/AttachedProperties.xaml.cs

I was attempting to recreate #9151, but instead I found it may not have been a bug. Since I had already written the test cases as part of the repro attempt, I thought they may be useful
- tests #9151
None
None
Not applicable

[core] Add tests for #9151

---

Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs

Fix CollectionView crash in iOS 9 (use non available API).
- fixes #14916 
None
- iOS
None
Not applicable
Launch any CollectionView sample from Core Gallery in iOS 9. Without exceptions, the test has passed.

[iOS] Fix CollectionView crash in iOS 9

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12887.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12887.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs

Fix issue using TextTransform and LineHeight properties at the same time  in iOS Label.
- fixes #12887 
None
- iOS
None
Not applicable
Launch Core Gallery and navigate to the issue 12887. If TextTransform property continue working using LineHeight property on Label, the test has passed.

[iOS] Fix issue using TextTransform and LineHeight properties at the same time

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10124.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs

Dismiss UISearchController when losing focus
- fixes #10124 
None
- iOS
When a query is confirmed in SearchHandler, the search handler will lose focus and will no longer display a dimmed view on top of the remaining page
Not applicable
1. Add a Shell SearchHandler
2. Tap the search bar to focus
3. Notice the main page is dimmed
4. Enter a search term
5. Execute the search
6. Notice the SearchHandler no longer displays a dimmed background and the main content is tappable

Dismiss UISearchController when losing focus

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14880.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14880.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/CollectionView/ItemContentView.cs
Xamarin.Forms.Platform.Android/CollectionView/ItemsViewAdapter.cs

Fix CollectionView item renderer disposal on Android (Memory Leak)
- fixes #14880 
None
- Android
None
Launch Control Gallery and navigate to the issue 14880. Place a breakpoint in the Dispose method of CheckBoxRendererBase.cs for the Android platform, then click the Back button. Does the breakpoint halt the program? If so, good. The Dispose method was called and the test passed.

[Android] Fix CollectionView item renderer disposal on Android (Memory Leak)

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8804.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8804.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs

Fix TabbedPage Disappearing events for swipe gestures on Android
- fixes #8804
None
- Android
None
Launch Core Gallery and navigate to the issue 8804. Swipe to Page 2. You should see an alert confirming that Page 1 is Disappearing. If you see the alert, the test has passed.

[Android] Fix TabbedPage Disappearing events for swipe gestures

---

Xamarin.Forms.Platform.Android/AppCompat/Platform.cs

This PR applies the fix from #12114 to the AppCompat versions for Android as well, hopefully fixing some sporadic exceptions.
- fixes #10159
- fixes #10031
None
- Android
None, hopefully no exceptions anymore!
Not applicable

[Android AppCompat] Add defensive code to prevent NRE in GetNativeSize

---

Xamarin.Forms.Platform.iOS/Renderers/ActivityIndicatorRenderer.cs

PR #11339 introduced ``UIActivityIndicatorViewDelegate`` to cope with changing Superview and start/stop UIActivityIndicatorView accordingly. However this conflicts with UIAppearance/theming of ``UIActivityIndicatorView``. It seems that on iOS 11 (and maybe other versions) sub-classes of ``UIActivityIndicatorView`` do not receive correct default theme/appearance leading to activity indicator showing all-black as reported in #14119.
This PR attempts to fix this by removing ``UIActivityIndicatorViewDelegate`` and instead handling ``LayoutSubviews()``/``Draw()``
through overriding ``ViewRenderer``. This way the native ``UIActivityIndicatorView`` is managed by ``ViewRenderer`` and thus
appearance works on older iOS versions as well.
- fixes #14119 
None
- iOS
None
**BEFORE (iOS 11)** …

Remove UIActivityIndicatorViewDelegate and instead override ViewRenderer to fix #14119

---

Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs

When the label is `TextType=Html` and the html is big, when you send the app to background change the theme, go back then the app and close the current page it has high changes to crash because the `Element` is `null`. So this fixes it by checking that before updating the color.
- I couldn't find an issue to link to this, should I create it?
None
- iOS
None
Not applicable
- Create a view that can be open and close from another part
- On that view set a Label with TextType HTML and bind a large HTML (In my particular case, I had one that was like 150 chars styled with different colors depending on the char type, i.e. number, special, alphabet, etc)
- Open the app and open that view
- Put the app on background
- Change the light/dark theme
- Open the app again and without leaving the HTML …

[iOS] Fix crash on iOS LabelRenderer UpdateTextColor

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13918.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13918.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/DatePickerRenderer.cs

Add consistency in date format between platforms.
- fixes #13918
None
- iOS
None
Not applicable
Launch Core Gallery and navigate to the sample 13918. If can see the century in the DatePicker, the test has passed.

[iOS] Add consistency in date format between platforms

---

Xamarin.Forms.Platform.UAP/Shell/ShellFlyoutItemRenderer.cs
Xamarin.Forms.Platform.UAP/Shell/ShellStyles.xaml

By overriding `NavigationViewItemOnLeftMinHeight `, any native application referencing Xamarin.Forms could be affected. Also, in the case of Shell, the `ShellNavigationView `style is used, which already set the `NavigationViewItemOnLeftMinHeight` property to zero.
- fixes #13457 
None
- UWP
None
Not applicable
Launch Core Gallery and open the Shell Store sample. Then, open the Flyout.

[Windows] Avoid override NavigationViewItemOnLeftMinHeight

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14397.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs
Xamarin.Forms.Platform.iOS/ViewRenderer.cs

Fix gradient background issue on Image on iOS.
- fixes #14397 
None
- iOS
None
Launch Core Gallery and navigate to the issue 14397. If can see the icon with the gradient background, the test has passed.

[iOS] Fix gradient background issue on Image

---

Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs

Allow empty image to hide back nav button.
- fixes #14331
None
- iOS
None
Not applicable

[iOS] Allow empty image to hide back nav button

---

Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs

Added a missing constructor in ListViewRenderer
Could not find it. But I saw it in the app crash logs:
ObjCRuntime.RuntimeException
Failed to marshal the Objective-C object 0x28382b600 (type: Xamarin_Forms_Platform_iOS_ListViewRenderer_ListViewDataSource). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Xamarin.Forms.Platform.iOS.ListViewRenderer+ListViewDataSource' does not have a constructor that takes one IntPtr argument).
Added:
- public ListViewRenderer(IntPtr handle)
- iOS
By having that missing constructor, we avoid that exception
I saw it in our crash logs.  
Don't know necessarily how to reproduce it.

added missing iOS constructor in ListViewRenderer

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14801.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14801.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.UAP/BrushExtensions.cs

Fix issue setting incorrectly the origin in RadialGradientBrush on UWP.
- fixes #14801 
None
- UWP
None
Launch Core Gallery and navigate to the issue 14801. If the RadialGradientBrush is rendered in all cases, the test passed.

[UWP] Fix issue setting incorrectly the origin in RadialGradientBrush

---

Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs
Xamarin.Forms.Platform.UAP/CollectionView/SelectableItemsViewRenderer.cs

Unsubscribe from `oldElement` on `TearDownOldElement` instead of current `Layout/ItemsView`that is already null.
- fixes 
- #14721
- #8928
None
- UWP
None
Not applicable
**Case 1: Nav back from CollectionView**
1. Take a `Memory Snapshot`
2. Navigate to a View that contains a `CollectionView`
3. Go back
4. Take another `Memory Snapshot` and compare it with the first one
5. Check that the `CollectionView`, BindingContext VM, Items VM are released
**Case 2: Change ItemsSource of CollectionView**
1. Take a `Memory Snapshot`
2. Add items to the `CollectionView`
3. Replace the `ItemsSource` with an empty collection
4. Take another `Memory Snapshot` and compare it with the first one
5. Check that the Items VM are released
Simple project available here: …

[UWP] CollectionView Memory Leak

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12603.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12603.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs

Perform scrolling inside the bounds of the ScrollView.
- fixes #12603
None
- iOS
If scrolling to an element, which is at the end of the list and setting ScrollToPosition to Start or Center the app now bahaves same as android.
Before:
After:

Fix iOS scrolling outside ScrollView bounds

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14657.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/Renderers/ContainerView.cs
Xamarin.Forms.Platform.Android/Renderers/ShellContentFragment.cs
Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs

Changes I am certail of that fixes (at least sometimes, read next paragraph) content page instances not garbage collected:
* `ShellToolbarTracker` - calling `RemoveDrawerListener(...)` in dispose method
* after adding this the simplest content page with no content were garbage collected
* `ShellContentFragment` - explicitly setting page TitleView to `null`
* this change allows pages to be collected when a page has set custom content via `Shell.TitleView` (you need to add at least some layout with content, e.g. `StackLayout` with `Label`)
* This is my first time browsing throught Xamarin.Forms codebase and I have no idea if this is the best place to set title to null, I would appreciate other devs feedback but it certainly fixed my issue
Those changes allow _simple_ pages to be collected …

[Android] Fix content pages not Garbage collected

---

Xamarin.Forms.Platform.iOS/Shapes/ShapeRenderer.cs

As of Xcode 13.2 something seems changed in the Apple iOS APIs that causes a NRE on our side. Not sure if this fix is perfect. I wonder if something in `CGAffineTransform` is changed that doesn't accept invalid values anymore, where it did before, or maybe something in the iOS APIs changed in the measurements which causes invalid values to come in in the first place.
Any views on that are appreciated :)
- fixes #14986
None
- iOS
No more crash when using a `Line`
Not applicable
Go to the Shapes Gallery and open the Line Gallery. If it doesn't crash and you can see lines, then it is all OK!

Fix NRE when using Line on iOS with Xcode 13.2

---

Xamarin.Forms.Core.UnitTests/StyleSheets/StyleParserTests.cs
Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
Xamarin.Forms.Core/StyleSheets/Style.cs
Xamarin.Forms.Core/StyleSheets/TextReaderExtensions.cs

[ `main` may be the more appropriate branch, but it's a relatively small change. ]
The current CSS parser doesn't support declarations like `label {font-size: 18; background-color: red}` where the final semicolon is omitted. These are, however, valid CSS.
This fixes that behavior and introduces a few unit tests to check for such edge cases.
- fixes #2588
Run all tests in the `Xamarin.Forms.Core.UnitTests.StyleSheets` and `Xamarin.Forms.StyleSheets.UnitTests` namespaces.

CSS: Support omitting semicolon from last property

---

Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs

The current implementation for iOS13+ overrides the settings that users might set through `UINavigationBar.Appearance`. This change should take those into account.
- fixes #13291
None
- iOS
TBD
Not applicable
TBD

Prefer UINavigationBar.Appearance over Forms settings

---

Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs

In https://github.com/xamarin/Xamarin.Forms/issues/11301 clearing the pages was invoking this code https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs#L540 also in the removed page. Trying to update and get the item, the index does not fit with the collection count.
Added some validations to svoid update the items title or icon if, the index is out of range.
- fixes #11301
<!-- List all API changes here (or just put None), example:
Added:
None
- Android
None
Not applicable
Use the NuGet package from this PR in the sample from https://github.com/xamarin/Xamarin.Forms/issues/11301#issue-650557548. If doing logout everything continue working without exceptions, the test has passed.

[Android] Fix crash trying to update a removed tab menu item

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Github7996.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core.UnitTests/BindingExpressionTests.cs
Xamarin.Forms.Core.UnitTests/BindingUnitTests.cs
Xamarin.Forms.Core.UnitTests/TypedBindingUnitTests.cs
Xamarin.Forms.Core/BindingExpression.cs

The input for floating numbers had some errors in different cultures.
When using german for example, the decimal seperator is a ',' and not a dot.
You can also use Nullable Types now. Before the Decimal Seperator would be cut off for Nullables.
- fixes #7996 
None
The user of an app can now use the correct decimal sperator for his language.
Not applicable
I have tested this on android.
I added a UI Test to the Gallery (G7996).
Unfortunately i cant test this on other platforms right now.
I also added a new Unit Test to prove the behaviour.

Fix input for decimal/float/double and nullable

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14472.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14472.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Core/OrientationStateTrigger.cs

Fix wrong orientation issue using `OrientationStateTrigger`.
- fixes #14472 
- fixes #9651
None
None
Not applicable
Launch Core Gallery and navigate to the issue 14472. If can see a Green Background Color in PortraitDown orientation, the test has passed.

[Core] Fix wrong orientation issue using OrientationStateTrigger

---

Xamarin.Forms.Platform.GTK/Controls/RadioButton.cs
Xamarin.Forms.Platform.GTK/Properties/AssemblyInfo.cs
Xamarin.Forms.Platform.GTK/Renderers/RadioButtonRenderer.cs
Xamarin.Forms.Platform.GTK/Xamarin.Forms.Platform.GTK.csproj

Adds missing implementation of RadioButton for Gtk.
None
Added:
- class Xamarin.Forms.Platform.GTK.Controls.RadioButton
- Xamarin.Forms.Platform.GTK.Renderers.RadioButtonRenderer
- Gtk
RadioButtons under Gtk get rendered, shown, and behave consistently with other platforms.
Not applicable
1. Start ControlGallery.Gtk.
2. Open the RadioButtonGroup page.
3. Verify RadioButtons show up and grouping behavior works.

[Gtk] Implement RadioButton

---

Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs
Xamarin.Forms.ControlGallery.iOS/CustomRenderers/UIStatusBarStyleRenderer.cs
Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
Xamarin.Forms.Controls/App.cs
Xamarin.Forms.Controls/CoreGallery.cs
Xamarin.Forms.Platform.iOS/Renderers/TabletFlyoutPageRenderer.cs

Since we were wrapping the renderers of FlyoutPage and DetailPage on a internal ViewController, the users couldn't provide overrides for `PreferredStatusBarStyle()`.
To fix this we override `ChildViewControllerForStatusBarStyle` on our internal `ChildViewController` and point to page's VC.
- fixes #13053 
None
- iOS
Should be able to provide UIStatusBar color
Before:
After:
Start the ControlGallery and check if the UIStatus bar shows white content on the left, and black content on the right.

[iOS] Allow VC renderers of FlyoutPage to specify UIStatusBarStyle

---

Xamarin.Forms.Platform.GTK/Controls/Shapes/EllipseView.cs
Xamarin.Forms.Platform.GTK/Controls/Shapes/PathView.cs
Xamarin.Forms.Platform.GTK/Controls/Shapes/PolygonView.cs
Xamarin.Forms.Platform.GTK/Controls/Shapes/PolylineView.cs
Xamarin.Forms.Platform.GTK/Controls/Shapes/RectangleView.cs
Xamarin.Forms.Platform.GTK/Controls/Shapes/ShapeView.cs
Xamarin.Forms.Platform.GTK/Properties/AssemblyInfo.cs
Xamarin.Forms.Platform.GTK/Renderers/Shapes/EllipseRenderer.cs
Xamarin.Forms.Platform.GTK/Renderers/Shapes/PathRenderer.cs
Xamarin.Forms.Platform.GTK/Renderers/Shapes/PolygonRenderer.cs
Xamarin.Forms.Platform.GTK/Renderers/Shapes/PolylineRenderer.cs
Xamarin.Forms.Platform.GTK/Renderers/Shapes/RectangleRenderer.cs
Xamarin.Forms.Platform.GTK/Renderers/Shapes/ShapeRenderer.cs
Xamarin.Forms.Platform.GTK/Xamarin.Forms.Platform.GTK.csproj

Supported Shapes:
- Ellipse
- Rectangle
- Path
Supported Path Segments:
- Arc
- Line
Supported Brushes:
- SolidColorBrush
(Strokes implementation will come in a 2nd PR.)
Co-authored-by: Afshin Arani &lt;afshinarani79@gmail.com&gt;
NOTE: even if this could be considered an enhancement, any code that used Shapes with XamarinForms5.0 (or older) running on Gtk would have crashed or contained bugs (obviously), so this is essentially a bugfix. So: None, no API changes.
- GTK
Manual with our own app.

[GTK] Some Shapes API support

---

build.cake

Hello! 
Running the `\build.ps1 -Target provision` on the recent branch, I've noticed that the script cannot pass through all the steps:
```
Installing: https://download.microsoft.com/download/A/1/D/A1D07600-6915-4CB8-A931-9A980EF47BB7/NDP47-DevPack-KB3186612-ENU.exe
An error occurred when executing task 'provision-netsdk-local'.
Error: One or more errors occurred. (One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).))
Response status code does not indicate success: 404 (Not Found).
```
That happened due to line 107 in the file `build.cake`:
```
string[] netFrameworkSdksLocalInstall = new string[]
{
"https://go.microsoft.com/fwlink/?linkid=2099470", //NET461 SDK
"https://go.microsoft.com/fwlink/?linkid=874338", //NET472 SDK
106: …
```

removed a broken direct link to net47 dev pack

---

Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs

Missing null check in #14797 causes a NRE in certain scenarios
- fixes #15104
None
- iOS
None
Not applicable

Fix NRE in iOS ImageRenderer

---

Xamarin.Forms.Platform.GTK/Controls/Shapes/PathView.cs

GeometryHelper.FlattenArc function returns a NaN point when
flattening very small arcs. Cairo doesn't ignore NaN points
and would draw an out-of-place line instead, which we need
to tweak to prevent weird renderings.
Co-authored-by: Afshin Arani <afshin@arani.dev>
- fixes https://github.com/xamarin/Xamarin.Forms/issues/15130
None
- Gtk
None
Not applicable

GTK: fix small arc rendering problem

---

Xamarin.Forms.Platform.iOS.UnitTests/TransformationTests.cs
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Xamarin.Forms.Platform.iOS/VisualElementTracker.cs

Fix using new Xamarin.IOS apis
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable

[iOS] Fix warnings on obsolete api

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GitHub15049.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/CollectionView/AdapterNotifier.cs

Reverts part of #10624 to overcome GREF issue
- fixes #15049
None
- Android

Fixes 15049

---

Xamarin.Forms.Platform.iOS/Extensions/ColorExtensions.cs
Xamarin.Forms.Platform.iOS/Extensions/LabelExtensions.cs
Xamarin.Forms.Platform.iOS/Forms.cs

Fixes the build for now, we should remove the actual obsoletes probably at some point

Add suppressions for Xam.iOS obsoletes

---

Xamarin.Forms.Platform.GTK/Renderers/NavigationPageRenderer.cs

Queue a redraw properly when coming back from navigation-bar event.
- fixes https://github.com/xamarin/Xamarin.Forms/issues/15170
None
- Gtk
See the testcase in https://github.com/xamarin/Xamarin.Forms/issues/15170

Fix gtk shapes rendering nav glitch

---

Xamarin.Forms.Core.UnitTests/BindingExpressionTests.cs
Xamarin.Forms.Core.UnitTests/BindingUnitTests.cs
Xamarin.Forms.Core.UnitTests/TypedBindingUnitTests.cs
Xamarin.Forms.Core/BindingExpression.cs

I ported #11815 to [.NET MAUI](https://github.com/dotnet/maui/pull/5005), but in the review it was revealed that `CurrentCulture` is actually the right setting to look at here. So fixing that back to Forms as well and making the test names a bit more clear.

Binding convert looks at right culture setting

---

Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
Xamarin.Forms.Platform.Android/FastRenderers/LabelAppCompatRenderer.cs
Xamarin.Forms.Platform.Android/Flags.cs
Xamarin.Forms.Platform.Android/Renderers/EditorAppCompatRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/EntryAppCompatRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/FormsAppCompatEditText.cs
Xamarin.Forms.Platform.Android/Renderers/FormsAppCompatTextView.cs
Xamarin.Forms.Platform.Android/Renderers/FormsTextView.cs

Adds 3 copies of renderers for `Entry`, `Editor` and `Label` which now inherit from the AppCompat version of the Android counterpart as opposed to the non-AppCompat version that it is currently.
To ensure a safety switch these are copies of the existing renderers, the new renderers are the default, but with a flag you can revert back to the old renderers and behavior.
- fixes #15245
Added:
* `public class EntryAppCompatRenderer : EntryRendererBase<FormsAppCompatEditText>`
* `public class EditorAppCompatRenderer : EditorRendererBase<FormsAppCompatEditText>`
* `public class LabelAppCompatRenderer : FormsAppCompatTextView`
* `public class FormsAppCompatTextView : AppCompatTextView`
* `public class FormsAppCompatEditText : FormsAppCompatEditTextBase`
* `public class FormsAppCompatEditTextBase …

Introduce Android AppCompat renderers for Entry, Editor and Label

---

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselViewGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/ReplaceSourceGallery.xaml
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/ReplaceSourceGallery.xaml.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CollectionViewGallery.cs
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/NestedGalleries/CarouselInCollectionViewGallery.xaml
Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/NestedGalleries/CarouselInCollectionViewGallery.xaml.cs

* Adds gallery page for changing the itemssource of a `CarouselView` for #15231 (CarsouelView Gallery -> CarsouselView Replace Source)
* Adds gallery page for `CarouselView` in `CollectionView` for #15082` (CollectionView Gallery -> CarouselView in CollectionView) 
Now I have these test cases, I'm going to have a look at fixing, but I figured the test cases were still useful on their own.
Incidentally, the existing CarouselView code galleries show weird behavior on Android if you update the number of items.

Add gallery pages for some carouselview bugs

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue15287.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue15287.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs

This commit https://github.com/xamarin/Xamarin.Forms/blob/aeec18668f72a34ee7990b822956eb845cae99d3/Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs#L20 caused the iOS `CarouselView` native items to have the wrong size under some specific circumstances.
Stepping through , there was an incorrect call to `ItemsViewLayout.ConstrainTo(CollectionView.Bounds.Size);`. This changes it to use `ConstrainToItemsView()` instead (which uses the `ItemsView` size if it has been calculated and `CollectionView.Bounds.Size` otherwise, which seems to match the existing comment).
- fixes #15287 
None
iOS
None
Not applicable
Issue 15287 has been added to the app. Scroll up and down the collection view and see that none of the items are incorrectly sized.

[iOS] Change how ItemsViewController.CheckEmptySource checks for item size

---

Environment.Build.props

Disable installing "missing" Android SDKs for now to work around https://github.com/xamarin/android-sdk-installer/pull/614

Disable installing "missing" Android SDKs for CI

---

Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs

Add method UpdateHideNavigationBarSeparator after UpdateBarBackground on HandlePropertyChanged (Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs)
- fixes https://github.com/xamarin/Xamarin.Forms/issues/15329
None
- iOS
NavigationBarSeparator is Hidden when the BarBackgroundColor is changed
Before:
After:

Fix 15329 NavigationBarSeparator is visible after changing BarBackgroundColor when SetHideNavigationBarSeparator(true)

---

Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
Xamarin.Forms.Platform.iOS/Forms.cs

Porting (potential) fix from .NET MAUI to Forms. Also see: https://github.com/dotnet/maui/pull/6878
- fixes #15230
None
- iOS
None
Not applicable

Comment out measure all strategy on iOS 15 for grouping

---

Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs

Android CarouselViewRenderer should call base UpdateItemsSource and UpdateAdapter to reset scroll listener and observers
- fixes #15265 
None
- Android
None
Not applicable

Android CarouselViewRenderer should call base UpdateItemsSource and UpdateAdapter

---

Xamarin.Forms.Platform.UAP/Shell/ShellItemRenderer.cs

Fixes the tab bar icon set with embedded font on UWP
fixes #13688
fixes #14959 
- UWP
Icon is correctly displayed

[UWP] Fix shell tab font icon set with Embedded Font

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue15368.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs

Update OnEnded method
- fixes https://github.com/xamarin/Xamarin.Forms/issues/15368
None
- iOS
None

Fix 15368 Editor's TextChanged event is fired on Unfocus even when no text changed

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14657.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
Xamarin.Forms.Core/Shell/ShellSection.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs

When navigating back via the back button on shell the state of shell isn't being properly updated
This broke with the following PR
https://github.com/xamarin/Xamarin.Forms/pull/15053

Propagate the BackButton on iOS

---

Xamarin.Forms.Platform.iOS/CollectionView/ItemComparer.cs

When an different types are used via Bindings on a Collectionview the ItemComparer can crash the application.
When valueA passed to ItemComparer is and Enum and valueB is an object, the Enum.CompareTo will throw an exception.
Sample:
```
var a=FooEnum.One;
var b = new CrazyObject();
ItemComparer.AreEquals(a,b);
// -> ArgumentException: Object must be the same type as the enum. The type passed in was 'CrazyObject'; the enum type was 'FooEnum'.
```
None
- iOS
- 
None (no Exception in Renderer, thus no crash)
Not applicable
See Code sample above, code can be unittested.

Comparing Enum to Object crashes ItemComparer

---

Xamarin.Forms.Core/BindingExpression.cs

Added null handling to BindingExpression.TryConvert to mitigate an `NullReferenceException` which thereafter leads to app crash in production.
- fixes #15381
None
None
Not applicable
None

gracefully handle null values in BindingExpression.TryConvert

---

Xamarin.Forms.Platform.Android/AppCompat/FlyoutPageContainer.cs
Xamarin.Forms.Platform.Android/AppCompat/FlyoutPageRenderer.cs
Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Xamarin.Forms.Platform.Android/Renderers/ViewGroupExtensions.cs
build/steps/build-osx.yml

The original RTL PR didn't test on an Android tablet so AFAICT this has never really worked on an Android Tablet. 
The split mode on Android is a bit of a hack of the drawer layout. It forces the flyout to be visible and then we calculate the layout bounds ourselves. 
Side note :-) This all works fine in MAUI because on MAUI when using split mode the flyout and details are just moved to a linear layout. This means the platform is able to apply RTL without us having to do anything magical. 
- fixes #15359

Account for RTL on Android Tablet

---

Xamarin.Forms.Platform.Android/FastRenderers/AutomationPropertiesProvider.cs

Seems like some check was forgotten in regard to accessibility and the Editor which caused the placeholder not to show up anymore on Android.
- fixes #15435
None
- Android
None
Not applicable

Fix Editor.Placeholder to show again on Android

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue15305.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue15305.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/CellAdapter.cs
Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs

- fix the wrong item indices and the wrong total count of items in a ListView on Android
- for this the header and footer are removed when they are empty
- partially taken from #10151
- fixes #4090
- fixes #15305
None
- Android
The TalkBack screen reader now has the correct item indices and item count for the elements in a ListView.
Not applicable
- Android: description can be seen in Issue15305.cs
- iOS: not able to test this
- UWP: not able to test this

[Android] fix item indices and item count in a ListView

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13790.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13790.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs

Fix crash in SwipeView collapsing ListView groups on Android.
- fixes #13790
None
- Android
None
Launch Core Gallery and navigate to the issue 13790. Collapse a group. Without exceptions, the test has passed.

[Android] Fix crash in SwipeView collapsing ListView groups

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue15100.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue15100.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.Android/Renderers/ScrollViewContainer.cs
Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs

The calculations of the needed size of a ScollView on Android do now always consider all Margins of its child view and all Paddings of the ScrollView.
- fixes #15100 
None
- Android
Now a ScrollView takes up all the space needed by the size of its child view, the Margins of the child view and the Paddings of the ScrollView.
So it is possible to see the complete child view and the complete Padding/Margin surrounding the child view.
- Android: description can be seen in Issue15100.cs
- iOS: not able to test this
- UWP: bug is not present

fix the calculations of the needed size of a ScollView on Android (Issue 15100)

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11514.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11514.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems

The crash does not happen in 5.0.0 branch and also everything works as expected. For that reason, this PR only includes the sample.
- fixes #11514 
None
- iOS
None
Launch Core Gallery and navigate to the issue 11514. If the image is clipped, the test has passed.

[iOS] Clip using a GeometryGroup

---

Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs

Ports a fix for a very similar issue with `Entry` also to `Editor` to overcome this bug.
- fixes #15465
None
- Android
None
Not applicable

Fix IndexOutOfBoundsException: setSpan crash in Editor on Android

---

Xamarin.Forms.Platform.GTK/Renderers/ImageRenderer.cs

This fix avoids threading problems caused by calling Pixbuf ctor from outside of the MainThread.
This fix avoids threading problems caused by calling Pixbuf ctor from outside of the MainThread by invoking it on the MainThread using Device.InvokeOnMainThreadAsync function.
None
- GTK
None
Not applicable

GTK: Call Pixbuf ctor on MainThread for LoadImageAsync functions

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14444.xaml
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14444.xaml.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs

Avoid setting default color value in the iOS SwipeView background under some conditions.
- fixes #14444 
None
- iOS
None
Launch Core Gallery and navigate to the issue 14444. If the SwipeView background is transparent, the test has passed.

[iOS] Fix SwipeView Background behavior

---

azure-pipelines.yml
build/steps/build-android.yml
build/steps/build-osx.yml
build/steps/build-windows.yml
eng/xf-release.yml

Invokes Provisionator with AUTH_TOKEN_GITHUB_AUTH set to support bootstrapping/downloading through dl.internalx.com
None
None
None
Not applicable
In CI

Use AUTH_TOKEN_GITHUB_COM when invoking Provisionator

---

Xamarin.Forms.Platform.Android/Platform.cs

Seems some non-appcompat Android APIs have become obsolete. People should be on the AppCompat variant anyway, so I think we can safely ignore these.

Ignore Non-AppCompat Android Obsolete APIs

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue15542.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Forms.cs
Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs

Fix wrong size TitleView issue on iOS 16.
- fixes #15542 
None
- iOS
None
Not applicable
Launch the Xamarin.Forms Core Gallery App and navigate to the issue 15542. If the Red TitleView is rendering, the test has passed.

[iOS 16] Fix wrong size TitleView issue on iOS 16

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue15565.cs
Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs

Fix issue using ToolbarItems with TitleView on iOS 16.
NOTE: The fix is the same applied in https://github.com/xamarin/Xamarin.Forms/pull/15600 This PR include specific UI Tests to validate the TitleView usage with ToolbarItems on iOS 16.
- fixes #15565
None
- iOS
None
Not applicable
Launch the Xamarin.Forms Core Gallery App and navigate to the issue 15565. If the Red TitleView is rendering with the ToolbarItems, the test has passed.

[iOS] Fix issue using ToolbarItems with TitleView on iOS 16

---

Xamarin.Forms.Platform.Android/Platform.cs
Xamarin.Forms.Platform.iOS/Extensions/UIViewExtensions.cs
build/steps/build-android.yml
build/steps/build-osx.yml
build/steps/build-windows.yml

As of iOS 16 (or probably more likely; Xcode 14) a `NaN` value would occur when measuring this label size. To account for that, detect `NaN` values and set it to an unknown value so it will recalculate.
- fixes #15535
- fixes #15579
None
- iOS
None
Not applicable

Fix crash iOS Label measure for RTL languages

---

Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs

In the `ItemsViewController` multiple methods (i.e. `UICollectionViewController.GetCell()` which calls `ItemsViewController.UpdateTemplatedCell()` and `UICollectionViewController.GetItemsCount()` and `UICollectionViewController.NumberOfSections()` which both call `ItemsViewController.CheckForEmptySource()`) can be called by iOS after `ItemsViewController.Dispose()` has been called and `_measurementCells` has been set to `null`. There are already null checks for `_measurementCells` in certain places, but not all. This should cover the rest of the cases where it can be null.
- fixes #15637 
None
- iOS
None
Not applicable
I was able to reproduce the crash in the attached sample from #15637. I then created a local nuget package from the 5.0.0 branch and confirmed the cause. After making these …

`ItemsViewController` null checks

---

Xamarin.Forms.Material.iOS/MaterialButtonRenderer.cs
Xamarin.Forms.Material.iOS/MaterialFrameRenderer.cs
Xamarin.Forms.Material.iOS/MaterialTextManager.cs

[Material] Fixed Renderer's LayoutSubviews may cause NullReferenceException on iOS.
```
var bgBrush = Element.Background;
```
to
```
var bgBrush = Element?.Background;
```
- fixes #15669
None
- iOS
None
Not applicable

[Material] Fixed Renderer's LayoutSubviews may cause NRE.

---

Xamarin.Forms.Core/Shell/BaseShellItem.cs
Xamarin.Forms.Platform.Android/Renderers/BottomNavigationViewUtils.cs
Xamarin.Forms.Platform.Android/Renderers/ShellItemRenderer.cs

In 3 places which had to do with Shell and/or TabbedPage we had a reference to sans-serif-medium as a string. This was causing exceptions, from what I can tell, on all Android devices and throwing underwater exceptions that the font could not be loaded.
I've changed these references to the TypeFace.SansSerif which is built-in and assume that it resolves to the same. From a visual test I don't see any differences.
Thinking about it, there will probably be no differences, since the font couldn't be loaded earlier, it would not have shown as it was intended in the first place.
Unfortunately, I couldn't really find any definitive source on if this was removed on Android at some point or what the cause is that we are seeing this now.
- fixes #13601
None
- Android
Should be none! If there are …

Replace Shell sans-serif-medium magic string on Android

---

Xamarin.Forms.Core.UnitTests/BindingUnitTests.cs
Xamarin.Forms.Core/BindableObject.cs
Xamarin.Forms.Core/BindingExpression.cs
Xamarin.Forms.Core/Brush.cs
Xamarin.Forms.Core/SolidColorBrush.cs
Xamarin.Forms.Core/TypedBinding.cs

Port **CollectionView** performance fixes from .NET MAUI https://github.com/dotnet/maui/pull/13327 from Peppers.
The types of leaks this fixes:
* Bindings to application-lifetime, singleton `ViewModel`s
* Scrolling `CollectionView`, `ListView`, etc. with data-bindings.
* Styles that were used on a `View` or `Page` that is now removed from the screen via navigation, de-parenting, etc.
None

Port CollectionView performance fixes from .NET MAUI

---

Xamarin.Forms.Core/Shell/BaseShellItem.cs
Xamarin.Forms.Platform.Android/Renderers/BottomNavigationViewUtils.cs
Xamarin.Forms.Platform.Android/Renderers/ShellItemRenderer.cs

Reverts xamarin/Xamarin.Forms#15698 
This wasn't the correct fix!

Revert "Replace Shell sans-serif-medium magic string on Android"

---

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2482.cs
Xamarin.Forms.Platform.UAP/Dispatcher.cs
Xamarin.Forms.Platform.UAP/DispatcherProvider.cs

This PR makes sure the UWP dispatcher is using the internal core dispatcher for thread access checks instead of the global device dispatcher which does not support multiple windows.
- fixes #15652
- related to #11880
None
- UWP
None
Not applicable

UWP Dispatcher should use the internal core dispatcher for state

---

Xamarin.Forms.Platform.Android/Platform.cs
Xamarin.Forms.Platform.Android/VisualElementRenderer.cs

Added definition for (IntPtr, JniHandleOwnership) to Android DefaultRenderer. Delegates to its base call in Android.Views.ViewGroup.
- fixes #15729
Added:
- Constructor Xamarin.Forms.Platform.Android.DefaultRenderer(IntPtr handle, JniHandleOwnership transfer)
Changed:
- none
Removed:
- none
- Android
None

fixed NotSupportedException in Xamarin.Forms.Platform.Android.Platform.DefaultRenderer
