- Xamarin.Forms.Core.UnitTests/ImageTests.cs
- Xamarin.Forms.Core/IImageController.cs
- Xamarin.Forms.Core/Image.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.Android/Renderers/ImageRenderer.cs
- Xamarin.Forms.Platform.WP8/ImageRenderer.cs
- Xamarin.Forms.Platform.WinRT/ImageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/IImageController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Image.xml
Add interface IImageController and update renderers to use it
> Prep Image for removal of InternalsVisibleTo

- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
Allow Xamarin.Forms.CarouselView to access internal api from Xamarin.Forms
No need for tests
> Set InternalsVisibleTo for CarouselView

- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.ControlGallery.Android/Properties/AndroidManifest.xml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40333.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/App.cs
- Xamarin.Forms.Platform.Android/AppCompat/FragmentContainer.cs
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailContainer.cs
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/MasterDetailContainer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
If an AppCompat MasterDetailPage hosts NavigationPages or TabbedPages in either the Master or Detail sections, those pages are now wrapped in their own Fragment (and use that Fragment's ChildFragmentManager) to isolate their Fragment management operations and avoid recursive entry into the `executePendingTransactions()` method.
Also fixed a disposal bug in the custom MDP renderer in Control Gallery.
- [40333 – [Android] IllegalStateException: Recursive entry to executePendingTransactions](https://bugzilla.xamarin.com/show_bug.cgi?id=40333)
- [40639 – Xamarin.Forms 2.1.0.6529 (Android only). Unhandled Exception: Java.Lang.IllegalStateException: Recursive entry to executePendingTransactions when switching MainPage or children of TabbedPage in …
> [Android] Isolate fragment management for children of MasterDetailPage 

- Xamarin.Forms.UITest.TestCloud/Uploader.cs
Adds an `exclude` option to the uploader so we can exclude tests by category (e.g., `ManualReview`)
Adds an `include` option to replace `category` to fit better with test-cloud.exe parameters
> Add option to exclude category to Test Cloud uploader utility

- Xamarin.Forms.Platform.iOS/PlatformRenderer.cs
PlatformRenderer and ModalWrapper are Wrappers around the real UIViewController, rotation and orientations methods are not correctly forwarded in IOS. Per example, you cannot programatically lock the rotation of the IOS screen. This changes will fix that.
No Unit test was made. Will do if you need checking, but the code is pretty straightforward.
None
None
PlataformRender and ModalWrapper will forward orientation methods from their first child (The Actual Controller).
> Forward Orientation Methods in PlatformRenderer and ModalWrapper

- Xamarin.Forms.Platform.WP8/FormsApplicationPage.cs
Fixed bug for WP8 silverlight so it will not hang when resuming app.
https://bugzilla.xamarin.com/show_bug.cgi?id=41076
None
None
> Fixed wp silverlight on resume bug - bugzilla 41076

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40333.cs
Disabling the UI test `ClickingOnMenuItemInMasterDoesNotCrash_NavPageVersion` on iOS; what it's testing was never broken on iOS (just on Android), and the test is broken because of an unrelated bug (see: [41085 Detail page contents disappear on iOS](https://bugzilla.xamarin.com/show_bug.cgi?id=41085))
> Turn off iOS version of 40333 UI test 

- Xamarin.Forms.Platform.Android/ViewRenderer.cs
- Xamarin.Forms.Platform.iOS/ViewRenderer.cs
ViewRenderer is filled with protections against null pointer on Control except for 1 place.  This fixes that 1 missing place by calling through to the base for the null Control case.
> Protect against null Control

- Xamarin.Forms.Core.UnitTests/AppLinkEntryTests.cs
- Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
- Xamarin.Forms.Core/AppLinkEntry.cs
- Xamarin.Forms.Platform.Android/FormsApplicationActivity.cs
Implement the AppIndexProvider on non-AppCompact backend.
Fix bug on KeyValues on AppLinkEntry
- https://bugzilla.xamarin.com/show_bug.cgi?id=40866
- https://bugzilla.xamarin.com/show_bug.cgi?id=40830
> [Android] Implement the AppIndexProvider on non-AppCompact, fix KeyValues on AppLinkEntry

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla31806.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/NavigationPageRenderer.cs
When calling` PopToRootAsync` on 8.1/UWP, the navigation stack was being cleared, but the current page wasn't actually being set, so a crash would subsequently occur if attempting to call it again, for example. This was due to a missing event handler on the `NavigationPageRenderer` which sets the page to the expected root.
https://bugzilla.xamarin.com/show_bug.cgi?id=31809
Added:
- (private) void OnPopToRootRequested(object sender, NavigationRequestedEventArgs e)
None.
> [8.1/UWP] Fix PopToRootAsync functioning incorrectly

- Xamarin.Forms.Pages/Xamarin.Forms.Pages.csproj
- Xamarin.Forms.Pages/packages.config
XF.Pages is the one project that uses MS.Bcl.Build v1.0.14 instead of v1.0.21. On a truly clean build (`git clean -fxd`) this version causes a build error:
> The build restored NuGet packages. Build the project again to include these packages in the build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317568.
Tried reading their link but it seemed a bit confused. Instead, noticed that `PageGallery.Droid.csproj` and `XF.Pages.Azure` use v1.0.21 so I updated to that version and the build error vanished. So I guess the MS.Bcl.Build team thought of a new way to solve their issue. Hopefully, there's no reason we can't simply upgrade.
> XF.Pages MS.Bcl.Build v1.0.14 -> v1.0.21

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40005.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/NavigationRenderer.cs
Make sure to call update toolbar method when not using non app compact NavigationPageRenderer
https://bugzilla.xamarin.com/show_bug.cgi?id=40005
> [Android] UpdateToolbar when page is added before on non AppCompact

- Xamarin.Forms.Platform.Android/Forms.cs
Timer comes back on a thread at the interval requested. In the event that our callback has no finished processing by the time this happens a second time, we will double fire the callback. Rather than attempt to "catch up" we skip frames that the callback misses.
This fixes the GREF issue reported by the Android team against Cycle 7, this report was not handled on the public bug tracker, so no link.
None
None other than described bug fix.
> Fix android StartTimer race condition

- Xamarin.Forms.Xaml.UnitTests/Issues/Bz41296.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz41296.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/MarkupExtensionTests.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/XamlServiceProvider.cs
Fixed loading MarkupExtension from default namespace if default namespace is not http://xamarin.com/schemas/2014/forms. See added unit test.
https://bugzilla.xamarin.com/show_bug.cgi?id=41296
None
None
> [Xaml] Fix MarkupExtension not found in default namespace

- Xamarin.Forms.Platform.WinRT/ImageRenderer.cs
Images on WinRT and UWP will be center cropped when in AspectFill to provide the same experience that Android and iOS currently provide. Change was discussed in forms-devel Digest, Vol 1, Issue 9.
None
Images on WinRT and UWP will be center cropped when in AspectFill.
> WinRT/UWP center crop image on AspectFill

- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
Storing default color for TabbedPage bar text on Android so we can reset it if necessary.
- [Android] Can't reset BarTextColor to default on TabbedPage
None
None
> [Android] TabbedPage text can be set back to Default

- Xamarin.Forms.Core/Thickness.cs
Thickness.IsDefault was ignoring Bottom value
None raised so far.  
None.
Thickness.IsDefault ignore Bottom value.  This PR resolves this small issue.
> [XAML] fix Thickness.IsDefault. Bottom was ignored

- Xamarin.Forms.UITest.Validator/Xamarin.Forms.UITest.Validator.csproj
Fix one of the iOS `git clean -fxd` build errors by removing extra XF.UITest.Validator nunit reference.
> Fix iOS clean build

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40333.cs
Disables failing test from fix for [40333](https://bugzilla.xamarin.com/show_bug.cgi?id=40333) for iOS, which fails due to unrelated issue [41085 – Detail page contents disappear on iOS](https://bugzilla.xamarin.com/show_bug.cgi?id=41085).
> Disable Tabbed test from 40333 for iOS

- Xamarin.Forms.Platform.Android/ViewRenderer.cs
ViewRenderer failed to unsubscribe from FocusChangeRequested on disposed and so attempted to dispatch a focus change request to a disposed renderer.
https://bugzilla.xamarin.com/show_bug.cgi?id=33507
> ViewRenderer unsubscribe from FocusChangeRequested on dispose

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla27417Xaml.xaml
- Xamarin.Forms.Platform.WP8/ButtonRenderer.cs
- Xamarin.Forms.Platform.WinRT/ButtonRenderer.cs
Previously, the Windows platforms hard-coded the size of button images to 30x30; this meant that larger images on buttons could not be displayed and smaller images were scaled up.
This change removes the hard-coded size and uses the actual size of the image when laying out the button.
Currently no way to automate tests for this.
- [41241 – Custom Button Image Missized in Xamarin Forms Cross-platform in the WinPhone App](https://bugzilla.xamarin.com/show_bug.cgi?id=41241)
None
Anyone who relied on the button images of sizes other than 30x30 resizing to 30x30 on Windows platforms will need to resize their Windows image assets to that specific size.
> Remove hard-coded image sizes for button images

- Xamarin.Forms.Core/Registrar.cs
Allow Registrar.RegisterAll to be invoked multiple times.
None
There are cases where we run RegisterAll manually to ensure all
assemblies have actually been registered. The `Registrar<T>` class
does not use the `Dictionary<K, V>.Add` method so it does not
throw if there's a clash/duplicate.
If we change the `Effect` registration to use the same pattern we
can remove errors like this:
```
System.ArgumentException: An item with the same key has already been added.
at ThrowArgumentException at offset 0 in file:line:column /Users/builder/data/lanes/2922/977921b7/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/throwhelper.cs:72:0
at Insert at offset 142 in file:line:column …
```
> [Core] Allow Registrar.RegisterAll to be run multiple times

- Xamarin.Forms.Controls/CoreGalleryPages/KeyboardCoreGalleryPage.cs
- Xamarin.Forms.Core/Keyboard.cs
- Xamarin.Forms.Core/KeyboardFlags.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Keyboard.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/KeyboardFlags.xml
When creating an Entry for a username, for example, there should be NO possible Keyboard interference with the typing performed by the user.  No autocaps, spellcheck, suggestions, etc.  usernames are typically not english words so we don't want any chance of the Keyboard itself messing up what the user types.  Therefore, there should be a keyboard that has none of these features.  Currently, there is no obvious way of doing this except for creating a custom keyboard with KeyboardFlags.  However, KeyboardFlags has no option to choose None of the features.  There is NO 0 value in the KeyboardFlags enum.  Therefore, the developer must hardcode a 0 and then cast it to KeyboardFlags like this:
Keyboard.Create((KeyboardFlags)0)
This is not very appealing.  This pull request allows a developer …
> Add Plain Keyboard from KeyboardFlags.None

- Xamarin.Forms.Core/GridLength.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/GridLength.xml
When writing UI in code, it should be as convenient as possible, like XAML.  When configuring Row and Column Definitions in a Grid, the majority of the time only (1,Auto) and (1,Star) are needed.  There is already a convenience value for (1,Auto) with GridLength.Auto, but there is not one for (1,Star) with GridLength.Star.  This adds that allowing this:
RowDefinitions = {
new RowDefinition { Height = GridLength.Auto },
new RowDefinition { Height = new GridLength (1, GridUnitType.Star) },
new RowDefinition { Height = new GridLength (1, GridUnitType.Star) }
}
to become this:
RowDefinitions = {
new RowDefinition { Height = GridLength.Auto },
new RowDefinition { Height = GridLength.Star },
new RowDefinition { Height = GridLength.Star }
}
Added convenience static value GridLength.Star
> Add convenience GridLength.Star

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41078.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/ListViewRenderer.cs
On Windows 8.1, when the `SelectedItem` property on a `ListView` was set prior to the page it was contained in displaying, there was no indication of that item being selected (although the value was set) when the page eventually displayed. This is normally indicated via a background color on the cell. Subsequent selections of other items would cause the visual indication to work as expected. Explicitly calling `OnElementItemSelected` in `OnElementChanged` if the `SelectedItem` value has been set resolves this.
A visual reproduction has been added to the Control Gallery's issues.
https://bugzilla.xamarin.com/show_bug.cgi?id=41078
None
None expected.
> [Win 8.1] Initial ListView selection not shown

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40704.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
When we are using the RecycleElement strategy we reuse always the same cell for the group header, but this should only happen when we are passed a valid native cell to be reused, not when we don't have a convertView (native reusable cell). 
This change makes sure we request a new GroupHeaderCell and don't use one that's being used at the same time.
https://bugzilla.xamarin.com/show_bug.cgi?id=40704
None
None
> [Android] Always create a new cell for GroupHeader when using Recycling

- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
Fix usage of a API18 only constructor on ScaleGestureDetector
- https://bugzilla.xamarin.com/show_bug.cgi?id=36447
None
None
> [Android] Fix Api18 usage on PinchGesture

- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
Update mangled characters in project reference in XS
This _might_ fix the problem with the PCL bait-and-switch getting the wrong DLL intermittently. Works on my machine, need to verify in the build lanes.
> Fixing parentheses in project reference

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40998.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/Platform.cs
On UWP, when DisplayActionSheet is being awaited, pressing escape while the ActionSheet is visible would cause it to disappear but not actually return any result. Checking for an escape keypress in the window and setting the result to `ContentDialogResult.None` (as no button was tapped) returns a result as expected.
A reproduction has been added to the issues gallery.
https://bugzilla.xamarin.com/show_bug.cgi?id=40998
None
Presumably none.
> [UWP] Escape key returns ActionSheet result

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41038.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
When a page is being removed we need to make sure we update the left toolbar item to show the master icon or text. We need to pas a reference of the remove page, because the NavigationPage still has that page in the navigation stack, the event fires on the renderer before it's removed from the internal children. 
https://bugzilla.xamarin.com/show_bug.cgi?id=41038
None
None
> [iOS] Call UpdateLeftBarButtonItem when page is removed

- Xamarin.Forms.Platform.WinRT/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.WinRT/Platform.cs
In order to push a modal on app load the NavigationProxy needs a inner reference to the Platform itself. 
Also a small fix to remove the back button on UWP when the NavigationPageRenderer is removed. 
- https://bugzilla.xamarin.com/show_bug.cgi?id=39187
- https://bugzilla.xamarin.com/show_bug.cgi?id=41854
None
None
> [WinRT] Add base platform as inner proxy navigation to Application, Fix back button issue

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla27417.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla27417Xaml.xaml
- Xamarin.Forms.Platform.Android/AppCompat/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ButtonRenderer.cs
When an image and no text is specified for an image, the image position should default to centered (vertically and horizontally). This fixes a bug in the Android logic which leaves images aligned near the top of the button when the button is sufficiently taller than the image.
- [Vertical centering of images from 27417](https://bugzilla.xamarin.com/show_bug.cgi?id=27417)
None
> [Android] Fix vertical centering of button images 

- Xamarin.Forms.Core/ListView.cs
We were using a fixed LayoutConstraint for the viewcell view, this caused Grid't using '*' (star) to skip computing the size of it's children and returning the cached value. 
https://bugzilla.xamarin.com/show_bug.cgi?id=37862
None
None
> [Core] Don't use the fixed LayoutConstraint when using uneven rows

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla38284.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Maps.iOS/MapRenderer.cs
If the iOS MKMapView is invisible it will update it's region because there's no Frame/Bounds for calculation. We need to make sure we update the current region when the map is visible again.
Couldn't find a way to add a UITest to it.
https://bugzilla.xamarin.com/show_bug.cgi?id=38284
None
None
> [IOS] Update the current region of the MKMapView when visible

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41842.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/MasterDetailControl.cs
MasterDetailControl will no longer null out the TCS before it is used. 
Failure only occurs when the MainPage is swapped out and the Detail page is changed twice. UI test doesn't cover this scenario.
- [Bug 41842  - Set MasterDetailPage.Detail = New Page() twice will crash the application when set MasterBehavior = MasterBehavior.Split] (https://bugzilla.xamarin.com/show_bug.cgi?id=41842)
None
Resolves NRE crash
> [UWP] MasterDetailControl will no longer null out the TCS before it is used. 

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41424.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/DatePickerRenderer.cs
When using the DatePicker in Android, closing it via the cancel button would not unfocus the Element, causing a Focus() call via something such as a button to not function as otherwise expected.
https://bugzilla.xamarin.com/show_bug.cgi?id=41424
None
None expected
> [Android] DatePicker unfocuses on cancel

- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/MasterDetailContainer.cs
On Android when using the split behaviour we need to add a extra padding to the master page.
https://bugzilla.xamarin.com/show_bug.cgi?id=41404
None
Master page of MDP when in split on a tablet android will show correctly bellow the status bar
> [Android] Fix padding on master MDP when using split view

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40704.cs
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
When we have to create a GroupHeader cell since we aren't using TIL methods we need to make sure we add a parent to the cell so it can measure the content. The issue wasn't visible at first because of missing the LayoutOptions on the label. 
https://bugzilla.xamarin.com/show_bug.cgi?id=40704
None
None
> [Android] Set parent to the new group header cell

- Xamarin.Forms.ControlGallery.iOS/CustomRenderers.cs
- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs
[iOS] Not setting the BarTextColor/BarBackgroundColor (i.e., leaving set to Default) will no longer override values set in custom renderers,
Visually test this by viewing the TabbedPage on the gallery. The tab bar should be purple/white, then maroon/yellow, then purple/white again.
- [Reported on forums] (https://forums.xamarin.com/discussion/comment/204166/#Comment_204166)
- [Bug 41980 - TabBar BarTintColor no longer working in 2.3.0.49] (https://bugzilla.xamarin.com/show_bug.cgi?id=41980)
- [Bug 42032 - UINavigationBar.Appearance.BarTintColor changes Tab bar color] (https://bugzilla.xamarin.com/show_bug.cgi?id=42032)
None
TabbedPage BarTextColor/BarBackgroundColor defaults are drawn from values set by a renderer, falling back to global defaults.
> [iOS] Default BarTextColor/BarBackgroundColor will no longer override values set in custom renderers

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39486.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Cells/ViewCellRenderer.cs
Fixes regression on UnevenRows.
When refactoring the code for the PR i added a extra parenthesis that was messing the calculation of the height of the row.
- Fixes regression on 2.3.1-pre1
> [iOS] Fix regression 2.3.1-pre1 UnevenRows

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42277.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.shproj
- Xamarin.Forms.Core/ITemplatedItemsList.cs
- Xamarin.Forms.Core/TemplatedItemsList.cs
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
- Xamarin.Forms.Platform.WinRT/ListViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/ITemplatedItemsList`1.xml
- [All] Fixed invalid cast exception when using DataTemplateSelectors.
- [Android] Fixed null reference exception when using grouped ListView with no GroupHeaderTemplate and RecycleElement enabled.
-  [Bug 42277  - DataTemplate System.InvalidCastException crash in 2.3.1-pre1] (https://bugzilla.xamarin.com/show_bug.cgi?id=42277)
Added:
- IListProxy ITemplatedItemsList.ListProxy { get; }
Hopefully none, besides not crashing, of course.
> [All] Crash fixes for ListViews

- Xamarin.Forms.Platform.Android/Renderers/DatePickerRenderer.cs
KitKat and older don't use a cancel button on the DatePicker dialog which was causing an NRE due to changes made in #204, so we have to account for it.
Fixes regression on #204
- https://bugzilla.xamarin.com/show_bug.cgi?id=42361
N/A
Should no longer crash.
> Fix DatePicker dialog regression

- Xamarin.Forms.Core.UnitTests/NavigationUnitTest.cs
- Xamarin.Forms.Core/NavigationPage.cs
- Xamarin.Forms.Core/PoppedToRootEventArgs.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- docs/Xamarin.Forms.Core/Xamarin.Forms/NavigationPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/PoppedToRootEventArgs.xml
Implementation of proposal 0002
[https://github.com/xamarin/xamarin-evolution/blob/master/xamarin.forms/proposals/0002-additional-event-args-on-popped-to-root.md](url)
API changes as stated in the proposal.
As stated in the proposal.
> Implementation of proposal-0002

- Xamarin.Forms.Core/VisualElement.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/VisualElement.xml
When making the VisualElement.cs changes to allow for InternalsVisibleTo to be disabled, the `protected virtual void InvalidateMeasure()` method was incorrectly refactored into an overload of `InvalidateMeasureInternal()`. This change restores the original method name.
- http://forums.xamarin.com/discussion/comment/208593/#Comment_208593
- [42352 – [iOS] Xamarin.Forms 2.3.1.111-pre2 does not work with linker](https://bugzilla.xamarin.com/show_bug.cgi?id=42352)
None
None
> Restore incorrectly renamed InvalidateMeasure method

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42074.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/TimePickerRenderer.cs
This is a similar fix to #204 which needed to be adjusted to respect the cancel button being pressed on the `TimePicker` dialog, as well. The control gallery reproduction and test for that issue has been duplicated and modified to check against the `TimePicker`.
https://bugzilla.xamarin.com/show_bug.cgi?id=42074
None.
None.
> [Android] TimePicker unfocuses on cancel

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue55555.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
When the user is using the RecycleElement strategy we don't really on the TIL cells, so we handle creating the group header cell on the platform side.
We weren't handling the case where no template was provided, (user provided the GroupDisplayPath).
This change makes sure we create the default group header and set the attached property so we know is a groupheader.
> [Android] Handle creating a default GroupHeader if no GroupHeaderTemplate is provided

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41205.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/CellControl.cs
Fix regression where CreateDefault would be passed a ToString variant of the ViewModel in the ItemsSource instead of the ViewModel directly.
- https://bugzilla.xamarin.com/show_bug.cgi?id=41205
None
On UWP/WinRT CreateDefault now gets passed the item from your ItemsSource and not the item.ToString () result. This is in line with iOS/Android and the previous UWP behavior of 2.0.
> Ensure BindingContext is properly passed to CreateDefault in UWP ListView

- Xamarin.Forms.Platform.Android/Renderers/ActivityIndicatorRenderer.cs
The API check does not need to be used as it was preventing a color from being applied to the ActivityIndicator when running on pre-Lollipop.
I set up an API 15 emulator to run the gallery with a reproduction to confirm it looks as expected when setting the color. It isn't included as a part of the commit.
https://bugzilla.xamarin.com/show_bug.cgi?id=42326
None
None
> [Android] Remove API check in ActivityIndicatorRenderer's UpdateColor method

- Xamarin.Forms.Platform.Android/AppCompat/PickerRenderer.cs
Multiple, rapid taps on the Picker in AppCompat could potentially open more than one dialog, causing a crash upon their being closed. Adding a null check for the dialog prevents more than one from being created. 
This was more easily producible on an actual device opposed to an emulator.
- https://bugzilla.xamarin.com/show_bug.cgi?id=41717
None
None
> [Android] Add dialog null check for AppCompat Picker OnClick

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
When a page was already navigated, and you used NavigationPage.SetHasBackButton(this, false) to switch of the Back Button in Android AppCompat, the toolbar was not updated.
[https://bugzilla.xamarin.com/show_bug.cgi?id=42557](https://bugzilla.xamarin.com/show_bug.cgi?id=42557)
None
> Fixes issue when setting NavigationPage.SetHasBackButton after page has navigated (Android/AppCompat)

- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
Resubmission of https://github.com/xamarin/Xamarin.Forms/pull/245
Forwarded orientation events from ParentingViewController to the child ViewController.
Did not find any specific bugs relating to the exact problem. The fixes however (and general issue altogether) is very similar to this, https://github.com/xamarin/Xamarin.Forms/pull/147, but is more to do with NavigationPage.
May also be related to this bug, https://bugzilla.xamarin.com/show_bug.cgi?id=26169
None.
None.
… on iOS.
> Fixed issues where you could not force rotation with a NavigationPage

- Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs
Added null checks before accessing fields. No tests since I didn't know how to test platform renderers.
None reported.
None
If user subclasses `ListViewRenderer` and calls `SetNativeControl` before `base.OnElementChanged` it no longer crashes.
> [Android] Null reference exception fix

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/EventsConnection.xaml
- Xamarin.Forms.Xaml.UnitTests/EventsConnection.xaml.cs
[XamlC] Correclty resolve the event handler in case the virtual base is overriden in a subclass
- in my mail box only
None
> [XamlC] correctly resolve override of virtual event handlers

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42075.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
Prevent the `FormsAppCompatActivity` from attempting to restore fragments when being restored after being killed because of limited memory. Previously, the fragments were restored and then ignored by XF; in the case of nested fragments (e.g., a `TabbedPage` or `MasterDetailPage` containing another `TabbedPage`), this caused an `IllegalStateException` (followed by a crash) because a view could not be associated with the nested fragment. Now the `FormsAppCompatActivity` won't attempt to restore the fragments we weren't going to use anyway. (Bonus: slight memory improvement!)
- [42075 – IllegalStateException - Fragment does not have a view](https://bugzilla.xamarin.com/show_bug.cgi?id=42075)
None
If a user is deliberately matching up and restoring fragments by tag when the application is …
> Prevent FormsAppCompatActivity from loading fragments we don't use on restart

- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Platform.UAP/Resources.xaml
- Xamarin.Forms.Platform.UAP/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.WinRT.Phone/FormsPivot.cs
- Xamarin.Forms.Platform.WinRT.Phone/PhoneResources.xaml
- Xamarin.Forms.Platform.WinRT.Phone/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.WinRT.Tablet/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.WinRT.Tablet/TabletResources.xaml
- Xamarin.Forms.Platform.WinRT/FrameworkElementExtensions.cs
Resolved known issues with the new `BarTextColor` feature for `TabbedPage`s on Windows platforms.
- [WinRT, WinPhone 8.1, UWP] Setting `BarTextColor` does not currently work. 
- [WinPhone 8.1, UWP] If the `TabbedPage` contains a `NavigationPage`, the `BarBackgroundColor` and `BarTextColor` for the `NavigationPage` takes precedence
- [WinPhone 8.1] If the `TabbedPage` contains a `NavigationPage`, switching between tabs may cause the background color to be lost.
None
- [Win] Explicitly setting the `BarTextColor` and `BarBackgroundColor` to `Color.Default` will take precedence over the `BarTextColor` and `BarBackgroundColor` on `NavigationPage`s. However, if the `BarTextColor` and `BarBackgroundColor` for the `TabbedPage` are never set, the `NavigationPage`s may supply individual …
> [Win] Setting TabbedPage.BarTextColor works

- Xamarin.Forms.Core/Image.cs
Catch an ObjectDisposedException in Image.cs. This is causing lots of crashes in production for us, but we are not able to reproduce the bug reliably.
https://bugzilla.xamarin.com/show_bug.cgi?id=37792
None
None
> Add workaround for bugzilla 37792

- Xamarin.Forms.Platform.WinRT/ListViewRenderer.cs
Putting ListView in line with standard behavior where `ItemClick` would normally fire off when pressing the enter key to select a ListView item.
https://bugzilla.xamarin.com/show_bug.cgi?id=42188
None
If a user had a custom renderer with behavior linked to `KeyUp` for the enter key, something unintentional could potentially occur, though perhaps unlikely.
> [8.1/UWP] ListView allows selection with enter key

- Xamarin.Forms.Platform.Android/AppCompat/PickerRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/PickerRenderer.cs
On AppCompat, focus and unfocus would not trigger when using the Picker. On pre-Lollipop, unfocus would not trigger, but only when tapping outside of the dialog.
https://bugzilla.xamarin.com/show_bug.cgi?id=42687
None
None
> [Android] Fix focus/unfocus behavior on both Picker renderers

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40858.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/CellAdapter.cs
When a text entry control (Entry, Editor, SearchBar, etc.) was being used in the header or footer of a `ListView` on Android, a long click/press would cause a crash. This was occurring in the `HandleContextMode` method because it expected to be a cell. Adding a null check and breaking out of the method if the value from `GetCellForPosition` is null prevents this crash from occurring.
https://bugzilla.xamarin.com/show_bug.cgi?id=40858
None
None
> [Android] Add null check to prevent crashes when long clicking a text entry in ListView header/footer

- Xamarin.Forms.Platform.Android/Forms.cs
On Android Color.Accent is set to a hardcoded value in Xamarin.Forms.Forms.SetupInit (in the Platform.Android project) and it cannot be changed by the user.
This color is then used as text and separator color for TableSections. The user cannot override the color.
As the hardcoded color may not fit to the users app theme, this should be changed.
Jason Smith said on forms-devel that the code should read from the current Android theme. This change does that.
I wouldn't know how to unit test this.
- https://bugzilla.xamarin.com/show_bug.cgi?id=42812
None
Color.Accent will be set to the accentColor of the current Android theme instead of the hardcoded values.
> [Android] Color.Accent is hardcoded

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42069.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42069_Page.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42069_Page.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/Image.cs
- Xamarin.Forms.Core/ImageSource.cs
- Xamarin.Forms.Core/WeakEventManager.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.WinRT/WindowsDeviceInfo.cs
The Image element subscribes to the `SourceChanged` on the `ImageSource` element, which means that Images which use an application-wide `ImageSource` static resource cannot be garbage collected. This change adds a PCL version of the `WeakEventManager` class which maintains weakly-referenced event subscriptions for the `ImageSource`'s internal `SourceChanged` event; this allows subscribers to be garbage collected.  
- [42069 – Garbage Collector can not collect pages that use ImageSource as a StaticResource](https://bugzilla.xamarin.com/show_bug.cgi?id=42069)
None
None
referencing application-wide StaticResource ImageSources to be GCed
> Allow GC of Images bound to application-wide ImageSource StaticResources

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42329.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/FrameRenderer.cs
The AppCompat version of `FrameRenderer` was not disposing of its child renderers, which prevented pages with some combinations of controls from being collected. Most renderers inherit this behavior from `VisualElementRenderer`, but `FrameRenderer` is not a subclass of `VisualElementRenderer`. This change duplicates the disposal behavior from `VisualElementRenderer`.
- [42329 – ListView in Frame and FormsAppCompatActivity Memory Leak](https://bugzilla.xamarin.com/show_bug.cgi?id=42329)
None
None
> Dispose of child renderers in FrameRenderer

- Xamarin.Forms.Platform.Android/Renderers/LabelRenderer.cs
When using the SetSingleLine(true) in the base LabelRenderer on Android, developers won't be able to use the SetMaxLines() in their own Custom Renderers
later on.
So we force a single line by using the SetMaxLines(1) in the
base LabelRenderer and SetSingleLine(false)
> [Android] Don't force the SetSingleLine() to true

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla33561.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs
Now restarting the indicator animation when the `ListView` reappears and is still refreshing. A manual test has been provided for review.
- [Bugzilla 33561 - Listview Pull-to-Refresh ActicityIndicator animation stuck when navigating away and then back again] (https://bugzilla.xamarin.com/show_bug.cgi?id=33561)
Added:
- `override UIViewController Platform.iOS.ListViewRenderer.ViewController`
Changed:
- `UIViewController Platform.iOS.VisualElementRenderer.ViewController` is now virtual
- [Android] `Refreshing` event will trigger again when the `ListView` appears again while it is still refreshing.
- [iOS] `ListView` will now received forwarded events from its parent `UIViewController` (e.g., `ViewWillAppear`), even when the parent is a `UINavigationController` or `UITabBarController`. …
> [A, iOS] ListView Pull-To-Refresh indicator animates when navigating back to it

- Xamarin.Forms.Platform.WinRT/ListViewRenderer.cs
In both UWP/Win 8.1, if a keyboard was being used to make a selection out of a list of items, the `SelectedItem` value on the `Element` was not being updated due to its not being changed via tap/click, although `OnControlSelectionChanged` would still fire and update the `SelectedIndex` value on the `ListView`.
In this change, the `ShouldCustomHighlight` bool property is removed, but its general behavior in checking that the platform isn't UWP and is the Phone idiom are shifted into the `OnControlSelectionChanged` method itself. `OnControlSelectionChanged` is then always hooked and unhooked so that it may be called when the selection changes, and if the `Element.SelectedItem` value hasn't changed, we can reasonably assume that this selection change was made via keyboard and not tap or …
> [UWP/8.1] ListView respects keyboard selection

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40824.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42364.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
When a `ListView` on a navigated page had a contextual actions menu open for one of its items and something caused a navigation to a new page (such as a button press), the menu would stay open. This was apparently caused by two things: the `Platform` type in the `ListViewAdapter` was being treated as the non-AppCompat type, thereby causing its use of the `MessagingCenter` to be non-functional, and the lack of the `NavAnimationInProgress` being set as necessary in the `NavigationPageRenderer` under AppCompat, whereas it was being set in the `NavigationRenderer` in non-AppCompat.
**Update**: A similar fix for TabbedPage which relies upon the initial commit has been added.
ControlGallery reproductions have been added for visual confirmation.
https://bugzilla.xamarin.com/show_bug.cgi?id=40824 …
> [Android] Fix ListView contextual actions not closing in AppCompat's NavigationPage/TabbedPage

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41029.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/FormsSeekBar.cs
- Xamarin.Forms.Platform.Android/Renderers/SliderRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
This issue seems to be a bug on android, for some reason the SeekBar gets the pressed state if we have a GestureDetector above on the hierarchy and the background ins transparent, i have checked and even with the correct Clickable = false; or DuplicateParentStateEnabled set to false this behaviour still occurs. 
My change is to override when android is trying to set the SeekBar as pressed state and check if we are or not touching the Slider itself before setting the pressed state.
The testing has to be with visual inspection . 
https://bugzilla.xamarin.com/show_bug.cgi?id=41029
None
> Fix bugzilla41209

- Xamarin.Forms.Platform.Android/CellAdapter.cs
Fixing a issue where destroy is called first on cell adapter, there we dispose the current mode open.
Then on click we weren't trying to finish the already disposed mode, by closing the correct one we don't need to check if the pointer is null. 
- Fixes failing uitest on android on master 32541
None
None
> [Android] Close the correct mode if it wasn't disposed

- Xamarin.Forms.Core.UnitTests/ResourceDictionaryTests.cs
- Xamarin.Forms.Core/ResourceDictionary.cs
Add the key in the message on throwing a KeyNotFoundException for trying to access an invalid key in the ResourceDictionary. This helps in tracking down what resource is actually missing. 
None
None
None
…ing to access an invalid key in the ResourceDictionary. This helps a lot in tracking down what resource is actually missing.
> Add the key in the message on throwing a KeyNotFoundException

- Xamarin.Forms.Core.UnitTests/WeakEventManagerTests.cs
- Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
- Xamarin.Forms.Core/WeakEventManager.cs
Adds unit tests (and a couple of bug fixes) for the PCL WeakEventManager
- Now handles static event handlers correctly
- Fix 'collection was modified' error when HandleEvent removes a collected subscription
None
None
> Unit tests for the PCL WeakEventManager

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41205.cs
- Xamarin.Forms.Platform.WinRT/CellControl.cs
Win/UWP cells created by `.CreateDefaultCell` will have their `BindingContext` set to the `item`.
- [Bug 41205  - Override ListView.CreateDefault, parameter is always string] (https://bugzilla.xamarin.com/show_bug.cgi?id=41205)
None
None
> [Win] Set BindingContext for default cell

- Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/ICompiledMarkupExtension.cs
- Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/StaticExtension.cs
- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/ExpandMarkupsVisitor.cs
- Xamarin.Forms.Build.Tasks/MethodDefinitionExtensions.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Xaml.UnitTests/FactoryMethods.xaml
- Xamarin.Forms.Xaml.UnitTests/FactoryMethods.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Validation/StaticExtensionException.xaml.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- Xamarin.Forms.Xaml/ExpandMarkupsVisitor.cs
- Xamarin.Forms.Xaml/XamlParser.cs
This will (one day) allow this syntax to be valid
```
<android:TextView x:Arguments="{x:Static forms:Forms.Context}" />
```
Every single line of code was manually crafted with pure droplets of sweat. DO NOT LICK. It's not food safe.
In order to help a brave soul to review this, I'll add some comments on my own to guide you, wait 5 minutes. Thx.
- none. The bugs I'm fixing only exists in my head
None
> [Xaml] x:Static in x:Arguments

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43214.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
No longer trying to prevent unnecessary calling of `SendRefreshing()`.
- [Bug 43214 - Setting Listview.IsRefreshing to false does not work on second "pull"] (https://bugzilla.xamarin.com/show_bug.cgi?id=43214)
None
iOS ListView may fire SendRefreshing more than once when navigating between tabs or pages.
> [iOS] Fixed bug that made pull-to-refresh indicator always visible after 2+ pulls

- Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs
Builds on #274. This time, we're restarting it `OnAttachedToWindow`. Will use the same test.
- [Bugzilla 33561 - Listview Pull-to-Refresh ActicityIndicator animation stuck when navigating away and then back again] (https://bugzilla.xamarin.com/show_bug.cgi?id=33561)
None
None
> [A] Pre-AppCompat ListView Pull-To-Refresh indicator animates when navigating back to it 

- Xamarin.Forms.Core.UnitTests/LabelTests.cs
- Xamarin.Forms.Core/Label.cs
Changes in `FormattedText` such as `FormattedText.Spans.Add` can change the length of text and the measure of `Label`. This commit assures that `Label` properly apply the change.
- Sorry but I have not opened an issue.
Nothing.
Nothing.
- [*] Has tests (if omitted, state reason in description)
- [*] Rebased on top of master at time of PR
- [*] Changes adhere to coding standard
- [*] Consolidate commits as makes sense
> Invalidate measure of Label when FormattedText changes

- Xamarin.Forms.Core.UnitTests/BindingUnitTests.cs
- Xamarin.Forms.Core/BindingExpression.cs
In our application we discovered a memory leak in the following situation:
* Have a long-lived ViewModel object (maybe lives the lifetime of your app)
* Bind to it in a View
* The View goes away, and get's GC'd
* A `BindingExpression` object and its children remain in memory as long as the long-lived ViewModel
- Not sure if there is an issue out for this, see my unit test that reproduces the issue
None
`BindingExpression` will not remain in memory when the `View` is GC'd.
> Fix for BindingExpression memory leak

- Xamarin.Forms.Platform.WinRT/Platform.cs
`DisplayAlert` was returning a true value when pressing the escape key while it was open on Windows (reported under UWP, but the behavior is a WinRT issue in general). It was also returning true when pressing the enter key. Inside of the `OnPageAlert` method where the `DefaultCommandIndex` value was being signed, that value was being set to zero as only one `UICommand` had been added by that point. Subsequently, the `CancelCommandIndex` was then being set to 0, which in this case would trigger the Accept command when pressing the escape key. Swapping the manner in which the values are set corrects the behavior.
https://bugzilla.xamarin.com/show_bug.cgi?id=43230
None
None
> [Windows] Correct enter/esc keypress behaviors for MessageDialog

- Xamarin.Forms.Xaml.UnitTests/MarkupExpressionParserTests.cs
- Xamarin.Forms.Xaml.UnitTests/TypeExtension.xaml
- Xamarin.Forms.Xaml.UnitTests/TypeExtension.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml.UnitTests/XamlLoaderCreateTests.cs
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/XamlNode.cs
Clone node tree on DataTemplates, allowing markup extensions (like x:Type and x:Static) to be evaluated multiple times.
- @jonathanpeppers: do you have link for this ?
None
> [Xaml] Clone node tree on DT

- Xamarin.Forms.Platform.WinRT/Platform.cs
Rapidly double-clicking an item in an action sheet twice under WinRT could cause an NRE due to the `_currentActionSheet` value being set to null right away within the `ItemClick` event handler. The value is set to null in the `CancelActionSheet` method which ultimately gets called via the `Closed` event, so it should be safe to remove the earlier null to prevent this potential crash.
https://bugzilla.xamarin.com/show_bug.cgi?id=43328
None
None
> [WinRT] Remove preemptive setting of null upon action sheet closure

- Xamarin.Forms.Platform.WinRT/ListViewRenderer.cs
Fix a regression due to a prior change (#182) which could cause a crash due to `Element.SelectedItem` being null prior to actually selecting an item in a ListView (and then using the keyboard to select items). Adding a null check prevents this from occurring until the ListView has actually had something initially selected.
N/A
None
None
> Fix regression by adding null check in Windows ListView selection

- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
When ItemsSource is set to null, CurrentPage also becomes null. This fix adds a check in TabbedPageRenderer on Android to prevent trying to scroll to a null CurrentPage and crashing.
- https://bugzilla.xamarin.com/show_bug.cgi?id=43726
None
None
> [Android] Fix TabbedPage crash when ItemsSource is set to null

- Xamarin.Forms.Platform.iOS/iOSAppLinks.cs
Currently if the thumbnail source for an AppLinkEntry is not valid on iOS, a generic NRE is thrown when calling `uiimage.AsPNG()`. This fix checks if `uiimage` is null after trying to load the image and if so throws an InvalidOperationException to inform the user why. It also moves other code into the try block in order to avoid another NRE if an OperationCanceledException is caught.
This all assumes that the thumbnail is always required for an AppLinkEntry. If it's not, the null check should be used to just avoid calling `uiimage.AsPNG()` then instead of throwing an exception.
- https://bugzilla.xamarin.com/show_bug.cgi?id=42061
None
None
> [iOS] Throw InvalidOperationException if AppLinkEntry.Thumbnail source is not valid

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla35132.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Cells/BaseCellView.cs
- Xamarin.Forms.Platform.Android/Cells/CellRenderer.cs
Fixes an Android memory leak caused by BaseCellView holding a reference to a Xamarin.Forms.Cell and another caused by a strong reference (via RendererHolder) between native views and CellRenderers.
- [35132 – Pages are not collected when using a Navigationpage](https://bugzilla.xamarin.com/show_bug.cgi?id=35132)
None
None
> Fix memory leaks caused by BaseCellView and RendererHolder

- Xamarin.Forms.Core.UnitTests/ListViewTests.cs
- Xamarin.Forms.Core/ListView.cs
In many places we use the same `BindingContext` for an entire page/view. One pain point, was that the `Header` and `Footer` of a `ListView` didn't get it's `BindingContext` passed down like the rest of the views on a page. 
Hopefully, this is not a design decision for `ListView` as it was an easy fix. It does not look like the change will cause much of a performance impact. There may be other views like `ListView` missing this same functionality, but I haven't ran into them yet.
- See unit test reproducing the issue.
None
When setting the `BindingContext` of a `ListView` the `Header` and `Footer` will also receive the same `BindingContext`.
> Fix for ListView BindingContext for Header/Footer

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42519.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/Layout.cs
- Xamarin.Forms.Platform.WP8/ViewToRendererConverter.cs
- Xamarin.Forms.Platform.WinRT/LabelRenderer.cs
- Xamarin.Forms.Platform.WinRT/ViewToRendererConverter.cs
Changed TextTrimming option for WinRT/UWP to CharacterEllipsis to be consistent with the other platforms. 
Fixed incorrect Height parameters in WrapperControl.
Added extra layout pass on Load for WrapperControl to ensure layouts get correct layout information on initial load.
Changed order of Forms-level layouts and content control measurement in WrapperControl so controls layout correctly on size changes (i.e., portrait->landscape changes).
- [42519 – Text Truncation in UWP](https://bugzilla.xamarin.com/show_bug.cgi?id=42519)
None
None
> Fix text truncation in ListView items in Windows

- Xamarin.Forms.Controls/ControlGalleryPages/PanGestureGalleryPage.cs
- Xamarin.Forms.Platform.Android/InnerGestureListener.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
Now sending the Completed event for Pan on Up event.
- [Bug 39768  - PanGestureRecognizer sometimes won't fire completed event when dragging very slowly] (https://bugzilla.xamarin.com/show_bug.cgi?id=39768)
Added:
- Android: `internal void InnerGestureListener.OnTouchEvent(MotionEvent e)`
None
> [A] PanGestureRecognizer will consistently send Completed event

- Xamarin.Forms.Platform.Android/Renderers/KeyboardExtensions.cs
- Xamarin.Forms.Platform.WP8/EntryRenderer.cs
KeyboardExtensions (Extensions for iOS) was already public in all projects except for Android and WP8. This gets rid of internal modifier so that we can use ToInputType() and ToInputScope() methods in custom renderers to create custom keyboards.
Here's a basic example:
```
// Making sure Android numeric keyboard is the same as iOS
if (Element.Keyboard == Keyboard.Numeric)
{
Control.InputType = InputTypes.ClassNumber | InputTypes.NumberFlagDecimal;
}
else
{
Control.InputType = Element.Keyboard.ToInputType();
}
```
N/A
Changed:
- internal static class KeyboardExtensions => public static class KeyboardExtensions
- internal static InputTypes ToInputType(this Keyboard self) => public static InputTypes ToInputType(this Keyboard self)
N/A
> KeyboardExtensions is now public

- Xamarin.Forms.Platform.Android/AppCompat/FragmentContainer.cs
The `OnResume` method in the `FragmentContainer` would falsely fire off `SendAppearing` for the non-visible tabs on a `TabbedPage`, causing the first switch to a tab to not fire the `Appearing` event as otherwise expected. Checking the UserVisibleHint value prevents this from occurring.
https://bugzilla.xamarin.com/show_bug.cgi?id=43774
None
None involving this, specifically. Note that there is a separate issue, however; when using a test reproduction in the gallery project, the `Appearing` event is still firing twice when first opening the page (Appearing -> Disappearing -> Appearing, after the correction), with the first occurrence coming via [Page.cs#L311](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Page.cs#L311). That issue would likely need to be revisited …
> [A] Check UserVisibleHint to prevent non-active tabs from firing SendAppearing in OnResume

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43516.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/LabelRenderer.cs
Changing a label's `FontAttributes` to `None` in Windows after having it initially set to `Bold` or `Italic` would cause the size of the label to change. This stems from the `IsDefault` method which would subsequently apply the `NamedSize.Medium` value on it. Adding a simple bool value to flag whether it was initially default or not based on the `IsDefault` is true when the control is being created.
For reference, on standard 8.1/UWP apps, the `TextBlock` size stays the same when its `FontWeight` value is changed. A visual reproduction has been added to the gallery.
https://bugzilla.xamarin.com/show_bug.cgi?id=43516
None
While it is technically possible that some apps might expect this odd functionality, it doesn't make much sense from a logical standpoint and presumably one could be …
> [Win] Fix FontAttributes unexpectedly changing a label's size

- Xamarin.Forms.Platform.WinRT.Phone/PhoneResources.xaml
- Xamarin.Forms.Platform.WinRT.Tablet/TabletResources.xaml
Fixes incorrect property name in XAML resources
> Fix incorrect background property name on Win 8.1 phone and tablet styles

- Xamarin.Forms.Build.Tasks/XamlGTask.cs
- Xamarin.Forms.Build.Tasks/XmlTypeExtensions.cs
- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Controls/GalleryPages/XamlNativeViews.xaml
- Xamarin.Forms.Controls/GalleryPages/XamlNativeViews.xaml.cs
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Core.UnitTests/NativeBindingTests.cs
- Xamarin.Forms.Core/INativeBindingService.cs
- Xamarin.Forms.Core/INativeValueConverterService.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Core/XamlParseException.cs
- Xamarin.Forms.Platform.Android/NativeBindingservice.cs
- Xamarin.Forms.Platform.Android/NativeValueConverterService.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
- Xamarin.Forms.Platform.UAP/NativeBindingService.cs
- Xamarin.Forms.Platform.UAP/NativeValueConverterService.cs
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
- Xamarin.Forms.Platform.iOS/NativeBindingService.cs
- Xamarin.Forms.Platform.iOS/NativeValueConverterService.cs
- Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
- Xamarin.Forms.Xaml.UnitTests/Issues/BPNotResolvedOnSubClass.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Issue1497.cs
- Xamarin.Forms.Xaml.UnitTests/NativeViewsAndBindings.xaml
- Xamarin.Forms.Xaml.UnitTests/NativeViewsAndBindings.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/TypeConversionExtensions.cs
- Xamarin.Forms.Xaml/XamlParser.cs
- Xamarin.Forms.Xaml/XmlnsHelper.cs
With this PR, the following Xaml is valid, and works as expected:
```
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
xmlns:ios="clr-namespace:UIKit;assembly=Xamarin.iOS;targetPlatform=iOS"
xmlns:android="clr-namespace:Android.Views;assembly=Mono.Android;targetPlatform=Android"
x:Class="Xamarin.Forms.Controls.XamlNativeViews">
<ContentPage.Content>
<ios:UILabel Text="I'm Native" />
<android:TextView  Text="I'm Native too" />
</ContentPage.Content>
</ContentPage>
```
That means 2 things:
- native views are automagically wrapped into the appropriate wrapper
- xmlns  defined on a non-matching targetPlatform (see TargetPlatform enumeration) are ignored
None
None
None
> [Xaml] Support native view declaration in Xaml

- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/SetResourcesVisitor.cs
- Xamarin.Forms.Core/ConstraintExpression.cs
- Xamarin.Forms.Xaml.UnitTests/GenericCollections.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Validation/SetterOnNonBP.xaml
- Xamarin.Forms.Xaml.UnitTests/Validation/SetterOnNonBP.xaml.cs
Replace runtime type check for SetValue by a compiletime one. It assumes our users are not morons and respect the naming conventions for bindable properties fields and accessors.
This also splits the most monstrous method in the Xamlc into manageable chunks.
> [XamlC] replace the runtime type check by compiletime

- Xamarin.Forms.Platform.iOS/Renderers/DatePickerRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TimePickerRenderer.cs
There's presently an issue where the `Ended` event on a `UITextView` doesn't appear to be firing off in iOS 10, but the `EditingDidEnd` hook is fine. This is just switching out those hooks as well as the ones for `Started` to keep them in line.
https://bugzilla.xamarin.com/show_bug.cgi?id=44056
None
None
> [iOS] Adjust Started/Ended hooks in pickers for iOS 10

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43354.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/Button.cs
When creating a `Button` it was possible to unintentionally re-enable it by either:
* Setting `IsEnabled` before `Command` in the constructor/assignment sequence
* Setting the `Command` value to null at another point in time (assuming the above did not occur) 
A visual reproduction has been added to the issues.
https://bugzilla.xamarin.com/show_bug.cgi?id=43354
None
None
> [C] Prevent enabling a Button via setting a Command

- Xamarin.Forms.Platform.WinRT/LabelRenderer.cs
After Label.FormattedText property changed  need invoke UpdateText method.
> Fix updating Label.FormattedText property in WinRT/LabelRenderer

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Added a similar check for disposed object in UpdateMenu() as there is in UpdateToolbar().
- Fixed a random crash in my work area. No bug report created and no sample app available now.
None
App may stop crashing.
> Android AppCompat: Don't do NavigationPage menu updates for disposed page

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Android running in AppCompat wouldn't go back to the home screen using the back button until a navigation was made; this was due to the fix in #272 not setting the `NavAnimationInProgress` value to false when the app first opened. Just moving it to the end and setting it once should fix this issue while leaving the old fix intact.
https://bugzilla.xamarin.com/show_bug.cgi?id=44018
None
None
> [A] Fix regression on NavAnimationInProgress

- Xamarin.Forms.ControlGallery.iOS/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43161.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Cells/ViewCellRenderer.cs
Will no longer adjust the Bounds of a ViewCell to hide the separator gap if there is an Accessory on the Cell.
- [Bug 43161  - Setting Accessory in ViewCellRenderer breakes layout] (https://bugzilla.xamarin.com/show_bug.cgi?id=43161)
None
[iOS] Custom ViewCells with Accessories may still have a gap between ListView cells even if SeparatorVisibility is set to none. See #217.
> [iOS] ViewCells with Accessories will be properly laid out again

- Xamarin.Forms.Platform.Android/Forms.cs
Android BeginInvokeOnMainThread() should not possibly block.
Android.App.Activity.RunOnUiThread() does not always run the argument
Runnable asynchronously; actually it is run synchronously if current
thread is the UI thread [1][2]
Use Handler.Post() instead. (It is also used in Android.App.SyncContext[3])
[\*1] https://developer.android.com/reference/android/app/Activity.html#runOnUiThread(java.lang.Runnable)
[\*2] http://stackoverflow.com/questions/33039600/android-runonuithread-not-async
[\*3] https://github.com/xamarin/xamarin-android/blob/5777337/src/Mono.Android/Android.App/SyncContext.cs#L15
> Android BeginInvokeOnMainThread() should not possibly block.

- Xamarin.Forms.Platform.Android/VisualElementPackager.cs
- Xamarin.Forms.Platform.Android/VisualElementTracker.cs
- Xamarin.Forms.Platform.WP8/VisualElementTracker.cs
- Xamarin.Forms.Platform.WinRT/VisualElementPackager.cs
Some implementations of `VisualElementPackager` and `VisualElementTracker` are marked public and aren't sealed, but don't implement the [Dispose pattern](https://msdn.microsoft.com/en-us/library/b1yfkh5e(v=vs.110).aspx) in a way which supports derived classes. This change updates those implementations to support derived classes.
> Implement dispose pattern correctly to support derived classes

- Xamarin.Forms.Controls/GalleryPages/XamlNativeViews.xaml
- Xamarin.Forms.Core.UnitTests/NativeBindingTests.cs
- Xamarin.Forms.Core/NativeBindingHelpers.cs
When creating the BP proxy, create it with the right type, and use the default value of the target property as default value for the BP
- fix binding to TextBlock.Text on UWP (you can't set Text to null)
It's been a long time since I've sent any PR during weekend. I think it classifies as a behavioral change. I'm quite interested about the final results of that transformation. It'll probably end up with the kids getting 2 xmas gifts.
> [C] specify type and default value for native bindings

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39489.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Maps.Android/MapRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/FragmentContainer.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/ViewRenderer.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
Fixes for several memory leaks on Android. Changes include:
- Calling Destroy() on Map during disposal (leaking the Map object)
- Cleaning up OnFocusChangeListener on ViewRenderer during disposal (leaking various renderers)
- Cleaning up listeners and tag on ButtonRenderer during disposal (leaking ButtonRenderer)
- Fixing bug where animated fragment transactions leaked FragmentContainer and PageContainer
- [39489 – [Android] Memory leak when using NavigationPage with Maps](https://bugzilla.xamarin.com/show_bug.cgi?id=39489)
- [40970 – Memory Leak in the Xamarin Forms Maps component on iOS](https://bugzilla.xamarin.com/show_bug.cgi?id=40970) (the Android parts)
None
None
> Fix several Android memory leaks

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41271.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/Cells/Cell.cs
- Xamarin.Forms.Platform.WinRT/CellControl.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Cell.xml
The `CellControl`'s `MeasureOverride` method will now return a non-zero height on the first pass so the `ListView` can estimate properly for UI virtualization. This will allow users to create `ListView`s without explicit heights set on the `Cell`s and without an explicit `RowHeight` and still take advantage of UI virtualization on Windows platforms.
There is also a sample reproduction for 41271 that demonstrates a workaround for the apparent memory leak that is caused by UWP's default behavior, which is to cache all pages loaded into a tabbed layout. This sample also serves as a manual test case for the UI virtualization, as each tab contains a `ListView` with 1000 items, yet a fraction of that are loaded into the visual tree.
- [Bug 38777  - Inserting 10000 items into ListView causes UWP …
> [UWP/WinRT] ListView UI virtualization works without explicit height on Cell/Row

- Xamarin.Forms.ControlGallery.Android/Activity1.cs
- Xamarin.Forms.ControlGallery.WP8/MainPage.xaml.cs
- Xamarin.Forms.ControlGallery.Windows/MainPage.xaml.cs
- Xamarin.Forms.ControlGallery.WindowsPhone/MainPage.xaml.cs
- Xamarin.Forms.ControlGallery.WindowsUniversal/MainPage.xaml.cs
- Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40911.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/ControlGalleryPages/NativeBindingGalleryPage.cs
- Xamarin.Forms.Controls/ControlGalleryPages/NestedNativeControlGalleryPage.cs
- Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
- Xamarin.Forms.Platform.Android/Platform.cs
- Xamarin.Forms.Platform.WP8/Platform.cs
- Xamarin.Forms.Platform.WinRT/Platform.cs
- Xamarin.Forms.Platform.iOS/Platform.cs
iOS Platform was using the current `Page`'s `RealParent` property to reach the current `Application` instance so it could set the `NavigationProxy.Inner` property during `ViewDidAppear`. But it's possible to have a situation where `ViewDidAppear` occurs while the current `Page` property is null (when setting the `MainPage` property from the native iOS app), which results in a NullReferenceException. Replaced the cast of `RealParent` with `Application.Current` to avoid the NRE.
Also updates the integration between the XF and native parts of Control Gallery to use MessagingCenter (and be less fragile).
- [40911 – NRE with Facebook Login](https://bugzilla.xamarin.com/show_bug.cgi?id=40911)
- [42214 – Project crashes with NRE in Main.cs - Xamarin …
> Fix potential NRE accessing current application via Page.RealParent

- Xamarin.Forms.Core/BindingExpression.cs
`BindingExpressionPart.Subscribe` clears out the previous subscription before applying the new one, which is a relatively expensive operation. This change avoids clearing and resubscribing if the new handler is the same as the old one.
> Don't unsubscribe/resubscribe the listener to the same INPC

- Xamarin.Forms.Platform.Android/Forms.cs
Currently, every time `Device.BeginInvokeOnMainThread()` is called on a Android device, a new instance of `Handler` is created to post the action to the main thread. This means that every time a bound property is changed, a new instance of `Handler` is created; this creates additional GC pressure, especially during floods of property changes. 
This change reuses the `Handler` each time rather than creating a new one, significantly reducing the number of objects allocated as a result of property changes.
> Reuse Handler when invoking on main thread

- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/SetValue.xaml
- Xamarin.Forms.Xaml.UnitTests/SetValue.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/X2009Primitives.xaml
- Xamarin.Forms.Xaml.UnitTests/X2009Primitives.xaml.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- Xamarin.Forms.Xaml/TypeConversionExtensions.cs
Support additional  builtin conversions for: `sbyte`, `uhort`, `uint`, `ulong` and `decimal`
Support additional Xaml2009 Language Primitives for `<x:SByte/>`, `<x:UInt16/>`, `<x:UInt32/>` and, wait for it, `<x:UInt64/>`.
Those primitives aren't part of the Xaml2009 specification (https://msdn.microsoft.com/en-us/library/ee792002(v=vs.110).aspx). We can now argue that the spec is wrong, and our implementation is right.
- http://stackoverflow.com/questions/39715592/how-to-put-a-uint-value-as-parameter-to-a-xaml-control
> [Xaml] more primitive types

- Xamarin.Forms.ControlGallery.Windows/CustomRenderers.cs
- Xamarin.Forms.ControlGallery.Windows/Xamarin.Forms.ControlGallery.Windows.csproj
- Xamarin.Forms.ControlGallery.WindowsPhone/CustomRenderers.cs
- Xamarin.Forms.ControlGallery.WindowsPhone/Xamarin.Forms.ControlGallery.WindowsPhone.csproj
- Xamarin.Forms.ControlGallery.WindowsUniversal/CustomRenderers.cs
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42602.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/VisualElementRenderer.cs
Can now use `ArrangeNativeChildren` option in Windows 8.1/UWP custom renderers to force native children of the View to be arranged.
- [Bug 42602  - Custom BoxView Renderer Does Not Render All Its Children Elements] (https://bugzilla.xamarin.com/show_bug.cgi?id=42602)
Added:
- `protected bool VisualElementRenderer.ArrangeNativeChildren { get; set; }`
If you opt in to the behavior on a renderer that has child renderers (e.g., a Page with a ListView on it), the child renderers can theoretically be arranged more than once, causing slightly increased load times.
> [Win] Will arrange native children of custom renderers (opt-in)

- Xamarin.Forms.Platform.WinRT.Phone/WindowsPhoneResourcesProvider.cs
Changes the Windows Phone RT platform resource lookup to get Setters from ancestor Styles in addition to the defined style.
Tests omitted because, as far as I can tell, testing the PlatformResourceProviders isn't possible.
- Part 1 of fixing [47873 - Most Device Styles do not render correctly in Windows Phone 8.1 (RT) applications](https://bugzilla.xamarin.com/show_bug.cgi?id=43783). Doesn't address the failure to lookup ThemeResources, however. Once that's addressed, will fix certain styles, such as the `BodyStyle`, which maps to the native `BodyTextBlockStyle`, which only directly defines a new `TextBlock.LineHeight` value. As Xamarin's style translation ignores that particular property, any Label using the Xamarin `BodyStyle` would get an unstyled Label, when they should, at the very …
> [Windows] Fix Device Style inheritance

- Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Controls/ControlGalleryPages/NativeBindingGalleryPage.cs
- Xamarin.Forms.Core/NativeBindingHelpers.cs
- Xamarin.Forms.Platform.iOS/Extensions/UIViewExtensions.cs
- Xamarin.Forms.Platform.iOS/NativeViewPropertyListener.cs
Keep our native property listener around the same time we keep our proxy, check if we are KVO compliant before adding observer
This fixes a crash when using NativeBinding 2-way without using a event. The KVO implementation wasn't ok, first we need to keep the observer around, nativePropertyListener, and we also need to make sure the a key for our property exists, normally it's a lowercase of XIOS public property. The only way was to catch the exception that the key wasn't found. 
Also added a example of how one can make a KVO compliant control to use 2 way binding in iOS without specifying the event.
> [iOS] Fixes KVO native binding

- Xamarin.Forms.Platform.Android/AppCompat/FragmentContainer.cs
When Android app was backgrounded or foregrounded, any page that implements `IPageContainer` was invoking appearing / disappearing methods for all pages on the stack. This change ensures that only the current page triggers its life cycle events. I'm not sure how `MasterDetailPage` behaves as I don't use it in my app, but this change should not break existing functionality.
In addition to this, I realized that if `MainPage` is set to a `ContentPage`, backgrounding / foregrounding the app does **NOT** raise appearing / disappearing events on the page. I will submit a bug in case this is a bug (not intended behavior) and needs to be fixed.
Possibly fixes:
- https://bugzilla.xamarin.com/show_bug.cgi?id=41322
- https://bugzilla.xamarin.com/show_bug.cgi?id=43815
I did not read the bug …
> [Android] Forward appearing / disappearing methods only for the last item on the stack

- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
Setting `InputTransparent="False"` does not work on Android if the background color is not set or if it is set to Transparent. The color must be set to a **non-transparent** color in order for taps not to propagate down. This change ensures for at least elements that use `VisualElementRenderer` that touch events are intercepted accordingly. Other renderers might have to do the same.
Another issue was `Grid`, `StackLayout`, and `ContentView` still participated in hit testing after `IsEnabled` is set to false.
This code takes care of both cases:
```
public override bool OnInterceptTouchEvent(MotionEvent ev)
{
if (Element.InputTransparent && Element.IsEnabled)
return false;
return base.OnInterceptTouchEvent(ev);
}
```
Note that parent elements do not push `IsEnabled` changes to their …
> [Android] InputTransparent and IsEnabled fixes on visual elements

- Xamarin.Forms.Platform.WinRT/ListViewRenderer.cs
In PR #241 some code was added for allowing ListView selection via the enter key. After the first selection was made with the key, it appeared that subsequent selections via mouse would cause a double firing of `ItemSelected`. This code can just be handled inside the `OnKeyPressed` method instead to prevent this.
https://bugzilla.xamarin.com/show_bug.cgi?id=44886
None
None
> [WinRT] Fix regression on ListView selection with enter key

- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
The use of `ViewStates.Gone` was not being taken into account when calculating the tab height in `OnLayout` in the AppCompat `TabbedPageRenderer` and as a result was always taking up space in the layout when it shouldn't be.
https://bugzilla.xamarin.com/show_bug.cgi?id=43108
None
None
> [A] Check for ViewStates.Gone in AppCompat TabbedPageRenderer

- Xamarin.Forms.Platform.Android.FormsViewGroup/Xamarin.Forms.Platform.Android.FormsViewGroup.csproj
Set the AndroidCodeGenTarget to XAJavaInterop1 to improve constructor performance in classes derived from FormsViewGroup.
> Set AndroidCodeGenTarget to XAJavaInterop1

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Fixes a regression introduced by [PR 360](https://github.com/xamarin/Xamarin.Forms/pull/360) where UserVisibleHint was set to false when a fragment was removed
None
None
None (restores the original, correct behavior)
> Set UserVisibleHint for new fragment to true

- Xamarin.Forms.Platform.Android/ViewRenderer.cs
Make CreateNativeControl virtual instead of abstract
None
Nothing in core. Android ViewRenderer now has default impl of CreateNativeControl
Old renderers which dont use this method no longer crash.
Fixes backwards compatibility issue.
> Make CreateNativeControl virtual instead of abstract

- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
#274 added call to ViewWillAppear of UITableViewController, but this seems to have broken iOS ListView scrollbar size when the soft keyboard disappears. I removed the base call though I'm not sure why this was necessary. We should either understand the root cause of the problem and invoke base ViewWillAppear or bypass this call as before.
- https://bugzilla.xamarin.com/show_bug.cgi?id=43993
> Fixed bug 43993 by removing call to base ViewWillAppear

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39768.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/InnerGestureListener.cs
Continuation of #313. Now sending the Started/Running events for Pan on Move event, which will allow Pan to function after a long press is detected without having to lift your finger. Previously, a long press would swallow the Scroll event, which gave the appearance that the Pan did not work when dragging very slowly.
- [Bug 39768  - PanGestureRecognizer sometimes won't fire completed event when dragging very slowly] (https://bugzilla.xamarin.com/show_bug.cgi?id=39768)
None
None
> [A] PanGestureRecognizer will consistently send Started/Move event

- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44166.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailContainer.cs
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Removes the current fragment when an AppCompat MasterDetailPageContainer is being disposed
- Unhooks the Drawer Listeners when disposing of a MasterDetailPageRenderer
- Nulls out the drawer listener for a NavigationPageRenderer that's being displayed by a MasterDetailPage
- Fixes a leak in the MDP custom renderer in the Control Gallery
- [44166 – MasterDetailPage instances do not get disposed upon GC; instance accumulation crashes app with OOM error using Forms 2.3.2.118-pre1 and AppCompat](https://bugzilla.xamarin.com/show_bug.cgi?id=44166)
None
None
- [] Changes adhere to coding standard
> Prevent MasterDetailPage and its components from leaking on Android

- Xamarin.Forms.Platform.WinRT.Phone/PhoneResources.xaml
Change incorrect property name `ToolbarVisibility` to `TitleVisibility`. 
- [45010 – Forms Sample "WorkingWithListview" throw exception with WinPhone8.1](https://bugzilla.xamarin.com/show_bug.cgi?id=45010)
> Update ToolbarVisibility to TitleVisibility in PhoneResources

- Xamarin.Forms.Controls/App.cs
- Xamarin.Forms.Controls/Bugzilla44596SplashPage.cs
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailContainer.cs
- Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
On Android, delay disposal of `PageRenderer`s to prevent a blank screen from appearing when the `MainPage` is switched to a `MasterDetailPage` containing a `TabbedPage` or `NavigationPage`. Also removing animation from above scenario.
Test is included, but must be uncommented in the App.cs.
- [Bug 44596 - Grey/Blank Screen when switching MainPage to MasterDetail with TabbedPage](https://bugzilla.xamarin.com/show_bug.cgi?id=44596)
None
None
> [A] Prevent blank page from appearing when MainPage is switched

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.iOS/packages.config
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39489.cs
- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Android.UITests/packages.config
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/packages.config
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/packages.config
Just trying to fix the remaining failure on IOS
> [UITest] Update to UItest beta 5, fix class naming

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39489.cs
UI Test for 39489 (originally an Android bug) doesn't run to completion on iOS devices; disabling the test for iOS temporarily while we work out what's going on with that platform.
> Temporarily disabling 39489 UITest on iOS

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40408.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT.Phone/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.WinRT.Tablet/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.WinRT/MasterDetailPageRenderer.cs
`MasterDetailPage` and `TabbedPage` in WinRT were only firing off the `Appearing` event once and not firing off `Disappearing` at all due to `OnUnloaded` being called after `Dispose`, always causing the `PageController` value to be null. If this is instead called before `SetElement(null)` in `Dispose` it allows the `Appearing`/`Disappearing` events to work as expected.
https://bugzilla.xamarin.com/show_bug.cgi?id=40408
None
None
> [WinRT] Fix MDP and TabbedPage Appearing/Disappearing

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44461.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs
iOS `ScrollView` was behaving differently than Android when using `ScrollToPosition` enums. If you center or end scroll the first element, iOS moves the scrollview out of place by setting the x position to a negative value. Similarly, if you start or center scroll the last element, the x position is set to a value greater than what should be allowed. This change ensures iOS and Android behave the same.
- https://bugzilla.xamarin.com/show_bug.cgi?id=44461
iOS is now more intelligent such that `ScrollView` elements are positioned without going out of bounds. Developers can still set to any position they want by using `ScrollToAsync(double x, double y, bool animated)`.
> iOS ScrollView should not scroll out of place on scrolling to element

- Xamarin.Forms.Platform.WinRT/FormsTextBox.cs
A System.ArgumentException was being thrown when trying to set the `InputScope` on a subsequent Entry control to `PasswordInputScope`. 
It looks like the same` InputScope` cannot be applied to multiple elements so this fix makes `PasswordInputScope` not static, which allows each Entry control to initialize its own if needed.
A similar report about this issue can be seen in the last few replies in [this thread](https://social.msdn.microsoft.com/Forums/en-US/24bec920-425b-4a9e-8a3e-be4417a2c5f4/ageruntimesetvalue-line-0-position-0?forum=wpdevelop).
- https://bugzilla.xamarin.com/show_bug.cgi?id=44679
- https://bugzilla.xamarin.com/show_bug.cgi?id=44954
None
None
> [Windows] Fix crash when toggling IsPassword on multiple Entry controls

- Xamarin.Forms.Core/OnIdiom.cs
The current implementation for OnIdiom<T> is missing the Desktop property. When running in a Windows UWP "desktop" app, it always returns the Phone property.
Added:
- Desktop property to OnIdiom
> OnIdiom support for Desktop (UWP)

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41153.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Only adding UI test for Bugzilla 41153. Actual bug was resolved by #331.
- [Bug 41153 - jobject must not be IntPtr.Zero with TabbedPage and ToolbarItems](https://bugzilla.xamarin.com/show_bug.cgi?id=41153)
None
None
> Add reproduction for Bugzilla 41153

- Xamarin.Forms.Platform.iOS/ContextActionCell.cs
Tapping on ListView with two/three fingers crashed iOS app when context action cells are used. This change ensures such taps are ignored. See the changes made in `static void Tapped(UIGestureRecognizer recognizer)`
~~Also made the following refactorings:~~
~~- static readonly field name change~~
~~- shorter getter~~
~~- object initialization~~
~~- convert to foreach loops~~
~~- ternary operator~~
- https://bugzilla.xamarin.com/show_bug.cgi?id=40263
> [iOS] Tapping on ListView with two fingers should not crash

- Xamarin.Forms.Build.Tasks/XamlGTask.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz43301.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz43301.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Prevent namespace collisions in XamlG, and prevent providing own extensions methods for LoadFromXaml and FindByName.
This PR replaces #390
~~https://bugzilla.xamarin.com/show_bug.cgi?id=44807~~
https://bugzilla.xamarin.com/show_bug.cgi?id=43301
> [XamlG] Fully qualify method names

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44166.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs
Fixes leaks preventing MasterDetailPage and its child pages from being garbage collected on iPad.
- [44166 – but on the iPad](https://bugzilla.xamarin.com/show_bug.cgi?id=44166)
None
None
> Fix MasterDetailPage/NavigationPage leaks on iPad

- Xamarin.Forms.Platform.WinRT/ImageRenderer.cs
I changed the type cast from BitmapImage to BitmapSource because if you want to do image manipulation, in UWP, you use the WriteableBitmap class.
This fixes the InvalidCastException which can result in the app crashing
None
None
> Modified type cast to appropriate type

- Xamarin.Forms.Platform.Android/Renderers/NavigationRenderer.cs
Check if PageController is null before calling it
https://bugzilla.xamarin.com/show_bug.cgi?id=44175
> [Android] Fix possible NRE when detaching NavigationPageRenderer

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44129.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
Ensure that the tab bar is updated before updating the pager which will attempt to then switch those tabs. If pager is empty it will attempt to switch to tab 0 when you add the first item to the view. This will result in a crash.
- https://bugzilla.xamarin.com/show_bug.cgi?id=44129
None
None
> [A]Don't crash when emptying/populating TabbedPage.ItemsSource

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40722.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/PlatformConfiguration/AndroidSpecific/AppCompat/Application.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.Android/AppCompat/FragmentContainer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific.AppCompat/Application.xml
- docs/Xamarin.Forms.Core/index.xml
- docs/Xamarin.Forms.Core/ns-Xamarin.Forms.PlatformConfiguration.AndroidSpecific.AppCompat.xml
Added Platform Specific feature to Android AppCompat that will allow users to disable Appearing and/or Disappearing events on Resume and Pause, respectively. Disabling these events will make the AppCompat event cycle match the pre-AppCompat event cycle. Events are enabled by default to preserve existing behavior for apps that rely on the events.
Users can disable the events using the following code:
```
using Xamarin.Forms.PlatformConfiguration;
using Xamarin.Forms.PlatformConfiguration.AndroidSpecific.AppCompat;
...
Application.Current.On<Android>()
.SendDisappearingEventOnPause(false)
.SendAppearingEventOnResume(false);
```
There is a manual test for this.
- [Bug 40722 - Using FormsAppCompatActivity calls OnDisappearing on device …
> [Android App Compat] Can opt out of sending Appearing/Disappearing events on Resume/Pause

- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
Instead of moving where we do the update and thus potentially side effect, just unhook from empty pagers to prevent confusing the tab layout when we blow away its tabs.
bugzilla.xamarin.com/show_bug.cgi?id=44129
None
> [A] Better fix for BZ44129

- Xamarin.Forms.Platform.Android/Platform.cs
Add a simple null check
None filed
None
None
Reproduction unknown, issue deduced from stack traces from HomeAway.
> [A] Prevent crash in event when renderer is null in Layout call.

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42832.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
This fixes an NRE that was being thrown when scrolling the ListView when an item with context actions was selected. It turns out this bit of code was being called after all contrary to the original comment.
- https://bugzilla.xamarin.com/show_bug.cgi?id=42832
None
Doesn't appear to be any. Removing the code doesn't seem to affect the cell rendering.
> [Android] Fix NRE When Scrolling ListView and Item With Context Actions Is Selected

- Xamarin.Forms.Core/Color.cs
Remove duplicate string replace call to replace the '#' a second time in Color.FromHex(). 
none
none
none
> Remove unnecessary string replace in Color.FromHex

- Xamarin.Forms.Platform.Android/Platform.cs
ActionBar may not be present in certain cases. For instance there is no ActionBar in full screen applications.
https://bugzilla.xamarin.com/show_bug.cgi?id=25677
https://forums.xamarin.com/discussion/55045/amazon-fire-tv-stick
None.
None except application now can work in a fullscreen mode.
The change works for me for a year now. As you can see from this code snippet
https://gist.github.com/gleblebedev/e89e1d77d76644142d44
I was modifying binary IL code to make the change because no source code was available. Since it's open source now I suggest to add it to repository.
> Check for Actionbar at UpdateActionBar method.

- Xamarin.Forms.Core/ViewExtensions.cs
When using Animation with Children animation, and doing easing at the top level, the Children are only animated from 0 to 1, so for Spring animation (going 0, -0.2, 1), the spring part of the animation is lost.
No test provided. that's Math, I can compute it all in my head up to the 5th decimal.
- https://bugzilla.xamarin.com/show_bug.cgi?id=44609
> [C] fix TranslateTo for easing going outside of (0,1)

- Xamarin.Forms.Platform.WinRT/NavigationPageRenderer.cs
Fixes the back button and navigation bar not being visible if the current page does not have title on Windows 8.1 projects.
- https://bugzilla.xamarin.com/show_bug.cgi?id=45255
None
None
> [WinRT] Fix back button not showing if current page has no title

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44044.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/TabbedPageAndroid.cs
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGallery.cs
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Core/PlatformConfiguration/AndroidSpecific/TabbedPage.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/TabbedPage.xml
- docs/Xamarin.Forms.Core/index.xml
There is an issue where some horizontal swipe gestures can get picked up by the TabbedPage in AppCompat. The bug filed used a drawable canvas as an example. By adding a Platform Specific feature for setting the paging functionality, this behavior can be easily adjusted to fit the individual user's needs.
https://bugzilla.xamarin.com/show_bug.cgi?id=44044
Added:
- public static readonly BindableProperty IsSwipePagingEnabledProperty
- public static bool GetIsSwipePagingEnabled(BindableObject element)
- public static bool IsSwipePagingEnabled(this IPlatformElementConfiguration<Android, FormsElement> config)
- public static IPlatformElementConfiguration<Android, FormsElement> SetIsSwipePagingEnabled(this IPlatformElementConfiguration<Android, FormsElement> config, bool value)
- public static …
> [Android] Add Platform Specific features for setting TabbedPage swipe paging and OffscreenPageLimit

- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/EntryPageiOS.cs
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGallery.cs
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Entry.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/Entry.xml
- docs/Xamarin.Forms.Core/index.xml
This PR adds a Platform Specific feature for setting the value of `AdjustsFontSizeToFitWidth` on `Entry` in iOS. From [Apple's docs](https://developer.apple.com/reference/uikit/uitextfield/1619625-adjustsfontsizetofitwidth):
> Normally, the text field’s content is drawn with the font you specify in the `font` property. If this property is set to `true`, however, and the contents in the `text` property exceed the text field’s bounding rectangle, the receiver starts reducing the font size until the string fits or the minimum font size is reached. The text is shrunk along the baseline.
N/A
Added:
- public static readonly BindableProperty AdjustsFontSizeToFitWidthProperty
- public static bool GetAdjustsFontSizeToFitWidth(BindableObject element)
- public static void …
> [iOS] Add Platform Specific feature for setting AdjustsFontSizeToFitWidth on Entry

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44584.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/EditorRenderer.cs
- Xamarin.Forms.Platform.WinRT/FormsTextBox.cs
Fixes disparity between the Editor and Entry controls on Windows with regard to background color when focused. The Entry preserves the background color set by the developer when it is focused; the Editor does not. This change makes the Editor behave like the Entry.
- [44584 – UWP - Editor: changing the background color will only take effect after the entry gained focus](https://bugzilla.xamarin.com/show_bug.cgi?id=44584)
None
None
…n Windows
> [Windows] Make Editor focused background color behavior consistent with Entry

- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
- Xamarin.Forms.Platform.Android/FormsApplicationActivity.cs
Can now use the Android Platform Specific `WindowSoftInputModeAdjust` in XAML and in constructor.
- n/a, reported internally
None
None
> [Android] SoftInputMode works with initial value

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41418.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UnitTests/ScrollViewUnitTests.cs
- Xamarin.Forms.Core/ScrollView.cs
`ScrollView` did not get the correct maximum height and width of its content and failed to show the correct content margin. If the content is 800 units tall with 200 units of vertical thickness, then `_content.Bounds.Bottom` returns 900 and `Top` is 100. 
We shouldn't ignore top and left positions as well as top and left paddings.
- https://bugzilla.xamarin.com/show_bug.cgi?id=41418
> ScrollView should account for Content margin

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44338.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/ContextScrollViewDelegate.cs
An issue in iOS 10 exists where if a context action is open, tapping off of it will cause a crash. In the [iOS 10 Release Notes](https://developer.apple.com/library/content/releasenotes/General/RN-iOSSDK-10.0/) it mentions the following:
> In iOS 10, there is a slight `UIGestureRecognizer` behavior change when removing a currently recognizing (that is, midflight) gesture recognizer from its view. Previously, removing the gesture recognizer midflight would not explicitly cancel the gesture recognizer, allowing you to re-add the gesture recognizer back to the same view or to a different view. In iOS 10, calling `removeGestureRecognizer:` on the view of a midflight gesture recognizer explicitly cancels the gesture recognizer. If a user desires to change the view of a midflight gesture …
> [iOS] Add check for UIGestureRecognizerState.Cancelled when closing a context action

- Xamarin.Forms.Core/PlatformConfiguration/WindowsSpecific/Page.cs
- Xamarin.Forms.Platform.UAP/MasterDetailControl.cs
- Xamarin.Forms.Platform.WinRT.Phone/FormsPivot.cs
- Xamarin.Forms.Platform.WinRT/PageControl.xaml.cs
Can now use the Windows Platform Specific ToolbarPlacement in XAML and in constructor.
- n/a, reported internally
None
None
> [Win] Toolbar placement works with initial value

- Xamarin.Forms.Platform.Android/Renderers/AHorizontalScrollView.cs
- Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
Android `ScrollViewer` is not forwarding touch events when they are caught by the nested horizontal scroll viewer. This PR will ask the nested item to forward its touch capture to the parent and ask it not to process the touch again. So, the touch bubbles up to the custom renderer and when it's back in the vertical scroll viewer, it won't go any further.
Just to add more, if scroll view orientation is vertical, touch events will be caught by the vertical (parent) scroll view. If horizontal, they will be forwarded. If bidirectional, depending on who captures the event, it will either be processed by the parent or forwarded to the parent.
- https://bugzilla.xamarin.com/show_bug.cgi?id=42883
Added:
- internal bool ShouldSkipOnTouch;
> [Android] Forward ScrollView touch events to custom renderers

- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
With AppCompat, changing the Title of a TabbedPage child Page would no longer update its tab text. This fixes that by wiring up to each child page's PropertyChanged event using the same mechanism as in the iOS TabbedRenderer in order to respond to the change. This also sets up the ability to respond to other child page property changes later if needed.
- https://bugzilla.xamarin.com/show_bug.cgi?id=43734
None
> Fixed tab not updating when page title is changed

- Xamarin.Forms.Platform.Android/Forms.cs
When we run under the context of layoutlib the `Context` object
that is created will not implement IDeviceInfoProvider. All this
means is that we will not get change notifications when the
orientation changes, but that's ok! This won't happen anyway.
If we instantiate the Device.Info object then everywhere else in
the code will be able to get access to the screen properties.
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=44893
> [Android] Always set a non-null Device.Info

- Xamarin.Forms.Platform.WinRT/FormsButton.cs
This fixes two issues introduced in #31:
1. The default background for a button is transparent
2. Background color set in a static resource style is ignored
When a FormsButton is first loaded, `BackgroundColor` will be null if the user did not set a color. In this case we will use the native control's `Background` instead as it will either be the default theme color or one from a style.
- https://bugzilla.xamarin.com/show_bug.cgi?id=42100
None
None
> [Windows] Fix Transparent Default Button

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla36788.cs
The UI test for 36788 is failing consistently on the first attempt as part of the whole UI test suite, possibly due to a device orientation change or larger screen sizes on some devices. This change makes the test function in both landscape and portrait mode on iPads as well as iPhones.
- Failing UI tests in the iOS lanes.
None
None
> Fix UI test for 36788

- Xamarin.Forms.Core.iOS.UITests/Tests/AutomationIDUITests.cs
The Automation ID UI tests are failing consistently in a couple of the lanes (notably iOS 8). This change addresses a couple of race conditions which can cause these tests to fail.
- Failing UI tests in iOS 8 lanes (and occasionally others)
None
None
> Fix possible race conditions in Automation ID tests

- Xamarin.Forms.Platform.WinRT/ActivityIndicatorRenderer.cs
It turns out that setting the `Foreground` of an indeterminate ProgressBar on Windows 8.1 simply does not work: https://social.msdn.microsoft.com/Forums/windowsapps/en-US/957b333f-035f-448e-9f4a-213d1290ee51/indeterminate-progressbar-foreground-dosent-work?forum=winappswithcsharp
You have to override the control's ProgressBarIndeterminateForegroundThemeBrush brush resource instead. Fortunately this can be done programmatically so users can dynamically change the color.
- https://bugzilla.xamarin.com/show_bug.cgi?id=45725
None
None
> [Windows] Setting ActivityIndicator.Color works now on W8.1

- Xamarin.Forms.Core/PlatformConfiguration/AndroidSpecific/AppCompat/Application.cs
- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific.AppCompat/Application.xml
Converting the work done in #441 to platform-specific functionality.
Added:
- public static readonly BindableProperty CanShowKeyboardOnResumeProperty
- public static bool GetCanShowKeyboardOnResume(BindableObject element)
- public static void SetCanShowKeyboardOnResume(BindableObject element, bool value)
- public static bool GetCanShowKeyboardOnResume(this IPlatformElementConfiguration<Android, FormsElement> config)
- public static IPlatformElementConfiguration<Android, FormsElement> CanShowKeyboardOnResume(this IPlatformElementConfiguration<Android, FormsElement> config, bool value)
EDIT: APIs were renamed to reflect `PreserveKeyboardOnResume`.
> [Android] Show keyboard on app resume if control has focus

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45743.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Platform.cs
Presently, calling `DisplayAlert` via `Device.BeginInvokeOnMainThread` prevents a subsequent use of `BeginInvokeOnMainThread` to do something such as push a new page prevents it from working. After doing some digging around, some [best practices](http://stackoverflow.com/questions/26554894/how-to-present-uialertcontroller-when-not-in-a-view-controller) Apple uses according to a reputable SO user suggests that they present a `UIAlertController` on a new `UIWindow`. Doing this appears to allow for such behavior to work as expected. DisplayActionSheet's behavior has been tweaked as well and to avoid repetition of code a `void PresentAlert(UIAlertController alert)` method was added.
https://bugzilla.xamarin.com/show_bug.cgi?id=45743
None
The DisplayAlert gallery appears to work as usual and a …
> [iOS] Use separate UIWindow for UIAlertController

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43663.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/Platform.cs
The `ModalPushed` and `ModalPopped` events were not firing on WinRT, which appears due to the `NavigationProxy.Inner` being assigned to `newRoot` and `page` values -- it appears that strictly leaving the value being assigned to `Application.Current` corrects this behavior (and Android/iOS both appear to set it similarly). The reproduction in the gallery checks the functionality while using other `NavigationProxy` functionality via `InsertPageBefore` to make certain it's still working after the changes, as well as inserting another page which unsubscribes from the added push/pop events when it appears.
https://bugzilla.xamarin.com/show_bug.cgi?id=43663
None
None
> [WinRT] Fix ModalPushed/ModalPopped not firing

- Xamarin.Forms.ControlGallery.WindowsUniversal/App.xaml
- Xamarin.Forms.ControlGallery.WindowsUniversal/App.xaml.cs
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.Platform.WinRT/Platform.cs
The mobile status bar appears as a blank white bar on version 14393 and a blank black bar on 10586 when the `RequestedTheme` is `Light`. This can be reproduced with a new UWP application independent of Xamarin.Forms. 
Since the `Light` theme should have a white bar with black text, we are now explicitly setting the status bar to be those colors. 
This is a VISUAL CHANGE on mobile devices targeting 10586, which would have a black status bar (with black text) in the Light theme. 
Users preferring the black status bar can explicitly change the status bar colors in `App.xaml.cs` `OnLaunched` in the UWP project. See a1e802e for a complete example.
- [Bug 45835 - There is a blank space on the screen top on UWP 14393(Windows 10 1607 Mobile)](https://bugzilla.xamarin.com/show_bug.cgi?id=45835) …
> [UWP] Explicitly set mobile StatusBar colors to white Background/black Foreground on Light theme

- Xamarin.Forms.Core/Frame.cs
- Xamarin.Forms.Platform.Android/AppCompat/FrameRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/FrameRenderer.cs
- Xamarin.Forms.Platform.WP8/FrameRenderer.cs
- Xamarin.Forms.Platform.WinRT/FrameRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Frame.xml
this replace #433 from @andreinitescu 
Added CornerRadius property to the Frame control to customize Frame's corner radius value.
N/A
Added:
- public float Frame.CornerRadius { get; set; } //Bindable Property
- public static readonly BindableProperty Frame.CornerRadiusProperty;
The property default value ensures the appearance of the Frame control in current apps remains unchanged.
> Frame CornerRadius

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla46494.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
If you create a `MasterDetailPage` where its detail is set to a `NavigationPage` or any other page wrapped in a fragment container and when you hit the back button to go to home screen, destroying current activity can run into a race condition such that the fragment is attempted to be destroyed after the activity is gone.
We should invoke base activity destroy only after our resources are destroyed.
Note that the test case does not work with the gallery app since the back button dismisses the MDP UI instead of sending you home. 
Ref #444
- https://bugzilla.xamarin.com/show_bug.cgi?id=46494
> [Android] Disposing MasterDetailPage when Detail has a FragmentContainer should not crash

- Xamarin.Forms.ControlGallery.iOS/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla36802.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/ContextActionCell.cs
On iOS, when a ListView is using RecycleElement along with GroupShortNameBinding, the UITableViewCellAccessory of a cell is partially hidden underneath the section index list.
Since `ContextActionCell.ContentView.Bounds` factors in the index list, this fix adjusts the width of the cell's contents to match the ContentView width so the AccessoryView is completely visible
- https://bugzilla.xamarin.com/show_bug.cgi?id=36802
None
None
> [iOS] Fix AccessoryView covered by section index list

- Xamarin.Forms.Core.UnitTests/BindableObjectUnitTests.cs
- Xamarin.Forms.Core/BindableObject.cs
- Xamarin.Forms.Core/Element.cs
If you put a view model locator as an App resource and set your binding context in MainPage, the locator gets called multiple times. This happens first when XAML for the main page is being loaded and then when the page is being parented by App.
This PR ensures that binding context changes are not made if the inherited context is the same as the value passed to `SetInheritedBindingContext()`
- https://bugzilla.xamarin.com/show_bug.cgi?id=45557
> BindingContext changes are called multiple times on app start

- Xamarin.Forms.ControlGallery.iOS/Info.plist
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/MasterDetailPageiOS.cs
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/NavigationPageiOS.cs
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/TabbedPageiOS.cs
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGallery.cs
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Page.cs
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/StatusBarHiddenMode.cs
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/UIStatusBarAnimation.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.iOS/Platform.cs
- Xamarin.Forms.Platform.iOS/PlatformRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PhoneMasterDetailRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/Page.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/StatusBarHiddenMode.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/UIStatusBarAnimation.xml
This is a Platform Specific feature which enables setting the visibility of the iOS status bar on a per-view basis. See some examples below:
This is accomplished through the `StatusBarHiddenMode` and `UIStatusBarAnimation` enumerators, which contain the following values:
`StatusBarHiddenMode.Default`
`StatusBarHiddenMode.True`
`StatusBarHiddenMode.False`
`UIStatusBarAnimation.None`
`UIStatusBarAnimation.Fade`
`UIStatusBarAnimation.Slide`
Per [Apple's documentation](https://developer.apple.com/reference/uikit/uiviewcontroller/1621440-prefersstatusbarhidden), since iOS 8 the `prefersStatusBarHidden` method returns true on vertically compact environments. This represents the `StatusBarHiddenMode.Default` value, while the latter two apply the respective values to both the vertical and …
> [iOS] Add Platform Specific features for PrefersStatusBarHidden/UIStatusBarAnimation

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44476.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailPageRenderer.cs
Additional top padding was being added onto a MasterDetailPage's detail when inside of a NavigationPage in AppCompat, presumably from the calculations that the NavigationPage itself was already doing. This additional status bar height being set as padding can be avoided by checking to see if the parent is a NavigationPage or not.
Gallery reproduction added, although it's a visual issue.
https://bugzilla.xamarin.com/show_bug.cgi?id=44476
None
None
> [A] Check for parent NavigationPage when setting MDP detail's TopPadding

- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
The mono compiler is giving us a CS0121 error where none should exist; switching from extension method syntax to static method syntax for now to work around it.
> Use static method syntax to prevent mono compiler error

- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Build.Tasks/XamlGTask.cs
- Xamarin.Forms.Xaml/Xamarin.Forms.Xaml.csproj
- Xamarin.Forms.Xaml/XamlCompilationAttribute.cs
- Xamarin.Forms.Xaml/XamlFilePathAttribute.cs
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml/XamlFilePathAttribute.xml
- docs/Xamarin.Forms.Xaml/index.xml
[XamlC] use correct filePath for XamlC error reporting.
Instead of using the resourceName, report build errors with the file name so you can click on the error on the IDE and get directly to the right xaml file and the faulty position.
- I do not fix bugs, I create them
Added:
- public class XamlFilePathAttribute
Ponies, rainbows, UNICORNS
> [XamlC] use correct filePath for XamlC error reporting

- Xamarin.Forms.Core.UnitTests/PickerTests.cs
- Xamarin.Forms.Core/Picker.cs
- Xamarin.Forms.Platform.Android/AppCompat/PickerRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/PickerRenderer.cs
- Xamarin.Forms.Platform.WP8/PickerRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Picker.xml
This PR includes and replace #296 by @joacar
None
Added:
public static readonly BindableProperty Picker.ItemsSourceProperty;
public static readonly BindableProperty Picker.SelectedItemProperty;
public BindingBase Picker.ItemDisplayBinding { get; set;}
public IList ItemsSource { get; set; }
public object SelectedItem { get; set; }
None
> Bindable picker

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla37431.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44777.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/NavigationPage.cs
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/StatusBarTextColorMode.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/NavigationPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/StatusBarTextColorMode.xml
- docs/Xamarin.Forms.Core/index.xml
[iOS] Add Platform Specific option to not adjust the status bar text color based on the luminosity of the NavigationBar text color.
Please note that this PR provides an opt-in override for the behavior described in the following bug reports. Users must call `NavigationBar.SetStatusBarTextColorMode(StatusBarTextColorMode.DoNotAdjust)` to override the automatic text color adjustment.
- [Bug 37431 - NavigationRenderer sets Status Bar Style arbitrarily](https://bugzilla.xamarin.com/show_bug.cgi?id=37431)
- [Bug 44777 - BarTextColor changes color for more than just the Navigation page](https://bugzilla.xamarin.com/show_bug.cgi?id=44777)
Added:
- `NavigationBar.On<iOS>().GetStatusBarTextColorMode()`
- …
> [iOS] Add Platform Specific option to not adjust the status bar text color based on the luminosity of the NavigationBar text color

- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailContainer.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Proposing this as an alternative to [PR 444](https://github.com/xamarin/Xamarin.Forms/pull/444)
PR 444 is adding a Platform Specific to NavigationPage which allows the developer to disable the default Android state loss check when committing a fragment transaction. 
The state loss check prevents unexpected behavior when restoring the state of fragments upon resuming an application. However, XF doesn't support fragment restoration at this time. So rather than add another Platform Specific which we have to maintain, we can simply change from `Commit()` to `CommitAllowingStateLoss()`. 
This PR also addresses a similar issue with MasterDetailPage, which also utilizes fragments (and thus transactions) when setting the master to detail to a NavigationPage or TabbedPage.
> Make CommitAllowingStateLoss the default for FragmentTransactions

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
When page orientation is changing, AppCompat `Toolbar` is being destroyed and rebuilt. However, this results in old values not being preserved if they cannot be replicated from other elements.
- https://bugzilla.xamarin.com/show_bug.cgi?id=46938
> [Android] Preserve Toolbar Subtitle on page orientation change

- Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs
iOS `TabbedRenderer` is setting `UITabBarItem` in two different places, which introduces multiple points of maintenance and inconsistency. This PR creates a method to set tab bar items consistently. It sets `Tag` (which was being set in one place) and `AccessibilityIdentifier` (enhancement) in each case. 
- https://bugzilla.xamarin.com/show_bug.cgi?id=41219
> [iOS] TabbedRenderer should set UITabBarItem properly

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla35736.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
Setting a similar behavior on `Editor` as with `Entry` for iOS due to the autocorrect suggestions updating the `Control.Text` but not the `Element.Text` value.
https://bugzilla.xamarin.com/show_bug.cgi?id=35736
None
None
> [iOS] Update Editor text from autocorrect when losing focus

- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/EntryPageiOS.cs
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/TabbedPageAndroid.cs
- Xamarin.Forms.Core/PlatformConfiguration/AndroidSpecific/TabbedPage.cs
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Entry.cs
- Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/TabbedPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/Entry.xml
Renaming of some platform specifics stuff per @davidbritch's request -- namely `AdjustsFontSizeToFitWidth` to `IsAdjustsFontSizeToFitWidthEnabled` and `SetOffscreenPageLimitProperty`  to `SetOffscreenPageLimit`.
Edit: Updated to only use the latter.
N/A
See description changes.
N/A
> Platform specifics naming adjustments

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla46630.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/CellAdapter.cs
Input views do not trap long clicks to show their editor context menus. Instead, cell context actions are shown. Please let me know if this needs to be a platform specific option or default expected behavior.
P.S. There seems to be an issue with `SearchBar` not getting focus when placed in a cell. When testing the sample code, make sure to give focus to other input views before long clicking `SearchBar`. There should be another bug for this.
- https://bugzilla.xamarin.com/show_bug.cgi?id=46630
> [Android] Do not show cell context actions if input views are long clicked

- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
We are reverting this change as it's throwing an exception when popping a page.
I think it's missing some code from my initial implementation, i remember some of it but need more time to figure it out. 
This means i need to look again to:
https://bugzilla.xamarin.com/show_bug.cgi?id=39908
https://bugzilla.xamarin.com/show_bug.cgi?id=42341
https://bugzilla.xamarin.com/show_bug.cgi?id=46195
> [iOS] Revert changes in popping navigation

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
- Xamarin.Forms.Core.iOS.UITests/BaseTestFixture.cs
Restarts the application if the navigation fails because of a Test Cloud issue (e.g., server issues on the device).
> Adding some restart logic to the UI tests if navigation fails

- Xamarin.Forms.Maps.UWP/MapRenderer.cs
Add location tracker for UWP maps. Every 15 seconds we will update the users location.
- Private report
None
When walking around while using a uwp app the user location dot will now follow the user.
> [UWP]Track user location when IsShowingUser enabled

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
- Xamarin.Forms.Core.iOS.UITests/BaseTestFixture.cs
- Xamarin.Forms.Platform.iOS/Platform.cs
Fix the iPad version of the issues addressed with [PR 543](https://github.com/xamarin/Xamarin.Forms/pull/543).
- Can't dismiss action sheets on iPad
> Fix broken alerts for iPad

- Xamarin.Forms.Core/MessagingCenter.cs
- Xamarin.Forms.Pages/DataSourceBinding.cs
- Xamarin.Forms.Platform.WP8/NavigationMenuRenderer.cs
When using `WeakReference`, one should not rely on `IsAlive` when it returns true as it could mean one of two things and we don't know which one. For more info, see bug description as well as the links in it.
It appears that XF is using a mix of `WeakReference` (.NET 1.1) and `WeakReference<T>` (4.5). For future references, `WeakReference` should probably be banned from being used.
- https://bugzilla.xamarin.com/show_bug.cgi?id=47203
> Fix weak references when getting targets

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla48158.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/BoxRenderer.cs
- Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs
We shouldn't override DrawRect, this method should only used when we  want to provide full implementation of what we are drawing on the screen. Since we provide a some information to the UIView Layer directly in out tracker update method, overriding this method prevents IOS of passing the info to the Layer properly . 
So this fix avoids that by configuring without overriding any Draw methods.
- https://bugzilla.xamarin.com/show_bug.cgi?id=48158
None
> [iOS] Avoid using DrawRect on base VisualElementRenderer

- Xamarin.Forms.Platform.Android/VisualElementPackager.cs
When `VisualElementPackager` is disposing itself, it doesn't check if its element is null. You could run the attached repro in the bug description and see that the user is nullifying `Element` and then disposing the packager.
```
protected override void Dispose(bool disposing)
{
if (disposing)
{
this.SetElement((VisualElement) null);
if (this.Packager != null) {
// exception
this.Packager.Dispose ();
this.Packager = null;
}
this.Tracker.Dispose();
this.Tracker = (VisualElementTracker) null;
}
base.Dispose(disposing);
}
```
This change is in line with the UAP counterpart. iOS side doesn't use `Element` after setting it to null.
P.S. I'm not sure why iOS seems to be the only platform that sets `Element` to null. Was this on purpose?
- https://bugzilla.xamarin.com/show_bug.cgi?id=39228
> [Android] Fix NRE in packager dispose

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz47950.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz47950.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Unreported004.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Unreported005.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Unreported005.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
see the title, there ^^^
note: this might be a slight regression, but implementing `IMarkupExtension<T>` is a valid workaround
- https://bugzilla.xamarin.com/show_bug.cgi?id=47950
- https://forums.xamarin.com/discussion/83236/no-property-bindable-property-or-event-found-for-yconstraint-after-update-to-forms-2-3-3-168
> [XamlC] support non-generic IMarkup on ABPs

- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz48554.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz48554.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Unreported006.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Unreported006.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] assigned derived type to generic BP
This isn't ironclad fix, but does the job for the reported case
Note: possible regression on 2.3.3
- https://forums.xamarin.com/discussion/comment/236161/#Comment_236161
- https://bugzilla.xamarin.com/show_bug.cgi?id=48554
> [XamlC] assigned derived type to generic BP

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla47971.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UnitTests/CommandTests.cs
- Xamarin.Forms.Core/Command.cs
On WinRT/UWP during the process of binding, items in a `ListView` initially inherit the binding context of the `ListView` before getting a more specific binding context. If the `DataTemplate` of the `ListView` includes an item which has both 
- a bound `Command` which includes a `CanExecute` method and
- a bound `CommandParameter`
the initial binding of the item will trigger a check on the `CanExecute` method (to determine if `IsEnabled` should be true). The `CanExecute` method attempts to cast the binding context to the correct type and throws an `InvalidCastException`. The `InvalidCastException` is not fatal, but it causes the rest of the `DataTemplate` binding to fail, and the `ListView` items will appear blank (though in the most recent version of XF they are still tappable). 
This …
> Don't run Command CanExecute on incorrect inherited binding context type

- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/SetValue.xaml
- Xamarin.Forms.Xaml.UnitTests/SetValue.xaml.cs
When we did the change to compile the enums, vs parsing them at runtime, we thought that supporting int-based enums was enough. The rationale behind this ? Well, except for interrop or maybe serialization, there's no real reason to use other than ints enums.
- the one @jonathanpeppers reported to me by email. No, not this one. The other below. Yeah, THAT is the one I'm speaking about.
> [Xaml] support non-int enums

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Core/ConstraintTypeConverter.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Unreported007.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Unreported007.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/SetValue.xaml
- Xamarin.Forms.Xaml.UnitTests/SetValue.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/XStatic.xaml
- Xamarin.Forms.Xaml.UnitTests/XStatic.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Align XamlC with Xaml capabilities.
More conversions are possible, and coming, but this PR only address the regression
- https://bugzilla.xamarin.com/show_bug.cgi?id=48242
> [XamlC] use op_implicit where we should

- .nuspec/Xamarin.Forms.nuspec
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/NavigationPageWindows.cs
- Xamarin.Forms.Platform.UAP/FormsCommandBar.cs
- Xamarin.Forms.Platform.UAP/FormsCommandBarStyle.xaml
- Xamarin.Forms.Platform.UAP/MasterDetailControl.cs
- Xamarin.Forms.Platform.UAP/MasterDetailControlStyle.xaml
- Xamarin.Forms.Platform.UAP/PageControlStyle.xaml
- Xamarin.Forms.Platform.UAP/Resources.xaml
- Xamarin.Forms.Platform.UAP/TabbedPageStyle.xaml
- Xamarin.Forms.Platform.UAP/ToolbarPlacementHelper.cs
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
- Xamarin.Forms.Platform.WinRT.Phone/FormsPivot.cs
- Xamarin.Forms.Platform.WinRT/PageControl.xaml.cs
This is an alternate solution to [PR 582](https://github.com/xamarin/Xamarin.Forms/pull/582) - that PR fixes the problem in [47295](https://bugzilla.xamarin.com/show_bug.cgi?id=47295) but introduces an issue where the Command Bar expands unevenly with the Title on Navigation and Master Detail pages.
This change merges the Command Bar and Title areas of the Navigation, Tabbed, and Master Detail pages when Command Bar is placed at the top of the application so that expansion of the Command Bar also applies to the Title area. The Command Bar height is no longer hard-limited to the Title Bar Height property, allowing it to expand to display the command labels.
This change also consolidates the toolbar placement management into a single helper class to make future maintenance easier.
No …
> Allow CommandBar to expand and show command labels

- Xamarin.Forms.Platform.iOS/Platform.cs
The method of handling Action Sheets and Alerts introduced by PR 481 doesn't work properly on iOS 8; this change restores the old functionality for iOS 8 while preserving the new functionality for iOS 9 and up.
- Action Sheet and Alerts completely non-functional in iOS 8
None
None
> Restore old Alert/ActionSheet method for iOS 8

- Xamarin.Forms.Platform.UAP/FormsPresenter.cs
- Xamarin.Forms.Platform.UAP/PageControlStyle.xaml
- Xamarin.Forms.Platform.UAP/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.UAP/TabbedPageStyle.xaml
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
On mobile, the CommandBar was covering the content inside a NavigationPage because the container area was not being updated after the CommandBar was moved to the bottom of the screen. 
The TabbedPage didn't have this issue as it used a TabbedPagePresenter to respond to the size change so I copied that code to a more generally named FormsPresenter class and used it also for the PageControl used by the NavigationPage renderer.
- https://bugzilla.xamarin.com/show_bug.cgi?id=48726
None
None
> [UWP] Fix CommandBar Overlaying NavigationPage Content

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla29110.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/SliderRenderer.cs
The Slider control has an odd behavior when centered via `VerticalOptions` and wasn't looking truly centered, like this:
Making adjustments to `ArrangeOverride` at an initial glance didn't seem to do enough, even when setting `VerticalAlignment` (although this was needed for cases where a `MinimumHeightRequest` was set, since as it exists it wasn't close to centering at all) so there was always a few pixels' difference as shown above. There is a slight difference in the default template between 8.1 and UWP templates so a slight adjustment using the `Margin` has been added depending on the platform so the result looks like this on each:
https://bugzilla.xamarin.com/show_bug.cgi?id=29110
None
Sliders were not centering as mentioned when a minimum height was specified so in those cases the …
> [WinRT/UWP] Adjust margin for centered Slider

- Xamarin.Forms.Core.UnitTests/ResourceDictionaryTests.cs
- Xamarin.Forms.Core/ResourceDictionary.cs
- Xamarin.Forms.Core/ResourcesExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/TestSharedResourceDictionary.xaml
- Xamarin.Forms.Xaml.UnitTests/TestSharedResourceDictionary.xaml.cs
- Xamarin.Forms.Xaml/MarkupExtensions/StaticResourceExtension.cs
Fix the ResourceDictionary interface. Some calls were using the RD values, some others were merging with the merged instance.
Now, all public API only poke the current RD.
StaticResource and implicit styles use an internal API.
This replaces #317.
- https://bugzilla.xamarin.com/show_bug.cgi?id=42264
minor
> ResourceDictionary fixes

- Xamarin.Forms.Platform.Android/Renderers/TableViewModelRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/TableViewRenderer.cs
When a TableSection has no header, then iOS doesn't render a header cell. Android rendered an empty TextCell and a separator line in the accent color. This could not be removed by the user.
With this change, the empty TextCell and the separator are not rendered. If you still want them, then you can set the Title to " ".
When I debugged the GetCellForPosition method, I saw that it was called very often. Before a TableView was rendered, the method was called twice for each Cell from GetView and twice for each Cell from IsEnabled. I removed one call from GetView, but IsEnabled is called twice from the adapter. I think the result of GetCellForPosition should be cached in a Cell[] or WeakReference<Cell>[] and two bool[] for isHeader and nextIsHeader. Then it would not have to iterate over all …
> Don't render empty TextCells for TableSections without Title (bugs 26104 and 42926)

- Xamarin.Forms.Platform.WinRT/NavigationPageRenderer.cs
Moved the change that was in #518 to a separate PR for clarity. On WinRT, the previous page value will no longer be stored when popping.
https://bugzilla.xamarin.com/show_bug.cgi?id=45593
None
None
> [WinRT] Do not store previous page when popping

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41415.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UnitTests/ScrollViewUnitTests.cs
- Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
Android `ScrollView` was incorrectly sending `ScrollX` and `ScrollY` values when scroll orientation was `Both`. This is because a horizontal scrollview is a child of a vertical scrollview and they are raising scroll events independently of each other. The user saw alternating 0 values for both positions.
This should send the final `ScrollX` and `ScrollY` to Core with every position update.
**EDIT:**
While testing horizontal + vertical scrolling, I discovered a bug. `ScrollToAsync()` method did not work when orientation was set to `Both`. Maybe I should have created a bug report for this and submitted it in a new PR. However, the fix works nicely with the fix for this bug. See the switch blocks for proper scroll calls. I also added a unit test to watch out for possible incorrect animation …
> [Android] ScrollView should send correct ScrollX and ScrollY

- Xamarin.Forms.Core/Page.cs
if you push a page on the navigation stack on device orientation change, this will crash because we are trying to update the element children collection while `foreach` is in progress during a layout cycle. There is a repro attached to the bug description.
- https://bugzilla.xamarin.com/show_bug.cgi?id=42651
> [iOS] Fix crash when pushing page on stack on orientation change

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla36846.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/CellAdapter.cs
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
If a `ListView` cell is removed from the items source and its context menu was visible, the menu stayed visible. This PR will close the context menu when the cell is no longer available.
- https://bugzilla.xamarin.com/show_bug.cgi?id=36846
> [Android] Dismiss context menu when view cell is removed

- Xamarin.Forms.Core.UnitTests/BehaviorTest.cs
- Xamarin.Forms.Core/BindableObject.cs
- Xamarin.Forms.Core/VisualElement.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/VisualElement.xml
Detach Triggers and Behaviors on VE finalizer, because they're not IDisposable...
- https://bugzilla.xamarin.com/show_bug.cgi?id=44074
> [C] detach Behaviors and Triggers on VE finalization

- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/SetValue.xaml
- Xamarin.Forms.Xaml.UnitTests/SetValue.xaml.cs
- Xamarin.Forms.Xaml/TypeConversionExtensions.cs
one might, at some point, find that capability useful.
> use op_implicit defined on Target

- Xamarin.Forms.Platform.iOS/Platform.cs
The original fix for [45743](https://bugzilla.xamarin.com/show_bug.cgi?id=45743) did not work for iOS 8 - action sheets and alerts were displayed smashed up against the top left corner of the screen (instead of full screen as intended). This fix addresses that bug for iOS 8.
- [45743 – Threading problem with PushAsync() after DisplayAlert() on iOS](https://bugzilla.xamarin.com/show_bug.cgi?id=45743)
None
None
> Fix for 45743 which works with iOS 8

- Xamarin.Forms.Platform.iOS/ContextActionCell.cs
- Xamarin.Forms.Platform.iOS/Forms.cs
- Xamarin.Forms.Platform.iOS/Platform.cs
- Xamarin.Forms.Platform.iOS/Renderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/CarouselPageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/FontExtensions.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PhoneMasterDetailRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TableViewModelRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TableViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs
- Xamarin.Forms.Platform.iOS/ResourcesProvider.cs
Deprecating iOS 8 and earlier by removing usage of `IsiOS7OrNewer` `IsiOS8OrNewer` (and since we're now always on iOS 9+, `IsiOS9OrNewer` shouldn't be needed either).
You were good operating system versions, but alas, your time has come. RIP.
N/A
N/A
Stuff not on iOS 9 or newer can and will likely blow up.
> Deprecate iOS 8 and earlier

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz46921.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz46921.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] support setting values on ValueTypes
- https://bugzilla.xamarin.com/show_bug.cgi?id=46921
> [XamlC] support setting values on ValueTypes

- Xamarin.Forms.Build.Tasks/CompiledConverters/ThicknessTypeConverter.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Core/ThicknessTypeConverter.cs
- Xamarin.Forms.Xaml.UnitTests/CompiledTypeConverter.xaml
- Xamarin.Forms.Xaml.UnitTests/CompiledTypeConverter.xaml.cs
[XamlC] compile ThicknessTypeConverter
> [XamlC] compile ThicknessTypeConverter

- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Xaml.UnitTests/I8.xaml
- Xamarin.Forms.Xaml.UnitTests/I8.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/MockCompiler.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] fix loading ulongs, optimize bytecode for longs
The code had a casting issue while generating IL for ulongs.
This patches, in addition to fix the issue, also optimize `ldc.i8` calls by 3 to 7B (from an original 9B) when the [u]long being loaded fits an int.
This optimization has been send to upstream as well https://github.com/jbevain/cecil/pull/307
> [XamlC] fix loading ulongs, optimize bytecode for longs

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz49307.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz49307.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml.Xamlc/Xamarin.Forms.Xaml.Xamlc.csproj
This doesn't happen often, and I haven't found any valid XAML file out
there requiring this, but in the case of 49307, it at least generates
valid IL, which then fails with a NRE as this is the nature of callvirt.
- generate valid IL for https://bugzilla.xamarin.com/show_bug.cgi?id=49307
> [XamlC] Box valueTypes on Add()

- Xamarin.Forms.Build.Tasks/MethodBodyExtensions.cs
- Xamarin.Forms.Xaml.Xamlc/Xamarin.Forms.Xaml.Xamlc.csproj
replace (2 to 6B)
```
ldloc x
stloc x
```
by (1 to 4B)
```
dup
stloc x
```
this gain is quite small (~1%)
require #611 and #612 
The current tests are covering this already
> Optimize stlod ldloc

- Xamarin.Forms.Build.Tasks/CompiledConverters/RectangleTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/TypeTypeConverter.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Core/TypeTypeConverter.cs
- Xamarin.Forms.Xaml.UnitTests/StringLiterals.xaml
- Xamarin.Forms.Xaml.UnitTests/StringLiterals.xaml.cs
[XamlC] Compile TypeTypeConverter
this is a huge improvements it:
- reduce the code size (e.g the StyleTests.InitializeComponent shrunk down to 3545 from 4104)
- do not resolve types at runtime as it's expensive and involve reflection
there's no new tests, this is already covered
> [XamlC] Compile TypeTypeConverter

- Xamarin.Forms.Build.Tasks/MethodBodyExtensions.cs
Remove unused local variables
This removes 2 variables and 4 instructions (4 to 12B) each time we use a ServiceProvider.
e.g., in StylesTests, it saves 14 variables and 72B of code.
> [Xamlc] remove unused locals

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43313.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Modifies the ListViewRenderer and UnevenListViewDataSource to return an estimated row height of zero when the cell heights are known. This prevents iOS from attempting to use row height estimates unnecessarily, which causes scrolling issues (especially if the specified cell heights are very different from the minimum measured cell heights). 
There are tests for both estimated row height and known row height, but they are not automated (nothing in the UI test platform for detecting this sort of thing).
- [43313 – Adding an item to ListView ItemSource has unexpected animation with different height rows and HasUnevenRows is true](https://bugzilla.xamarin.com/show_bug.cgi?id=43313)
- [44830 – ListView not consistently focusing at the end of the …
> Disable using EstimatedRowHeight for uneven rows with known heights

- Xamarin.Forms.Build.Tasks/BindablePropertyReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/BindablePropertyConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledValueProviders/ICompiledValueProvider.cs
- Xamarin.Forms.Build.Tasks/CompiledValueProviders/SetterValueProvider.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Core/Setter.cs
`IValueProvider`s tagged with the appropriate attribute will be bypassed
and the compiled version, if found, will be used.
This first version contains a compiled version of Setter's
IValueProvider and it already reduces the amount of generated IL by 39%
in, e.g. StyleTests.
It's a huge gain because XamlC no longer have to generate
ServiceProviders for those, so the methodbody is smaller, takes less
time to jit, less time to execute and nothing is invoked at runtime,
which probably saves a tons of time as well, as most IValueProvider
implementation heavily uses reflection.
> [XamlC] Allow compilation of IValueProviders

- Xamarin.Forms.Platform.iOS/ContextActionCell.cs
- Xamarin.Forms.Platform.iOS/Forms.cs
- Xamarin.Forms.Platform.iOS/Platform.cs
- Xamarin.Forms.Platform.iOS/Renderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/CarouselPageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/FontExtensions.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PhoneMasterDetailRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TableViewModelRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TableViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs
- Xamarin.Forms.Platform.iOS/ResourcesProvider.cs
Same as last pr, but leaves iOS 9 checks in place and fixes some if statements that were improperly resolved.
None
None
Older iOS versions continue to be unsupported.
> Deprecate versions of iOS older than 8

- Xamarin.Forms.Core/Device.cs
- Xamarin.Forms.Core/OnPlatform.cs
- Xamarin.Forms.Core/PlatformConfiguration/ExtensionPoints.cs
- Xamarin.Forms.Core/TargetPlatform.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration/Tizen.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Device.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/OnPlatform`1.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/TargetPlatform.xml
- docs/Xamarin.Forms.Core/index.xml
This PR is introduce to Tizen as a TargetPlatform.  `TargetgetPlatform.Tizen` indicates that forms is running on the Tizen Platform.
- None
Added:
- TargetPlatform.Tizen // enum
- T OnPlatform<T>.Tizen { get; set; }
- static void Device.OnPlatform (Action iOS, Action Android, Action WinPhone, Action Default, Action Tizen)
- static T Device.OnPlatform<T> (T iOS, T Android, T WinPhone, T Tizen)
- sealed class Xamarin.Forms.PlatformConfiguration.Tizen : IConfigPlatform
- None
> Add Tizen to TargetPlatform

- Xamarin.Forms.ControlGallery.Android/Resources/layout/Layout38989.axml
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.Android/_38989CustomRenderer.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla38989.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ConditionalFocusLayout.cs
Offering this as an alternative to https://github.com/xamarin/Xamarin.Forms/pull/567
This version is concise and avoids the two potential NRE situations created by checking the nullable result against 0.
- [38989 – [Android] NullReferenceException when using a custom ViewCellRenderer](https://bugzilla.xamarin.com/show_bug.cgi?id=38989)
None
None
> Fix potential NRE in ConditionalFocusLayout

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43469.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/Platform.cs
Calling `DisplayAlert` to show multiple dialogs would cause a crash. According to [this StackOverflow question](http://stackoverflow.com/questions/29209954/multiple-messagedialog-app-crash) it appears that there cannot be multiple MessageDialogs. Per the answer there, the dialogs can instead be queued. This functionality could perhaps be discussed further, but it brings the behavior in line with Android and iOS and prevents this crash from occurring.
https://bugzilla.xamarin.com/show_bug.cgi?id=43469
Added:
`public static class MessageDialogExtensions` 
- contains `public static async Task<IUICommand> ShowAsyncQueue(this MessageDialog dialog)`
The SO post does mention a reason or two that having multiple dialogs might not be desirable, but again, this behavior can be discussed further if …
> [WinRT] Use a queue to prevent multiple MessageDialogs from causing a crash

- Xamarin.Forms.Platform.WinRT.Phone/WindowsPhonePlatform.cs
- Xamarin.Forms.Platform.WinRT/Platform.cs
This fix makes use of the Page.Content bounds to lay out elements as opposed to the Page bounds. Page.Content already compensates for the status bar and on screen buttons if present so it prevents elements from being laid out below them.
This issue mostly affected stand alone ContentPages and pages pushed modally since they would be laid out based on the Page's bounds.
- https://bugzilla.xamarin.com/show_bug.cgi?id=42055
None
None
> [Windows] Fix modal pages being laid out below soft buttons

- Xamarin.Forms.Platform.Android/Renderers/SliderRenderer.cs
Android `SeekBar` does not allow Min to be set and `Progress` is an int. This creates a problem when `Slider`'s Min and Max values can be double. For example, when Min is 1 and Max is 10, SeekBar's 1000 ticks need to be distributed over this range. When `Slider` loads initially with a value of 5, Progress will be calculated as an int which results in precision loss. When we read this int back and try to convert it to a double, then the user sees 4.996. To me, it looked like there is no way to fix this problem.
What I did was letting the user see whatever value they set in XF even if this value is slightly off (4.996 is the correct value whereas 5 would be incorrect). However, once they move the slider, then they should begin seeing floating point numbers.
Perhaps, the truly correct thing …
> [Android] Slider should show user-set value on initial load

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44453.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/Platform.cs
Secondary toolbar items on UWP were being given the same foreground color as those in the bar itself. Shifting the call to `BindForegroundColor` after checking the order to see if it's a primary item prevents this from happening. The light drop down menu appears to be in line with a standard UWP app, as applying the background on a `CommandBar` only applies it to the bar itself.
https://bugzilla.xamarin.com/show_bug.cgi?id=44453
None
This only specifically deals with the foreground color being set on the secondary items, potentially making them difficult to read.
> [UWP] Use toolbar foreground color on primary items

- Xamarin.Forms.Core/OnPlatform.cs
use `Device.OnPlatform` for the `OnPlatform` `op_Implicit` to avoid diverging at some point.
no new tests: the previous ones covers this
> Avoid duplicating code in OnPlatform

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla33248.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
When the `Completed` event of an `Entry` fires after keyboard return button is hit, the entry should not pass a newline to the next responder. Circumventing this iOS issue by returning false from the respective method.
- https://bugzilla.xamarin.com/show_bug.cgi?id=33248
> [iOS] Entry should not pass a newline to the next responder

- Xamarin.Forms.Build.Tasks/CompiledConverters/BindablePropertyConverter.cs
- Xamarin.Forms.Core/BindablePropertyConverter.cs
- Xamarin.Forms.Core/IValueConverterProvider.cs
- Xamarin.Forms.Core/Interactivity/BindingCondition.cs
- Xamarin.Forms.Core/Interactivity/MultiCondition.cs
- Xamarin.Forms.Xaml.UnitTests/TriggerTests.xaml
- Xamarin.Forms.Xaml.UnitTests/TriggerTests.xaml.cs
- Xamarin.Forms.Xaml/ValueConverterProvider.cs
Support short version of Property (`IsPassword` instead of `Entry.IsPassword`) 
```
<MultiTrigger TargetType="Entry">
<MultiTrigger.Conditions>
<PropertyCondition Value="True" Property="IsPassword" />
</MultiTrigger.Conditions>
<Setter Property="Scale" Value="1.2" />
</MultiTrigger>
```
- The one I found out earlier this week while doing somewhat related stuffs, you know which one
> [Xaml] support short Properties for PropertyCondition

- Xamarin.Forms.Build.Tasks/CompiledValueProviders/PassthroughValueProvider.cs
- Xamarin.Forms.Build.Tasks/CompiledValueProviders/TriggerValueProvider.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Core.UnitTests/DataTriggerTests.cs
- Xamarin.Forms.Core.UnitTests/MultiTriggerTests.cs
- Xamarin.Forms.Core/Interactivity/BindingCondition.cs
- Xamarin.Forms.Core/Interactivity/DataTrigger.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz28719.xaml.cs
- Xamarin.Forms.Xaml/ValueConverterProvider.cs
Or better, avoid compiling DataTrigger, and avoid generating ServiceProvider for (now) unused ProvideValue
I feel there's something not-quite-right in the way the compiled value providers are invoked but can't put my finger on it. This isn't an issue as we control, and test, 100% of the compiled value providers.
I guess I'll refine this when I'll compile (the remaining) markup extensions
> Xamlc compile data triggers

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41054.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/FormsTextBoxStyle.xaml
An issue exists with the Entry in UWP where the text color won't update while focused (the bug report referred to one of the Forms samples projects using a behavior to check against a numerical value); after some poking around it looks like the cause of this was stemming from the template where the value wasn't being applied on the Focused VisualState, but using it on the ContentElement itself allows things to function as normal.
https://bugzilla.xamarin.com/show_bug.cgi?id=41054
None
None
> [UWP] Fix TextBox style for foreground focus color

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla38723.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
If you change page content in Picker's `SelectedIndexChanged` so that the picker is no longer attached to the page, this throws an NRE. This should be tested on top of #478 or you can hit the `Done` button without scrolling.
- https://bugzilla.xamarin.com/show_bug.cgi?id=38723
> [iOS] Fix NRE when updating page Content in Picker SelectedIndexChanged

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla31141.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
iOS does not reload new keyboard type while keyboard is visible and the user makes changes to the `Keyboard` property. This PR ensures the behavior will be similar to Android.
- https://bugzilla.xamarin.com/show_bug.cgi?id=31141
> [iOS] Change keyboard type while keyboard is visible

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40073.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/TabbedPageWindows.cs
- Xamarin.Forms.Platform.UAP/FormsCommandBar.cs
- Xamarin.Forms.Platform.UAP/MasterDetailControl.cs
- Xamarin.Forms.Platform.UAP/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.UAP/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.UAP/TabbedPageStyle.xaml
- Xamarin.Forms.Platform.UAP/ToolbarPlacementHelper.cs
- Xamarin.Forms.Platform.WinRT.Phone/FormsPivot.cs
- Xamarin.Forms.Platform.WinRT/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.WinRT/PageControl.xaml.cs
Makes the UWP toolbar consistent with Android/iOS with regard to visibility.
- [40073 – Toolbar items are not not functioning properly on UWP](https://bugzilla.xamarin.com/show_bug.cgi?id=40073)
- [51142 – Toolbar not showing when using PushAsync on UWP](https://bugzilla.xamarin.com/show_bug.cgi?id=51142)
None
None
> Make UWP toolbar visibility consistent with other platforms

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43735.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/ContextScrollViewDelegate.cs
iOS `ListView` is allowing multiple cells to be swiped to show their context action menus at the same time. This PR will fix that. It seems that each cell has its own dedicated `ScrollView` and they are not aware of each other.
- https://bugzilla.xamarin.com/show_bug.cgi?id=43735
> [iOS] Prevent multiple ListView cells from being swiped simultaneously

- Xamarin.Forms.Core/ListView.cs
`ItemTapped` of `ListView` returns `ItemTappedEventArgs` that is supposed to be showing item tapped as well as the group it lives in. As of now, XF is returning an internal object `TemplatedItemsList`. This PR will ensure that parameters are directly convertible to user-defined models.
```
void OnItemTapped(Object sender, ItemTappedEventArgs e)
{
var item = (MyItem)(e.Item);
var group = (MyGroup)(e.Group);
}
```
There is no point in returning an internal member. Similarly, users should not be using reflection. This will be a breaking change for those who were using reflection. So, please make sure to communicate the change.
- https://bugzilla.xamarin.com/show_bug.cgi?id=45092
> Return group instead of internal class on ItemTapped of grouped ListView

- Xamarin.Forms.Maps.Android/MapRenderer.cs
- Xamarin.Forms.Maps.iOS/MapRenderer.cs
Move to correct region when `Map` control changes layout. Ref #172.
The repro attached to the bug has two maps in a vertical StackLayout. The second one is invisible on load and made visible on button click. Both maps should have the same camera view when visible; however, the first one is not re-adjusting its view region when control layout changes.
@rmarinho I don't believe checking visibility change on the second map on iOS is the right approach. For now, I removed it. I also ran `Bugzilla38284` on Android device and confirmed that it's not working as it is.
- https://bugzilla.xamarin.com/show_bug.cgi?id=38284
- https://bugzilla.xamarin.com/show_bug.cgi?id=43639 (possibly. There is no repro there, so I can't decide if it represents the same or a different bug.)
> [iOS/Android] Move Map camera to correct region on layout change

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45926.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UnitTests/MessagingCenterTests.cs
- Xamarin.Forms.Core/MessagingCenter.cs
- Xamarin.Forms.Platform.iOS/FormsApplicationDelegate.cs
- Xamarin.Forms.Platform.iOS/PageExtensions.cs
If the target of a MessagingCenter callback is the subscriber, keep a weak reference to the subscriber to allow it to be garbage collected.
Also refactored MessagingCenter slightly because I got tired of miscounting the angle brackets.
- [45926 – MessagingCenter prevents subscriber from being collected](https://bugzilla.xamarin.com/show_bug.cgi?id=45926)
None
None
> Allow subscriber to be collected if MessagingCenter is the only reference to it

- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Picker.cs
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/UpdateMode.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/Picker.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/UpdateMode.xml
Converting #478 into platform specifics.
- https://bugzilla.xamarin.com/show_bug.cgi?id=38204
Added:
- `ShouldChangeSelectedIndexWhenDoneProperty` (as usual, not sure about the naming)
- getters and setters for the property
> [iOS] Platform specifics for controlling Picker SelectedIndex change behavior

- Xamarin.Forms.Platform.Android/Renderers/TimePickerRenderer.cs
The renderer for the Android time picker opens the time picker dialog with a hardcoded 12-hr setting despite the fact the the platform allows to determine whether 24 hr time formatting was configured or not.
Time picker should respect the 12hr/24hr setting of the user on Android.
Enable 24-hr time formatting depending on Android system settings instead of the hard coded 12-hour setting.
> Enable 24-hr formatting for Android TimePicker

- Xamarin.Forms.Platform.Android/Renderers/FontExtensions.cs
Defers the creation of the regex used to determine whether the font needs to be loaded from an assset. Reduces overhead if no font with a FontFamily property is ever used in the application.
- None
- None
- None
> Don't create FontExtensions Regex unless/until necessary

- Xamarin.Forms.Core/Application.cs
Currently the built-in Application.Properties dictionary is initialized as part of the Application constructor, which adds overhead to application startup even if the application doesn't use the feature. 
This change defers the initialization of the Properties feature until first use.
No new tests.
- None
- None
- Slightly faster application startup
- Slight delay on first access of Properties
> Defer initialization of Application.Properties until first use

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
`NavigationPageRenderer` is creating a new `Fragment` every time we push, pop, or pop to root. While it makes sense to do this in the first case, it doesn't in other cases. Instead, we can re-use existing fragments from `_fragmentStack`. Not sure what this means for performance, but there is no need to instantiate a `Fragment` object unnecessarily. 
Also removed two local variables.
- N/A
> [Android] NavigationPageRenderer should not create a Fragment unnecessarily

- Xamarin.Forms.Core/DependencyService.cs
- Xamarin.Forms.Core/Registrar.cs
Optimize search for Effect resolution name
Avoid multiple collection of assemblies during startup
Cache handler lookups
Don't resolve Effect resolution short name unless the assembly actually has effects.
If the Dependency Service hasn't already been initialized, pass the assembly list to it for initialization (so the Dependency Service doesn't have to compile that list again for itself).
When  looking up handler types, cache null results to avoid traversing the class hierarchy on subsequent lookups.
- None
- None
- None
> Improve registry startup and lookup performance

- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
Under iOS, only if the Navigation Bar is translucent, the content is placed underneath the Navigation
Bar and not aligned to the bottom.
- https://forums.xamarin.com/discussion/27745/navigationrender-issue
None
Before this patch, if the Navagion Bar was setted to translucent, underneath the navigation bar the user see the background of the navigation controller. After the patch he'll see the child view (on iOS this should be the right behaviour for translucent navigation bar)
> Put the child view underneath the Navigation Bar when translucent (iOS)

- Xamarin.Forms.Platform.Android/Forms.cs
- Xamarin.Forms.Platform.iOS/Forms.cs
Fix bug-39359 UriImageSource does cache failed HTTP responses
https://bugzilla.xamarin.com/show_bug.cgi?id=39359
> fix bug-39359

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39489.cs
- Xamarin.Forms.Core.iOS.UITests/UITestCategories.cs
- Xamarin.Forms.Maps.iOS/FormsMaps.cs
- Xamarin.Forms.Maps.iOS/MapRenderer.cs
This is the same fix as [PR 467](https://github.com/xamarin/Xamarin.Forms/pull/467), but applied to iOS 9. MKMapView instances are pooled and reused to avoid leaking memory.
- Failing test 39489 on iOS 9
None
None
> Pool and reuse MKMapView instances on iOS 9 as well as iOS 10

- Xamarin.Forms.Build.Tasks/CompiledConverters/ListStringTypeConverter.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Core/ListStringTypeConverter.cs
- Xamarin.Forms.Xaml.UnitTests/CompiledTypeConverter.xaml
- Xamarin.Forms.Xaml.UnitTests/CompiledTypeConverter.xaml.cs
compile the ListStringTypeConverter, used in Style and the new OnPlatform
slightly longer IL, but no reflection calls, and less method calls
> [XamlC] compile ListStringTypeConverter

- .nuspec/Xamarin.Forms.Maps.nuspec
- .nuspec/Xamarin.Forms.nuspec
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Users want to upgrade to Xamarin.Support.* v25 but cannot because XF locks its version at v23 (in .nuspec, see version="[23.3.0]"). If we simply unlocked the version then they can reference v25 however those assemblies reference Android SDK API 25 which if not installed will break their build. So we have to make sure that by default, when they upgrade, API 25 is present. The VS SDK installer is not owned by Xamarin's division so are forced to wait till May for the installer to add API 25 during a VS upgrade. That upgrade will also include Xamarin.Android (XA) which will support MonoAndroid70. XA will automatically update Android csproj files at load time to MonoAndroid71. Hence, for users that simply upgrade VS in May, XF knows that if referring project is MonoAndroid70 or greater than …
> Add MonoAndroid70 to Forms/Map .nuspec 

- .nuspec/Xamarin.Forms.Maps.nuspec
- .nuspec/Xamarin.Forms.nuspec
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Users want to upgrade to Xamarin.Support.* v25 but cannot because XF locks its version at v23 (in .nuspec, see version="[23.3.0]"). If we simply unlocked the version then they can reference v25 however those assemblies reference Android SDK API 25 which if not installed will break their build. So we have to make sure that by default, when they upgrade, API 25 is present. The VS SDK installer is not owned by Xamarin's division so are forced to wait till May for the installer to add API 25 during a VS upgrade. That upgrade will also include Xamarin.Android (XA) which will support MonoAndroid70. XA will automatically update Android csproj files at load time to MonoAndroid71. Hence, for users that simply upgrade VS in May, XF knows that if referring project is MonoAndroid70 or greater than …
> Add MonoAndroid70 to Forms/Map .nuspec

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla51503.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/VisualElement.cs
When `EventTrigger`, `DataTrigger` or `MultiTrigger` are attached to a `VisualElement`, the finalizer throw a `NullReferenceException` which crash the application after the page disappear. 
It's because these inherit from `TriggerBase` and not `Trigger`.
- https://bugzilla.xamarin.com/show_bug.cgi?id=51503
Nothing
> [Core] Fix NullReferenceException in VisualElement finalizer.

- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
In the case where the footer view was removed, the event handler for `_footerRenderer.Element.MeasureInvalidated` was not removed so re-adding a footer would fire off the event while `_footerRenderer` was still null and [cause an NRE](https://github.com/jimmgarrido/Xamarin.Forms/blob/a4ba715083a4b1545f44f6bacd6c8699076ac172/Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs#L296).
The same thing would also happen with a header.
- https://bugzilla.xamarin.com/show_bug.cgi?id=51652
None
> [iOS] Fix NRE when re-adding header/footer

- Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs
[iOS] redraw Frame on CornerRadius changed. We missed that part in #496.
- https://github.com/xamarin/Xamarin.Forms/pull/496#issuecomment-273363058
/
/
> [iOS] redraw Frame on CornerRadius changed

- Xamarin.Forms.Platform.Android/Renderers/SearchBarRenderer.cs
Adds a try/catch around API that fails in previewer specific situation.
None
None
Works now with previewer
> [A]Fix potential crash when calling ClearFocus in SearchBarRenderer

- Xamarin.Forms.Platform.MacOS/Renderers/TabbedPageRenderer.cs
`GetTabViewItemIcon` uses NSImage.ImageNamed, which supports only named images or images in the root directory of the bundle. This PR adds support for images in a subdirectory. It also prevents the app from crashing, if the image is not found.
None
None
None
> [macOS] Fixed Tab NSImage crash in TabbedPageRenderer

- Xamarin.Forms.Core.UnitTests/NavigationUnitTest.cs
- Xamarin.Forms.Core/INavigationPageController.cs
- Xamarin.Forms.Core/NavigationPage.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/NavigationRenderer.cs
- Xamarin.Forms.Platform.WP8/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.WinRT/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/INavigationPageController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/NavigationPage.xml
Removes the StackCopy member of NavigationPage and replaces it with an enumerable to avoid the Stack construction and Reverse operation overhead. 
- None
- Removes `StackCopy` from `INavigationPageController`
- Adds `Page Peek(int depth);`
- Adds `IEnumerable<Page> Pages { get; }`
- None
> Reduce overhead of pushing existing navigation stack 

- Xamarin.Forms.Core.UnitTests/NavigationUnitTest.cs
- Xamarin.Forms.Core/INavigationPageController.cs
Adds default parameter value of zero to `Peek()` method. Because Rui's right, it's a lot nicer that way.
- Adds default parameter value of zero to `Peek()` method.
> Add default parameter value of zero to INavigationPageController.Peek()

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45330.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
Gestures on view cells which are in the process of being destroyed (e.g., if the ListView's underlying data source is being replaced) can end up in a race condition where the underlying Android gesture detector is already disposed before they are handled. This change adds a check for this condition to avoid a crash.
No UI tests for this; the timing on simulated gestures isn't accurate enough to consistently reproduce this issue. 
- [45330 – System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Android.Views.GestureDetector'.](https://bugzilla.xamarin.com/show_bug.cgi?id=45330)
- None 
- None
> Add check for disposed gesture detector on VisualElementRenderer

- Xamarin.Forms.Core.UnitTests/MessagingCenterTests.cs
- Xamarin.Forms.Core/MessagingCenter.cs
Fixes incorrect subscription cleanup logic which removed subscriptions which were not eligible for removal. Adds unit test to catch the problem in the future.
- [51703 – MessagingCenter.Unsubscribe unsubbs ALL instances that has subscribed to the message](https://bugzilla.xamarin.com/show_bug.cgi?id=51703)
- None 
- None
> Fix overeager subscription cleanup

- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/ExpandMarkupsVisitor.cs
- Xamarin.Forms.Build.Tasks/SetFieldVisitor.cs
- Xamarin.Forms.Build.Tasks/SetNamescopesAndRegisterNamesVisitor.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/SetResourcesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz27863.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz27968.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz45179.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz45179.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- Xamarin.Forms.Xaml/ExpandMarkupsVisitor.cs
- Xamarin.Forms.Xaml/FillResourceDictionariesVisitor.cs
- Xamarin.Forms.Xaml/MarkupExtensions/StaticResourceExtension.cs
- Xamarin.Forms.Xaml/NamescopingVisitor.cs
- Xamarin.Forms.Xaml/PruneIgnoredNodesVisitor.cs
- Xamarin.Forms.Xaml/RegisterXNamesVisitor.cs
- Xamarin.Forms.Xaml/XamlNode.cs
- Xamarin.Forms.Xaml/XamlNodeVisitor.cs
Do not instantiate DataTemplate Content at parsing time
- https://bugzilla.xamarin.com/show_bug.cgi?id=45179
/
/
> [Xaml[C]] Do not instantiate DataTemplate Content at parsing time

- Xamarin.Forms.Build.Tasks/CompiledValueProviders/SetterValueProvider.cs
- Xamarin.Forms.Build.Tasks/CompiledValueProviders/TriggerValueProvider.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz51567.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz51567.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] allow xml-elements as Setter/Trigger Values
- https://bugzilla.xamarin.com/show_bug.cgi?id=51567
/
/
> [XamlC] allow xml-elements as Setter/Trigger Values

- Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/StaticExtension.cs
- Xamarin.Forms.Xaml.UnitTests/XStatic.xaml
- Xamarin.Forms.Xaml.UnitTests/XStatic.xaml.cs
[XamlC] use TypeRefComparer to compare TypeRef from different assemblies
- https://bugzilla.xamarin.com/show_bug.cgi?id=49228
/
/
> [XamlC] use TypeRefComparer to compare TypeRef from different assemblies

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla32206.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43941.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Cells/CellTableViewCell.cs
- Xamarin.Forms.Platform.iOS/Cells/ViewCellRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
iOS `ListView` is leaking for various reasons. Although the bug description mentions issues with `RecycleElement`, this applies to either caching strategy. Since this seems to be a serious issue, can this PR be given priority?
See comments for details.
P.S. It was mentioned that the same issue occurs on Android, but I wasn't able to reproduce it on AppCompat (at least not with the sample code in this PR).
EDIT: Also included the fix for another bug concerning context actions not being properly disposed.
- https://bugzilla.xamarin.com/show_bug.cgi?id=43941
- https://bugzilla.xamarin.com/show_bug.cgi?id=32206
- https://bugzilla.xamarin.com/show_bug.cgi?id=27194 (possibly fixes this too. Download links seem to be down.)
> [iOS/Critical] Fix ListView memory leaks

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43867.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/EditorEditText.cs
- Xamarin.Forms.Platform.Android/Renderers/EntryEditText.cs
- Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
When the soft keyboard is dismissing on `Entry` and `Editor`, it changes characters. This seems to happen randomly instead of following a consistent pattern unless you use a Google keyboard (tested on S6) in which case it seems to happen every time.
- https://bugzilla.xamarin.com/show_bug.cgi?id=43867
> [Android] Keyboard should not change layout while dismissing on Entry and Editor

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43783.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT.Phone/WindowsPhoneResourcesProvider.cs
- Xamarin.Forms.Platform.WinRT.Tablet/WindowsResourcesProvider.cs
On the Windows platforms, the device styles were being retrieved and copied into the Forms resource dictionary by walking up the style tree and retrieving the Setter values. However, this fails when the walk up the style tree encounters a Setter whose value is a binding expression (e.g., to ThemeResource). Because of this, most of the built-in device styles do not render at all on the Windows platforms.
Rather than walk the tree, this change creates a TextBlock, applies the style to it, and retrieves the resolved values for use in the Forms resource dictionary. This allows it to retrieve values which come from ThemeResource bindings. The rendered device styles now match more closely with the values in WinRT apps created in Blend:
[Windows Phone 8.1 Styles …
> Use a prototype TextBlock to resolve theme resources on Windows

- Xamarin.Forms.Platform.UAP/NavigationPageRendererUWP.cs
- Xamarin.Forms.Platform.UAP/PlatformUWP.cs
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
- Xamarin.Forms.Platform.WinRT/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.WinRT/NavigationPageRendererWinRT.cs
- Xamarin.Forms.Platform.WinRT/Platform.cs
- Xamarin.Forms.Platform.WinRT/PlatformWinRT.cs
- Xamarin.Forms.Platform.WinRT/Xamarin.Forms.Platform.WinRT.csproj
The WinRT/UWP shared Platform.cs and NavigationPageRenderer.cs files share the bulk of their code;  the many interlaced conditional compilation statements make them difficult to modify and review changes in. 
This change is aimed at reducing the number of conditional compilation statements and making it clearer how the platform and navigation pages behave on each platform. 
This also allows for the removal of a few suppressed Resharper warnings about methods which are marked `async` and lack `await` operators. 
No tests, this is just a refactoring. 
Countless future ones :)
None
None
> Make WinRT/UWP platform classes more maintainable

- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/EntryPageiOS.cs
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Entry.cs
- Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/Entry.xml
There was lingering usage of "Enabled" in naming from #526. This corrects those names while we should still be able to since this is only in 2.3.4-pre1.
N/A
See changes
N/A
> [iOS] Remove "Enabled" usage on AdjustsFontSizeToFitWidth

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41619.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/SliderRenderer.cs
A bound initial value on a slider was not working on WinRT/UWP if the `Minimum` value was not set to 0. it appears that not setting these values on the control prior to assigning `OnNativeValueChanged` is incorrectly setting `Element.Value` to `Minimum`. Adjusting the sequence allows the behavior to function as expected. 
(While it was noticed, a small adjustment was made to remove an unnecessarily extra capital letter in OnNativeValueChanged.)
https://bugzilla.xamarin.com/show_bug.cgi?id=41619
None
None
> [WinRT/UWP] Fix Slider binding value incorrectly

- Xamarin.Forms.Core.UnitTests/MessagingCenterTests.cs
- Xamarin.Forms.Core/MessagingCenter.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/IMessagingCenter.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/MessagingCenter.xml
Proposing this as an alternative to [PR 541](https://github.com/xamarin/Xamarin.Forms/pull/541). This change is designed to allow for easier testing of components which utilize `MessagingCenter` by introducing an interface (`IMessagingCenter`) which can be faked/mocked/substituted in automated tests (see the `TestMessagingCenterSubstitute()` method in `MessagingCenterTests` for an example). 
This is essentially the same interface proposed in 541, but built on top of the changes from [PR 617](https://github.com/xamarin/Xamarin.Forms/pull/617). Also, this version allows the continued use of the original `MessagingCenter` API without deprecation; the static methods on `MessagingCenter` simply call through to the new singleton instance, allowing the code to be shared rather than duplicated.
- …
> Make MessagingCenter testable

- Xamarin.Forms.Controls/ControlGalleryPages/AccessibilityGallery.cs
- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core/Accessibility.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.Android/AppCompat/FrameRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.Android/IVisualElementRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/MasterDetailRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.Android/ViewRenderer.cs
- Xamarin.Forms.Platform.Android/VisualElementExtensions.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
- Xamarin.Forms.Platform.UAP/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.UAP/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.WinRT.Phone/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.WinRT.Tablet/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.WinRT/CarouselPageRenderer.cs
- Xamarin.Forms.Platform.WinRT/IVisualElementRenderer.cs
- Xamarin.Forms.Platform.WinRT/ListViewRenderer.cs
- Xamarin.Forms.Platform.WinRT/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.WinRT/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.WinRT/ViewRenderer.cs
- Xamarin.Forms.Platform.WinRT/VisualElementRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
- Xamarin.Forms.Platform.iOS/ViewRenderer.cs
- Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Accessibility.xml
Adds several new attached properties that will enable native screen readers to discover and interact with Xamarin.Forms controls.
As described in XFE proposal: https://forums.xamarin.com/discussion/85909/basic-accessibility-support
- Provides an alternate fix for [Bugzilla 41072](https://bugzilla.xamarin.com/show_bug.cgi?id=41072) that will actually fire the Forms `ItemSelected` event when selected by Keyboard and Narrator. (#182)
Added:
- `string Accessibility.Hint { get; set; } //Attached Bindable Property`
- `bool Accessibility.IsInAccessibleTree { get; set; } //Attached Bindable Property`
- `VisualElement Accessibility.LableledBy {  get; set; } //Attached Bindable Property`
- `string Accessibility.Name { get; set; } //Attached …
> [All] Basic Accessibility Support

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz44213.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz44213.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
Use the `op_Implicit` operator on the value to cast to `BindingBase` before calling `SetBinding()`. This allows scenarios like this to work:
```
<Label x:Name="label">
<Label.Text>
<OnPlatform x:TypeArguments="BindingBase" Android="{Binding Bar}">
<OnPlatform.iOS>
<Binding Path="Foo"/>
</OnPlatform.iOS>
</OnPlatform>
</Label.Text>
</Label>
```
- https://bugzilla.xamarin.com/show_bug.cgi?id=44213
- http://stackoverflow.com/questions/41760510/xamarin-forms-xaml-onplatform-not-working-on-bindings
/
/
> [Xaml[C]] cast to BindingBase before SetBinding()

- Xamarin.Forms.Core.UnitTests/ResourceDictionaryTests.cs
- Xamarin.Forms.Core/ResourceDictionary.cs
[C] throw meaningful exception on duplicate RD key
- https://bugzilla.xamarin.com/show_bug.cgi?id=45678
None: the argument has the same type, the message is different.
/
> [C] throw meaningful exception on duplicate RD key

- Xamarin.Forms.Xaml.UnitTests/Issues/Bz44216.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz44216.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
[Xaml] do not set properties with private setters
- https://bugzilla.xamarin.com/show_bug.cgi?id=44216
/
/
> [Xaml] do not set properties with private setters

- Xamarin.Forms.Core.UnitTests/NavigationUnitTest.cs
- Xamarin.Forms.Core/NavigationPage.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/NavigationPage.xml
`NavigationPage` has `CurrentPage` which points to the tail of the stack, but it lacks a pointer to the head. `RootPage` (a read-only property) should be used to get access to the first element of the stack. This makes it easier to look up the root and change it if needed via `InsertPageBefore()`
When changing root, I should be able to do something like:
```
np.InsertPageBefore(newPage, np.RootPage);
await np.PopToRootAsync();
```
Removing root should be even easier:
`np.RemovePage(np.RootPage);`
Also edited & added unit tests.
Added:
- static readonly BindablePropertyKey RootPagePropertyKey
- public static readonly BindableProperty RootPageProperty
> [Core] Added RootPage to NavigationPage

- Xamarin.Forms.Core.UnitTests/RelativeLayoutTests.cs
- Xamarin.Forms.Core/RelativeLayout.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/RelativeLayout.xml
Constraints of a RelativeLayout are bindable properties but the layout does not update when the constraints are updated.
This change will invalidate the layout whenever  XConstraint, YConstraint, WidthConstraint or HeightConstraint is changed (either in code or through a change in the bound property)
Methods added:
- RelativeLayout.SetXConstraint(BindableObject,Constraint)
- RelativeLayout.SetYConstraint(BindableObject,Constraint)
- RelativeLayout.SetWidthConstraint(BindableObject,Constraint)
- RelativeLayout.SetHeightConstraint(BindableObject,Constraint)
RelativeLayout will now invalidate itself when any of the constraint expressions on children change. Since constraints are bindable properties, this is the expected behavior. 
In the exisiting implementation, it was impossible to update …
> Update RelativeLayout to make it respond to constraint changes

- Xamarin.Forms.Core/OnIdiom.cs
- Xamarin.Forms.Core/TargetIdiom.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/OnIdiom`1.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/TargetIdiom.xml
Add TV to TargetIdiom. `TargetIdiom.TV` indicates that Forms is running on a Tizen app on Tizen TV devices.
- None
Added:
- TargetIdiom.TV //  enum
- T OnIdiom<T>.TV { get; set; }
- None
> Add TV to TargetIdiom

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1024.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.iOS/ViewRenderer.cs
When you have a `ListView` where each `ViewCell` contains an `Entry`, popping the current page does not release it because `EntryRenderer` is missing `if (e.NewElement != null)` in `OnElementChanged`. I have a UI test case that could be automated. Let me know if you want me to push it as well. Since I haven't created a bug, I do not know what to name the test class.
Please run this on top of #524.
- N/A
> [iOS] Dispose Entry and Editor properly and automate GC checks

- Xamarin.Forms.Build.Tasks/DebugXamlCTask.cs
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Build.Tasks/XamlTask.cs
[XamlC] support portable pdb. Reuse Cecil logic (https://github.com/mono/cecil/commit/898fb6b8cb03319937448d93bdf6eaa3dd2c6008#diff-d60c9973465fb52c71c5ba9af324992aR687) based on file availability to pick between Pdb (portable or native) or Mdb.
Portable Pdb will be the default symbol format for mono in Cycle10. We HAVE to support this.
~~This PR actually contains a single commit but is built on top of #699. Merge that one before.~~
- https://bugzilla.xamarin.com/show_bug.cgi?id=51778
/
/
> [XamlC] support portable pdb

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla32956.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
On iOS and Android, if you push a page on `ListView` item selected event and when you then go back to the previous page, renderers can't decide if the next selected item change comes from a native tap or some other action. This happens when selected item change is called multiple times with frequent taps and flags fall out of sync. See changes and sample code for a better understanding.
- https://bugzilla.xamarin.com/show_bug.cgi?id=32956
> [iOS/Android] Handle item selection highlight when ListView cell is tapped erratically

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Core/IMarkupExtension.cs
- Xamarin.Forms.Xaml.UnitTests/AcceptEmptyServiceProvider.xaml
- Xamarin.Forms.Xaml.UnitTests/AcceptEmptyServiceProvider.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.Xaml/AcceptEmptyServiceProviderAttribute.xml
- docs/Xamarin.Forms.Core/index.xml
Do not generate ServiceProvider if they're not used in Custom MarkupExtensions.
- ask @jonathanpeppers 
Added:
```
[AttributeUsage(AttributeTargets.Class, Inherited = false)]
public sealed class AcceptEmptyServiceProviderAttribute : Attribute
```
/
> Xaml empty service provider

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45027.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/CellAdapter.cs
If a cell context menu is open and you double tap an action, it shouldn't crash.
- https://bugzilla.xamarin.com/show_bug.cgi?id=45027
> [Android] Double tapping on context action should not crash

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1023.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/DatePickerRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TimePickerRenderer.cs
Went through renderers for `Picker`, `TimePicker`, and `DatePicker` to add/enhance dispose methods. Also added a UI test to automate GC checks. This should be run on top of #524.
- N/A
> [iOS] Dispose pickers properly and automate GC checks

- .gitattributes
On a clean master branch I expect to be able to run update-docs-windows.bat and have git detect no changes. What actually happens is (1) the line endings are changed from windows to unix by mdoc and (2) non-white spaces changes are made because the build does not always detect that doc changes were made (it checks for "Members Added: 0, Members Deleted: 0" but that is buggy and reports 0 when changes were actually made). To fix (1) we can force all doc files to be checked out by git using unix line endings regardless of dev os by updating .gitattributes. To fix (2), after this change goes through, we can update our build to fail on account of missing docs whenever after running update-docs-windows.bat git detects any changes.
To force git to re-checkout the docs with unix line endings …
> Checkout docs using unix line endings

- docs/Xamarin.Forms.Core/index.xml
- update-docs-windows.bat
I expect that when I run update-docs-windows.bat on a clean master no files change. What actually happens is that sometime doc files change. This happens because the build fails to detect changes to the docs. The build runs `update-docs-windows.bat` which returns a success exit code if mdoc returns `"Members Added: 0, Members Deleted: 0"` and a failure exit code otherwise. This doesn't work because mdoc may return that string when docs are non-trivially changed.
To make the change check more robust, I concat all *.xml doc files into a `doc.xml` before running mdoc and then again into `_doc.xml` after running mdoc. I fail the build if `fc` detects those two files are different.
None
None
None
None
> Robust doc change detection

- Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/NullExtension.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Xaml/MarkupExtensions/NullExtension.cs
do not call ProvideValue on `{x:Null}` but push `ldnull` on the stack instead. Reduce Il size and computation time.
/
/
/
> Null compiled markup

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44940.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/ScrollViewRenderer.cs
`SendScrollFinished` was not being called inside of `OnScrollToRequested` on WinRT/UWP which would cause an `await` to not be returned.
https://bugzilla.xamarin.com/show_bug.cgi?id=44940
None
None
> [WinRT/UWP] Insert missing SendScrollFinished call

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla22229.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla34632.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42069.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ImageLoadingErrorHandling.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue773.cs
- Xamarin.Forms.Controls/ControlGalleryPages/AccessibilityGallery.cs
- Xamarin.Forms.Controls/GalleryPages/ButtonGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CellsGalleries/ProductViewCell.cs
- Xamarin.Forms.Controls/GalleryPages/FrameGallery.cs
- Xamarin.Forms.Controls/GalleryPages/LabelGallery.cs
- Xamarin.Forms.Controls/TestCases.cs
- Xamarin.Forms.Core.UnitTests/ListViewTests.cs
- Xamarin.Forms.Core/Device.cs
- Xamarin.Forms.CustomAttributes/TestAttributes.cs
- Xamarin.Forms.Platform.WinRT/WindowsBasePlatformServices.cs
- Xamarin.Forms.Xaml/XamlParser.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Device.xml
Splits the `Windows` option for `RuntimePlatform` into separate `WinRT` and `UWP` values, allowing for separate `OnPlatform` values for each platform (and distinguishing between the two anywhere else it might be called for).
Also added long-overdue `UWP` option to `PlatformAffected`.
None
Anywhere which previously checked for a `Device.RuntimePlatform` of `Windows` will now need to check `WinRT` and `UWP` individually.
`Device.RuntimePlatform` now returns `WinRT` on WinRT and `UWP` on UWP.
> Split Windows RuntimePlatform into UWP and WinRT

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41600.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs
As it presently exists, using a `ListView`'s `ScrollTo` while passing in an invalid value (such as `listView.ScrollTo("Test", ScrollToPosition.Start, false)` will result in the application crashing opposed to silently returning from the method when running on Android. iOS and RT/UWP do not crash, so the inclination is to bring Android's behavior in line with the other platforms and make certain that this is documented. This behavior already existed when `IsGroupingEnabled` is set to true, and was only applying to situation where it was false.
https://bugzilla.xamarin.com/show_bug.cgi?id=41600
None
Aside from a crash not occurring, this behavior should be documented somewhere.
> [A] Do not throw error for first param in ScrollTo

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45284.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45284.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Forms.cs
- Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs
[iOS] Fix extra tab icon appearing in iOS for TabbedPage
This branch pull #448 along, and add a test.
This adds a workaround for an iOS 10 bug that displays extra icons in a UITabBarController when the UITabBarItem.Title property is changed. More info here: http://stackoverflow.com/questions/38776978/ios-10-uitabbar-more-items-visible-after-setting-title
- https://bugzilla.xamarin.com/show_bug.cgi?id=45284
Added:
- internal Forms.IsiOS10OrNewer { get; }
> [iOS] Fix extra tab icon appearing in iOS for TabbedPage (was #448)

- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42000.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Cells/EntryCellRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/KeyboardExtensions.cs
- Xamarin.Forms.Platform.Android/Renderers/LocalizedDigitsKeyListener.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Proposing this as an alternative fix to [PR 396](https://github.com/xamarin/Xamarin.Forms/pull/396)
The DigitsKeyListener in Android has `.` [hard-coded as the decimal separator](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/text/method/DigitsKeyListener.java#63). This change introduces a LocalizedDigitsKeyListener which checks the current decimal separator for the device language. If the separator is `.`, it defers to the built-in DigitsKeyListener; if not, it uses an instance of LocalizedDigitsKeyListener with the correct decimal separator.
This preserves the default Android behavior (not allowing the user to enter an invalid number format) while allowing for "alternate" decimal separators (e.g. `,`). 
This change also provides an easily …
> Add localized listener for Android numeric input

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla52533.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
Fix regression introduced in #529 allowing an infinite width to be returned for `Label's on iOS, which led to an exception in nested and potentially horizontally infinite layouts. 
- [Bug 52533 - Xamarin.Forms v2.3.4.192-pre2 Regression: System.ArgumentException: NaN is not a valid value for width](https://bugzilla.xamarin.com/show_bug.cgi?id=52533)
None
None
> [iOS] Prevent "NaN is not a valid value for width" exception

- Xamarin.Forms.Core/Editor.cs
- Xamarin.Forms.Core/IEditorController.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.MacOS/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.WP8/EditorRenderer.cs
- Xamarin.Forms.Platform.WinRT/EditorRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Editor.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IEditorController.xml
- docs/Xamarin.Forms.Core/index.xml
3ed parties are adding platforms and their renderers need access to internal XF members that are exposed internally via InternalVisibleToAttribute. To expose those internal members we're adding IViewControllers to all renderers; We're making the internal members public but as explicit implementations of an interface to hide them from isense. 
Added Editor.SendCompleted as explicit implementation of IEditorController.
> IEditorController

- Xamarin.Forms.Core/Interactivity/BindingCondition.cs
- Xamarin.Forms.Core/Interactivity/DataTrigger.cs
- Xamarin.Forms.Pages/DataSourceBindingExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/ArrayExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/BindingExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/NullExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/TemplateBindingExtension.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/BindingCondition.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/DataTrigger.xml
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml/ArrayExtension.xml
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml/BindingExtension.xml
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml/NullExtension.xml
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml/TemplateBindingExtension.xml
[Xaml][XamlC] decorate IMarkupExtnesion and IValueProvider with `[AcceptEmptyServiceProvider]` when the service provider isn't used. This speeds up inflating as the loader doesn't have to create a service provider. In case of XamlC, it further reduces IL size.
> [Xaml] decorate markup and value providers to speed up inflating

- Xamarin.Forms.Build.Tasks/DebugXamlCTask.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Build.Tasks/XamlTask.cs
- Xamarin.Forms.Build.Tasks/packages.config
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml.UnitTests/packages.config
[XamlC] update to cecil 0.10.0-b4 for better symbol detection.
since -beta4 Cecil uses a different `snk` than mono, so the one we build against and deploy will no longer be mismatched with the one installed in the GAC
this is an enhanced version of #726 
/
/
/
> [XamlC] update to cecil 0.10.0-b4 for better symbol detection

- Xamarin.Forms.Core.UnitTests/ColorUnitTests.cs
- Xamarin.Forms.Core/Color.cs
- Xamarin.Forms.Core/ColorTypeConverter.cs
[C] support more color format in ColorTypeConverter
/
/
/
> [C] support more color format in ColorTypeConverter

- Xamarin.Forms.Controls/SdxApp.xaml
- Xamarin.Forms.Controls/SdxApp.xaml.cs
- Xamarin.Forms.Controls/SdxPage.xaml
- Xamarin.Forms.Controls/SdxPage.xaml.cs
- Xamarin.Forms.Core.UnitTests/DynamicResourceTests.cs
- Xamarin.Forms.Core/MergedStyle.cs
- Xamarin.Forms.Core/ResourcesExtensions.cs
[Xaml] Fallback to App.Current for DynamicResources so the previewer can resolve them even if the displayed control is not parented back to Application.Current.MainPage.
this needs to be backported to 2.3.4 once merged
- https://bugzilla.xamarin.com/show_bug.cgi?id=52706
/
/
> [Xaml] Fallback to App.Current for DynResources (Previewer)

- Xamarin.Forms.Core/Button.cs
- Xamarin.Forms.Core/Editor.cs
- Xamarin.Forms.Core/Entry.cs
- Xamarin.Forms.Core/FontElement.cs
- Xamarin.Forms.Core/IFontElement.cs
- Xamarin.Forms.Core/Label.cs
- Xamarin.Forms.Core/SearchBar.cs
- Xamarin.Forms.Core/Span.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
Reuse the same BPs for IFontElement properties. The advantage is that it's now possible to set the FontSizeProperty to any IFontElement property without knowing what it is, and make sure the property will apply.
no api change => no new tests.
/
/
None, ideally
> [Core] Share BP across IFontElement implementors

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla51238.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
- Xamarin.Forms.Platform.Android/VisualElementTracker.cs
Restoring the visibility of Views which have an Alpha value between 0 and 1 causes a crash due to a negative width/height in `VisualElementTracker`'s `UpdateLayout` method.
- [51238 – Transparent Grid causes Java.Lang.IllegalStateException: Unable to create layer for Platform_DefaultRenderer](https://bugzilla.xamarin.com/show_bug.cgi?id=51238)
None
None
> Fix for Android Visibility/Opacity crash 

- Xamarin.Forms.Platform.Android/Cells/ViewCellRenderer.cs
- Xamarin.Forms.Platform.iOS/Cells/ViewCellRenderer.cs
Currently, a generic unhandled exception will be thrown during runtime if `ViewCell.View == null`. This fix adds a null check which throws an `InvalidOperationException` with a more descriptive exception message.
None
None
None
> Throw InvalidOperationException when ViewCell View is null

- Xamarin.Forms.Platform.Android/Platform.cs
On Lollipop and above `NavigationPage.BarTextColorProperty` was not working when using `FormsApplicationActivity` because getting a reference to the title `TextView` with the `action_bar_title` resource Id returns null. Instead you have to get a reference to the view indirectly via the Toolbar.
- https://bugzilla.xamarin.com/show_bug.cgi?id=49384
None
None
> [Android] Fix NavigationPage.BarTextColorProperty on API 21+ with FormsApplicationActivity

- Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs
When a TabbedPage is rendered on iOS with no set CurrentPage (i.e. CurrentPage = null), this results in a NullReferenceException. 
This occurs for example when the children are loaded/added async.
Add null check in ChildViewControllerForStatusBarHidden() in TabbedRenderer
None
None
None
> Fix for nullreferenceexception in TabbedRenderer on iOS when it has are no children (yet) 

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44955.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/FormsTextBoxStyle.xaml
- Xamarin.Forms.Platform.WinRT.Phone/FormsTextBoxStyle.xaml
- Xamarin.Forms.Platform.WinRT.Tablet/FormsTextBoxStyle.xaml
Similar to #618, there's an issue with behaviors and the background color. This is an older fix that was sitting around that was most of the way there for WinRT, but is better than the current situation where the entry background color isn't updating correctly. The only lingering issue is that the border on WinRT (tablet) has a very faint tint to it when the background changes to white (in the repro, it'll be a very light red), but nothing in the template stood out and I wanted to avoid modifying it too much. The phone template is simpler and doesn't seem to have the same problem. If anything stands out on the former, feel free to point it out.
https://bugzilla.xamarin.com/show_bug.cgi?id=44955
None
None
> [WinRT/UWP] Make TextBox better respect background color changes via behaviors

- Xamarin.Forms.ControlGallery.Android/Activity1.cs
- Xamarin.Forms.ControlGallery.WindowsUniversal/MainPage.xaml.cs
- Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla51505.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
Revert setting `EffectControlProvider` to `null` (added in #360).
- [Bug 51505 - ObjectDisposedException On Effect detachment.](https://bugzilla.xamarin.com/show_bug.cgi?id=51505)
None
May reintroduce leak in Android. Will need to be reinvestigated.
> [Android] Don't crash if Control is accessed in Effect OnDetached when Page is Disposed.

- Xamarin.Forms.Platform.iOS/ContextActionCell.cs
Fix a build error in upcoming versions; an overload of the ActionSheet constructor we use is [being obsoleted](https://github.com/xamarin/xamarin-macios/blob/master/src/UIKit/UIActionSheet.cs#L51). This updates to the non-obsolete constructor.
> Fix obsolete constructor in ContextActionCell

- Xamarin.Forms.Platform.UAP/AutoSuggestStyle.xaml
Presently trying to set the AutoSuggestBox style like the following for UWP causes a crash:
<Style TargetType="AutoSuggestBox">
<Setter Property="FontFamily" Value="Comic Sans MS"/>
</Style>
Although setting this property in a native UWP app would not work (the style should be applied as a value on `TextBoxStyle`), it wouldn't crash. The crash here appears due to a naming conflict on the `AutoSuggestBoxTextBoxStyle` key being used; renaming this appears to prevent this crash from occurring. The `App.xaml` in the UWP gallery project was not modified for this PR to keep global styles the same, but would reproduce the issue if added.
https://bugzilla.xamarin.com/show_bug.cgi?id=41919
None
None
> [UWP] Adjust AutoSuggestBox's TextBoxStyle style name to prevent possible crash

- Xamarin.Forms.Platform.UAP/SearchBarRenderer.cs
The feature in #499 was deemed as something that be moved into an effect, but there is one element of it that is actually a fix via setting `AutoMaximizeSuggestionArea` to false to prevent the SearchBar from shifting up awkwardly to accommodate a suggestion area which doesn't exist (explained and displayed in that PR).
(I had been meaning to get around to extracting this)
https://bugzilla.xamarin.com/show_bug.cgi?id=45924
None
None
> [UWP] Set SearchBar's AutoMaximizeSuggestionArea to false

- Xamarin.Forms.Maps.UWP/MapRenderer.cs
Issues:
1. The MapRenderer calls TrySetViewBoundsAsync before the map is ready for it. This causes the map to hardly ever initialize to the correct position.
2. The visible region calculation gets the zoom wrong.
3. Map can cause a crash if you rotate/zoom a lot when setting the visible region.
Fixes:
1. Call MoveToRegion using MapControl's RunIdleAsync to have it move after the map starts rendering
2. lat/long delta should be:
var latitudeDelta = Math.Abs(nw.Position.Latitude - se.Position.Latitude);
var longitudeDelta = Math.Abs(nw.Position.Longitude - se.Position.Longitude);
rather than calculated from the center
3. Move the visible region set into the try/catch block.
- https://bugzilla.xamarin.com/show_bug.cgi?id=41900
- https://bugzilla.xamarin.com/show_bug.cgi?id=42151
None
> UWP MapRenderer fixes.

- Xamarin.Forms.Platform.Android/Renderers/ActivityIndicatorRenderer.cs
Null check all the things to prevent the XF Previewer from crashing. No tests added, but did verify that this stops the crash in https://github.com/xamarin/app-crm on `SplashPage.xaml`.
- [Bug 52885 - ActivityIndicatorView does not null check the IndeterminateDrawable](https://bugzilla.xamarin.com/show_bug.cgi?id=52885)
None
None
> [Android] Add null checks to ActivityIndicator

- Xamarin.Forms.Controls/CoreGalleryPages/ListViewCoreGalleryPage.cs
- Xamarin.Forms.Core/PlatformConfiguration/AndroidSpecific/ListView.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.CustomAttributes/TestAttributes.cs
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
- Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/ListView.xml
- docs/Xamarin.Forms.Core/index.xml
Work on some feedback from @Clancey  for ListViewRenderer ,
- Add Platform specific for IsFastScrollEnabled 
- Cache count
Added:
- Platform specific `IsFastScrollEnabled `
Usage:
- `listView.On<Android>().SetIsFastScrollEnabled(true);`
> [Android] Small performance fixes to ListViewRenderer, PlatformSpecific IsFastScrollEnabled 

- Xamarin.Forms.Core/VisualElement.cs
- Xamarin.Forms.Platform.WP8/VisualElementTracker.cs
- Xamarin.Forms.Platform.WinRT/VisualElementTracker.cs
Our views on UWP can take anywhere from 30 seconds to 10 minutes to render.  This fix takes all those views down to milliseconds.  I would rather have just removed all the IsInNativeLayout and also the MaybeInvalidate() function because they seem to not really do anything.  InvalidateLayout shouldnt cause a layout cycle unless something else was wrong.  So even though we are checking the tree once per control now instead of multiple times, I believe its still too much and shouldnt be needed.
No Tests needed as this is for performance only.  I did see some performance functions in the master code if that is something that can be used on UWP then it would be interesting to see the differences on complex trees.
#52507
None
UWP views should load extremely fast now, especially in release.
> Fixed a redundant check that caused a massive slowdown on UWP.

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44525.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/ControlGalleryPages/CellForceUpdateSizeGalleryPage.cs
- Xamarin.Forms.Platform.iOS/Cells/CellRenderer.cs
Getting the `ViewCell`'s index from the `sender` if we cannot get it from the `UITableView` (i.e., when the `ListView` uses the `RecycleElement` strategy.
Please note that all other `Cell` types will still fail to respond to `ForceUpdateSize` on iOS. Updating gallery page to indicate this until a proper fix is found.
- [Bug 44525 - Xamarin.Forms Listview Row Height Does Not Adapt In iOS](https://bugzilla.xamarin.com/show_bug.cgi?id=44525)
None
None
> [iOS] ViewCells will respond to ForceUpdateSize in RecycleElement mode

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42599.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/LabelRenderer.cs
Ported `GetDesiredSize` override from iOS to WinRT/UWP `LabelRenderer`.
- [Bug 42559 - LineBreakMode does not work on UWP](https://bugzilla.xamarin.com/show_bug.cgi?id=42559)
None
None
> [Win] Labels will now wrap when inside horizontally infinite layouts

- Xamarin.Forms.Platform.WinRT/TableViewRenderer.cs
TextCell expected to be disabled if Command.IsEnabled is false. Actually, on UAP, TextCell remained enabled. Fixed by checking if Cell.IsEnabled before dispatching command.
https://bugzilla.xamarin.com/show_bug.cgi?id=53224
None
UAP TextCell no longer dispatches Command if the Command is disabled.
> Bug 53224; Disable Cell if Command IsEnabled false

- Xamarin.Forms.Core/DependencyService.cs
- Xamarin.Forms.Core/Effect.cs
- Xamarin.Forms.Core/Registrar.cs
Added internal Xamarin.Forms.Registrar.RegisterAll(). Without this previewer breaks. They bind to it using reflection.
None
None
None
> Add internal XF.Registrar.RegisterAll b/c previewer needs it

- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Core/Internals/ResourceLoader.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Xaml.UnitTests/DefaultCtorRouting2.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/XamlLoaderGetXamlForTypeTests.xaml.cs
- Xamarin.Forms.Xaml.Xamlc/Xamarin.Forms.Xaml.Xamlc.csproj
- Xamarin.Forms.Xaml.Xamlc/packages.config
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/HydratationContext.cs
- Xamarin.Forms.Xaml/XamlFilePathAttribute.cs
- Xamarin.Forms.Xaml/XamlLoader.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/ResourceLoader.xml
- docs/Xamarin.Forms.Core/index.xml
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml.Internals/XamlLoader.xml
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml/XamlFilePathAttribute.xml
More generic resourceLoading mechanism for the Previewer, so the same API can be reused to load different kind of resources.
/
/
/
> Resource loading

- Xamarin.Forms.Platform.iOS/PlatformRenderer.cs
The TransitioningDelegate of the ModalWrapper is now set to the TransitioningDelegate of the child ViewController.
This limits the need to create a custom renderer when wanting to provide custom transitions.
TransitioningDelegate was not being applied to a the ViewController when pushing Modally.
None
> Inherit Transitioning Delegate from Child (ModalWrapper)

- Xamarin.Forms.Core/Element.cs
Element.Effects is a publicly exposed list and so users can insert null. Whenever we act on elements of the list we must first check for null. We failed to do that for EffectsOnClearing. This change adds the null check.
https://bugzilla.xamarin.com/show_bug.cgi?id=53417
None
None
> null check effects before clearing

- Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
By default an iOS phones in landscape won't display the status bar. It's expected this is not the behavior for a tablet which will show the status bar either way. Actually we see the status bar is hidden for a tablet in landscape just like a phone. 
We tried to re-implement the iOS default behavior but omitted the idiom check. Instead, we simply call into iOS and allow it to handle it's own default behavior. 
https://bugzilla.xamarin.com/show_bug.cgi?id=52620
None
See description
> Adopt iOS status bar visibility defaults

- Xamarin.Forms.Core.UnitTests/ContentFormUnitTests.cs
- Xamarin.Forms.Core.UnitTests/ContentViewUnitTest.cs
- Xamarin.Forms.Core.UnitTests/TemplatedPageUnitTests.cs
- Xamarin.Forms.Core.UnitTests/TemplatedViewUnitTests.cs
- Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
- Xamarin.Forms.Core/TemplateUtilities.cs
I think the code before the change was intended to remove all the items in the InternalChildren. However, the code is removing only the odd-numbered items from InternalChildren. This PR modifies the code to fit the original intent.
This PR modifies the code to fit the original intent.
None
> [Core] Fix internal children clear logic

- Xamarin.Forms.Maps.UWP/MapRenderer.cs
1. If UWP MapRenderer is navigated away from, before the user location
is found, an uncaught NRE will be thrown.
2. UWP MapRenderer updates are not enforced to be on UI thread
3. Order of operations in MapRenderer would cause user location to never
be shown.
Fixes:
1. Added null checks in UpdateUserIsShowing and LoadUserPosition
methods.
2. Called map position updates on UI thread.
3. Changed order of operations in OnElementChanged to allow for user
geocoordinates to be shown.
- https://bugzilla.xamarin.com/show_bug.cgi?id=53113
None
None
> UWP MapRenderer NRE and Location fixes

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla52266.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/PickerRenderer.cs
The Picker presently focuses the `ComboBox` but doesn't open the dropdown when `Focus()` is called on it. The dropdown itself (essentially a `Popup`) is separate from the `ComboBox` (`FormsComboBox`) that is used. Hooking into `GotFocus` and tracking whether the dropdown was just closed lets this function in line with what the other platforms do.
https://bugzilla.xamarin.com/show_bug.cgi?id=52266
None
The unfortunate side effect here is that this is a behavior change from what presently occurs which appears in line with the default behavior of the platform (focusing the `ComboBox` only focuses the `ComboBox` and does not open the dropdown). We could alternatively implement a platform specific behavior which allows the user to define if this focus behavior opens the popup (or vice versa).
> [WinRT/UWP] Open Picker dropdown when calling Focus

- Xamarin.Forms.Maps.Android/MapRenderer.cs
Move to GetMapAsync API for better forwards compatibility with map renderer on Android
None
None
None
> Convert Android maps to GetMapAsync call

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Core/Span.cs
Use a fake BO in Span to benefit from FontElement logic sharing
- the one @samhouts whispered in my ear during my sleep
/
/
> [C] fix NIE in Span

- Xamarin.Forms.Platform.Android/AppCompat/FrameRenderer.cs
This applies the same fix from [PR 706](https://github.com/xamarin/Xamarin.Forms/pull/706) to FrameRenderer.
- [45330 – System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Android.Views.GestureDetector'.](https://bugzilla.xamarin.com/show_bug.cgi?id=45330)
> Add gesture disposed check to FrameRenderer

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla53362.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/LabelRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
Labels will no longer expand to the width constraint unless required to do so. Regression caused by #529. Jason tried to warn me. What could go wrong, I said. It's just a small fix, I said. 
- [Bug 53362 - Layout regression in Grid on iOS: HorizontalOption = Center does not center](https://bugzilla.xamarin.com/show_bug.cgi?id=53362)
None.
This shouldn't break anything, I said.
> [iOS/Win] Label will not unnecessarily expand

- Xamarin.Forms.Core/Layout.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz53381.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz53381.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz53381App.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz53381App.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
If Layout.InternalChildren are added in the base `ctor`, the event handler isn't connected yet, and the parenting code isn't executed.
So, all children added directly or indirectly through implicit styles (handled in base ctor) are orphans. This fix gives a foster parent to those children. They'll get as much love as natural borns, but they'll still be a bit different, and I have no code to fix that.
- https://bugzilla.xamarin.com/show_bug.cgi?id=53381
/
/
> [C] Make sure all children are parented

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz53203.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz53203.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] accept assignment of Object from unboxed value types in SetValue
I sometimes wish our BP were generic...
- https://bugzilla.xamarin.com/show_bug.cgi?id=53203
/
/
> [XamlC] accept assignment of Object from unboxed value types in SetValue

- Xamarin.Forms.ControlGallery.Android/Activity1.cs
- Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45874.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
Made Android `ScrollView` an `IEffectControlProvider'`.
- [Bug 45874 - Effect not attaching to ScrollView (Android)](https://bugzilla.xamarin.com/show_bug.cgi?id=45874)
None
None
> [Android] ScrollView can now consume Effects

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla51536.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla53834.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Reverting to calculating the estimated row height for grouped lists in the likely event that the group header has a known height. Related to #454.
- [Bug 53834 - incorrect row heights on ios when using groupheadertemplate in Xamarin.Forms 2.3.4.214-pre5](https://bugzilla.xamarin.com/show_bug.cgi?id=53834)
None
May reintroduce the scrolling issues for grouped lists that were fixed by #454.
> [iOS] Don't skip row height estimation for grouped lists 

- Xamarin.Forms.Core.UnitTests/ListProxyTests.cs
- Xamarin.Forms.Core/ListProxy.cs
If a collection implements INotifyCollectionChanged with a Weak Reference then the ListProxy's subscription will get finalized prematurely by the GC since there are no roots holding onto the WeakProxy or the CollectionChanged subscription. I added a ConditionalWeakTable keyed on the ListProxy to hold the WeakProxy and the NotifyCollectionChangedEventHandler this way when there are no more roots holding onto ListProxy they will still get disposed. All current unit tests pass and I added an additional one that demonstrates the bug.
https://bugzilla.xamarin.com/show_bug.cgi?id=31415
I first came across this issue when trying to use a ReactiveList with Xamarin Forms
https://github.com/reactiveui/ReactiveUI/issues/806
None
There shouldn't be any. When there are no more roots referencing the …
> Setup a ConditionalWeakTable in ListProxy to hold weak references so that a ListView will work when connected to a Weak Source

- Xamarin.Forms.Platform.UAP/Resources.xaml
Unexpected styling for UWP EntryCell label: https://bugzilla.xamarin.com/attachment.cgi?id=20400
The user expected the EntryCell label styling to match the SwitchCell label styling. EntryCell style is set here: https://github.com/xamarin/Xamarin.Forms/blob/c65a9a8c57d93b0eff38fd8b06223f6a04688c59/Xamarin.Forms.Platform.UAP/Resources.xaml#L427. 
As you can see it sets ` Foreground="{Binding LabelColor, Converter={StaticResource ColorConverter}, ConverterParameter=SystemControlBackgroundChromeMediumLowBrush}" `. 
This must have been added to allow coloring the label (prob to red to indicate validation error) however no other controls allow coloring the label -- just EntryCell. Which is fine but there is no precedent for the `ConverterParameter`. Currently its value is …
> Fix 53427; Change default UAP styling for a label

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45277.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/FormsTextBox.cs
There is presently an issue in WinRT/UWP where entries with `Password = true` do not allow selection of text. This is a larger issue on the desktop than mobile, but is an issue for both. What this PR changes in particular is that selection is allowed, but also handles a variety of other inputs. The code is appropriately commented due to being a process that involves
- Caching the size of the selection of text for deletion purposes
- Caching whether the Ctrl key is in a pressed state and handling the key routing
- Handling any use of the Shift key, Tab key, arrow keys, or Home/End/PgUp/PgDown keys (which can be used to select text or leave the entry)
- Handle any use of the Copy (C), Cut (X), Undo (Z), or Redo (Y) keys in the instance that the Ctrl key is in being actively pressed to …
> [WinRT/UWP] Enable selection in password entry

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GestureBubblingTests.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/FrameRenderer.cs
- Xamarin.Forms.Platform.WinRT/ButtonRenderer.cs
- Xamarin.Forms.Platform.WinRT/DatePickerRenderer.cs
- Xamarin.Forms.Platform.WinRT/SliderRenderer.cs
- Xamarin.Forms.Platform.WinRT/StepperRenderer.cs
- Xamarin.Forms.Platform.WinRT/SwitchRenderer.cs
- Xamarin.Forms.Platform.WinRT/TimePickerRenderer.cs
- Xamarin.Forms.Platform.WinRT/VisualElementRenderer.cs
- Xamarin.Forms.Platform.WinRT/VisualElementTracker.cs
This change brings iOS, Android, and WinRT/UWP all into alignment on how they treat taps/clicks on a control within a container. 
Previously, if a container (Grid, ContentView, Frame, etc.) had a tap gesture assigned to it and contained controls (Label, Box, Entry, etc.) which do not have gestures assigned, the platforms all behaved differently when those controls were tapped. On each platform, some of the controls would bubble the tap gesture up to the container and some would not, and those lists were different on each platform. 
With this change, controls which become interactive on tap/click (Entry, Editor, Button, etc.) will *not* bubble the tap gesture to the container. Controls which do not (Label, Image, Box, Frame) will allow the gesture to bubble up to their container. The two …
> Align iOS, Android, Windows handling of tap gesture event bubbling

- Xamarin.Forms.Platform.iOS/Platform.cs
#481 and #543 made `UIAlertController` use a separate window which is hidden after the alert is dismissed. However this is causing [some](https://forums.xamarin.com/discussion/comment/263097/#Comment_263097) [issues](https://github.com/jamesmontemagno/MediaPlugin/issues/186) when trying to immediately present another view controller since the alert window is still in the view hierarchy. 
This can be worked around by adding a brief delay before presenting the new view controller, but we can also fix this on our end by hiding the new window _before_ setting the result and returning to the user's code.
- https://bugzilla.xamarin.com/show_bug.cgi?id=54153
None
> [iOS] Hide alert window before setting result

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44980.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Cells/ViewCellRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ActivityIndicatorRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
`ActivityIndicator` on iOS disappears when used in a list view cell and it's scrolled off. In `RetainElement` mode, this happens randomly whereas `RecycleElement` has this problem for every reused cell. Native view seems to have its `IsAnimating` property set to false possibly when iOS is preparing cells for reuse, but Element's `IsRunning` stays true. This PR will sync the two so the indicator can be seen.
Instead of using `MessagingCenter`, I wanted to observe changes in `IsAnimating` but could not get the observer to work despite all efforts.
Referencing https://jira.appcelerator.org/browse/TIMOB-15293
and https://github.com/appcelerator/titanium_mobile/pull/4852
- https://bugzilla.xamarin.com/show_bug.cgi?id=44980
> [iOS] ActivityIndicator should not disappear when used in a ViewCell

- Xamarin.Forms.Platform.Android/Cells/BaseCellView.cs
Removes an unnecessary optimization in BaseCellView which can, under certain circumstances, cause a `NullReferenceException` in the `ListViewAdapter` when the list is scrolled quickly enough.
The NRE occurs in `GetView` when the adapter attempts to get the Element from the cell; if the previous override of `OnDetachedFromWindow()` has already been called, the `Element` will return `null` and the application will crash.
No UI tests, it's a race condition and difficult to reliably reproduce.
- The aforementioned NRE
None
None
> Fix NRE when RecycleElement is on and list is scrolled quickly on Android

- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
When OnResume is called it should not expect the _application to be set already.
I have an app where I use one activity for showing a splash screen and then it starts an intent to show the main activity containing the application.
This used to work before 2.3.4.224.
I have added a null check for the `_application` object before it's used.
OnResume crashes if the `_application` has not been set.
None
> OnResume assumed that _application had been set

- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Expected that disabling pullToRefresh does not kill an in progress refresh. Actually observed disabling pullToRefresh killed in progress refresh. Consider the case of bug 52962:
1. User pulls to refresh
2. App RefreshCommand fires (at this point _refresh.Refreshing is true)
3. RefreshCommand disables itself via a call to ChangeCanExecute which returns false
maybe the command it's attached to a button the app wants disabled)
4. OnCommandCanExecuteChanged handler sets RefreshAllowed to false because the RefreshCommand is disabled
5. We end up here; A refresh is in progress while being asked to disable pullToRefresh
https://bugzilla.xamarin.com/show_bug.cgi?id=52962
None
As described.
> Fix 52962; Cont refresh even when pullToRefresh is disabled

- Xamarin.Forms.Core.UnitTests/BaseTestFixture.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz53275.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz53275.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/TypeExtension.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/XamlServiceProvider.cs
[Xaml] Set the TargetProperty on ServiceProvider
The TargetProperty was set in XamlC scenarios. Set it on uncompiled Xaml too.
This is an alternate version of #814.
- https://bugzilla.xamarin.com/show_bug.cgi?id=53275 which is not really a bug, as it's fine to get a `null` for the TargetProperty.
/
/
> [Xaml] Set the TargetProperty on ServiceProvider

- Xamarin.Forms.Build.Tasks/DebugXamlCTask.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/TypeDefinitionExtensions.cs
- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
After bisection I found that change `eacbc1acf4cc` in `GetImplicitOperatorTo` causes the reproduction of https://bugzilla.xamarin.com/show_bug.cgi?id=54012 to throw an AccessViolationException in https://github.com/xamarin/Xamarin.Forms/blob/c65a9a8c57d93b0eff38fd8b06223f6a04688c59/Xamarin.Forms.Platform.WinRT/LabelRenderer.cs#L20. Note the bug reports a different issue; this is a regression  that blocks investigation of the reported issue.
Expected `MasterDetailNavigation.dll` for 54012 to successfully pass peverify but actually observed errors. Expected xaml compiler to emit initlocals for all method bodies but actually did not. Expected xaml compiler to not emit op_implicit if `fromType` equals `toType` but actually emits op_implicit when that is the case. Either actual behavior …
> Do not emit implict_op if from/to are same type

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla30166.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Platform.cs
- Xamarin.Forms.Platform.Android/Renderers/NavigationRenderer.cs
This gets rid of duplicate calls to some of the methods that update the ActionBar. 
It also fixes a bug that affected API 21+ where the background color was reset due to `ActionBar.IsShowing` not being reliable in the newer versions. I still added a UITest for this even though the issue only affects` FormsApplicationActivity` not `FormsAppCompat`.
- https://bugzilla.xamarin.com/show_bug.cgi?id=30166
- https://bugzilla.xamarin.com/show_bug.cgi?id=27731
None
None
> [Android] Clean up NavigationBar code in FormsApplicationActivity Platform

- Xamarin.Forms.Maps.Android/MapRenderer.cs
- Xamarin.Forms.Maps.iOS/MapRenderer.cs
- Xamarin.Forms.Maps/Pin.cs
- docs/Xamarin.Forms.Maps/Xamarin.Forms.Maps/Pin.xml
Makes the Xamarin.Forms.Maps projects more extensible, by unsealing the Pin class and adding hooks in the MapRenderer classes for customization of map and pins.
Added:
- protected virtual void MapRenderer.OnMapReady(GoogleMap map) (Android)
- protected virtual MarkerOptions MapRenderer.CreateMarker(Pin pin) (Android)
- protected virtual IMKAnnotation MapRenderer.CreateAnnotation(Pin pin) (iOS)
- Pin.LabelProperty
Changed:
- IOnMapReadyCallback.OnMapReady(GoogleMap map) calls protected OnMapReady for map initialization 
- public sealed class Pin => public class Pin
- Pin.Label now uses backing BindableProperty LabelProperty
No behavioral changes to existing functionality, reduces need for workarounds when subclassing MapRenderer.
> Map renderer extensibility

- Xamarin.Forms.Platform.Android/ResourceManager.cs
In F#, loading images from files causes a null reference exception.
https://bugzilla.xamarin.com/show_bug.cgi?id=53515
None
None
> Resource Manager fix for F# File Resources (Bugzilla 53515)

- Xamarin.Forms.Core.UnitTests/ListProxyTests.cs
Original version of the test didn't work in Release mode because the local ListProxy object was optimized out before the end of the test. Added a member reference to keep it around throughout the test.
> Update ListProxyTest.WeakToWeak so it works in Release mode

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla30324.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
- Xamarin.Forms.Core.UITests.Shared/Remotes/BaseViewContainerRemote.cs
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailContainer.cs
- Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
- Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
- Xamarin.Forms.Platform.Android/Platform.cs
Switching the application's main page when a fragment transaction has already been queued up by `MasterDetailContainer.AddChildView` can cause a race condition where the FragmentContainer is never created and attempting to commit the transaction causes a crash. This change adds a check to verify that the FragmentContainer has been created.
This change also defers the disposal of the previous page set until after all currently queued events for that page set have been processed; this prevents a race conditions which can result in an `ObjectDisposedException`.
None
None
None
> Verify FragmentContainer created when queueing fragment transaction (Android)

- Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
This changes allows for custom renderers which derive from the fast renderers to override `OnElementPropertyChanged`.
> Make OnElementPropertyChanged virtual on fast renderers

- Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
Calling an API not available in all versions of Android.
https://forums.xamarin.com/discussion/comment/267383/#Comment_267383
https://bugzilla.xamarin.com/show_bug.cgi?id=55230
None
None
> Calling API not available in all versions

- Xamarin.Forms.Build.Tasks/XmlTypeExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/TypeExtension.xaml
- Xamarin.Forms.Xaml.UnitTests/TypeExtension.xaml.cs
[XamlC] allow namespaces in {x:Type} markups, like in 
```
<Button CommandParameter="{x:Type ns:Foo.Bar}" />
```
as it's supported with XamlC off
- https://bugzilla.xamarin.com/show_bug.cgi?id=55027
/
/
> [XamlC] allow namespaces in {x:Type} markups

- Xamarin.Forms.Build.Tasks/XmlTypeExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/XStatic.xaml
- Xamarin.Forms.Xaml.UnitTests/XStatic.xaml.cs
[XamlC] support nested types type declarations
- https://bugzilla.xamarin.com/show_bug.cgi?id=55096
/
/
> [XamlC] support nested types type declarations

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ListViewNRE.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Changes made in #520 will allow the code in `OnItemSelected` to execute in more situations, including when the `ListView` has already been disposed. In this situation, we will get a `NullReferenceException`. Adding a null check to prevent this. Exception was not observed on Android, but I added a check there nonetheless to be safe.
- Not reported
None
None
> [iOS] Prevent NRE in ListView OnItemSelected

- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz55347.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz55347.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Who could have guessed that picking the first implicit operator with the right return type without checking the input parameter would not work all the time ?
What were the chances that it would fail ?
1 out of a trillion. No more. No less.
But still that particular unlikely case happened. That's really bad luck.
- https://bugzilla.xamarin.com/show_bug.cgi?id=55347
/
/
> [XamlC] Check param type in op_Implicit

- .nuspec/Xamarin.Forms.Maps.nuspec
- .nuspec/Xamarin.Forms.Pages.nuspec
- .nuspec/Xamarin.Forms.nuspec
Add `netstandard1.0` group to .nuspec to allow net standard projects to install Xamarin.Forms packages.
n/a
none
none
> [Internal] Add netstandard group to nuspec

- Xamarin.Forms.Platform.iOS/ContextScrollViewDelegate.cs
Added check for instance of UITableView, so that only one ContextAction can be open **per ListView**.
https://bugzilla.xamarin.com/show_bug.cgi?id=55588
https://bugzilla.xamarin.com/show_bug.cgi?id=55607 (duplicate)
None.
None.
> Bugzilla55607 - [iOS] Opening a ListView Cell's context action will disable context actions for all other ListViews

- Xamarin.Forms.Build.Tasks/XamlGTask.cs
- Xamarin.Forms.Xaml.UnitTests/FieldModifier.xaml
- Xamarin.Forms.Xaml.UnitTests/FieldModifier.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Issue2450.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Issue2450.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml.UnitTests/XamlgTests.cs
- Xamarin.Forms.Xaml/XamlParser.cs
Supports `x:FieldModifier` in Xaml files.
This attribute is only looked for if:
- the top-level node as an `x:Class`,
- the current node as an `x:Name`,
- and some other conditions, but those are the same ones used for generating fields from `x:Name` 
If the value of the attribute isn't set, the generated field will be `private`. If the attribute is set to `NonPublic`, the field will be `internal`, and the field will be bright pink if you set the attribute to `Public`.
This feature isn't supposed to be used by any sane developers, but has been implemented as requested by you-know-who. Using this feature encourages bad design, when any Mvvm framework can do the exact same work while adding 2 full seconds at your app startup (did I already told you that you do not require a Mvvm framework …
> [XamlG] supports x:FieldModifier

- Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
Check if the Label is disposed on GetDesiredSize() on FastRenderer.LabelRenderer
Doesnt crash if GetDesiredSize is called when Label is disposed
none
none
- [ X] Rebased on top of master at time of PR
- [ X] Changes adhere to coding standard
- [ X] Consolidate commits as makes sense
> [Android] Add disposed check on FastRenderers.LabelRenderer

- Xamarin.Forms.Platform.Android/FastRenderers/VisualElementRenderer.cs
Added disposed check on UpdateBackgroundColor()
None
None
Prevents crashes when element is disposed
- [ X] Rebased on top of master at time of PR
- [ X] Changes adhere to coding standard
- [X ] Consolidate commits as makes sense
> [Android] Add disposed check on FastRenderers.VisualElementRenderer

- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Core/Xaml/TypeConversionExtensions.cs
- Xamarin.Forms.Core/Xaml/ValueConverterProvider.cs
- Xamarin.Forms.Xaml/Xamarin.Forms.Xaml.csproj
- docs/Xamarin.Forms.Core/index.xml
- docs/Xamarin.Forms.Xaml/index.xml
introducing the ValueConverterProvider created a dependency from Core to Xaml. Moving the files to Core to avoid implicit dependency.
- https://bugzilla.xamarin.com/show_bug.cgi?id=55636
/
/
> [Xaml] move ValueConverterProvider to Core

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla55745.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs
#524 added `renderer?.Dispose()` to clean up the trial renderers that were created to calculate cell height when the `ListView` had uneven rows. This had an unintended consequence of setting the `Element`s (in this case, any child `Element`s of a `ViewCell`) to `null`, which in turn caused some strange behaviors when the `ViewCell`'s content was changed.
We will now unhook the `Element` from the renderer entirely before we dispose it to prevent this behavior from occurring.
- [Bug 55745 - [iOS] NRE in ListView with HasUnevenRows=true after changing content and rebinding](https://bugzilla.xamarin.com/show_bug.cgi?id=55745)
None
None
> [iOS] Null Element before disposing trial renderers in uneven ListViews

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla55912.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Platform.cs
- [55912 – Tap event not always propagated to containing Grid/StackLayout](https://bugzilla.xamarin.com/show_bug.cgi?id=55912)
None
None
> Give layouts a chance to handle touch events after passing though immediate children

- Xamarin.Forms.Platform.Android/Renderers/FrameRenderer.cs
[Android] Add null check before creating and drawing canvas bugzilla 55559 & 45602
Bugs 
[Android] Exception when setting the backgroundcolor of a frame
https://bugzilla.xamarin.com/show_bug.cgi?id=55559
NullPointerException when applying style
https://bugzilla.xamarin.com/show_bug.cgi?id=45602
None.
Added:
a null check on the _bitmap object before creating a canvas with it.
None
> [Android] Add null check before creating and drawing canvas bugzilla 55559 & 45602

- Xamarin.Forms.Platform.Android/Renderers/TableViewModelRenderer.cs
Unsubscribe the ModelChanged Event when the Android TableViewModelRenderer is disposed.
> Unsubscribe OnModelChanged event when TableViewModelRenderer is disposed

- Xamarin.Forms.Controls/App.cs
- Xamarin.Forms.Core.UnitTests/RegistrarUnitTests.cs
- Xamarin.Forms.Core/Registrar.cs
This issue comes from January related with #674 , what happens is View was being cached with a null renderer.
- https://bugzilla.xamarin.com/show_bug.cgi?id=55542
We don't cache null renderers
> Fix bugzilla55542

- Xamarin.Forms.Platform.UAP/FormsTextBoxStyle.xaml
Bug 52419 notes vertical mis-alignment of text in entry control (see https://bugzilla.xamarin.com/attachment.cgi?id=21636). Modify v-align property to taste. Chose `bottom` instead of `centered` because the padding pushes the text up so `bottom` alignment "looked" better. Padding numbers were/are inherited/copied from the default TextBoxStyle (see https://msdn.microsoft.com/en-us/library/windows/apps/mt299154.aspx) so I didn't want to mess with them.
https://bugzilla.xamarin.com/show_bug.cgi?id=55397
None
Centers text in Entry control.
> UWP; Bugzilla 55397; Set v-align to bottom for TextBoxStyle

- Xamarin.Forms.ControlGallery.Android/Activity1.cs
- Xamarin.Forms.ControlGallery.Android/Resources/values/Colors.xml
- Xamarin.Forms.ControlGallery.Android/Resources/values/styles.xml
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/AndroidStatusBarColor.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla47548.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
Previously, Android status bar background color was set by creating a view to be laid out behind the status bar and setting its background color. This required an extra view, a query for the height of the status bar, several adjustments to layouts to account for the size of the view, and a search through application resources to find the "colorPrimaryDark" value, all of which affect application startup (on older devices, this took as much as 100 ms). Additionally, this caused an issue when setting the soft input adjustment mode to "resize"; a gap would appear between the status bar and the application.
This change removes the status bar underlay. Status bar background color is still determined by the "colorPrimaryDark" value (the default for AppCompat). Changing the status bar color at …
> Remove status bar underlay view in Android AppCompat

- Xamarin.Forms.Core/Color.cs
This is the fixed version of #896
Avoid using string.format to parse hex values, improves performance by 25x, and avoids creating GC junk.
This code change is covered by existing tests.
**Please do not squash-merge to preserve author informations.**
/
/
/
> avoid using string.format to parse hex values

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla54649.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/NavigationPageRenderer.cs
When a `NavigationPage` is inside of a `TabbedPage` on UWP, navigating between the tabs would not update the title when navigating back to a given tab. Calling `UpdateTitleVisible` upon the page's appearing resolves this, and the hook is only assigned when it is inside a parent `TabbedPage` (`_parentTabbedPage`).
https://bugzilla.xamarin.com/show_bug.cgi?id=54649
None
None
> [UWP] Call UpdateTitleVisible on NavigationPage's appearing when inside a TabbedPage

- Xamarin.Forms.Core/Accessibility.cs
- Xamarin.Forms.Xaml.UnitTests/Accessibility.xaml
- Xamarin.Forms.Xaml.UnitTests/Accessibility.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- docs/Xamarin.Forms.Core/Xamarin.Forms/Accessibility.xml
Add the required get/set methods for XamlC to properly parse the Accessibility attached properties.
- [Bug 56079 - Accessibility Support doesn't work in XAML](https://bugzilla.xamarin.com/show_bug.cgi?id=56079)
Added: 
- `Accessibility.GetHint`
- `Accessibility.GetIsInAccessibleTree`
- `Accessibility.GetLabeledBy`
- `Accessibility.GetName`
- `Accessibility.SetHint`
- `Accessibility.SetIsInAccessibleTree`
- `Accessibility.SetLabeledBy`
- `Accessibility.SetName`
None
> [Core] Accessibility works with XamlC

- Xamarin.Forms.Core/AutomationProperties.cs
Fix BindableProperty.Create invocations
- this is required by an upcoming PR
/
/
> [C] fix BP declaring Types for A11y

- Xamarin.Forms.Platform.WinRT/NavigationPageRenderer.cs
Adjust the unhook from #901 which was called after `SetElement(null)` leading to a NRE.
N/A
N/A
N/A
> Adjust unhook location from PR #901

- .nuspec/Xamarin.Forms.Debug.targets
- .nuspec/Xamarin.Forms.targets
- Xamarin.Forms.Build.Tasks/DebugXamlCTask.cs
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Build.Tasks/XamlTask.cs
It can happen that DebugType is set and DebugSymbols is not. In that case, a .pdb is generated, and we should process it to avoid a linker failure.
- https://bugzilla.xamarin.com/show_bug.cgi?id=53805
- https://bugzilla.xamarin.com/show_bug.cgi?id=56296
/
/
> [XamlC] process symbols if DebugType is set

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla55365.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UnitTests/BehaviorTest.cs
- Xamarin.Forms.Core/VisualElement.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/VisualElement.xml
The finalizer added to fix [44074](https://bugzilla.xamarin.com/show_bug.cgi?id=44074) causes an InvalidOperationException during the .NET finalization process because it attempts to operate on other objects which are not guaranteed to be alive and which contain ConditionalWeakTables which may or may not have already had their finalizers run. This ends up causing the ConditionalWeakTable to fail its integrity check. Detaching behaviors and triggers during finalization cannot safely be done, because there are no guarantees of the order that the objects are collected/finalized.
This change removes the finalizer so the exception does not occur.
This change also removes the test `TestBehaviorsAreDetachedBeforeGarbageCollection`, which actually tested whether behaviors were detached during …
> Remove VisualElement finalizer

- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
- Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
I wrote #350 a while ago so we could programmatically toggle the status bar on and off both at application start and during runtime. However, this was needed only because of the dummy underlay added to the overall view tree (which was recently removed by #892). We don't need to layout the root page anymore. This cuts down startup time by as much as 40 ms (at least in my case) if you were hiding the status bar behind the splash screen.
The following still works:
`<item name="android:windowFullscreen">true</item>` in `styles.xml` will not show the status bar at app start.
`global::Xamarin.Forms.Forms.SetTitleBarVisibility(Xamarin.Forms.AndroidTitleBarVisibility.Never);` in `MainActivity` will add `WindowManagerFlags.Fullscreen` flag to window attributes and hide the status bar. …
> Do not layout page in OnWindowAttributesChanged on fullscreen flag change

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42956.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
As documented [here](https://developer.xamarin.com/api/type/Xamarin.Forms.DataTemplateSelector/#Remarks), the `DataTemplateSelector` can have up to 20 `DataTemplates` on Android. 
Due to some indexing issues, the actual limit was 17. Increasing the limit to the documented limit of 20. 
Surpassing this limit will cause the following known (and expected) exception:
```
08-01 15:50:32.987 E/mono    (22808): 
08-01 15:50:32.987 E/mono    (22808): Unhandled Exception:
08-01 15:50:32.987 E/mono    (22808): Java.Lang.RuntimeException: length=23; index=26
08-01 15:50:32.987 E/mono    (22808):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <filename unknown>:0 
08-01 15:50:32.987 E/mono    (22808):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualBoo …
```
> [Android] Support up to 20 templates, as documented.

- Xamarin.Forms.Platform.iOS/Renderers/OpenGLViewRenderer.cs
use a different RunLoop and add a null-check
I ran the UITest provided by Jon in https://bugzilla.xamarin.com/show_bug.cgi?id=41413#c7 on XTC on iOS 8.4.1 and 10.3.2
- Using XF 2.2.0.45 (the bug reproduction)
- Fails on 8.4.1
- works on 10.3.2
- Using XF 2.3.6.103-nightly (current master)
- Fails on 8.4.1
- works on 10.3.2
- Using the `Xamarin.Forms.Platform.iOS` produced by this PR:
- **WORKS** on 8.4.1
- works on 10.3.2
- https://bugzilla.xamarin.com/show_bug.cgi?id=41413
- https://bugzilla.xamarin.com/show_bug.cgi?id=42755
None
None
> Fix animations with GLViews

- Xamarin.Forms.Platform.WinRT/NavigationPageRenderer.cs
A [ContentThemeTransition](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.Animation.ContentThemeTransition) animation is triggered whenever the content is changed which results in flickering when the app window is resized:
By using an [EntranceThemeTransition](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.Animation.EntranceThemeTransition) instead, the animation only runs when the content first appears so resizing is fluid:
- https://bugzilla.xamarin.com/show_bug.cgi?id=56169
None
None
> Switch to EntranceThemeTransition Animation

- Xamarin.Forms.ControlGallery.iOS/CustomRendererBugzila38731.cs
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla38731.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
If the user has some custom code to pop a page using a custom renderer that could bring situations were disposing the page and tapping multiple times calling pop makes it happen concurrently, so we should just check if we still have the renderer for that page, if we don't we don't need to handle it.
https://bugzilla.xamarin.com/show_bug.cgi?id=38731
None 
None
> [iOS] Handle user popping pages out of order

- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Android.UITests/packages.config
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/packages.config
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/packages.config
- Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
- Xamarin.Forms.Core.macOS.UITests/packages.config
Bumps the UI test library version to 2.0.9 so we can run UI tests on machines with XCode 8.3.
> Moving to version 2.0.9 of Xamarin.UITest

- Xamarin.Forms.ControlGallery.WindowsUniversal/FocusEffect.cs
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla56609.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/FormsTextBoxStyle.xaml
Changes in #749 were made to respect behaviors adjusting the `BackgroundFocusBrush` but an adjustment needed to be made so that setting it via Effect works as well, which can be fixed via the template. The issue 44955 in the reproductions still functions as expected.
(If the Effect in the UWP control gallery project can be placed elsewhere, feel free to suggest it.)
https://bugzilla.xamarin.com/show_bug.cgi?id=56609
None
None
> [UWP] Respect TextBox BackgroundFocusBrush Effect

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla49069.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Extensions/TextViewExtensions.cs
- Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/LabelRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
The issue here is a [old Android bug ](https://issuetracker.google.com/issues/36950033) that when calculating the Ellipsis for wrapping the text it takes in account we provide the correct value for SingleLine.
Also refactored to share the fix between the 2 LabelRenderers 
- https://bugzilla.xamarin.com/show_bug.cgi?id=49069
None
None
> [Android] Set SingleLine to true when we only have 1 line on a TextView

- Xamarin.Forms.Core.UnitTests/DynamicResourceTests.cs
- Xamarin.Forms.Core/Element.cs
Prior to this change Element tracked which DynamicResources would trigger a change in one of its properties by storing a List of BindableProperty/Key pairs where Key was the name of a DynamicResource. When a change to the DynamicResources was reported to the Element via Element.OnResourcesChanged the Element would compare the names of the changed DynamicResources to it's list of DynamicResource key names and when there was a match re-initialize the associated BindableProperty. This worked so long as the the Element had a unique set of Keys. However this bug demonstrates that's not always the case.
This bug constructed an example whereby a Label had two different DynamicResources bound to its  Label.TextColor BindableProperty. The first was bound via a Style declared at the application …
> Fix bz56030; DynamicResource overriding

- Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
There are situations where we don't want to dismiss the keyboard when return key is pressed.
Making OnShouldReturn protected will let custom renderers to disable ResignFirstResponder behaviour.
OnShouldReturn is now a protected method.
> make OnShouldReturn protected

- Xamarin.Forms.Core.UnitTests/DatePickerUnitTest.cs
- Xamarin.Forms.Core/DatePicker.cs
Use picker creation date as default Date.
Not easy to write a unit test for this, so there's none.
- https://bugzilla.xamarin.com/show_bug.cgi?id=44011
/
/
> [C] use picker creation date as default Date

- Xamarin.Forms.Platform.MacOS/Renderers/ScrollViewRenderer.cs
macOS.ScrollViewer: Tested against a background color existing or not.  This fixes the issue where ScrollViewer's background color wasnt showing correctly.
Tests Omitted.
https://bugzilla.xamarin.com/show_bug.cgi?id=57022
None.
ScrollViewer's BackgroundColor should show properly now.
> [macOS] Scroll view background not working.

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla54036.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/MasterDetailControl.cs
Only account for the height of the `CommandBar` when it is actually going to be rendered and use the height of the `Master`'s `ContentPresenter` instead of the `MasterDetailControl` to account for the height of the `Master` title area.
- [Bug 54036 - [UWP] MasterPage - Bad Rendering](https://bugzilla.xamarin.com/show_bug.cgi?id=54036)
None
There's a possibility that a `Page` will no longer extend to the bottom of the screen if the content does not also extend to the bottom of the screen. Was not seen during dev testing, but looks like it could be possible.
> [UWP] Correctly calculates height of Master Page content

- Xamarin.Forms.Platform.Android/AppCompat/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/ButtonBackgroundTracker.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/Properties/AssemblyInfo.cs
- Xamarin.Forms.Platform.Android/Renderers/ButtonDrawable.cs
- Xamarin.Forms.Platform.Android/Renderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Don't allow negative border width .
Refactoring and add support for border properties to appcompact and fast renderer button  
https://bugzilla.xamarin.com/show_bug.cgi?id=36031
> Fix border on android buttons 

- Xamarin.Forms.Platform.MacOS/Renderers/MasterDetailPageRenderer.cs
Added handling of IsPresented on macOS's MasterDetailsPage.
Omitted tests as this is new functionality.
https://bugzilla.xamarin.com/show_bug.cgi?id=56855
none
MasterDetailsPage can now handle IsPresented correctly for hiding and showing.
> [macOS] bz56855 Implementation of macOS.MasterDetailsPage.IsPresented.

- Xamarin.Forms.Core.UnitTests/AnimationTests.cs
- Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
- Xamarin.Forms.Core/Animation.cs
- Xamarin.Forms.Core/AnimationExtensions.cs
On repeat, we restart animating from 0 to 1, so the _finishedTriggered flag that is used to avoid invoking the callback when a children animation is finished can be reset, and the sub animation will run again.
- https://bugzilla.xamarin.com/show_bug.cgi?id=51424
/
/
> [C] reset children animation on repeat

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla36703.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/VisualElementTracker.cs
Now updates the `Enabled` property on Android Views when the Element's `IsEnabled` property changes.
- [36703 – TapGestureRecognizer inside initially disable Image will never fire Tapped event](https://bugzilla.xamarin.com/show_bug.cgi?id=36703)
None
None
> Update View Enabled property when IsEnabled changes

- Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
Check if buttonrenderer is disposed when making changes
Check if disposed on elementChanged
Prevent crashes when making changes to a disposed renderer
"System.ObjectDisposedException: Cannot access a disposed object."
None
None
> [Android]Dispose check on FastButtonRenderer to prevent crash

- Xamarin.Forms.Platform.MacOS/Renderers/ButtonRenderer.cs
macOS's NSButton was using AttributedTitle for TextColor.  This sets the Font's attributes to that property.
Tests omitted.
https://bugzilla.xamarin.com/show_bug.cgi?id=57190
None.
Buttons should now have font attributes associated with the Forms Button control.
> [macOS] Button's Font attributes arent setting when using color.

- Xamarin.Forms.ControlGallery.iOS/Info.plist
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44500.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/PlatformRenderer.cs
Work around an iOS bug where a UIWebView presented modally calls dismiss twice after presenting a UIDocumentMenuViewController, which leaves the UIImagePickerController (or whatever else it's displaying) without a connection to the view hierarchy.
No UI tests - can't reliably handle the permissions issues on the test devices.
- [44500 – A WebView that has a file picker control fails to show photo picker when page is pushed modally.](https://bugzilla.xamarin.com/show_bug.cgi?id=44500)
None
None
> Prevent double dismiss of modal view controller when webview opens image picker on iOS

- Xamarin.Forms.Platform.WinRT/VisualElementRenderer.cs
Developers of custom renderers expect descriptive error messages but they actually are getting NullReferenceExceptions. Custom renderer developers are essentially extending the system and so if they fail to follow unwritten conventions of the system they'll encounter states for which we do not have heavy test coverage. 
OnElementChanged is one such method whose implementation must follow an unwritten conventional form and so often trips up custom renderer developers as is the case here. This change provides a more descriptive exception which should hopefully point our developers in the right direction.
https://bugzilla.xamarin.com/show_bug.cgi?id=57021
None
None that are breaking.
> Trap for OnElementChanged implementation error

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla52419.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/PageRenderer.cs
In a pre-AppCompat `TabbedPage`, navigating to new pages on one of the tabs, switching to another tab, and then switching back to the prior tab will fire the Appearing event for each page in its navigation stack. Checking for `Visibility` state of `ViewStates.Gone` (along with the already existing check for `pageContainer`) prevents this from occurring.
The gallery reproduction currently outputs the event firing to debug with the Guid of the visible page in the first tab.
https://bugzilla.xamarin.com/show_bug.cgi?id=52419
None
None
> [A] Check Visibility for tab's page appearing

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla56710.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/ContextActionCell.cs
On iOS, if a Cell had one or more ContextActions that used bindings and the ItemsSource was modified after the Cell was disposed (e.g. when the ListView page was popped), then an NRE was thrown because the`OnMenuItemPropertyChanged` handler would still respond to the property change.
This may only have begun in 2.3.5 because of the fixes in #524. Previously it looks like the Cell was not calling `Dispose()` so this wasn't an issue.
This fix ensures that the MenuItem.PropertyChanged handler is removed when the Cell is disposing.
- https://bugzilla.xamarin.com/show_bug.cgi?id=56710
None
None
> Fix possible crash on iOS when using ContextActions

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40161.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/AbsoluteLayout.cs
Expected swapping an image source of an image in an absolute layout with h/v options of center to render the swapped in image to it's native size. Actually observed swapped in image within an absolute layout rendering to the size of the original image. This happened because of an optimization in the layout engine which assumed re-computation of the size was unnecessary. The optimization was trying to take advantage of the fact that an absolute layout can sometimes dictate the size of it's children. The optimization was treating a child with h/v options _centered_ as one of those cases but it's not. With h/v options centered the child determines its own size in the case where more space was allocated to the image than the native image size. When more space is allocated the image does not …
> bug 40161; force layout of centered image in abs layout

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla57317.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/CellAdapter.cs
When modifying ContextActions while the ActionMode is open, a call is made to _actionMode.Invalidate() without checking for null (which _actionMode will be if you're using FormsAppCompatActivity).
This occurs if you modify the ContextAction while the ActionMode is open (typically reacting to the command/click event from a ContextAction but something running asynchronously in the background could do it too).
The rest of CellAdapter.cs has calls to _actionMode?.XX() to prevent null references, so I've followed that standard (and added a call to _supportActionMode too).
There's a UI test added for Android.
https://bugzilla.xamarin.com/show_bug.cgi?id=57317
None
None
> Fix crash when modifying ContextActions on Android

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla38770.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/VisualElementPackager.cs
`EnsureZIndex` was not being called upon use of `LowerChild` or `RaiseChild` in the `VisualElementPackager`. `OnChildrenReordered` calls `EnsureZIndex` which corrects this and enables expected behavior.
https://bugzilla.xamarin.com/show_bug.cgi?id=38770
None.
None
> [WinRT/UWP] Update ZIndex on LowerChild/RaiseChild

- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
User tried to add multiple rows to a ListView but passed bad arguments to NotifyCollectionChangedEventArgs. Basically, the user asked to insert 2 elements at index 6 however the list had only 2 elements to start. The bad index was passed to iOS which generated an error which, due to the translation, was hard to understand. This PR simply adds a check before the translation and throws a more comprehensible error message.
I've updated the customer reproduction with correct arguments. Basically, when inserting 2 elements at the end of a 4 element list the start index should be 4 instead of 6. 
https://bugzilla.xamarin.com/show_bug.cgi?id=56771
None
None; Better error message. The existing tests are sufficient as they throw the exception on bad input. We're just throwing a more comprehensible …
> Provide better exception for bad INotifyCollectionChanged index bounds

- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.Android/_57114CustomRenderer.cs
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.ControlGallery.WindowsUniversal/_57114Renderer.cs
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.iOS/_57114Renderer.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla57114.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs
- Xamarin.Forms.Platform.iOS/EventTracker.cs
If you create a custom renderer for a control which already has a gesture recognizer, gestures from that control will not be recognized by the Forms gesture recognizer. This change allows the gestures from the control to be processed by the Forms recognizer.
- [57114 – Forms gestures are not supported on UIViews that have native gestures](https://bugzilla.xamarin.com/show_bug.cgi?id=57114)
None
None
> [iOS] Allow Forms gestures on custom renderers for controls which already have gestures

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla25943.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39331.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40173.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla55912.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2775.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TransparentOverlayTests.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/FastRenderers/GestureManager.cs
- Xamarin.Forms.Platform.Android/Platform.cs
- Xamarin.Forms.Platform.Android/Renderers/BoxRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ImageRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/LabelRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/MotionEventHelper.cs
- Xamarin.Forms.Platform.Android/VisualElementExtensions.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
- Xamarin.Forms.Platform.WinRT/VisualElementRenderer.cs
- Xamarin.Forms.Platform.WinRT/VisualElementTracker.cs
- Xamarin.Forms.Platform.iOS/Platform.cs
This change brings iOS, Windows, and Android into alignment with regard to Layout transparency. 
Previously, Layouts with sufficiently low `Opacity` were input transparent on iOS but not on Windows or Android; Layouts with a `BackgroundColor` of `Transparent` or `Default` were input transparent on Android but not on Windows or iOS; and Layouts with `InputTransparent` were input transparent on iOS, mostly input transparent on Android, and not input transparent at all on Windows. 
With this change, input transparency is entirely a function of the `InputTransparent` flag; if a layout is marked `InputTransparent`, then clicks/taps/gestures will pass through it to controls below. Visual transparency (i.e., `Opacity` and the transparency of the background color) no longer has any bearing on …
> Align Layout transparency behavior between Android, iOS, Windows

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/NavigationRenderer.cs
Unlike its predecessor, `AppCompat`'s `NavigationPageRenderer` does not allow certain methods to be overridable and accessible.
- https://bugzilla.xamarin.com/show_bug.cgi?id=57578
> [Android] Change modifiers on NavigationPageRenderer's navigation methods

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla37285.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
Now clearing any text that is entered with a hardware keyboard on a Picker.
- [Bug 37285 - Possible to enter text into Picker control](https://bugzilla.xamarin.com/show_bug.cgi?id=37285)
None
None
> [iOS] Picker no longer allows arbitrary text to be typed with keyboard

- Xamarin.Forms.ControlGallery.iOS/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla52700.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/ContextActionCell.cs
Now passing SelectionStyle property when wrapping the ViewCell.
https://www.screencast.com/t/ruwrHQxI
- [Bug 52700 - Can't disable cell SelectionStyle using ViewCellRenderer for cells when using recycling](https://bugzilla.xamarin.com/show_bug.cgi?id=52700)
None
None
> [iOS] Proxy UITableViewCell SelectionStyle when wrapped

- Xamarin.Forms.Core/Entry.cs
- Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
Work around the fact the UITextField always returns 30 as fitting size for RoundedRect BorderStyle.
Also make sure the layout is invalidated when the font is changed.
- https://bugzilla.xamarin.com/show_bug.cgi?id=44774
/
/
> [iOS] workaround a weird iOS behavior.

- Xamarin.Forms.Core.UnitTests/TemplatedViewUnitTests.cs
- Xamarin.Forms.Core/ContentPage.cs
- Xamarin.Forms.Core/ContentView.cs
- Xamarin.Forms.Core/IControlTemplated.cs
- Xamarin.Forms.Core/TemplateUtilities.cs
- Xamarin.Forms.Core/TemplatedPage.cs
- Xamarin.Forms.Core/TemplatedView.cs
When we remove an old template before setting a new one, all Bindings are unapplied (as part of unparenting).
This fix force a setting back the binding context when the an existing ControlTemplate is swapped for another one.
- https://bugzilla.xamarin.com/show_bug.cgi?id=43685
/
/
> [C] reset the BindingContext on template change

- Xamarin.Forms.Build.Tasks/BindablePropertyReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/MethodDefinitionExtensions.cs
- Xamarin.Forms.Build.Tasks/PropertyDefinitionExtensions.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz53350.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz53350.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml.UnitTests/XamlC/MethodDefinitionExtensionsTests.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/PropertyDefinitionExtensionsTests.cs
Look at this snippet:
public class Bz53350Generic<T> : ContentView
{
public static readonly BindableProperty SomeBPProperty =
BindableProperty.Create("SomeBP", typeof(T), typeof(Bz53350Generic<T>), default(T));
public T SomeBP
{
get { return (T)GetValue(SomeBPProperty); }
set { SetValue(SomeBPProperty, value); }
}
public T SomeProperty { get; set; }
}
This PR allows properties and Bindable properties like `SomeProperty` and `SomeBP` to be assigned when XamlC is on
- https://bugzilla.xamarin.com/show_bug.cgi?id=53350
/
/
> [XamlC] Allow Properties and BP of generic types

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla36780.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs
- Xamarin.Forms.Platform.iOS/EventTracker.cs
Because of the way XF sets up tap gestures on iOS, the last one in always wins. This change adds a [`ShouldRecognizeSimultaneously`](https://developer.apple.com/reference/uikit/uigesturerecognizerdelegate/1624208-gesturerecognizer) delegate to the native tap gestures to allow for more than one to be recognized at the same time.
- [36780 – [iOS] Multiple TapGestureRecognizers on an Object Are Not Fired](https://bugzilla.xamarin.com/show_bug.cgi?id=36780)
- [45014 – Only top level TapGestureRecognizer works on iOS when multiples are on same view](https://bugzilla.xamarin.com/show_bug.cgi?id=45014)
- [45251 – GestureRecognizer added from a renderer](https://bugzilla.xamarin.com/show_bug.cgi?id=45251)
None
None
> Allow multiple tap gestures to fire simultaneously on iOS

- Xamarin.Forms.Platform.MacOS/Renderers/FlippedClipView.cs
- Xamarin.Forms.Platform.MacOS/Renderers/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.MacOS/Xamarin.Forms.Platform.macOS.csproj
Changed ScrollViewRenderer on macOS to align for Start,Center,End on contents that are smaller than the ScrollView panel.  It also fixes an issue where the coordinates being sent into the Forms control from the macOS control on ScrollY were inverted.
Tests omitted.
https://bugzilla.xamarin.com/show_bug.cgi?id=56947
None
ScrollView's should now render at top left rather than bottom left, they should behave vertically for Start, Center, and End.  The correct Y coord should be correct for the Xamarin control.  The only remaining issue is when a window is resized vertically, the control doesnt resize correctly, when the window is resize horizontally it resets to the correct position.  I think this is outside of that control and maybe related to some other events not getting correctly passed …
> [macOS] ScrollView's content are showing at End.

- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla32830.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
On iOS, set `IgnoresContainerArea` to true when the `Page` does not have a `NavigationBar`. This will tell the XF layout system to use the total area of the screen to layout the `Page`.
On Android, use the presence of a `NavigationBar` on the `Page` hosted by the `NavigationPage` rather than the `NavigationPage`'s `ToolbarVisible` property to hide/show the `CommandBar`. The `CommandBar` and `PageContainer` will be set simultaneously to avoid the two being out of sync, which was causing a white bar to appear briefly.
- [Bug 32830 - Hiding navigation bar causes layouts to shift during navigation
briefly](https://bugzilla.xamarin.com/show_bug.cgi?id=32830) (also reported in #431)
None
None
> [iOS/Android] Fixes "jumping" when navigation to a page with a NavigationBar from a page without one

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla46363.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UITests.Shared/Utilities/Gestures.cs
- Xamarin.Forms.Platform.Android/Cells/ViewCellRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/GestureManager.cs
- Xamarin.Forms.Platform.Android/InnerGestureListener.cs
- Xamarin.Forms.Platform.Android/Renderers/MotionEventHelper.cs
- Xamarin.Forms.Platform.Android/Renderers/ViewCellExtensions.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Android stops paying attention to long presses/clicks in ListViews when a list item has any Clickable View inside of it unless the list item's container is marked as LongClickable. This change marks the View inside the ViewCell as LongClickable if the ViewCell has any ContextActions. It also handles pushing the UP MotionEvent to the ViewCell's child layout (if necessary) to cancel any pending long presses/clicks after handling a TapGesture.
- [46363 – TapGestureRecognizer blocks List View Context Actions](https://bugzilla.xamarin.com/show_bug.cgi?id=46363)
None
None
> Allow Context Actions on ViewCells with TapGestures

- Xamarin.Forms.Core/BindableObject.cs
- Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/BindableObject.xml
As fonts or colors can be changed via an inherited renderer, or an effect, do not force reset them on every text changes.
Those are still resets when switching from formatted text to texts.
As before, no-op on font or color change if the text is formatted, as that would change the Label in a way the user do not expect.
- https://bugzilla.xamarin.com/show_bug.cgi?id=51631
/
/
> [iOS] decoupling UpdateText() on LabelRenderer

- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/AndroidHelpText.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/FastRenderers/AutomationPropertiesProvider.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
This is an alternative to #904 (and revision to #801). This will clarify and simplify the code a bit more. 
Note that this code will be moved to extension methods if #889 is accepted.
Also adds a UI test to prevent recurrence.
Also removed the nullable parameters in the `AutomationPropertiesProvider` that are no longer necessary.
- Reported in #904 and #801
- [Bug 56444 - A small "dot" shows up as value in Android labels when the value is null/empty.](https://bugzilla.xamarin.com/show_bug.cgi?id=56444)
None
None
> [Android] Remove the ". " on empty labels (Accessibility) on Fastrenderers

- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
Can we issue a warning to people who're pushing a `MasterDetailPage` onto a `NavigationPage` on iOS? I'm not sure how existing apps are using this pattern with or without problems, but new apps should not be encouraged to use it.
https://developer.apple.com/documentation/uikit/uisplitviewcontroller
> Note
> You cannot push a split view controller onto a navigation stack. Although it is possible to install a split view controller as a child in some other container view controllers, doing is not recommended in most cases. Split view controllers are normally installed at the root of your app’s window. For tips and guidance about ways to implement your interface, see iOS Human Interface Guidelines.
Looks like only the Tablet idiom seems to be using `UISplitViewController` in the case of XF. …
> [iOS] Issue warning to console when MasterDetailPage is pushed onto NavigationPage

- Xamarin.Forms.Platform.WinRT/NativeViewWrapperRenderer.cs
Customer expected to be able to embed native TextBlock into AbsolutLayout but that actually generated a layout cycle. Looks like OnElementChanged hooked up Contol.LayoutUpdated so the native control could lay itself out when something changed. Turns out that event gets call just after the layout cycle is complete and doesn't appear to be documented as a place where actual layout should be preformed. Instead, we can use Control.SizeChanged which is only fired if the size of the control changes which should trigger a new layout of the view. See: 
https://blogs.msdn.microsoft.com/devdave/2008/05/27/layout-events-sizechanged-and-layoutupdated/
FYI, @hartez I just kinda made some of this stuff as my best guess as to what is going on. I added a test next to your other tests but that doesn't …
> [UWP] Bug 56843; LayoutUpdated > SizeChanged; Layout Cycle

- Xamarin.Forms.Platform.Android/Platform.cs
The changes made in #631 and #835 were causing an InvalidCastException when using the Holo theme on Lollipop or higher since that theme does not use a Toolbar.
This fixes it by first checking if there is the older ActionBarTextView on all Android versions and if not, _then_ checking for a Toolbar. This also includes a null check for the Toolbar for situations were it is not present, e.g. using a NoActionBar theme.
- https://bugzilla.xamarin.com/show_bug.cgi?id=57108
None
None
> Fix possible crash on API 21+ at launch when using Holo theme and FormsApplicationActivity

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/MapsModalCrash.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/TestCases.cs
- Xamarin.Forms.Platform.Android/AppCompat/CarouselPageRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailContainer.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/AutomationPropertiesProvider.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
- Xamarin.Forms.Platform.Android/Platform.cs
- Xamarin.Forms.Platform.Android/Renderers/PageContainer.cs
- Xamarin.Forms.Platform.Android/Renderers/PageRenderer.cs
- Xamarin.Forms.Platform.Android/ViewExtensions.cs
- Xamarin.Forms.Platform.Android/ViewRenderer.cs
Because Forms doesn't set the `Id` value for Android Views it creates, some methods (most notably `BackStackRecord.configureTransitions`) which search for Views by `Id` and cast them were failing because all of the Views had the default of `NO_ID` (-1). 
This change sets the `Id` field for the various renderers and for the `ModalContainer` to prevent this issue.
- https://forums.xamarin.com/discussion/comment/280624/#Comment_280624
- https://forums.xamarin.com/discussion/81768/launching-a-modal-over-a-page-containing-a-map-maps-ad-m-cannot-be-cast-to-android-view-viewgroup
None
None
> Set the Id field for Android Views created by Forms

- Xamarin.Forms.Core.UnitTests/GridTests.cs
- Xamarin.Forms.Core/Grid.cs
User expected Grid.AddHorizontal to add a column which spans all rows. What actually happens is that the column spans all the rows except the last one _unless_ there are no rows in which case it creates a new row and spans that single row. 
The fix requires tweaking Grid.AddHorizontal. Grid.AddHorizontal calls Add to create the column. Add takes a view, left/right, and top/bottom. For simplicity consider just the arguments to create the columns: left/right. Starting with a grid with no columns calling add with 0,1 will create one column. First, note that the first index doesn't exist. When the first index doesn't exist that means create a new dimension. Second, note that the second index is one past the index to be created. Now consider the top/bottom values specifying the rows to span. …
> Make Grid.AddHz/Vt span ortho dim

- Xamarin.Forms.Build.Tasks/XamlCTask.cs
This adds two public properties to XamlC task to allow some of its hard coded defaults to be overridden.
1. You can now override its assembly resolver to use/reuse your own
2. You can change the default of whether to compile
Added:
- `bool XamlCTask.ForceCompile { get; set; }`
- `bool XamlCTask.CompileByDefault { get; set; }`
- `IAssemblyResolver XamlCTask.DefaultAssemblyResolver { get; set; }`
This will cause the task to use the given assembly resolver instead of always creating its own.
This will also allow tools to force compilation.
- XamlCTask doesn't have any tests
> [XamlC] Allow overriding the assembly resolver and whether to compile

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla56896.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
#454 turned off row height estimation for `ListView`s enabling `HasUnevenRows` when the first `ViewCell` had a non-zero `Height`. This requires every row to be measured on initial load to prepare the scroll area, so large item sources developed a significant load time.
Re-enabling estimation is ideal for performance; however, it will regress the issue resolved by #454. As a compromise, this change will cache known `ViewCell` heights to be used by `EstimateHeight`, which will be called once when the `ListView` loads and allow the scroll area to be accurately estimated (preserving the resolved status of Bugzilla 43313) while still providing a value for estimation quick enough to restore performance. 
Users may still see that the `ViewCell` constructors will be called more times than they …
> [iOS] ListView with UnevenRows and Cell Heights will no longer be slow to load

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ButtonBackgroundColorTest.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ButtonRenderer.cs
Adds null checks on BackgroundTracker for pre-appcompat Button; also adjusts initialization timing to match AppCompat ButtonRenderer.
- [57717 – Setting background color on Button in Android FormsApplicationActivity causes NRE](https://bugzilla.xamarin.com/show_bug.cgi?id=57717)
None
None
> Fix NRE when background color of button set in FormsApplicationActivity

- Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
Clicking a button quickly to Navigate pages can cause a crash because we weren't always checking to see if the control was disposed. Now we're checking all over the place. 
- None
None
None
> [Android] Dispose check before setting properties on Button

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzila57749.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/VisualElementTracker.cs
Just make sure we updated the HitTestVisible when IsEnabled changes 
https://bugzilla.xamarin.com/show_bug.cgi?id=57749
> [UWP] Make sure to update HitTestVisible when IsEnable changes

- Xamarin.Forms.Core/DefinitionCollection.cs
DefinitionCollection<T> did not unsubscribe to the SizeChanged event  when set via indexer. This could result in unnecessary layouting when for example the Width Property of a ColumnDefinition, that is no longer part of the ColumnDefinitions Collection of a Grid, changes.
None
None
None
> Unsubscribe from IDefinition.SizeChanged event when set via indexer

- Xamarin.Forms.Xaml/XamlLoader.cs
While investigating https://bugzilla.xamarin.com/show_bug.cgi?id=43583 I found out that each view inflated from xaml was keeping alive a string corresponding to its xaml, even when the parsing was complete.
This should address this
/
/
/
I'm currently running manual tests on the profiler, to see if it actually changes something
> [Xaml] Dispose string readers as soon as we're done with them

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla57758.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ViewCellExtensions.cs
If the handler for a tap gesture removes the renderer from the layout (which causes eager disposal to kick in), the renderer will be disposed by the time the `EnsureLongClickCancellation` method runs. This change adds a disposed check to `EnsureLongClickCancellation` to prevent an ObjectDisposedException in that situation.
- [57758 – ObjectDisposedException for Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer](https://bugzilla.xamarin.com/show_bug.cgi?id=57758)
None
None
> Add disposed check to EnsureLongClickCancellation

- Xamarin.Forms.Maps.iOS/MapRenderer.cs
Maps renderer on iOS has been throwing a NullReferenceException when disposing due to the delegate property being null.
I have noticed this when using Xamarin.Forms v2.3.5.239-pre3 in conjunction with the TKCustomMap library.
Added a null check on the Delegate property in the Dispose method of the MapRenderer to make sure it isn't null before calling it's Dispose method.
> [iOS] Fix for disposing a map causing a null reference

- Xamarin.Forms.Platform.WinRT/NavigationPageRenderer.cs
Call UpdateBackbutton when we are inside a tabbed page and it appears.. since Loaded doesn't get called when we change tabs.
https://bugzilla.xamarin.com/show_bug.cgi?id=57482
> [UWP] Make sure to update back button when tabbedpage appears

- Xamarin.Forms.Platform.Android/Forms.cs
On some Samsung devices with API 19 or lower (and possibly other devices), the accent color was being incorrectly resolved using the method for Android 5.0+ which caused some elements, such as TableSection Titles, to appear blank.
This fix adds a check to make sure we are running on API 21+ so those devices can use the fallback methods. No tests are included since any existing ones should cover this already.
Before fix: https://testcloud.xamarin.com/test/accentcolor_a0f83499-e3e6-4c40-bc4d-43ec4b028dd7/
After fix: https://testcloud.xamarin.com/test/accentcolor_7c220793-db86-48c1-bc1a-dec4ce402d1c/
- https://bugzilla.xamarin.com/show_bug.cgi?id=53222
None
None
> Fix accent color on some Samsung devices

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/PopAfterRemove.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Now handles fragment removal inside of the `RemovePage` method rather than leaving it pending for `SwitchContentAsync` to deal with later. 
- [53179 – PopAsync crashing after RemovePage when support packages are updated to 25.1.1](https://bugzilla.xamarin.com/show_bug.cgi?id=53179)
None
None
> [Android] Handle fragment removal inside of the RemovePage method

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ScrollViewObjectDisposed.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
Calling `Element.ClearValue(Platform.RendererProperty);` when the fast renderers are disposed will prevent the disposed renderer from being inadvertently returned later.
Numerous; TBD.
None
None
> [Android] Prevent ObjectDisposed exceptions on Fast Renderers

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla32871.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/BindingExpression.cs
User expects to be able to bind Entry to double, float, or decimal backed property and be able to enter "-0.1" and/or "0.1". What actually happens is that "-0" and "0." are both canonicalized to "0" preventing the user from entering their values. 
Under the hood, after each character is entered into the Entry the binding system attempts to convert the text to the bound property type. If successful then the text is replaced with the ToString value of the converted texted which is canonicalized. 
The fix is special case "-0" and "\d*." so that they no longer convert to 0.
https://bugzilla.xamarin.com/show_bug.cgi?id=32871
Bug pointed out "\d*."; Testing found "-0" case
None
Entering "0." or "-0" into an Entry bound to a decimal, float, or double bound property will not convert to "0".
> [core] Prevent canonicalization of '*.[.]' and '-0'

- Xamarin.Forms.Platform.WinRT/WindowsSerializer.cs
After storing non-primitive types in the properties dictionary, future attempts to deserialize the dictionary on Windows would result in a crash. Android and iOS already had a try-catch when reading the properties dictionary that would prevent this crash and output the exception to the log. This just adds the same try-catch to Windows.
- https://bugzilla.xamarin.com/show_bug.cgi?id=32116
None
None
> Add try-catch when reading properties dictionary on Windows

- NuGet.config
- Xamarin.Forms.Maps.Tizen/Xamarin.Forms.Maps.Tizen.csproj
- Xamarin.Forms.Maps.Tizen/project.json
Tizen projects use the tizen packages uploaded in nuget.org.
Therefore the temporary "NuGet.Config" to use packages in tizen.myget.org has been deleted.
- N/A
- N/A
- N/A
> [Tizen] Fix dependencies of Tizen projects

- Stubs/Xamarin.Forms.Platform.cs
- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
Apps using FormsApplicationActivity were incorrectly getting the "fast" renderers for Label and Image. This change gives legacy apps the correct renderers and uses the "fast" renderers only for FormsAppCompatActivity.
> Use correct renderers for pre-AppCompat

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ScrollViewIsEnabled.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs
Prevents the user from scrolling a ScrollView which has `IsEnabled` set to `false`.
- https://forums.xamarin.com/discussion/comment/285062/#Comment_285062
None
None
> Disallow scrolling in ScrollView when IsEnabled set to False

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39407.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
When closing the Picker by tapping outside or hitting the Done button, verify the source selection index matches the UI control's selected row. When it is spinning during close, the animation completes offscreen and the next time it opens you see the wrong row selected.
https://bugzilla.xamarin.com/show_bug.cgi?id=39407
None
None
> [39407] [iOS] Verify Picker selected index on close

- Xamarin.Forms.Platform.MacOS/Platform.cs
The return value of `await Page.Alert` was switched (returned true on no and false on yes). This PR fixes this bug.
> [macOS] Page.Alert return value fix

- Xamarin.Forms.Core/PlatformConfiguration/macOSSpecific/Page.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.MacOS/Renderers/PageRenderer.cs
This PR adds the option to set the tab order for elements on a page. After setting the tab order, you can cycle through these elements with the tab key.
`Page.On<macOS>().SetTabOrder(entry1, entry2, button1, ....)`
> [macOS] Set tab order (e.g. for entries) on a Page

- Xamarin.Forms.Platform.MacOS/Renderers/BoxViewRenderer.cs
This PR fixes the BoxViewRenderer. It used the incorrect BackgroundColor Property and not the Color Property.
> [macOS] BoxViewRenderer Color Fix

- Xamarin.Forms.Platform.MacOS/Renderers/TabbedPageRenderer.cs
When you use TabsStyle.OnNavigation or TabsStyle.Hidden, you have a small offset at the top. This PR fixes the bug.
> [MacOS] Tabbed Page Top Offset Fix

- Xamarin.Forms.Platform.MacOS/Controls/FormsImageView.cs
- Xamarin.Forms.Platform.MacOS/Renderers/ImageRenderer.cs
[macOS] Image Aspect Ratio Implementation
This PR implements image aspect ratios for macOS. NSImageView doesn't support AspectFill, like iOS. Therefore, I used a NSView with a CALayer to mimic a NSImageView.
Before this PR, the macOS platform didn't have image aspect ratios implemented.
> [MacOS] Image Aspect Fix

- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
The fix from #520 introduced a regression , since the flag _selectedFromNative was never set to true, so we were scrolling the item to the middle thinking it was  selected from the Forms side.
https://bugzilla.xamarin.com/show_bug.cgi?id=58283
> [iOS] Fix regression introduced on #520

- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Fixes issues where we leave some "state" on our ListViewSource 
https://bugzilla.xamarin.com/show_bug.cgi?id=32956  (iOS)
> [iOS] Clear state so we allow the SelectedItem to be set

- Xamarin.Forms.ControlGallery.Android/Properties/AssemblyInfo.cs
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.Android/_58406EffectRenderer.cs
- Xamarin.Forms.ControlGallery.WindowsUniversal/FocusEffect.cs
- Xamarin.Forms.ControlGallery.WindowsUniversal/Properties/AssemblyInfo.cs
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.ControlGallery.WindowsUniversal/_58406EffectRenderer.cs
- Xamarin.Forms.ControlGallery.iOS/Properties/AssemblyInfo.cs
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.iOS/_58406EffectRenderer.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45874.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla51505.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla56609.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla58406.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Effects.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/GalleryPages/ButtonGallery.cs
- Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs
- Xamarin.Forms.Platform.Android/FastRenderers/VisualElementRenderer.cs
Fixes a bug where Effects were never applied to the fast Label renderer on Android.
- [58406 – Effect is never attached to Label, but is attached to Label subclass (Android)](https://bugzilla.xamarin.com/show_bug.cgi?id=58406)
None
None
> Apply effects to fast renderers on Android

- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs
- Xamarin.Forms.ControlGallery.Android/Properties/AssemblyInfo.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/AndroidHelpText.cs
- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/GestureManager.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/VisualElementRenderer.cs
- Xamarin.Forms.Platform.Android/Flags.cs
- Xamarin.Forms.Platform.Android/Forms.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
- Xamarin.Forms.Platform.MacOS/Xamarin.Forms.Platform.macOS.csproj
- Xamarin.Forms.Platform.UAP/Flags.cs
- Xamarin.Forms.Platform.UAP/FormsUWP.cs
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
- Xamarin.Forms.Platform.WinRT.Tablet/Forms.cs
- Xamarin.Forms.Platform.iOS/Flags.cs
- Xamarin.Forms.Platform.iOS/Forms.cs
- Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
Add support for backwards-compatibility hint flags.
Added:
- `public static void SetFlags(params string[] flags)` 
Android fast renderers now require setting flag `FastRenderers_Experimental`.
> Add support for backcompat hint flags

- Xamarin.Forms.Platform.iOS/VisualElementTracker.cs
This PR fixes the autolayout engine exceptions thrown while running an application. The exceptions to not crash the application, but they show up in the console output.
The console output shows a lot of these exceptions:
```
tickerfeed[99161:30967911] This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.
Stack:(
0   CoreFoundation                      0x00007fffc6b9b57b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fffdbf5f1da objc_exception_throw + 48
2   CoreFoundation                      0x00007fffc6c18c55 +[NSException raise:format:] + 197
3   Foundation                          0x00007fffc87ee7d9 …
```
> [macOS] Autolayout Engine Exception Fix

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/RemovePageOnAppearing.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Remove unnecessary call to `ExecutePendingTransactions` which causes a "recursive entry to executePendingTransactions" error for Android Support libraries version 23 when removing a page from the navigation stack in response to another page's `Appearing` event. With Android Support libraries version 25 and up, this was throwing an exception with the error "FragmentManager is already executing transactions"; this change also fixes that issue.
- Problem caused by previous fix to [53179 – PopAsync crashing after RemovePage when support packages are updated to 25.1.1](https://bugzilla.xamarin.com/show_bug.cgi?id=53179#c42)
None
None
> Avoid exception when removing a page from navigation during Appearing handler

- Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
This PR implements/fixes the vertical text alignment in the Label Renderer for macOS.
> [macOS] Implements/Fixes Vertical Text Alignment in the Label Renderer

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla58645.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/RendererPool.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs
This fixes the same issue that was fixed by #894, except it includes scenarios where the `ItemTemplate`s have container `Element`s (e.g., `Grid`s).
This is related to the memory leak fixes in #524, which introduced disposal of the trial renderers that are created when measuring the height of a cell for a `ListView`. This eager disposal of the renderers and unhooking from the Elements was not yet accounted for in the `VisualElementRenderer` (fixed by #894) or the `VisualElementTracker` (fixed by this PR).
- [Bug 58645 - [iOS] NRE Thrown When ListView Items Are Replaced By Items With a Different Template](https://bugzilla.xamarin.com/show_bug.cgi?id=58645) **(regression in 2.3.5 prerelease)**
None
None
> [iOS] Prevent ListView HasUnevenRows crash when template w/container Element is swapped

- Xamarin.Forms.Platform.MacOS/ModalPageTracker.cs
- Xamarin.Forms.Platform.MacOS/PlatformNavigation.cs
- Xamarin.Forms.Platform.MacOS/PlatformRenderer.cs
ModalPages and their children did not resize, when you changed the size of the main window. This PR fixes this bug.
> [macOS] ModalPage Resize Fix

- .nuspec/Xamarin.Forms.nuspec
- .nuspec/Xamarin.Forms.props
- .nuspec/Xamarin.Forms.targets
By default, Compile/EmbeddedResource/None items are added to Sdk-style projects by wildcard. Use the same logic to add XAML files and fix up the item metadata.
No tests as there's no test infrastructure for the MSBuild targets.
Sdk-style (i.e. netstandard) projects that list these items explicitly will get an error about duplicate items and will have to remove them.
> Automatically add XAML items to Sdk-style projects

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44886.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/ListView.cs
- Xamarin.Forms.Platform.WinRT/ListViewRenderer.cs
Resolves regressions caused by #713.
Now calling `OnListItemClicked` when the native `ListView`s selection is changed and _not_ attempting to set the `SelectedItem` property of the `ListView` renderer at the same time. This was causing the second `ItemSelected` event to fire.
Calling `OnListItemClicked` when the selection changes ensures a consistent experience when using touch, mouse, keyboard, and Narrator navigation. UWP by default will select an item when it is focused by the keyboard, and using the spacebar/enter key will deselect the item. This PR preserves that default behavior. Deselecting an item will now fire an event, too, since that is a valid `SelectedItem` change. Note that this now allows the item returned by `Tapped` events to be null in these cases.
- [Bug 44886 - UWP …
> [UWP] ListView ItemSelected event will fire only once on selection changed

- Xamarin.Forms.Platform.Android/Renderers/TimePickerRenderer.cs
On Android, users who checked TimePicker.Time in the Unfocused event would get the previously set Time instead of the newly chosen one. This fixes the issue by setting the Time property before setting the IsFocused property and brings it in line with the behavior of [DatePicker](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/DatePickerRenderer.cs#L108). 
- https://bugzilla.xamarin.com/show_bug.cgi?id=58071
None
None
> [Android] Set TimePicker Time Before Unfocusing

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla58645.cs
Add preserve to see if it fixes the failing test
> [UITest] Fix failing test

- Xamarin.Forms.Platform.WinRT/SliderRenderer.cs
Setting the `BackgroundColor` on a `Slider` in UWP would also set it on the entire control's `Panel` via `UpdateBackgroundColor` in the `VisualElementRenderer`. Overriding this method on the renderer and removing the latter half of it prevents this from occurring, and only sets the color on the "rail" (`HorizontalTrackRect`) of the `Slider`, which is the correct behavior. No specific reproduction has been added as the behavior can be observed on the Slider Gallery page in the control gallery.
https://bugzilla.xamarin.com/show_bug.cgi?id=57787
None
None
> [UWP] Adjust setting of Slider's BackgroundColor

- Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/FormsEditText.cs
Restore the `EntryEditText` and `EditorEditText` classes to avoid breaking dependencies on them. Marks those classes as `Obsolete`.
- [58966 – [Android] EntryEditText and EditorEditText have been removed which is a breaking change](https://bugzilla.xamarin.com/show_bug.cgi?id=58966)
> [Android] Restore and obsolete EditorEditText and EntryEditText controls

- Xamarin.Forms.Platform.Android/Renderers/TimePickerRenderer.cs
A prior PR allowed for the use of 24-hour time on the `TimePicker`, but didn't set the text part of the control. While it's technically possible to add a test for this, it would be reliant upon knowing the setting of the device the test is being run on at the time, so it's been omitted for the moment.
https://bugzilla.xamarin.com/show_bug.cgi?id=54645
None
None
> [Android] Use 24-hour time format on TimePicker text if enabled

- .nuspec/Xamarin.Forms.DefaultItems.props
- .nuspec/Xamarin.Forms.DefaultItems.targets
- .nuspec/Xamarin.Forms.nuspec
- .nuspec/Xamarin.Forms.props
- .nuspec/Xamarin.Forms.targets
Fixes installing XF NuGet on VS2015
- https://forums.xamarin.com/discussion/101625/xamarin-forms-2-4-0-266-pre1-the-attribute-remove-in-element-is-unrecognized
- https://bugzilla.xamarin.com/show_bug.cgi?id=58897
- https://bugzilla.xamarin.com/show_bug.cgi?id=58893
None
None
> [Internal] Fix loading props file on older MSBuild versions

- Xamarin.Forms.Platform.Android.FormsViewGroup/Xamarin.Forms.Platform.Android.FormsViewGroup.csproj
Building Xamarin.Forms gives warnings such as:
```
BINDINGSGENERATOR (0, 0)
BINDINGSGENERATOR(0,0): Warning BG8800: Unknown parameter type
System.Xml.XmlReader in method CreateFromXml in managed type
Android.Content.Res.ColorStateList.
BINDINGSGENERATOR (0, 0)
BINDINGSGENERATOR(0,0): Warning BG8800: Unknown parameter type
System.Xml.XmlReader in method CreateFromXml in managed type
Android.Content.Res.ColorStateList.
BINDINGSGENERATOR (0, 0)
BINDINGSGENERATOR(0,0): Warning BG8800: Unknown parameter type
System.Xml.XmlReader in method ParseBundleExtras in managed type
Android.Content.Res.Resources.
BINDINGSGENERATOR (0, 0)
BINDINGSGENERATOR(0,0): Warning BG8800: Unknown parameter type
System.Xml.XmlReader in method CreateFromXml in managed type
Android.Graphics.Drawables.Drawable.
```
For …
> [android] fix binding warnings from FormsViewGroup

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla59097.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/InnerGestureListener.cs
Fix NRE when page is being disposed 
needs to be on 2.4.0
- https://bugzilla.xamarin.com/show_bug.cgi?id=59097
> [Android] Fix NRE when page is being disposed

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla58779.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.MacOS/Platform.cs
Xamarin Forms Mac OS X bug fix.
DisplayActionSheet shows a list of items the user can select from.
If the list is long (e.g. 15 items) the Popup went off the bottom of the Mac Desktop.
Not all items can be selected.
The cancel button goes off the bottom of the screen
Bugzilla 58779
None
A NSScrollView is used to allow long lists of items to fit on the Mac Desktop
> [MacOS] Fix bugzilla58779

- .nuspec/Xamarin.Forms.DefaultItems.props
- .nuspec/Xamarin.Forms.DefaultItems.targets
- .nuspec/Xamarin.Forms.props
- .nuspec/Xamarin.Forms.targets
Fixes issues in MSBuild evaluation order that caused the default items files to never get used.
N/A
N/A
N/A
> [Internal] Fix default items

- .nuspec/Xamarin.Forms.Debug.targets
- .nuspec/Xamarin.Forms.targets
- PagesGallery/PagesGallery.UWP/PagesGallery.UWP.csproj
- PagesGallery/PagesGallery/PagesGallery.csproj
- Xamarin.Forms.Build.Tasks/GetTasksAbi.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Generate errors at build if:
- multiple `Xamarin.Forms.targets` files are referenced
- the version of the `.targets` doesn't match the `Tasks.dll`
Note that this, as itself, is an ABI change and will generate its own lot of bug reports...
This PR was manually tested. No monkey was harmed during this process.
None. But will help debug user issues in the future.
/
/
> Better XF .targets errors reporting

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41424.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42074.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GestureBubblingTests.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/InputTransparentTests.cs
> [Tests] Fix UITests that are failing on API 19 android

- Xamarin.Forms.Platform.Android/Renderers/PickerRenderer.cs
This fixes a regression on Android pre-AppCompat where an app would crash if the Page's Content changed when a Picker was unfocused. No additional tests added since this was caught by existing ones.
- https://bugzilla.xamarin.com/show_bug.cgi?id=36681
None
None
> Prevent possible crash when Picker is unfocused in FormsApplicationActivity

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla59248.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/ListViewRenderer.cs
A previous change involving the accessibility implementation had an effect which prevented the enter key from firing `ItemTapped`. We are able to instead use `IsItemClickEnabled` and use earlier behavior to make sure that the selected item is updated correctly.
https://bugzilla.xamarin.com/show_bug.cgi?id=59248
None
None expected.
> [UWP] Use ItemClick to re-enable use of enter key for selection on ListView

- Xamarin.Forms.Platform.WinRT/DatePickerRenderer.cs
On UWP, if you try to set the DatePicker.MinimumDate to DateTime.MinValue when the UTC offset is positive an `ArgumentOutOfRangeException` is thrown because the time gets converted to UTC which makes it go out of range.
This fix catches the exception and specifies the date as UTC in order to prevent it from being converted.
- https://bugzilla.xamarin.com/show_bug.cgi?id=57855
None
None
> [UWP] Prevent crash when using DateTime.MinValue for DatePicker

- Xamarin.Forms.Platform.Android/ResourceManager.cs
Enables custom images (especially SVG) through the new IImageSourceHandler to work with tab bar icons on Android (like it does on iOS). And also on cell adapters and navigation page menu.
No test: there is no existing test for IImageSourceHandler (or can't find where).
None
None
> [Android] Enables custom images (especially SVG) through the new IImageSourceHandler

- Xamarin.Forms.Platform.WinRT/ImageRenderer.cs
Added Aspect.AspectFit to the aspect ratios that will center the image in the containing view.
https://bugzilla.xamarin.com/show_bug.cgi?id=58987
Changed:
- Xamarin.Forms.Platform.UWP.ImageRenderer.UpdateAspect 
This will center an Image in UWP when the image uses all of the default layout options, i.e. only an ImageSource is set, everything else is default. Before this PR, the image would be centered by default on Android and iOS but left or top aligned on UWP. 
My first PR so forgive me if I am not sure how to properly do 1, 2, and 4
Not sure best way to test this. 
- [*] Changes adhere to coding standard
> [UWP] Center Image when Aspect is Aspect.Fit (Bug 58987)

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla46363.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla58875.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs
- Xamarin.Forms.Platform.iOS/ContextScrollViewDelegate.cs
#578 added a static `WeakReference` to the `UIScrollView` to check against and prevent multiple `ContextAction`s from being activated at once. This was not being set to `null` on `Dispose`, so if the `ListView` was on a page that was popped and then pushed again, subsequent attempts to activate `ContextAction`s would fail, since the reference was now out of sync. Now nulling the static `WeakReference` to resolve this.
#885 built upon the original fix in #578, but as Ruddy2007 mentioned in that PR, this change caused possible `NullReferenceException`s. Added null checks to resolve this.
- [Bug 58875 - Back navigation disables Context Action in whole app, if Context Action left open](https://bugzilla.xamarin.com/show_bug.cgi?id=58875)
None
None
> [iOS] Can activate ContextActions on ListViews reliably again

- Xamarin.Forms.Core.UnitTests/DataTemplateSelectorTests.cs
- Xamarin.Forms.Core/DataTemplateExtensions.cs
- Xamarin.Forms.Core/DataTemplateSelector.cs
- Xamarin.Forms.Core/ElementTemplate.cs
- Xamarin.Forms.Core/ITemplatedItemsList.cs
- Xamarin.Forms.Core/ItemsView.cs
- Xamarin.Forms.Core/ListView.cs
- Xamarin.Forms.Core/ListViewCachingStrategy.cs
- Xamarin.Forms.Core/TemplatedItemsList.cs
- Xamarin.Forms.Platform.MacOS/Renderers/ListViewDataSource.cs
- Xamarin.Forms.Platform.iOS/ContextActionCell.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/DataTemplateExtensions.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/TemplatedItemsList`2.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ITemplatedItemsList`1.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ListViewCachingStrategy.xml
- docs/Xamarin.Forms.Core/index.xml
Expect when an iOS `ListView` with `HasUnevenRows` computes the row height for an appearing cell, that does not require creating a new iOS view. Actually, we've been creating a new view every time we compute the height. 
The fix is to create an iOS cell (prototypical cell) for each type of `ViewCell`, then when the height of a `ViewCell` of that type needs to be computed, get (or create) the prototypical cell, update it's BindingContext, measure its height, and return that result.
How the type of the `ViewCell` is determined depends on the caching strategy. 
* RecycleElement -> the `ViewCell` type key is the `DataTemplate`. 
* RecycleElementAndDataTemplate -> the `ViewCell` type is the CLR `Type` of the binding context retrieved out of the `ItemsSource`. This differs from `RecycleElement` …
> Add iOS prototypical cell cache for LV RowHeight calcs

- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
Expect all ListViewCachingStrategy tests to use bitwise operations after changing `ListViewCachingStrategy` enum to a flag. Actually, while trying to carve Android work out of the iOS work I cut too deeply and missed a few callsites in `ListViewAdapter.cs`. 
Continuation of #1143.
> [Android] Use bitwise ops on caching strategy in ListViewAdapter.cs

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla59580.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/CellAdapter.cs
Added null check in Xamarin.Forms.Platform.Android.CellAdapter and added call to _supportActionMode?.Invalidate()
https://bugzilla.xamarin.com/show_bug.cgi?id=56274
None
None
> [Android] - CanExecuteChanged raises a NullReferenceException

- Xamarin.Forms.ControlGallery.Android/Activity1.cs
- Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs
- Xamarin.Forms.ControlGallery.Android/FormsApplicationActivity.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/RestartAppTest.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Forms.cs
The first call to the `Forms.SetFlags` must come before `Forms.Init`; otherwise it throws an `InvalidOperationException`. However, Android apps can restart (and call `OnCreate` again) due to configuration changes (e.g., plugging in a hardware keyboard). The second call to `OnCreate` (and subsequent second call to `SetFlags`) was triggering the `InvalidOperationException` after a configuration change and crashing the application.
This change ensures that only the first call to `SetFlags` must come before `Init`; subsequent calls are ignored.
None
None
> Prevent Flags/IsInitialized check from crashing Android app on restart

- Xamarin.Forms.Core.UnitTests/BindableObjectUnitTests.cs
- Xamarin.Forms.Core/BindableObject.cs
[C] Use ReferenceEquals to compare BindingContext
This is a breaking behavioral change, but unlikely to affect anyone, and it puts us il line with other platforms supporting bindings.
- https://bugzilla.xamarin.com/show_bug.cgi?id=59507
/
While changing a BindingContext with overridden Equals(), Binding weren't updated. Some people might do that on purpose, but I really doubt it's the case...
> [C] Use ReferenceEquals to compare BindingContext **Behavior change**

- Xamarin.Forms.Build.Tasks/SetResourcesVisitor.cs
- Xamarin.Forms.Core.UnitTests/ResourceDictionaryTests.cs
- Xamarin.Forms.Core/ResourceDictionary.cs
- Xamarin.Forms.Xaml.UnitTests/MergedResourceDictionaries.xaml
- Xamarin.Forms.Xaml.UnitTests/MergedResourceDictionaries.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/SharedResourceDictionary2.xaml
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/FillResourceDictionariesVisitor.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/ResourceDictionary.xml
**NOTE0: this PR replaces #869**
**NOTE1: Do not squash merge to preserve author information. Thanks**
The addition of Multiple MergedDictionaries into ResourceDictionary, as discussed in the Evolution forum: https://forums.xamarin.com/discussion/86308/multiple-merged-dictionaries. Allows multiple ResourceDictionaries to be added to the VisualElement root Resources property.
- N/A
Added:
- ICollection<ResourceDictionary> MergedDictionaries // In ResourceDictionary.cs
The addition, of adding multiple ResourceDictionaries into a ResourceDictionary. No behavioral changes to existing functionality were made.
> [Evolution] Merged Dictionaries

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39331.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40173.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ButtonFastRendererTest.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TransparentOverlayTests.cs
- Xamarin.Forms.Core/AbsoluteLayout.cs
- Xamarin.Forms.Core/Grid.cs
- Xamarin.Forms.Core/PlatformConfiguration/AndroidSpecific/Elevation.cs
- Xamarin.Forms.Core/RelativeLayout.cs
- Xamarin.Forms.Core/StackLayout.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.Android/Elevation.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/BoxRenderer.cs
- Xamarin.Forms.Platform.Android/VisualElementExtensions.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/Elevation.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/AbsoluteLayout.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Grid.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/RelativeLayout.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/StackLayout.xml
- docs/Xamarin.Forms.Core/index.xml
Adds a platform specific value of `Elevation` (a `float?`) to `VisualElement` on Android. This allows the end user to control the immediate value of [Elevation](https://developer.android.com/reference/android/view/View.html#attr_android:elevation) on Android where necessary. 
This value has no effect on pre-Lollipop Android. 
- Allows users to fix Fast button renderer popping up 'above' elements which should be higher in the z-order (e.g., see tests for Bugzilla39331 and Bugzilla40173)
Added:
- `public static float? GetElevation(VisualElement element)`
- `public static void SetElevation(VisualElement element, float? value)`
- `public static float? GetElevation(this IPlatformElementConfiguration<Android, VisualElement> config)`
- `public static IPlatformElementConfiguration<Android, …
> [Android] Add platform specific for Elevation

- Xamarin.Forms.Platform.WinRT/VisualElementRenderer.cs
Moved the native control to add AFTER the events were attached to.  The issue was their render routines were being ignored because they had loaded during or shortly after the Children.Add causing the Loaded event to never be caught.  This fixes that issue.  All our views load perfectly now.
No need for tests, this is a simple and obvious change.
https://bugzilla.xamarin.com/show_bug.cgi?id=58630
None.
UWP Views will now update correctly when sizing the window, validation, to everyday loading of views.  You no longer need to force controls to update.
> [UWP] Controls are ignoring their rendering routines.

- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailContainer.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Calling `DisallowAddToBackStack()` is costing me more than 100 ms. I'm not sure why we need this. As per the [documentation](https://developer.android.com/reference/android/app/FragmentTransaction.html#disallowAddToBackStack()), this method throws an exception if we have already called `AddToBackStack()`. Since it doesn't throw an exception in our case, it means we haven't. I also searched the codebase for any references and did not find any. Another purpose of this method is to make sure any subsequent calls to `AddToBackStack()` will throw an exception so it acts as a safety check.
I think we could let go of this safety check because, if we call `AddToBackStack()`, I'd assume that it was on purpose.
I have tested `NavigationPage`. Please test MDP to make sure all is okay.
Also …
> [Android] Do not call DisallowAddToBackStack()

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla46363_2.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Cells/ViewCellRenderer.cs
The original fix for 46363 handled the case where a TapGesture was added to the top-level control inside of a DataTemplate; unfortunately, it missed the case where a TapGesture was added to a control nested deeper in the DataTemplate's hierarchy. This fix addresses the more general case. 
- [46363 – TapGestureRecognizer blocks List View Context Actions](https://bugzilla.xamarin.com/show_bug.cgi?id=46363#c14)
None
None
> [Android] Fix context action/tap gesture conflict when tap gesture is on nested view

- .nuspec/Xamarin.Forms.targets
Adds a ProjectCapability to the targets file so that tooling can pick up X.F. compatible projects in net standard projects.
None
None
None
> Add ProjectCapability to targets file

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla52487.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
Expect checking if a cell is enabled does not always create a new view. Actually, before the stop gap fix, we had been creating a new view, binding, then checking if the view is enabled. As views are checked all the time to see if they are enabled this was a big leak. 
The stop gap fix, which this fix replaces, was to create and cache a new view, `_enabledCheckCell`, and rebind that view to determine if a cell is enabled. That worked fine so long as all cells used the same type of view to render themselves. However, when a `DataTemplateSelector` is used, then different cells can use different views so its not sufficient to cache a single view. 
This fix caches the correct view for a given type of cell which can be repeatedly rebound and checked to see if it's enabled. How the type of a …
> [Android] Prototypical Cell Cache for IsEnabled testing; UITest

- Xamarin.Forms.Core/PlatformConfiguration/macOSSpecific/NavigationPage.cs
- Xamarin.Forms.Core/PlatformConfiguration/macOSSpecific/NavigationTransitionStyle.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.MacOS/Renderers/NavigationPageRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.macOSSpecific/NavigationPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.macOSSpecific/NavigationTransitionStyle.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.macOSSpecific/Page.xml
- docs/Xamarin.Forms.Core/index.xml
This PR adds the option to set the transition style on a NavigationPage for pushing and popping pages. (old request was https://github.com/xamarin/Xamarin.Forms/pull/1043). Now with docs. I also added the docs for the TabOrder Extension on macOS that I wrote. I didn't want to create a separate PR for this, but I can do it, if required.
On<Xamarin.Forms.PlatformConfiguration.macOS> ().SetNavigationTransitionStyle (NavigationTransitionStyle.Crossfade, NavigationTransitionStyle.SlideUp);
> [MacOS] Navigation Transition Style

- Xamarin.Forms.Platform.UAP/FormsTextBoxStyle.xaml
PR #882 made a change to the template for the `TextBox` control, but in cases where the TextBox/Entry had a tall height, it would only modify the vertical alignment of the the placeholder and not the actual text, as seen below:
After entering text, it would still appear the same as the first photo. By default a TextBlock in UWP will place both the text and placeholder text at the top. The original report mentioned a misalignment, but using its code compared to a default UWP TextBox of the same height looks to be virtually identical, with a pixel's difference if anything (in the below case, it is Forms UWP below standard UWP):
Ultimately we need to revert this original change because of the negative impact it has on the Entry.
https://bugzilla.xamarin.com/show_bug.cgi?id=60041
None
None
> Revert PR #882

- Xamarin.Forms.Platform.WinRT/LabelRenderer.cs
If a Label.FormattedText line contained a null (say from a binding), UWP would crash.
https://bugzilla.xamarin.com/show_bug.cgi?id=60002
None.
Using a null in a span of the Label.FormattedText property will now no longer crash UWP.
> [UWP] Fixed issue where Label.FormattedText was crashing.

- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailContainer.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Adds a check for `IsDestroyed` before cleaning up `MasterDetailContainer` in `Dispose()` to avoid the exception thrown in [59996](https://bugzilla.xamarin.com/show_bug.cgi?id=59996).
- [59996 – Race condition when disposing MasterDetailPageRenderer on Android app restart](https://bugzilla.xamarin.com/show_bug.cgi?id=59996)
None
None
> Checking IsDestroyed before using FragmentManager in Dispose()

- Xamarin.Forms.Core/Device.cs
- Xamarin.Forms.Platform.Android/Forms.cs
- Xamarin.Forms.Platform.WinRT.Tablet/Forms.cs
- Xamarin.Forms.Platform.iOS/Forms.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Device.xml
Expose the Flags to the Core, through Device
as we aren't sure yet if this is the best API ever, decorate it with a nice [STAND BACK] attribute
New API:
```
[EditorBrowsable(EditorBrowsableState.Never)]
public static IReadOnlyList<string> Device.Flags { get; private set; }
[EditorBrowsable(EditorBrowsableState.Never)]
public static void Device.SetFlags(IReadOnlyList<string> flags)
```
> [*] Expose the Flags to the Core

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla59863_0.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla59863_1.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla59863_2.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/GestureManager.cs
- Xamarin.Forms.Platform.Android/InnerGestureListener.cs
When an element has a TapGestureRecognizer with NumberOfTaps set to 1 (and no "double-tap" recognizer is present), tapping fast enough causes every other tap to be ignored. This is caused by confusion from the double-tap recognition component. This change addresses that scenario. 
- [59961 – TapGestureRecognizer with NumberOfTapsRequired="1" works only with double tap](https://bugzilla.xamarin.com/show_bug.cgi?id=59961)
- [59873 – Tap Gesture Recognizers not firing on frames](https://bugzilla.xamarin.com/show_bug.cgi?id=59873)
- *Possibly* [59863 – TapGestureRecognizer extremely finicky](https://bugzilla.xamarin.com/show_bug.cgi?id=59863). We'll need to get verification from Phillipp Sumi that this fixes his problem; other people jumped into the report and it's not clear if he was …
> [Android] Handle rapid taps when only single-tap recognizer is present

- Xamarin.Forms.Platform.MacOS/Renderers/CarouselPageRenderer.cs
- Xamarin.Forms.Platform.MacOS/Renderers/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.MacOS/Renderers/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.MacOS/Renderers/PageRenderer.cs
- Xamarin.Forms.Platform.MacOS/Renderers/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.MacOS/Renderers/TabbedPageRenderer.cs
In Xamarin.Forms.Platform.MacOS the PageRenderer and ScrollViewRenderer did not have the usual protected virtual methods OnElementChanged and OnElementPropertyChanged. They were private and partly wrong named. Therefore users could not inherit from those renderers and use them as every other renderer on every other platform.
Changed:
- PageRenderer: void OnElementChanged => protected virtual void OnElementChanged
- PageRenderer: void OnHandlePropertyChanged => protected virtual void OnElementPropertyChanged
- ScrollViewRenderer: void OnElementChanged => protected virtual void OnElementChanged
- ScrollViewRenderer: void HandlePropertyChanged => protected virtual void OnElementPropertyChanged
None
> [MacOS] make OnElementChanged and OnElementPropertyChanged protected virtual

- Xamarin.Forms.Core/BindableProperty.cs
- Xamarin.Forms.Core/Xaml/TypeConversionExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz59818.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz59818.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- Xamarin.Forms.Xaml/MarkupExtensions/StaticResourceExtension.cs
[Xaml] Chain op_implicit for OnPlatform (if flag is set)
NOTE: you have to set the flag "xamlDoubleImplicitOpHack" for this to work
For OnPlatform<T>, if a conversion for T to the destination type exists,
first convert OnPlatform<T> to T, the T to the dest type
Also unify the way we look for op_implicit operators
- https://bugzilla.xamarin.com/show_bug.cgi?id=59818
/
/
> [Xaml] Chain op_implicit for OnPlatform (if needed)

- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
Customer expected MainPage could be re-initialized after reloading app. Actually, existence of a renderer for the MainPage prevented MainPage from being attached the the new activity. This is "correct" (although still a regression) as the old MainPage renderer existed in a different context. 
The "fix" is to clear the MainPage renderer so a new renderer is created in the correct context. I say, "fix" because it does not reuse the existing renderer so the customer will not see the same performance benefit however it'll likely have saved the customer from even more insidious bugs stemming from using views from a deleted context. 
https://bugzilla.xamarin.com/show_bug.cgi?id=59882
None
Allow MainPage to be re-initialized after re-launch.
> Clear MainPage renderer if exists after reload

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60056.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/ViewToRendererConverter.cs
PR #731 intended to resolve an issue where `Label` text inside a `ListView` could vanish in certain circumstances. A side effect occurred in the change whereby inheriting from `Canvas` (which [uses absolute positioning](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Canvas#Remarks)) caused the outermost view to not respect margins given to it. Changing the inheritance of `WrapperControl` from `Canvas` to `Panel` appears to resolve this issue.
Before:
After:
https://bugzilla.xamarin.com/show_bug.cgi?id=60056
None
None
> [UWP] Inherit from Panel on WrapperControl

- EmbeddingTestBeds/Embedding.Droid/Embedding.Droid.csproj
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj
- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla57910.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/QuickCollectNavigationPage.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
- Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj
- Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
A continuation of #1063, this will do the same work for `HeaderTemplate` and `FooterTemplate`. Additionally, calling `RemoveAllViews` before calling `Dispose` is a terrible thing and leaves orphaned views behind. Also using a `_disposed` bool instead of checking for a non-null `HeaderView` just for added clarity and to prevent possible situations where everything may not be disposed.
- [Bug 48998 - Back on NavigationPage causes System.ObjectDisposedException](https://bugzilla.xamarin.com/show_bug.cgi?id=48998)
- [Bug 57910 - ObjectDisposedException in Xamarin.Forms.Platform.Android.Renderers.ProgressBarRenderer](https://bugzilla.xamarin.com/show_bug.cgi?id=57910)
- https://bugzilla.xamarin.com/show_bug.cgi?id=45330
None
None
> [Android] Prevent ObjectDisposedExceptions in ListViews with Header/FooterTemplates

- Xamarin.Forms.Platform.UAP/FormsTextBoxStyle.xaml
- Xamarin.Forms.Platform.WinRT/FormsTextBox.cs
The FormsTextboxStyle control template was applying the FocusForegroundBrush property to the textbox's ContentElement even when the textbox was not focused.  This caused the incorrect text color to be applied to the textbox when focus was lost. In "Light" mode, this is mostly okay because the two color values are the same, but in "Dark" mode the focus color matches the textbox background, so the text disappears.
This change removes the incorrect value from the style and adds some logic to fix the original problem the incorrect style attempted to address.
No automated tests, because we don't have a way to check for text color changes. To test manually, change `RequestedTheme="Light"` to `RequestedTheme="Dark"` in Control Gallery and run it, then browse to the Entry Gallery.
Before the …
> Stop forcing FormsTextBox content to ForegroundFocusBrush on UWP

- Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs
This issue only happens with the IOS11 SDK there no documentation about this changed, but seems be related to way UIView layouts respect size that fits now of controls. 
Tests are in our Searchbar View tests that were broken on iOS11
- https://bugzilla.xamarin.com/show_bug.cgi?id=59595
> [iOS11] Don't pass infinite value to UISearchBar width

- Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
- Xamarin.Forms.Core.UITests.Shared/Tests/ToolbarItemTests.cs
- Xamarin.Forms.Platform.iOS/Extensions/ToolbarItemExtensions.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
On iOS11 secondary buttons are rendererd off screen. We fix this by removing hardcoded values.
With change  (check iOS version on the details of the image)
> [iOS11] Fix Secondary toolbar items iOS11

- Xamarin.Forms.Platform.iOS/Forms.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs
There seems to be a issue with ScrollToRow on iOS11, there are other native users complain about similar issues:
https://stackoverflow.com/questions/46075517/uitableview-scrolltorow-no-longer-works-on-ios-11-right-after-adding-a-new-row
http://www.openradar.me/34865052
Adding a small delay just on iOS11 seems to fix the issue, also take note issue only is evidente when using ScrollTo with no animation
Also added the check just for iOS11 to UISearchBar fix i did on #1203
- Fixes 32462 test on iOS11
Internal API to check iOS11
Added:
- bool iOS11OrNewer { get ;}
> [iOS] Delay for ScrollTo to work on iOS11

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44886.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla59718.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/PlatformConfiguration/WindowsSpecific/ListView.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.WinRT/ListViewRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.WindowsSpecific/ListView.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.WindowsSpecific/ListViewSelectionMode.xml
- docs/Xamarin.Forms.Core/index.xml
#1133 switched UWP `ListViews` to use `ItemClick` instead of `Tapped` to enable the keyboard Enter key as a selector. However, this renders any `TapGestures` inside the `ListView` inoperable, since those events are not routed through a `Click`. This change will preserve the changes made in #1133 as default but allow the users to switch back to the legacy mode via a platform specific.
```
using Xamarin.Forms.PlatformConfiguration;
using Xamarin.Forms.PlatformConfiguration.WindowsSpecific;
_list.On<Windows>().SelectionMode(ListViewSelectionMode.Inaccessible);
```
#1005 was a partial fix for the `ItemSelected` event firing twice, but the test case was incomplete, so we did not resolve the entire issue. This should be fully resolved now.
- [Bug 59718 - Multiple issues with listview and …
> [UWP] Fix ListView selection issues **Behavior change**

- Xamarin.Forms.Platform.Android/GestureManager.cs
Forms is using a deprecated constructor for GestureDetector which doesn't load up the scaled version of the touch slop value. Because of this, some percentage of taps are being incorrectly recognized as fling gestures. This change updates to a Context-specific constructor which loads the correct touch slop value for the device.
(FTR, "touch slop" is [Android's term](https://android.googlesource.com/platform/frameworks/base.git/+/master/core/java/android/view/GestureDetector.java#419), not mine. But it _is_ fun to say.)
Whether a user encounters the bug depends on the device's physical size, display density, the user's finger size, and the user's tapping style. So automated tests for this are pretty much out of the question, unless we install varying sizes of robot fingers in the Test …
> [Android] Use non-deprecated constructor for GestureDetector

- Xamarin.Forms.Platform.UAP/FormsTextBoxStyle.xaml
For some reason #1190 didn't do what it was supposed to. For whatever reason the code that was supposed to be removed just got shuffled around.
https://bugzilla.xamarin.com/show_bug.cgi?id=60041
N/A
N/A
> Proper revert of PR #882

- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
Fix NRE introduced by 59882. Expect application can be null before OnStart is called. Actually, while fixing another bug, assumed it was non-null which caused NRE.
https://bugzilla.xamarin.com/show_bug.cgi?id=60337
None
None
> Fix NRE introduced by 59882

- Xamarin.Forms.Build.Tasks/XamlGTask.cs
- Xamarin.Forms.Core/Xaml/XamlResourceIdAttribute.cs
- Xamarin.Forms.Xaml.Xamlg/Xamlg.cs
- Xamarin.Forms.Xaml/XamlLoader.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.Xaml/XamlResourceIdAttribute.xml
[Xaml] create the [XamlResourceId] at assembly level
this allows, as before, finding the resource for a type, but also find the type of a resource or from a pack-like uri
> [Xaml] create the [XamlResourceId] at assembly level

- Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/RestartAppTest.cs
- Xamarin.Forms.Platform.Android/FormsApplicationActivity.cs
See also: https://github.com/xamarin/Xamarin.Forms/pull/1200
Customer expected MainPage could be re-initialized after reloading app. Actually, existence of a renderer for the MainPage prevented MainPage from being attached to the new activity. Preventing the MainPage from being attached is correct as the old MainPage renderer existed in a different context. 
The fix is to clear the MainPage renderer so a new renderer is created in the correct context. This fix will not reuse the existing renderer so the customer will _not_ see the same performance benefit as was achieved previously. However that performance gain was likely hiding more insidious bugs stemming from using views from a deleted context. 
https://bugzilla.xamarin.com/show_bug.cgi?id=59882
None
Allow MainPage to be …
> [Android] Clear MainPage renderer if exists after reload (non-appCompat)

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60382.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
Expected RecycleElement with null DataTemplateSelector to not throw exception on Android. Actually throws an exception. Simply, supply a dummy prototypical cell that does nothing (context insensitive).
Found while investigating 60382 (which turned out to be by design)
https://bugzilla.xamarin.com/show_bug.cgi?id=60382
None
None
> Allow RecycleElement with null Template

- docs/Xamarin.Forms.Core/Xamarin.Forms/BindingMode.xml
Fix a typo noticed in the [BindingMode API docs](https://developer.xamarin.com/api/field/Xamarin.Forms.BindingMode.OneWayToSource/).
none filed
not applicable
none
> [docs] BindingMode typo fix.

- Xamarin.Forms.Platform.MacOS/FormsApplicationDelegate.cs
Make sure we check if a MainMenu is provided via the storyboard
- 
None
User should now provided a Main.storyboard. the default template already has one so should be no issue
> [macOS] Handle case where no storyboard is provided for menus

- Xamarin.Forms.Controls/App.cs
- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/LargeTitlesPageiOS.cs
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/SafeAreaPageiOS.cs
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGallery.cs
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/LargeTitleDisplayMode.cs
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/NavigationPage.cs
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Page.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.iOS/Cells/CellRenderer.cs
- Xamarin.Forms.Platform.iOS/Cells/ViewCellRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/LargeTitleDisplayMode.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/NavigationPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/Page.xml
- docs/Xamarin.Forms.Core/index.xml
Fixes and new features for iOS11 support.
Platform specifics for `SafeArea`, `SafeAreaInsets`  and `LargeTitles`.
- https://bugzilla.xamarin.com/show_bug.cgi?id=60054
- https://bugzilla.xamarin.com/show_bug.cgi?id=59927
Added:
Page iOS Platform Specific
```
public enum LargeTitleDisplayMode
{
Automatic,
Always,
Never
}
public static readonly BindableProperty LargeTitleDisplayProperty = BindableProperty.Create(nameof(LargeTitleDisplay), typeof(LargeTitleDisplayMode), typeof(Page), LargeTitleDisplayMode.Automatic);
public static LargeTitleDisplayMode GetLargeTitleDisplay(BindableObject element)
public static void SetLargeTitleDisplay(BindableObject element, LargeTitleDisplayMode value)
public static IPlatformElementConfiguration<iOS, FormsElement> SetLargeTitleDisplay(this …
```
> [iOS] Fixes for iOS11 

- Xamarin.Forms.Platform.Android/Platform.cs
This changes one of the overloads of `CreateRenderer` to `internal` to avoid confusing the previewer during reflection. 
Trying this out as an alternative to #1233.
`public static IVisualElementRenderer CreateRenderer(VisualElement element, Context context)` =>
`internal static IVisualElementRenderer CreateRenderer(VisualElement element, Context context)`
Third-party code using `CreateRenderer` will not have access to the new version of the method for the time being. This is expected to have limited impact, as the new version of the method is only necessary to ensure controls work with multi-activity applications in embedding scenarios.
In the future, changes to previewer should allow us to make the overload public.
> [Android] Change overload of CreateRenderer to internal for previewer compatibility

- .gitignore
- Xamarin.Forms.Core/ITemplatedItemsList.cs
- Xamarin.Forms.Core/TemplatedItemsList.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/TemplatedItemsList`2.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ITemplatedItemsList`1.xml
- xtc-manual-ios.bat
Expect to be able to re-init ListView content. Actually, when using RetainElement, we experience an expectation due to use of a disposed view. The view in question was disposed by logic that used it to compute an estimated row height. That logic did expect the view to be recycled as part of pooling (resetting the Element). The fix is to allocate a view that does not participate in pooling.   
https://bugzilla.xamarin.com/show_bug.cgi?id=59813
None
None
> [Core, iOS] Allocate prototypical view for RetainElement

- Xamarin.Forms.Build.Tasks/XamlGTask.cs
[XamlG] only use forward slashes in XamlResource paths
> [XamlG] only use forward slashes in XamlResource paths

- Xamarin.Forms.Build.Tasks/XamlGTask.cs
when the targetPath contains a `\`, the output file name might end up wrong on Mac.
this fixes it
I'm not able to reproduce it in our test project, only on @davidortinau's.
- 🐞 ask @davidortinau
> [XamlG] do not mess with path separators

- Xamarin.Forms.Build.Tasks/DebugXamlCTask.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Build.Tasks/XamlGTask.cs
- Xamarin.Forms.Build.Tasks/XamlGenerator.cs
- Xamarin.Forms.Build.Tasks/XamlTask.cs
- Xamarin.Forms.Xaml.UnitTests/RDWithoutCodeBehind.xaml
- Xamarin.Forms.Xaml.UnitTests/SharedResourceDictionary.xaml
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml.UnitTests/XamlgFileLockTests.cs
- Xamarin.Forms.Xaml.UnitTests/XamlgTests.cs
- Xamarin.Forms.Xaml.Xamlg/Xamlg.cs
PR #1229 allowed the creation of RD without code behind (no `x:Class` and no `.xaml.cs` files). This PR piles on that one (only look at the latest commit while reviewing) and add a `xml` processing instruction to generate a phony codebehind with the right attributes so the XamlC will pick it up.
here's a very simple RD as example:
```
<?xml version="1.0" encoding="UTF-8" ?>
<?xaml-comp compile="true" ?>
<ResourceDictionary xmlns="http://xamarin.com/schemas/2014/forms"
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
<Style x:Key="foo" TargetType="Label">
<Setter Property="TextColor" Value="Orange" />
<Setter Property="Text" Value="Pumpkin" />
</Style>
</ResourceDictionary>
```
look at line 2 `<?xaml-comp compile="true" ?>`. This is what instructs XamlG to generate this file
``` …
```
> [XamlC] Compile RDs without codebehind

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla56771.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla59896.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
#948 added an informational exception to help users diagnose indexing issues when adding items. However, the logic throws unnecessarily when the ListView is grouped. This change will simply skip the index check if the ListView is grouped.
Also added a UI test for 56771 to ensure that this doesn't break the original intention of the informational exception.
- https://bugzilla.xamarin.com/show_bug.cgi?id=59896
None
None
> [iOS] Don't crash when grouped ListView uses ObservableCollection

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla31688.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/NavigationRenderer.cs
Don't try to specify a index that is out of bounds when popping pages 
https://bugzilla.xamarin.com/show_bug.cgi?id=31688
> [Android] Fix Index Out of Bounds when removing page on non AppCompact

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla36651.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/ScrollViewRenderer.cs
When items are being added into a ScrollView on WinRT/UWP, it can cause ScrollToAsync to fail, particularly when scrolling to the end, as the items are added but have not yet been laid out, leading to incorrect scroll values in OnScrollToRequested. It appears as if the Android implementation of the ScrollViewRenderer does something [similar](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs#L284-L292) by running a small delay of up to 10ms; a similar usage here appears to alleviate the problem while not affecting the previous behavior (based on the use of the control gallery's ScrollView page).
https://bugzilla.xamarin.com/show_bug.cgi?id=36651
Adjust OnScrollToRequested to use async
A very small 10ms addition which should …
> [WinRT/UWP] Add delay for layout in OnScrollToRequested

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla52299.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
When multiple entries are on a page in Android and the completion sends focus from one to another (e.g. Field One -> Field Two), it can skip to the next entry if the Enter key on a physical keyboard is pressed (e.g. Field One -> Field Three). Checking for the `KeyEventAction` being `Up` opposed to `Down` can help alleviate this.
- https://bugzilla.xamarin.com/show_bug.cgi?id=52299
None
None
> [A] Adjust Entry to avoid skipping upon completion via Enter key

- Xamarin.Forms.Platform.iOS/FormsApplicationDelegate.cs
This changes the way the window is used in iOS in a backwards compatible way.
It was not possible to swap out the current root for a native Xamarin ViewController, and then navigate back to a Forms one.
Also when changing the MainPage on a custom window it would crash because it would not implement PlatformRenderer. The new check prevents this.
Added:
- Window { get; set; }
This will not change any behaviour but just enable to work easier with Native views, especially in MvvmCross.
> Make it possible to customise the window on iOS

- Xamarin.Forms.Build.Tasks/CompiledConverters/RDSourceTypeConverter.cs
- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/XamlGTask.cs
- Xamarin.Forms.Build.Tasks/XamlGenerator.cs
- Xamarin.Forms.Core/ResourceDictionary.cs
- Xamarin.Forms.Xaml.UnitTests/AppResources/Colors.xaml
- Xamarin.Forms.Xaml.UnitTests/AppResources/CompiledColors.xaml
- Xamarin.Forms.Xaml.UnitTests/RDWithoutCodeBehind.xaml
- Xamarin.Forms.Xaml.UnitTests/ResourceDictionaryWithInvalidSource.xaml
- Xamarin.Forms.Xaml.UnitTests/ResourceDictionaryWithInvalidSource.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/ResourceDictionaryWithSource.xaml
- Xamarin.Forms.Xaml.UnitTests/ResourceDictionaryWithSource.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Fix an issue while trying to load a RD without code behind through Source.
- Always generate [XamlResourceId] even for RD without a x:Class
- throw a meaningful error if the RD isn't found.
- add more tests
- 🐞 add @davidortinau 
/
/
> [Xaml] fix loading RD without codebehind

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60524.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
#1226 improved the estimation for iOS row heights when `HasUnevenRows` is true, but it did not account for grouped `ListView`s using `DataTemplateSelector`s. This change will get the first item in the first group to inflate the `DataTemplate` instead of the first group.
- https://bugzilla.xamarin.com/show_bug.cgi?id=60524
None
None
> [iOS] Fix NRE when Grouped ListView w/DataTemplateSelector has uneven rows

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla49304.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/VisualElementTracker.cs
Using [`PlaneProjection`](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.PlaneProjection) when rotating a `FrameworkElement` prevents scroll functionality from working on `ScrollView`/`ListView`/`TableView`. Using [`CompositeTransform`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.compositetransform) instead allows this functionality to work as expected.
https://bugzilla.xamarin.com/show_bug.cgi?id=49304
None
Only a Z rotation isn't being applied, but it shouldn't matter in this case.
> [UWP] Use CompositeTransform for ScrollView/ListView/TableView to allow scrolling

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45702.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/App.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Moved code that removed fragments upon `NavigationPage` `dispose` to the end of method. This will allow children to be disposed before the fragments are removed so that when we call their `dispose` methods, we don't get an invalid handle exception.
- [Bug 45702 - Disabling back press on modal page causes app to crash](https://bugzilla.xamarin.com/show_bug.cgi?id=45702)
None
None
> [Android] Remove NavigationPage fragments after everything else is disposed 

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla123456.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla59925.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Platform.cs
- Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
Fix entry renderer font size
- https://bugzilla.xamarin.com/show_bug.cgi?id=59925
None
None
> [iOS] Fix entry renderer font size

- Xamarin.Forms.Build.Tasks/XamlGTask.cs
For some reason, `UpdateDesignTimeXaml` target doesn't set all the metadata we rely on for generating the file path. Use a hidden random file name instead. Those files won't anyway end up in the final build artifact.
- the one reported by @hartez 
/
/
> [XamlG] use random file names while used by UpdateDesignTimeXaml

- Xamarin.Forms.Platform.iOS/Extensions/FlowDirectionExtensions.cs
`UISemanticContentAttribute` was added in iOS9, so we need to avoid calling it in lower versions.
Continuation of #1222.
- Failing UI tests on master
None
Native controls on iOS <8 may not fully respect the `FlowDirection` value.
> [iOS] Check for iOS8 before changing control flow direction

- Xamarin.Forms.Core/AutomationProperties.cs
- Xamarin.Forms.Core/Internals/INamescopeProvider.cs
- Xamarin.Forms.Core/ReferenceTypeConverter.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Xaml.UnitTests/AutomationProperties.xaml
- Xamarin.Forms.Xaml/MarkupExtensions/ReferenceExtension.cs
- Xamarin.Forms.Xaml/Properties/AssemblyInfo.cs
- Xamarin.Forms.Xaml/XamlServiceProvider.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/AutomationProperties.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ReferenceTypeConverter.xml
- docs/Xamarin.Forms.Core/index.xml
this
```
AutomationProperties.LabeledBy="label"
```
is now a shortcut for
```
AutomationProperties.LabeledBy="{x:Reference label}"
```
/
Moved:
- Xamarin.Forms.Xaml.Internals.INameScopeProvider from Xaml to Core, with additional type forwarding for backward compat
Added:
- class ReferenceTypeConverter
/
> Allow specifying AutomationProperties.LabeledBy by name

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz60575.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz60575.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
The logic for adding elements to collection was always relying on a backing property, even for bindable. Those properties aren't obviously found for attached BPs. This PR fixes that.
- https://bugzilla.xamarin.com/show_bug.cgi?id=60575
> [Xaml[C]] allow adding elements to attached BP

- Xamarin.Forms.Platform.iOS/Cells/ViewCellRenderer.cs
Revert change  from #1238 related with ViewCell padding on iPhoneX. 
Users can use safe are from the `Page` to set padding on cells. 
**Before**
**After**
- https://forums.xamarin.com/discussion/comment/306004/#Comment_306004
None
Cells will not auto adjust to safe area, user is now responsible of handling the padding for now.
> [iOS] Revert iOS11 safe area fix on ViewCell

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Support of overriding of method "ShouldShowToolbarButton" in MasterDetailPage
Instead of setting toggle.DrawerIndicatorEnabled to true, it is now set to the
value which will returned by MasterDetailPage.ShouldShowToolbarButton();
https://bugzilla.xamarin.com/show_bug.cgi?id=60311
> [Android] Updated method "UpdateToolBar" in NavigationPageRenderer

- Xamarin.Forms.Build.Tasks/CompiledConverters/RDSourceTypeConverter.cs
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Core/Internals/ResourceLoader.cs
- Xamarin.Forms.Core/ResourceDictionary.cs
- Xamarin.Forms.Core/Xaml/IResourcesLoader.cs
- Xamarin.Forms.Core/Xaml/XamlResourceIdAttribute.cs
- Xamarin.Forms.Xaml.UnitTests/ResourceDictionaryWithSource.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/ResourceLoader.xaml
- Xamarin.Forms.Xaml.UnitTests/ResourceLoader.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/ResourcesLoader.cs
- Xamarin.Forms.Xaml/XamlLoader.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/ResourceDictionary.xml
[Xaml[C]] route loading of RD through ResourceLoader
- allows the Previewer to inject modified RD (without code-behind) without recompiling
- will allow CSS to work in the previewer
- add tests for ResourceLoader
/
ResourceLoader now takes a path (vs a ResourceId). That's no problem as it's internal API, and the previewer doesn't use that yet.
/
> [Xaml[C]] route loading of RD through ResourceLoader

- Xamarin.Forms.Build.Tasks/CompiledConverters/BindablePropertyConverter.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz60203.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz60203.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] fix parent walking in compiledBPConverter with ListNode
it's about time I kill the ListNode... but not this time, yet
- https://bugzilla.xamarin.com/show_bug.cgi?id=60203
/
/
> [XamlC] fix parent walking in compiled BPConverter with ListNode

- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/LargeTitlesPageiOS.cs
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGallery.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
Since on iOS11 the NavigationBar has a interaction with UIScrollView it will change it's size, Forms needs to be able to handle that. 
https://bugzilla.xamarin.com/show_bug.cgi?id=60659
BEFORE
AFTER
> [iOS] Fix issue when enabling SafeArea and scrolling 

- .nuspec/Xamarin.Forms.targets
On `netstandard` the imports are imported before the common targets (except with `package.config`).
As the default `*DependsOn` properties are not additive, our values gets replaced
```
Property reassignment: $(CoreCompileDependsOn)="_ComputeNonExistentFileProperty;ResolveCodeAnalysisRuleSet"
(previous value: "
XamlG;
;
") at /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Microsoft.CSharp.CurrentVersion.targets (175,9)
```
use AfterTargets and BeforeTargets to avoid that.
see also https://github.com/Microsoft/msbuild/issues/1468#issuecomment-269560176
/
/
/
> [Xaml] use [Before|After]Targets to avoid being overridden

- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
If the end user project type differs from Core's type, the compiler can
be confused while comparing base styles, like System.Double.
this fixes that by assuming System.Runtime, mscorlib and netstandard
types are equivalent (because they are)
/
/
/
> [XamlC] treat netstandard types as mscorlib

- Xamarin.Forms.Core.UnitTests/BindingBaseUnitTests.cs
[Tests] make sure the test pass even if the locale is wrongly implemented on the platform
win 10 creator update, against all odds and documentation, somehow decided that P2 formatting in English and invariant culture should be displayed `95.00%` and no longer `95.00 %` as it as the case before, and as documented (https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#PFormatString).
> [Tests] make sure the test pass even if the locale is wrong

- Xamarin.Forms.Core.UnitTests/BindingUnitTests.cs
- Xamarin.Forms.Core/BindableObject.cs
- Xamarin.Forms.Core/Binding.cs
- Xamarin.Forms.Core/BindingBase.cs
- Xamarin.Forms.Core/Element.cs
- Xamarin.Forms.Core/TemplateBinding.cs
- Xamarin.Forms.Core/TypedBinding.cs
- Xamarin.Forms.Pages/DataSourceBinding.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz34037.xaml.cs
[C] do not reapply a Binding with a Source:
- when the Context changes,
- the view is parented
- the inherited context changes.
- https://bugzilla.xamarin.com/show_bug.cgi?id=57081
/
/
> [C] do not reapply a Binding with a Source when the Context changes

- Xamarin.Forms.Platform.Android/Platform.cs
Restores two methods the XF previewer needs for compatibility.
> Restore a couple of internal methods for previewer compatibility

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Core/ResourceDictionary.cs
- Xamarin.Forms.Xaml.UnitTests/AutoMergedResourceDictionaries.xaml
- Xamarin.Forms.Xaml.UnitTests/AutoMergedResourceDictionaries.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/ResourceDictionary.xml
Allow RD to be implicitly merged, without declaring the MergedDictionaries property. This makes this Xaml valid
```
<ContentPage 
xmlns="http://xamarin.com/schemas/2014/forms"
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
x:Class="Xamarin.Forms.Xaml.UnitTests.AutoMergedResourceDictionaries">
<ContentPage.Resources>
<ResourceDictionary>
<Color x:Key="notpink">Purple</Color>
<Color x:Key="pink">Pink</Color>
<ResourceDictionary Source="AppResources/Colors.xaml" />
</ResourceDictionary>
</ContentPage.Resources>
<Label x:Name="label" TextColor="{StaticResource notpink}" BackgroundColor="{StaticResource Primary}"/>
</ContentPage>
```
- not breaking
- less verbose (combine with #1295)
- that syntax doesn't work on UWP 
/
Added:
- void ResourceDictionary.Add(ResourceDictionary);
/
> Auto merged ResourceDictionaries

- Xamarin.Forms.Platform.Android/Platform.cs
For previewer compatibility reasons, we were not able to make the new overload of `CreateRenderer` public. However, we also marked the old overload `Obsolete` with instructions to use the new overload, which is not accessible. This means that
1. Our obsolete message instructions are wrong
2. Third party controls with custom renderers can't work correctly with embedding in multi-activity applications 
3. People with "treat warnings as errors" turned on will have to disable the warning for the old overload
Eventually we will be making the new overload public, but until then we need to provide some way of accessing the correct overload. Thus, `CreateRendererWithContext`.
- [60815 – New CreateRenderer overload not public](https://bugzilla.xamarin.com/show_bug.cgi?id=60815)
- [60797 – New …
> Create renderer with context

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60524.cs
- Xamarin.Forms.Core/IListProxy.cs
- Xamarin.Forms.Core/ListProxy.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/IListProxy.xml
Expect adding two empty groups to a ListView won't crash app. Actually crashes. Test TryGetValue for null instead of indexing with bad index.
https://bugzilla.xamarin.com/show_bug.cgi?id=59896
None
None
> [Core, iOS] Fix 59896; Add empty listView group twice

- Xamarin.Forms.Build.Tasks/SetResourcesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz60788.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz60788.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/FillResourceDictionariesVisitor.cs
With changes introduced to FillRDVisitor, it can happen that nested RD are processed multiple times, hence creating duplicate keys. This prevents that.
**NOTE0**: this PR is against the 2.5.0 branch. once merged, it needs to be merged back to master.
**NOTE1**: should be included in next -sr
- https://bugzilla.xamarin.com/show_bug.cgi?id=60788
/
/
> [Xaml[C]] avoid processing nested RD multiple times

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60563.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
#524 added logic on iOS that will remove all `Subview`s of a `ListView` from their parents to prevent memory leaks. On iOS 8, this caused a SIGSEGV for `ActivityIndicator`s. The actual fault appears to be an iOS issue whereby the `UIActivityIndicatorView` is being accessed by the OS after it has been set to `nil` by `RemoveFromSuperview`. 
This change will adjust the aggressive `DisposeSubviews` method to only remove views that are not `IVisualElementRenderer`s, with the assumption that the renderers themselves should handle the disposal and removal of their own views. This effectively prevents the SIGSEGV by not calling `RemoveFromSuperview` on `ActivityIndicatorRenderer` and puts the onus on the renderers to take care of that.
- https://bugzilla.xamarin.com/show_bug.cgi?id=60563
None …
> [iOS] ListView should not explicitly remove subviews coming from renderers

- Xamarin.Forms.Platform.UAP/FormsTextBoxStyle.xaml
One more removal of bottom alignment re: #1220  to correctly fix placeholder.
https://bugzilla.xamarin.com/show_bug.cgi?id=60041
N/A
N/A
> [UWP] Entry alignment re-adjustment

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45125.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/ListView.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
`ListView` previously used `TitleForHeader` when using a `GroupDisplayBinding`. The downside to that is that it will not fire any event when it disappears. Now using a `HeaderView` in all cases so we can use `HeaderViewDisplayingEnded` to fire the `Disappearing` event. Also firing the `Appearing` event when the `HeaderView` is displayed.
- [Bug 45125 - ListView lacks a way to to get information about visible elements (such as FirstVisibleItem) to restore visual positions of elements](https://bugzilla.xamarin.com/show_bug.cgi?id=45125)
None; API changes requested in the Bugzilla ticket will need to be addressed at a later date.
None beyond that described above.
> [iOS] Grouped ListViews will use always HeaderView instead of TitleForHeader

- Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
While looking into a separate issue, a scenario was found where an empty `Picker` could be tapped/swiped at and then closed, causing a crash in `OnEnded` as it attempts to select row -1. 
The `Picker` page in the gallery is empty by default; attempting to reproduce the issue without this fix should cause a crash there.
N/A
None
I don't believe this should affect the original fix from #1054; only the scenario where the list is empty and nothing is selected.
> [iOS] Check for SelectedIndex value in OnEnded

- .nuspec/Xamarin.Forms.Maps.nuspec
- .nuspec/Xamarin.Forms.nuspec
Add Tizen related files (dll, pdb, xml) to nuget packages. 
- Xamarin.Forms.Platform.Tizen.dll, .pdb --> (tizen40) Xamarin.Forms.nupkg
- Xamarin.Forms.Maps.Tizen.dll, .pdb --> (tizen40) Xamarin.Forms.Maps.nupkg
- N/A
- N/A
Tizen app developer only needs to refer to Xamarin.Forms nuget package without Xamarin.Forms.Platform.Tizen.
> [Tizen] Add Tizen stuff to NuGet packages

- Xamarin.Forms.Core.UnitTests/BindingUnitTests.cs
- Xamarin.Forms.Core/BindingExpression.cs
Allow ValueTuple shorthand names to be used in Binding paths.
```
public class Person {
public (string First, string Last) Name { get; set; }
}
```
Allow this kind of Binding path
```
<Label Text="{Binding Name.First}" />
```
It also allows to bind to anonymous tuples using the indexer (that should have worked already, but wasn't). This is possible as ValueTuple implements `ITuple`.
```
<Label Text="{Binding Name[0]}" />
```
/
/
/
> [C] bind to ValueTuples

- Xamarin.Forms.Core/Point.cs
- Xamarin.Forms.Core/Rectangle.cs
- Xamarin.Forms.Core/Size.cs
- Xamarin.Forms.Core/Thickness.cs
- Xamarin.Forms.Core/VisualElement.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Point.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Rectangle.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Size.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Thickness.xml
[C] Adding deconstructors for common structs
/
Added:
- `Thickness.Decontruct(out double, out double, out double, out double)`
- `Rectangle.Decontruct(out double, out double, out double, out double)`
- `Point.Decontruct(out double, out double)`
- `Size.Decontruct(out double, out double)`
/
> [C] Adding deconstructors for common structs

- Xamarin.Forms.Core/PlatformConfiguration/AndroidSpecific/Application.cs
- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/WindowSoftInputModeAdjust.xml
Re-doing #917 without the platform specific.
- N/A
Added:
- `Unspecified` is an option for `WindowSoftInputModeAdjustProperty`
> [Android] Unspecified can be the default window soft input mode

- Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
iOS.PickerRenderer was attaching to EditingChanged, but it wasn't detaching from it.
- I didn't create any bug on Bugzilla, I just noticed it when adapting this component.
None.
None.
> [iOS] PickerRenderer EditingChanged detach

- Xamarin.Forms.Core/ImageSource.cs
- Xamarin.Forms.Platform.iOS/Forms.cs
As `GetCallingAssembly` wasn't available in PCL profiles, but actually there in all the final platforms we were using, we were finding it through reflection.
Now that we've moved to `netstandard2.0` that API is available. It also looks like the previous one could cause problems in some (new) conditions.
- fixes #1362 
/
/
> [C] no need to use reflection for GetCallingAssembly

- Xamarin.Forms.Controls/CoreGalleryPages/DatePickerCoreGalleryPage.cs
- Xamarin.Forms.Controls/CoreGalleryPages/PickerCoreGalleryPage.cs
- Xamarin.Forms.Controls/CoreGalleryPages/TimePickerCoreGalleryPage.cs
- Xamarin.Forms.Core/DatePicker.cs
- Xamarin.Forms.Core/Picker.cs
- Xamarin.Forms.Core/TimePicker.cs
- Xamarin.Forms.CustomAttributes/TestAttributes.cs
- Xamarin.Forms.Platform.Android/AppCompat/PickerRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/DatePickerRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/PickerRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/TimePickerRenderer.cs
- Xamarin.Forms.Platform.MacOS/Renderers/DatePickerRenderer.cs
- Xamarin.Forms.Platform.MacOS/Renderers/PickerRenderer.cs
- Xamarin.Forms.Platform.MacOS/Renderers/TimePickerRenderer.cs
- Xamarin.Forms.Platform.UAP/DatePickerRenderer.cs
- Xamarin.Forms.Platform.UAP/PickerRenderer.cs
- Xamarin.Forms.Platform.UAP/TimePickerRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/DatePickerRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TimePickerRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/DatePicker.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Picker.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/TimePicker.xml
As discussed [here](https://forums.xamarin.com/discussion/84742/add-ability-to-change-font-family-of-picker); this implements `IFontElement` on `Picker`, `DatePicker`, and `TimePicker`. The core gallery pages were updated to include these types.
https://bugzilla.xamarin.com/show_bug.cgi?id=50098
`IFontElement` is applied on the above three controls which includes:
- public static readonly BindableProperty FontAttributesProperty
- public static readonly BindableProperty FontFamilyProperty
- public static readonly BindableProperty FontSizeProperty
- public FontAttributes FontAttributes
- public string FontFamily
- public double FontSize
N/A
> [All] Implement IFontElement on Picker, DatePicker, and TimePicker

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Core/Xaml/TypeConversionExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh1346.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh1346.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Since the merge of #1176, the Xaml engine was calling op_implicit even if the property was assignable directly from the value. As reported in #1346, it is causing problems in some remote edge cases.
This PR adds a check for property assignability before considering using op_implicit
- fixes #1346
/
/
> [Xaml[C]] do not use implicit operator if the variable is assignable

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
When using either TransluscentStatus or TransluscentNavigation flags on Android the content will be layed out under the statusbar (not below as it would without them). This PR adds padding and height to NavigationBar if any of those flags are set. The padding is calculated based on the statusbar height.
Now we can finally use the flags mentioned on android to create stunning looking UI.
To use any of the flags just set this in MainActivity OnCreate()
```
Window.AddFlags(WindowManagerFlags.TranslucentNavigation);
Window.AddFlags(WindowManagerFlags.TranslucentStatus);
```
Before we added a statusbarunderlay = we couldnt layout stuff under the statusbar even with those flags, but that got removed in 2.3.4 (i think). Now the only thing stopping us is the adjusting padding and height, thats …
> [Android] AppCompat NavigationBar should handle Transluscent Flags

- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml.UnitTests/packages.config
- Xamarin.Forms.Xaml.Xamlc/Xamarin.Forms.Xaml.Xamlc.csproj
- Xamarin.Forms.Xaml.Xamlc/app.config
- Xamarin.Forms.Xaml.Xamlc/packages.config
- Xamarin.Forms.Xaml.Xamlg/Program.cs
- Xamarin.Forms.Xaml.Xamlg/Properties/AssemblyInfo.cs
- Xamarin.Forms.Xaml.Xamlg/Xamarin.Forms.Xaml.Xamlg.csproj
- Xamarin.Forms.Xaml.Xamlg/app.config
- Xamarin.Forms.Xaml.Xamlg/packages.config
moving the Build.Tasks to netstandard is probably fine. but the test project doesn't like it
> revert part of #1370. keep the test project out of netstandard for now

- Xamarin.Forms.Maps.Tizen/Xamarin.Forms.Maps.Tizen.csproj
- Xamarin.Forms.Platform.Tizen/Xamarin.Forms.Platform.Tizen.csproj
This PR is for using `GlobalAssemblyInfo` on `Xamarin.Forms.Platform.Tizen.csproj` and `Xamarin.Forms.Maps.Tizen.csproj`.
None
None
Tizen backend asssembly version will be detemined by GlobalAssemblyInfo
> Use GlobalAssemblyInfo on tizen backend

- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
iOS status bar color is being set when View is loading and when `BarTextColor` property changes. This means that if a page is popped off the stack, the status bar color is not syncing with the previous page.
See the changes made to bring `ViewWillAppear` into the equation.
Previously, users would have to set this color in `OnAppearing` via a message/dependency service call. I'm not sure if the current logic should stay intact or change.
Also note that there are other properties in `ViewDidLoad` that could potentially be updated in `ViewWillAppear`.
- https://bugzilla.xamarin.com/show_bug.cgi?id=60716
> [iOS] Update status bar color while page is appearing

- .nuspec/Xamarin.Forms.targets
Execute XamlG and XamlC either on [After|Before]Compile or on [Core]CompileDependsOn overrides. This allows building UWP Shared Assets Projects, as in those projects some compilation is done before the `BeforeCompile` target.
Make sure XamlC and XamlG are only ran once per project
- fixes #1358 
/
/
> [Xaml] execute XamlG and XamlC on UWP SAP

- Xamarin.Forms.Core.UnitTests/ColorUnitTests.cs
- Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
- Xamarin.Forms.Core/Color.cs
This change simplifies working with colors in a .NET Standard way by adding implicit conversion between the two color types:
```
Xamarin.Forms.Color c1 = Xamarin.Forms.Color.FromRgba(1, 1, 1, 1);
System.Drawing.Color c2 = c1;
Xamarin.Forms.Color c3 = c2;
if (c2 == c1)
{
// Colors are equal
}
```
This came out of this discussion: https://github.com/xamarin/Xamarin.Forms/pull/1306#issuecomment-350355271
- N/A
Added:
- `public static implicit operator System.Drawing.Color(Xamarin.Forms.Color color)`
- `public static implicit operator Xamarin.Forms.Color(System.Drawing.Color color)`
None.
> Add implicit color conversion to .NET Standard's System.Drawing.Color

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1326.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Cells/ViewCellRenderer.cs
`Label`s in a hierarchy that utilizes margins can sometimes wrap in a `ViewCell`, and the `ViewCell` will not appear to resize properly to contain the full text. This is because the `ViewCellRenderer` was not measuring its content with the content's `Margin`s, so the `ViewCell` thought it had enough room to display the text without wrapping, thus the `Height` was incorrect.
Now measuring the contents of a `ViewCell` with the `Margin`s included.
Before:
After:
- fixes #1326
None
It is possible for any `ViewCell` to be a different size now if the contents included `Margin`s. This should ideally lead to a better representation of the `ViewCell`'s true size.
> [iOS] Include margins when measuring ViewCell renderers

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1356.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
Per #1356, the when setting a ListView's SelectedItem while constructing the page, the item would be visually highlighted on Android/iOS, but not UWP. Some code existed previously in the ListViewRenderer that (at least for 8.1) allowed the behavior to function as expected, and appears to correct this particular issue.
#1356 
None
None
> [UWP] Set ListView SelectedItem when constructing page

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla57674.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
The ListView Renderer for UWP was not managing the OnCollectionChanged event.
Adding a new method and subscribing it to the respective handler to manage the OnCollectionChanged event
https://bugzilla.xamarin.com/show_bug.cgi?id=57674
None
None
> [UWP] Bug 57674 - XF.UWP ListView not honoring INotifyCollectionChanged 

- Xamarin.Forms.Platform.UAP/WindowsDeviceInfo.cs
UWP contains APIs relating to scale that aren't available on 8.1, namely `RawPixelsPerViewPixel` which simplifies getting the return value that we can use for the platform instead of checking `ResolutionScale` values.
https://bugzilla.xamarin.com/show_bug.cgi?id=59404
None
None
> [UWP] Use RawPixelsPerViewPixel for ScalingFactor

- Xamarin.Forms.Platform.iOS/PlatformRenderer.cs
UIApplication.StatusBarStyle is deprecated since iOS 9 (https://developer.apple.com/documentation/uikit/uiapplication/1622988-statusbarstyle) and doesn't work on Xamarin.Forms at all. If you use the black navigation bar style or a dark background color for the navigation page, the status bar always uses the default black color.
This PR simply redirects the calls to UIViewController.PreferredStatusBarStyle from the PlatformRenderer to the top view controller (NavigationRenderer or PageRenderer), therefore you can set the status bar color in your own renderer/ViewController:
```
public class ExtNavigationRenderer : NavigationRenderer
{
public override UIStatusBarStyle PreferredStatusBarStyle()
{
return UIStatusBarStyle.LightContent;
}
}
```
There should be none.
> [iOS] Redirect PreferredStatusBarStyle to the Child View Controller

- Xamarin.Forms.Platform.Tizen/Flags.cs
- Xamarin.Forms.Platform.Tizen/Forms.cs
Add support for backwards-compatibility hint flags for Tizen backend. This PR is extension of #1074 and #1181.
None
Added:
- `public static void SetFlags(params string[] flags)`
None
> [Tizen] Add support for hint flags for tizen backend

- Xamarin.Forms.Platform.Android/FastRenderers/AutomationPropertiesProvider.cs
- Xamarin.Forms.Platform.Android/ViewRenderer.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
Expected fast renderers to reuse slow renderer code where possible. Actually found duplication. This is an attempt to de-duplicate the automation code and establish a precedent for code reuse going forward.
> [Android] Deduplicate AutomationPropertiesProvider

- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
If the application creates too many DataTemplates, it will crash with a very weird exception like this:
`java.lang.ArrayIndexOutOfBoundsException: length=23; index=26`
I spent a few hours trying to figure this out. Basically, in my client's application `DateTemplateSelector` returned a new `DataTemplate` object on each `OnSelectTemplate` call. This caused `_dataTemplateIncrementer` to overflow and return an invalid `key`.
Descriptive Exception will be thrown instead of java.lang.ArrayIndexOutOfBoundsException
Not sure if needed
> [Android] Descriptive exception when ItemViewType >= ViewTypeCount

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60774.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60774_1.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60774_2.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/AHorizontalScrollView.cs
- Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
With `ScrollOrientation` set to `Both`, the `ScrollViewRenderer` and `AHorizontalScrollView` controls are forcing extra scrolling in the X/Y-direction rather then letting the base implementations take care of it, resulting in extra scrolling. This change removes the extraneous calls to `ScrollBy`.
Can't think of a way to reliably UI test this on Android at all resolutions. Manual test screens for horizontal, vertical, and diagonal scrolling are included
- [60774 – [Android] ScrollOrientation.Both doubles the distance of scrolling](https://bugzilla.xamarin.com/show_bug.cgi?id=60774)
None
None
> [Android] Remove extra scrolling when ScrollOrientation is Both

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Github1331.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Github1331.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Cells/ViewCellRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs
ViewCells on Android which have TapGestures on Views in their content have to handle the LongPress gesture (for context actions) manually; the LongClickListener is cancelled out by the listener for the TapGesture. The LongPress handling worked fine when the View with the TapGesture totally filled the ViewCell. But when only part of the ViewCell was filled, the remaining section of the ViewCell triggered the LongPress incorrectly (on a single tap). This change fixes that issue.
- [60850 – [Android] ViewCell containing View with TapRecognizer shows ContextActions on every tap](https://bugzilla.xamarin.com/show_bug.cgi?id=60850)
- [[Android] ViewCell shows ContextActions on tap instead of long press · Issue #1331 · xamarin/Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms/issues/1331) …
> [Android] Handle LongPress correctly in ViewCell with TapGesture content

- Xamarin.Forms.Platform.iOS/Extensions/ColorExtensions.cs
I've replaced the ToCGColor extension function so developers can get the desired color on controls that uses CGColor, for example Frame. No special tests needed since it depends on existing methods.
Can't find any specific bug report so far, but here is a library that shows the problem: https://github.com/GalaxiaGuy/xamarin-forms-frame-color
None.
None.
- [-] Has tests (if omitted, state reason in description)
> [iOS] CGColor creation fixed

- Xamarin.Forms.Maps.iOS/MapRenderer.cs
Expected to be able to reset a iOS map view pulled from the recycled pool but actually that threw an exception because recycled map views have null annotation arrays. Added a null check. Also had to disable the pool as the recycled map views failed to render. 
https://bugzilla.xamarin.com/show_bug.cgi?id=60140
None
None
> [iOS] Disable iOS Map pooling; Add null check

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1439.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WinRT/ListViewRenderer.cs
#1133 restored the ability to select items in a `ListView` with the Enter key on UWP. However, it did not take into account the change in item index when a `ListView` is grouped. This change will get the index of the selected item from the `ListView`'s `TemplatedItemsList`, which does take groups into account. Thank you to @r-a-y-w for researching this fix.
- fixes #1439 
- fixes #1401 (duplicate)
- https://bugzilla.xamarin.com/show_bug.cgi?id=60720
None
> [UWP] Grouped ListViews respond correctly to Tapped events

- Xamarin.Forms.Core.UnitTests/ButtonUnitTest.cs
- Xamarin.Forms.Core/Button.cs
When Button IsEnabled is false and invoked  IButtonController methods, the events and Commad.Execute do not fired.
- Commad.Execute is calling when invoke IButtonController.SendClicked and IsEnabled is false
(none)
(none)
> [Core] Fixed invocation of the IButtonController methods when IsEnabled is false

- Xamarin.Forms.Core/Element.cs
- Xamarin.Forms.Core/Element_StyleSheets.cs
- Xamarin.Forms.Core/StyleSheets/StyleSheet.cs
- Xamarin.Forms.Core/VisualElement.cs
- Xamarin.Forms.Core/VisualElement_StyleSheet.cs
Cells, and other Elements, are now part of the hierarchy used for setting down stylesheets,
- fixes #1472
/
/
> [CSS] Apply StyleSheets through Cells

- Xamarin.Forms.Platform.UAP/WindowsBasePlatformServices.cs
An issue exists where if a user is running an app in assigned access (kiosk) mode, calling DisplayAlert causes the application to crash. This is due to the current call on `IsInvokeRequired` checking `CoreApplication.MainView`; per the [MSDN docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/partnerapps/create-a-kiosk-app-for-assigned-access), it is instructed that you use `CurrentView` instead:
> Each view or window has its own dispatcher. In assigned access mode, you should not use the MainView dispatcher, instead you should use the CurrentView dispatcher.
A check on `IsInvokeRequired` was made to see if `LockApplicationHost.GetForCurrentView()` is null. If it is, then the current window is not running above lock (i.e. in the assigned access/kiosk mode) and …
> [UWP] Check LockApplicationHost/assigned access on IsInvokeRequired

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla55674.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/TabbedPageRenderer.cs
New PR for #922 which removes some now unnecessary code that was used for Win 8.1, per @rmarinho's request
https://bugzilla.xamarin.com/show_bug.cgi?id=55674
N/A
None
> [UWP] Use transparent as default TabbedPage bar background color (#922 reopen)

- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/ExpandMarkupsVisitor.cs
- Xamarin.Forms.Build.Tasks/SetFieldVisitor.cs
- Xamarin.Forms.Build.Tasks/SetNamescopesAndRegisterNamesVisitor.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/SetResourcesVisitor.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh1554.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh1554.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- Xamarin.Forms.Xaml/ExpandMarkupsVisitor.cs
- Xamarin.Forms.Xaml/FillResourceDictionariesVisitor.cs
- Xamarin.Forms.Xaml/NamescopingVisitor.cs
- Xamarin.Forms.Xaml/PruneIgnoredNodesVisitor.cs
- Xamarin.Forms.Xaml/RegisterXNamesVisitor.cs
- Xamarin.Forms.Xaml/XamlNode.cs
- Xamarin.Forms.Xaml/XamlNodeVisitor.cs
[Xaml[C]] avoid processing RD content multiple times
Stop the RD visitor on the RD node, as the SetPropVisitor is taking over
- fixes #1554
/
/
> [Xaml[C]] avoid processing RD content multiple times

- Xamarin.Forms.Core/BindablePropertyConverter.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh1566.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh1566.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[Xaml] do not check PropertyName on Obsolete BPs
- fixes #1566
/
/
> [Xaml] do not check PropertyName on Obsolete BPs

- Xamarin.Forms.Platform.UAP/ButtonRenderer.cs
On UWP, if you click around an app quickly, you can get it crash with this error:
> Xamarin.Forms.Platform.UAP.dll!Xamarin.Forms.Platform.UWP.ButtonRenderer.UpdateContent.AnonymousMethod__0(object sender, Windows.UI.Xaml.RoutedEventArgs args)
Since image loading is deferred, if you navigate quickly (or if you load the image from a slow source), the Xamarin.Forms element may no longer be present when `ImageOpened` is raised. The null check in this PR should fix that.
(I made the change in the GitHub web editor - since it's only one character. I haven't tested. The editor caused the newline change at the bottom of the file. No need to keep that change obviously.)
> Fix UWP button image rendering crash

- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Core/Internals/ResourceLoader.cs
- Xamarin.Forms.Xaml.UnitTests/ResourceLoader.xaml.cs
- Xamarin.Forms.Xaml/ResourcesLoader.cs
- Xamarin.Forms.Xaml/XamlLoader.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/ResourceLoader.xml
in addition to the resourcePath, tell the previewer the assembly in
which we're looking for the resource.
it changes an API that's not supposed to be used (yet) but the previewer, but I'd like @alanmcgovern approval on this.
/
Changed:
- `public static Func<AssemblyName, string, string> Xamarin.Forms.Internals.ResourceLoader.ResourceProvider { get; internal set; }`
> [Xaml] let the previewer know the asm

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1414.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/VisualElementPackager.cs
Fixes an issue in the iOS `VisualElementPackager` which allows recycled renderers to be assigned elements of the wrong type. The regression was caused by [this change](https://github.com/xamarin/Xamarin.Forms/pull/1136/files#diff-e7ceab256a6b8ec5ca5f9ddc81304defR16) which uses `_element` rather than `Renderer.Element` to look for child elements. When a renderer's element changes, `VisualElementPackager.SetElement` could [update the render pool](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/VisualElementPackager.cs#L160) before it [assigns `_element`](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/VisualElementPackager.cs#L178) which causes the wrong children to be compared.
This PR assigns `_element` earlier in …
> [iOS] Fix for assigning wrong element type to a recycled renderer

- Xamarin.Forms.Platform.UAP/PageRenderer.cs
If the `MainPage` of the application is set to a `NavigationPage`, the `Unloaded` event of the root `ContentPage`'s renderer fires incorrectly after the page loads. This only occurs on the first setting of `MainPage` - subsequent calls to set it work just fine.
This change adjusts the `PageRenderer` so that the `Unload` event is not tracked until the renderer has been `Loaded`, which prevents the renderer from incorrectly calling `SendDisappearing`.
Since this bug only occurs when an application sets `MainPage` for the first time, it's exceedingly awkward to UI test in ControlGallery.
- [60589 – Unexpected call to OnDisappearing on UWP when using NavigationPage](https://bugzilla.xamarin.com/show_bug.cgi?id=60589)
- [[UWP] Page.Disappearing is raised on the root page of a NavigationPage · …
> Don't hook up Unloaded handler in UWP PageRenderer until Loaded fires. fixes #1602

- Xamarin.Forms.Core/BindingExpression.cs
[C] fix and speed up binding to BP
That code path was no longer hit (name comparison was always false), so
I fixed it. The fix that gets the MethodInfo from the interface instead
of on the type speeds things up by a factor 6 (in my tests)
> [C] fix and speed up binding to BP

- Xamarin.Forms.Core/Xaml/TypeConversionExtensions.cs
This allows the use of dynamic types (non runtime types) to be used in binding.
- #1703 
None
Dynamic types can now be bound to.
> Use GetMethod instead of GetRuntimeMethod in TypeConversionExtensions

- Xamarin.Forms.ControlGallery.Android/Resources/anim/enter_from_left.xml
- Xamarin.Forms.ControlGallery.Android/Resources/anim/enter_from_right.xml
- Xamarin.Forms.ControlGallery.Android/Resources/anim/exit_to_left.xml
- Xamarin.Forms.ControlGallery.Android/Resources/anim/exit_to_right.xml
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.Android/_50787CustomRenderer.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla50787.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Redoing #661. 
Note that `TransitionDuration` must be overriden in a custom renderer to match durations in XML animation resource files so that pages disappear from the screen at the same time animations complete. I'm not sure if there is an API to extract durations from the resource files at runtime for us to sync `TransitionDuration` with those durations without having to set `TransitionDuration` manually. 
Also, another thing to note is it is possible for the page animation and the page removal timer to finish at different times even though they are expected to finish at about the same time since neither is probably guaranteed to finish in the given course of time. To guard for this, it might be a good idea to set `TransitionDuration` slightly higher than durations in resource files. I …
> [Android] Redo: Hide Fragments before removing them to allow custom animations

- Xamarin.Forms.Core/Registrar.cs
- Xamarin.Forms.Platform.Android/Platform.cs
- Xamarin.Forms.Platform.Android/ResourceManager.cs
- Xamarin.Forms.Platform.GTK/Cells/ImageCellRenderer.cs
- Xamarin.Forms.Platform.GTK/Controls/TableView.cs
- Xamarin.Forms.Platform.GTK/Platform.cs
- Xamarin.Forms.Platform.GTK/Renderers/ImageRenderer.cs
- Xamarin.Forms.Platform.GTK/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.GTK/Renderers/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.WPF/CellControl.cs
- Xamarin.Forms.Platform.WPF/Converters/ImageConverter.cs
- Xamarin.Forms.Platform.WPF/Platform.cs
- Xamarin.Forms.Platform.WPF/Renderers/ImageRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/Registrar`1.xml
Replace remaining uses of `GetHandler` with `GetHandlerForObject` so that IReflectableTypes can be used.
This is work that should have been done in #1006 but was missed.
- fixes #1712 
Added:
- `public T Registrar.GetHandlerForObject<T>(obj, args)`
> Use GetHandlerForObject instead of GetHandler

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1614.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/DatePickerRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TimePickerRenderer.cs
Address change in iOS 11 where InputAccessoryView is hidden by the InputView in landscape.
This fixes #1614 
None
The toolbar item (Done) will be visible while using a Picker, DatePicker or TimePicker on iOS 11 in landscape mode.
> [iOS] Fix Picker InputAccessoryView visibility in landscape

- Xamarin.Forms.Build.Tasks/CompiledConverters/RDSourceTypeConverter.cs
- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
[XamlC] get the Assembly through the TypeInfo
when an assembly object is required, XamlC was generating IL equivalent to the following c#
```
var asm = typeof(Foo).Assembly;
```
That API (the `Assembly` property) is not available in PCL profiles, but is always present at runtime. So there was no problem executing the code, but tools like CodeAnalysis were seriously confused.
The fix in this PR changes the generated code to the equivalent of
```
var asm = typeof(Foo).GetTypeInfo().Assembly;
```
Upgrading your projects from PCL to `netstandard2.0` would fix this as well.
- https://bugzilla.xamarin.com/show_bug.cgi?id=44130
/
/
> [XamlC] get the Assembly through the TypeInfo

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60001.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/DatePickerRenderer.cs
Changed the DateTimeOffset on DatePickerRenderer.UWP to create a new date based on an unspecified time zone.
https://bugzilla.xamarin.com/show_bug.cgi?id=60001
None.
The DatePicker on UWP should show the same value as the other OS's.  There may be other ways to fix this issue, maybe changing the other OS's to match UWP?  Or another way to reset the DateTimeKind.  This worked for us in a jiffy.
> [UWP] Fixed inconsistency on UWP's DatePicker and the other OS's.

- Xamarin.Forms.Core.UITests.Shared/Tests/AutomationIDUITests.cs
Making sure we test `AutomationId` on `ToolbarItems`. `AutomationId` is not supported on `ToolbarItems` on Android at this time, so this test is only for iOS.
None
None
None
> [Internal] Enable iOS test for AutomationId on ToolbarItems

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/InputTransparentInheritance.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/Layout.cs
- Xamarin.Forms.Core/VisualElement.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
- Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs
- Xamarin.Forms.Platform.UAP/VisualElementTracker.cs
- Xamarin.Forms.Platform.iOS/Platform.cs
- Xamarin.Forms.Platform.iOS/VisualElementTracker.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Layout.xml
By default, if a `Layout` is marked `InputTransparent`, its child controls are also `InputTransparent`. However, in some scenarios this behavior may not be desirable (e.g., control overlays). This change adds a boolean `InputTransparentInherited`. When set to true (the default), a `Layout`'s child controls are `InputTransparent` when the `Layout` is `InputTransparent`. When set to false, the `Layout`'s child controls are `InputTransparent` only if that property is explicitly set.
- [40967 – Layouts intercept all input on iOS.](https://bugzilla.xamarin.com/show_bug.cgi?id=40967)
- [60766 – AbsoluteLayout without background captures input on Android](https://bugzilla.xamarin.com/show_bug.cgi?id=60766)
Added:
`Xamarin.Forms.Layout` 
- `bool InputTransparentInherited { get; set; }` 
- …
> Allow Layouts to specify whether child controls inherit InputTransparent

- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
Bug Fix. Now working file.
fixes #1493
No change in API
Changed:
change in OnElementPropertyChanged() for Header change
From:
else if (e.PropertyName == ListView.HeaderProperty.PropertyName)
To:
else if (e.PropertyName == ListView.HeaderProperty.PropertyName || e.PropertyName == "HeaderElement")
{
UpdateHeader();
}
From:
else if (e.PropertyName == ListView.FooterProperty.PropertyName)
To:
else if (e.PropertyName == ListView.FooterProperty.PropertyName || e.PropertyName == "FooterElement")
{
UpdateFooter();
}
> [UWP] Update ListView header and footer fixes to #1493

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CascadeInputTransparent.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/Layout.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
- Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs
- Xamarin.Forms.Platform.iOS/Platform.cs
- Xamarin.Forms.Platform.iOS/VisualElementTracker.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Layout.xml
This is the property renaming I wanted to do in [1621](https://github.com/xamarin/Xamarin.Forms/pull/1621#issuecomment-362105404). 
`InputTransparentInherited` is confusing and doesn't really communicate what the property does. Changing it to the more descriptive `CascadeInputTransparent`.
> Rename InputTransparentInherited to CascadeInputTransparent
