- Xamarin.Forms.sln
Add Xamarin.Forms.Pages.Azure nuspec to sln , no need for tests.
> Add Xamarin.Forms.Pages.Azure nuspec to sln

- Xamarin.Forms.Core.UnitTests/SearchBarUnitTests.cs
- Xamarin.Forms.Core/ISearchBarController.cs
- Xamarin.Forms.Core/SearchBar.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.Android/Renderers/SearchBarRenderer.cs
- Xamarin.Forms.Platform.UAP/SearchBarRenderer.cs
- Xamarin.Forms.Platform.WP8/SearchBarRenderer.cs
- Xamarin.Forms.Platform.WinRT.Phone/SearchBarRenderer.cs
- Xamarin.Forms.Platform.WinRT.Tablet/SearchBarRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/ISearchBar.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ISearchBarController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/SearchBar.xml
Add ISearchBarController interface; update renderers to use interface.
> Prep SearchBar for removal of InternalsVisibleTo

- Xamarin.Forms.Core/IButtonController.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/IButtonController.xml
It was mostly already done; just needed to make IButtonController public
> Prep Button for removal of InternalsVisibleTo

- Xamarin.Forms.Core.UnitTests/NavigationUnitTest.cs
- Xamarin.Forms.Core/INavigationPageController.cs
- Xamarin.Forms.Core/Internals/NavigationRequestedEventArgs.cs
- Xamarin.Forms.Core/NavigationPage.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/Platform.cs
- Xamarin.Forms.Platform.Android/Renderers/NavigationRenderer.cs
- Xamarin.Forms.Platform.WP8/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.WinRT/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/NavigationRequestedEventArgs.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/INavigationPageController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/NavigationPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/NavigationRequestedEventArgs.xml
Add the INavigationPageController interface and update renderers to use it.
> Prep NavigationPage for removal of InternalsVisibleTo

- Xamarin.Forms.Core/IStreamImageSource.cs
- Xamarin.Forms.Core/StreamImageSource.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.Android/Renderers/StreamImagesourceHandler.cs
- Xamarin.Forms.Platform.WP8/ImageRenderer.cs
- Xamarin.Forms.Platform.WinRT/StreamImagesourceHandler.cs
- Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/IStreamImageSource.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/StreamImageSource.xml
Add IStreamImageSource interface; update renderers to use interface
> Prep StreamImageSource for removal of InternalsVisibleTo

- Xamarin.Forms.Core.UnitTests/MasterDetailFormUnitTests.cs
- Xamarin.Forms.Core/IMasterDetailPageController.cs
- Xamarin.Forms.Core/MasterDetailPage.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/Platform.cs
- Xamarin.Forms.Platform.Android/Renderers/MasterDetailContainer.cs
- Xamarin.Forms.Platform.Android/Renderers/MasterDetailRenderer.cs
- Xamarin.Forms.Platform.UAP/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.WP8/MasterDetailRenderer.cs
- Xamarin.Forms.Platform.WinRT/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PhoneMasterDetailRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/IMasterDetailPageController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/MasterDetailPage.xml
Created IMasterDetailPageController interface; updated renderers to use it.
> Prep MasterDetailPage for removal of InternalsVisibleTo

- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TableViewModelRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TableViewRenderer.cs
Copied some row height code from ListViewRenderer into TableViewRenderer.  Verified it works with sample test project provided in bug report.
https://bugzilla.xamarin.com/show_bug.cgi?id=39486
None
None
> Fix Bug 39486

- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/BaseDataSource.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/CardView.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/CompoundCollection.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/DataItem.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/DataPage.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/DataSourceBinding.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/DataSourceBindingExtension.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/DataView.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/DirectoryPage.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/HeroImage.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/IDataItem.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/IDataSource.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/IDataSourceProvider.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/JsonDataSource.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/JsonSource.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/JsonSourceConverter.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/ListDataPage.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/ListDataPageControl.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/ListItemControl.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/PersonDetailPage.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/StringJsonSource.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/UriJsonSource.xml
- docs/Xamarin.Forms.Pages/index.xml
- docs/Xamarin.Forms.Pages/ns-Xamarin.Forms.Pages.xml
> Initial add of Pages XML.

- .nuspec/Xamarin.Forms.nuspec
Add .mdb files to nuget to enable iOS debugging using private packages
> Add .mdb files to nuget to enable iOS debugging using private packages

- Xamarin.Forms.Platform.WinRT/ViewToRendererConverter.cs
- Xamarin.Forms.Platform.iOS/Cells/ViewCellRenderer.cs
Make sure the backend renderers implement the correct position and size of the View of a ViewCell
> Fix margins on ViewCell 

- docs/Xamarin.Forms.Core/Xamarin.Forms/Effect.xml
Added remarks to Effects summary.
> Added note to effects docs about Effects vs. Behaviors.

- docs/Xamarin.Forms.Core/Xamarin.Forms/Easing.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ScrollView.xml
Removed note about BounceIn not working properly. Fixed ScrollView example.
> Fixed code in Scrollview doc. Removed bug note in Easing.

- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/BaseDataSource.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/CardView.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/CompoundCollection.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/DataItem.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/DataPage.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/DataView.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/DirectoryPage.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/HeroImage.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/IDataItem.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/IDataSource.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/IDataSourceProvider.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/JsonDataSource.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/JsonSource.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/JsonSourceConverter.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/ListDataPage.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/ListDataPageControl.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/ListItemControl.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/PersonDetailPage.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/StringJsonSource.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/UriJsonSource.xml
About 1/3 to 1/2 of DataPages summaries. More to follow.
> DataPages docs.

- PagesGallery/PagesGallery/PagesGallery.csproj
Add missing reference to PagesGallery.csproj
> [Pages] Add reference to Xamarin.Forms.Build.Tasks

- docs/Xamarin.Forms.Core/Xamarin.Forms/ContentPage.xml
ContenPage => ContentPage in links
> Fixed typos in ContentPage.xml

- Xamarin.Forms.Android.UITests/Xamarin.Forms.Android.UITests.csproj
- Xamarin.Forms.Android.UITests/packages.config
- Xamarin.Forms.ControlGallery.iOS/CustomRenderers.cs
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.iOS/packages.config
- Xamarin.Forms.iOS.UITests/Legacy-PlatformHelpers.cs
- Xamarin.Forms.iOS.UITests/Xamarin.Forms.iOS.UITests.csproj
- Xamarin.Forms.iOS.UITests/packages.config
Fix use of internal extension methods
> [Controls] Fix use of internal extension methods

- docs/Xamarin.Forms.Core/Xamarin.Forms/PoppedToRootEventArgs.xml
- docs/Xamarin.Forms.Core/index.xml
> Update docs for PoppedToRootEventArgs

- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Unreported004.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Unreported004.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Get the right getter
- ask @samhouts 
Nada
> [XamlC] Fix the getter of getters

- Xamarin.Forms.Build.Tasks/DebugXamlCTask.cs
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
> [XamlC] fix a bug in the debugging code introduced last week

- docs/Xamarin.Forms.Core/Xamarin.Forms/Picker.xml
Typo fix in Picker.xml. Also reworded SelectedIndex remarks in same.
-  https://github.com/xamarin/documentation/issues/1508
> Fixed https://github.com/xamarin/documentation/issues/1508 (Picker.xml XAML members)

- docs/Xamarin.Forms.Core/Xamarin.Forms/ExportEffectAttribute.xml
> identifer => identifier in ExportEffectAttribute.xml

- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/McIgnorable.xaml
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
Ignore children nodes in an ignored element
none
> Fix mc ignorable

- docs/Xamarin.Forms.Core/Xamarin.Forms/Page.xml
Added note about line endings to Page.xml
> Added note about line endings to Page.xml.

- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/ILRootNode.cs
- Xamarin.Forms.Build.Tasks/SetNamescopesAndRegisterNamesVisitor.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/SetResourcesVisitor.cs
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Xaml.UnitTests/McIgnorable.xaml
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- Xamarin.Forms.Xaml/FillResourceDictionariesVisitor.cs
- Xamarin.Forms.Xaml/PruneIgnoredNodesVisitor.cs
- Xamarin.Forms.Xaml/Xamarin.Forms.Xaml.csproj
- Xamarin.Forms.Xaml/XamlLoader.cs
> Refix mc ignorable

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/SetValue.xaml
- Xamarin.Forms.Xaml.UnitTests/SetValue.xaml.cs
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/XmlName.cs
> Do not treat element with ignored children as collections

- docs/Xamarin.Forms.Core/Xamarin.Forms/Easing.xml
> Fixed SinInOut description.

- Makefile
Update Makefile to support linux enviroment as well. 
N/A
N/A
N/A
- [v] Has tests (if omitted, state reason in description)
- [v] Rebased on top of master at time of PR
- [v] Changes adhere to coding standard
- [v] Consolidate commits as makes sense
> Update Makefile to support linux env

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz43450.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz43450.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/MockCompiler.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] throw exception on missing property
[XamlC] instrument the compiler so we can unittest compile time exceptions
- https://bugzilla.xamarin.com/show_bug.cgi?id=43450
> [XamlC] throw exception on missing property

- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
- Xamarin.Forms.Platform.Android/FormsApplicationActivity.cs
- Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs
Fixes some warnings related with deprecated API's in Android
> [Android] Fix warnings

- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
do not `NoWarn` on release builds
> do not disable warning

- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43161.cs
Fix Failing UITEsts on android suite.
> [Android] Fix failing UITests

- Xamarin.Forms.Maps.Android/MapRenderer.cs
Just doing the reformat of Android's MapRenderer.cs that somehow got missed when we standardized everything else.
> Format MapRenderer according to project code style

- Xamarin.Forms.Build.Tasks/BindablePropertyReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/MethodReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Build.Tasks/PropertyDefinitionExtensions.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Core/IProvideValueTarget.cs
- Xamarin.Forms.Xaml.UnitTests/MarkupExpressionParserTests.cs
- Xamarin.Forms.Xaml.UnitTests/OnPlatform.xaml
- Xamarin.Forms.Xaml.UnitTests/OnPlatform.xaml.cs
- Xamarin.Forms.Xaml/MarkupExtensions/StaticResourceExtension.cs
- Xamarin.Forms.Xaml/XamlServiceProvider.cs
Implements TargetProperty for Value Converters consumption
Fix the issues with StaticResources consumed from one another in ResourceDictionaries
Also, removes another gross hack in StaticResourceExtension
- grep the forums for reference
> [XamlC] Implement IValueProvider.PropertyType

- Xamarin.Forms.Platform.WinRT/Xamarin.Forms.Platform.WinRT.csproj
enable native views and native bindings from xaml for WP
> [Xaml] Xaml native views and bindings for WP8.1

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
Just fix the linking on IOS gallery
> [Controls] Link only SDK so we don't brake the sample

- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
allow, e.g., converting to nfloat when using xaml nativeviews
> [Xaml] allow compatible arguments for x:Factory

- .gitignore
Added .bak extension to the .gitignore file.
N/A
N/A
N/A
> Add .bak extension to .gitignore

- .nuspec/Xamarin.Forms.nuspec
Include MacOS on nuspec pcl profile
> [Nuspec] Include MacOS

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42832.cs
Makes the UITest added in #310 only run on Android.
None
None
> Fix UITest for b#42832

- docs/Xamarin.Forms.Core/Xamarin.Forms/ActivityIndicator.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Application.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/BoxView.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Button.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/CarouselPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/DatePicker.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Editor.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Entry.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Frame.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IElementConfiguration`1.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Image.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Label.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ListView.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/MasterDetailPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/NavigationPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/OpenGLView.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Page.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Picker.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ProgressBar.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ScrollView.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/SearchBar.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Slider.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Stepper.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Switch.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/TabbedPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/TableView.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/TimePicker.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/WebView.xml
On&lt;T&gt; member summaries. (More platform-specific API docs to come.)
> On&lt;t&gt; summaries.

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44166.cs
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
Just modifying the test to reduce the number of places it could fail when querying for the GC button.
> Attempt to get UI test for 44166 working on iOS

- README.md
Update the badges on the readme to point to the current lanes.
> Update badge URLs to point at current build lanes

- docs/Xamarin.Forms.Core/Xamarin.Forms/AppLinkEntry.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Application.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/BindableProperty.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IAppLinkEntry.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IAppLinks.xml
Documentation for AppLinks, plus link fix.
> Applinks API docs, and a link fix in BindableProperty.xml.

- docs/Xamarin.Forms.Core/Xamarin.Forms/IApplicationController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IButtonController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ICellController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IElementController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IEntryCellController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IEntryController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IImageController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IItemViewController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ILayoutController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IListViewController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IMasterDetailPageController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IMenuItemController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/INavigationPageController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IOpenGLViewController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IPageController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IScrollViewController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ISearchBarController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ITableViewController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IViewController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IVisualElementController.xml
Marked all I___Controller interfaces for internal use by renderer (docs)
> Marked all I___Controller interfaces for internal use by renderer (docs)

- Xamarin.Forms.Controls/GalleryPages/ButtonGallery.cs
- Xamarin.Forms.Core.UnitTests/NotifiedPropertiesTests.cs
- Xamarin.Forms.Core/Button.cs
- Xamarin.Forms.Platform.WP8/ButtonRenderer.cs
- Xamarin.Forms.Platform.WinRT/ButtonRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ButtonRenderer.cs
port of an old fix
- https://bugzilla.xamarin.com/show_bug.cgi?id=40943
- https://bugzilla.xamarin.com/show_bug.cgi?id=30313
> [W] Support 0 as valid BorderWidth

- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/XamlGTask.cs
- Xamarin.Forms.Build.Tasks/XmlTypeExtensions.cs
- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Core/XmlnsDefinitionAttribute.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Issue1637.cs
- Xamarin.Forms.Xaml.UnitTests/LoaderTests.cs
- Xamarin.Forms.Xaml.UnitTests/TypeExtensionTests.cs
- Xamarin.Forms.Xaml/Properties/AssemblyInfo.cs
- Xamarin.Forms.Xaml/TypeArgumentsParser.cs
- Xamarin.Forms.Xaml/XamlParser.cs
- Xamarin.Forms.Xaml/XamlServiceProvider.cs
- Xamarin.Forms.Xaml/XmlnsHelper.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/XmlnsDefinitionAttribute.xml
- docs/Xamarin.Forms.Core/index.xml
- docs/Xamarin.Forms.Xaml/index.xml
internal changes, mostly. XmlnsDefinition are only looked for in XF assembly
Added:
- class XmlnsDefinitionAttribute
> [Xaml] cleanup xmlns usage, add XmlnsDefinition

- docs/Xamarin.Forms.Core/Xamarin.Forms/Button+ButtonContentLayout+ImagePosition.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Button+ButtonContentTypeConverter.xml
API docs: typo fixes in button nested classes docs
> API docs: typo fixes in button nested classes docs

- Xamarin.Forms.Platform.iOS/Platform.cs
Adds a call to hide the alert's UIWindow on iOS after alert is dismissed.
- Action Sheets and Alerts are not allowing any user input after being dismissed.
None
None
> Have PresentAlert hide new window when alert is dismissed

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla47295.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/MasterDetailControlStyle.xaml
- Xamarin.Forms.Platform.UAP/PageControlStyle.xaml
- Xamarin.Forms.Platform.UAP/TabbedPageStyle.xaml
> Jimmgarrido uwp toolbar

- docs/Xamarin.Forms.Core/Xamarin.Forms/ListView.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/MasterDetailPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/MenuItem.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/NavigationPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Page.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ScrollToRequestedEventArgs.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/SearchBar.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/StreamImageSource.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/TableView.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/VisualElement.xml
Last of Xamarin.Forms namespace internal doc items.
> Last of Xamarin.Forms namespace internal doc items.

- Xamarin.Forms.Platform.iOS/Renderers/PhoneMasterDetailRenderer.cs
Stumbled upon this while working on #563.
- N/A
> [iOS] Dispose tap gesture properly in phone master detail renderer

- docs/Xamarin.Forms.Core/Xamarin.Forms/ListStringTypeConverter.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/OnIdiom`1.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Picker.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/PoppedToRootEventArgs.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/SelectedPositionChangedEventArgs.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Style.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/TimePicker.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/VisualElement.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/DataSourceBinding.xml
- docs/Xamarin.Forms.Pages/Xamarin.Forms.Pages/DataSourceBindingExtension.xml
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml/BindingExtension.xml
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml/Extensions.xml
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml/XmlLineInfo.xml
Catch-up in Xamarin.Forms.[Core|Pages|Xaml]
> Catch-up in Xamarin.Forms.[Core|Pages|Xaml]

- Xamarin.Forms.Build.Tasks/XmlTypeExtensions.cs
- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
- Xamarin.Forms.Core/XmlnsDefinitionAttribute.cs
- Xamarin.Forms.Xaml/Properties/AssemblyInfo.cs
- Xamarin.Forms.Xaml/XamlParser.cs
- docs/Xamarin.Forms.Xaml/index.xml
you really do not want to know
- should fix the build 👊
> [Xaml] revert namespace change for XmlnsDefAttr

- Xamarin.Forms.Build.Tasks/CompiledConverters/ConstraintTypeConverter.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Core/ConstraintTypeConverter.cs
- Xamarin.Forms.Xaml.UnitTests/CompiledTypeConverter.xaml
- Xamarin.Forms.Xaml.UnitTests/CompiledTypeConverter.xaml.cs
[XamlC] Compile ContraintTypeConverters
> [XamlC] Compile ContraintTypeConverters

- docs/Xamarin.Forms.Core/Xamarin.Forms/ExportEffectAttribute.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Image.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/MasterDetailPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Picker.xml
- docs/Xamarin.Forms.Maps/Xamarin.Forms.Maps/MapType.xml
> Typos bug sweep.

- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml.UnitTests/XamlC/TypeReferenceExtensionsTests.cs
Test and fixes for TypeReferenceExtensions.
This is a more complete fix than #566, but because of the new exception being thrown, I do not feel confident about including this in a bug fix release.
> [XamlC] Type ref tests, and fixes

- Xamarin.Forms.Build.Tasks/MethodBodyExtensions.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
[XamlC] Optimize generated DT IL
this one is based on #611. merge #611 first.
> [XamlC] Optimize data template IL

- Xamarin.Forms.Build.Tasks/CompiledValueProviders/TriggerValueProvider.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Core/Interactivity/PropertyCondition.cs
- Xamarin.Forms.Core/Interactivity/Trigger.cs
- Xamarin.Forms.Xaml.UnitTests/TriggerTests.xaml.cs
Based on #622
Compiled version of Trigger iValueProvider
this was already covered by existing tests
> Xamlc compiled trigger

- Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/StaticExtension.cs
- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/MethodReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/BuiltInConversions.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Unreported008.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Unreported008.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Import types and methods on x:Static and factory methods
- https://forums.xamarin.com/discussion/comment/239842#Comment_239842
> [XamlC] import members on x:Static and factories

- Xamarin.Forms.Core.iOS.UITests/Tests/Legacy-CellsUITests.cs
Ignore this intermittent failure for now
> [iOS] Ignore intermittent failing test on XTC

- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Android.UITests/packages.config
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/packages.config
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/packages.config
> [UITest] Update to UITest 2.0.5

- Xamarin.Forms.Platform.MacOS/Cells/CellNSView.cs
- Xamarin.Forms.Platform.MacOS/Cells/NSTableViewCellStyle.cs
- Xamarin.Forms.Platform.MacOS/Cells/ViewCellNSView.cs
- Xamarin.Forms.Platform.MacOS/Renderers/ListViewRenderer.cs
> [MacOS] Context actions

- Xamarin.Forms.Controls/ControlGalleryPages/ToolbarItems.cs
- Xamarin.Forms.Core.iOS.UITests/Tests/ToolbarItemTests.cs
- Xamarin.Forms.Core.macOS.UITests/MacOSApp.cs
- Xamarin.Forms.Platform.MacOS/NativeToolbarTracker.cs
Adds fixes to MacOS toolbar items to support property changes, makes proper tests work for iOS and Android related with ToolbarItems
> [MacOS] Fixes to ToolbarItems

- .nuspec/Xamarin.Forms.nuspec
Nuget is not being generated correctly.
> [Nuget] Fix nuspec for macOS

- Xamarin.Forms.Platform.WinRT/WindowsBasePage.cs
Fixes crash in UWP designer
Internal
None
None
> Fix crash in UWP design mode

- Xamarin.Forms.Platform.iOS/Forms.cs
fix for https://bugzilla.xamarin.com/show_bug.cgi?id=29247
> [iOS,macOS] Use NSURL constructor from string to parse correctly the url string

- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Exposed UITableViewRow animations for inserting, deleting, reloading rows and reloading sections.
- None
Added:
- protected UITableViewRowAnimation InsertRowsAnimation
- protected UITableViewRowAnimation DeleteRowsAnimation
- protected UITableViewRowAnimation ReloadRowsAnimation
- protected UITableViewRowAnimation ReloadSectionsAnimation
So when you inherit from ListViewRenderer you can change those properties to change between animations for row actions.
Changed:
- None
No changes since the default value is UITableViewRowAnimation.Automatic
> [iOS] Expose row animation properties in ListViewRenderer

- Xamarin.Forms.Platform.MacOS/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.MacOS/Renderers/ScrollViewRenderer.cs
This PR adds vertical scrollbars to the ListView and ScrollView.
Before this PR, the macOS platform didn't show scrollbars at all.
> [macOS] Adds Scrollbars to ListViews and ScrollViews

- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/Application.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/TabbedPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/WindowSoftInputModeAdjust.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.WindowsSpecific/CollapseStyle.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.WindowsSpecific/MasterDetailPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.WindowsSpecific/Page.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.WindowsSpecific/ToolbarPlacement.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/BlurEffectStyle.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/Entry.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/NavigationPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/Page.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/Picker.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/StatusBarHiddenMode.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/StatusBarTextColorMode.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/UIStatusBarAnimation.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/UpdateMode.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/VisualElement.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration/Android.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration/Tizen.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration/Windows.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration/iOS.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IConfigPlatform.xml
> Platform-specifics API docs.

- Xamarin.Forms.Build.Tasks/CompiledConverters/BindablePropertyConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/StaticExtension.cs
- Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/TypeExtension.cs
- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Build.Tasks/XmlTypeExtensions.cs
- Xamarin.Forms.Xaml/MarkupExtensions/StaticExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/StaticResourceExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/TypeExtension.cs
Attribute some marker extension and compile them instead of evaluating them at runtime. This is mainly the infrastructure, more compiled markup will come next.
/
/
/
> [XamlC] compiled TypeExtension

- Xamarin.Forms.Build.Tasks/CompiledValueProviders/SetterValueProvider.cs
- Xamarin.Forms.Build.Tasks/CompiledValueProviders/TriggerValueProvider.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Unreported009.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Unreported009.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
...it's embarrassing, I don't really wanna talk about it
- the one reported by @jonathanpeppers 
/
/
> [XamlC] complete the Setter/Trigger fix

- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/CellExtensions.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/DynamicResource.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/EvalRequested.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/IDataTemplate.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/IDynamicResourceHandler.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/INameScope.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/InvalidationTrigger.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/NameScope.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/NavigationRequestedEventArgs.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/NotifyCollectionChangedEventArgsEx.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/NotifyCollectionChangedEventArgsExtensions.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/PreserveAttribute.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/Ticker.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/ToolbarTracker.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/TypedBindingBase.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/TypedBinding`2.xml
Marked Xamarin.Forms.Internal classes internal.
> Marked Xamarin.Forms.Internal classes internal in API docs.

- Xamarin.Forms.Controls/ControlGalleryPages/AccessibilityGallery.cs
Restore a11y gallery after a bad merge reverted it to an earlier state. 
N/A
N/A
N/A
> [Controls] Fix accessibility gallery

- Xamarin.Forms.Platform.iOS/Forms.cs
> [MacOS] Fix build

- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
Add ability to set internals for Flexlayout testing
> [IVT] Add IVT for testing FlexLayout

- docs/Xamarin.Forms.Core/index.xml
> [Docs] Fix docs editor

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.iOS/packages.config
Remove AdvancedColorPIcker component and use nuget
> [Controls] Remove dependency on Components

- docs/Xamarin.Forms.Core/Xamarin.Forms/Accessibility.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/BindableObject.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Device.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Frame.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IButtonController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IElementConfiguration`1.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IMessagingCenter.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/INavigationPageController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IPlatformElementConfiguration`2.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ITableModel.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ITemplatedItemsView`1.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Image.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ImageSource.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/MessagingCenter.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/NavigationPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/On.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/OnPlatform`1.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ResourceDictionary.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/TabbedPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/TabsStyle.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/VisualElement.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/WebView.xml
Remaining API docs for XF.Core
> Remaining API docs for XF.Core

- docs/Xamarin.Forms.Core/Xamarin.Forms/IMessagingCenter.xml
> [Docs] Fix formatting

- .nuspec/Xamarin.Forms.AppLinks.nuspec
Just fix the nuspec to work like the others on MonoDroid70
Will allow to upgrade google support packages
> [Nuget] Remove fix dependency on MonoDroid70

- Xamarin.Forms.Core/Button.cs
- Xamarin.Forms.Core/DatePicker.cs
- Xamarin.Forms.Core/Editor.cs
- Xamarin.Forms.Core/Entry.cs
- Xamarin.Forms.Core/ITextElement.cs
- Xamarin.Forms.Core/Label.cs
- Xamarin.Forms.Core/Picker.cs
- Xamarin.Forms.Core/SearchBar.cs
- Xamarin.Forms.Core/TextElement.cs
- Xamarin.Forms.Core/TimePicker.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.WP8/FontExtensions.cs
- Xamarin.Forms.Platform.WinRT/FontExtensions.cs
Similar to #783 but for sharing TextColorProperty
> [C] ITextElement and TextElement

- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific.AppCompat/Application.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/Entry.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.macOSSpecific/TabbedPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration/macOS.xml
- docs/Xamarin.Forms.Core/index.xml
PlatformConfiguration parameters and summaries. (Docs)
> PlatformConfiguration parameters and summaries. (Docs)

- Xamarin.Forms.Xaml.UnitTests/Issues/Bz53318.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz53318.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Nothing to see, only an additional test. I'll merge as soon as I got a green build.
- https://bugzilla.xamarin.com/show_bug.cgi?id=53318
/
/
> [test] passing test for 53318

- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml.Internals/NameScopeProvider.xml
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml.Internals/SimpleValueTargetProvider.xml
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml.Internals/XamlLoader.xml
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml.Internals/XamlServiceProvider.xml
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml.Internals/XamlTypeResolver.xml
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml.Internals/XmlLineInfoProvider.xml
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml.Internals/XmlNamespaceResolver.xml
Marked the Xaml.Internals members for internal use only.
None
> Internal-only boilerplate for Xaml.Internals docs.

- docs/Xamarin.Forms.Core/Xamarin.Forms.Xaml/AcceptEmptyServiceProviderAttribute.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Xaml/IMarkupExtension`1.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Xaml/IValueProvider.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Xaml/IXamlTypeResolver.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Xaml/IXmlLineInfoProvider.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Xaml/XamlParseException.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.Xaml/XmlLineInfo.xml
Remaining XAML API summaries.
None
> Remaining XAML API summaries.

- Xamarin.Forms.Platform.Android/AppCompat/PickerRenderer.cs
Fix NRE when pciker is dismissing
https://bugzilla.xamarin.com/show_bug.cgi?id=38723
**(needs to be backported to 2.3.4)**
> [Android] Fix NRE on Picker

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/CellAdapter.cs
- Xamarin.Forms.Platform.Android/Platform.cs
- Xamarin.Forms.Platform.Android/ResourceManager.cs
> [Android]Refactor to use a extension method to get the drawable

- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/ScrollView.xml
- docs/Xamarin.Forms.Core/index.xml
> [Docs] Fix docs Scrollview IOS Specific

- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/MethodDefinitionExtensions.cs
- Xamarin.Forms.Build.Tasks/MethodReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/XamlGTask.cs
- Xamarin.Forms.Xaml.UnitTests/GenericsTests.xaml
- Xamarin.Forms.Xaml.UnitTests/GenericsTests.xaml.cs
- Xamarin.Forms.Xaml/TypeArgumentsParser.cs
- Support x:Name attributes on types with generic type arguments
- Support factory methods with generic parameters
- crash nicely on undeclared xmlns prefix
- https://bugzilla.xamarin.com/show_bug.cgi?id=53503
/
/
> More Xaml generic support

- docs/Xamarin.Forms.Core/Xamarin.Forms/FormattedString.xml
Simpel spell correction
None.
None.
None.
> Spell correction of FromattedString

- Xamarin.Forms.Core.UnitTests/ResourceDictionaryTests.cs
- Xamarin.Forms.Core/ResourceDictionary.cs
- Xamarin.Forms.Xaml/MarkupExtensions/StaticResourceExtension.cs
[C] Lookup in RD also lookup in merged RDs
- not sure it's filled already
/
/
> [C] Lookup in RD also lookup in merged RDs

- README.md
Support was added in https://github.com/xamarin/Xamarin.Forms/pull/650
(https://github.com/xamarin/Xamarin.Forms/commit/52fc04724fc163c68c54cf33a5931871f8c1ee8e)
> README: add macOS to list of supported platforms

- Xamarin.Forms.Core/OnPlatform.cs
- Xamarin.Forms.Xaml.UnitTests/OnPlatform.xaml
- Xamarin.Forms.Xaml.UnitTests/OnPlatform.xaml.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/OnPlatform`1.xml
[Xaml] OnPlatform.Default value
Implements the proposal: https://forums.xamarin.com/discussion/93454/default-value-for-onplatform
Do not merge until the proposal is accepted
/
Added:
- public T OnPlatform<T>.Default { get; set; }
> [Xaml] OnPlatform.Default value

- Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs
Add disposed checks 
prevents chrash if object is disposed
None
None
- [ X] Rebased on top of master at time of PR
- [X ] Changes adhere to coding standard
- [X ] Consolidate commits as makes sense
> [Android] Add disposed check on FastRenderers.FrameRenderer

- docs/Xamarin.Forms.Core/Xamarin.Forms/Application.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/BindableObject.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Binding.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Color.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Device.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Element.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Grid.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ItemsView`1.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ListView.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/MenuItem.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/MultiPage`1.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/PlatformEffect`2.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/TableView.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/TapGestureRecognizer.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/UriImageSource.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/UrlWebViewSource.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/VisualElement.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/WebViewSource.xml
Marked a bunch of API docs internal based on EditorBrowsableState.
- [ x ] Rebased on top of master at time of PR
> Marked a bunch of API docs internal based on EditorBrowsableState

- docs/Xamarin.Forms.Core/Xamarin.Forms/TargetIdiom.xml
Touchup TargetIdiom docs to not imply that all UWP apps run on the desktop.
https://bugzilla.xamarin.com/show_bug.cgi?id=46372
None
None
> TargetIdiom docs touchup

- Xamarin.Forms.ControlGallery.iOS/CustomRendererBugzila38731.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla38731.cs
> [Controls] Fix test error

- .nuspec/Xamarin.Forms.Maps.nuspec
- .nuspec/Xamarin.Forms.Pages.Azure.nuspec
- .nuspec/Xamarin.Forms.Pages.nuspec
- .nuspec/Xamarin.Forms.nuspec
[nuget] shorten paths
- https://bugzilla.xamarin.com/show_bug.cgi?id=38336
/
/
> [nuget] shorten paths

- docs/Xamarin.Forms.Core/Xamarin.Forms/Aspect.xml
Added properly formatted remarks to Aspect.xml to allow tooling that expects valid ECMA XML to work. Passed `xmllint`, `xmlstarlet validate`, and `mdoc validate` in pre-commit hook
> Added missing/corrected malformed remarks sections in Aspect.xml

- docs/Xamarin.Forms.Core/Xamarin.Forms/AbsoluteLayout.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/AppLinkEntry.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Application.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Behavior.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Behavior`1.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/BindableProperty.xml
Removed deprecated code and edited remarks in:
AbsoluteLayout.xml, AppLinkEntry.xml, Application.xml, Behavior.xml, Behavior`1.xml, and BindableProperty.xml.
Passed local lints in pre-commit
> Updated example code in API docs for first few types in core.

- docs/Xamarin.Forms.Core/Xamarin.Forms/Device.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ListView.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ListViewCachingStrategy.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/VisualElement.xml
Minor doc updates in response to bugs. Passed local pre-commit linting.
> Bashing doc bugs.

- docs/Xamarin.Forms.Core/Xamarin.Forms/AppLinkEntry.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Application.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Behavior.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Behavior`1.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/BindableProperty.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Device.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ListView.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ListViewCachingStrategy.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/VisualElement.xml
> 2.3.4 2 cherry pick doc updates and doc bug fixes

- Xamarin.Forms.Maps.Tizen/FormsMaps.cs
- Xamarin.Forms.Maps.Tizen/GeocoderBackend.cs
- Xamarin.Forms.Maps.Tizen/MapRenderer.cs
- Xamarin.Forms.Maps.Tizen/Properties/AssemblyInfo.cs
- Xamarin.Forms.Maps.Tizen/Xamarin.Forms.Maps.Tizen.csproj
- Xamarin.Forms.Maps/Properties/AssemblyInfo.cs
- Xamarin.Forms.Tizen.sln
- docs/Xamarin.Forms.Maps/index.xml
This PR adds Xamarin.Forms.Maps.Tizen project.  
None
None
Xamarin.Forms.Maps APIs are available on Tizen platform.
> Add Xamarin.Forms.Maps.Tizen project

- docs/Xamarin.Forms.Core/Xamarin.Forms/Binding.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/BindingCondition.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/BindingTypeConverter.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/DataTrigger.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/MultiTrigger.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/PropertyCondition.xml
Trigger- and condition-related doc updates. Passed local xml linting.
> Updated some more code examples related to triggers and conditions.

- docs/Xamarin.Forms.Core/Xamarin.Forms/Device.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/EventTrigger.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/MasterDetailPage.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Trigger.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/TriggerAction`1.xml
- docs/Xamarin.Forms.Maps/Xamarin.Forms.Maps/MapSpan.xml
Fixed some broken links, added/updated examples in trigger-related docs. Passed local linting.
> Fixed some broken links, added/updated examples in trigger-related docs

- docs/Xamarin.Forms.Core/Xamarin.Forms/Animation.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/AnimationExtensions.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/AppLinkEntry.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Application.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Behavior.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Behavior`1.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Trigger.xml
- docs/Xamarin.Forms.Core/index.xml
Parameter complete drive and change to Trigger.xml. Passed local linting.
> Parameter complete drive and change to Trigger.xml

- Xamarin.Forms.Platform.Android/AppCompat/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ButtonRenderer.cs
Removed a couple debug statements from `ButtonRenderer`
N/A
N/A
> Remove debug outputs

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42620.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Parameterized UITest for Bugzilla 42620
None
None
None
> Make Grid.AddHz/Vt span ortho dim; UITest

- Xamarin.Forms.Core/DefinitionCollection.cs
Correctness change really. Still crashes due to invalid user behavior, but now with the right error.
None
None
None
> Fix DefinitionCollection index check order

- Xamarin.Forms.Platform.UAP/Properties/Xamarin.Forms.Platform.UAP.rd.xml
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
- Xamarin.Forms.Platform.WinRT/WindowsBasePlatformServices.cs
Adding the xaml assembly so reflection works.
Add reference on rd.xml to use Windows.UI.Xaml.
https://bugzilla.xamarin.com/show_bug.cgi?id=56795
> [UWP] Fixes for usage of XF with .net native toolchain

- Xamarin.Forms.Core.UnitTests/DatePickerUnitTest.cs
- Xamarin.Forms.Core.UnitTests/packages.config
- Xamarin.Forms.Pages.UnitTests/packages.config
- Xamarin.Forms.Xaml.UnitTests/GenericsTests.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/packages.config
Add nunit test adapter to hook tests to vsts
> [Tests] Add nunit test adapter

- Xamarin.Forms.Build.Tasks/XamlCTask.cs
When XamlC modifies a module, modify the module MVID too.
- https://bugzilla.xamarin.com/show_bug.cgi?id=57931
/
/
> [XamlC] change module MVID

- Xamarin.Forms.Core.UnitTests/MapTests.cs
- Xamarin.Forms.Maps.Android/MapRenderer.cs
- Xamarin.Forms.Maps.UWP/MapRenderer.cs
- Xamarin.Forms.Maps.WP8/MapRenderer.cs
- Xamarin.Forms.Maps.WinRT.Tablet/MapRenderer.cs
- Xamarin.Forms.Maps.iOS/MapRenderer.cs
- Xamarin.Forms.Maps/Geocoder.cs
- Xamarin.Forms.Maps/Map.cs
- Xamarin.Forms.Maps/Pin.cs
- Xamarin.Forms.Maps/Properties/AssemblyInfo.cs
- docs/Xamarin.Forms.Maps/Xamarin.Forms.Maps/Geocoder.xml
- docs/Xamarin.Forms.Maps/Xamarin.Forms.Maps/Map.xml
- docs/Xamarin.Forms.Maps/Xamarin.Forms.Maps/Pin.xml
- docs/Xamarin.Forms.Maps/index.xml
This PR is an extension of the #782 for Xamarin.Forms.Maps.
None
None. The public surface area we support is unchanged.
None. The change should result in no behavioral changes.
> Remove InternalsVisibleTo from Maps

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz57574.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz57574.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Allow generic EventArgs
- https://bugzilla.xamarin.com/show_bug.cgi?id=57574
/
/
> [XamlC] resolve generic EventArgs

- Xamarin.Forms.Platform.MacOS/Renderers/ProgressBarRenderer.cs
Fix Progress bar always 100%
- https://bugzilla.xamarin.com/show_bug.cgi?id=58318
> [Mac] Fix ProgressBar

- Xamarin.Forms.Platform.Android.FormsViewGroup/Xamarin.Forms.Platform.Android.FormsViewGroup.csproj
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Update warnings to ignore so we can build without issues on Beta channel 15.4 preview 5.
> [Android] Update Android warnings to ignore for now

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
Added:
- string ListView.GroupName { get; set; } //Bindable Property
- int ListView.GroupId { get; set; } // Bindable Property
- void ListView.Clear ();
Changed:
- object ListView.SelectedItem => Cell ListView.SelectedItem
> remove provision

- README.md
Adding some instructions to the readme for customizing Visual Studio for Mac style preferences.
- [none] Has tests
> added styling instructions for Visual Studio for Mac

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ButtonFastRendererTest.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/ButtonBackgroundTracker.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/Platform.cs
- Xamarin.Forms.Platform.Android/VisualElementPackager.cs
Fix missing states on fast button renderer
> [Android] Fix missing shadow on Button fast renderer

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.iOS/packages.config
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ButtonFastRendererTest.cs
- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Android.UITests/packages.config
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/packages.config
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/packages.config
- Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
- Xamarin.Forms.Core.macOS.UITests/packages.config
> [UITest] Fix FastRenderer test for iOS

- Xamarin.Forms.Platform.Android/Platform.cs
Fix regression fromn #1034 
- https://bugzilla.xamarin.com/show_bug.cgi?id=58868
> [Android] Fix bugzilla58868

- Xamarin.Forms.Platform.iOS/Forms.cs
We were missing the query in our generated url 
https://bugzilla.xamarin.com/show_bug.cgi?id=59101
> [iOS] Make sure to include query path on generated url

- Xamarin.Forms.Platform.Android/VisualElementPackager.cs
Fix a possible leak on the VisualElementPackager with CompressedLayout changes
> [Android] Make sure to clean the element reference

- PagesGallery/PagesGallery.iOS/PagesGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.iOS/packages.config
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla51173.cs
- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Android.UITests/packages.config
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/packages.config
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/packages.config
- Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
- Xamarin.Forms.Core.macOS.UITests/packages.config
Update UITest packages to support iOS11
Update UITest to scroll so it can find element with result after tap
> [UITests] Update packages, fix failing test

- .nuspec/Xamarin.Forms.targets
> [Nuget]Fix condition to import DefaultItems.targes

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Android.UITests/packages.config
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/packages.config
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/packages.config
- Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
- Xamarin.Forms.Core.macOS.UITests/packages.config
> [UITests] Update uitest dev packages ios11

- Xamarin.Forms.Build.Tasks/CompiledConverters/BindablePropertyConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledValueProviders/SetterValueProvider.cs
- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/SetResourcesVisitor.cs
- Xamarin.Forms.Build.Tasks/XamlGTask.cs
- Xamarin.Forms.Build.Tasks/XamlTask.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz27299.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz42531.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Issue2114.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/MergedResourceDictionaries.xaml
- Xamarin.Forms.Xaml.UnitTests/TypeConverterTestsLegacy.cs
- Xamarin.Forms.Xaml.UnitTests/X2009Primitives.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- Xamarin.Forms.Xaml/ExpandMarkupsVisitor.cs
- Xamarin.Forms.Xaml/FillResourceDictionariesVisitor.cs
- Xamarin.Forms.Xaml/HydrationContext.cs
- Xamarin.Forms.Xaml/NamescopingVisitor.cs
- Xamarin.Forms.Xaml/PruneIgnoredNodesVisitor.cs
- Xamarin.Forms.Xaml/RegisterXNamesVisitor.cs
- Xamarin.Forms.Xaml/Xamarin.Forms.Xaml.csproj
- Xamarin.Forms.Xaml/XamlLoader.cs
- Xamarin.Forms.Xaml/XamlNodeVisitor.cs
- Xamarin.Forms.Xaml/XamlParser.cs
- Xamarin.Forms.Xaml/XamlServiceProvider.cs
- Xamarin.Forms.Xaml/XmlName.cs
Fixes some possible bugs introduced by the hack in #1138. Refactors the RD visitors to reuse the logic in other visitors.
This is based on #1138, and need to be rebased when the other PR is merged.
/
/
/
> [Xaml/XamlC] better RD inflation

- .nuspec/Xamarin.Forms.nuspec
Add missing file to pcl target
- Build error in PCL
None
None
> Fix nuspec file to install DefaultItems.targets in PCL projects

- Xamarin.Forms.Build.Tasks/CompiledConverters/UriTypeConverter.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Core/UriTypeConverter.cs
compiled version of the UriTypeConverter
/
/
/
> [XamlC] Compiled UriTypeConverter

- Xamarin.Forms.Platform.MacOS/Renderers/ScrollViewRenderer.cs
This PR fixes the bug that a ScrollView automatically scrolls to the top when its size changes.
> [macOS] ScrollView Resize Fix

- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
Leave out UITest.
Added:
- string ListView.GroupName { get; set; } //Bindable Property
- int ListView.GroupId { get; set; } // Bindable Property
- void ListView.Clear ();
Changed:
- object ListView.SelectedItem => Cell ListView.SelectedItem
> Prototypical Cell Cache for IsEnabled testing

- .nuspec/Xamarin.Forms.AppLinks.nuspec
- .nuspec/Xamarin.Forms.Maps.nuspec
- .nuspec/Xamarin.Forms.nuspec
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- PagesGallery/PagesGallery.Droid/packages.config
- Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj
- Stubs/Xamarin.Forms.Platform.Android/packages.config
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.Android/packages.config
- Xamarin.Forms.Maps.Android/MapRenderer.cs
- Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
- Xamarin.Forms.Maps.Android/packages.config
- Xamarin.Forms.Platform.Android.AppLinks/AndroidAppLinks.cs
- Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj
- Xamarin.Forms.Platform.Android.AppLinks/packages.config
- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
- Xamarin.Forms.Platform.Android/packages.config
Working from #1037 ad updating packages and nugets for testing.
Updating AppLinks 
Update support libs for Android 
Update GooglePlayServices for Maps
> [Android] Applinks firebase 42

- EmbeddingTestBeds/Embedding.Droid/Embedding.Droid.csproj
- EmbeddingTestBeds/Embedding.Droid/packages.config
Update embedding project package versions to match rest of solution
- Build is broken
None
None
> Update embedding package version

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39530.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2272.cs
- Xamarin.Forms.Controls/HanselForms/BlogPage.xaml.cs
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Controls/packages.config
- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Android.UITests/packages.config
- Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/packages.config
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/packages.config
- Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
- Xamarin.Forms.Core.macOS.UITests/app.config
- Xamarin.Forms.Core.macOS.UITests/packages.config
> [Packages] Update UITest and consolidate packages

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/DesktopSupportTestPage.cs
- Xamarin.Forms.Platform.MacOS/Extensions/NSMenuExtensions.cs
- Xamarin.Forms.Platform.MacOS/FormsApplicationDelegate.cs
Fix top main menu error when menu changes and a NRE related with shortcuts
> [MacOS] Fix Menus

- Xamarin.Forms.Core/MasterDetailPage.cs
By default we want to show the Master on MacOS, it's up to the user to provide UI to hide it
Master page will be shown by default on MacOS desktop app.
> [Core]Set default value for IsPresented on MacOS

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla37841.cs
If all goes good make iOS11 test lane green
> [UITests] Make test work on iOS11

- Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs
Just some info on the gallery when using Fast Renderers flag
> [Controls] Add info  when using FastRenderers

- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Page.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/Page.xml
Hide SetSafeAreaInsets
user's won't be able to set safe area insets
> [Core] Hide SetSafeAreaInsets

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40161.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41415.cs
- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Android.UITests/packages.config
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/packages.config
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/packages.config
- Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
- Xamarin.Forms.Core.macOS.UITests/packages.config
> [UITest] Try dev uitest for api25 fixes

- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
> [build] avoid retries on copy

- Xamarin.Forms.Core/Cells/EntryCell.cs
- Xamarin.Forms.Core/Entry.cs
- Xamarin.Forms.Core/ITextAlignmentElement.cs
- Xamarin.Forms.Core/Label.cs
- Xamarin.Forms.Core/SearchBar.cs
- Xamarin.Forms.Core/TextAlignmentElement.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
use a single BP for all HorizontalAlignmentProperty. required for css styling
/
/
/
> [C] unify HorizontalTextAlignmentProperty

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40704.cs
> [UITest] Fix issue with scrolling velocity on iOS11

- Xamarin.Forms.Xaml/XamlLoader.cs
[Xaml] do not report unhandled node on XmlDeclaration
> [Xaml] do not report unhandled node on XmlDeclaration

- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Android.UITests/packages.config
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/packages.config
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/packages.config
- Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
- Xamarin.Forms.Core.macOS.UITests/packages.config
> [UITest] Update UITest package to 2.2.1.1670-dev

- Xamarin.Forms.Core/Frame.cs
- Xamarin.Forms.Core/IPaddingElement.cs
- Xamarin.Forms.Core/Layout.cs
- Xamarin.Forms.Core/PaddingElement.cs
- Xamarin.Forms.Core/Page.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
[C] unify Padding into IPaddingElement
changes required to support Padding in CSS
/
/
/
> [C] unify Padding into IPaddingElement

- Xamarin.Forms.Core/BindingExpression.cs
[C] fix an issue with netstnadard when context type is object
/
/
/
> [C] fix an issue with netstandard when context type is object

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz60575.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Bz60575.xaml.cs
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
Add test, and fix the case, when the collection defined by an attached BP has a single element.
- some additional cases for 60575
/
/
> Fix bz60575 again

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.iOS/packages.config
Update uitest test cloud agent to 0.21.3
> [UITest] Update TestCloud agent  0.21.3

- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Build.Tasks/packages.config
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml.UnitTests/packages.config
- Xamarin.Forms.Xaml.Xamlc/Xamarin.Forms.Xaml.Xamlc.csproj
- Xamarin.Forms.Xaml.Xamlc/packages.config
[XamlC] update cecil to 0.10-b7
/
/
/
> [XamlC] update cecil to 0.10-b7

- Xamarin.Forms.Platform.Android/Platform.cs
Restores the ability for the previewer to set its own Context for each page being rendered.
> [Android] Allow Previewer to set a per-page Context

- Makefile
> [docs] update Makefile to use msbuild and local version

- Xamarin.Forms.Platform.UAP/FormsTextBoxStyle.xaml
Re-target of #1286 to 15-5 branch.
> [UWP] Entry alignment re-adjustment

- Xamarin.Forms.Core/PaddingElement.cs
- Xamarin.Forms.Core/View.cs
expose the various margin properties as BP, so the style engine can set them
/
/
/
> [C] expose margin properties to css

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla58779.cs
Make sure to close action sheet
> [UITests] Try fix uitests iOS

- Xamarin.Forms.Xaml/ViewExtensions.cs
- docs/Xamarin.Forms.Xaml/Xamarin.Forms.Xaml/Extensions.xml
- docs/Xamarin.Forms.Xaml/index.xml
This should never ever be used as a mechanism for loading your application screens.
It might be used if you're writing tools and IDE that generates xaml.
> [Xaml] open the api for loading xaml from string

- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Core/BindingExpression.cs
Backporting #1281 and #1282 to 15-5
This PR has been manually tested, as our test projects aren't netstandardized yet.
- fixes #1316, fixes #1368
/
/
> Fix for netstandard projects

- EmbeddingTestBeds/Embedding.Droid/Embedding.Droid.csproj
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
- Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
- docs/Xamarin.Forms.Core/Xamarin.Forms/Color.xml
Added:
- string ListView.GroupName { get; set; } //Bindable Property
- int ListView.GroupId { get; set; } // Bindable Property
- void ListView.Clear ();
Changed:
- object ListView.SelectedItem => Cell ListView.SelectedItem
> Bump submodule

- Xamarin.Forms.Platform.WPF/FormsTimePicker.cs
- Xamarin.Forms.Platform.WPF/Properties/AssemblyInfo.cs
- Xamarin.Forms.Platform.WPF/Renderers/TimePickerRenderer.cs
- Xamarin.Forms.Platform.WPF/Xamarin.Forms.Platform.WPF.csproj
Added a simplistic TimePicker.
None
None
A simplistic TimePicker will now show up and obey the correct TimeFormat.  Our users like to enter the text rather than have a pop up.  If a popup is needed in the future, or a drop down that can be done.
> [WPF] Added a simplistic TimePicker.

- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh1497.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh1497.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml.UnitTests/XamlC/TypeReferenceExtensionsTests.cs
[XamlC] resolve generic types with generic and non-generic parameters
- fixes #1497
/
/
> [XamlC] resolve generic types with generic and non-generic parameters

- Xamarin.Forms.Xaml/ResourcesLoader.cs
[CSS] allow the previewer to intercept the load call earlier
/
/
/
> [CSS] allow the previewer to intercept the load call earlier

- Xamarin.Forms.Platform.Android/Platform.cs
Null check casts to Activity from Context in Platform
Theoretically fixes #1407
> [Android] Don't assume casts to Activity from Context will be successful

- Xamarin.Forms.Core.UnitTests/StyleSheets/StyleTests.cs
- Xamarin.Forms.Core/Element_StyleSheets.cs
[C] Cascade StyleSheets defined at Application level
- fixes #1553
/
/
> [C] Cascade StyleSheets defined at Application level

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/BindingsCompiler.xaml
- Xamarin.Forms.Xaml.UnitTests/BindingsCompiler.xaml.cs
[XamlC] TypedBindings to self for value types
- fixes #1603
/
/
> [XamlC] TypedBindings to self for value types

- Xamarin.Forms.Xaml/XmlName.cs
[Xaml] fix inconsistency in XmlName
- fixes #1640
> [Xaml] fix inconsistency in XmlName

- .nuspec/Xamarin.Forms.Debug.targets
- .nuspec/Xamarin.Forms.targets
- Xamarin.Forms.Build.Tasks/CssGTask.cs
- Xamarin.Forms.Build.Tasks/CssGenerator.cs
- Xamarin.Forms.Build.Tasks/DebugXamlCTask.cs
- Xamarin.Forms.Build.Tasks/Logger.cs
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Build.Tasks/XamlGTask.cs
- Xamarin.Forms.Build.Tasks/XamlGenerator.cs
- Xamarin.Forms.Build.Tasks/XamlTask.cs
- Xamarin.Forms.Xaml.Xamlc/Xamlc.cs
[build] reduce verbosity of build
- fixes #1798
/
/
> [build] reduce verbosity of build

- Xamarin.Forms.Build.Tasks/Properties/AssemblyInfo.cs
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Build.Tasks/XamlGenerator.cs
[xamlg] version the CodeGeneratedAttribute
- fixes #1810
/
/
> [xamlg] version the CodeGeneratedAttribute

- Xamarin.Forms.Platform.Android/AppCompat/SwitchRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/SwitchRenderer.cs
Remove dead code
fixes #1539
None
None
> [Android] Remove dead code on SwitchRenderer

- .nuspec/Xamarin.Forms.Maps.nuspec
- .nuspec/Xamarin.Forms.nuspec
- Xamarin.Forms.Core.Design/Xamarin.Forms.Core.Design.csproj
- Xamarin.Forms.Core.Design/packages.config
- Xamarin.Forms.Maps.Design/Xamarin.Forms.Maps.Design.csproj
- Xamarin.Forms.Maps.Design/packages.config
- Xamarin.Forms.Xaml.Design/Xamarin.Forms.Xaml.Design.csproj
- Xamarin.Forms.Xaml.Design/packages.config
- Xamarin.Forms.sln
Add back intellisense Support for VS.
> [Nuspec] Add .Design dll.s back

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.iOS/packages.config
- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Android.UITests/packages.config
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/packages.config
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/packages.config
- Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
- Xamarin.Forms.Core.macOS.UITests/packages.config
Update UITest packages and TestCloud agent
> [UITest] Update packages

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2411.cs
- Xamarin.Forms.Controls/ControlGalleryPages/AutomationIDGallery.cs
Seems tests are failing because of failing to find the button on top of the page
> [UITest] Fix tests for UITest package update

- Xamarin.Forms.Platform.Android/AppCompat/FragmentContainer.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
Fix Appearing/Disappearing 
fixes #1438
> [Android] Remove UserVisibleHint

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh1978.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh1978.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] better error reporting on missing Add()er
- fixes #1978
/
/
> [XamlC] better error reporting on missing Add()er

- Xamarin.Forms.Core/OnIdiom.cs
- Xamarin.Forms.Core/TargetIdiom.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/OnIdiom`1.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/TargetIdiom.xml
Add Watch to TargetIdiom. `TargetIdiom.Watch` indicates that Forms is running on a smart watch such as Samsung Gear S serires
None
Added:
- TargetIdiom.Watch // enum
- T OnIdiom.Watch { get; set; }
The following scenarios are possible on different devices :
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
xmlns:local="clr-namespace:SimpleText"
x:Class="SimpleText.MainPage">
<Label VerticalOptions="Center" HorizontalOptions="Center" FontSize="Large" FontAttributes="Bold">
<Label.Text>
<OnPlatform x:TypeArguments="x:String">
<On Platform="Android" Value="Welcome to Xamarin.Forms.Android!" />
<On Platform="iOS" Value="Welcome to Xamarin.Forms.iOS!" />
<On Platform="UWP" …
```
> [Core] Add Watch to TargetIdiom

- Xamarin.Forms.Core.Design/toolbox/Xamarin.Forms.toolbox.xml
Just changes the XML icon names to match agreed upon spec
> remove -16 from xml names for toolbox

- Xamarin.Flex/Flex.cs
- Xamarin.Forms.Core.UnitTests/FlexLayoutTests.cs
- Xamarin.Forms.Core/FlexLayout.cs
> [flex] better margin support with Wrap

- Xamarin.Forms.Core/Application.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Application.xml
[C] make Application ctor public
- fixes #2018
Changed:
- `protected Application.Application()` => `public Application.Application()`
> [C] make Application ctor public

- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
- Xamarin.Forms.Xaml/Properties/AssemblyInfo.cs
- docs/Xamarin.Forms.Xaml/index.xml
Just adds an IVT attribute for LiveXAML usage.
> Add IVT for kzu's needs with comments for future automation

- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2007.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2007.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/MarkupExtensions/ReferenceExtension.cs
[Xaml] better error reporting on x:Reference
- fixes #2007
/
/
> [Xaml] better error reporting on x:Reference

- Xamarin.Forms.Build.Tasks/ExpandMarkupsVisitor.cs
- Xamarin.Forms.Build.Tasks/XmlTypeExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2034.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2063.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2063.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] report undeclared xmlns on custom markups
- fixes #2063
/
/
> [XamlC] report undeclared xmlns on custom markups

- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2064.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2064.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] report missing ctor param
for parameterized ctors, like Style.
- fixes #2064
/
/
> [XamlC] report missing ctor param

- .nuspec/Xamarin.Forms.nuspec
- Xamarin.Forms.Controls/CoreGalleryPages/SliderCoreGalleryPage.cs
- Xamarin.Forms.CustomAttributes/TestAttributes.cs
- Xamarin.Forms.Platform.UAP/FormsSlider.cs
- Xamarin.Forms.Platform.UAP/Resources.xaml
- Xamarin.Forms.Platform.UAP/SliderRenderer.cs
- Xamarin.Forms.Platform.UAP/SliderStyle.xaml
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
This is the UWP implementation of thumb image/color (fixes #1684). It is an addendum to the changes in PR #1781.
This also adds the new Slider properties to the Slider Gallery.
> [UWP] Thumb color and image for Slider

- .nuspec/Xamarin.Forms.AppLinks.nuspec
- .nuspec/Xamarin.Forms.Maps.GTK.nuspec
- .nuspec/Xamarin.Forms.Maps.WPF.nuspec
- .nuspec/Xamarin.Forms.Maps.nuspec
- .nuspec/Xamarin.Forms.Pages.Azure.nuspec
- .nuspec/Xamarin.Forms.Pages.nuspec
- .nuspec/Xamarin.Forms.Platform.GTK.nuspec
- .nuspec/Xamarin.Forms.Platform.WPF.nuspec
- .nuspec/Xamarin.Forms.nuspec
Comply with the authoring requirements from Microsoft for  the nuspecs
- None
- None
- None
> [Nuget] Update nuspec's with msft info

- Xamarin.Forms.Core/DependencyService.cs
- Xamarin.Forms.Core/Registrar.cs
Fix for previewer, no bug filed.
> Try/Catch assembly loading so previewer doesn't have a fit

- Xamarin.Forms.Core/IServiceProviderExtensions.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.Xaml/IServiceProviderExtensions.xml
- docs/Xamarin.Forms.Core/index.xml
> Generic GetService

- Xamarin.Forms.Platform.MacOS/Renderers/WebViewRenderer.cs
Implement the navigation events on MacOS 
- fixes #1630
> [MacOS] Implement the navigation events on MacOS

- Xamarin.Forms.Platform.Tizen/Native/MasterDetailPage.cs
- Xamarin.Forms.Platform.Tizen/PanGestureHandler.cs
- Xamarin.Forms.Platform.Tizen/Platform.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/TabbedPageRenderer.cs
This PR is intended to fix small issues we discovered while testing on various tizen devices and emulators.
- Fix 5 minor issues on tizen devices/emulators.
None
None
> [Tizen] Fix minor issues tizen backend

- .nuspec/Xamarin.Forms.nuspec
design dlls for all plats
- fixes #2474
> design dlls for all plats

- Xamarin.Forms.Build.Tasks/CompiledConverters/ColorTypeConverter.cs
- Xamarin.Forms.Build.Tasks/ModuleDefinitionExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/SetValue.xaml
[XamlC] accept lowercase colors
- fixes #2459
> [XamlC] accept lowercase colors

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2266.cs
This test was based on the older UI Test structure and was crashing when anyone tried to run it. This PR updates it to the newer testing structure, adds preserve attributes for android, and includes a UI Test for automation
> [UI Tests] Fixing Issue2266 to conform to new test structure and automating test

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla51825.cs
- Xamarin.Forms.Controls/ControlGalleryPages/ToolbarItems.cs
- Xamarin.Forms.Core.UITests.Shared/Tests/ToolbarItemTests.cs
Try fix test that are failing on master
> [UITests] Fix failing tests

- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/ExpandMarkupsVisitor.cs
- Xamarin.Forms.Build.Tasks/SetFieldVisitor.cs
- Xamarin.Forms.Build.Tasks/SetNamescopesAndRegisterNamesVisitor.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/SetResourcesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2483.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2483.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- Xamarin.Forms.Xaml/ExpandMarkupsVisitor.cs
- Xamarin.Forms.Xaml/FillResourceDictionariesVisitor.cs
- Xamarin.Forms.Xaml/NamescopingVisitor.cs
- Xamarin.Forms.Xaml/PruneIgnoredNodesVisitor.cs
- Xamarin.Forms.Xaml/RegisterXNamesVisitor.cs
- Xamarin.Forms.Xaml/XamlNode.cs
- Xamarin.Forms.Xaml/XamlNodeVisitor.cs
[Xaml[C]] consider subclass of RDs as RDs
- fixes #2483
/
/
> [Xaml[C]] consider subclass of RDs as RDs

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2266.cs
Added a button to open the Master page so UI Test works on Android and iOS
> fix ui test for iOS on Issue2266

- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2508.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2508.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] correctly create ldc_i4 for uint
- fixes #2508
/
/
> [XamlC] correctly create ldc_i4 for uint

- Xamarin.Forms.Xaml/MarkupExtensions/StyleSheetExtension.cs
[CSS] attribute Source with UriTypeConverter
- fixes #1653
/
/
> [CSS] attribute Source with UriTypeConverter

- Xamarin.Forms.Platform.UAP/WindowsBasePage.cs
Add a null check
- Fixes #2297 
None
None
> [UWP] Fix crash when closing app and not actually loading an Application

- Xamarin.Forms.Build.Tasks/SetFieldVisitor.cs
- Xamarin.Forms.Build.Tasks/XamlGenerator.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2574.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2574.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml.UnitTests/XamlgTests.cs
[XamlG] creates fields for x:Name on root
- fixes #2574
/
/
> [XamlG] creates fields for x:Name on root

- Xamarin.Forms.Platform.UAP/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.UAP/ViewRenderer.cs
Added margins to view elements
http://prntscr.com/j7wqei
Fixes #2357
None
All `views` in `UWP` now will process margin. 
Also inside `ScrollView`.
> [UWP] Added margin inside scroll view

- Xamarin.Flex/Flex.cs
- Xamarin.Forms.Core.UnitTests/FlexLayoutTests.cs
[C][flex] proper handling of grow in reverse
- fixes #2551
/
/
> [C][flex] proper handling of grow in reverse

- Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs
This PR is extension of #1280 for tizen backend.
None
None
None
> [Tizen] ScaleX and ScaleY

- Xamarin.Forms.Platform.Android/VisualElementTracker.cs
[A] apply global scale on BatchUpdate
probably due to a bad merge or rebase...
/
/
/
> [A] apply global scale on BatchUpdate

- README.md
Table points to 3.0.0 packages, but header still shows 2.5.0
Version in readme
N/A
N/A
> Fixed out-of-date version

- .nuspec/Xamarin.Forms.nuspec
[nuspec] update description to add new plats
- fixes #2627
/
/
> [nuspec] update description to add new plats

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60691.cs
- Xamarin.Forms.Platform.iOS/Forms.cs
[iOS] allow mailto: uri
same as #1311 but for mailto:
- fixes #2628
/
/
> [iOS] allow mailto: uri

- Xamarin.Forms.Platform.WPF/Renderers/SearchBarRenderer.cs
PlaceholderText & Color in WPF
Now both working fine
> SearchBar Placeholder in WPF

- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
added animate code to `ListView.ScrollTo` in `UWP`
Screencast: https://www.screencast.com/t/liuXQZ9arEh
Fixes #2048
None
If parameter `shouldAnimate` is true, then scrolling should be animated =)
> [UWP] Animate ListView.ScrollTo

- Xamarin.Forms.Platform.UAP/SearchBarRenderer.cs
[UWP] fix NRE in SearchBarRenderer
Manually tested
- fixes #2633
/
/
> [UWP] fix NRE in SearchBarRenderer

- Xamarin.Forms.Platform.Android/Renderers/TimePickerRenderer.cs
> [Android] Fixes TimePicker FontSize & FontFamily 

- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
[Xaml] avoid AmbiguousMatchException
- fixes #2796
> [Xaml] avoid AmbiguousMatchException

- Xamarin.Forms.Platform.Tizen/Native/RoundRectangle.cs
- Xamarin.Forms.Platform.Tizen/Renderers/BoxViewRenderer.cs
Add CornerRadius implementation on BoxView for tizen
https://github.com/xamarin/Xamarin.Forms/issues/1709
None
None
> [Tizen] Add CornerRadius implementation on BoxView

- Xamarin.Forms.Platform.Tizen/Renderers/EditorRenderer.cs
[Tizen] Add PlaceHolder implementation on Editor
https://github.com/xamarin/Xamarin.Forms/issues/1907
None
None
> [Tizen] Add PlaceHolder implementation on Editor

- .nuspec/Xamarin.Forms.AppLinks.nuspec
- .nuspec/Xamarin.Forms.Maps.nuspec
- .nuspec/Xamarin.Forms.nuspec
Remove references to 23.3 Support libs
> [Nuspec]Remove reference to 23.3.0 support libs

- Xamarin.Forms.Maps.Tizen/MapRenderer.cs
Tizen map renderers listen for the PropertyChanged event on each Pin in Map.Pins to update position of native pins when changed in cross-platform code. This PR is tizen implementation of #2121.
- Fixes #2121
None
None
> [Maps/Tizen] Handle Pin.PropertyChanged events

- .nuspec/Xamarin.Forms.AppLinks.nuspec
- .nuspec/Xamarin.Forms.Maps.nuspec
- .nuspec/Xamarin.Forms.nuspec
- EmbeddingTestBeds/Embedding.Droid/Embedding.Droid.csproj
- EmbeddingTestBeds/Embedding.Droid/packages.config
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- PagesGallery/PagesGallery.Droid/packages.config
- Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj
- Stubs/Xamarin.Forms.Platform.Android/packages.config
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.Android/packages.config
- Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
- Xamarin.Forms.Maps.Android/packages.config
- Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj
- Xamarin.Forms.Platform.Android.AppLinks/packages.config
- Xamarin.Forms.Platform.Android.FormsViewGroup/Xamarin.Forms.Platform.Android.FormsViewGroup.csproj
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
- Xamarin.Forms.Platform.Android/packages.config
> [Android] Update android packages

- Xamarin.Forms.Platform.Tizen/Cells/EntryCellRenderer.cs
- Xamarin.Forms.Platform.Tizen/Cells/SwitchCellRenderer.cs
- Xamarin.Forms.Platform.Tizen/Cells/ViewCellRenderer.cs
- Xamarin.Forms.Platform.Tizen/Native/RoundRectangle.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/SliderRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/SwitchRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs
This PR is intended to fix small issues we discovered while testing on various tizen devices and emulators.
- BoxView geometry issue
- IsFocusAllowed platform specific issue
- PropagateEvents Issue
None
None
> [Tizen] Fix minor issue tizen backend

- Xamarin.Forms.Platform.Tizen/Native/WebViewContainer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/WebViewRenderer.cs
Enhancement Tizen WebView Renderer
- Support Focus
- Support GestureRecognizers
Fix focus issue
Fix GestureRecognizer
None
None
> [Tizen] Enhancement WebView Renderer

- Xamarin.Forms.Platform.WPF/WPFPlatformServices.cs
Implemented OpenUriAction in WPF Backend.
- fixes #2912
> [WPF] Implemented OpenUriAction in WPF Backend

- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
[CSS] apply border-color to all IBorderElements
> [CSS] apply border-color to all IBorderElements

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla56771.cs
New test added in #2512 caused 56771 to start failing.
> [UI Test] Revert 56771 test

- Xamarin.Forms.Platform.WPF/Renderers/ImageRenderer.cs
Fixed Images from Stream.
_NOTE: Image from base64 to byte array, then use a Stream to create the ImageSource._
- fixes #2844
> [WPF] Fixed Images from Stream

- Xamarin.Forms.Platform.GTK/Renderers/EntryRenderer.cs
Apply transparent color in case of receive default color in GTK Entry.
- fixes #2778 
Apply transparent color in case of receive default color in GTK Entry.
> [GTK] Fixed Issue 2778: Apply transparent color in case of receive default color in GTK Entry

- Xamarin.Forms.Core/FlexLayout.cs
[Flex] do not double layout
Invalidating is enough, and by itself will trigger eventually a
re-layout.
/
/
/
> [Flex] do not double layout

- Xamarin.Forms.Core/EnumerableExtensions.cs
Enumerate copy so list can be mutated w\o throwing. Fixes #2576
fixes #2576
None
> [Core] Enumerate copy so GetGesturesFor list can be mutated w\o throwing

- Xamarin.Forms.Core/ScrollView.cs
Fix ScrollToPosition.MakeVisible bug
- Fix `isItemVisible` condition on ScrollView
As is
Fixed
None
None
> [Core] Fix ScrollToPosition.MakeVisible bug

- Xamarin.Forms.Platform.Tizen/Cells/ImageCellRenderer.cs
- Xamarin.Forms.Platform.Tizen/Cells/SwitchCellRenderer.cs
- Xamarin.Forms.Platform.Tizen/Platform.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ActivityIndicatorRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/FrameRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/PickerRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/SearchBarRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/SliderRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/SwitchRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/TimePickerRenderer.cs
[Tizen] Enhancement serveral Rendereres for Watch on Tizen
**1. In case of Wearable and TV profile, the default border color of Frame should be changed**
- Before
- After
**2. In case of Wearable, the default style of ActivityIndicator should be changed**
- Before
- After
**3. In case of Wearable, the default width of swich in cell should be changed**
- Before
- After
**4. In case of Wearable, the default style of ImageCell should be changed**
- Before
- After
**5. Update on property of Element using SetValueFromRenderer method**
**6. In case of Wearable, the popup style should be changed**
- Before
- After
None
None
None
> [Tizen] Enhancement serveral Rendereres for Watch on Tizen

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GestureBubblingTests.cs
Ignore Gesture bubbling on iOS slider
> [Tests] Ignore slider uitest

- Xamarin.Forms.Platform.UAP/VisualElementTracker.cs
If statement was backwards.
#2841
#2514
None
RotationX/Y start working again
> Fix 3d rotation on UWP

- Xamarin.Forms.Core/Stepper.cs
Call void ctor from parameterized ctor of Stepper
- #2918
None
Platform specifics will work correctly with non-XAML constructed steppers.
> Make sure PlatformConfiguration created with Stepper

- .nuspec/Xamarin.Forms.targets
- Xamarin.Forms.Build.Tasks/CssGTask.cs
- Xamarin.Forms.Build.Tasks/GetTasksAbi.cs
- Xamarin.Forms.Xaml.UnitTests/MSBuild/MSBuildTests.cs
Similar to #2825, but for CSS files
/
/
/
> CSSG Incremental

- Xamarin.Forms.Platform.Android/Renderers/StepperRenderer.cs
Ensure stepper up and down button are the same size
- #2919
None
Stepper down button will no longer be larger than up button on some dpis.
> Make sure stepper buttons are always the same size

- Xamarin.Forms.Platform.Tizen/Native/EditfieldEntry.cs
- Xamarin.Forms.Platform.Tizen/Native/Entry.cs
- Xamarin.Forms.Platform.Tizen/Native/SearchBar.cs
- Xamarin.Forms.Platform.Tizen/Renderers/SearchBarRenderer.cs
Previous code implements SearchBar using Layout and several visual elements in renderer instead of native widget. It makes hard to modify renderer codes for multi profiles(TV, Mobile, Watch).
So, This PR refactors SearchBar Renderer to use theme style.
- Mobile
- TV
- Watch
None
None
None
> [Tizen] Refactor SearchBar Renderer

- Xamarin.Forms.Platform.GTK/Controls/ScrolledTextView.cs
- Xamarin.Forms.Platform.GTK/Renderers/EditorRenderer.cs
Implemented Editor Placeholder and PlaceholderColor in GTK.
- GTK
> [GTK] Added Editor Placeholder and PlaceholderColor

- .nuspec/Xamarin.Forms.targets
Throw a meaningful error on old .NET Framework
> [build] require .NET framework >= 4.7

- Xamarin.Forms.Platform.WPF/Xamarin.Forms.Platform.WPF.csproj
Fix lang version to default (Debug and Release)
Build OK on Release
- WPF
> [WPF] Fix lang version to default

- Xamarin.Forms.Platform.WPF/Themes/FormsContentPage.xaml
Change the default content page background for content page to WHITE
Content page default is now White instead Transparent
> WPF - Fix default background color for content page

- .nuspec/Xamarin.Forms.targets
Add option to ignore framework version validation
> [Build] Add option to ignore framework version validation

- Xamarin.Forms.Build.Tasks/XamlGenerator.cs
- Xamarin.Forms.Xaml.UnitTests/XamlgTests.cs
[XamlG] allow x:Name on types in using: xmlns
- fixes #3393
/
/
> [XamlG] allow x:Name on types in using: xmlns

- Xamarin.Forms.Platform.GTK/Renderers/TabbedPageRenderer.cs
Fixed wrong CurrentPage index in TabbedPage. It did not change the index of the current page correctly.
- GTK
> [GTK] Fixed wrong CurrentPage index in TabbedPage

- Xamarin.Forms.Platform.UAP/VisualElementTracker.cs
Fixes image scale
- fixes #3169
None
- UWP
image scale works correctly
> [UWP] Fixes image scale

- Xamarin.Forms.Platform.WPF/Forms.cs
Added option to register extra assemblies in WPF Forms initialization.
- WPF
> [WPF] Added option to register extra assemblies in WPF Forms initialization

- Xamarin.Forms.Platform.Android/Renderers/MasterDetailRenderer.cs
Addresses https://devdiv.visualstudio.com/DevDiv/_workitems/edit/657472
> [Android] Fix a potential null reference

- Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
This PR adds support for caret position(CursorPosition, SelectionLength in Entry) on tizen backend.
- None
- None
- Tizen
- None
> [Tizen]Add Caret position for Tizen

- Xamarin.Forms.Platform.GTK/Renderers/AbstractPageRenderer.cs
Fixed problem disposing childs navigating back.
- Fixes #2987
- GTK
> [GTK] Fixed problem disposing childs navigating back

- Xamarin.Forms.Platform.UAP/WindowsBasePage.cs
- Xamarin.Forms.Platform.WPF/FormsApplicationPage.cs
- [WPF] Added check whether the page is loaded when set `MainPage`. Because need to load `FormsApplicationPage` for the correct `MainPage` set.
- [UWP] Added support for null `MainPage` in the initialization of the application.
Screencast: https://www.screencast.com/t/TXqChhQzqL
- Fixes #2704
None
> [UWP, WPF] Fixes rendering of the main page

- Xamarin.Forms.Platform.Android/Renderers/LabelRenderer.cs
- Xamarin.Forms.Platform.UAP/LabelRenderer.cs
Label didn't refresh if LineHeight changes. 
fixes #3344
None
- Android
None
> [Android] Fix Label LineHeight

- Xamarin.Forms.Platform.Android/Platform.cs
And null check in `GetRenderer`.
- fixes #3563
None
Android
None other than won't throw NRE.
> Add Null Check to GetRenderer

- Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
Add a null check.
- fixes #3562 
None
- Android
None
> Fix 3562 Null Reference Exception

- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailPageRenderer.cs
Add null check.
- fixes #3564 
None
Android
None
> Fix 3564 Null Reference Exception

- Xamarin.Forms.Platform.GTK/Extensions/LabelExtensions.cs
Fixed Issue 3663: ListView entries problem with some characters:
- fixes #3663 
None
- GTK
Cells using special characters must be rendered without problems.
Before
After
> [GTK] Fixed Issue 3663: ListView entries problem with some characters

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla26171.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1733.cs
- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Android.UITests/packages.config
- Xamarin.Forms.Core.UITests.Shared/Tests/Legacy-CellsUITests.cs
- Xamarin.Forms.Core.UITests.Shared/Tests/ToolbarItemTests.cs
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/packages.config
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/packages.config
- Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
- Xamarin.Forms.Core.macOS.UITests/packages.config
Update Xamarin.UITest to 2.2.5
> [UITest] Update Xamarin.UITest nuget package

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1733.cs
Reworked Issue1733 UITest to be more deterministic and less prone to failure based on device speed
> [UITests] replace awaits with more reliable WaitForElement

- Xamarin.Forms.Core/Element.cs
Added a bindable AutomationId property. It's Sunday morning, and I'm half asleep still. Part of me says the work that goes into this isn't as trivial as I made it to be. :)
I believe Xamarin takes care of documentation now.
- fixes #3845
Added:
- string AutomationId { get; set; } //Bindable Property
> [Enhancement] Create a bindable property for AutomationId

- Xamarin.Forms.Platform.WPF/Renderers/NavigationPageRenderer.cs
Fix  : Unable to intercept back button.
- fixes #3689
- WPF
> WPF - Fix Unable to intercept back button

- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
fix css mapping for column-gap
- reported directly by @davidbritch 
Changed:
- CSS mapping
None
Not applicable
> [C] fix css mapping

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1851.cs
Fixed UI test 1851 and automated it with a ScrollView wrapping the StackLayout. Note that I'm unable to run the automated tests at the moment due to VS not recognizing NUnit references in my workspace.
- fixes #2255
- Android
> [Android] Fix UI test 1851

- Xamarin.Forms.Platform.WPF/FormsTextBox.cs
Fix  Ctrl+A does not select all in WPF password Entry
Patch inspired by the UWP renderer :)
- fixes #3258
> WPF - Fix Ctrl+A does not select all in WPF password Entry

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3913.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WPF/Renderers/ViewRenderer.cs
Fix Height of items not consistent.
- fixes #3913
- WPF
> [WPF] Fix Height of items not consistent

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2187.cs
- Xamarin.Forms.Platform.WPF/Extensions/FontExtensions.cs
Fix FontFamily Assignment in platform specific project for Button and Span
Related to PR #3225
- WPF
> WPF - Apply font fix for button and span

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41778.cs
> Added instructions to UI test B41778

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45702.cs
- Xamarin.Forms.Controls/App.cs
> Automate UI test B45702

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla38105.cs
> Added instructions for UI test 38105

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41424.cs
* Add manual steps
* Add checks for ui test
- fixes #2358
None
None
Not applicable
> Fix UI test B41424 needs instructions

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla35127.cs
Not sure if this test will pass as I had to write it without being able to run it. However, the execution lines should be trivial.
I'd appreciate some help with resolving the following issue:
> [9/27/2018 6:36:17 PM Informational] The running adb server is incompatible with the Android SDK version in use by UITest: 
>     C:\Program Files (x86)\Android\android-sdk
> 
> You probably have multiple installations of the Android SDK and should update them or ensure that your IDE, simulator and shell all use the same instance.  The ANDROID_HOME environment variable can effect this.
I was able to run UI tests last night, but today VS decided to fail on me. My adb version is as follows:
Android Debug Bridge version 1.0.40
Version 4797878
Installed as C:\Program Files …
> Automate UI test 35127

- Xamarin.Forms.Core/Interactivity/PropertyCondition.cs
- Xamarin.Forms.Core/Setter.cs
- Xamarin.Forms.Core/StyleSheets/Style.cs
- Xamarin.Forms.Platform.Android/Extensions/TextViewExtensions.cs
- Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/LabelRenderer.cs
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/MarkupExtensionParser.cs
Provide a way to add custom view in ToolBarItem so that custom icons can be added on NavigationBar.
<ToolBarItem.CustomView></ToolBarItem.CustomView>
- iOS
- Android
- UWP
> Add Custom View in ToolBarItem

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43941.cs
* Include all platforms
* Remove non-deterministic test behaviour ``` // At this point, the counter can be any value, but it's most likely not zero. ```
- fixes #2376
None
None
Not applicable
> Fix UI test B43941

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2597.cs
Add test for issue 2597:
* Click on "+"
* Check that stepper event was not invoked
- fixes #2284
None
None
Not applicable
I didn't check on iOs
> Fix Issue2597 Needs UI Test

- Xamarin.Forms.Platform.Tizen/Renderers/ActivityIndicatorRenderer.cs
When `ActivityIndicator.IsEnabled` state is changed to `false` and back to `true`,
`ActivityIndicator.IsRunning` state is not updated properly.
It always stops running in this case.
- N/A
- None
- Tizen
- `ActivityIndicator.IsRunning` State is updated properly when `IsEnabled` value is changed.
`ActivityIndicator.IsRunning` State is updated properly when `IsEnabled` value is changed.
- Before
- After
```c#
class ActivityIndicatorTest : ContentPage
{
public ActivityIndicatorTest()
{
ActivityIndicator ai = new ActivityIndicator();
Button button = new Button
{
HorizontalOptions = LayoutOptions.FillAndExpand,
Text = "ActivityIndicator.IsEnabled " + ai.IsEnabled
};
Button button1 = new Button
{
HorizontalOptions = LayoutOptions.FillAndExpand,
Text = "ActivityIndicator.IsRunning " + …
```
> [Tizen] Fixes ActivityIndicator IsRunning state issue

- .nuspec/Xamarin.Forms.nuspec
Add UAP symbol files to nuget packages to add it debugging of customer reproductions.
> add pdb for uap into nuget

- README.md
Added UI Tests and Run UWP UI Tests section to README.md with the goal of including instructions for setting a system up to run the UWP UI Tests, as described in #3984.
- fixes #3984
None
- UWP
None
Not applicable
> [UWP] Document in the README.md the steps required to run UI Tests

- Xamarin.Forms.Platform.Tizen/Flags.cs
- Xamarin.Forms.Platform.Tizen/Renderers/CarouselPageRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/CustomFocusManager.cs
- Xamarin.Forms.Platform.Tizen/Renderers/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs
This PR implement TabIndex feature in Tizen
- fixes https://github.com/xamarin/Xamarin.Forms/issues/1700
None
- Tizen
None
Not applicable
> [Tizen] Add TabIndex implement

- Stubs/Xamarin.Forms.Platform.Tizen/Xamarin.Forms.Platform.Tizen (Forwarders).csproj
Fix loading of Xamarin.Forms.Platform.Tizen (Forwarders)
- Loading on VS4Mac
None
- GTK
None
Not applicable
Just open the sln on VS4MAc
> [Tizen] Fix ProjectGuid for Forwarders

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla36955.cs
Fixed UI test for working properly, without crashes.
Made changes regarding to @hartez comment
- fixes #2291
None
- iOS (UITEST)
No crashing
Not applicable
Open Bugzilla36955 test. See that there is no crash
> Prevented crash in Bugzilla36955 UITest

- Xamarin.Forms.Controls/ControlGalleryPages/ClickGestureGalleryPage.cs
- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Platform.GTK/VisualElementTracker.cs
Add support for ClickGestureRecognizer
None
None
- GTK+
None
Not applicable
> [GTK] Add support for ClickGestureRecognizer

- Xamarin.Forms.Platform.Tizen/FormsApplication.cs
This PR change Window Alpha value update timing. because previous timing too early to update by Application code easily
None
None
- Tizen
None
Not applicable
> [Tizen] Fix Window alpha update timing

- .nuspec/Xamarin.Forms.nuspec
Remove the byte order mark from the nuspec file
> Remove BOM from nuspec

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1777.cs
Added instructions and UI test for test Issue1777
- fixes #2251
None
- UWP
None
Not applicable
>  Issue1777 - Add UI Test. Add instructions. Move to correct namespace

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2794.cs
* Add UI test
* Add instructions
- fixes #2293
None
Not applicable
> Fix Issue2794 needs UI Test

- Xamarin.Forms.Platform.Tizen/Cells/EntryCellRenderer.cs
- Xamarin.Forms.Platform.Tizen/Cells/SwitchCellRenderer.cs
- Xamarin.Forms.Platform.Tizen/Cells/ViewCellRenderer.cs
This PR propertly update PropagateEvent property value. 
Only Button and Switch have PropagateEvent as false on Cells, but currently the outermost object was set to PropageteEvent as false.
- fixes #
None
- Tizen
Items of ListView are not selected when button of cell was tapped
* Before
* After
> [Tizen] Fix PropagateEvent value properly on Cells

- README.md
fixes the link to contribution file in the readme
None
None
None
Not applicable
Click on `How to Contribute` link
> fixes the link How to Contribute in the readme

- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
fix dependon for Controls.csproj
properly populate DependOn xaml and code behind
> fix dependon for Controls.csproj

- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Remove files that are already included because of sdk style projects
> remove implicitly included files from csproj

- azure-pipelines.yml
- build/provisioning/provisioning.csx
- build/provisioning/provisioning_windows.csx
- build/scripts/generate-docs.ps1
- build/steps/build-nuget.yml
- build/steps/build-osx.yml
- build/steps/build-prepare.yml
- build/steps/build-sign.yml
- build/steps/build-windows-test.yml
- build/steps/build-windows.yml
Add initial yaml draft definition for Xamarin Forms build process
- fixes #3430
None
None
Not applicable
Check new pipeline on azure devops
> [Build] Add azure pipeline definition

- .nuspec/Xamarin.Forms.nuspec
Add UAP symbols to nuget package. Helps when debugging user reproductions.
> Add UAP symbols to nuget package

- Xamarin.Forms.Platform.Tizen/Native/BorderRectangle.cs
- Xamarin.Forms.Platform.Tizen/Native/RoundRectangle.cs
- Xamarin.Forms.Platform.Tizen/Properties/AssemblyInfo.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ImageButtonRenderer.cs
This PR implement ImageButton Renderer on Tizen
- fixes the tizen part of https://github.com/xamarin/Xamarin.Forms/issues/1724
None
- Tizen
None
> [Tizen] Add ImageButton Renderer

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1914.cs
Use propotional values for issue 1914
- fixes #3972 
- fixes #2368
None
- Android
- UWP
Not applicable
Visit issue 1914 on UWP and Android
> [Controls]Use propotional values on test 1914

- Xamarin.Forms.Xaml.UnitTests/MSBuild/MSBuildTests.cs
- build/steps/build-windows-test.yml
[tests] fix msbuild tests
those tests are failing sice the move to SDK-style project for
Xaml.UnitTests
> [tests] fix msbuild tests

- XFCorePostProcessor.Tasks/XFCorePostProcessor.Tasks.csproj
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
bump nuget versions of cecil, msbuild, gitinfo, strongnamer
> bump our build dependencies

- Xamarin.Forms.Core.UnitTests/MockPlatformServices.cs
- Xamarin.Forms.Xaml.UnitTests/MSBuild/DummyBuildEngine.cs
- Xamarin.Forms.Xaml.UnitTests/MSBuild/MSBuildTests.cs
- Xamarin.Forms.Xaml.UnitTests/MSBuild/MSBuildXmlExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/MockCompiler.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/FieldReferenceExtensionsTests.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/MethodDefinitionExtensionsTests.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/MethodReferenceExtensionsTests.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/PropertyDefinitionExtensionsTests.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/TypeReferenceExtensionsTests.cs
- Xamarin.Forms.Xaml.UnitTests/XamlgFileLockTests.cs
- Xamarin.Forms.Xaml.UnitTests/XamlgTests.cs
Change the namespace of some tests, allowing me to isolate the slow
running ones and avoid running them every single time.
> [tests] Change namespace of tests

- Xamarin.Forms.Core.Design/Xamarin.Forms.Core.Design.csproj
- Xamarin.Forms.Maps.Design/Xamarin.Forms.Maps.Design.csproj
[Design] Design assemblies targets v4.5
- fixes #2216
None
None
Not applicable
> [Design] Design assemblies targets v4.5

- Xamarin.Forms.Core/DependencyAttribute.cs
- Xamarin.Forms.Core/ExportEffectAttribute.cs
- Xamarin.Forms.Core/Internals/PreserveAttribute.cs
- Xamarin.Forms.Core/ResolutionGroupNameAttribute.cs
Follow CA1813 guidance. And seal our attributes.
- fixes #1788
None
None
Before
After
> [C] Seal our attributes

- Xamarin.Forms.Platform.Android/Renderers/MasterDetailContainer.cs
https://github.com/xamarin/Xamarin.Forms/pull/3575 with an additional check
fixes #3563
according to my comment https://github.com/xamarin/Xamarin.Forms/issues/3563#issuecomment-442476461
> total fix of issue #3575

- Xamarin.Forms.Platform.Android/AppCompat/ImageButtonRenderer.cs
Set ImageButton property public.
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> Set ImageButton property of Android.ImageButtonRenderer public

- .nuspec/Xamarin.Forms.nuspec
Add missing xbf files to UAP nuspec
- fixes #
- UWP
Install NUGET into UWP app and see if it runs
> [UWP] add missing xbf files to nuspec

- Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/DataTemplateExtension.cs
- Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/TypeExtension.cs
- Xamarin.Forms.Xaml.UnitTests/DataTemplateExtension.xaml
- Xamarin.Forms.Xaml.UnitTests/DataTemplateExtension.xaml.cs
- Xamarin.Forms.Xaml/MarkupExtensions/ArrayExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/BindingExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/DataTemplateExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/DynamicResourceExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/OnIdiomExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/OnPlatformExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/ReferenceExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/StaticResourceExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/TemplateBindingExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/TypeExtension.cs
[XamlC] Compile the {DataTemplate} markup
- fixes #4592
None
None
Not applicable
> [XamlC] Compile the {DataTemplate} markup

- .nuspec/Xamarin.Forms.nuspec
- .nuspec/Xamarin.Forms.targets
- EmbeddingTestBeds/Embedding.XF/Embedding.XF.csproj
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- PagesGallery/PagesGallery.UWP/PagesGallery.UWP.csproj
- PagesGallery/PagesGallery.iOS/PagesGallery.iOS.csproj
- PagesGallery/PagesGallery/PagesGallery.csproj
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Build tasks in VS **MUST** target net46 and no higher
- fixes #4667
None
None
Not applicable
> [tasks] Build.Tasks targets net46

- README.md
Corrected typo to reflect the correct Android name.
- fixes #4686
None
> GH-4686 Updated README to reflect correct name

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Controls/ControlGalleryPages/VisualGallery.xaml
- Xamarin.Forms.Controls/ControlGalleryPages/VisualGallery.xaml.cs
- Xamarin.Forms.Core/AlertArguments.cs
- Xamarin.Forms.Core/Page.cs
- Xamarin.Forms.Core/ProgressBar.cs
- Xamarin.Forms.Platform.iOS/Material/MaterialButtonRenderer.cs
- Xamarin.Forms.Platform.iOS/Material/MaterialFrameRenderer.cs
- Xamarin.Forms.Platform.iOS/Material/MaterialProgressBarRenderer.cs
- Xamarin.Forms.Platform.iOS/Material/MaterialSliderRenderer.cs
- Xamarin.Forms.Platform.iOS/Platform.cs
- Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
Requires: https://jenkins.mono-project.com/job/Components-OpenSource-PR/56/Azure/
> [WIP] Updating the Material Visual to v72.1

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41424.cs
Fix UITest 41424
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> [UItests] Fix UITest 41424

- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
be ready for when we'll merge #4743
/
None
None
Not applicable
> XmlnsPrefix for design

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4484.cs
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> [tests] UWP requires file extensions

- Xamarin.Forms.Core.UnitTests/ShellTests.cs
- Xamarin.Forms.Core/Shell/Shell.cs
- Xamarin.Forms.Core/Shell/ShellNavigationState.cs
Navigate to a relative URI
- fixes #4971
None
- Core
> [Shell] fixes navigate to a relative URI

- Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs
Replace items on iOS
- implements item replacement from #3172
None
- iOS
Automated tests will be available once #4697 is merged.
> [iOS] CollectionView item replacement on iOS

- Xamarin.Forms.Core/InvalidNavigationException.cs
- Xamarin.Forms.Core/UnsolvableConstraintsException.cs
- Xamarin.Forms.Core/XamlParseException.cs
This PR adds [Serializable] attribute to all exception types =>
UnsolvableConstraintsException
XamlParseException
UnsolvableConstraintsException
based on following microsoft recommendations:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/creating-and-throwing-exceptions#defining-exception-classes
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1064-exceptions-should-be-public?view=vs-2017
None
None
Not applicable
> Add Serializable on exception types

- Xamarin.Forms.Platform.iOS/Platform.cs
Removing some leftover code from a much earlier version of ActionSheet handling that doesn't do anything now.
> [iOS] Remove unused ActionSheet code

- .nuspec/Xamarin.Forms.Maps.nuspec
- .nuspec/Xamarin.Forms.nuspec
- EmbeddingTestBeds/Embedding.Droid/Embedding.Droid.csproj
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
- Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Latest version of the support libraries help to mitigate an issue that causes VS to freeze when there is a mismatch of support versions from transient dependencies
> Update support dependencies to latest 28.0.0.1 version

- Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs
Tabulation on the Mac has been rewritten with using KeyUp method
- fixes #4156 
None
- Mac
None
- run ControlGallery on Mac
- click on `SwapRoot - ContentPage` twice or more
- app should't crash
- run uitest 1700
- check tab order on controls
> [Mac] fixes NRE when changing MainPage. Refactoring tab order.

- azure-pipelines.yml
> [Build] Use wildcards on triggers

- Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- Xamarin.Forms.Xaml/XamlLoader.cs
[previewer] more info to the callback
/
None
None
Not applicable
> [previewer] more info to the callback

- Xamarin.Forms.Core/Shell/QueryPropertyAttribute.cs
Reverts xamarin/Xamarin.Forms#5180
> Revert "Add AllowMultiple=true to QueryPropertyAttribute"

- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5095.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5095.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Validation/TypeMismatch.xaml.cs
Report error on invalid value nodes
- fixes #5095
None
None
Not applicable
> [Xaml] better error reporting

- Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs
- Xamarin.Forms.Xaml.UnitTests/FactoryMethodMissingCtor.xaml.cs
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- Xamarin.Forms.Xaml/ResourcesLoader.cs
- Xamarin.Forms.Xaml/XamlLoader.cs
Backport some 3.6 previewer changes to 3.5
> Backport some 3.6 previewer changes to 3.5

- Xamarin.Forms.Core.UnitTests/BindableLayoutTests.cs
- Xamarin.Forms.Core/BindableLayout.cs
BindableLayout should pass container in SelectTemplate!
How did that happen!? Who wrote that!? 😡 Oh, wait...
- fixes #5156
None
Not applicable
> BindableLayout: Pass container in SelectTemplate

- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CollectionModifier.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CollectionViewGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ItemsSourceGenerator.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ObservableCodeCollectionViewGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ObservableCollectionGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ObservableMultiItemCollectionViewGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/TemplateCodeCollectionViewGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/TemplateCodeCollectionViewGridGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/TextCodeCollectionViewGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/TextCodeCollectionViewGridGallery.cs
- Xamarin.Forms.Controls/GalleryPages/GalleryBuilder.cs
- Xamarin.Forms.Core.UITests.Shared/Queries.cs
- Xamarin.Forms.Core.UITests.Shared/Tests/CollectionViewUITests.cs
- Xamarin.Forms.Core.UITests.Shared/Xamarin.Forms.Core.UITests.projitems
UITests  initial 
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> Collectionview uitest

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41600.cs
Added UI test to B41600.
- fixes #2359
None
- Android
None
Not applicable
Run UI test.
> Added UI test to B41600

- Xamarin.Forms.Controls/ControlGalleryPages/VisualGallery.xaml
- Xamarin.Forms.Material.iOS/MaterialEditorRenderer.cs
- Xamarin.Forms.Material.iOS/MaterialMultiLineTextField.cs
- Xamarin.Forms.Material.iOS/MaterialTextField.cs
- Xamarin.Forms.Material.iOS/MaterialTextManager.cs
- Xamarin.Forms.Material.iOS/Properties/AssemblyInfo.cs
- Xamarin.Forms.Material.iOS/Xamarin.Forms.Material.iOS.csproj
- Xamarin.Forms.Platform.Android/Material/MaterialEditorRenderer.cs
- Xamarin.Forms.Platform.Android/Material/MaterialEntryRenderer.cs
- Xamarin.Forms.Platform.Android/Material/MaterialFormsEditTextManager.cs
- Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
- Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
Material Editor
- fixes #5009 
- iOS
- Android
- Check Editors on Visual Gallery
> [Visual] Material Editor

- Xamarin.Forms.ControlGallery.WindowsUniversal/App.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1667.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1937.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2004.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2399.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2894.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3809.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3840.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4597.cs
- Xamarin.Forms.Controls/App.cs
- Xamarin.Forms.Controls/TestCases.cs
- Xamarin.Forms.Core.Windows.UITests/WinDriverApp.cs
- Xamarin.Forms.Core.Windows.UITests/WindowsTestBase.cs
Just made some small changes so the UI tests are compatible with UWP.
> [UWP] fix so tests are compatible with UWP

- Xamarin.Forms.Core/BindableProperty.cs
When implementing several bindable properties on a custom view, it's sometimes easy to forget to set the default value or set the right default value. 
The current exception message doesn't give much information which property has the problem, and sometimes it takes more time than necessary to figure out what's the issue. I've bitten (too) many times because of this.
This PR changes the exception message to point to exact property and problem.
None
It's easy to either forget to set the right default value (which by default is null) or set it to the wrong one.
Example:
```
public static BindableProperty ValueProperty = BindableProperty.Create(nameof(Value), typeof(uint), typeof(MyView), defaultValue: 100);
```
Before:
After:
Not applicable
> BindableProperty: More explanatory exception message

- Xamarin.Forms.Core/StyleSheets/Style.cs
- Xamarin.Forms.Core/Xaml/TypeConversionExtensions.cs
- Xamarin.Forms.Core/Xaml/ValueConverterProvider.cs
- Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- Xamarin.Forms.Xaml/MarkupExtensionParser.cs
- Xamarin.Forms.Xaml/MarkupExtensions/OnIdiomExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/OnPlatformExtension.cs
Catch more exception cases, make sure the previewer can recover from them
- fixes #5397
None
None
Not applicable
> [X] more conv exception, bubble to previewer

- README.md
VS for Mac requires a little bit of coercing to work. This PR updates the readme to help people get started.
- fixes #5409
> update readme to include vs for mac instructions

- .nuspec/Xamarin.Forms.nuspec
Fix missing dependency
- fixes #5188
- UWP
https://www.screencast.com/t/Cq38uxLK
> [UWP] added nuget dependency Win2D.uwp

- Xamarin.Forms.Maps/Map.cs
> Fix Map ItemsSource bp name

- Xamarin.Forms.Core/Shell/ShellContent.cs
Adding better exception messages for Shell. 
- fixes #5081
None
None
Not applicable
> [Shell,Core] Add better exception messages for Shell

- Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
[X] resilient to random text content
- fixes https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/817588
None
None
Not applicable
> [X] resilient to random text content

- Xamarin.Forms.Controls/XamStore/Views/StorePages.cs
- Xamarin.Forms.Core/Internals/PageExtensions.cs
- Xamarin.Forms.Core/NavigationModel.cs
- Xamarin.Forms.Platform.Tizen/Platform.cs
- Xamarin.Forms.Platform.iOS/Platform.cs
Fix show alert
- fixes #5504
None
Not applicable
> [shell] Fix show DisplayAlert

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5555.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Cells/EntryCellRenderer.cs
- Xamarin.Forms.Platform.iOS/Cells/SwitchCellRenderer.cs
see #5604 + #5603 with unit test
> cellrenderer leak fixes + test

- Xamarin.Forms.Core/Application.cs
- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
- Xamarin.Forms.Platform.Android/FormsApplicationActivity.cs
- Xamarin.Forms.Platform.Android/Platform.cs
Don't do anything in SetPage if the page as not changed, do not destroy the previous one in this case.
- Fixes #4706
- Fixes #4325
- Android
> [Android] Fix old root page dispose when main page change

- azure-pipelines.yml
- build/provisioning/provisioning.csx
- build/provisioning/provisioning_sign.csx
- build/steps/build-android.yml
- build/steps/build-osx.yml
- build/steps/build-sign.yml
Update provision on yaml builds 
None
- iOS
- Android
- UWP
None
Not applicable
> [Build] Fix provision on yaml

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
IDE  added a reference to local file location. This PR removes that
> Remove locally referenced folder

- Xamarin.Forms.Core/Shell/SearchHandler.cs
Add a selectedItem property for the case where you do not want to subclass SearchHandler
- fixes #5712
Added:
- public static readonly BindableProperty SearchHandler.SelectedItemProperty;
- public SearchHandler.SelectedItem { get; }
None
Not applicable
> [C] SearchHandler.SelectedItem

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
In case of value types in Compiled Binding Paths, we weren't checking
for null property on the right part of the path.
no simple way to unit-test this
before
```csharp
bindingExtension.TypedBinding = new TypedBinding<Gh5770, Color>(delegate(Gh5770 gh)
{
if (gh == null)
{
return new ValueTuple<Color, bool>(default(Color), false);
}
Gh5770VM expr_24 = gh.MyContentViewModel;
return new ValueTuple<Color, bool>(expr_24.TextColor, true);
}, ..., ...);
```
after
```csharp
bindingExtension.TypedBinding = new TypedBinding<Gh5770, Color>(delegate(Gh5770 gh)
{
if (gh == null)
{
return new ValueTuple<Color, bool>(default(Color), false);
}
Gh5770VM expr_24 = gh.MyContentViewModel;
if (expr_24 == null)
{
return new ValueTuple<Color, bool>(default(Color), false);
}
return new ValueTuple<Color, …
```
> [X] check for null on the parent property

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41619.cs
This is my first contribution, I followed the steps of @PureWeen on live streaming. If I did something wrong, let me know. 
Created automated test.
#2360
Class:
Xamarin.Forms.Controls.Issues.Bugzilla41619
> Create UITest for Bugzilla41619

- Xamarin.Forms.Core/Interactivity/Behavior.cs
- fixes #5520
Added:
- `protected Behavior.Behavior()`
None
Not applicable
> [C] allow inheriting from Behavior

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla31145.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla31255.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla32206.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla32898.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla35132.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39489.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40955.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42069.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42329.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43941.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44047.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44166.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45722.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45722Xaml0.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45926.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla51503.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla55365.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla57910.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Helpers/GarbageCollectionHelper.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1023.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1024.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1703.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1895.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2399.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5555.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Fix Issue5555 so it no longer fails on android
Run issue5555 on android and watch it succeed
let all the automated tests finish
> [Android] add another gc.collect for Android to ensure all is collected

- XFCorePostProcessor.Tasks/XFCorePostProcessor.Tasks.csproj
- Xamarin.Forms.Build.Tasks/Xamarin.Forms.Build.Tasks.csproj
> [X] update Cecil

- Xamarin.Forms.Controls/GalleryPages/ButtonGallery.cs
- Xamarin.Forms.Controls/XamStore/Views/DemoShellPage.xaml.cs
- Xamarin.Forms.Controls/XamStore/Views/StorePages.cs
- Xamarin.Forms.Core/SearchBoxVisiblity.cs
- Xamarin.Forms.Core/Shell/SearchHandler.cs
- Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs
- Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs
- Xamarin.Forms.Platform.iOS/Renderers/ShellScrollViewTracker.cs
Closes https://github.com/xamarin/Xamarin.Forms/pull/5925
per https://github.com/xamarin/Xamarin.Forms/pull/5925#issuecomment-483573639
> s/SearchBoxVisiblity/SearchBoxVisibility/ from base 4.0.0

- azure-pipelines.yml
- build/steps/build-android.yml
- build/steps/build-nuget.yml
- build/steps/build-osx.yml
- build/steps/build-sign.yml
- build/steps/build-windows.yml
Update our public yaml builds 
- fixes #
None
None
Not applicable
> [Build] Fix yaml public

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Controls/ContactsPage.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1763.cs
Create UITest for issue 1763
- fixes #2248
None
- UWP
None
Not applicable
> Add UITest for issue 1763

- Xamarin.Forms.Core.UnitTests/TabIndexTests.cs
- Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
- Xamarin.Forms.Core/TabIndexExtensions.cs
Breaking out the unrelated changes from #3989 to make the review easier.
n/a
None
None
Not applicable
> Add unit tests for TabIndexExtensions

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5131.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/Shell/BaseShellItem.cs
- Xamarin.Forms.Core/Shell/ITabStopElement.cs
- Xamarin.Forms.Core/TabIndexExtensions.cs
- Xamarin.Forms.Core/VisualElement.cs
- Xamarin.Forms.Platform.Android/Renderers/PageRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRecyclerAdapter.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutRenderer.cs
- Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs
Added tab stop support for shell items 
- fixes #5131
None
- iOS
- Android
None
Not applicable
- run ui test 5131
- click on hamburger icon
- try to navigate between menu items with the `tab` button
> [Shell, iOS, Android] added tab order on Shell flyout menu items

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5951.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/ShadowEffect.cs
Added a null check in iOS ShadowEffect OnDetached
fixes #5951
> Add null check in iOS ShadowEffect OnDetached - Fixes #5951

- Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs
- fixes #5700
None
- iOS
- Android
- UWP
None
Not applicable
> Fixes _child.Element null reference exception

- Xamarin.Forms.Controls/ControlGalleryPages/AppearingGalleryPage.cs
- fixes #5854
- iOS
- Android
- UWP
> Addresses issue #5854

- Xamarin.Forms.Core/Application.cs
simplify Application.Current getter, other minor cosmetic changes
> simplify App.Current

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40005.cs
Creating automated UI Test for the Bugzilla issue 40005
- fixes #2339 
None
- iOS
- Android
- UWP
None
Not applicable
Run UI test
- [ x] Has automated tests
> Fixes for B40005 test case

- Xamarin.Forms.Platform.Android/Renderers/ShellRenderer.cs
Change transition from fade to enter mask
- fixes #5216
- Android
> changes transition to enter mask

- build/scripts/generate-docs.ps1
Fix a build issue stemming from an old typo
> Hopefully fix the mdoc issues with the localization typo

- Xamarin.Forms.Core/Xaml/TypeConversionExtensions.cs
While wrapping an exception into a XPE in case of a TypeConversion issue, concat the message of the wrapped exception
> [Xaml] better exception message in case of a TypeConversion issue

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5766.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
- Xamarin.Forms.Platform.Android/VisualElementTracker.cs
Added update layout after changing the element.
- fixes #5766 
None
- Android
None
|:------:|:-----:|
|  ![image](https://user-images.githubusercontent.com/27482193/57302270-75ef1280-70e3-11e9-93af-acac1ff8132f.png) |  ![image](https://user-images.githubusercontent.com/27482193/57302106-1b55b680-70e3-11e9-8477-d2afd5881dac.png) |
- run UItest 5766
- run UItest 1760
- run UItest 1760 (1)
- run UItest 5184
> [Android] Fix Frame size

- Xamarin.Forms.Platform.WPF/FormsApplicationPage.cs
Fixed a typo in a code comment.
None
None
- WPF (sort of but not really, since it's a comment)
None
Not applicable
Hope none required for a comment change
> Fix comment typo

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43527.cs
Created UITest for issue B43527
- fixes #2373
None
- UWP
None
Not applicable
> Created UITest for issue B43527

- azure-pipelines.yml
- build/steps/build-nuget.yml
Update nuget version when generating packages 
Allow to continue if it failed to push a debug package to internal feed (this could happen because a couple of reasons like connection or the package was deleted )
> [Build]Yaml consolidate nuget

- Version.targets
Using the previous version wes not as predictable has what we would expect. This way it should be easier to test against the GitInfo.txt 
If this test fails is because we didn't bump the GitInfo.txt
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> [Build] Update version target

- Version.targets
- azure-pipelines.yml
- build/steps/build-android.yml
- build/steps/build-nuget.yml
- build/steps/build-windows.yml
Simplify package version on yaml builds 
More same internal number versions f
None
- iOS
- Android
- UWP
None
Not applicable
> Fix packageversion

- build/steps/build-nuget.yml
Fix env variable for release packages 
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> [Build]  Fix env variable for release nuget

- Xamarin.Forms.Platform.Android/Renderers/ShellSearchView.cs
Fixes crash App on api 22 or less
- fixes #6197 
None
- Android
None
- run ControlGallery
- SwapRoot - Store Shell
- the application should't crash
> [Shell, Android] Fixes crash on api 22 or less

- .nuspec/Xamarin.Forms.Visual.Material.nuspec
- Xamarin.Forms.ControlGallery.Tizen/Xamarin.Forms.ControlGallery.Tizen.csproj
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/VisualControlsPage.xaml
- Xamarin.Forms.Material.Tizen/MaterialActivityIndicatorRenderer.cs
- Xamarin.Forms.Material.Tizen/MaterialButtonRenderer.cs
- Xamarin.Forms.Material.Tizen/MaterialEntryRenderer.cs
- Xamarin.Forms.Material.Tizen/MaterialFrameRenderer.cs
- Xamarin.Forms.Material.Tizen/Xamarin.Forms.Material.Tizen.csproj
- Xamarin.Forms.Platform.Tizen/Extensions/KeyboardExtensions.cs
- Xamarin.Forms.Platform.Tizen/Native/Box.cs
- Xamarin.Forms.Platform.Tizen/Native/Button.cs
- Xamarin.Forms.Platform.Tizen/Native/Canvas.cs
- Xamarin.Forms.Platform.Tizen/Native/Entry.cs
- Xamarin.Forms.Platform.Tizen/Native/IButton.cs
- Xamarin.Forms.Platform.Tizen/Native/IEntry.cs
- Xamarin.Forms.Platform.Tizen/Native/Span.cs
- Xamarin.Forms.Platform.Tizen/Native/TextHelper.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
This PR is for supporting Visual on Tizen.
This PR also includes the renderers  for material style components that will be swapped out based on a Visual property.
- ActivityIndicator
- Button
- Entry
None
None
- Tizen
None
> [Tizen]Add Material Style Renderers

- Xamarin.Forms.Xaml.UnitTests/HRTests.cs
- Xamarin.Forms.Xaml/XamlLoader.cs
Handle more cases, like implicit resources
not reported
None
None
Not applicable
> handle implicit resources

- Version.targets
Try fix nightly builds on yaml
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> [Build] Fix nightly package naming

- Version.targets
Tag a build so the RE picks it up. this will always be with a user with permissions on CI since it's a Schedule build 
- fixes #
None
None
Not applicable
> [Build] Add nightly tag to azdo

- Xamarin.Forms.Platform.Tizen/Renderers/TabbedPageRenderer.cs
This PR is a tizen implementation of #4899. With this PR, the following properties on `TabbedPage` are newly supported.
- TabbedPage.BarTextColor
- TabbedPage.SelectedTabColor
- TabbedPage.UnselectedTabColor
- fixes #3478
None
- Tizen
The user is now able to specify a separate color for a selected and unselected tab.
Navigate to `RootPages Gallery` -> `Tab->Content`.
> [Tizen] Support to TabbedPage.BarTextColor, SelctedTabColor, UnselecedTabColor

- Xamarin.Forms.Sandbox/App.StartHere.cs
- Xamarin.Forms.Sandbox/App.cs
- Xamarin.Forms.Sandbox/ShellPage.xaml
Removing some code that got checked in and updating the helper a bit
> Sandbox cleanup of shell and css file

- Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs
- Xamarin.Forms.Platform.Android/CollectionView/ItemsViewAdapter.cs
- Xamarin.Forms.Platform.Android/CollectionView/ObservableItemsSource.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
- Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewLayout.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs
- Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> Fix Carousel rebase

- .nuspec/Xamarin.Forms.nuspec
Add generated checkbox xbf style to nuspec so it gets packaged
- fixes #6501
- UWP
- Download the nuget and create a checkbox inside a UWP app
> [UWP] Add FormsCheckBoxStyle.xbf to nuspec

- Xamarin.Forms.Core/Items/ItemsLayout.cs
- Xamarin.Forms.Core/Items/ListItemsLayout.cs
Allows setting the Layout Orientation without using the x:Arguments syntax.
Before:
```
<CollectionView>
<CollectionView.ItemsLayout>
<ListItemsLayout>
<x:Arguments>
<ItemsLayoutOrientation>Horizontal</ItemsLayoutOrientation>
</x:Arguments>
</ListItemsLayout>
</CollectionView.ItemsLayout>
</CollectionView>
```
After:
```
<CollectionView>
<CollectionView.ItemsLayout>
<ListItemsLayout Orientation="Horizontal"/>
</CollectionView.ItemsLayout>
</CollectionView>
```
Note that the need for the `<x:Arguments>` tag is no more and instead you can set the `Orientation` attribute directly on the `ListItemsLayout`.
None
None, both the old and new way will work
Not applicable, visually no change
> [C] Add [Parameter] attribute to constructor for CollectionView Layouts

- Xamarin.Forms.Core/BindableProperty.cs
- Xamarin.Forms.Core/Shell/Shell.cs
- Xamarin.Forms.Core/Shell/ShellContent.cs
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> use a BP for QueryAttributes

- Xamarin.Forms.Controls/GalleryPages/DynamicViewGallery.cs
None
None
Dynamic view gallery support all Enum properties
> Dynamic view gallery support all Enum properties

- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/Extensions/JavaObjectExtensions.cs
Co-Authored-By: Felipe Silveira <transis2@users.noreply.github.com>
Replacement PR for #4586.
- fixes #3489 
- closes #4586
None
- Android
None
Not applicable
None known
> [Android] Add disposed check to MasterDetailPageRenderer

- Xamarin.Forms.Platform.Android/Forms.cs
Consulted with @Clancey for a bit but came to the conclusion that adding the hardcoded values based on [this](https://material.io/develop/android/theming/typography/) made the most sense.
I tried to see if I could do it following the same construction like the ones above this change, so based on:
`_buttonDefaultSize = ConvertTextAppearanceToSize(Resource.Attribute.TextAppearanceButton, Resource.Style.TextAppearanceDeviceDefaultWidgetButton, 14);`
The `ConvertTextAppearanceToSize` method will then determine which of these three values should be used.
But the necessary resource either wasn't available within the style or the attribute which would make the use of this function redundant anyway. If I'm overlooking something or you see any other way I'm open to suggestions, but AFAIC: this is …
> Forms 4.1: Device.GetNamedSize throws exception on Android

- Xamarin.Forms.Core/MergedStyle.cs
During my investigation for #6635 I saw that `ImplicitStyle` is set to null before the `while` loop which is actually calculating the implicit style to apply:
void OnImplicitStyleChanged()
{
var first = true;
ImplicitStyle = null;
foreach (BindableProperty implicitStyleProperty in _implicitStyles)
{
var implicitStyle = (Style)Target.GetValue(implicitStyleProperty);
if (implicitStyle != null)
{
if (first || implicitStyle.ApplyToDerivedTypes)
{
ImplicitStyle = implicitStyle;
return;
}
}
first = false;
}
}
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/MergedStyle.cs#L108
This change makes sure the implicit style is set to `null` only when the `while` loop didn't set an implicit style in order to prevent re-applying the implicit style.
- fixes #6635
None
- Core/XAML …
> Don't reset implicit style (#6635)

- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/DebugXamlCTask.cs
- Xamarin.Forms.Build.Tasks/MethodReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/TypeDefinitionExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh6176.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh6176.xaml.cs
- fixes #6176
None
None
Not applicable
> [X] resolve event handlers in base generic types

- .gitignore
- Xamarin.Forms.Core/Items/SelectableItemsView.cs
- Xamarin.Forms.Platform.UAP/CollectionView/CollectionViewRenderer.cs
- Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs
- Xamarin.Forms.Platform.UAP/CollectionView/SelectableItemsViewRenderer.cs
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
UWP CollectionView  SelectionMode
#3172
#6489 
#5844
#5625
- fixes #
UWP CollectionView  SelectionMode
- UWP
* CollectionViewRender.cs -> (ItemsViewRender.cs + SelectableItemsRender.cs + CollectionViewRender.cs)
~~* Update SelecteableListView.SelectedItems `get`~~
* Changed Render<CollectionView,ItemControl> -> Render<CollectionView,ListViewBase>
* CollectionView Gallery
* Enable CollectionView
* Selection Galleries
> UWP CollectionView SelectionMode

- Xamarin.Forms.Material.Tizen/MaterialCheckBoxRenderer.cs
- Xamarin.Forms.Platform.Tizen/Extensions/ColorExtensions.cs
- Xamarin.Forms.Platform.Tizen/Properties/AssemblyInfo.cs
- Xamarin.Forms.Platform.Tizen/Renderers/CheckBoxRenderer.cs
This PR is tizen implementation of `CheckBox`.
- fixes for Tizen #1728
None
- Tizen
None
- Default
- Material
Checkbox Core Gallery and VisualGallery
> [Tizen] Add Checkbox

- Xamarin.Forms.Controls/ControlGalleryPages/AutomationPropertiesGallery.cs
- Xamarin.Forms.Platform.Tizen/Extensions/AccessibilityExtensions.cs
- Xamarin.Forms.Platform.Tizen/Native/ToolbarItemButton.cs
- Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs
Added support `AutomationProperty` for Tizen backend. This PR is an addendum to the changes in #713. Due to platform limitations, `Frame` and `Cells` are not supported
None
None
- Tizen
None
Check AutomationPropertyGallery
> [Tizen] Added support AutomationProperties

- Xamarin.Forms.Build.Tasks/XamlGenerator.cs
- fixes #6668
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> try to generate more unique names

- Xamarin.Forms.Controls/GalleryPages/ButtonLayoutGalleryPage.xaml
- Xamarin.Forms.Controls/GalleryPages/ButtonLayoutGalleryPage.xaml.cs
- Xamarin.Forms.Controls/NullableThicknessConverter.cs
- fixes #6469
None
None
None
BEFORE:
AFTER:
> Button Layout gallery page: don't set initial Padding

- README.md
Update with nightly feed from Azure 
Known issues:
Current this is a azure static feed since there's no server side code we don't have search capabilities 
- fixes #6347
None
- iOS
- Android
- UWP
None
Not applicable
> Update nightly feed

- Stubs/Xamarin.Forms.Platform.cs
- Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewRenderer.cs
Avoid crashing iOS if using a CarouselView. 
- fixes #6553 
None
- iOS
Should not crash, but shows nothing
Not applicable
Visit the CarouselView gallery page
> [iOS] Provide a base CarouselViewRenderer

- Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs
Addded a new constructor in WkWebViewRenderer so that the devs can pass a WKWebViewConfiguration object when creating a new WKWebView.
- fixes #4815 
None
- iOS
None
Not applicable
- [] Has automated tests
> Add constructor in WkWebViewRenderer to use custom configuration

- Xamarin.Forms.ControlGallery.Android/Properties/AndroidManifest.xml
The control gallery app crashes on Android when visiting Map gallery pages:
> java.lang.NoClassDefFoundError:failed resolution of :Lorg/apache/http/ProtocolVersion
This is because app targets Android 9. 
See 
https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library
I guess once Xamarin.GooglePlayServices.Maps will be updated to bind to com.google.android.gms:play-services-maps:17.0.0 and Xamarin.Forms.Android.Map updates to the latest Xamarin.GooglePlayServices.Maps. setting `uses-library` will no longer be necessary.
- fixes #
None
None
Not applicable
> [Android] Fix Map Gallery page

- Xamarin.Forms.Platform.UAP/ImageSourceIconElementConverter.cs
cleanup: corrected spelling mistake
cleanup: corrected spelling mistake
None
- UWP
None
Not applicable
> cleanup: corrected spelling mistake

- Xamarin.Forms.Core.UnitTests/TemplatedViewUnitTests.cs
- Xamarin.Forms.Core/TemplatedPage.cs
- Xamarin.Forms.Core/TemplatedView.cs
Add the protected method `GetTemplateChild(string name)` to `ContentPage` and `ContentView`. A continuation for the work on #5691 🤦‍♀ 
I also updated the unit test to really use the protected version of `GetTemplateChild` instead of the internal extension method implemented in `TemplateUtilities` 🤦‍♂ 
**`GetTemplateChild` introduced by #5691 is really useless without this PR so I hope we can get this merged in fast for the next 4.1 update.**
Instead of adding GetTemplateChild to both ContentPage and ContentView, another option is maybe to make the `TemplateUtilities` class public but this requires further thinking as some of the methods in `TemplateUtilities` are not ready to be made public and it would require some discussion and more refactoring (for example, `OnContentChanged` and …
> Add protected GetTemplateChild to ContentPage and ContentView 

- Xamarin.Forms.Platform.UAP/ImageRenderer.cs
cleanup: moved closing brace to new line
n/a
None
- UWP
None
Not applicable
edited inline with github editor
> cleanup: moved closing brace to new line

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2577.cs
As mentioned by @PureWeen in #6548 [here](https://github.com/xamarin/Xamarin.Forms/pull/6548#pullrequestreview-252002377), issue #2577  could have an automated test. So, here it is!
N/A
None
None
None
Not applicable
> Added UITest for #2577

- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
- VS [bug 939527](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/939527)
None
- Android
the Previewer will show TabbedPage
Before
After
- Create a Xamarin Forms project, select the `Tabbed` template 
- Open file `MainPage.xaml` (Views->MainPage.xaml) 
- Click "Design" to open previewer
- Select platform as `Android`
> VS bug [#948950](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/948950)
> [Android] Fix previewer exceptions with TabbedPage

- Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
Adds null check.
- fixes #6539
- iOS
None
> Fixes GH 6539

- Xamarin.Forms.Core/DependencyService.cs
- Xamarin.Forms.Platform.UAP/WindowsBasePlatformServices.cs
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
the Xaml asssembly need to be scanned for DependecyServices. The
code in place intended it, but was referring to the wrong type...
- fixes #6974
None
- UWP
None
Not applicable
> [UWP] Register the Xaml assembly

- Xamarin.Forms.ControlGallery.Android/StaggeredCollectionViewRenderer.cs
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/AlternateLayoutGalleries/AlternateLayoutGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/AlternateLayoutGalleries/StaggeredLayout.xaml
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/AlternateLayoutGalleries/StaggeredLayout.xaml.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CollectionViewGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ExampleTemplates.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ScrollModeGalleries/ScrollModeTestGallery.xaml
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ScrollModeGalleries/ScrollModeTestGallery.xaml.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ScrollToCodeGallery.cs
- Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs
- Xamarin.Forms.Platform.Android/CollectionView/ScrollHelper.cs
- Xamarin.Forms.Platform.Android/CollectionView/SpacingItemDecoration.cs
Some minor changes to the Android CollectionView implementation to make custom renderers easier (specifically an overrideable method for creating a custom spacing decoration). 
Plus a demo using the StaggeredGridLayoutManager.
None
- Android
None
Not applicable
> [Android] Make it easier to create custom renderers for alternate CV layouts 

- Directory.Build.props
- Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj
Combined all values from the different `PropertyGroups` that have no conditions into one and removed the `DebugType` tags from the Android.AppLinks csproj file.
- Housekeeping for #6886
None
N/A
None
Not applicable
> [sourcelink] Cleaned up build.props and removed AppLinks csproj DebugType

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewHeaderFooterString.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewHeaderFooterTemplate.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewHeaderFooterView.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterGrid.xaml
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterGrid.xaml.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewRenderer.cs
Implement header/footer for CollectionView on iOS.
Note: This only implements static header/footer - this does not include sticky headers.
- implements part of #3172
- iOS
- Automated
> [iOS] CollectionView Header/Footer

- Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
Cherry pick #6151 back to 3.6.0. This doesn't guarantee we are going to do an SR of 3.6 but we want this fix inside 3.6+ branches if we decide to do SRs
> Cherry pick Update ScrollViewRenderer.cs (#6151) to 3.6

- Xamarin.Forms.Platform.iOS/Forms.cs
Adding this bool to work more specifically on new iOS 13 features.
No tests for the other bools, so none here.
> [iOS] Added static bool and check for iOS 13

- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
- Xamarin.Forms.Platform.Android/Forms.cs
- Xamarin.Forms.Platform.Android/Platform.cs
- Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutTemplatedContentRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ShellRenderer.cs
Add profiler instrumentation for startup code paths. Does not affect any behavior. If the Shell template is run and the profile visualized, then you'll see areas that need improvement and those improvements will follow shortly. I cleaved out these no-op changes into this PR so the changes that do affect behavior are smaller and easier to digest.
Also replaced some spaces with tabs. 
None
None
- Android
None
None. If things startup fine then everything is ok.
> Add profiler instrumentation

- Xamarin.Forms.Platform.Android/ContextExtensions.cs
Revert to old implementation but just store into static variable so it only checks once
> Replace IsDesignModeEnabled check with original Context Type Check

- Xamarin.Forms.Platform.iOS/Extensions/Extensions.cs
- Xamarin.Forms.Platform.iOS/Forms.cs
- Xamarin.Forms.Platform.iOS/PlatformRenderer.cs
Cherry pick of  https://github.com/xamarin/Xamarin.Forms/pull/7172 to 3.6
> Force iOS 13 to use Full Screen for Modal

- Xamarin.Forms.Platform.iOS/Forms.cs
- Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs
Cherry pick of https://github.com/xamarin/Xamarin.Forms/pull/7171 for 3.6 branch
> Fix MDP for iPads running iOS13

- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewRenderer.cs
Fixed a logic error and made a few refactoring attempts
> [iOS] CollectionView minor fixes

- Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs
- Xamarin.Forms.Platform.UAP/CollectionView/SelectableItemsViewRenderer.cs
Implements basic header/footer functionality for CollectionView on UWP
- implements part of #3172 
None
- UWP
None
Not applicable
In Control Gallery, navigate to CollectionView Gallery -> Header/Footer Galleries and try all the buttons.
> Basic Header/Footer for UWP CollectionView

- Xamarin.Forms.Platform.iOS/ContextScrollViewDelegate.cs
Fix NRE for bug #6776
- fixes #6776
None
- iOS
None
> Fix NRE for 6776

- azure-pipelines.yml
Add trigger for nightly to yaml
> [Build] Add nightly schedule

- Xamarin.Forms.Platform.iOS/ContextActionCell.cs
- Xamarin.Forms.Platform.iOS/Platform.cs
Check for `null`.
- fixes #4267
None
- iOS
None
> Fix NRE for gh 4267

- Xamarin.Forms.Build.Tasks/ExpandMarkupsVisitor.cs
- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh7187.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh7187.xaml.cs
- Xamarin.Forms.Xaml/ExpandMarkupsVisitor.cs
[X] Detect empty property value in markups
- fixes #7187
None
None
Not applicable
> [X] Detect empty property value in markups

- Xamarin.Forms.Xaml.UnitTests/LabelHtml.xaml
- Xamarin.Forms.Xaml.UnitTests/LabelHtml.xaml.cs
- Xamarin.Forms.Xaml/XamlParser.cs
handle CDATA properties
- fixes https://github.com/xamarin/Xamarin.Forms/pull/4527#issuecomment-525979139
None
None
Not applicable
> [X] handle CDATA explicit properties

- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
Make letter-spacing (CharacterSpacing) available for css.
https://cssreference.io/property/letter-spacing/
- https://github.com/xamarin/Xamarin.Forms/pull/5167#issuecomment-526865171
None
None
Not applicable
> css: letter-spacing

- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Pages.UnitTests/Xamarin.Forms.Pages.UnitTests.csproj
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- azure-pipelines.yml
- build/steps/build-windows.yml
Some CI updates, build on VS2019, update nugets to try fix OOM exceptions on CI
> [Build] Bump msbuild locator move to VS2019 

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/PositionControl.cs
- Xamarin.Forms.Core.UITests.Shared/Tests/CarouselViewUITests.cs
Fix failing tests for Carousel, we weren't t waiting for the swipe animation 
None
Not applicable
> [UItests] Fix CarouselView tests

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
The main goal here is to clarify what can be worked on and what branches should be targeted.
> Update contributing guide; tweak pull request template

- Xamarin.Forms.Platform.Tizen/Forms.cs
- Xamarin.Forms.Platform.Tizen/FormsApplication.cs
- Xamarin.Forms.Platform.Tizen/Platform.cs
- Xamarin.Forms.Platform.Tizen/PreloadedPlatform.cs
- Xamarin.Forms.Platform.Tizen/PreloadedWindow.cs
- Xamarin.Forms.Platform.Tizen/TizenPlatformServices.cs
This PR is for optimize launching time of application, it including belows
* Add prelaunching API
* Apply lazy loading for MD5 checksum
* Apply preload systeminfo
- fixes #
Added : 
``` c#
void Forms.Preload();
```
- Tizen
None
Not applicable
> [Tizen] Tizen renderer performance optimization

- Xamarin.Forms.Platform.Tizen/Forms.cs
- Xamarin.Forms.Platform.Tizen/TizenPlatformServices.cs
Update InitializationOptions for Tizen
- Can specify Assemly list for optimzied searching performance
- fixes #
Added : 
``` c#
public InitializationOptions(CoreApplication application, bool useDeviceIndependentPixel, params Assembly[] assemblies)
```
``` c#
var option = new InitializationOptions(app, true,
Assembly.GetAssembly(typeof(Forms)),
Assembly.GetAssembly(typeof(App)));
// Initiailize
Forms.Init(option)
```
- Tizen
None
Not applicable
> [Tizen] Update InitializationOptions

- .nuspec/Xamarin.Forms.Maps.nuspec
- .nuspec/Xamarin.Forms.Visual.Material.nuspec
- .nuspec/Xamarin.Forms.nuspec
- EmbeddingTestBeds/Embedding.Droid/Embedding.Droid.csproj
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
- Xamarin.Forms.Material.Android/Xamarin.Forms.Material.Android.csproj
- Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
- Xamarin.Forms.Sandbox.Android/Xamarin.Forms.Sandbox.Android.csproj
> Update support libraries from 28.0.0.1 to 28.0.0.3

- Xamarin.Forms.Core/Items/CarouselView.cs
Hide some CarouselView methods from IntelliSense.
- None
None
None
Not applicable
> Hide some CarouselView methods from IntelliSense

- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/Diagnostics/DebuggerHelper.cs
- Xamarin.Forms.Xaml/Diagnostics/ResourceDictionaryDiagnostics.cs
- Xamarin.Forms.Xaml/Diagnostics/VisualDiagnostics.cs
- Xamarin.Forms.Xaml/MarkupExtensions/StaticResourceExtension.cs
Add VisualDiagnostics for 🔥♻️
/
None
None
Not applicable
> visualDiagnostics

- Xamarin.Forms.Core.UnitTests/ViewUnitTests.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- await the tasks returned from animation
- Update MSBuild Locator to fix CI issues
> await tasks on ViewUnitTests and update MSBuild Locator

- Xamarin.Forms.Core.UnitTests/DeviceUnitTests.cs
Test fails on nunit3 because of check for async void so need to use new ThrowAsync api
> Update unit test to Nunit3 ThrowAsync api

- Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs
Small refactoring attempt to simplify reverse layout setting so that the code is more readable.
> [Android] Refactor the code for setting reverse layout in ItemsViewRenderer

- .nuspec/proguard.cfg
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
Adds additional classes to our default ProGuard configuration 
- fixes #5742
- Android
- download the nuget and test the scenario listed here #5742
> Add additional proguard classes to work with Bottom Tab Bar

- Xamarin.Forms.Core.Design/AttributeTableBuilder.cs
- Xamarin.Forms.Core.Design/KeyboardDesignTypeConverter.cs
- Xamarin.Forms.Core.Design/Xamarin.Forms.Core.Design.csproj
Added intelisense to Keyboard property
- fixes [835646](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/835646)
None
None
After
- create nuget and empty XF project
- update nuget in project
- check intellisense of `Keyboard` attribute in `Entry`, `Editor`, `SearchBar`, `EntryCell` elements
> [C] Added intelisense to Keyboard property

- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
Fix uitests not running because of mono shared runtime
> [UITests] Try again to run UItests

- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
- fixes #7301
- Android
Ran reproduction.
> NRE fix for 7301

- EmbeddingTestBeds/Embedding.UWP/Embedding.UWP.csproj
- PagesGallery/PagesGallery.UWP/PagesGallery.UWP.csproj
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7525.xaml.cs
- Xamarin.Forms.Core.UnitTests/DeviceUnitTests.cs
- Xamarin.Forms.Maps.UWP/Xamarin.Forms.Maps.UWP.csproj
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
- azure-pipelines.yml
- build.cake
- build/steps/build-windows.yml
Remove VS 2019 bits
- Make sure nuget works on VS 2017
> UWP fixes for lower target sdk on VS 2017

- Xamarin.Forms.Platform.WPF/Renderers/ImageRenderer.cs
Rollback 7.3 features on WPF for VS 2017 images
> Remove 7.3 features from WPF

- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselViewGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CollectionCarouselViewGallery.cs
Add more CarouselView samples
None
None
Not applicable
> [ControlGallery] Add more CarouselView samples

- Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs
fixes #7399 
- iOS
Reproduction passes.
> Fix NRE reported in 7399

- Xamarin.Forms.Xaml/XamlLoader.cs
- Xamarin.Forms.Xaml/XamlParser.cs
[X] send VisualTreeChanged for root
None
None
None
Not applicable
> [X] send VisualTreeChanged for root

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5395.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/VisualElementTracker.cs
Fixes anchor point for macOS.
Rotation, scaling and translation work as expected.
- fixes #5395
None
- MacOS
Rotation, scaling and translation work as expected
Not applicable
> [macOS] Fix Image Rotation issue

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7556.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs
Cherry pick MDP fix
- download nuget and test on ios 13 or test the included Gallery test
> Update iOS MDP Tablet Renderer to use current APIS for Master Behavior

- .gitignore
- Version.targets
- build.cake
Writes a file with the version so cake script can use it.
Run pack see if provides the metadata on package version
> [Build] Share package version with cake

- Xamarin.Forms.Xaml.UnitTests/Issues/Gh7830.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh7830.xaml.cs
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
regression introduced by #7531
- fixes #7830
None
None
Not applicable
> [X] pass the RootAssembly to DT Context

- Stubs/Xamarin.Forms.Platform.cs
Fix `RendererWith` attributes of Xamarin.Forms.Platform.Tizen (Forwarders). Plus, remove unnecessary condition for `ImageButtonRenderer`.
Fix the following exception when using `CollectionView` in Tizen app.
```cs
System.TypeLoadException: Could not load type 'Xamarin.Forms.Platform._CollectionViewRenderer' from assembly 'Xamarin.Forms.Platform, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 …
```
> [Tizen] Fix RenderWith attributes for Forwarders

- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.Controls/Properties/AssemblyInfo.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- azure-pipelines.yml
- build.cake
- build/steps/build-windows.yml
Reinstates the intentions of this PR https://github.com/xamarin/Xamarin.Forms/pull/7381 in a way that's compatible with our Directory.build.props
- Android
- make sure ui pass
- make sure you can run the android CG locally on windows and android
> [Android] speed up development builds

- Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
- fixes #7888
None
- iOS
None
Not applicable
> [iOS] Label size doesn't change when text changed

- Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutTemplatedContentRenderer.cs
- Xamarin.Forms.Platform.UAP/SwitchRenderer.cs
Fixes small issues from a merge in 4.3.0.
None
d
- UWP
None
Not applicable
> [HouseKeeping] Fixed build error in 4.3.0

- Xamarin.Forms.Material.Tizen/MaterialStepperRenderer.cs
This PR is to add material renderer of `Stepper`
- None
None
- Tizen
None
- Before
- After
> [Tizen] Add Meterial Stepper Renderer

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1747.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1747.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ViewModel.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Creating automated UI tests for the issue 1747
- fixes #2237
None
- iOS
- Android
- UWP
None
Not applicable
Run UI tests
> Creating automated UI tests for the issue 1747

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41038.cs
> Add instructions for B41038

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41029.cs
> Changed manual test and added instructions for B41029

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1342.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5766.cs
- Xamarin.Forms.Core.UITests.Shared/Tests/CarouselViewUITests.cs
Ignore tests that based on the test info here https://dev.azure.com/xamarin/public/_test/analytics?definitionId=3&contextType=release should be ignored and worked in a better version
None
- iOS
- Android
None
Not applicable
> Fix random test failures

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla33870.cs
Creating automated UI Test for the Bugzilla issue 33870
- fixes #2257
None
- iOS
- Android
- UWP
None
Not applicable
Run UI tests
> Automating bugzilla issue 33870

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla38770.cs
Adding instructions to the UI Test 38700
- Fixes #2303
None
- UWP
None
Not applicable
> Adding instructions to the UI Test (issue 38770)

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6663.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.CustomAttributes/TestAttributes.cs
- Xamarin.Forms.Platform.GTK/Controls/Page.cs
- Xamarin.Forms.Platform.GTK/Platform.cs
- Xamarin.Forms.Platform.GTK/Renderers/NavigationPageRenderer.cs
Clean-rebase version of this other PR: https://github.com/xamarin/Xamarin.Forms/pull/7931
Either merge that one, or this one. Thanks
Fixes #6663
> Revert "[GTK] Fix visibility of hidden pages in the stack (#3904)

- Xamarin.Forms.Core.UnitTests/ViewUnitTests.cs
- Xamarin.Forms.Core/AnimationExtensions.cs
Wish to reduce code size for batch updates (BatchBegin + BatchCommit)
**Compare:**
- **BEFORE:**
```csharp
try
{
view.BatchBegin();
//update properties
}
finally
{
view.BatchCommit();
}
```
- **AFTER:**
```csharp
using (view.Batch())
{
// update properties
}
```
Added:
- An extension method to IAnimatable (Batch)
- Core
None
Not applicable
I added an Unit Test. Just run it and verify it passes
> [Enhancement] Batch updates via "using" statement

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2241.cs
Added instructions and changed the manual test as well as the automated test. Please make sure the new automation works (I haven't had a chance to run it).
- fixes #2274
> Added instructions and changed the test for Issue2241

- Xamarin.Forms.Platform.iOS/Cells/CellRenderer.cs
Set the default background color for a cell to transparent
- fixes #7680
- fixes #7850
None
- iOS
To my knowledge, and as far as I have checked with the gallery app, this still works fine so people should not notice any changes. However, people who do some customization with the background color of underlaying elements for these cells might suddenly see something weird.
This change is needed to make the selection work again on apps that are built agains the iOS 13 APIs (see #7680 for some background (hi-hi) information)
This change was imminent also because of the preparation on dark mode support.
Before (with Dark Mode, notice the selection is not visible only barely because of the seperator line being gone)
After (with Dark Mode)
After (without Dark Mode)
> iOS Cell default bgcolor to transparent

- Xamarin.Forms.Platform.WPF/Renderers/ListViewRenderer.cs
Implements ListView.Scrolled event in WPF
None
- WPF
None
Not applicable
Control gallery listview page
> [WPF]  ListView.Scrolled event implemented

- Xamarin.Forms.Platform.MacOS/Renderers/MasterDetailPageRenderer.cs
Fixed the bug when `MasterDetailPage.MasterBehavior` is PopOver on macOS:
`IsPresented` has no effect.
- fixes #3149
None
- macOS
None
Not applicable
> macOS: Fixed IsPresented PopOver

- azure-pipelines.yml
- build.cake
- build/provisioning/provisioning.csx
- build/steps/build-android.yml
- build/steps/build-osx.yml
- build/steps/build-windows.yml
Some updates to build system:
- Remove image reference
- Clean repos on checkout
- Specify sdk's Xamarin Forms depends
- iOS
- Android
- UWP
None
Not applicable
> [Build] Clean repos, update vs image

- Xamarin.Forms.Platform.Android/Renderers/ShellItemRenderer.cs
Fixes issues using API21 api when running on Android with API19 
- fixes test case 8145 on API19
None
- Android
Should not crash
Not applicable
Run ControlGallery and visit the issue 8145 on a API19 device.
> [Android] Fix API21 usage on shell

- Xamarin.Forms.Xaml.UnitTests/Issues/Bz24485.xaml
Add a missing `}` in `Xamarin.Forms.Xaml.UnitTests/Issues/Bz24485.xaml`
None
None
None
Not applicable
> Add a missing '}' in Xamarin.Forms.Xaml.UnitTests/Issues/Bz24485.xaml

- Xamarin.Forms.Xaml/MarkupExtensions/FontImageExtension.cs
fixes https://github.com/xamarin/Xamarin.Forms/pull/7887#issuecomment-549437276
/cc @davidbritch 
/
> [X] FontSizeConverter on FontImageExtension

- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
Changing target min platform lowered the available reflection APIs with UWP so needed to fix one once changes got merged to master
- UWP
> Fx reflection call on UWP

- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/ILContext.cs
- Xamarin.Forms.Build.Tasks/ILRootNode.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Build.Tasks/XamlTask.cs
- Xamarin.Forms.Xaml/Diagnostics/VisualDiagnostics.cs
- Xamarin.Forms.Xaml/XamlNode.cs
When compiling in DEBUG, Register sourceInfo even for compiled code
/
None
None
Not applicable
> [X] RegisterSourceInfo for XamlC

- Stubs/Xamarin.Forms.Platform.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/CarouselView.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/CollectionView.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/LinearLayoutManager.cs
- Xamarin.Forms.Platform.Tizen/Properties/AssemblyInfo.cs
- Xamarin.Forms.Platform.Tizen/Renderers/CarouselViewRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ItemsViewRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/StructuredItemsViewRenderer.cs
Makes the CarouselView functionality work on Tizen.
- Fix RenderWith attributes for Forwarders
- Add StructuredItemsViewRenderer
- Add CarouselViewRenderer
None
- Tizen
None
Not applicable
Launch Tizen Core Gallery and try the CarouselView Galleries sample.
(Tizen Core Gallery - CollectionView Gallery - CarouselView Galleries)
> [Tizen] Add CarouselViewRenderer

- Xamarin.Forms.Platform.Tizen/StaticRegistrar.cs
Fix build 4.4.0
- fixes #
None
- Tizen
None
Not applicable
> [Tizen] Update StaticRegistrar

- Stubs/Xamarin.Forms.Platform.cs
- Xamarin.Forms.Platform.Tizen/Properties/AssemblyInfo.cs
- Xamarin.Forms.Platform.Tizen/Renderers/SwipeViewRenderer.cs
- Xamarin.Forms.Platform.Tizen/ResourcePath.cs
- Xamarin.Forms.Platform.Tizen/StaticRegistrar.cs
* Add SwipeViewRenderer for Tizen on swipeview-II branch
related PR : https://github.com/xamarin/Xamarin.Forms/pull/7603
- fixes for Tizen #3171
None
- Tizen
None
> [Tizen] Add SwipeViewRenderer on Tizen

- Xamarin.Forms.Platform.Tizen/FormsApplication.cs
This PR is a patch to optimize application startup time so that you can use pre-created window object (that is created by the system process in idle time) instead of creating new ones when initializing your application. 
The platform API that provides Precreated Window was newly added in Tizen 5.5 (`API 6`), so it was implemented through reflection to avoid breaking existing ABI compatibility. As a result, on Tizen platforms(4.0 and 5.0) prior to Tizen 5.5, it works without any change from the existing operation. And, on the Tizen platform 5.5 or later, we can expect the effect of reducing the launch time (about 50~100ms) through pre-created window.
None
None
- Tizen
None
Not applicable
> [Tizen] Use pre-created window at initailzation time

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Cells/CellRenderer.cs
- Xamarin.Forms.Platform.iOS/Cells/EntryCellRenderer.cs
- Xamarin.Forms.Platform.iOS/Cells/ImageCellRenderer.cs
- Xamarin.Forms.Platform.iOS/Cells/SwitchCellRenderer.cs
- Xamarin.Forms.Platform.iOS/Cells/TextCellRenderer.cs
- Xamarin.Forms.Platform.iOS/Cells/ViewCellRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs
- Xamarin.Forms.Platform.iOS/ResourcesProvider.cs
Some additional constructors needed Preserve Attributes.
> [iOS] Additional Preserve Attributes

- azure-pipelines.yml
Update the nuget version for release
None 
None
- iOS
- Android
- UWP
None
Not applicable
> [Build]Update nuget release number

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
Update UITests packages 
-None
None
- iOS
- Android
None
Not applicable
> [UITests] Update Xamarin.UITests packages

- Xamarin.Forms.Platform.Tizen/Native/EditfieldEntry.cs
- Xamarin.Forms.Platform.Tizen/Native/SearchBar.cs
- Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs
Enhancement EntryRenderer
- Support ReturnType.Next
- Support ClearButtonVisibility
- Limitation 
- No support `ClearButtonVisibility` on TV
- No support `ClearButtonVisibility` on Wearable Tizen Version lower than Tizen 5.5 
- fixes https://github.com/xamarin/Xamarin.Forms/issues/5228 , https://github.com/xamarin/Xamarin.Forms/pull/5277
None
- Tizen
None
> [Tizen] Enhancement EntryRenderer

- Xamarin.Forms.Platform.GTK/Cells/EntryCell.cs
- Xamarin.Forms.Platform.GTK/Cells/ImageCell.cs
- Xamarin.Forms.Platform.GTK/Cells/TextCell.cs
- Xamarin.Forms.Platform.GTK/Controls/DatePicker.cs
- Xamarin.Forms.Platform.WPF/Microsoft.Windows.Shell/Standard/ErrorCodes.cs
- Xamarin.Forms.Platform.WPF/Microsoft.Windows.Shell/Standard/NativeMethods.cs
- Xamarin.Forms.Platform.WPF/Microsoft.Windows.Shell/SystemParameters2.cs
Follow your [current style guide](https://github.com/xamarin/Xamarin.Forms/tree/d6ddd53ed551f85712bb244b74bac27c7dc643f7#coding-style).
> Remove private modifier

- Xamarin.Forms.Core/Internals/NameScope.cs
Adds the actual name to the exception so it's easier to solve by the user.
- fixes #7540
None
None
> Add name of key in INameScope.RegisterName ArgumentException

- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Controls/global.json
Switch to using a global.json file instead of having it as part of the CSPROJ
> Reference Sdk Extras in a way that works with netcore 2

- Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs
- Xamarin.Forms.ControlGallery.WindowsUniversal/App.xaml.cs
- Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs
- Xamarin.Forms.Core/ExperimentalFlags.cs
- Xamarin.Forms.Core/SwipeView.cs
- Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs
- Xamarin.Forms.Platform.UAP/SwipeViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs
Add experimental flag for SwipeView
> Put SwipeView behind experimental flag

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
fixes: #5177
fixes #5177
None
- Android
None
**Before**
**After**
> fix back icon color for the navigation page

- Xamarin.Forms.Xaml.UnitTests/XamlC/FieldReferenceExtensionsTests.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/MethodDefinitionExtensionsTests.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/MethodReferenceExtensionsTests.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/ModuleDefinitionExtensionsTests.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/TypeReferenceExtensionsTests.cs
Make sure to dispose resolver and module.
- fixes fails on unit tests
None
- iOS
- Android
- UWP
None
Not applicable
> [UnitTests] Fix OOM exception on unit tests

- .nuspec/Xamarin.Forms.nuspec
- EmbeddingTestBeds/Embedding.UWP/Embedding.UWP.csproj
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- PagesGallery/PagesGallery.UWP/PagesGallery.UWP.csproj
- PagesGallery/PagesGallery.iOS/PagesGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.MacOS/Xamarin.Forms.ControlGallery.MacOS.csproj
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Maps.GTK/Xamarin.Forms.Maps.GTK.csproj
- Xamarin.Forms.Maps.UWP/Xamarin.Forms.Maps.UWP.csproj
- Xamarin.Forms.Pages.Azure/Xamarin.Forms.Pages.Azure.csproj
- Xamarin.Forms.Pages/Xamarin.Forms.Pages.csproj
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
Updating the UWP package to 6.0.15 to take advantage of bug fixes. Also consolidating and updating some packages in use by the test projects.
n/a
None
- UWP
None
Not applicable
Run automated tests.
> [UWP] Update to 6.0.15

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4606.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Material.Android/MaterialButtonRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/ImageButtonRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/BorderDrawable.cs
Cherry pick of corner clipping fixes
- Make sure included ui test operates how you'd expect it to
> Fix corner clipping on ImageButton and Button (FR) (#7723)

- Xamarin.Forms.Build.Tasks/XamlCTask.cs
An assembly resolver holds opened files, and leaks if it is not disposed. It is problematic if you run Xamarin.Forms.Xaml.UnitTests on Linux with the default configuration because it has a small limit for the number of opened files. It may cause stability issues also on other platforms, depending on the situation.
None
None
None
Not applicable
Run `Xamarin.Forms.Xaml.UnitTests` with a debugging means like strace. You'll see the number of the file descriptor will not keep increasing while it does without this change.
> [XamlC] Dispose assembly resolver constructed by XamlCTask

- Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs
InputTransparencyTest for Frame should pass now.
> Stop Frame shadow from blocking user input on iOS

- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Core/BindingExpression.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh8936.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh8936.xaml.cs
this was regressed by #7836
- fixes #8936
None
None
Not applicable
> [C,X] Resolve indexers on base class

- Xamarin.Forms.Platform.Tizen/Shell/ShellNavBar.cs
- Xamarin.Forms.Platform.Tizen/Shell/ShellSectionNavigation.cs
This PR is to fix navigating page issue in Shell when a user click a back button.
None
None
- Tizen
None
- Before
- After
> [Tizen] Fix back button issue in Shell navigation

- Xamarin.Forms.Platform.Tizen/LightweightPlatform.cs
- Xamarin.Forms.Platform.Tizen/Platform.cs
- Xamarin.Forms.Platform.Tizen/PopupManager.cs
* Enhancement LightweightPlatform on Tizen
* Supporting Modal stack
* Supporting dialogs(alert/action sheet/prompt/waiting)
* It improve startup time at page push
``` c#
Forms.Init(new InitializationOptions(app)
{
PlatformType = PlatformType.Lightweight
});
```
- fixes #
None
- Tizen
None
Before                      /               After
> [Tizen] Enhancement LightweightPlatform on Tizen

- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- build/steps/build-osx.yml
Copying system.* files to appcenter can cause weird issues
- UI Tests still run
> Don't copy system files to appcenter

- Xamarin.Forms.Core/Registrar.cs
Add assembly name to frameend call
- make sure you can launch the android CG
> fix Profile FrameEnd call

- Xamarin.Forms.Core/Xaml/Diagnostics/VisualDiagnostics.cs
> send remove events

- Xamarin.Forms.ControlGallery.Tizen/ControlGallery.Tizen.cs
- Xamarin.Forms.ControlGallery.Tizen/Xamarin.Forms.ControlGallery.Tizen.csproj
- Xamarin.Forms.Material.Tizen/Shell/MaterialNavigationView.cs
- Xamarin.Forms.Material.Tizen/Xamarin.Forms.Material.Tizen.csproj
- Xamarin.Forms.Platform.Tizen/Extensions/ImageExtensions.cs
- Xamarin.Forms.Platform.Tizen/Native/Image.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ImageRenderer.cs
- Xamarin.Forms.Platform.Tizen/Shell/INavigationView.cs
- Xamarin.Forms.Platform.Tizen/Shell/NavigationView.cs
- Xamarin.Forms.Platform.Tizen/Shell/ShellRenderer.cs
This PR is to support below Background Image properties of Shell.Flyout on Tizen.
- Shell.FlyoutBackgroundImage
- Shell.FlyoutBackgroundImageAspect
fixes #4410
Changed
- Image.LoadFromImageSourceAsync()
- Image.LoadFromFile()
These two methods are changed to extension method for `Elmsharp.Image` from `Native.Image` member methods.
- Tizen
The background Image of flyout will be shown on Tizen.
- Before
- After
> [Tizen] Shell: FlyoutBackgroundImage, FlyoutBackgroundImageAspect

- Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeViewGallery.cs
Added the SwipeView tag to the Core Gallery samples (housekeeping).
None
None
Not applicable
Launch Core Gallery and navigate to the SwipeView samples. Verify that you can browse the SwipeView samples without any exception.
> Added the SwipeView tag to the Core Gallery samples

- .github/ISSUE_TEMPLATE/bug_report.md
By adding the workaround heading to the bug template people will think about a possible workaround, or maybe they already know about it but are not triggered to report it. This way other people landing on an issue might be unblocked while waiting for the issue to be resolved
> Add workaround header to bug report template

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/Extensions/AccessibilityExtensions.cs
- Xamarin.Forms.Platform.Android/Extensions/ToolbarExtensions.cs
- Xamarin.Forms.Platform.Android/ResourceManager.cs
Address ABI breaks introduced with 4.4
fixes #9164 
- Check the release notes and see if I missed anything or fixed incorrectly
- run ABI check tool comparing 4.4.0.991265 to the nuget created by this pr
> Fix introduced ABI breaks

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Fix usage of deprecated API 
- None
None
Not applicable
> [Android] Fix color filter usage on API29

- azure-pipelines.yml
Because of how PRs merge with the source branch on CI we need to specify a specific 2017 image for 4.4 and 4.5 to stay independently functional
- build passes
> Add 2017 Image for 4.4.0 builds

- Xamarin.Forms.Platform.WPF/Renderers/ListViewRenderer.cs
Wrapped the ListView in a Grid that allows for the insert/delete of headers and footers.
- fixes #3947 
- fixes #3770
None
Added:
No public changes.
-WPF
Headers and footers will not show on Platform.WPF
> Implements ListView Header and Footer for WPF

- Xamarin.Forms.Xaml.UnitTests/Issues/Bz24485.xaml
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/XamlLoader.cs
make sure we can trace the relative uri back to the originator
None
None
Not applicable
> [HR] complement the sourceinfo with assemblyname

- Xamarin.Forms.Core.UnitTests/ItemsViewTests.cs
- Xamarin.Forms.Core/Items/ItemsView.cs
Propagate BindingContext on the ItemsView to the ItemsLayout
> Propagate BindingContext to ItemsLayout

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7701.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
(copy from #8031)
Incorporated changes in iOS13 pertaining to navigation bar background color.
- fixes #7701
- fixes #7350 
- fixes #7679 (possibly)
> [iOS] Fix navigation bar background color in iOS13

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/EventTracker.cs
- Xamarin.Forms.Platform.iOS/Extensions/UIApplicationExtensions.cs
- Xamarin.Forms.Platform.iOS/Platform.cs
- Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
Replace KeyWindow api with non deprecated api
- iOS
- ios still works
> Remove uses of deprecated KeyWindow

- UWP.Build.props
Fix TPV on UWP platform projects
- UWP
> Fix TPV on UWP platform projects

- .github/PULL_REQUEST_TEMPLATE.md
fix broken link in PULL_REQUEST_TEMPLATE.md
None
None
None
Not applicable
> fix broken link in PULL_REQUEST_TEMPLATE.md

- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
Fix loading image vector on 4.4.0
None
- Android
None
Not applicable
> [Controls, Android] Fix tests on 4.4.0

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9355.cs
Fix failing tests on 4.5.0 for iOS and Android
- fixes failing tests
None
- iOS
- Android
None
Not applicable
> [Controls, iOS, Android] Fix tests on 4.5.0

- .nuspec/Xamarin.Forms.props
Adds `HOTRESTART` define constant to support conditional compilation, the property `IsHotRestartBuild` will be set from Visual Studio to enable this scenario.
> Adds HotRestart conditional compilation

- Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs
If the RecylerView is still scrolling after it's been disposed there's a race condition where the unmanaged code might still try to call into the managed code.
This changes the implementation over to using a listener so that the listener can be removed as soon as possible
- Android
> Move CarouselViewRenderer scrolled overrides to listener

- Xamarin.Forms.Platform.MacOS/Properties/AssemblyInfo.cs
Preserve the macOS assembly from the linker
- fixes #
None
- macOS
None
Not applicable
> Preserve the macOS assembly from the linker

- Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs
- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Controls/GalleryPages/TwoPaneViewGalleries/NestedTwoPaneViewSplitAcrossHinge.xaml
- Xamarin.Forms.Controls/GalleryPages/TwoPaneViewGalleries/NestedTwoPaneViewSplitAcrossHinge.xaml.cs
- Xamarin.Forms.Controls/GalleryPages/TwoPaneViewGalleries/TwoPaneViewGallery.cs
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.DualScreen.UnitTests/TestDeviceInfo.cs
- Xamarin.Forms.DualScreen.UnitTests/TestDualScreenService.cs
- Xamarin.Forms.DualScreen.UnitTests/TwoPaneViewNotSpannedTests.cs
- Xamarin.Forms.DualScreen.UnitTests/TwoPaneViewSpannedTests.cs
- Xamarin.Forms.DualScreen/DualScreenInfo.shared.cs
- Xamarin.Forms.DualScreen/DualScreenService.android.cs
- Xamarin.Forms.DualScreen/DualScreenService.uwp.cs
- Xamarin.Forms.DualScreen/IDualScreenService.shared.cs
- Xamarin.Forms.DualScreen/NoDualScreenServiceImpl.shared.cs
- Xamarin.Forms.DualScreen/TwoPaneView.shared.cs
- Xamarin.Forms.DualScreen/TwoPaneViewLayoutGuide.shared.cs
- Xamarin.Forms.Platform.Android/Properties/AssemblyInfo.cs
- Added the start of a gallery
- Fixed some layout timing issues. Basically I added handlers on the native layer to report back to the TPV once the native layout is finished so that I can accurately adjust the position relative to the hinge
- play with the gallery
> Fix TPV to adjust to native layout changes better

- build/steps/build-nuget.yml
Fix key
None
None
Not applicable
> [Build] Fix variable

- .github/CONTRIBUTING.md
Fixed link to PULL_REQUEST_TEMPLATE.md in CONTRIBUTING.md
> Fixed broken link in CONTRIBUTING.md

- azure-pipelines.yml
- build/scripts/generate-docs.ps1
- build/steps/build-android.yml
- build/steps/build-windows.yml
Clean workspaces when building on ci
None
- iOS
- Android
- UWP
None
Not applicable
> [Build] Add workspace clean

- Xamarin.Forms.ControlGallery.Android/Assets/googlemap.html
- Xamarin.Forms.ControlGallery.Android/Assets/googlemapsearch.html
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/issue3262.cs
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Platform.Android/Renderers/FormsWebViewClient.cs
- Xamarin.Forms.Platform.UAP/WebViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/WebViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs
- NRE check on Android
- NRE check on ios
- setup cookies on WkWebViewRenderer
- iOS
- Android
- UWP
> WebView cookie changes fixes

- Xamarin.Forms.Platform.Android/Cells/ViewCellRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
- Xamarin.Forms.Platform.Android/VisualElementPackager.cs
I remarked that Performance call stop are missing in some places, I added them.
None
None
Android
None
Not applicable
Nothing particular
> [Android] Fix unbalanced performance start/stop call

- README.md
> Update VS 2015 -> Visual Studio for Windows

- Xamarin.Forms.Controls/GalleryPages/IndicatorViewGalleries/IndicatorsSampleMaximumVisible.xaml
- Xamarin.Forms.Controls/GalleryPages/IndicatorViewGalleries/IndicatorsSampleMaximumVisible.xaml.cs
- Xamarin.Forms.Core/IndicatorStackLayout.cs
- Xamarin.Forms.Core/IndicatorView.cs
- Xamarin.Forms.Platform.Android/CollectionView/IndicatorViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/IndicatorViewRenderer.cs
Implement MaximumVisible on the renderers and core 
- fixes #8912 
None
- iOS
- Android
None
Not applicable
Visit the page `IndicatorsSampleMaximumVisible`  , Verify there's 5 indicators, click `Change MaximumVisible`  and verify that we have only 3 indicators, click it again and check if we have 2 indicators.
> [iOS,Android,Core] Implement MaximumVisible  on iOS and Android 

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewItemsUpdatingScrollMode.cs
Rewriting test to work even if UITest still somehow sees slightly off-screen items.
> Make KeepItemsInView test more reliable

- .nuspec/Xamarin.Forms.DualScreen.nuspec
- Xamarin.Forms.DualScreen/DualScreenService.android.cs
- Xamarin.Forms.DualScreen/Xamarin.Forms.DualScreen.csproj
Added Null Check in GetHinge() that was causing crashes when using the DualView class.
- fixes #0001 Added null check.
None
- Android
None
Not applicable
> Added check for null hinge in GetHinge()

- Xamarin.Forms.Platform.Android/Renderers/BottomNavigationViewUtils.cs
- build.cake
Convert provisioning over to use new boots properties that keeps our UI tests running against stable bits
- make sure it can all build
> Boots updates

- Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs
Amended typo in EditorRenderer on Android
- fixes #9862
None
- Android (just message text)
Proper text in the warning 
Not applicable
> Amended typo in Obsolete Attribute message in EditorRenderer

- Xamarin.Forms.Core/StateTriggerBase.cs
Fixed mistake in StateTriggersExperimental verification.
None
- Core
None
Not applicable
Launch any StateTrigger sample without using the experimental flag. An exception will be raised and the message will appear. Verify that the message indicate the correct flag and base class (StateTriggerBase).
> Fixed mistake in StateTriggersExperimental verification

- azure-pipelines.yml
- build.cake
- build/steps/build-android.yml
- build/steps/build-windows.yml
Update some build images
None
None
Not applicable
> [Build] Update pool and pipelines

- Xamarin.Forms.Core/Style.cs
This is the same fix from #9195 - we just forgot to apply it to Style as well as AttachedCollection.
- Fixes #9656
None
> Apply NRE fix from #9195 to Style

- .nuspec/Xamarin.Forms.nuspec
- Xamarin.Forms.Platform.UAP/Platform.cs
- Xamarin.Forms.Platform.UAP/Resources.xaml
- Xamarin.Forms.Platform.UAP/Shell/ShellRenderer.cs
- Xamarin.Forms.Platform.UAP/Shell/ShellStyles.xaml
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
- UWP
- Go to the shell store on UWP and click the button for changing the flyout background color
> [Shell] Implement FlyoutBackgroundColor for UWP

- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.Core/SwipeView.cs
Fix SwipeItem cast issue on SwipeView.
None
- Core
None
Not applicable
> Fix SwipeItem cast issue on SwipeView

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9306.cs
Fix failing UITest in 4.5 branch.
> Fix failing UITest in 4.5 branch

- EmbeddingTestBeds/Embedding.iOS/Embedding.iOS.csproj
- PagesGallery/PagesGallery.iOS/PagesGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- azure-pipelines.yml
- build.cake
Remove old archs when building on iOS
- none
None
- iOS
None
Not applicable
Change the macOSXvariable on the build lane to macos-14.5
> [Build] Fixes to build on Catalina

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9088.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9306.cs
Fixed failing SwipeView UITests on Android (Api Level 19).
> Fixed failing SwipeView UITests on Android (Api Level 19)

- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
fix master build
- master builds
> Set Unit Test Projects to add when built from source or nuget

- Xamarin.Forms.Controls/GalleryPages/EmbeddedFonts.xaml
- Xamarin.Forms.Core/FontRegistrar.cs
- Xamarin.Forms.Platform.Android/Renderers/FontExtensions.cs
- Xamarin.Forms.Platform.Tizen/Extensions/FontExtensions.cs
- Xamarin.Forms.Platform.UAP/FontExtensions.cs
- Xamarin.Forms.Platform.iOS/EmbeddedFontLoader.cs
- Xamarin.Forms.Platform.iOS/Extensions/FontExtensions.cs
iOS and android had times when the emebedded font's were not loaded
- fixes #9190
- fixes #9255
None
- iOS
- Android
> Embedded fonts fix

- .nuspec/Xamarin.Forms.Visual.Material.nuspec
- EmbeddingTestBeds/Embedding.iOS/AppDelegate.cs
- EmbeddingTestBeds/Embedding.iOS/Embedding.iOS.csproj
- PagesGallery/PagesGallery.iOS/AppDelegate.cs
- PagesGallery/PagesGallery.iOS/PagesGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs
- Xamarin.Forms.ControlGallery.iOS/PerformanceTrackerRenderer.cs
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Material.iOS/IMaterialTextField.cs
- Xamarin.Forms.Material.iOS/MaterialMultiLineTextField.cs
- Xamarin.Forms.Material.iOS/MaterialProgressBarRenderer.cs
- Xamarin.Forms.Material.iOS/MaterialSliderRenderer.cs
- Xamarin.Forms.Material.iOS/MaterialTextField.cs
- Xamarin.Forms.Material.iOS/MaterialTextManager.cs
- Xamarin.Forms.Material.iOS/Xamarin.Forms.Material.iOS.csproj
Bump MDC library to latest release
- iOS
- there shouldn't be any
- test the visual gallery page make sure nothing looks off or changed from previous version
- Compare to Android
> iOS Material Components Bump

- Xamarin.Forms.Core.UnitTests/ShellLifeCycleTests.cs
- Xamarin.Forms.Core.UnitTests/ShellModalTests.cs
- Xamarin.Forms.Core.UnitTests/ShellTestBase.cs
- Xamarin.Forms.Core.UnitTests/ShellTests.cs
- Xamarin.Forms.Core/Page.cs
- Xamarin.Forms.Core/Routing.cs
- Xamarin.Forms.Core/Shell/BaseShellItem.cs
- Xamarin.Forms.Core/Shell/Shell.cs
- Xamarin.Forms.Core/Shell/ShellUriHandler.cs
- Fix Navigating/Navigated/OnNavigating/OnNavigated so they fire the correct number of times
- Process ".." navigation as going back one url path
- fixes #9169
- partially fixes #8904
Unit tests included
> Fix navigating/navigated events and add ".." navigation

- Xamarin.Forms.Core.UITests.Shared/Tests/ExpanderViewUITests.cs
A new middle page was added to allow for more galleries and to enable the expander flag
- make sure UI tests pass
> Fix navigation to expander test

- README.md
Link was dead, now it's not!
- fixes #10215
> Fix coding style dead link in readme

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellInsets.cs
Fix EntryScrollTest_apple_iphone
- None
None
- iOS
None
Not applicable
UItests should pass
> [UITests] Fix scrolling test

- Xamarin.Forms.Platform.Android.UnitTests/ShellTests.cs
- Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutTemplatedContentRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ShellRenderer.cs
Watch for flyout header changes and swap it out
- partially fixes #6161
- Android
- automated UI Tests
> [Android] Let user swap out Flyout Header on Shell

- Xamarin.Forms.Controls/ControlGalleryPages/ListViewSelectionColor.cs
- Xamarin.Forms.Controls/GalleryPages/GroupedListActionsGallery.cs
- Xamarin.Forms.Controls/GalleryPages/GroupedListContactsGallery.cs
- Xamarin.Forms.Controls/GalleryPages/ListPage.cs
- Xamarin.Forms.Core/ListView.cs
- Xamarin.Forms.Core/StackLayout.cs
- Xamarin.Forms.Platform.WPF/CellControl.cs
- Xamarin.Forms.Platform.WPF/Converters/ViewToRendererConverter.cs
- Xamarin.Forms.Platform.WPF/FormsPanel.cs
- Xamarin.Forms.Platform.WPF/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.WPF/WPFResources.xaml
Apply template for ListViewItem, fix NRE and ArgumentOutOfRangeException
- fixes #6436 
- fixes #8039
- fixes #9029
- fixes #5682
- fixes #6842
Changed:
- Move measure cell size on ItemAppearing (see CellControl.cs)
Added:
- override WSize MeasureOverride(WSize constraint) 
- Core
- WPF
Before WPF:
After:
WPF:
GTK:
ControlGallery->ListView SelectionColor Gallery
> [Bug] [Core+WPF] Grid + ListView -> first row height not correct + width not correct + ArgumentOutOfRangeException when tapped

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9794.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/CollectionView/DefaultCell.cs
- Xamarin.Forms.Platform.iOS/CollectionView/HeightConstrainedTemplatedCell.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewCell.cs
- Xamarin.Forms.Platform.iOS/CollectionView/TemplatedCell.cs
- Xamarin.Forms.Platform.iOS/CollectionView/WidthConstrainedTemplatedCell.cs
- Xamarin.Forms.Platform.iOS/ModalWrapper.cs
- Xamarin.Forms.Platform.iOS/Renderers/PageContainer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs
- Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs
Exported attributes get linked out if you don't mark them as preserve
- fixes #9794 
- iOS
- ui tests pass
> Add Preserve attributes to all Export attributes

- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Controls/CoreGalleryPages/RadioButtonCoreGalleryPage.cs
- Xamarin.Forms.Controls/GalleryPages/GalleryBuilder.cs
- Xamarin.Forms.Controls/GalleryPages/RadioButtonGalleries/RadioButtonGalleries.cs
- Xamarin.Forms.Controls/GalleryPages/RadioButtonGalleries/RadioButtonGroupGalleryPage.xaml
- Xamarin.Forms.Controls/GalleryPages/RadioButtonGalleries/RadioButtonGroupGalleryPage.xaml.cs
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Core/Expander.cs
- Xamarin.Forms.Core/ExperimentalFlags.cs
- Xamarin.Forms.Core/RadioButton.cs
Add the experimental flag to Radio Button
- iOS
- Android
- UWP
- make sure core gallery can run without errors
- make sure the flag works via the Radio Button Gallery
> RadioButton Experimental  Flag

- Xamarin.Forms.Platform.iOS/Extensions/FontExtensions.cs
- Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs
PR #10396 should've targeted 4.6, but noticed only after merging it in master. So cherrypicking this one back to 4.6.
> Cherrypick #10396 (embedded fonts iOS fix) to 4.6

- Xamarin.Forms.Core/Expander.cs
Made internal Expander control refactoring.
1) Added ContentHolder for preventing cutting off the animation.
2) Updated method of getting the content height.
- fixes #10230
None
- Core
No UI glitches.
**BEFORE**
Can be found in the original ticket.
**AFTER**
The test sample is attached to the bug's ticket.
> Expander + CollectionView issues

- Xamarin.Forms.Core.UITests.Shared/Tests/CarouselViewUITests.cs
Fix some flacky tests.
- fixes #
None
- iOS
- Android
None
Not applicable
UITests should be green
> [UITests] Better handling of scroll tests

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8291.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs
A bug in the editor control on the google side causes selection to not work when editor is part of a scrollview
https://issuetracker.google.com/issues/37095917
- fixes #8291
- Android
- CG test included
> Add hack to get around google selection bug

- Xamarin.Forms.Platform.Tizen/Shell/Watch/ShellRenderer.cs
This PR update ShellRenderer to make more extendable on sub class. 
None
on ShellRenderer
Added:
``` c#
// allow to override, creating a custom NavigationView
protected virtual NavigationView CreateNavigationView(EvasObject parent);
// allow to override, creating a custom NavigationDrawer
protected virtual NavigationDrawer CreateNavigationDrawer(EvasObject parent);
```
- Tizen
None
Not applicable
> [Tizen] Update ShellRenderer for extend

- Xamarin.Forms.Xaml/XamlNode.cs
- fixes #9902 
**none**
None
Not applicable
> Fixed Issue #9902 : Xaml[C] Xaml parsing optimizzation

- Xamarin.Forms.Core/PlatformConfiguration/TizenSpecific/StyleValues.cs
- Xamarin.Forms.Core/PlatformConfiguration/TizenSpecific/Switch.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/CarouselView.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/CollectionView.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/IndicatorView.cs
- Xamarin.Forms.Platform.Tizen/Native/DateTimePicker.cs
- Xamarin.Forms.Platform.Tizen/Native/DateTimePickerDialog.cs
- Xamarin.Forms.Platform.Tizen/Native/IDateTimeDialog.cs
- Xamarin.Forms.Platform.Tizen/Native/Watch/WatchDateTimePicker.cs
- Xamarin.Forms.Platform.Tizen/Native/Watch/WatchDateTimePickerDialog.cs
- Xamarin.Forms.Platform.Tizen/Native/Watch/WatchListView.cs
- Xamarin.Forms.Platform.Tizen/Native/Watch/WatchScroller.cs
- Xamarin.Forms.Platform.Tizen/Native/Watch/WatchSpinner.cs
- Xamarin.Forms.Platform.Tizen/Renderers/DatePickerRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/StepperRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/SwitchRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/TimePickerRenderer.cs
- Xamarin.Forms.Platform.Tizen/Shell/Watch/NavigationView.cs
- Xamarin.Forms.Platform.Tizen/Shell/Watch/ShellSectionNavigationRenderer.cs
This PR is to update native controls and add options to provide tizen specific feature for watch, and it allows app developers to use watch specific feature through customizing renderers or extending these tizen native controls.
Including restructuring native controls, this PR includes following changes: 
- Optimize DatePicker and TimePicker for watch
- Separate DateTimePicker and WatchDateTimePicker
- Change parent class of WatchDateTimePicker from DateTimePicker to CircleDateTimeSelector
- Modify IDateTimeDialog interface to hide Picker control in DateTimePickerDialog
- Fix class name: WatchDataTimePicker -> WatchDateTimePicker
- Add SwitchStyles in TizenSpecific
- Fix some bugs related to IndicatorView
- Improve extensibility of native control for customizing 
- WatchListView
- …
> [Tizen] Optimize and enhance UI controls for watch

- Environment.Build.props
- SampleImports/Directory.Build.props
- SampleImports/Directory.Build.targets
- SampleImports/Netstandard.Build.props
- SampleImports/Netstandard.Build.targets
- SampleImports/Nuget.Build.targets
Cleanup/fix some issues  with uses the SampleProject props/target files in external projects
- make sure builds work
- open up CG on vsmac and vs to verify CG's all still can build easily
> Fix props imports

- Xamarin.Forms.ControlGallery.WPF/MainWindow.xaml.cs
- Xamarin.Forms.Platform.WPF/FormsRadioButton.cs
- Xamarin.Forms.Platform.WPF/Properties/AssemblyInfo.cs
- Xamarin.Forms.Platform.WPF/Renderers/RadioButtonRenderer.cs
Added RadioButton Renderer for WPF
Missing RadioButton control for WPF
- WPF
Control Gallery
> RadionButton control for WPF

- Xamarin.Forms.Platform.UAP/SearchBarRenderer.cs
Added Dispose method with events unsubscription 
Proper disposing of a SearchBar control
- UWP
Controls gallery
> [UWP] Fix SearchBar disposing

- README.md
- Xamarin.Forms.Platform.Android.FormsViewGroup/Xamarin.Forms.Platform.Android.FormsViewGroup.csproj
- build.cake
- build/provisioning/provisioning.csx
- update readme with more current information
- Bumped FormsGroup to v9.0 so we don't have to install API 24
- verify Readme changes
- verify you can run provisioning script
- verify CI builds everything alright
> Update Readme for setting up environment to build from source

- Xamarin.Forms.Platform.Tizen/Native/ITableView.cs
- Xamarin.Forms.Platform.Tizen/Native/Watch/WatchTableView.cs
- Xamarin.Forms.Platform.Tizen/Renderers/TableViewRenderer.cs
This PR fixes TableView selection issue on Tizen Wearable device
- fixes 
A first Item of TableView was not selected on Tizen Wearable devices
None
- Tizen
None
Not applicable
> [Tizen] Fix TableView issue on Wearable device

- Xamarin.Forms.Platform.iOS/CollectionView/GroupableItemsViewController.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
The fixes from #10948 adapted for 4.6.
> Apply iOS 10 9686 fixes from 4.7 to 4.6

- Xamarin.Forms.Platform.Android/CollectionView/GroupableItemsViewAdapter.cs
- Xamarin.Forms.Platform.Android/CollectionView/ItemsViewAdapter.cs
- Xamarin.Forms.Platform.Android/CollectionView/SelectableItemsViewAdapter.cs
- Xamarin.Forms.Platform.Android/CollectionView/StructuredItemsViewAdapter.cs
change internal constructor to protected
- Android
> #9012: [Enhancement] Allow extend GroupableItemsViewAdapter

- .nuspec/Xamarin.Forms.nuspec
- PagesGallery/PagesGallery.UWP/PagesGallery.UWP.csproj
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.Platform.UAP/Shell/ShellStyles.xaml
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
Update to latest release of WinUI
- UWP
- Test SwipeView
- Test RefreshView
- Make sure Shell Loads
> Update to Latest 2.4 WinUI release

- Xamarin.Forms.Platform.UAP/FileImageSourceHandler.cs
Fix NRE using Native Forms with Images in UWP.
- fixes #10926
None
- UWP
None
Not applicable
> [UWP] Fix NRE using Native Forms

- Xamarin.Forms.Platform.Android/AppCompat/PickerRenderer.cs
Fix NRE disposing AppCompat PickerRenderer.
- fixes #10894 
None
- Android
None
Not applicable
> [Android] Fix NRE disposing the AppCompat PickerRenderer

- Xamarin.Forms.Platform.UAP/CompositionHelper.cs
- Xamarin.Forms.Platform.UAP/Extensions/ClipExtensions.cs
- Xamarin.Forms.Platform.UAP/Extensions/CompositionExtensions.cs
- Xamarin.Forms.Platform.UAP/VisualElementTracker.cs
Verify if Composition Geometry IsTypePresent on UWP
None
- UWP
None
Not applicable
Test Shapes on UWP using target 16299.
> Verify if Composition Geometry IsTypePresent on UWP

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11031.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS.UnitTests/BackgroundColorTests.cs
- Xamarin.Forms.Platform.iOS.UnitTests/CornerRadiusTests.cs
- Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs
> Backport #11032 to 4.6.0

- Xamarin.Forms.Core.UITests.Shared/Tests/CollectionViewUITests.cs
UI test is currently private which doesn't allow it to run on vsmac
- iOS
- Android
- UWP
- make sure test runs
> Make TestCase VisitAndCheckForItems public

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11031.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs
> Backport #11032 to 4.6.0 (#11040)

- azure-pipelines.yml
Make sure the pages jobs finish before the nugets jobs start
- verify this PR runs on devdiv and public CI
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3813434&view=results
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3813492&view=results
> Add pages depends on to nuget pack job

- Xamarin.Forms.Platform.Android/ButtonLayoutManager.cs
Add missing null check after merge up.
- fixes UI test crash for RadioButton tests
None
- Android
None
Not applicable
Android UI tests.
> Check renderer and view for null in UpdateTextAndImage

- Xamarin.Forms.Platform.Tizen/Renderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ProgressBarRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/SwitchRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/TabbedPageRenderer.cs
This PR is to ensure the update of color related properties after theme style changing on tizen.
None
None
- Tizen
None
> [Tizen] Ensure the update of color after theme style changing

- Xamarin.Forms.Platform.Tizen/Forms.cs
This PR fixes UseDeviceIndependentPixel options related issue
- UseDeviceIndependentPixel options was not set with `void Init(InitializationOptions options)`
- fixes UseDeviceIndependentPixel options
None
- Tizen
None
Not applicable
> [Tizen] Fix initialize of Device Independent Pixel option

- Xamarin.Forms.Platform.UAP/StepperRenderer.cs
Added Dispose method with events unsubscription 
Proper disposing of Stepper control
- UWP
Controls gallery
> [UWP] Fix Stepper disposing

- Xamarin.Forms.Platform.UAP/ButtonRenderer.cs
Added Dispose method with events unsubscription 
Proper disposing of Button control
- UWP
Controls gallery
> [UWP] Fix Button disposing

- .nuspec/Xamarin.Forms.Pages.Azure.nuspec
- .nuspec/Xamarin.Forms.Pages.nuspec
- .nuspec/Xamarin.Forms.nuspec
- Git.Build.targets
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- PagesGallery/PagesGallery.UWP/PagesGallery.UWP.csproj
- PagesGallery/PagesGallery.iOS/PagesGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.MacOS/Xamarin.Forms.ControlGallery.MacOS.csproj
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
- Xamarin.Forms.Maps.GTK/Xamarin.Forms.Maps.GTK.csproj
- Xamarin.Forms.Maps.UWP/Xamarin.Forms.Maps.UWP.csproj
- Xamarin.Forms.Pages.Azure/Xamarin.Forms.Pages.Azure.csproj
- Xamarin.Forms.Pages.UnitTests/Xamarin.Forms.Pages.UnitTests.csproj
- Xamarin.Forms.Pages/Xamarin.Forms.Pages.csproj
- Xamarin.Forms.Platform.UAP.UnitTests/Xamarin.Forms.Platform.UAP.UnitTests.csproj
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Update packages for security reasons
None
None
- iOS
- Android
- UWP
None
Not applicable
> [Nuget] Components governance

- Directory.Build.props
> [Build] Update Directory.Build.props

- Xamarin.Forms.ControlGallery.WindowsUniversal/_2489CustomRenderer.cs
- Xamarin.Forms.Platform.UAP/PageRenderer.cs
With this change we call `VisualElementRenderer.Dispose(true)` disposing Pages.
- fixes #10423 
None
- UWP
None
Not applicable
> [UWP] Fixed issue disposing Pages

- .gitignore
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- build.cake
- build/steps/build-osx.yml
Add a set of cake tasks that allow ios tests to run via cake.
```sh
var IOS_SIM_NAME = Argument("IOS_SIM_NAME", "iPhone 8");
var IOS_SIM_RUNTIME = Argument("IOS_SIM_RUNTIME", "com.apple.CoreSimulator.SimRuntime.iOS-13-5");
var IOS_TEST_PROJ = "./Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj";
var IOS_TEST_LIBRARY = Argument("IOS_TEST_LIBRARY", $"./Xamarin.Forms.Core.iOS.UITests/bin/{configuration}/Xamarin.Forms.Core.iOS.UITests.dll");
var IOS_IPA_PATH = Argument("IOS_IPA_PATH", $"./Xamarin.Forms.ControlGallery.iOS/bin/iPhoneSimulator/{configuration}/XamarinFormsControlGalleryiOS.app");
var IOS_BUNDLE_ID = "com.xamarin.quickui.controlgallery";
var IOS_BUILD_IPA = Argument("IOS_BUILD_IPA", (target == "cg-ios-deploy") ? true : (false || isCIBuild) );
var …
```
> Run iOS tests from the command line via cake

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
Fix incorrect property on iOS CG
- make sure tests still run from CLI correctly
- make sure project runs from vsmac correctly
> Fix iOSPlatform property

- azure-pipelines.yml
Update nuget  client to use and dotnet so we use a more secure version
- None
- None
- None
Not applicable
> [Build] Update nuget and dotnet version

- Xamarin.Forms.ControlGallery.WindowsUniversal/App.xaml.cs
- Xamarin.Forms.ControlGallery.WindowsUniversal/MainPage.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue10744.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9827.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/ScreenshotConditionalApp.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
- Xamarin.Forms.Controls/TestCases.cs
- Xamarin.Forms.Core.Windows.UITests/WinDriverApp.cs
- Xamarin.Forms.Platform.UAP/SearchBarRenderer.cs
- azure-pipelines.yml
- build.cake
- build/steps/run-windows-tests.yml
Fix up cake tasks so that the UWP tests can run on a VM
- UWP
- make sure uwp tests can run
> Uwp ui tests tweaks

- Xamarin.Forms.Core.UnitTests/SwipeViewTests.cs
- Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
Verifying an issue (#11349) I have realized that we have SwipeView UITests but not a simple unit test validating the constructor.
None
None
Not applicable
Verify that the SwipeView unit tests pass.
> [Core] Added SwipeView unit tests

- Xamarin.Forms.Platform.Tizen/Native/CollectionView/CarouselView.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/CollectionView.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/GridLayoutManager.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/ICollectionViewLayoutManager.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/LinearLayoutManager.cs
- Xamarin.Forms.Platform.Tizen/Renderers/CarouselViewRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ItemsViewRenderer.cs
* Enhancement CollectionView on Tizen platform
- Implement ScrollBarVisibility
- Implement LinearItemsLayout.ItemSpacing
- Implement GridItemsLayout.VerticalItemSpacing/HorizontalItemSpacing
- Fix SnapPointsType issue
- fixes : N/A
None
- Tizen
None
Not applicable
> [Tizen] Enhancement CollectionView

- Xamarin.Forms.Platform.Android.UnitTests/PlatformTestFixture.cs
- Xamarin.Forms.Platform.Android.UnitTests/ShellTests.cs
- Xamarin.Forms.Platform.Android.UnitTests/TestActivity.cs
- Xamarin.Forms.Platform.Android.UnitTests/Xamarin.Forms.Platform.Android.UnitTests.csproj
This adds the ability to create a new activity and host content there for cases where the renderer needs an activity to be hosted inside
- the tests don't schmear
> Add shell renderer to page instead of window

- Xamarin.Forms.Core/Device.cs
Fix invalid message.
Fixes #11433
None
All
None
Not applicable
> Fix OpenUri obsoletion message

- Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs
- Xamarin.Forms.Platform.UAP/Shell/ShellItemRenderer.cs
- Xamarin.Forms.Platform.UAP/Shell/ShellRenderer.cs
- Xamarin.Forms.Platform.UAP/Shell/ShellSectionRenderer.cs
- Xamarin.Forms.Platform.UAP/Shell/ShellStyles.xaml
Build the basics for push/pop/etc.. with Shell
- fixes #8498
- UWP
- click around on store shell
> Light up UWP Shell Navigation

- Xamarin.Forms.Core/Device.cs
Exception message mentions API that doesn't exist so I changed it to the correct API.
Fixes #11527
None
Core
None
Not applicable
> Fix Device error message reference to Xamarin.Forms.Init

- .nuspec/Xamarin.Forms.Pages.Azure.nuspec
- .nuspec/Xamarin.Forms.Pages.nuspec
- .nuspec/Xamarin.Forms.nuspec
- Git.Build.targets
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- PagesGallery/PagesGallery.UWP/PagesGallery.UWP.csproj
- PagesGallery/PagesGallery.iOS/PagesGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.MacOS/Xamarin.Forms.ControlGallery.MacOS.csproj
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
- Xamarin.Forms.Maps.GTK/Xamarin.Forms.Maps.GTK.csproj
- Xamarin.Forms.Maps.UWP/Xamarin.Forms.Maps.UWP.csproj
- Xamarin.Forms.Pages.Azure/Xamarin.Forms.Pages.Azure.csproj
- Xamarin.Forms.Pages.UnitTests/Xamarin.Forms.Pages.UnitTests.csproj
- Xamarin.Forms.Pages/Xamarin.Forms.Pages.csproj
- Xamarin.Forms.Platform.UAP.UnitTests/Xamarin.Forms.Platform.UAP.UnitTests.csproj
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- azure-pipelines.yml
- build/steps/build-nuget.yml
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> Add secure checks

- Xamarin.Forms.ControlGallery.Android/RippleEffect.cs
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11374.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11374.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs
Fix issue using SwipeView in ListView using a RippleEffect on Android.
- fixes #11374 
None
- Android
None
Not applicable
Launch Core Gallery and navigate to the issue 11374. Swipe an Item to the right or left. If you can open the SwipeView, the test has passed.
> [Android] Fix issue using SwipeView in ListView using a RippleEffect 

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh11620.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh11620.xaml.cs
Do not return false on CanAdd if all that's required is boxing.
- fixes #11620
None
None
Not applicable
automated tests
> [X] Box On Add

- Xamarin.Forms.Core.UnitTests/DragGestureRecognizerTests.cs
- Xamarin.Forms.Core.UnitTests/DropGestureRecognizerTests.cs
- Xamarin.Forms.Core/DragAndDrop/DragGestureRecognizer.cs
- Xamarin.Forms.Core/DragAndDrop/DropEventArgs.cs
- Xamarin.Forms.Core/DragAndDrop/DropGestureRecognizer.cs
- Xamarin.Forms.Core/ViewExtensions.cs
- Xamarin.Forms.Platform.Android/DragAndDropGestureHandler.cs
- Xamarin.Forms.Platform.UAP/VisualElementTracker.cs
- Xamarin.Forms.Platform.iOS/DragAndDropDelegate.cs
- generalize extracting text data into xplat code
- add switch and radiobutton for drag/drop source/target
- add more unit tests
- change Handled setter to a public property
- iOS
- Android
- UWP
- ui tests pass
- test gallery pages make you happy
> Drag and drop tweaks

- Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs
WebViews now support multiple windows on Android!
n/a
None
- Android
None
Not applicable
> [Android] Enable SetSupportMultipleWindows on WebView

- Xamarin.Forms.Platform.Tizen/Extensions/EvasMapExtensions.cs
- Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs
* Update implementation of rotation to apply perspective
- fixes #
None
- Tizen
|before|after|
|-|-|
|![c5729700-dbe0-11ea-9b9d-3753e29758a2](https://user-images.githubusercontent.com/1029155/90459063-18959e00-e13b-11ea-9739-177a30c835f2.gif)|![rotation2](https://user-images.githubusercontent.com/1029155/90459107-3a8f2080-e13b-11ea-9187-3a448bb95ffb.gif)|
> [Tizen] Implement perspective rotation

- .github/workflows/dotnet-format-daily.yml
Add auto format action.
- None
None
- iOS
- Android
- UWP
None
Not applicable
> [Build] Add auto-format daily action

- Xamarin.Forms.Platform.Tizen/Renderers/CarouselPageRenderer.cs
This patch for using an indicator to `CarouselPage`.
It provides views such as a combination of `CarouselView` and `IndicatorView`.
- fixes #
None
- Tizen
None
> [Tizen] Add indicator to CarouselPage

- Xamarin.Forms.Core/Items/CarouselView.cs
Fix the default value of `CarouselView`.VisibleViews property
- fixes #11826
None
None
Not applicable
> Fix CarouselView.VisibleViews default value

- azure-pipelines.yml
- build/steps/build-sign.yml
Small update to sigining template
None
- None
None
Not applicable
> [Build] Update sigining

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11653.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11653.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UnitTests/PathSegmentTests.cs
- Xamarin.Forms.Platform.Android/Extensions/GeometryExtensions.cs
- Xamarin.Forms.Platform.iOS/Extensions/GeometryExtensions.cs
- Xamarin.Forms.Platform.iOS/Shapes/ShapeRenderer.cs
Added more Shapes Segments unit tests cases.
- fixes #11653 
None
- Android
- iOS
None
Not applicable
Navigate to the issue 11653. Without exceptions, the test has passed.
_NOTE: Nothing will render._
> [Core] Validate Segment points

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11333.xaml.cs
Changed UITest to run only on Android.
None
None
Not applicable
The 5.0.0 branch build must pass.
> [Housekeeping] Changed UITest to run only on Android

- Xamarin.Forms.Core/ViewExtensions.cs
All the other extension methods are extension methods... except the cancel.
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> Make CancelAnimations an extension method

- Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
Removing check that was re-added from merge to 4.8.0
- iOS
- make sure UI Tests Pass
> [iOS] Remove Appeared Check on Page Renderer

- .nuspec/Xamarin.Forms.nuspec
- DualScreen/DualScreen.UWP/DualScreen.UWP.csproj
- EmbeddingTestBeds/Embedding.UWP/Embedding.UWP.csproj
- UWP.Build.props
- UWP.Build.targets
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.DualScreen/DualScreenService.uwp.cs
- Xamarin.Forms.DualScreen/Xamarin.Forms.DualScreen.csproj
- Xamarin.Forms.Platform.UAP.UnitTests/Xamarin.Forms.Platform.UAP.UnitTests.csproj
- Xamarin.Forms.Platform.UAP/Forms.cs
- Xamarin.Forms.Platform.UAP/Platform.cs
- Xamarin.Forms.Platform.UAP/WindowsIsolatedStorage.cs
- build.cake
Bump UWP to compile against 19041 SDK and set target framework to 19041
- UWP
- uitests run
> Bump UWP to 19041

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11573.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11573.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11737.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11737.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11764.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11764.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
Added missing files (looks like a merge error).
None
None
Not applicable
> [Housekeeping] Fix build error

- Xamarin.Forms.Platform.Tizen/Forms.cs
- Xamarin.Forms.Platform.Tizen/ThemeConstants.cs
- Xamarin.Forms.Platform.Tizen/ThemeManager.cs
* Font size was not aligned to pixel size on some profiles, This PR resolve this issue
* On Tizen device, Font size scaled to internal scale factor and device scale factor and it cause difference with real pixel size
- None
None
- Tizen
Font size was little bit changed
|-|-|
|<img src=https://user-images.githubusercontent.com/1029155/91797376-5deabd00-ec5d-11ea-932e-e0ff94668e9c.png width=300>|<img src=https://user-images.githubusercontent.com/1029155/91797368-575c4580-ec5d-11ea-9170-6dc036006971.png width=300>|
|-|-|
|![before-watch](https://user-images.githubusercontent.com/1029155/91797394-67742500-ec5d-11ea-87fc-60ee066243eb.png)|![after-watch](https://user-images.githubusercontent.com/1029155/91797398-693de880-ec5d-11ea-8193-c08f36faf54d.png)|
| …
> [Tizen] Update profile unified font size scaling

- azure-pipelines.yml
- build/steps/build-sign.yml
Update signing based on #12014 
None
- iOS
- Android
- UWP
None
Not applicable
> [Nuget]  Use main branch of yaml-templates, ensure nugets are properly signed 

- Xamarin.Forms.Core/Shell/SearchHandler.cs
IsFocusedProperty is a readonly property, So to update it, we should use a IsFocusedPropertyKey instead IsFocusedProperty.
- fixes #11894
None
None
Not applicable
> [Core/Shell] Fix SearchHandler.SetIsFocused

- Xamarin.Forms.ControlGallery.WPF/Xamarin.Forms.ControlGallery.WPF.csproj
- Xamarin.Forms.Platform.WPF/Properties/AssemblyInfo.cs
Fix assembly version for WPF, thanks @krdmllr  for figuring it out. 
fixes #11328
fixes #10489
None
- WPF
None
Not applicable
Should be able to run the WPF Control Gallery
> [WPF] Fix Assembly version 

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla32898.cs
Increase timeout on uitest for 32898 to see if it works.
None
None
- Android
None
Not applicable
> [UITests] Try fix uitest 32898

- Xamarin.Forms.Core/WeakEventManager.cs
`WeakEventManager` class made public. 
- fixes #8405, https://github.com/xamarin/XamarinCommunityToolkit/issues/272
Changed:
- internal WeakEventManager => public WeakEventManager
None
Not applicable
> public WeakEventManager

- Xamarin.Forms.Build.Tasks/BindablePropertyReferenceExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh12025.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh12025.xaml.cs
[X] Find most derived ABP
- fixes #12025
None
None
Not applicable
> [X] Find most derived ABP

- Xamarin.Forms.Platform.Tizen/DisplayResolutionUnit.cs
- Xamarin.Forms.Platform.Tizen/Forms.cs
* To support multiple device screen size and density, we introduce `DisplayResolutionUnit`. It's including two features 
First is `DeviceScale` If device has more than some physical size, UI is scaled up.
Second is Viewport, Now app developer can set app's virtual screen size to want, UI is scaled to virtual screen size
* DeviceScale 
* Viewport
* How to use
It is integrated with Forms.Init method and InitializationOptions
``` c#
// Use Pixel unit
Forms.Init(app, DisplayResolutionUnit.Pixel());
Forms.Init(new InitializationOptions(app)
{
DisplayResolutionUnit = DisplayResolutionUnit.Pixel(),
}
// apply device scale with pixel unit
Forms.Init(app, DisplayResolutionUnit.Pixel(true));
Forms.Init(new InitializationOptions(app)
{
DisplayResolutionUnit = DisplayResolutionUnit.Pixel(true),
}
``` …
> [Tizen] Adds the DisplayResolutionUnit

- Xamarin.Forms.Platform.Tizen/Forms.cs
This PR fix missing of assembly registration on some initialization options
- fixes #
None
- Tizen
None
Not applicable
> [Tizen] Fix Assembly registration issue

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
[hk] fix dependentupon in shared project
> [hk] fix dependentupon in shared project

- ControlGallery.Build.props
- Environment.Build.props
- Stubs/Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS (Forwarders).csproj
- Xamarin.Forms.Maps.GTK/Xamarin.Forms.Maps.GTK.csproj
- Xamarin.Forms.Maps.MacOS/Xamarin.Forms.Maps.macOS.csproj
- Xamarin.Forms.Maps.iOS/Xamarin.Forms.Maps.iOS.csproj
- Xamarin.Forms.Material.iOS/Xamarin.Forms.Material.iOS.csproj
- Xamarin.Forms.Platform.GTK/Xamarin.Forms.Platform.GTK.csproj
- Xamarin.Forms.Platform.MacOS/Xamarin.Forms.Platform.macOS.csproj
- Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
Now that we've removed VS 2017 support we can update to using C# 8.0 
- make sure tests all pass
> Update to C# 8.0

- Xamarin.Forms.Platform.Android/CollectionView/CarouselViewAdapter.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/Button/ButtonHandler.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/IViewHandler.Android.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/IViewHandler.Mac.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/IViewHandler.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/IViewHandler.iOS.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/View/AbstractViewHandler.Android.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/View/AbstractViewHandler.MaciOS.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/View/AbstractViewHandler.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/View/ViewHandler.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Platform/Android/ButtonExtensions.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Platform/Android/ContextExtensions.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Platform/Android/HandlerExtensions.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Platform/Android/ViewExtensions.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Platform/Standard/ViewExtensions.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Platform/iOS/HandlerExtensions.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Platform/iOS/LayoutView.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Platform/iOS/ViewExtensions.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Primitives/Keyboard.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Properties/AssemblyInfo.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/PropertyMapper.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Registrar.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Xamarin.Platform.Handlers.csproj
- src/Platform.Handlers/tests/Xamarin.Platform.Handlers.Tests/PropertyMapperTests.cs
Implement Nullable Reference Types on Handler projects.
More information: https://github.com/dotnet/maui/issues/232
> Implement Nullable Reference Types on Handler projects

- Xamarin.Forms.Platform.WPF/Themes/FormsFlyoutPage.xaml
- Xamarin.Forms.Platform.WPF/Themes/Generic.xaml
Fixes issue with styles when renaming MasterDetailPage to FlyoutPage
- fixes #12235
None
- WPF
WPF apps should work
Not applicable
ControlGallery should work on WPF
> [WPF] Fix styles for FormsFlyoutPage

- Xamarin.Forms.sln
- src/Platform.Handlers/samples/Sample.iOS/AppDelegate.cs
- src/Platform.Handlers/samples/Sample.iOS/Sample.iOS.csproj
Enable Hot restart on Sample.iOS
none
None
- iOS
None
Not applicable
HotRestart should work
> [Build] Enable hot restart on Handlers

- .github/workflows/dotnet-format-daily.yml
Since we moved the base branch we need to add this to 5.0.0
None
None
None
Not applicable
> [Build] Add code format workflow

- Xamarin.Forms.Platform.Tizen/Renderers/CarouselPageRenderer.cs
There was a problem with `CarouselPage` rendering, fixed the layout of the renderer.
fixes #12451 
None
- Tizen
> [Tizen] Fix CarouselPage rendering  issue

- Xamarin.Forms.Platform.Tizen/Renderers/DatePickerRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ImageButtonRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/PickerRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/SearchBarRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/TimePickerRenderer.cs
* Some views does not delivered focused event when view was focused, this PR fixed it
- fixes N/A
None
- Tizen
None
| Before | After|
|-|-|
|![focus-event-test](https://user-images.githubusercontent.com/1029155/95694364-b48be380-0c6c-11eb-9054-6fad1ee17ec6.gif)|![focus-event-test-fixed](https://user-images.githubusercontent.com/1029155/95694369-bc4b8800-0c6c-11eb-9a30-3b82ab9c2576.gif)|
|![focus-event-test-mobile](https://user-images.githubusercontent.com/1029155/95694380-c3729600-0c6c-11eb-813e-d0571eae6b67.gif)|![focus-event-test-mobile-fixed](https://user-images.githubusercontent.com/1029155/95694386-ca010d80-0c6c-11eb-8ad3-e44713a08a3c.gif)|
> [Tizen] Fix focused event missing issue

- Xamarin.Forms.Platform.Tizen/Renderers/StepperRenderer.cs
This PR is to fix Stepper value issue.
https://developer.tizen.org/ko/forums/tizen-.net/stepper-control-broken?langredirect=1
None
- Tizen
- Watch
|--|--|
| <img width="300" src="https://user-images.githubusercontent.com/20968023/96957021-88a61300-1534-11eb-892a-a335b5676b55.gif" /> | <img width="300" src="https://user-images.githubusercontent.com/20968023/96957027-8b086d00-1534-11eb-903b-45ba3a9b15b1.gif" /> |
- Mobile
|--|--|
| <img width="300" src="https://user-images.githubusercontent.com/20968023/96957014-8479f580-1534-11eb-9f44-26f2731c34ee.gif" /> | <img width="300" src="https://user-images.githubusercontent.com/20968023/96957015-85ab2280-1534-11eb-9ba0-8e0e520d836c.gif" /> |
> [Tizen] Fix stepper value issue

- Xamarin.Forms.Platform.iOS/ContextActionCell.cs
Fixed NRE and crash #12585 
- fixes #12585
None
- iOS
None
Not applicable
- Did not test, the change is very small
> [iOS] Fixed NRE in ContextActionsCell #12585

- Xamarin.Forms.Core/Internals/NameScope.cs
> [C] get the name of a scoped object

- Environment.Build.props
- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs
- Xamarin.Forms.ControlGallery.Android/Issue10182Activity.cs
- Xamarin.Forms.ControlGallery.Android/MultiWindowService.cs
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.Android/_50787CustomRenderer.cs
- build/steps/build-android.yml
Cleanup old references to PRE_APPLICATION_ACTIVITY 
- Fixes main build
None
- Android
None
Not applicable
Main should build, tests should run
> [Build] Fix main and remove all pre app compat references

- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
> [X] avoid crashing on null lineinfo

- Xamarin.Forms.Core/BindableObject.cs
- fixes #12525
None
- iOS
- Android
- UWP
None
Not applicable
> [C] BO.GetLocalValueEnumerator()

- Xamarin.Forms.Platform.Tizen/Shell/NavigationDrawer.cs
- Xamarin.Forms.Platform.Tizen/Shell/ShellNavBar.cs
- Xamarin.Forms.Platform.Tizen/ThemeConstants.cs
- Xamarin.Forms.Platform.Tizen/ThemeManager.cs
This PR is to optimize Shell Flyout for TV including follow changes:
- Resolve an focus issue on TV
- Resize Flyout's width on TV
- Change menu button icon
None
None
- Tizen
- Control Shell Flyout with TV remote controller
- Shell Flyout Icon changes
> [Tizen] Optimize Shell Flyout for TV 

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Helpers/UITestHelper.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/ScreenshotConditionalApp.cs
- Xamarin.Forms.Core.UITests.Shared/BaseTestFixture.cs
Test for Network Connectivity needs to also apply to the Gallery tests
- UI Tests all pass (or are ignored)
> Apply internet check to additional tests

- Xamarin.Forms.Xaml.UnitTests/Issues/Gh12763.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh12763.xaml.cs
- Xamarin.Forms.Xaml/MarkupExpressionParser.cs
Quotes are already parsed, and handled elsewhere
- fixes #12763
None
People working around this issue with double quoting will be effected by this change
Not applicable
> [X] Don't remove enclosing quotes

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/DateTimePickerLocalizationTests.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4597.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/ScreenshotConditionalApp.cs
- Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs
- Xamarin.Forms.Core.Windows.UITests/WinDriverApp.cs
The Date/TimePickers on UWP are fairly different than the ones on Android/iOS so the App Driver and the expected results needed to be updated to match the expectations when running on UWP
- UWP
- UWP tests all pass
> Build UWP version of locale tests

- .github/ISSUE_TEMPLATE/bug_report.md
Updated the bug report new issue template asking for additional details:
- Added request for build logs (binlog preferred) if issue is related to a build error, including instructions on how to obtain
- Added request for more environment details, including instructions on how to obtain
> Updated bug report issue template with more detail

- EmbeddingTestBeds/Embedding.Droid/Directory.Build.targets
- Xamarin.Forms.ControlGallery.Android/Directory.Build.targets
- Xamarin.Forms.ControlGallery.Android/Nuget.Build.targets
- Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
Remove references to Xamarin.AndroidX.Migration , seems package is not correctly signed.
- unblocks template insertion 
None
- Android
None
Not applicable
> [Android] Remove AndroidX Migration packages

- Xamarin.Forms.Platform.Tizen/SkiaSharp/CanvasViewRenderer.cs
- Xamarin.Forms.Platform.Tizen/SkiaSharp/FrameRenderer.cs
- Xamarin.Forms.Platform.Tizen/SkiaSharp/IClipperCanvas.cs
- Xamarin.Forms.Platform.Tizen/SkiaSharp/SKCliperView.cs
- Xamarin.Forms.Platform.Tizen/SkiaSharp/SKClipperView.cs
* This PR solved the cliping issue of Frame when Frame was scrolled
- fixes #
None
- Tizen
None
|Before | After|
|-|-|
|![frame-cliper-before](https://user-images.githubusercontent.com/1029155/99767824-0b77b900-2b47-11eb-8899-472185d7ab0c.gif)|![frame-cliper-after](https://user-images.githubusercontent.com/1029155/99767827-0fa3d680-2b47-11eb-8617-381ab6840a56.gif)
> [Tizen] Fix Frame cliping issue

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11563.cs
- Xamarin.Forms.Platform.Android/Shapes/PolygonRenderer.cs
- Xamarin.Forms.Platform.Android/Shapes/PolylineRenderer.cs
- Xamarin.Forms.Platform.UAP/Shapes/PolygonRenderer.cs
- Xamarin.Forms.Platform.UAP/Shapes/PolylineRenderer.cs
- Xamarin.Forms.Platform.iOS/Shapes/PolygonRenderer.cs
- Xamarin.Forms.Platform.iOS/Shapes/PolylineRenderer.cs
Detect PointCollection changes in Polyline (based on #11576).
- fixes #11848
None
None
Not applicable
> [Core] Detect PointCollection changes in Polyline

- Xamarin.Forms.Platform.Tizen/Native/CollectionView/CarouselView.cs
- Xamarin.Forms.Platform.Tizen/Renderers/CarouselViewRenderer.cs
Change CarouselView position update time to apply initial value.
Fix internal value for CarouselView page scroll size
- fixes #
None
- Tizen
None
Not applicable
> [Tizen] Fix CarouselView issue

- Xamarin.Forms.Platform.Tizen/SkiaSharp/SKClipperView.cs
Frame was nested, crash was occurred on tizen platform, this PR resolve it
- fixes #
None
- Tizen
None
Not applicable
> [Tizen] Fix Frame nested issue

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11969.xaml.cs
Fix 5.0.0 branch failing UITest
None
None
Not applicable
The build passes.
> [Housekeeping] Fix 5.0.0 branch failing UITest

- Xamarin.Forms.Platform.Tizen/Renderers/ScrollViewRenderer.cs
This is hotfix for ScrollViewRenderer. Fix exceptions caused by casting errors during initialization.
None
None
- Tizen
None
> [Tizen] Fix ScrollView renderer invalid cast issue

- src/Forms/src/Xamarin.Forms.Core/View.cs
- src/Platform.Handlers/samples/Sample/Controls/FrameworkElement.cs
- src/Platform.Handlers/samples/Sample/Controls/HorizontalStackLayout.cs
- src/Platform.Handlers/samples/Sample/Controls/Layout.cs
- src/Platform.Handlers/samples/Sample/Controls/StackLayout.cs
- src/Platform.Handlers/samples/Sample/Controls/VerticalStackLayout.cs
- src/Platform.Handlers/samples/Sample/Controls/View.cs
- src/Platform.Handlers/samples/Sample/MyApp.cs
- src/Platform.Handlers/samples/Sample/Platform.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Core/IFrameworkElement.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Layouts/HorizontalStackLayoutManager.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Layouts/LayoutExtensions.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Layouts/VerticalStackLayoutManager.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Primitives/Thickness.cs
- src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/Layouts/ConstraintTests.cs
- src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/Layouts/HorizontalStackLayoutManagerTests.cs
- src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/Layouts/LayoutExtensionTests.cs
- src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/Layouts/StackLayoutManagerTests.cs
- src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/Layouts/VerticalStackLayoutManagerTests.cs
- src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/TestCategory.cs
- src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/Xamarin.Platform.Handlers.UnitTests.csproj
Adds Margin to IFrameworkElement and updates layout code to account for margins.
Also adds unit tests for layout code.
> Add margins to layouts

- Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
Fix failing tests on main
- None
None
- iOS
- Android
- UWP
None
Not applicable
> [UITests] Fix failing UITests

- .github/workflows/rebase-trigger.yml
Add Rebase Trigger action to our repository
> Add Rebase Trigger Workflow

- .github/workflows/backport-trigger.yml
Add back port bot so we can easily backport PRs through github
> Backport Bot

- src/Forms/src/Xamarin.Forms.Core/Layout.cs
- src/Forms/src/Xamarin.Forms.Core/View.cs
- src/Platform.Handlers/samples/Sample.Droid/MainActivity.cs
- src/Platform.Handlers/samples/Sample.Droid/Resources/layout/content_main.xml
- src/Platform.Handlers/samples/Sample.iOS/AppDelegate.cs
- src/Platform.Handlers/samples/Sample/Controls/FrameworkElement.cs
- src/Platform.Handlers/samples/Sample/Controls/Layout.cs
- src/Platform.Handlers/samples/Sample/Controls/View.cs
- src/Platform.Handlers/samples/Sample/MyApp.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Core/IFrameworkElement.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Core/ILayout.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Core/IView.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/Layout/ILayoutHandler.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/Layout/LayoutHandler.Android.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/Layout/LayoutHandler.Standard.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/Layout/LayoutHandler.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/Layout/LayoutHandler.iOS.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/View/ViewHandler.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Platform/Android/LayoutViewGroup.Android.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Platform/Android/ViewExtensions.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Platform/Standard/ViewExtensions.cs
Implement adding/removing IViews to ILayouts.
None
Added Xamarin.Platform.ILayoutHandler
void Add(IView child)
void Remove(IView child)
- iOS
- Android
Adding and removing IViews from ILayouts now updates them.
Not applicable
Run the Droid and iOS Sample apps; 5 seconds after loading, the controls on the screen will change.
> Implement Layout add/remove

- src/Platform.Handlers/tests/Xamarin.Platform.Handlers.DeviceTests/Handlers/HandlerTestBase.cs
- src/Platform.Handlers/tests/Xamarin.Platform.Handlers.DeviceTests/Handlers/Layout/LayoutHandlerTests.Android.cs
- src/Platform.Handlers/tests/Xamarin.Platform.Handlers.DeviceTests/Handlers/Layout/LayoutHandlerTests.cs
- src/Platform.Handlers/tests/Xamarin.Platform.Handlers.DeviceTests/Handlers/Layout/LayoutHandlerTests.iOS.cs
- src/Platform.Handlers/tests/Xamarin.Platform.Handlers.DeviceTests/Stubs/Layout.cs
- src/Platform.Handlers/tests/Xamarin.Platform.Handlers.DeviceTests/TestBase.cs
Add some basic tests for the layout handlers (add, remove, verify that views in the layout at handler creation are present in the native control).
> Basic tests for layout handlers

- build.cake
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> Add API levels 26 (8.0) and 27 (8.1)

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13616.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue13616.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs
Fix exception adding items to CarouselView on Android.
- fixes #13616 
None
- Android
None
Launch Core Gallery and navigate to the issue 13616. Tap the Button to add a new Item, without exceptions, the test has passed.
> [Android ] Fix exception adding items to CarouselView

- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
- Xamarin.Forms.DualScreen.UnitTests/Xamarin.Forms.DualScreen.UnitTests.csproj
- Xamarin.Forms.Platform.Android.UnitTests/Xamarin.Forms.Platform.Android.UnitTests.csproj
- Xamarin.Forms.Platform.UAP.UnitTests/Xamarin.Forms.Platform.UAP.UnitTests.csproj
- Xamarin.Forms.Platform.iOS.UnitTests/Xamarin.Forms.Platform.iOS.UnitTests.csproj
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Update to the latest version of NUnit3
I've been hitting occasional errors compiling locally which seem to be resolved by updating to the latest version of Nunit
- tests run
- I didn't miss any places to update
> Update to latest Nunit3

- build/steps/build-android.yml
- build/steps/build-osx.yml
- build/steps/build-windows.yml
Fix merge of cake changes 
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> Fix build cake on 5.0

- build.cake
- build/steps/build-android.yml
Install .net first 
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> Fix cake 4 8 0

- DevopsNuget.config
- NuGet.config
Fix nuget.config
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> [Build] Fix nuget.config

- eng/devices/android.cake
- eng/devices/ios.cake
Improve Android:
* Add a longer boot timeout for CI (it takes about 5 mins to boot)
* Fail the command if the tests failed
* Pass the arch correctly to the driver
* Add support for selecting the emulator "skin" or "type"
Improve iOS:
* Copy the test result files to <out-dir>/TestResults.xml
I switched to TABS to match the rest of the repo, so this may help: https://github.com/xamarin/Xamarin.Forms/pull/13761/files?w=1
None.
None
None
None
Not applicable
> xharness improvements

- src/Forms/src/Xamarin.Forms.Core/HandlerImpl/Button.Impl.cs
- src/Platform.Handlers/samples/Sample/Controls/Button.cs
- src/Platform.Handlers/samples/Sample/Controls/Label.cs
- src/Platform.Handlers/samples/Sample/MyApp.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Core/IText.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/Button/ButtonHandler.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Handlers/Label/LabelHandler.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Platform/Android/ButtonExtensions.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Platform/Standard/ButtonExtensions.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Platform/iOS/ButtonExtensions.cs
- src/Platform.Handlers/tests/Xamarin.Platform.Handlers.UnitTests/PropertyMapperTests.cs
Rename the property for future PRs to avoid mixing all the changes in together.
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> Rename IText.Color to TextColor

- src/ControlGallery/src/Xamarin.Forms.ControlGallery.Android/Resources/layout/Tabbar.axml
- src/ControlGallery/src/Xamarin.Forms.ControlGallery.Android/Resources/layout/Toolbar.axml
- src/ControlGallery/src/Xamarin.Forms.Controls/CoreGallery.cs
- src/ControlGallery/src/Xamarin.Forms.Controls/GalleryPages/LayoutGalleries/HorizontalStackLayoutGallery.cs
- src/ControlGallery/src/Xamarin.Forms.Controls/GalleryPages/LayoutGalleries/LayoutGallery.cs
- src/ControlGallery/src/Xamarin.Forms.Controls/GalleryPages/LayoutGalleries/VerticalStackLayoutGallery.cs
- src/Forms/src/Xamarin.Forms.Core/FormsHandlers.cs
- src/Forms/src/Xamarin.Forms.Core/Layout/HorizontalStackLayout.cs
- src/Forms/src/Xamarin.Forms.Core/Layout/Layout.cs
- src/Forms/src/Xamarin.Forms.Core/Layout/StackLayout.cs
- src/Forms/src/Xamarin.Forms.Core/Layout/VerticalStackLayout.cs
- src/Forms/src/Xamarin.Forms.Core/RadioButton.cs
- src/Forms/src/Xamarin.Forms.Core/View.cs
- src/Platform.Handlers/samples/Sample.iOS/AppDelegate.cs
- src/Platform.Handlers/samples/Sample/Controls/HorizontalStackLayout.cs
- src/Platform.Handlers/samples/Sample/Controls/VerticalStackLayout.cs
- src/Platform.Handlers/samples/Sample/Platform.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Core/IFrameworkElement.cs
- src/Platform.Handlers/src/Xamarin.Platform.Handlers/Registrar.cs
- src/Platform.Renderers/src/Xamarin.Forms.Platform.Android/HandlerToRendererShim.cs
- src/Platform.Renderers/src/Xamarin.Forms.Platform.iOS/HandlerToRendererShim.cs
Move the layout classes from the Sample app to Forms.
Adds a small gallery to demo using the new layouts in a Forms Page with shimmed Labels.
> Move the new Layout classes to Forms; make the new layouts work in CG

- Directory.Build.props
- Directory.Build.targets
Reduce the tasks needed to run when developing
- skip the gitinfo install
- skip the version generation
- skip the sourcelink
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> Disable the versioning locally

- src/Core/src/Platform/Android/ContextExtensions.cs
- src/Core/tests/DeviceTests/AssertionExtensions.Android.cs
* check when using new APIs
* add the view to the hierarchy to make sure everything is complete
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> Fix android tests

- eng/pipelines/device-tests.yml
- eng/pipelines/handlers.yml
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> Fixing the branch name

- Xamarin.Forms.Platform.Tizen/Native/Watch/WatchDialog.cs
Prevent null reference for Tizen WatchDialog.
- fixes #
None
- Tizen
None
Not applicable
> [Tizen] Fix WatchDialog

- Xamarin.Forms.Core/ListView.cs
Fix possible Exception in ListView Command validation.
- fixes #14443 
None
None
Not applicable
> [Core] Fix NRE in ListView Command validation

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11795.xaml
- Xamarin.Forms.Platform.Android.UnitTests/AssertionExtensions.cs
- Xamarin.Forms.Platform.Android.UnitTests/CornerRadiusTests.cs
- Xamarin.Forms.Platform.Android.UnitTests/PlatformTestFixture.cs
- Xamarin.Forms.Platform.Android/GradientStrokeDrawable.cs
- Xamarin.Forms.Platform.Android/Renderers/BoxRenderer.cs
Fix broken Android platform tests.
None
- Android
None
Not applicable
> [Housekeeping] Fix broken Android platform tests

- Xamarin.Forms.Platform.Android.FormsViewGroup/Xamarin.Forms.Platform.Android.FormsViewGroup.csproj
- build/steps/build-android.yml
Fixes issues using stable android 
None
- Android
None
Not applicable
turn provisioningCake to true
> [Android] Fix building with Android stable bits

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla30353.cs
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> Add better resolution to UI Tests

- Xamarin.Forms.Platform.iOS/DragAndDropDelegate.cs
Fix Exception dropping element from removed view on iOS.
- fixes #14602 
None
- iOS
None
> [iOS] Fix NRE dropping element from removed view

- Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
TBD
- fixes #14887
None
- iOS
None
Not applicable
> [WIP] Revert ClearButton Visibility Regressions on iOS

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue14380.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
Fix issue rendering gradient background in NavigationPage on iOS.
- fixes #14380 
None
- iOS
None
Not applicable
Launch Core Gallery and navigate to the issue 14380. If can see the gradient background, the test has passed.
> [iOS] Fix issue rendering gradient background in NavigationPage 

- Xamarin.Forms.Core/VisualElement.cs
Added null check to prevent introduced NRE in edge cases
- fixes #15177
None
None
Not applicable
> Fix NRE VisualElement Background when is null

- README.md
fix the link to the repro.md file in the README of Xamarin.Forms
None
None
None
Not applicable
> fix link to repro.md

- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.MacOS/Xamarin.Forms.ControlGallery.MacOS.csproj
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
- Xamarin.Forms.Maps.GTK/Xamarin.Forms.Maps.GTK.csproj
Closes #15425
Closes #15427
Closes #15428
Closes #15429
Closes #15430
Closes #15431
Closes #15432
Closes #15433
> Update all Newtonsoft.Json references

- Xamarin.Forms.Platform.UAP/FlyoutPageRenderer.cs
Fix issue detecting Flyout property changes.
- fixes #14151
None
- UWP
None
> [UWP ]Fix issue detecting Flyout property changes 

- Xamarin.Forms.Platform.Android/PopupManager.cs
Also see: https://github.com/dotnet/maui/pull/9342
> Update PopupManager EditText to AppCompat

- Xamarin.Forms.Core/MenuItem.cs
> Adds a null-guard in `MenuItem` to prevent NRE

- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
- Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs
> Fix iOS 16 TitleView measurement

- Xamarin.Forms.sln
Project Filenames changed to fix solution on case sensitive filesystems.
- fixes #
no.
> Solution fix for projects on case sensitive filesystems
