- Xamarin.Forms.Controls/CoreGalleryPages/WebViewCoreGalleryPage.cs
- Xamarin.Forms.Core.UnitTests/WebViewUnitTests.cs
- Xamarin.Forms.Core/PlatformConfiguration/WindowsSpecific/WebView.cs
- Xamarin.Forms.CustomAttributes/TestAttributes.cs
- Xamarin.Forms.Platform.UAP/WebViewRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.WindowsSpecific/WebView.xml
- docs/Xamarin.Forms.Core/index.xml
Implements and fixes #1682.
Add a PlatformSpecific property for `WebView` on UWP to allow WebViews to display alert boxes via JavaScript.
`webView.On<Windows>().SetIsJavaScriptAlertEnabled(true)` causes js calls to `window.alert` to display the intended message in a native UWP message box.
Added (UWP Only):
- bool WebView.IsJavaScriptAlertEnabled() //Bindable Property
- void WebView.SetIsJavaScriptAlertEnabled(bool value)
> [Enhancement] UWP PlatformSpecific to display JavaScript alerts in WebView

- Xamarin.Forms.Platform.iOS/Cells/ImageCellRenderer.cs
by the time the async image load completes the imagecell could be disposed resulting in an unhandled exception (NSObjectDisposed)
> [iOS] Fix object disposed exception in ImageCell

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Core.UnitTests/BindingUnitTests.cs
- Xamarin.Forms.Core.UnitTests/TypedBindingUnitTests.cs
- Xamarin.Forms.Core/BindingBase.cs
- Xamarin.Forms.Core/BindingExpression.cs
- Xamarin.Forms.Core/BindingMode.cs
- Xamarin.Forms.Core/TypedBinding.cs
- Xamarin.Forms.Xaml.UnitTests/BindingsCompiler.xaml
- Xamarin.Forms.Xaml.UnitTests/BindingsCompiler.xaml.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/BindingMode.xml
[C/XamlC] BindingMode.OneTime
Bindings with mode == OneTime:
- are only applied when the BindingContext changes
- do not subscribe to INPC
if the Binding is compiled and the mode explicitely set in the
`{Binding}` Markup extension, the setters and handlers aren't even
created.
- fixes #1686
Added:
- `BindingMode.OneTime`
/
> [C/XamlC] BindingMode.OneTime

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40092.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UnitTests/AbsoluteLayoutTests.cs
- Xamarin.Forms.Core/AbsoluteLayout.cs
- Xamarin.Forms.Core/DeviceInfo.cs
- Xamarin.Forms.Platform.Android/Forms.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/DeviceInfo.xml
Changed AbsoluteLayout.cs to use a platform specific DisplayRound method to allow for cases where a straight Math.Round won't correctly round to the pixel density of the device.  Currently this is only overridden in Android and all the other platforms still just use Math.Round
https://bugzilla.xamarin.com/show_bug.cgi?id=40092
fixes #1128
Added:
- public override double DisplayRound(double value)
Platforms can now customize how rounding works for calculations that pertain to pixels.
None
- [X ] Has tests (if omitted, state reason in description)
- [ X] Rebased on top of master at time of PR
- [ X] Changes adhere to coding standard
- [ X] Consolidate commits as makes sense
> [Core] AbsoluteLayout content now fills all available space on Android devices

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Github1625.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/SliderRenderer.cs
#378 fixed an issue but also introduced regression. This fixes both #378 and #1625. When the element itself or its properties are changing from the Core side, SeekBar's tracker isn't being manipulated by the user, so we can ignore native changes being propagated back to Core. Please see instructions in the test.
Note that this introduces the problem that Core and Native aren't always in sync as there is a small precision difference. However, not adding this fix is more problematic because users see values that they did not expect.
- https://bugzilla.xamarin.com/show_bug.cgi?id=54887
- fixes #1625
> [Android] Slider should show correct Value even though SeekBar's Progress is slightly off

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1717.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/PlatformConfiguration/WindowsSpecific/InputView.cs
- Xamarin.Forms.Core/PlatformConfiguration/WindowsSpecific/Label.cs
- Xamarin.Forms.Platform.UAP/EditorRenderer.cs
- Xamarin.Forms.Platform.UAP/EntryRenderer.cs
- Xamarin.Forms.Platform.UAP/LabelRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.WindowsSpecific/InputView.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.WindowsSpecific/Label.xml
- docs/Xamarin.Forms.Core/index.xml
Fixes #1717 by adding property DetectReadingOrderFromContentProperty
to InputView and Label and updating EntryRenderer, EditorRenderer and LabelRenderer
for Windows.
Added `DetectReadingOrderFromContent` property to InputView (Entry/Editor) and Label on Windows. Updated EntryRenderer, EditorRenderer and LabelRendrer classes on Windows so when this PS is enabled, the TextReadingOrder property of the native controls is set to DetectFromContent. Otherwise, TextReadingOrder remain in its default value of UseFlowDirection.
- #1717 Allow DetectReadingOrderFromContent on UWP
Added to `WindowsSpecific`:
- `InputView.DetectReadingOrderFromContent //Bindable property`. Includes `Entry` and `Editor` classes when inherit from `InputView`.
-  `Label.DetectReadingOrderFromContentProperty //Bindable …
> [UWP] Allow DetectReadingOrderFromContent (#1717)

- Xamarin.Forms.Platform.Android/GestureManager.cs
- Xamarin.Forms.Platform.Android/InnerGestureListener.cs
The ScaleGestureDetector in Android doesn't always fire an end gesture event. It seems we rely upon this to fire the EndScrolling method. 
If we also listen for the touch up event, we can call EndScrolling event if the ScaleGestureDetector fails to fire.
I'm not opposed to moving the TapAndPanGestureDetector to it's own file, if you prefer.
- fixes #1495
None
None
> [Android] Ensure PanGestureRecognizer sends the Completed status (#1495)

- Xamarin.Forms.Build.Tasks/BindablePropertyReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/BindingTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/BoundsTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/ColorTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/ConstraintTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/LayoutOptionsConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/ListStringTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/RDSourceTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/RectangleTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/ThicknessTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/TypeTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/UriTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/StaticExtension.cs
- Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/TypeExtension.cs
- Xamarin.Forms.Build.Tasks/CompiledValueProviders/SetterValueProvider.cs
- Xamarin.Forms.Build.Tasks/CompiledValueProviders/StyleSheetProvider.cs
- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/DebugXamlCTask.cs
- Xamarin.Forms.Build.Tasks/ModuleDefinitionExtensions.cs
- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Build.Tasks/SetNamescopesAndRegisterNamesVisitor.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/SetResourcesVisitor.cs
- Xamarin.Forms.Build.Tasks/TypeDefinitionExtensions.cs
- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Build.Tasks/XamlTask.cs
[XamlC] Cache Resolve and ImportReference
ImportReference with System.Reflection based argument is notoriously
slow on .NET. So we cache the results for those.
We do not cache the results for TypeReference, MethodReference or
FieldReference calls, as those are already fast (passthrough if the
reference was already imported), and they aren't valid as dictionary
keys (no concept of equatability).
While we're at it, we shave another few ms from Resolve(TypeReference)
calls as well.
As, on good days, it shaves up to 40% of XamlC time, we can say that it fixes #1848
- fixes #1848
> [XamlC] Cache Resolve and ImportReference

- .nuspec/Xamarin.Forms.AppLinks.nuspec
- .nuspec/Xamarin.Forms.Maps.GTK.nuspec
- .nuspec/Xamarin.Forms.Maps.WPF.nuspec
- .nuspec/Xamarin.Forms.Maps.nuspec
- .nuspec/Xamarin.Forms.Pages.nuspec
- .nuspec/Xamarin.Forms.Platform.GTK.nuspec
- .nuspec/Xamarin.Forms.Platform.WPF.nuspec
- .nuspec/Xamarin.Forms.nuspec
remove $IdAppend$ from our .nuspec
those nuget variables aren't used anymore, I think, in any of our release script (but I might be wrong)
> [Internal] Remove $IdAppend$ from our .nuspec

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60045.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60045.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UnitTests/TextCellTests.cs
- Xamarin.Forms.Core/Cells/TextCell.cs
Adds a check for `IsEnabled` before executing a Command from a TextCell.
* [60045 – ListView with RecycleElement strategy doesn't handle CanExecute of TextCell Command properly (Forms->iOS)](https://bugzilla.xamarin.com/show_bug.cgi?id=60045)
None
None
> Check IsEnabled on TextCell before executing command

- Xamarin.Forms.Controls/CoreGalleryPages/ProgressBarCoreGalleryPage.cs
- Xamarin.Forms.Core.UnitTests/NotifiedPropertiesTests.cs
- Xamarin.Forms.Core/ProgressBar.cs
- Xamarin.Forms.CustomAttributes/TestAttributes.cs
- Xamarin.Forms.Platform.Android/Renderers/ProgressBarRenderer.cs
- Xamarin.Forms.Platform.MacOS/Renderers/ProgressBarRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ProgressBarRenderer.cs
- Xamarin.Forms.Platform.UAP/ProgressBarRenderer.cs
- Xamarin.Forms.Platform.WPF/Renderers/ProgressBarRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ProgressBarRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/ProgressBar.xml
This PR adds the `ProgressColor` bindable property to the `ProgressBar` control.
- fixes #1690
Added:
- `BindableProperty ProgressBar.ProgressColorProperty;`
- `Color ProgressBar.ProgressColor { get; set; } //Bindable Property`
Changed:
- None
- None
- On Android API 21+ `ColorStateList` is used instead of `SetColorFilter` in order to apply the color tinting to the progress line only
- The Android Renderer manages both the `Determinate` and `Intederminate` state
- NOP on GTK due to some constraints when overriding the default GtkWidget style
- Not every platform exposes APIs to change the track appearance. Shouldn't the TrackColor feature be implemented in a platform-specific fashion?
> Add ProgressColor on ProgressBar

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GitHub1878.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/AutoSuggestStyle.xaml
- Xamarin.Forms.Platform.UAP/ColorExtensions.cs
- Xamarin.Forms.Platform.UAP/Extensions.cs
- Xamarin.Forms.Platform.UAP/Forms.cs
- Xamarin.Forms.Platform.UAP/FormsCancelButton.cs
- Xamarin.Forms.Platform.UAP/MasterBackgroundConverter.cs
- Xamarin.Forms.Platform.UAP/Resources.xaml
- Xamarin.Forms.Platform.UAP/SearchBarRenderer.cs
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
When setting the `CancelButtonColor` of multiple SearchBars on UWP, every SearchBar's cancel button will have the color of the last one set. 
This PR changes the way the colors are set in the renderer, and allows each SearchBar to have its own CancelButtonColor.
- fixes #1878 
None
None
> [UWP] Allow SearchBar cancel button colors to be set individually 

- Xamarin.Forms.Core.UnitTests/BindableObjectUnitTests.cs
- Xamarin.Forms.Core/BindableObject.cs
- Xamarin.Forms.Core/FlexLayout.cs
- Xamarin.Forms.Core/VisualStateManager.cs
[C] BO.IsSet() returns false after ClearValue()
- fixes #1813
/
/
> [C] BO.IsSet() returns false after ClearValue()

- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/EntryPageAndroid.cs
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGallery.cs
- Xamarin.Forms.Core/PlatformConfiguration/AndroidSpecific/Entry.cs
- Xamarin.Forms.Platform.Android/Extensions/EntryRendererExtensions.cs
- Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/Entry.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/ImeFlags.xml
- docs/Xamarin.Forms.Core/index.xml
Add a platform specific for entries on Android that allows to control the options for keyboard and interactions with TextView
- Fixes #1696
``` 
public static readonly BindableProperty ImeOptionsProperty = BindableProperty.Create(nameof(ImeOptions), typeof(ImeFlags), typeof(Entry), ImeFlags.Default);
public static ImeFlags GetImeOptions(BindableObject element)
public static void SetImeOptions(BindableObject element, ImeFlags value)
public static ImeFlags ImeOptions(this IPlatformElementConfiguration<Android, FormsElement> config)
public static IPlatformElementConfiguration<Android, FormsElement> SetImeOptions(this IPlatformElementConfiguration<Xamarin.Forms.PlatformConfiguration.Android, FormsElement> config, ImeFlags value)
public enum ImeFlags
{
Default = 0,
None = 1,
Go = 2,
Search = …
```
> [Android,Core] Entry platform specific to set ImeOptions and flags

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1660.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/InputView.cs
- Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.UAP/EditorRenderer.cs
- Xamarin.Forms.Platform.UAP/EntryRenderer.cs
- Xamarin.Forms.Platform.UAP/FormsTextBoxStyle.xaml
- Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/InputView.xml
Adds the InputView.IsSpellCheckEnabled property which makes it easier to
disable the native spell checking features. Fixes #1660.
Added `IsSpellCheckEnabledProperty` to `InputView`, which is the base class of both `Entry` and `Editor`. Modified `EditorRenderer.OnElementPropertyChanged()` and `EntryRenderer.OnElementPropertyChanged()` for Android, iOS and UWP to react to changes to the new `IsSpellCheckEnabled` property.
While implementing this for UWP I discovered what seemed to be a bug in that the UWP `EditorRenderer.UpdateInputScope()` method had calls to `ClearValue()` for the native control's `IsTextPredictionEnabledProperty` and `IsSpellCheckEnabledProperty`  while `EntryRenderer.UpdateInputScope()` hadn't. The effect was that for UWP `Editor`s text prediction and spell checking …
> [All] IsSpellCheckEnabled on Entry/Editor

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Allow customizing Android MenuItem with tintcolor and custom drawable.
Added:
- protected virtual void UpdateDrawableMenuItem(Context context, IMenuItem menuItem, ToolbarItem toolBarItem)
Changed:
- void HandleToolbarItemPropertyChanged(object sender, PropertyChangedEventArgs e) -> protected virtual void HandleToolbarItemPropertyChanged(object sender, PropertyChangedEventArgs e)
> [Android] Allow customizing Android MenuItem

- .gitmodules
This is the norm in all other repos building in VSTS and
makes upstream build definitions and scripts much simpler.
> Use relative URL to support recursive checkout in VSTS

- Xamarin.Forms.Platform.Tizen/Renderers/LayoutRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ViewRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs
This PR is extension of #1771 and #1621 for tizen backend. 
- On Tizen Mobile Emulator
None
None
From now, tizen also support to allow `Layout` to specify whether child controls cascade `InputTrandparent`.
> [Tizen] Support CascadeInputTransparent to Tizen

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1665.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/ListView.cs
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/SeparatorStyle.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/ListView.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/SeparatorStyle.xml
- docs/Xamarin.Forms.Core/index.xml
This PR adds a `SeparatorStyle` (with possible values `Default, FullWidth`) property to iOS specific `ListView`. Setting this to `FullWidth` causes the separator between cells to use the full width of the screen.
Added new `enum SeparatorStyle {Default, FullWidth}` which can be set to new property `ListView.SeparatorStyle` on iOS. The `ListViewRenderer` checks if this property is set when cells are rendererd in `ListViewDataSource.GetCell()` and sets `SeparatorInset` and `LayoutMargins` to zero if separator style is `FullWidth`. 
A design decision was made to not support changing separator style back to Default once it has been set to FullWidth. So a reused cell already rendered with FullWidth won't be changed if the separator style is reverted to Default. The reasoning is that you …
> [iOS] ListView full width separators

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1707.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/VisualElement.cs
- Xamarin.Forms.Platform.iOS/Properties/AssemblyInfo.cs
- Xamarin.Forms.Platform.iOS/ShadowEffect.cs
- Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/VisualElement+ShadowEffect.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.iOSSpecific/VisualElement.xml
- docs/Xamarin.Forms.Core/index.xml
Adds the ability to set drop shadows for any arbitrary iOS control. For now I have descoped the UWP implementation as after digging in it appears to be much more involved than initially hoped. It does not seem likely it can be well encapsulated without having to affect renderers not using the new drop shadow API.
This does not mean we shouldn't do UWP at some point, just that the risk profile does not match the goals of the F100 project.
- fixes #1707
Added:
```csharp
View.On<iOS>.SetShadowColor (Color color);
View.On<iOS>.SetShadowRadius (double radius);
View.On<iOS>.SetShadowOffset (Size offset);
View.On<iOS>.SetShadowOpacity (double opacity);
```
There are no behavioral changes, just the additions.
> [iOS] Add shadow effect

- .editorconfig
set csharp_space_after_keywords_in_control_flow_statements to true in editor config to fit the development guidelines of having a space
```
if (
```
None
> set csharp_space_after_keywords_in_control_flow_statements to true

- Xamarin.Forms.Controls/GalleryPages/MapGallery.cs
- Xamarin.Forms.Core.UITests.Shared/PlatformQueries.cs
- Xamarin.Forms.Core.UITests.Shared/Queries.cs
- Xamarin.Forms.Core.UITests.Shared/Tests/MapUITests.cs
- Xamarin.Forms.Core.UITests.Shared/Xamarin.Forms.Core.UITests.projitems
- Xamarin.Forms.Maps.iOS/MapRenderer.cs
- #893 without breaking change to iOS MapRenderer base class.
- Continuation of #844 to create customization feature parity between Android and iOS.
- [Evolution Forum Post](https://forums.xamarin.com/discussion/91907/map-renderer-extensibility/)
Removed:
- MapDelegate class -> Methods moved into MapRenderer class
Changed:
- private void AttachGestureToPin(MKPinAnnotationView mapPin, IMKAnnotation annotation) => protected void AttachGestureToPin(MKAnnotationView mapPin, IMKAnnotation annotation) 
- So the Pin.Clicked event can be used when GetViewForAnnotation is overridden and/or native pin is rendered as a different subclass of MKAnnotationView
Should not change any existing functionality in the base library, makes it easier to customize pins when extending the iOS MapRenderer.
> [iOS Maps] Pin rendering customization

- Xamarin.Forms.Core/Application.cs
- Xamarin.Forms.Core/BindableObject.cs
- Xamarin.Forms.Core/Cells/Cell.cs
- Xamarin.Forms.Core/Cells/EntryCell.cs
- Xamarin.Forms.Core/Cells/SwitchCell.cs
- Xamarin.Forms.Core/DeviceInfo.cs
- Xamarin.Forms.Core/Editor.cs
- Xamarin.Forms.Core/Element.cs
- Xamarin.Forms.Core/FormattedString.cs
- Xamarin.Forms.Core/Interactivity/MultiCondition.cs
- Xamarin.Forms.Core/Interactivity/PropertyCondition.cs
- Xamarin.Forms.Core/Internals/ToolbarTracker.cs
- Xamarin.Forms.Core/ListView.cs
- Xamarin.Forms.Core/MasterDetailPage.cs
- Xamarin.Forms.Core/MenuItem.cs
- Xamarin.Forms.Core/MultiPage.cs
- Xamarin.Forms.Core/OpenGLView.cs
- Xamarin.Forms.Core/Page.cs
- Xamarin.Forms.Core/ScrollView.cs
- Xamarin.Forms.Core/TableView.cs
- Xamarin.Forms.Core/TemplatedItemsList.cs
- Xamarin.Forms.Core/Tweener.cs
- Xamarin.Forms.Core/VisualElement.cs
- Xamarin.Forms.Core/WebView.cs
This is effectively equivalent to the original code, yet nicer to read :)
This is also how it's being done elsewhere (i.e. fast renderers,
BindableObject, etc.), probably because that code is newer?
> Simplify event raising invocation pattern

- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.ControlGallery.WindowsUniversal/CustomRenderers.cs
- Xamarin.Forms.ControlGallery.iOS/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1683.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/KeyboardFlags.cs
- Xamarin.Forms.Platform.Android/Renderers/KeyboardExtensions.cs
- Xamarin.Forms.Platform.UAP/KeyboardExtensions.cs
- Xamarin.Forms.Platform.iOS/Extensions/Extensions.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/KeyboardFlags.xml
The Entry and Editor controls do not have a simple mechanism for controlling the native automatic capitalization features.
Expand Keyboard flags to include Word, Character, and No Capitalized. The keyboard already supports CapitalizeSentence so it just needs to have Words and Characters added to it
Currently
```
[Flags]
public enum KeyboardFlags
{
None = 0,
CapitalizeSentence = 1,
Spellcheck = 1 << 1,
Suggestions = 1 << 2,
All = ~0
}
```
Expand To
```
[Flags]
public enum KeyboardFlags
{
None = 0,
CapitalizeSentence = 1,
Spellcheck = 1 << 1,
Suggestions = 1 << 2,
CapitalizeWords = 1 << 3,
CapitalizeCharacters = 1 << 4,
CapitalizeNone = 1 << 5,
All = ~0
}
```
Currently None only really has in meaning for iOS
Add checks for additional flags to
```
public static void ApplyKeyboard(this …
```
> AutoCapitalization support for Entry/Editor

- Xamarin.Forms.Build.Tasks/BindablePropertyReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/BindingTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/BoundsTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/ColorTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/ConstraintTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/LayoutOptionsConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/ListStringTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/RDSourceTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/RectangleTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/ThicknessTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/TypeTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/UriTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/TypeExtension.cs
- Xamarin.Forms.Build.Tasks/CompiledValueProviders/SetterValueProvider.cs
- Xamarin.Forms.Build.Tasks/CompiledValueProviders/StyleSheetProvider.cs
- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/ModuleDefinitionExtensions.cs
- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Build.Tasks/SetNamescopesAndRegisterNamesVisitor.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/TypeDefinitionExtensions.cs
- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/XamlCAssemblyResolver.cs
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Build.Tasks/XamlTask.cs
- Xamarin.Forms.Build.Tasks/XmlTypeExtensions.cs
[XamlC] no longer use any reflection-base ImportReference
reflection-base ImportReference -- we were using MethodBase and Type --
are importing the types present in the reflection context, at the time
of compilation. As the compilation happens on netstandard2.0, and our
assembly can now be netstandard1.0 again, those imported types are
failing to be resolved.
this changes always import references based on the assembly, or the
assembly references.
it might, or might not, give us another speed bump.
> [XamlC] no longer use any reflection-base ImportReference

- Xamarin.Forms.Controls/GalleryPages/ScrollGallery.cs
- Xamarin.Forms.Core/ScrollBarVisibility.cs
- Xamarin.Forms.Core/ScrollView.cs
- Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.GTK/Renderers/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.MacOS/Renderers/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.UAP/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.WPF/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.WPF/Renderers/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/ScrollBarVisibility.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ScrollView.xml
- docs/Xamarin.Forms.Core/index.xml
Added vertical and horizontal scroll bar visibility properties to ScrollView and updated UWP, WPF, iOS and Android renderers
I noticed on Android when the ScrollView.Orientation = ScrollOrientation.Both that a horizontal scroll bar is never shown, only the vertical.  I did not try to change this to avoid making a default behavior change.
Unit Tests are not included as I'm not sure what to test right now besides that basic properties were set.
fixes #1670 
- N/A
Added:
```
public enum ScrollBarVisibility
{
Default,
Always,
Never,
} 
```
- ScrollBarVisibility ScrollView.HorizontalScrollBarVisibility {get; set;};
- ScrollBarVisibility ScrollView.VerticalScrollBarVisibility {get;set;};
Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this …
> [Core, iOS, Android, UWP, WPF] Hide scroll view scroll bars

- Xamarin.Forms.Platform.Tizen/Renderers/ButtonRenderer.cs
This PR support to `Button.Pressed` and `Button.Released` events on tizen backend.  And ,removes the `warning CS0618: 'Button.BorderRadiusProperty' is obsolete` as well.
None
None
None
> [Tizen] Enhance the button renderer of tizen backend

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1908.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Extensions/ImageViewExtensions.cs
If the provided source for an image is a FileImageSource then attempt to resolve the image as a drawable via GetResource opposed to creating a bitmap from the file itself.  This requires a lot less memory.  With the included Unit Test I can load 1000 Xamarin Forms Images without causing Out Of Memory Exceptions now. 
fixes #1908
This change was done in such a way that behavior should remain the same outside of some performance gains when an image is used in multtiple places
> [Android] attempt to load images from drawables before using bitmap

- Xamarin.Flex/Flex.cs
- Xamarin.Forms.Core/OrderedDictionary.cs
The fixed instances are either invalid XML (spaces around the xml element name) 
or point to non-existing members.
> Fix invalid XML docs

- Xamarin.Forms.Core/DesignMode.cs
- Xamarin.Forms.Core/Internals/ResourceLoader.cs
- Xamarin.Forms.Platform.UAP/WindowsBasePage.cs
- Xamarin.Forms.Xaml/XamlLoader.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/DesignMode.xml
- docs/Xamarin.Forms.Core/index.xml
this is a clean version of #1844
Adds a static class and static bool for DesignModeEnabled to Xamarin.Forms.Core. This is to address the F100 Issue (fixes #1731). This is only intended to address programmatic checks by a developer. It does not cover things like d:DesignHeight or other designer aware XAML elements and attributes.
Tooling would need to toggle the DesignModeEnabled property whenever appropriate so that developers can rely on it.
- fixes #1731
Added:
- `public static DesignMode.DesignModeEnabled { get; }`
/
> [Xaml] add DesignMode flag

- Xamarin.Forms.ControlGallery.Android/Resources/drawable/red_button.xml
- Xamarin.Forms.ControlGallery.Android/Resources/values/styles.xml
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.Android/_1909CustomRenderer.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1436.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1909.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/PlatformConfiguration/AndroidSpecific/Button.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Platform.Android/ButtonBackgroundTracker.cs
- Xamarin.Forms.Platform.Android/Renderers/ButtonDrawable.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.AndroidSpecific/Button.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Button.xml
- docs/Xamarin.Forms.Core/index.xml
Removing the Padding and Shadow that were added in #1570 to make the X.F. Buttons mimic the style of a default Android `Button`. These can be added back to Buttons using new Platform Specifics.
Also adjusting the padding mismatch that made circle Buttons appear to be slightly rectangular.
Before #1570:
After #1570:
After this change (note, changed the test case for an additional parameter):
- fixes #1909
- fixes #1954 
Added:
- `bool Button.On<Android>().UseDefaultPadding()`
- `void Button.On<Android>().SetUseDefaultPadding(true/false)`
- `bool Button.On<Android>().UseDefaultShadow()`
- `void Button.On<Android>().SetUseDefaultShadow(true/false)`
> [Android] Buttons can be round; remove Padding & Shadow by default

- Xamarin.Forms.Core.UnitTests/PageTests.cs
- Xamarin.Forms.Core/Application.cs
- Xamarin.Forms.Core/Page.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Application.xml
In scenarios where you want to keep track of pages as they are
appearing on screen, it's useful to be able to subscribe to a
global event from the `Application` to track those pages for
later processing (i.e. showing a timeline for the app, reloading
XAML for some of those pages, maybe replaying the timeline, etc.)
The new events are automatically raised from the Page base class
right after sending the page-level Appearing/Disappearing events.
> Add Application.PageAppearing/Dissapearing events

- Xamarin.Flex/Flex.cs
- Xamarin.Forms.Core/FlexLayout.cs
[Flex] correctly measure images
use Aspect.Fill to measure images. also make sure we do not crash if the
Bounds are smaller than the request. Like any other control, we will
draw outside of our bounds, and rely on ClipToBounds for a nice shave.
> [Flex] correctly measure images

- Xamarin.Forms.Core/VisualElement.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/VisualElement.xml
[CSS] use `class` instead of `StyleClass`
- fixes #2022
Added:
- `public [TypeConverter(typeof(ListStringTypeConverter))] VisualElement.IList<string> @class { get; set;}`
Changed:
- `public [TypeConverter(typeof(ListStringTypeConverter))] VisualElement.IList<string> StyleClass{ get; set;}` => Obsolete
/
> [CSS] use `class` instead of `StyleClass`

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1705_2.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/PlatformConfiguration/WindowsSpecific/TabbedPage.cs
- Xamarin.Forms.Platform.UAP/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.UAP/TabbedPageStyle.xaml
- docs/Xamarin.Forms.Core/Xamarin.Forms.PlatformConfiguration.WindowsSpecific/TabbedPage.xml
- docs/Xamarin.Forms.Core/index.xml
Implement icon support for TabbedPage on UWP.
Fixes #1705.
Added new Windows platform specific properties to enable/disable icons on tabbed page control as well as possibility to control icon size. 
Added:
- New bindable properties on Xamarin.Forms.PlatformConfiguration.WindowsSpecific.TabbedPage, "HeaderIconsEnabledProperty" and "HeaderIconsSizeProperty"
- TabbedPage.On<Windows>().IsHeaderIconsEnabled();
- TabbedPage.On<Windows>().SetHeaderIconsEnabled(true/false);
- TabbedPage.On<Windows>().GetHeaderIconsEnabled();
- TabbedPage.On<Windows>().EnableHeaderIcons();
- TabbedPage.On<Windows>().DisableHeaderIcons();
- TabbedPage.On<Windows>().SetHeaderIconsSize(true/false);
- TabbedPage.On<Windows>().GetHeaderIconsSize();
By default icons will remain disabled on tabbed page controls so …
> [UWP] Icon on TabbedPage

- Xamarin.Forms.Core/VisualElement.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/VisualElement.xml
Reinstate StyleClass
None
Changed:
- VisualElement.StyleClass is no longer Obsoleted
None
> Reinstate StyleClass but keep @class

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GitHub1567.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
We were disposing our renderers of the prototype cell so we should also just clear our prototypecell 
- fixes #1567
> [iOS] Clear prototype cell on UnevenRows

- Xamarin.Forms.Build.Tasks/CompiledConverters/BindablePropertyConverter.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2034.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2034.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] Find the real VisualState parent
`VisualStateGroupList` can be implicit, and it looks like tht wasn't
tested. This adds a test, and a fix.
- fixes #2034
/
/
> [XamlC] Find the real VisualState parent

- Xamarin.Forms.Controls/CoreGalleryPages/LabelCoreGalleryPage.cs
- Xamarin.Forms.Controls/GalleryPages/LabelGallery.cs
- Xamarin.Forms.Core.UnitTests/SpanTests.cs
- Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
- Xamarin.Forms.Core/BindableProperty.cs
- Xamarin.Forms.Core/FormattedString.cs
- Xamarin.Forms.Core/Label.cs
- Xamarin.Forms.Core/MergedStyle.cs
- Xamarin.Forms.Core/Span.cs
- Xamarin.Forms.Core/VisualElement.cs
- Xamarin.Forms.Platform.Android/Renderers/FormattedStringExtensions.cs
- Xamarin.Forms.Platform.GTK/Extensions/LabelExtensions.cs
- Xamarin.Forms.Platform.Tizen/Cells/CellRenderer.cs
- Xamarin.Forms.Platform.Tizen/Cells/TextCellRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/LabelRenderer.cs
- Xamarin.Forms.Platform.UAP/LabelRenderer.cs
- Xamarin.Forms.Platform.WPF/Extensions/FormattedStringExtensions.cs
- Xamarin.Forms.Platform.iOS/Renderers/FormattedStringExtensions.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/FormattedString.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Label.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/Span.xml
This allows Text to be Bindable on a Span.
It also added the Style property to the Span, to set the Font Elements.
fixes #1340
N/A
Added:
- TextColor { get; set; } // Bindable Property
Marked Obsolete:
- ForegroundColor { get; set; }
- ForegroundColor now just updates TextColor
N/A
> [All] Bindable span

- Xamarin.Forms.Core.UnitTests/BindableObjectUnitTests.cs
- Xamarin.Forms.Core/BindableObject.cs
BindableProperties with a defaultValueCreator are never in the default
(as defined by the defaultValue parameter) state. IsSet now reflects
that.
To allow styling properties with defaultVC, this adds a new flag in
BindableContextAttributes.
fixes #2046 
/
/
> [C] do not return IsSet for BP with defaultVC

- Xamarin.Forms.Platform.Tizen/GestureDetector.cs
- Xamarin.Forms.Platform.Tizen/Renderers/LayoutRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ViewRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs
This change provides :
- a) a way for the user to inject their own dependency resolution method for gesture handlers (it comes from #1870). As a results, users can specifiy resolution method for gesture handlers on tizen backend. See also [a brief exapmle of using this with an IoC container](https://gist.github.com/rookiejava/17f8d8f92032e3c06187ecd92a9fe486)
- b) fix the potential issue for the GestureDetector
None
None
None
> [Tizen] Refactor the GestureDetector

- Xamarin.Forms.Core.UnitTests/BindableObjectUnitTests.cs
- Xamarin.Forms.Core/BindingExpression.cs
If the BindingContext is set using SetInheritedBindingContext, INPC
isn't fired, and bindings containing the "BindingContext" string in
the path ends up not being notified of the Change.
In addition to listening to PropertyChanged, this also hooks into
BindingContextChanged, and update the bindings accordingly.
- fixes #2019
/
/
> [C] Update Bindings with "BindingContext" in path

- Xamarin.Forms.Platform.Tizen/Renderers/SliderRenderer.cs
This PR is extension of #1781.
_Due to tizen UX policy and limitation, this feature only works on mobile devices (`TargetIdiom.Phone`) and is ignored for other devices._
None
None
None
> [Tizen] Support to change color on Slider

- Xamarin.Forms.Platform.MacOS/Renderers/PickerRenderer.cs
Changed the native control in macOS's Picker to the NSPopUpButton from the NSComboBox.
fixes #1610
None.
The popup on the control will now size to the elements in the list no longer ellipsising the items.  It also allows for the control to be clicked over the entirety of the control rather than just the drop down button.
OLD:
NEW:
> [macOS] Alternate picker.  Changed native control to NSPopupButton.

- EmbeddingTestBeds/Embedding.Droid/Embedding.Droid.csproj
- EmbeddingTestBeds/Embedding.XF/Embedding.XF.csproj
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- PagesGallery/PagesGallery.UWP/PagesGallery.UWP.csproj
- PagesGallery/PagesGallery.iOS/PagesGallery.iOS.csproj
- PagesGallery/PagesGallery/PagesGallery.csproj
- Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
- Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj
- Xamarin.Forms.Platform.Android.FormsViewGroup/Xamarin.Forms.Platform.Android.FormsViewGroup.csproj
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
These changes solve two problems. 
Right now after a full `git clean`, opening the solution in VSWin results in errors in each project which attempts to import Xamarin.Forms.targets because Xamarin.Forms.Build.Tasks.dll is not yet built. VS doesn't display these errors immediately. If you then build the Tasks project and then attempt to build and run any of the XF projects in the solution (ControlGallery, PagesGallery, or the EmbeddingTestBed), VS will either:
1. Display the "Could not load Xamarin.Forms.targets" errors and refuse to build/run the project or
2. Completely freeze up and have to be killed
Either scenario requires a restart. 
With these changes, VSWin does not load the Xamarin.Forms.targets files if Xamarin.Forms.Build.Tasks.dll is not available, preventing the initial …
> Fix VS errors when loading clean solution; prevent VS rewriting Android project files

- Xamarin.Forms.Platform.Android/Renderers/FormsEditText.cs
Makes FormsEditText, EntryEditText, and EditorEditText constructors public. Consumption of these classes is generally a bad idea.
- Fixes #1797
Description says it all
None
> Mark ctors public

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1733.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/Editor.cs
- Xamarin.Forms.Core/EditorAutoSizeOption.cs
- Xamarin.Forms.Platform.UAP/EditorRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Editor.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/EditorAutoSizeOption.xml
- docs/Xamarin.Forms.Core/index.xml
fixes #1733
Added a property to Editor that will cause it to grow dynamically as the content of the Editor is changed. Basically as the text is changed the Editors size is recalculated and re-measured
Android was the least amount of work and was able to resize itself purely based on having its measure invalidated.
iOS almost worked as seamlessly as Android. 
When a new line is added to the UITextView the vertical growth happens after the view has already scrolled meaning now you had a line of text partially scrolled off screen. I added an event to watch for Frame Changes on the UITextView and if these happened then I forced the ScrollPosition to go back to *(0,0)*  If the Editor is set to AutoSize then the Frame of the UITextView should never be scrolled if the internal content hasn't …
> Editor Auto Resize with Text Changes

- Xamarin.Forms.Platform.UAP/MasterDetailControl.cs
- Xamarin.Forms.Platform.UAP/MasterDetailPageRenderer.cs
When nesting `NavigationPage` inside the MDP on UWP we weren't handling correctly the check if we should or not show the navigationbar. Since the UpdateMode wasn't taking that in account and always forcing the NavBar to appear. 
- fixes #1437 
None
None
> [UWP] MDP should respect HasNavigationBar for current page

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1601.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/VisualElementPackager.cs
Pass down removal queues to children packages in VisualElementPackager. Also dispose child packagers properly.
Fixes #1601 
None
Doesn't crash anymore :)
> [Android] Fix issue where compressed layouts couldn't be removed from the visual hierarchy

- Xamarin.Forms.Controls/ControlGalleryPages/EntryReturnTypeGalleryPage.cs
- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Core.UnitTests/EntryUnitTests.cs
- Xamarin.Forms.Core/Entry.cs
- Xamarin.Forms.Core/ReturnType.cs
- Xamarin.Forms.Platform.Android/Extensions/EntryRendererExtensions.cs
- Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.Tizen/Extensions/EntryExtensions.cs
- Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.UAP/EntryRenderer.cs
- Xamarin.Forms.Platform.UAP/Extensions.cs
- Xamarin.Forms.Platform.iOS/Extensions/Extensions.cs
- Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Entry.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/ReturnType.xml
- docs/Xamarin.Forms.Core/index.xml
Adding option for specify a diferente UI for the Done button of the Entry control. Also allows to specify a command and command parameter 
All props go to @brminnick  https://github.com/brminnick/EntryCustomReturnPlugin.
Investigated how we could expand this to allow any Image or Text like suggested on the spec, but that's really hard on most platforms, and needs to be "hacked" in using native private api from the OS. 
- Fixes #1697 
```csharp
public static readonly BindableProperty ReturnButtonTypeProperty = BindableProperty.Create(
nameof(ReturnButtonType),
typeof(ReturnButtonType),
typeof(Entry),
ReturnButtonType.Default);
public static readonly BindableProperty ReturnCommandProperty =  BindableProperty.Create(
nameof(ReturnCommand),
typeof(ICommand),
typeof(Entry));
public static …
```
> [Enhancement] Entry ReturnType

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1677.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/Entry.cs
- Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.UAP/EntryRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms/Entry.xml
Makes it easier for users to disable text prediction/autocomplete/autosuggest.
Fixes #1677.
Added the `Entry.IsTextPredictionEnabledProperty` field and `Entry.IsTextPredictionEnabled` property. Modified `EntryRenderer.OnElementPropertyChanged()` for Android, iOS and UWP to react to changes to the new `IsTextPredictionEnabled` property.
On Android setting `IsTextPredictionEnabled` to `false` sets the `InputTypes.TextFlagNoSuggestions` flag on the native control's `InputType`.
On UWP the native control's `IsTextPredictionEnabled` will be set to the value of the `Entry.IsTextPredictionEnabled` property.
On iOS the native control's `AutocorrectionType` property will be set to `No` when `Entry.IsTextPredictionEnabled` is `false`.
- Fixes #1677 [Enhancement] Entry: Control over text-prediction …
> Added the Entry.IsTextPredictionEnabled property

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1323.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs
We should update the TabBarItems color for text and background when we add new TabBarItems not only when we create the control
- fixes #1323 
None
None
> [iOS] Set UITabBarItem colours when they are added 

- Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
By default we were copying the title attributes to the LargeTitle we shouldn't do that if the user specified some Appearance on the iOS platform fot LargeTitles
Added a visual test for our navigation bar on the gallery 
- fixes #1804 
None
If user specifies `UINavigationBar.Appearance.LargeTitleTextAttributes` we won't copy the titles color and font properties for the normal navigation bar title.
> [iOS] Use UINavigationBar.Appearance.LargeTitleTextAttributes if specified

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1583_1.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/WebViewRenderer.cs
Encode url so it doesn't fail with non-ascii characters
fixes #1583 
None
> [iOS] Encode url for UIWebView so it doesn't fail with non-ascii characters 

- Xamarin.Forms.Core.UnitTests/NavigationUnitTest.cs
- Xamarin.Forms.Core/NavigationPage.cs
This is #1818 but user didn't rebase for 15-5
- [https://bugzilla.xamarin.com/show_bug.cgi?id=31171](https://bugzilla.xamarin.com/show_bug.cgi?id=31171)
- fixes #1429 
None 
None
> [Core] Fixed leaking reference to popped Page in PopAsync()

- Xamarin.Forms.Platform.Android/Renderers/ButtonDrawable.cs
As part of https://github.com/xamarin/Xamarin.Forms/pull/1935, code was added to figure in the padding needed for the background drawable
```csharp
float PaddingLeft
{
get { return (_paddingLeft / 2f); }
set { _paddingLeft = value; }
}
float PaddingTop
{
get { return (_paddingTop / 2f) + _shadowDy; }
set { _paddingTop = value; }
}
```
But this padding was only added for PaddingTop so the background rectangle won't inset properly relative to the ShadowLayer being added if there's a non zero ShadowX value.
This doesn't really come into play with Button as it always has a zero for the shadowDx but I added some APIs to leverage these more with ImageButton. So the screen shots below are from that
Here it is without the padding
Here it is with the padding
```
float PaddingLeft
{
get { return …
```
> [Android] Button PaddingLeft now accounts for ShadowDx

- Xamarin.Forms.Platform.Tizen/Extensions/KeyboardExtensions.cs
- Xamarin.Forms.Platform.Tizen/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
Enable KeyboardFlags and IsSpellCheckEnabled on tizen backend
#1683 [Enhancement] AutoCaptialization support for Entry/Editor 
#1660 [Enhancement] IsSpellCheckEnabled on Entry/Editor.
None
None
> [Tizen] Enhance the Entry renderer of tizen backend

- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/VisualElementiOS.cs
- Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs
When the `BlurEffect` platform-specific is used on iOS, it prevents touch events on the blurred element(s) from working as the `UIVisualEffectView` is laid on top of it; setting `UserInteractionEnabled` to false lets the touch events pass through.
Fixes #2129
N/A
This could technically be an expected side effect on iOS when using the functionality as it currently exists, but probably needs to be documented if a change like this isn't made ([docs here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/platform-specifics/consuming/ios#applying-blur)). There is also an alternative route of adding an additional platform-specific value which updates the `UserInteractionEnabled` value, which we could do if desired, leaving the behavior as it is as the default and updating the …
> [iOS] Allow user interaction with blurred elements

- Xamarin.Forms.Platform.Tizen/Native/EditfieldEntry.cs
- Xamarin.Forms.Platform.Tizen/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
Use EditfileEntry as a default native control of Entry/Editor. The major change in this PR is UI style updates for Entry and Editor. The biggest problem with the existing style is that the boundaries of Entry and Editor are ambigous. Especially for TV, the default TextColor is the same as the default Background Color, so if you do NOT set the color arbitrarily, the text will not be visible. 
The following screenshots show before and after on each devices. 
|  |Before  | After |
|----|----|----|
|**Mobile** |   <p align="center"> <img src = "https://user-images.githubusercontent.com/1029134/37581469-26675ae4-2b8c-11e8-9f95-d37d7f58a5cc.png" width=240 align="middle"> </p> |  <p align="center"> <img src = "https://user-images.githubusercontent.com/1029134/37581480-2f488ef8-2b8c-11e8-9fad-0e08 …
> [Tizen] Change the appearance of Entry/Editor even better

- Xamarin.Forms.Core/BindingExpression.cs
Binding to a Newtonsoft.Json.Linq.JObject with an indexer throws an
AmbiguousMatchException (because the Indexer is overriden). This fixes
the property finding code so it doesn't thorw, but returns the moste
derived indexer.
> [C] avoid exception on overriden indexer

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2130.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2130.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
[Xaml[C]] don't fail if event has same name as ABP
- fixes #2130
/
/
> [Xaml[C]] don't fail if event has same name as ABP

- Xamarin.Forms.Platform.Tizen/Cells/TextCellRenderer.cs
- Xamarin.Forms.Platform.Tizen/Forms.cs
- Xamarin.Forms.Platform.Tizen/Native/MasterDetailPage.cs
- Xamarin.Forms.Platform.Tizen/TizenPlatformServices.cs
This PR includes :
a) Set TargetIdom.Watch to Device in case of Tizen wearable profile
b) Optimize font size and style for TargetIdiom.Watch
NamedSize  | Phone | TV | Wearable 
---| ---| ---|---
Micro | 19 pt | 24 pt | 24 pt
Small | 22 pt| 26 pt | 30 pt
Medium / Default | 25 pt | 28 pt | 32 pt
Large | 31 pt | 84 pt | 36 pt
None
None
`TargetIdiom.Watch` works well with Tizen wearable device (e.g. upcoming Samsung Gear S series)
> [Tizen] Set TargetIdom.Watch for Tizen wearable device

- Xamarin.Forms.Platform.Tizen/Extensions/KeyboardExtensions.cs
- Xamarin.Forms.Platform.Tizen/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
This PR is extension of [#2038](https://github.com/xamarin/Xamarin.Forms/pull/2038) for tizen backend. 
AutoComplete of `ElmSharp.Entry` is enabled if Keyboard is`CustomKeyboard` and has (Suggestions or Spellcheck) flags or Keyboard is not `CustomKeyboard` and (`IsSpellCheckEnabled` and `IsTextPredictionEnabled`) are true. Otherwise, AutoComplete of `ElmSharp.Entry` is off.
| CustomKeyboard | KeyboardFlags. Suggestions | KeyboardFlags. Spellcheck | Entry. IsSpellCheckEnabled | Entry. IsTextPredictionEnabled | Tizen Native Entry AutoComplete |
| --- | --- | --- | --- | --- | --- |
| True | True | True | - | - | **True** |
| True | True | False | - | - | **True** |
| True | False | True | - | - | **True** |
| True | False | False | - | - | **False** |
| False | - | - | True | True | …
> [Tizen] Enable Entry.IsTextPredicationEnabled property

- Xamarin.Forms.Controls/CoreGalleryPages/WebViewCoreGalleryPage.cs
- Xamarin.Forms.Core/IWebViewController.cs
- Xamarin.Forms.Core/Internals/EvalRequested.cs
- Xamarin.Forms.Core/WebView.cs
- Xamarin.Forms.CustomAttributes/TestAttributes.cs
- Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs
- Xamarin.Forms.Platform.GTK/Renderers/WebViewRenderer.cs
- Xamarin.Forms.Platform.MacOS/Renderers/WebViewRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/WebViewRenderer.cs
- Xamarin.Forms.Platform.UAP/WebViewRenderer.cs
- Xamarin.Forms.Platform.WPF/Renderers/WebViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/WebViewRenderer.cs
- docs/Xamarin.Forms.Core/Xamarin.Forms.Internals/EvaluateJavaScriptDelegate.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/IWebViewController.xml
- docs/Xamarin.Forms.Core/Xamarin.Forms/WebView.xml
- docs/Xamarin.Forms.Core/index.xml
fixes #1699 .
Adds the ability to execute and return the result of a passed javascript string from a platform's webview.
Platform support:
Added:
Task<string> WebView.EvaluateJavaScriptAsync
> [Enhancement] Add EvaluateJavaScript method to WebView

- Xamarin.Forms.Core/VisualElement.cs
Fixed incorrect modification of VisualState when the IsFocused property was updated.
[VisualStateManager] "Focused" does not behave correctly. fixes #2157
None.
None.
> [Core] Fix CommonStates.Focused issue

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1864.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.CustomAttributes/TestAttributes.cs
- Xamarin.Forms.Platform.WPF/Renderers/WebViewRenderer.cs
The original issue is Load local html with the following code will throw ArgumentException with message "Relative URIs are not allowed":
This PR fix this issue
fixes #1864
Add WPF in PlatformAffected enum (TestAttributes.cs)
None
> [WPF] Fix bug : Xamarin.Forms WPF load local html throw ArgumentException with message "Relative URIs are not allowed"

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla29247.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60691.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1583_1.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UITests.Shared/Tests/ToolbarItemTests.cs
- Xamarin.Forms.Platform.iOS/Forms.cs
#734 enabled users to open URLs on iOS while properly passing the query strings.
`NSUrl` is not happy when `tel` paths have spaces, however, so it crashes when attempting to parse it. 
Since `tel` paths won't have query strings, using the `AbsoluteUri` to let it encode properly.
Note: this is #1296 pointed at 15-5.
- https://bugzilla.xamarin.com/show_bug.cgi?id=60691
- fixes #1651
None
None
> [iOS] Device.OpenUriAction can open tel URIs with spaces again

- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2171.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2171.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/MarkupExpressionParser.cs
[Xaml[C]] properly parse nested markups
don't stop parsing when the next char is `}`
- fixes #2171
/
/
> [Xaml[C]] properly parse nested markups

- Xamarin.Forms.Core/ItemsView.cs
- Xamarin.Forms.Core/ListView.cs
[C] move ListView code out of ItemsView
/
Added:
```
protected virtual bool ItemsView<TVisual>.ValidateItemTemplate(DataTemplate template);
```
/
> [C] move ListView code out of ItemsView

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla59718.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1801.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/ListView.cs
- Xamarin.Forms.Core/ListViewSelectionMode.cs
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
- Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
- Xamarin.Forms.Platform.UAP/TableViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Added the `ListView.SelectionMode` property and the `ListViewSelectionMode` enum. `ListViewSelectionMode.Single` is the default and retains the previous behavior. When `SelectionMode` is set to `ListViewSelectionMode.None` rows cannot be selected and `ItemSelected` will not be fired. `Tapped` events are still fired and the tapped row will be briefly highlighted during the tap. When  a row has been selected and the property is changed from `Single` to `None` the `SelectedItem` property will be set to `null` and a `ItemSelected` event with a `null` item  will be fired.
**NOTE**: The Xamarin Forms APIs already has an enum named `ListViewSelectionMode` in `Xamarin.Forms.PlatformConfiguration.WindowsSpecific`. This is obviously Windows specific and IIUC it's unrelated to the UWP …
> Added the ListView.SelectionMode property

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2035.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
Simply added a null check. 🤦‍♀️ 
- fixes #2035 
None
None
> [Android] Fix crash when TabbedPage is initialized to a tab > 0

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1801.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ListViewRenderer.cs
This PR is tizen implementation of ListView.SelectionMode (fixes #1801).
It is an addendum to the changes in #2143.
None
None
None
> [Tizen] Support the ListView.SelectionMode property

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1975.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Unsubscribe collection changed handler for short names when disposing ListViewRenderer.
- fixes #1975 
None
None
> [Core] Unsubscribe collection changed handler for short names

- Xamarin.Forms.Core.Design/AttributeTableBuilder.cs
- Xamarin.Forms.Core.Design/NonExclusiveEnumConverter.cs
- Xamarin.Forms.Core.Design/Xamarin.Forms.Core.Design.csproj
This ensures that intellisense in Visual Studio
does not report an error when numeric values are
put in this property instead of the 'string' values
like 'Small', 'Large' etc
NOTE: This might need additional niceing up to ensure that actual invalid values are still marked as invalid.
> [Design] Allow numeric values for FontSize

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45125.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GroupListViewHeaderIndexOutOfRange.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Fixes issue where resetting a Grouped ListView on iOS can result in a crash due to an order of operations issue on the TIL. The best fix as always is to move the data into the container of the Cell itself and thus not have to touch the TIL.
Bug reported on Twitter and modified test 45125 to actually cover this case so we still have coverage.
None
Less crashy crash
> [iOS] Grouped ListView will no longer crash when its ItemSource is cleared

- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
https://developercommunity.visualstudio.com/content/problem/29331/pdbs-are-not-generated-when-building-a-uwp-app-tha.html
Adding debugtype pdbonly or full to the NetStandard library causes the break points to start working in the Control Gallery project.
Reading around I'm still not quite clear whether this is a tooling bug or expected behavior
> add debug type full property to control gallery netstandard library so break points are hit

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43161.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45284.xaml.cs
These tests do not render properly when the linker is enabled on Android. Adding `Preserve` attributes to fix that.
> [UI Tests] Add missing preserve attributes

- Xamarin.Forms.Build.Tasks/CompiledConverters/BindingTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/BoundsTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/ColorTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/ConstraintTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/LayoutOptionsConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/ListStringTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/RDSourceTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/RectangleTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/ThicknessTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/TypeTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledConverters/UriTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/TypeExtension.cs
- Xamarin.Forms.Build.Tasks/CompiledValueProviders/StyleSheetProvider.cs
- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/ModuleDefinitionExtensions.cs
- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Build.Tasks/SetNamescopesAndRegisterNamesVisitor.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/TypeDefinitionExtensions.cs
- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/XamlCTask.cs
[XamlC] cache ImportReference and ImportMethodReference as they're slow
on ns1.4
Project: SmartHotels.Client (`ea3dd73`)
`msbuild /v:diag /t:rebuild`
| **project type** | **Xamarin.Forms version**                            | **XamlC time**    | **Csc time** |
| ---------------- | ---------------------------------------------------- | ----------------- | ------------ |
| `netstandard1.4` | `2.5.0` (pre-netstandard)                            | 3600ms            | 1600ms       |
|                  | `3.0.0-pre2` (some perf work already in)             | 7900ms            | `"`          |
|                  | `https://github.com/xamarin/Xamarin.Forms/pull/2025` | 1900ms            | `"`          |
| `netstandard2.0` | `2.5.0` (pre-netstandard)                            | NS2 not supported …
> [XamlC] cache ImportReference and ImportMethodReference as they're slow

- .nuspec/Xamarin.Forms.targets
Context: https://github.com/jonathanpeppers/XamarinAndroidBuildTimes
After doing a profiling/review of Xamarin.Android project build times, I
noticed that the `XamlC` target was running on every build no matter
what. The project I used was the Forms Master/Detail template from VS
2017 15.6.4.
In my test repo, I was timing the following situations:
1. Completely clean/fresh build
2. Build again, no changes
3. Change C#, build again
4. Change `AndroidResource` XML, build again
In all cases `XamlC` was running, due to the task not having setup
proper inputs and outputs for the MSBuild target. Thinking about it, it
seemed like we could skip `XamlC` as long as the input assembly did not
change, such as case no. 2 or no. 4.
Changes to the `XamlC` target:
- Setup …
> [msbuild] setup inputs and outputs for XamlC target

- Xamarin.Forms.Core.Design/Xamarin.Forms.Core.Design.csproj
The intent is that we can load the toolbox xml file from an
assembly by looking it up by  *exact* name. That means we
should not prefix it with assembly specific info.
Similarly the lookup of the images is *supposed* to be handled
by using *exact* lookups using the format "{platform}.{filename}"
where the filename is the one stored in the toolbox xml file.
This change makes that happen by correctly setting the LogicalName.
> [Designer] Do not prefix the toolbox images

- Xamarin.Forms.Core.UnitTests/VisualStateManagerTests.cs
- Xamarin.Forms.Core/VisualElement.cs
Currently state changes apply in a very specific/narrow way when a property changes. This doesn't allow users to override and add their own states and it also doesn't take into account that you need to reassess all the properties before setting the state. For example when a control becomes enabled the state might need to go to focused and not directly to Normal
Added:
```C#
public partial class VisualElement
{
protected virtual void ChangeVisualState()
```
The only behavior change I can see is if something goes from disabled to enabled the state might go to Focused where as before it would just go to Normal.
> [Core] Centralizing visual state change checks and providing a method to override if users want to add/control state changes themselves

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2394.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WPF/Renderers/ViewRenderer.cs
- Xamarin.Forms.sln
The original issue is  StackLayout VerticalOptions = LayoutOptions.End is not working
This PR fix this issue
fixes #2394
> [WPF] Fix bug : StackLayout VerticalOptions = LayoutOptions.End is not working

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43469.cs
- Xamarin.Forms.Platform.UAP/PlatformUWP.cs
UWP cannot display multiple Alerts at one time, so this change forces new Alerts to wait until the current Alert is finished.
- fixes #2369 
None
None
> [UWP] Only display one alert at a time

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43313.cs
- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
#1235 updates the List's DataContext when the ListView's source is changed. This causes the List to get out of sync temporarily, and a race condition prevented the ScrollTo function from working properly right after the source was changed. This change will force the List to update after the collection changes so it's back in sync before it attempts to scroll.
- fixes #2367
None
None
> [UWP] Prevent crash/unexpected behavior with ListView ScrollTo

- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
UWP ListView's DataContext is being reset on every CollectionChanged event; this change limits those resets to `NotifyCollectionChangedAction.Reset`.
The relevant tests here are `Issue1875` and `Bugzilla57674` - the fix for 57674 (#1235) introduced the crash/regression.
- fixes #2332 
None
None
> [UWP] Only reset ListView DataContext on INotifyCollectionChanged Reset

- .nuspec/Xamarin.Forms.targets
[XamlG] depends on PrepareResourceNames
make sure TargetPath and ManifestResourceNames metadata are assigned
before running XamlG
- fixes #2395
> [XamlG] depends on PrepareResourceNames

- Xamarin.Forms.Platform.Android/GestureManager.cs
Disables long press detection in TapAndPanGestureDetector; the long press firing prevents the scroll from initiating.
- fixes #2324 
None
None
> [Android] Disable long press detection so it doesn't prevent pans in TapAndPanGestureDetector

- Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2339.cs
- Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
Fixed picker on iOS so when nothing gets selected and it's closed that IsFocused gets correctly set back to false
This is a 2.5.1 to 3.0.0 regression so let me know if you want me to retarget this to 3.0.0
fixes #2398
> [iOS] Picker IsFocused not being set back to false if nothing in picker was selected

- Xamarin.Forms.Platform.Tizen/Renderers/SwitchRenderer.cs
This PR is tizen implementation of #1662 and is an addendum to the changes in #1929.
fixes #1662
**- Phone**
Default | OnColor (Red)
---|---
**- Watch**
Default | OnColor (Red)
---|---
**- TV**
-  Default 
- OnColor (Red) 
None
None
None
> [Tizen] Supports Switch.OnColor to tizen

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
[XamlC] Import property typeRefs in BindingCompiler
Tested locally.
- fixes #2518
/
/
> [XamlC] Import property typeRefs in BindingCompiler

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla32898.cs
Try fix failing test 32898, Works fine on emulators and devices , was tested on device with API23 .
> [UITests] Bump delay on UITest 32898

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla33561.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2247.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/TestCases.cs
- Xamarin.Forms.Platform.iOS/Platform.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
If an editing control (Entry, SearchBar, Editor, etc) has focus when pushing a navigation page onto the stack, the ListView's refresh control will not display when IsRefreshing is true. Forcing the current editing control to resign as first responder prevents this issue. 
This changes calls the UIWindow's EndEditing method before pushing a page onto the navigation stack in order to force the editing control to resign as first responder.
- fixes #2247 
None
None
> [iOS] Force iOS to end editing when pushing a navigation page

- Xamarin.Forms.Platform.UAP/MasterDetailControl.cs
When calculating the size of the main page added check the first load after updating the mode `MainDetailControl`
Screencast: https://www.screencast.com/t/P6PJyxT6d
Fixes https://github.com/xamarin/Xamarin.Forms/issues/2228
--
Height of main page calculates correctly
> [UWP] Fixes the reduced height of the main page

- Xamarin.Forms.Platform.MacOS/Renderers/MasterDetailPageRenderer.cs
Fixes issue with hiding master page of `MasterDetailPage`
Fixes https://github.com/xamarin/Xamarin.Forms/issues/2507
None
On desktop `macOS` changes `IsPresentedProperty` have no effect to hide the master page.
> [macOS] Fixes issue with hiding master page of `MasterDetailPage`

- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.Android/_2489CustomRenderer.cs
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.ControlGallery.WindowsUniversal/_2489CustomRenderer.cs
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.ControlGallery.iOS/_2489CustomRenderer.cs
- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Core/Registrar.cs
- Xamarin.Forms.Platform.Android/Properties/AssemblyInfo.cs
- Xamarin.Forms.Platform.iOS/Properties/AssemblyInfo.cs
Renderers are registered in three ways in Xamarin.Forms:
1. Via the `RenderWithAttribute`. This is how core renderers are registered for Android.
2. Via the `ExportRendererAttribute`. This is how core renderers are registered for iOS, UWP, and how users typically register their custom renderers.
3. Via `RegisterHandlerForDefaultRenderer`. This is how core renderers are registered for AppCompat and Fast Renderers.
After we introduced the `RenderWith` model, it became possible for the `Registrar` to return a less specific renderer for a type if a renderer for a base type was registered first.
This change alters the order in which we hunt for the most specific renderer and also ensures that we are registering the proper types with the proper renderers.
It also moves iOS to the `RenderWith` …
> [Core] Improve Renderer registration order

- Xamarin.Forms.Core/Device.cs
The existing message is confusing since the `RuntimePlatform` is not a member of the calling code 
but of `Device`. So use the full member name in the suggested API usage.
Reduces the confusion of:
Followed by:
> Improve warning message, since the calling code isn't on Device

- .nuspec/Xamarin.Forms.DefaultItems.targets
Fixes duplicate CSS files in solution pad in VS Mac.
- Fixes VSTS #606364 - CSS files are duplicated in solution pad
None
> Fix .css files not excluded from default None items

- Xamarin.Forms.Xaml/XamlParser.cs
If the users chooses to change the XAML namespace prefix from x to something else (which is totally valid still in XML and XAML (WPF/UWP) land), XF will fail to parse the XAML attributes correctly.
This should not be the case since the XML infoset is the same in either case.
Fixes #2560
> Do not assume XAML namespace prefix in use

- Xamarin.Forms.Platform.UAP/SearchBarRenderer.cs
Modifies the text of the SearchBar element if it does not match the query.
Fixes #2439
--
What will be typed in the search bar will be in the query regardless of the speed of typing.
> [UWP] Fixes the search bar query, when you type text quickly

- Xamarin.Forms.ControlGallery.Android/AttachedStateEffectRenderer.cs
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.WindowsUniversal/AttachedStateEffectRenderer.cs
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.ControlGallery.iOS/AttachedStateEffectRenderer.cs
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Effects/AttachedStateEffect.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Effects/AttachedStateEffectList.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2399.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
- Xamarin.Forms.Platform.UAP/ViewToRendererConverter.cs
- Xamarin.Forms.Platform.UAP/VisualElementPackager.cs
- Xamarin.Forms.Platform.iOS/VisualElementPackager.cs
Added code to VisualElementPackager to dispose of children. Renderers typically create cycle references due to watching the events of the Elements they represent
Renderer => HasElement => Wires it self to events that element owns => Element has Renderer
This causes the Renderers to not finalize because there's a reference cycle
When a ListViewRenderer is disposed nothing was trickling down that dispose operation to the cells/renderers inside the ListView.   Code was added to  Cleanup all the cells of a listview as well as disposing of children in UWP's version of a VisualElementPackager
- fixes #2399
None
Dispose is now going to be called on Renderers where it wasn't being called before. If users were  depending on this or have code in their dispose that's wrong then this change will …
> [iOS, UWP] Explicitly dispose of children renderers that belong to Packager

- Xamarin.Forms.Platform.UAP/CarouselPageRenderer.cs
In tracker of `CarouselPageRenderer` a `Container` is defined
Fixes #2127
None
When you set the `CarouselPage` properties, will no longer throw NRE exception
> [UWP] Fixed setting of properties to the CarouselPage

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1729.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Slider.cs
- Xamarin.Forms.Platform.iOS/Renderers/SliderRenderer.cs
This PR adds support for tapping a slider on iOS to set the value which is not natively support by a standard `UISlider`. This new behaviour is triggered by setting a new iOS specific property `UpdateOnTap` to `true`.
- fixes #1729 
Added:
- bool Slider.UpdateOnTap { get; set; } //iOS specific Bindable Property
> Adding support for tapping on iOS Slider to set value

- Xamarin.Forms.Platform.UAP/AlertDialog.cs
- Xamarin.Forms.Platform.UAP/PlatformUWP.cs
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
Activating vertical scrolling in the Alert dialog box.
Screencast: http://recordit.co/f4TrhdqvEd
Fixes #2355
--
UWP Alert box now uses `AlertDialog` subclass of `ContentDialog`.
> [UWP] Activating vertical scrolling in the Alert dialog box.

- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Build.Tasks/SetNamescopesAndRegisterNamesVisitor.cs
- Xamarin.Forms.Core/ConstraintExpression.cs
- Xamarin.Forms.Core/Element.cs
- Xamarin.Forms.Core/Internals/INameScope.cs
- Xamarin.Forms.Core/Internals/INamescopeProvider.cs
- Xamarin.Forms.Core/Internals/NameScope.cs
- Xamarin.Forms.Core/NameScopeExtensions.cs
- Xamarin.Forms.Core/ReferenceTypeConverter.cs
- Xamarin.Forms.Core/Xaml/IReferenceProvider.cs
- Xamarin.Forms.Xaml.UnitTests/DynamicResource.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2517.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/NameScopeTests.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- Xamarin.Forms.Xaml/MarkupExtensions/ReferenceExtension.cs
- Xamarin.Forms.Xaml/NamescopingVisitor.cs
- Xamarin.Forms.Xaml/Properties/AssemblyInfo.cs
- Xamarin.Forms.Xaml/RegisterXNamesVisitor.cs
- Xamarin.Forms.Xaml/XamlServiceProvider.cs
- turn Element.FindByName() public
- reduce the amount of time (both Xaml and XamlC) we need to actually set the NameScope on an object
- add a IReferenceProvider
- allows custom markups replicating x:Reference
- more efficient x:Reference
/
Added
```
public object Element.FindByName(string name);
public interface Xamarin.Forms.Xaml.IReferenceProvider
{
object FindByName(string name);
}
```
/
> Namescope enhancements

- Xamarin.Forms.Build.Tasks/CompiledConverters/ColorTypeConverter.cs
- Xamarin.Forms.Core/ColorTypeConverter.cs
[CSS] lightgray is spelled lightgrey in CSS world
- fixes #2596
/
/
> [CSS] lightgray is spelled lightgrey in CSS world

- Xamarin.Flex/Flex.cs
- Xamarin.Forms.Core.UnitTests/FlexLayoutTests.cs
- Xamarin.Forms.Core/FlexLayout.cs
[Flex] do not layout invisible children
- fixes #2593
/
children with `IsVisible` `false` won't take space in a flex layout
> [Flex] do not layout invisible children

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43469.cs
- Xamarin.Forms.Platform.UAP/PlatformUWP.cs
fixes #2607
Added ConfigureAwait(false) to the process waiting for the dialog to close so as to not cause a deadlock with the await in the while loop above it
```C#
options.SetResult(await s_currentAlert.ConfigureAwait(false));
```
Also slightly modified the Bugzilla test that started this all to include the case which was causing the deadlocks on UWP
None
> [UWP] Deadlock if you rapid fire alerts  fixes #2607

- Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
Fixes App crash when clicking `undo`, `cut`, `delete` on Picker
Screenshot: https://prnt.sc/jbwlje
Fixes #2465
None
- disabled `paste`, `delete` and `cut` action on the Picker
- in the text box of Picker, you can only `select` and `copy` text
- clear the undo stack when typing with a keyboard
> [iOS] Fixes App crash when clicking "undo", "cut", "delete" on Picker

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GitHub2598.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UnitTests/NotifyCollectionChangedEventArgsExtensionsTests.cs
- Xamarin.Forms.Core/Internals/NotifyCollectionChangedEventArgsExtensions.cs
Fixes replace action in `NotifyCollectionChangedEventArgsExtensions` class
**Screencasts**
UWP: http://recordit.co/WaOGnn0rON
iOS: http://recordit.co/Y0nEJSuxvd
Fixes #2598 
Fixes #2585
/
Fixed replacement of items in`NotifyCollection'
> [Core] Fixes replace action in NotifyCollectionChangedEventArgsExtensions

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1734.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/ILineHeightElement.cs
- Xamarin.Forms.Core/Label.cs
- Xamarin.Forms.Core/LineHeightElement.cs
- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
- Xamarin.Forms.Core/Span.cs
- Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/FormattedStringExtensions.cs
- Xamarin.Forms.Platform.Android/Renderers/LabelRenderer.cs
- Xamarin.Forms.Platform.UAP/LabelRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/FormattedStringExtensions.cs
- Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
Fixes #1734 by adding LineHeight property to Label and Span. The unit of LineHeight is relative to the original line height or font size. Also know as *multiplier* on iOS and Android. For UWP the actual line height will be calculated as a multiple of the font size.
Setting LineHeight on Span doesn't work on UWP which doesn't
seem to support that on its `Run` class.
On Android the separate LineHeight on span only has effect if
the text has linebreaks within the string. Then it's possible
to set different line heights for individual lines using Span.
If the lines are automatically split using WordWrap for instance,
it seems like Android will use the LineHeight set on the last Span.
Added:
- double Label.LineHeight { get; set; } //Bindable Property specifying the relative line height.
- …
> Adding line height to Label and Span

- Xamarin.Forms.Platform.UAP/WindowsBasePlatformServices.cs
Check `HasThreadAccess` instead checking `LockApplicationHost` on `IsInvokeRequired`
Fixes #2327
None
`IsInvokeRequired` return true if `_dispatcher.HasThreadAccess` is false
> [UWP] Fix crashes animation in the thread pool

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1760.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2595.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ScrollViewContainer.cs
ScrollView on Android does not automatically trigger a re-layout when its content changes; in some circumstances, this can cause incorrect or out-of-date layouts.
This change triggers a re-layout on the ScrollViewContainer when the content of the ScrollViewContainer is a Layout and that content's layout changes.
- fixes #1760 
- fixes #2595 
- fixes #1332 
None
None
> [Android] Force ScrollView layout when changing ContentView content

- Xamarin.Forms.Platform.UAP/ScrollViewRenderer.cs
- Added null check on ScrollView Element in UWP Scroll View Renderer
- unsubscribe from ScrollToRequested in dispose to improve cleanup
fixes #2336
None
> [UWP] NRE when checking IsInNativeLayout during OnScrollToRequested

- Xamarin.Forms.Core.UnitTests/MenuItemTests.cs
- Xamarin.Forms.Core/Accelerator.cs
if the accelerator text is equal to the `separator` (+) then his keys equals his text
Fixes #1639
/
`Accelerator` will support `+` key
> [Core] Fixes getting the accelerator keys, if the key is equal to the separator

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla47923.cs
- Xamarin.Forms.Platform.Android/Cells/BaseCellView.cs
- Xamarin.Forms.Platform.Android/Extensions/ImageViewExtensions.cs
- Xamarin.Forms.Platform.Android/ResourceManager.cs
- Change drawables to pull via appcompat 
- Change ImageCell to use ImageViewExtensions so that it benefits and just reuses the same image loading code.  Currently ImageCell isn't using the code that will reuse drawables and thus it will crash if too many rows are created with the same drawable
Fixes  #1872
Fixes  #1872
> [Android] Fix drawables to load using AppCompat and change ImageCell to use standard image loading code

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GitHub1702.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/CoreGalleryPages/ButtonCoreGalleryPage.cs
- Xamarin.Forms.Core/Button.cs
- Xamarin.Forms.CustomAttributes/TestAttributes.cs
- Xamarin.Forms.Platform.Android/AppCompat/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.UAP/ButtonRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ButtonRenderer.cs
Added padding to Button control
**Screencasts**
UWP: http://recordit.co/RO6d9sqjNR
Android: http://recordit.co/mcJqcuVA65
iOS: http://recordit.co/3MjGiRf06X
Fixes #1702
Added:
Thickness Padding { get; set; } //Bindable Property in Button
User will be able to set Padding for Button.
> [iOS, Android, UWP] Added padding to Button control

- Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs
This is a fix for issue #2634. On Android, when no BorderColor is set, a white border is always drawn around a Frame. That is a regression bug introduced in 3.0.0
fixes #2634 
None
Android only: no border will be drawn around a frame if BorderColor is not set or is set to Color.Default. Previously, a white border was drawn
Android FrameRenderer doesn't seem to have any tests.
> [Android] Fix issue #2634. Draw no border if no BorderColor is set

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2625.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2625.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UnitTests/VisualStateManagerTests.cs
- Xamarin.Forms.Core/VisualStateManager.cs
- Xamarin.Forms.Xaml.UnitTests/VisualStateManagerTests.xaml
- Xamarin.Forms.Xaml.UnitTests/VisualStateManagerTests.xaml.cs
Previously the setting of the initial VisualState for a VisualElement happened when the VisualStateGroupList was set; however, this means an empty VisualStateGroupList when the list is initially created with the DefaultValueCreator. 
This change adds monitoring to the VisualStateGroupList to allow the VisualElement to update its current state as new states are added, which means that any default states (e.g. "Normal" or "Disabled") are immediately set.
- fixes #2625 
None
None
> Call ChangeVisualState when new states are added

- Xamarin.Forms.Platform.Android/VisualElementPackager.cs
There can be a NullReferenceException when accessing the field _childPackagers because it is initialized in AddChild and not in ctor.
Add null-check.
None that I am aware of
None
None
> [Android] Add null-check to VisualElementPackager.RemoveChild

- Xamarin.Forms.Controls/GalleryPages/MapGallery.cs
- Xamarin.Forms.Maps.Android/MapRenderer.cs
- Xamarin.Forms.Maps.iOS/MapRenderer.cs
Map renderers listen for the PropertyChanged event on each Pin in Map.Pins to update Label, Address, and Position of native pins when changed in cross-platform code.
- Fixes #2121
/
> [Maps] Handle Pin.PropertyChanged events

- Xamarin.Forms.Controls/GalleryPages/MapGallery.cs
- Xamarin.Forms.Maps.Android/MapRenderer.cs
Fix the Android MapRenderer so markers are found and removed from the GoogleMap when Pins are removed from the Map.
fixes #2411
> [Android Maps] Fix pins not being removed

- Xamarin.Forms.Platform.MacOS/FormsApplicationDelegate.cs
On `Mac` clearing main menu affects only menu items created in code.
**Screencast:** http://recordit.co/C4T494i8QL
Fixes #2659 
/
When launch application the menu created in `storyboard` is not deleted
> [Mac] Fix deleting main menu items

- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1942.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Platform.cs
For cases when 
- there's a DefaultRenderer in the visual tree
- the child of that DefaultRenderer element being clicked on is one of the Android elements that fakes an OnTouchEvent to short circuit 
- the user manually attaches a Touch Listener to the Default Renderer
This change will cause the Touch Event to correctly propagate to that touch listener
fixes #1942
This shouldn't cause any  behavioral changes. The only path I can follow where a change in behavior would happen is  
- someone setup the scenario above but didn't realize their touch listener wasn't called
- they were returning TRUE from the listener
- They are then expecting OnTouchEvent to still be called
But even in normal Xamarin Android world if you return true from an attached TouchListener the OnTouchEvent of that view …
> [Android] Added a custom call for calling any manually set OnTouchListeners

- Xamarin.Forms.Core/Performance.cs
- Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
- Xamarin.Forms.Platform.Android/Cells/CellRenderer.cs
- Xamarin.Forms.Platform.Android/Cells/ViewCellRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs
- Xamarin.Forms.Platform.Android/Platform.cs
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
- Xamarin.Forms.Platform.Android/VisualElementPackager.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
- Xamarin.Forms.Platform.Android/VisualElementTracker.cs
- Xamarin.Forms.Platform.iOS/Cells/CellRenderer.cs
- Xamarin.Forms.Platform.iOS/Cells/ViewCellRenderer.cs
- Xamarin.Forms.Platform.iOS/Platform.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.iOS/VisualElementPackager.cs
- Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs
- Xamarin.Forms.Platform.iOS/VisualElementTracker.cs
Unless there is a `PerformanceProvider`, we should not waste time creating a reference for the tracker.
- N/A
Added parameter to internal `Performance.Start` method
None
> [Core] Remove Guid.NewGuid() calls from performance tracking

- Xamarin.Forms.Controls/TestCases.cs
The SearchBar on the TestCases page is not visible due to narrow height in Tizen
It was set 42 to show correctly in Android N So change to MinimumHeightRequest from HeightRequest
Bug
Fixed
None
None
> Fix ControlsGallery SearchBar HeightRequest issue

- Xamarin.Forms.Platform.Tizen/Native/Label.cs
- Xamarin.Forms.Platform.Tizen/Native/Span.cs
- Xamarin.Forms.Platform.Tizen/Renderers/LabelRenderer.cs
[Tizen] Support LineHeight on Label,Span
https://github.com/xamarin/Xamarin.Forms/issues/1734
None
None
> [Tizen] Support LineHeight on Label,Span

- Xamarin.Forms.Core/BindingExpression.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2632.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2632.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[Binding] avoid AmbiguousMatchException on redefined property
this bug appeared with the `netstandard20` migration
- fixes #2632
/
/
> [Binding] avoid AmbiguousME on redefined property

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2681.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
moved UpdateLayout call in ListViewRenderer into BeginInvokeOnMainThread otherwise UWP was creating a duplicate Cell and causing a deadlock in some cases
I found that the change here https://github.com/xamarin/Xamarin.Forms/pull/2436 was causing an extra non visible CellControl to generate.
This was causing two different cell controls to contain the same Label which was then causing a ping pong effect of Measurement Invalidations.
This exception wasn't happening on master because of this addition of this call
https://github.com/xamarin/Xamarin.Forms/pull/2515
I'm not really sure why having that was short circuiting the Measurement deadlocks. Either way it's not great to have 2 CellControls for one label.   It would only create an extra CellControl for the first element not any additional …
> [UWP] moved UpdateLayout call in ListViewRenderer into BeginInvokeOnMainThread

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2653.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/VisualElementPackager.cs
Changes were made in this PR https://github.com/xamarin/Xamarin.Forms/pull/1196 so that less calls were made to set the ZIndex on UWP. This only took into account when RaiseUp and Down were called and didn't factor in when a child element is inserted out of order
Fixes #2653
None
> fixes #2653 on uwp set the Z Index when children aren't added to the end of the stack

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1667.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/Entry.cs
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Entry.cs
- Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/FormsEditText.cs
- Xamarin.Forms.Platform.UAP/EntryRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
This PR adds support for getting and setting
caret position on a text Entry on iOS, Android and UWP.
Also adding support for setting CursorColor but only for iOS since
it seems unsupported on UWP and couldn't figure out how to do it
on Android in an not too complicated manner.
- Fixes #1667 except for cursor color functionality on UWP and Android.
Added:
- `int Entry.CursorPosition { get; set; } //Bindable Property`
- `int Entry.SelectionLength { get; set; } // Bindable Property`
- `Color Entry<iOS>.CursorColor { get; set; } // iOS specific Bindable Property`
> Controlling Caret position on iOS,Android,UWP and color on iOS

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1583_1.cs
This test is occasionally not being navigated to on iOS 10 so I delayed the setting of the web view source and added a label to help visually.
> delay setting of source to help verify ui test block

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla56771.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1875.cs
- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
`ItemsSource` wrapped in an `ObservableCollection`
Added processing for adding and removing items.
Screencast: https://www.screencast.com/t/LrPoEiM8a6v0
Fixes #2485
--
Correct Items shown when the collection is changed
> [UWP] Fixed sync of ListView items with ListViewProxy

- .nuspec/Xamarin.Forms.targets
- Xamarin.Forms.Build.Tasks/XamlGTask.cs
- Xamarin.Forms.Xaml.UnitTests/MSBuild/DummyBuildEngine.cs
- Xamarin.Forms.Xaml.UnitTests/MSBuild/MSBuildTests.cs
- Xamarin.Forms.Xaml.UnitTests/MSBuild/MSBuildXmlExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml.UnitTests/XamlgFileLockTests.cs
- Xamarin.Forms.Xaml.UnitTests/XamlgTests.cs
- Xamarin.Forms.Xaml.UnitTests/app.config
- Xamarin.Forms.Xaml.UnitTests/packages.config
- Xamarin.Forms.Xaml.Xamlg/Xamlg.cs
Context: https://github.com/xamarin/Xamarin.Forms/pull/2230
The main performance problem with the collection of MSBuild targets in
`Xamarin.Forms.targets` is they don't build incrementally. I addressed
this with `XamlC` using a "stamp" file; however, it is not quite so
easy to setup the same thing with `XamlG`.
They way "incremental" builds are setup in MSBuild, is by specifying
the `Inputs` and `Outputs` of a `<Target />`. MSBuild will partially
build a target when some outputs are not up to date, and skip it
entirely if they are all up to date.
The best docs I can find on MSBuild incremental builds:
https://msdn.microsoft.com/en-us/library/ms171483.aspx
Unfortunately a few things had to happen to make this work for
`XamlG`:
- Define a new target `_FindXamlGFiles` that is invoked before …
> [XamlG] builds incrementally, add MSBuild integration tests

- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Page.cs
IF we disabe UseSafeArea and then reaenable it it wasn't reapplying the safe área insets. 
- Helps with fix for #1584 
None
When Enable safearea it will always set the SafeAreaInsets
> [iOS] Fix reapply of safe insets

- Xamarin.Forms.Core.UnitTests/BindablePropertyUnitTests.cs
- Xamarin.Forms.Core/BindableProperty.cs
According to the [documentation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/bindable-properties), when no default value is provided in a call to BindableProperty.Create(), it will use the default value of the property type. However, this is not how it behaves for value types. When no explicit default value is provided for a value type property, an exception will be thrown.
When a BindableProperty is created for a value type and the default value is null, the default value will be set to the default for the type.
No API changes
BindableProperty.Create() will no longer throw an exception when no default value is provided and the property type is a value type. The default value will be the default value for the property type.
> Support default value for value types in BindableProperty

- Xamarin.Forms.Controls/ControlGalleryPages/AutomationPropertiesGallery.cs
- Xamarin.Forms.Platform.UAP/LabelRenderer.cs
- Xamarin.Forms.Platform.iOS/ViewRenderer.cs
We expect screen readers to be able to read content by default. On iOS and UWP, this was not true for non-interactive elements such as Labels.
We create iOS views programmatically, in which case the `IsAccessibilityElement` value defaults to `false`. We expected it to default to `true`, as it states in the documentation, but this apparently is only the case when using storyboards. We are now explicitly setting `IsAccessibilityElement` to true for all controls.
This functionality was originally working, but it was thwarted by a change made later for UI testing. Reverting that change for now until we can find a better alternative.
- fixes #1946
None
- UWP UI Tests will probably fail
- Anyone explicitly setting `UIView.IsAccessibilityElement` to `false` in custom renderers should ensure they …
> [UWP,iOS] Enable screen readers to read non-interactive elements

- Xamarin.Forms.Controls/ControlGalleryPages/ToolbarItems.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
Don't redraw the toolbaritems if the available size didn't change,. Seems LayoutSubviews is called more times on IOS10 and our code was setting the frame of the buttons after they were layout with the correct size.
- fixes #2798 
None
> [iOS] Fix secondary toolbaritems

- Xamarin.Forms.Platform.Android/Cells/ViewCellRenderer.cs
The constructor for *GestureDetector* that doesn't take Context is going to be deprecated. This switches to a constructor that won't be
> Use GestureDetector constructor that takes in Context since the one without it is going to be deprecated

- Xamarin.Forms.Platform.GTK/Controls/EntryWrapper.cs
- Xamarin.Forms.Platform.GTK/FormsWindow.cs
Fixed wrong state in GTK Entry using Placeholder and Text.
- fixes #2810
> [GTK] Fixed Issue 2810: Wrong state in GTK Entry using Placeholder and Text

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2929.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
Check for null `ItemsSource` before trying to access it in `ReloadData` and `UpdateGrouping`.
- fixes #2929 
None
None
> Check ItemsSource for null in ListViewRenderer

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1323.cs
- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.Android/Cells/BaseCellView.cs
* fixed unit test to verify crash didn't happen
* added try catch to BaseCellView and TabbedPageRenderer when image can't load
> [Android] Fixes crash with Tabbed Page when image for icon doesn't exist

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2767.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/GridCalc.cs
Added support 0* RowDefinition in Grid
- fixes #2767 
/
`RowDefinition` "0*" have zero height
> [Core] Fixes '0*' RowDefinition/ColumnDefinition in Grid

- Xamarin.Forms.Core.UnitTests/FlexLayoutTests.cs
- Xamarin.Forms.Core/FlexLayout.cs
[Flex] Make sure layout is invalidated on time
When a BP changes, the BP value changes, the propertyChanged event is
fired, then the propertyChanged delegate is executed.
As the invalidation was done in the event, and setting the flexitem
property was done in the delegate, the invalidation, and relayout, was
executed with an out-of-date flexitem.
With this change, we invalidate the child size, and that'll bubble up to
invalidate the layout, as part of the property changed delegate
- fixes #2821
/
/
> [Flex] Make sure layout is invalidated on time

- Xamarin.Forms.Platform.Tizen/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ImageRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/LabelRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ProgressBarRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs
- Xamarin.Forms.Platform.Tizen/TizenPlatformServices.cs
Remove unnecessary property for checking whether tizen specific is available or not. Since Xamarin.Forms 3.0 (support tizen backend) this is no longer necessary.
None
None
None
> [Tizen] Remove legacy tizen specific available condition

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GestureBubblingTests.cs
- Xamarin.Forms.Platform.iOS/Renderers/SliderRenderer.cs
Sets UpdateOnTap to true for the Slider in the gesture bubbling tests (on iOS).
Also fixes a bug where the initial setting for UpdateOnTap is ignored by the SliderRenderer.
> Use UpdateOnTap setting for Slider to fix broken gesture bubbling test

- Xamarin.Forms.Core/PlatformConfiguration/TizenSpecific/StyleValues.cs
- Xamarin.Forms.Platform.Tizen/Native/Button.cs
- Xamarin.Forms.Platform.Tizen/Native/Watch/WatchButton.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ButtonRenderer.cs
This PR  make certain that various button styles work well on watch devices. It also includes fixes about determining the button size correctly if button has icon. 
In order to change button theme style, user can just use something like -
```cs
button.On<Tizen>().SetStyle(ButtonStyle.Circle);
```
The size of the button is determined correctly across target idioms. 
Added:
Xamarin.Forms.PlatformConfiguration.TizenSpecific
- string ButtonStyle.Text; 
- string ButtonStyle.SelectMode; 
None.
> [Tizen] Ensures various button styles work well on watch

- Xamarin.Forms.Platform.WPF/Renderers/ImageRenderer.cs
Fixed WPF Build removing C# "pattern matching".
> [WPF] Fixed Build: Remove "pattern matching" from ImageRenderer

- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Effects/AttachedStateEffectLabel.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Effects/AttachedStateEffectList.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2829.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
Currently _DisposeCells_ only iterates using GetChildAt which will only return visible cells. When you would scroll a listview this would cause a cell to not be visible and would thus return NULL for GetChildAt but the ConditionalFocusLayout would still exist in memory. This fix keeps track of created Layouts in an internal list to ensure that all resources get disposed of
I can't say for sure if this is the only cause of https://github.com/xamarin/Xamarin.Forms/issues/2829 but it definitely fixes a case where Dispose wasn't being called for a given cell.  
fixes #2829
> [Android] Keep track of created ConditionalFocusLayouts so they can all be disposed of

- Xamarin.Forms.Platform.Android/Extensions/FlowDirectionExtensions.cs
- Xamarin.Forms.Platform.Android/Renderers/SearchBarRenderer.cs
For non RTL we need to set the vertical gravity to center on the Search Bar so it centers correctly.
Caused by https://github.com/xamarin/Xamarin.Forms/pull/1222.
fixes #2936
> [Android]  Set vertical center on gravity for Search Bar

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2653.cs
- Xamarin.Forms.Platform.UAP/VisualElementPackager.cs
* When elements are first added to the visual tree don't set the Z-Index https://github.com/xamarin/Xamarin.Forms/issues/2943 and https://bugzilla.xamarin.com/show_bug.cgi?id=60143
* When elements are re-orderered call Ensure Z Index to assert the ordering (https://bugzilla.xamarin.com/show_bug.cgi?id=60143)
* When elements are added/inserted after initial load make sure to reset the Z-Index to represent newly added children (https://github.com/xamarin/Xamarin.Forms/issues/2653)
https://bugzilla.xamarin.com/show_bug.cgi?id=60143
fixes #2943
fixes #2653
> [UWP] Ignore setting the Z Index on initial load

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1583_1.cs
- Xamarin.Forms.Platform.iOS/Renderers/WebViewRenderer.cs
In WebViewRenderer.LoadUrl, the given string was encoded regardless how the url was structured or if it was already encoded. This commit fixes it by parsing the string as System.Uri and using IdnHost and the existing implicit operator from Uri to NSUrl which has the correct encoding mechanism.
The following URI structures were not accessible but are again after these changes:
1. Fragments (hashes) e.g. http://example.com/page#anchor
2. Queries with encoding e.g. https://www.google.com/search?q=http%3A%2F%2Fmicrosoft.com
fixes #2736
None
The app will not crash when a host name with unicode characters is navigated.
>  [iOS] Correct encoding in WebViewRenderer.LoadUrl

- Xamarin.Forms.Core.UnitTests/BindingUnitTests.cs
- Xamarin.Forms.Core.UnitTests/TypedBindingUnitTests.cs
- Xamarin.Forms.Core/Binding.cs
- Xamarin.Forms.Core/BindingBase.cs
- Xamarin.Forms.Core/BindingExpression.cs
- Xamarin.Forms.Core/TypedBinding.cs
- Xamarin.Forms.Xaml/MarkupExtensions/BindingExtension.cs
[Binding] FallbackValue and TargetNullValue
Changes applies to
- Bindings
- CompiledBindings
- {Binding} markup extension
- fixes #1803
**Added**
```csharp
public object BindingBase.FallbackValue { get; set; }
public object BindingBase.TargetNullValue { get; set; }
```
Prior to this, when a path (or part of the path) wasn't resolved, the `BindableProperty.DefaultValue` was applied.
Now, if the `Binding.FallbackValue` is non-null, the `FallbackValue` is used.
Converters are never applied.
Prior to this, a source value of `null` was eventually converted (if a converter was present), eventually formatted (if stringFormat was defined), and the result was then applied.
Now, the value is eventually converted, and if it's still null after the conversion, the TargetNullValue (if non-null) is …
> [Binding] FallbackValue and TargetNullValue

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2763.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/Layout.cs
Update `IPaddingElement.OnPaddingPropertyChanged` on Layout to inform change of measure
Size of Layout could be changed by Padding
https://github.com/xamarin/Xamarin.Forms/blob/882bf07917bea57b93d0d9becd768dcab739c26f/Xamarin.Forms.Core/Layout.cs#L129-L134
fixes 2763
As is
Fixed
None
None
> [Core] Fix Padding of Layout update Issue

- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
Fix listview not rendering when ItemsSource is initially null
When ItemsSource is initially null, the DataContext is not set, and it is never set when the ItemsSource property is set later. This fix will call ReloadData() when the ItemsSource property is changed on the XF ListView control.
No bug reported yet
> [UWP] Fix listview not rendering when ItemsSource is initially null

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2653.cs
https://github.com/xamarin/Xamarin.Forms/issues/2989
A layering bug that's been around for awhile was revealed by the addition of some UWP tests. Ignore test on Android for now until issue is resolved
> [Android] ignore layering test on android

- Xamarin.Forms.Platform.Tizen/FormsApplication.cs
- Xamarin.Forms.Platform.Tizen/LightweightPlatform.cs
- Xamarin.Forms.Platform.Tizen/Platform.cs
This PR is about adjusting `Platform` creation timing to ensure native contols can be created before Page is set. 
Fixed an issue where ControlGallery would not run after #2772 was merged.
None
You can create a native control (via renderer) before the Page is set, just like what ControlGallery currently does.
> [Tizen] Adjust the platform creation timing

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2499.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.Windows.UITests/WindowsTestBase.cs
- Xamarin.Forms.Core/Picker.cs
**This is a retargeted version of #2833. See discussion, and reviews, over there**
In the `UpdateSelectedItem` sends the real `selectedIndex`
- Fixes #2499
- Fixes #2815
- closes #2833
None
> [C] Fixes setting to Null Binding Context in Picker

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1931.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
The Android ScrollViewRenderer is missing a check against double disposal, and in circumstances where Dispose is called twice it throws a NullReferenceException.
This change adds a guard against double disposal, checks the Tracker and Container for null before disposing, only calls SetElement during deterministic disposal, and calls the base Dispose method in the correct order.
- fixes #1931 
- fixes #2011
None
- Android
None
> [Android] Make ScrollViewRenderer handle double disposal

- Xamarin.Forms.sln
XFCorePostProcessor  was added with the same GUID as Xamarin.Forms.Xaml.Design so VS on Windows kept reassigning it and then adding it to all the build configurations. This commit gives it its own GUID and keeps it removed from all build configurations
> Give XFCorePostProcessor a different GUID than Xamarin.Forms.Xaml.Design

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1799.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Removing the refresh indicator when IsPullToRefreshEnabled is set to false and the ListView has no data on iOS causes the list to move enough to trigger an infinite loop in the Scrolled override. This change averts the loop.
- #1799
None
- iOS
None
> Avoid infinite loop when removing refresh indicator on iOS

- Xamarin.Forms.Core.UnitTests/VisualStateManagerTests.cs
- Xamarin.Forms.Core/VisualStateManager.cs
Significantly reduce the performance impact of the `Validate` method on `VisualStateGroupList`.
- fixes #3033 
None
None
> Fine-tune the performance of VisualStateGroupList.Validate

- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Maps/Xamarin.Forms.Maps.csproj
Just added
```
+	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
+		<DebugType>full</DebugType>
+	</PropertyGroup>
```
to shared csproj files as this is needed for UWP to be able to generate pdb files in the right places and hit break points
> [UWP] add Debug Type full to Debug property groups so UWP can hit breakpoints

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/AddingMultipleItemsListView.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla56771.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GroupListViewHeaderIndexOutOfRange.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Helpers/UITestHelper.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1439.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1875.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1975.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2929.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3008.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3019.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
* fixed code to only call reload data once
https://github.com/xamarin/Xamarin.Forms/pull/3023/files#r194827139
* if itemsource is set to null then just null out CVS otherwise it'll cause a COM Exception
* added ListView Categories to some tests to more easily run targeted tests against UWP
* fixed a couple UWP tests that weren't passing
* Items added to Source collections weren't being synced correctly to internal collection
fixes #3008
fixes #3009
fixes #3018
fixes #3019 
fixes #2996
> [UWP] Fixed code to only call ReloadData once, set CVS to null, and add correct items to internal source

- .nuspec/Xamarin.Forms.targets
- Xamarin.Forms.Xaml.UnitTests/MSBuild/MSBuildTests.cs
Some links about design-time builds:
- https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md
- https://daveaglick.com/posts/running-a-design-time-build-with-msbuild-apis
In Visual Studio 2017 (Windows), a "design-time" build is what drives
Intellisense in cases such as using `x:Name` in XAML (or
`Resource.designer.cs` in a plain Xamarin.Android app). Improving our
"design-time" build speed will improve general performance in the IDE
such as project load and how long Intellisense takes to update. Since
XamlC is not needed during a design-time build, it is an "easy-win" to
just disable it. XamlC can take a bit of time for projects with a lot
of XAML.
This might also help with: https://github.com/xamarin/Xamarin.Forms/issues/3004
Although we should probably not do …
> [XamlC] should not run during Design-Time Builds

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2837.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
Android
If there was only 1 element on the stack the the índex was trying to remove a element of out bounds. 
IOS
Was removing the top and only controller
- fixes #2837 
None
Should not crash when removing the previous page when appearing on Android
> [Android,IOS] Fix inserting page and popping current

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2499.cs
- Xamarin.Forms.Platform.Android/AppCompat/PickerRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/PickerRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
SelectedIndex being a BP, setting it's value might be delayed, and as
both ios and android PickerRenderer do not update on individual property
changes, but have a single UpdatePicker method, some properties might be
out-of-date, causing a crash.
This doesn't attemps to fix the renderers, but only prevents a crash to
happen.
/
- iOS
- Android
/
> Fix broken 2499 test

- Xamarin.Forms.Core.UnitTests/RelativeLayoutTests.cs
- Xamarin.Forms.Core/BoundsConstraint.cs
- Xamarin.Forms.Core/RelativeLayout.cs
[C] Allow change constraint before parenting
Allow a constraint to be changed when the view is not parented yet.
- fixes #2169
/
/
/
> [C] Allow change constraint before parenting

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2993.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
When the Navigation Bar is on the bottom for Android the Navigation Renderer Content Area needs its bottom padding set so content doesn't show up beneath it
fixes #2993
- Android
> [Android] Set bottom content padding on bottom of Navigation Container when bottom tab is present

- Xamarin.Forms.Platform.Tizen/Extensions/LayoutExtensions.cs
- Xamarin.Forms.Platform.Tizen/NativeViewWrapper.cs
- Xamarin.Forms.Platform.Tizen/Properties/AssemblyInfo.cs
- Xamarin.Forms.Platform.Tizen/Renderers/NativeViewWrapperRenderer.cs
`EvasObjectWrapper` is renamed to `NativeViewWrapper` for the sake of consistency. It also changed to inhert `ViewRenderer` from `VisualElementRenderer`.
None
None
- Tizen
None
> [Tizen] Rename EvasObjectWrapper to NativeViewWrapper

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/BindablePropertiesAccessModifiers.xaml
- Xamarin.Forms.Xaml.UnitTests/BindablePropertiesAccessModifiers.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
Changes the XAML compiler and parser to allow `internal` bindable properties on controls.
- fixes #2425
None
None
> [Core] Add support for internal bindable properties for F#

- Xamarin.Forms.Core/BindableProperty.cs
[C] do not crash on OneTime defaultBindingMode
- fixes #3071
/
- Core (all platforms)
No longer crash when creating a BP with `OneTime` as default binding mode.
> [C] do not crash on OneTime defaultBindingMode

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3089.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/ListView.cs
Changed usage of default TextCell by ListView to use Bindings to set the Text instead of just setting the text directly. This way recycled cells will correctly have their text changed when the BindingContext is changed
- fixes #3089 
- Core (all platforms)
> [ALL] fixes #3089 Change default TextCell to use binding

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1483.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/PageControl.cs
- Xamarin.Forms.Platform.UAP/PageControlStyle.xaml
For some reason, if a Navigation Page was the root page of a Forms application, on UWP the containing PageControl could not properly load its ControlTemplate. This had the side effect of preventing the ActivityIndicator from displaying or running.
This change allows the PageControl to find its template even when the Navigation Page is the root, which allows the ActivityIndicator to display properly.
Unfortunately, there's no good way to automate the test for this (we can't verify that the ActivityIndicator is displaying correctly, and the test app can't launch with the test page as its root).
Related to #730
- fixes #1483 
None
- UWP
None
> [UWP] Allow PageControl to find its template if a NavigationPage is the app root

- Xamarin.Forms.ControlGallery.Tizen/ControlGallery.Tizen.cs
- Xamarin.Forms.ControlGallery.Tizen/SampleNativeControl.cs
- Xamarin.Forms.Controls/GalleryPages/XamlNativeViews.xaml
This PR adds support for `Xaml Native Views Gallery` on tizen backend. This also include `SampleNativeControl` tizen implementation coming from #2772.
None
None
- Tizen
None
> [Controls] Support NativeView to ControlGallery.Tizen

- Xamarin.Forms.Platform.Tizen/Native/Dialog.cs
- Xamarin.Forms.Platform.Tizen/Native/Watch/WatchDialog.cs
- Xamarin.Forms.Platform.Tizen/Platform.cs
This RR is to add circle style dialog for tizen watch
None
None
- Tizen
DisplayAlert 
- with a cancel button
| -- | -- |
|![tw_displayalert_1_1](https://user-images.githubusercontent.com/20968023/41759747-f70c2e0c-762a-11e8-8d66-145259eb5200.png)|![tw_displayalert_1](https://user-images.githubusercontent.com/20968023/41759753-fdd68c00-762a-11e8-9d70-946606a877d0.png)|
- with an accept button and a cancel button
| -- | -- |
|![tw_displayalert_2_1](https://user-images.githubusercontent.com/20968023/41759767-0de68d0c-762b-11e8-970f-31006163d56d.png)|![tw_displayalert_2](https://user-images.githubusercontent.com/20968023/41759773-140015c8-762b-11e8-8c80-4b33062bded8.png)|
DisplayActionSheet
| -- | -- | …
> [Tizen] Add circle style dialog for watch

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1342.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Added a check to verify if the cells of the UITableView have rendered and need to be kept synchronized to source list
- fixes #1342
- fixes #1542 
- fixes #1927
- iOS
> [iOS] If the UITableView hasn't rendered anything yet don't try to sync cells

- Xamarin.Forms.Platform.Android/Cells/ViewCellRenderer.cs
This is just to get these changes into an early branch so that once 15.8 drops we'll still be able to compile
https://github.com/xamarin/Xamarin.Forms/pull/2836
> Use GestureDetector constructor that takes in Context 3.0

- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
remove AfterBuild call to xbuild
build is obsolete and not really needed anymore. This is also causing an error with the latest VS for Mac tooling
> remove AfterBuild call to xbuild

- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3087.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/LegacyComponents/NonAppCompatSwitch.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/SwitchRenderer.cs
For non app compat Switch Renderer *OnCheckedChange* was being fired during initialization prior to the *_defaultTrackDrawable* being initialized which would cause UpdateColor to null out the *TrackDrawable* and lead to an NRE on the next check changed
- fixes #3087
- Android
> [Android] fixes #3087. Move initialization of TrackDrawable  non app compat

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/EntryUnfocusedImmediately.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3012.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.CustomAttributes/TestAttributes.cs
- Xamarin.Forms.Platform.MacOS/Renderers/EntryRenderer.cs
Improve the conditions which an Entry's Focused and Unfocused events fire running on macOS. Previously when the Entry element was clicked, the Focused event would be invoked, and immediately be followed by the Unfocused event being invoked. This was a result of the macOS FirstResponder quirks with NSTextField. 
Reference https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/EventHandlingBasics/EventHandlingBasics.html#//apple_ref/doc/uid/10000060i-CH5-SW23 
- fixes #3012 
None
The Entry element on macOS will no longer invoke Focused and Unfocused events when the Entry is clicked. 
The Entry's Focused event is now invoked only when the element obtains FirstResponder or when the Entry was previously focused when the window lost key status and the window …
> [macOS] Entry focus unfocus events

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1939.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
We were attempting to get the list item from the ListProxy for the DataTemplateSelector. When the source is cleared asynchronously, the ListProxy is empty, causing the lookup to fail. No longer attempting to look up the value when there are no items in ListProxy.
- fixes #1939
None
- Android
None
> [Android] Don't throw ArgumentNullException when ObservableCollection is cleared asynchronously

- Xamarin.Forms.Controls/ControlGalleryPages/ToolbarItems.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
Revert #2870 
Do not set frame twice as it causes the button to shift
- fixes #2798 
None 
- iOS
Should layout buttos ok even after push and rotation
> [iOS] Try another fix for toolbar items layout

- Xamarin.Forms.Platform.UAP/VisualElementTracker.cs
Fixed Swipe gesture not being handled correctly in `VisualElementTracker`.
Was incorrectly returning out of the `UpdatingGestureRecognizers()` method _before_ wiring manipulation and pointer event handlers.
Fixes #3097.
None
- UWP
None
> [UWP] Swipe gesture not being handled in VisualElementTracker

- Xamarin.Forms.ControlGallery.iOS/Info.plist
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1583_1.cs
- Xamarin.Forms.Platform.iOS/Renderers/WebViewRenderer.cs
Fixes regression loading a url with a port number
- https://github.com/xamarin/Xamarin.Forms/commit/3b2be6912c35a0991ff08b26b92414a9eefb1cd0#commitcomment-29458985
-  fixes #3073
None
- iOS
Url with port number should now load as before
> [iOS] Fix iOS WebView load url with port number

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2617.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3053.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/CellControl.cs
Reusing templated cells on UWP breaks the UWP listview in multiple ways. This change rolls back to just creating a new cell for each row.  I tested the memory implications of this and did not see any leaks caused by this changed.   At a later point we can further test and optimize the performance but ListView2 may trump that effort
- fixes #2617
- fixes #3053
- fixes #2832
- UWP
> [UWP] Remove use of TemplatedItemsList for Cells

- Xamarin.Forms.Platform.GTK/Renderers/AbstractPageRenderer.cs
Fixed error in page height calcs hiding the navigation bar.
On a page like this:
The default result:
Using `NavigationPage.SetHasNavigationBar(this, false);`
- fixes #3153 
- GTK
> [GTK] Fixed Layout calcs with NavigationBar

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2740.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/PageContainer.cs
Add native ctor to PageContainer so it can be accessed when on a Fragment remove event
- fixes #2740
> [Android] Add native ctor to PageContainer

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1583.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1583_1.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
Fix small issue introduce with TitleView, Fix NRE when child wasn't added yet to NavigationPage
No link
None
- iOS
No crash
> [iOS] Fix NRE when child wasn't added yet to NavigationPage

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1556.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs
- Xamarin.Forms.Core.UnitTests/MotionTests.cs
- Xamarin.Forms.Core/AnimationExtensions.cs
- Xamarin.Forms.Core/Internals/Ticker.cs
- Xamarin.Forms.Core/Tweener.cs
- Xamarin.Forms.Platform.Android/AndroidTicker.cs
- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
- Xamarin.Forms.Platform.Android/FormsApplicationActivity.cs
- Xamarin.Forms.Platform.Android/PowerSaveModeBroadcastReceiver.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
For Android APIs below Lollipop, this changes nothing.
For Lollipop and higher, the app will now listen for changes to the power save mode status and respond accordingly. When power save is on, animations will immediately move to their finished state. If power save becomes active while an animation is in progress, the animation will be immediately moved to its finished state.
- fixes #1556
None
- Android
None
> [Android] Force animations to finish immediately when power save mode is on

- Xamarin.Forms.Controls/App.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
If you push a page with a `WebView` onto a `NavigationPage` on `Application OnStart`, it seems to cause the `WebView` to infinitely navigate, rendering it basically useless on Android.
This is hard to reproduce in the Control Gallery, since it only happens if you do the navigation `OnStart`, so to run the test, you must uncomment the test from the `App.cs OnStart` method.
This change will ensure that a `Page` doesn't get pushed a second time `OnStart` (or `OnAttached`, in Android).
related to #1999
- fixes #2393
None
- Android
Honestly? Probably tons. O_O
> [Android] NavigationPage should not push a page that has already been pushed

- Xamarin.Forms.Platform.UAP/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.UAP/NavigationPageRendererUWP.cs
- Xamarin.Forms.Platform.UAP/PageControl.cs
The UWP PageControl class contains code to manage the back button, but the back button it manages does not exist anywhere in the template. It looks like this is code left over from handling Windows 8.1 TabletResources.
No automated tests, there's literally nothing to test for.
None
None
- UWP
None
> [UWP] Clean up "backButton" stuff in PageControl

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2482.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs
- Xamarin.Forms.Core/AnimationExtensions.cs
- Xamarin.Forms.Core/ViewExtensions.cs
When using the animation extensions to `VisualElement`, queueing up multiple animations can result in a race condition where an animation Task result is set multiple times (throwing an exception) and another animation's result is never set (meaning an `await` on it never returns). 
This change guarantees that all animations with the same key are cancelled before queueing up a new animation with that key, avoiding both scenarios.
- fixes #2482 
None
None
> Clear all previous animations with the same key when starting a new animation

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GitHub1702.cs
- Xamarin.Forms.Platform.Android/AppCompat/ButtonRenderer.cs
#2426 added the `Button.Padding` property, but on Android, it was removing necessary padding when the value wasn't set. This checks to ensure that there is a value set before it adjusts it.
unreported
None
- Android
None
> [Android] Don't mess with the `Button.Padding` if the `Padding` property isn't set

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43469.cs
- Xamarin.Forms.Platform.UAP/PlatformUWP.cs
The while loop on s_currentAlert wasn't thread safe so it could be set to null between the check and the await which meant it would be awaiting on null and throw an exception.
Added text to description but the clicking to cause the issue has to happen too quickly for the UI test to detect
- fixes #3250 
- UWP
> [UWP] store alert to local variable for thread safety

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40005.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2338.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.Windows.UITests/WindowsTestBase.cs
- Xamarin.Forms.Platform.Android/AppCompat/ILifeCycleState.cs
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailContainer.cs
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
- Xamarin.Forms.Platform.Android/Extensions/FragmentManagerExtensions.cs
- Xamarin.Forms.Platform.Android/Renderers/MasterDetailRenderer.cs
- Xamarin.Forms.Platform.Android/VisualElementExtensions.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
OnAppearing for Android fires sometimes during *OnAttached* and sometimes during "OnResume"
- when you swapped out the MainPage it would call RemoveViews mid fragment lifecycle which would then lead to the fragment not found when FragmentManager would try to Resume the fragment
- Added an interface to allow a renderer to be declared MarkedForDeath so that things like adding more fragments or pending operations can just be halted
- Centralized on interactions with Fragments into a single Extension class because that just made it easier to break point or print debug messages for any Fragment modifications.
- Moved all the code for changing out the main page into the MainLooper call so that all "active" life cycle events will just settle before the main page does it's clean up and …
> [Android]  Let inflight life cycle events finish up before tearing them down

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/PerformanceGallery/Scenarios/ImageScenarios.cs
- Xamarin.Forms.Core/Registrar.cs
- Xamarin.Forms.Platform.Android/Extensions/ImageViewExtensions.cs
- Xamarin.Forms.Platform.Android/Renderers/FileImageSourceHandler.cs
- Xamarin.Forms.Platform.Android/Renderers/IImageViewHandler.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Context:
https://github.com/bumptech/glide
https://github.com/jonathanpeppers/glidex
Currently the way my "proof-of-concept" GlideX library works by
completely bypassing `IImageSourceHandler`. GlideX provides its own
custom `ImageRenderer` and `ImageCellRenderer`. This was required due
to how *opinionated* the Glide library is. Glide's approach is to
never allow a developer access to a `Android.Graphics.Bitmap` or
`Android.Graphics.Drawable` because we would likely do it wrong... and
developers do all the time!
To evolve Xamarin.Forms to where images could be better handled down
the road, I've introduced a new interface:
public interface IImageViewHandler : IRegisterable
{
Task LoadImageAsync(ImageSource imageSource, ImageView imageView, CancellationToken cancellationToken = …
> [android] new IImageViewHandler API

- Xamarin.Forms.Platform.Android/Renderers/ScrollViewContainer.cs
`ScrollViewContainer` was missing an API level check for `IsInLayout`. 
- fixes #3186 
None
- Android
None
> Add missing API check in ScrollViewContainer

- Xamarin.Forms.Platform.UAP/PageControl.cs
- Xamarin.Forms.Platform.UAP/PageControlStyle.xaml
The fix for issue #1483 (PR #3074) made PageControl unable to find the correct ControlTemplate when it wasn't the root page of the application. This change makes PageControl find the correct template in both situations.
No tests, for the same reason there are no tests for PR #3074.
- fixes #3297
None
- UWP
None
> [UWP] Fix incorrect style for PageControl when not the application root

- Xamarin.Forms.Platform.WPF/Extensions/FontExtensions.cs
Add font-size "Default" to FontExtenstions of the WPF-Platform.
- fixes #3355 
- WPF
> [WPF] Add font-size "Default" to FontExtentions

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GitHub1776.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.MacOS/Renderers/ButtonRenderer.cs
Pressed, Released, Clicked, and Command all fire appropriately
- fixes #1776 
None
- macOS
The standard Button element will invoke pressed on mousedown.
The standard Button element will invoke released on mouseup, regardless of mouseup position after mousedown.
The standard Button element will invoke Clicked on mouseup if mouseup occurs in button after mousedown.
The standard Button element will execute Command on mouseup if mouseup occurs in button after mousedown.
> [macOS] Fix standard button events

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3000.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/Cells/Cell.cs
- Xamarin.Forms.Core/IFlowDirectionController.cs
- Xamarin.Forms.Core/Layout.cs
- Xamarin.Forms.Core/ScrollView.cs
- Xamarin.Forms.Core/VisualElement.cs
- Xamarin.Forms.Platform.Android/ContextExtensions.cs
- Xamarin.Forms.Platform.Android/Extensions/FlowDirectionExtensions.cs
- Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.UAP/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs
Android - LayoutDirection needed to be set on the internal HorizontalScollView 
Android (when target < 17), UWP, iOS - When the scroll view is initially loaded and set to RTL it will start out scrolled all the way to the right.  
- fixes #3000
- iOS
- Android
- UWP
> Remove math on scroll view container for RTL

- Xamarin.Forms.Core/FlexLayout.cs
This PR checks for the null reference of _root `Flex.Item` in `LayoutChildren()` before calling `Layout()` on the inner children.
- fixes #3234 
None
None
This is a very simplistic fix and there might be some more digging to do as whether or not the last layout cycle should be avoided upstream.
> [Core] Add check for null _root flex item

- Xamarin.Forms.Platform.UAP/FormsTextBox.cs
Fixes password Entry Copy/Paste/Insert/Remove behavior
- fixes #2388
None
- UWP
- Correct behavior copy/paste for password Entry in any position of the text cursor
- Restore cursor after insert char or string in password Entry
Screencast: http://recordit.co/fPqYn9mKXT
> [UWP] Fixes password Entry Copy/Paste/Insert/Remove behavior

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Core/ContentPropertyAttribute.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3260.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3260.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
GetMethod, GetField, ... were already correctly resolving generic base
types. GetProperty or GetEvent were not, causing NRE later on.
- fixes #3260
/
/
> [XamlC] Resolve generic base type on GetProperty

- Xamarin.Forms.Platform.iOS/Cells/ViewCellRenderer.cs
- Xamarin.Forms.Platform.iOS/DisposeHelpers.cs
- Xamarin.Forms.Platform.iOS/Platform.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
- Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
The iOS platform has a few places where `Element.Platform` is cast to the native iOS `Platform` to call helper methods which don't actually need anything from the native `Platform` class. 
This change makes those helper methods static and moves them to their own class. This removes the need for IPlatform in native iOS code.
None; laying the groundwork for removing `Platform` from `Element`.
None
- iOS
None
> [iOS] Remove iOS Platform Casts

- Xamarin.Forms.Platform.UAP/TabbedPageRenderer.cs
TabbedPageRenderer is missing the IToolBarForegroundBinder interface on UWP, so changes to BarTextColor and BarBackgroundColor are not applied. This change implements the interface.
> [UWP] Add missing IToolBarForegroundBinder interface on TabbedPageRenderer

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
BackButtonTitleProperty  isn't used by Android so when it's changed Android shouldn't call *UpdateToolBar*
- Android
> BackButtonTitleProperty isn't used by android

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3333.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
Add a null check in case the List is null
- fixes #3333 
- UWP
> [UWP] add null check to Listview layout update in case it's been disposed

- Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
Android platform is doing a type check to see which version of `CloseContextActionsSignalName` to send, but both versions do the same thing. This just consolidates to a single version of the message. 
None, just avoiding a _very_ minor performance hit.
None
- Android
None
> [Android] Simplify subscription to context action closure messages

- Xamarin.Forms.Core/Application.cs
A lot of logging happens internally, for example when a binding fails. In order to make these logs more accessible to the end-user, the `Application.LogWarningsToApplicationOutput` property was introduced. WIth this, logging will also be outputted to the debug console.
- fixes #2639
Added: 
```csharp
public static bool Application.LogWarningsToApplicationOutput { get; set; }
```
When `Application.LogWarningsToApplicationOutput` is set to true, a `LogListener` is attached to the internal logging system which outputs the messages through a `Debug.Writeline`. When set to false the `LogListener` is removed again.
> [Core] Report binding failures

- Xamarin.Forms.Platform.Tizen/Platform.cs
This change is about fixing the appearance of `Page.IsBusy` on Tizen.
- Inappropriate white color background of popup is removed
- Busy mark is moved to the center of a screen
- fixes #
- None
- Tizen
Unwanted white background color is removed, and busy mark is shown as expected.
> [Tizen] Fix Page.IsBusy Appearance

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2838.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/FrameRenderer.cs
This PR fixes issue #2838 - CornerRadius rendering for Frame control on UWP. This occurs for `Frame` elements with a set background color and `CornerRadius`. In current release this causes the background to protrude through the rounded corners, which means the corners essentially remain square.
The fix provides a custom override of the `VisualElementRenderer`'s `UpdateBackgroundColor` method in UWP `FrameRenderer`.
**Before**
**After**
- fixes #2838 
N/A
- UWP
`Frame` with `CornerRadius` and a background color will now render properly on UWP.
> [UWP] Fix CornerRadius rendering on Frame

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1469.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
Added synchronization between the abstract and native `SelectedItem` when it was changed by clicking.
- Fixes #1469
/
> [UWP] Fixes setting SelectedItem inside ItemSelected event

- Xamarin.Forms.Core/RectangleTypeConverter.cs
- Xamarin.Forms.Core/Size.cs
- Xamarin.Forms.Core/SizeTypeConverter.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3280.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3280.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Add a missing TypeConverter attribute to Size struct.
- fixes #3280
/
/
> [C, Xaml] add SizeTypeConverter

- Xamarin.Forms.Core/IStyleElement.cs
- Xamarin.Forms.Core/Span.cs
- Xamarin.Forms.Core/Style.cs
- Xamarin.Forms.Core/VisualElement.cs
[C] abstract the Style property in an interface
so it's shared between VisualElement and span, and retrieving the
property is easier.
- fixes #3314
/
/
> [C] abstract the Style property in an interface

- Xamarin.Forms.Platform.UAP/Forms.cs
- Xamarin.Forms.Platform.UAP/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.UAP/Platform.cs
- Xamarin.Forms.Platform.UAP/WindowsBasePage.cs
Fix the two places where UWP is relying on casting Element.Platform to UWP.Platform (for handling back button presses and for toolbar updates).
None, prepping for further cleanup.
None
- UWP
None
> [UWP] Remove Platform casts

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3390.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UnitTests/ButtonUnitTest.cs
- Xamarin.Forms.Core/Button.cs
If you change the `CornerRadius` to 5 has replaced it by -1, and If you change the `BorderRadius` when set to -1 has replaced it by 5. This happened because there was no verification conflicts.
These two properties change each other and the default property may not be applied correctly in this process. 
This PR adds a check that the property is already in the process of changing. And no need to change value to default.
- fixes #3390
/
- Core (all platforms)
Correct setting `CornerRadius` of button to 5.
Correct setting `BorderRadius` of button to -1.
> [Core] Fixed setting CornerRadius of button to 5

- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
Per: https://github.com/xamarin/Xamarin.Forms/issues/3354#issuecomment-406725306
Adding ```[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.0.0.0")]``` to Xamarin.Forms.Core `AssemblyInfo` after it was removed from the `GlobalAssemblyInfo` in #3118 
- fixes #3354
None
None
> Add assembly version to XF.Core

- Xamarin.Forms.Core.UnitTests/BindingUnitTests.cs
- Xamarin.Forms.Core/BindingBase.cs
Due to a flux in the matrix, Bindings with a TargetNullValue assigned
were always returning that value. It had the advantage of being right
sometimes, but the inconvenient for being wrong, most of the times.
By properly aligning the bits of the register with the sun at beer time,
we can avoid that side effect, and actually returns a value when the
binding is succesful, and the TargetNullValue whem the Binding returns
null.
- fixes #3467
/
/
> [C] fix TargetNullValue Bindings

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3415.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/SwipeGestureRecognizer.cs
- Xamarin.Forms.Platform.Android/InnerGestureListener.cs
#2727 added a SwipeGestureRecognizer for all platforms. On Android, the command was firing twice because the `EndScrolling` delegate is called twice. Now checking the same `isScrolling` bool that prevents the duplicate call for the `PanGestureRecognizer`.
Also removed the `HasFlag` calls in favor of bitwise checks for performance.
- fixes #3415 
None
- Android
None
> [Android] Prevent duplicate events from SwipeGestureRecognizer

- Xamarin.Forms.Platform.Android/Renderers/ButtonRenderer.cs
Fix for NullReferenceException that occurs when a page is closed
- fixes #3373
- iOS
- Android
- UWP
> [Android] Fixing a NullReferenceException that happens when a page is closed

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3367.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
`ListView` scrolls asynchronously so as not to freeze the UI thread.
**Screencast:** http://recordit.co/f2RIEyQdTG
- fixes #3367 
/
- UWP
> [UWP] Fixed freezing UI when scrolling the listview

- Xamarin.Forms.Platform.iOS/ContextActionCell.cs
Prevent NRE and crash when a leaked cell in ListView with Recycle mode has MenuItem with bindings and framework like Prism.Forms sets BindingContext to null after leaving the page. Leaked cells can appear as result of device orientation change plus scrolling or just ListView.ScrollTo call.
- fixes the crash but not underlying cell leak, see #3275
N/A
- iOS
N/A
- [ x] Rebased on top of the target branch at time of PR
- [ x] Changes adhere to coding standard
> [iOS] Prevent crash when a leaked cell has MenuItem with bindings

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2004.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/App.cs
- Xamarin.Forms.Platform.Android/AppCompat/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/ButtonBackgroundTracker.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ButtonDrawable.cs
- Xamarin.Forms.Platform.Android/Renderers/ButtonRenderer.cs
From what I can tell the set of operations that causes this to happen go as follows
- Main Page set to a page with a ListView that has lots of buttons with background set
- Set Main Page to something else
- Main Page set to a page with a ListView that has lots of buttons with background set
- At this point the ListView gets LayedOut twice. From what I can tell this is caused from a race condition with fragments.  Two commits occur when the page is swapped out. One from the DetailsContainer on the MasterDetails and then one from the Internal navigation page. Sometimes a layout happens between the two commits which means it'll happen a second time after the second commit
- Between the first and second layout (on low end devices) the GC runs which causes the bitmaps that are stored inside …
> [Android] check if bitmaps have been GC'd

- Xamarin.Forms.Platform.Tizen/Renderers/ActivityIndicatorRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/CarouselPageRenderer.cs
1. Fixed `CarouselPage` 
- Fixed the issue of `CarouselPage`, The current page is not chagned when `CarouselPage` have one page and another page is added after.
- When children of `CarouselPage` is changed, the layout bound should be reset. Because inner container is temporarily empty by `UnPackAll` method of inner container.
2. Fixed ActivityIndicator.IsRunning condition
- Update `IsRunning` property when the `IsEnabled` property is updated.
Tizen
> [Tizen] Fix minor bugs on CarouselPage and ActivityIndicator

- Xamarin.Forms.Platform.WPF/Renderers/ListViewRenderer.cs
When you tap the selected item in a ListView, ItemTapped is not raised, because it raised only when on native control changed item index. This behavior has been replaced to listening to native events `MouseUp`, `KeyUp`, `StylusUp`, `TouchUp`.
- fixes #3265
- WPF
Event `ListView.ItemTapped` is raised whether the item was selected or not.
> [WPF] Fix ItemTapped event in a ListView

- Xamarin.Forms.Platform.WPF/Themes/FormsContentDialog.xaml
Fixes title at Page.DisplayActionSheet
- fixes #3259 
None
- WPF
The title in the Page.DisplayActionSheet text wraps now and the is not in uppercase.
> [WPF] Fixes title in Page.DisplayActionSheet

- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
This change detects that OnCreate was called prior to calling LoadApplication and throws a better error message to help the developer.
NullReferenceException with no information is thrown if you don't call `base.OnCreate(bundle)` in your subclass. It took quite a long time to figure this oversight out - a proper error message would have gotten me to move a lot faster.
I found lots of forum issues with people reporting the same thing. 
None
Android
None
> [Android] Improve error message when not calling base.OnCreate

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1601.cs
- Xamarin.Forms.Controls/App.cs
- Xamarin.Forms.Controls/Bugzilla44596SplashPage.cs
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailContainer.cs
- Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
#421 resolved this issue once, but it was regressed by #865, presumably because it was causing crashes when the MainPage was quickly swapped out because the `FragmentContainer` was not initialized properly. 
Instead of calling `ExecutePendingTransactions` to try to get the transition to happen quickly and in the proper order, we are now explicitly waiting to remove any views from the main ViewGroup until the new views have been added and are ready to display. This should eliminate that flicker and avoid any side effects from the `ExecutePendingTransactions` call altogether.
- fixes #1373
None
- Android
OnAppearing and OnDisappearing events to fire in a different order when swapping out the MainPage.
This PR
```
OnAppearing: Page1
OnAppearing: Page2
OnDisappearing: Page1
```
Before PR
``` …
```
> [Android] Prevent white flash when switching MainPage to new MasterDetailPage

- Xamarin.Forms.Platform.UAP/Platform.cs
- Xamarin.Forms.Platform.UAP/Resources.xaml
Before the various IToolBarProvider implemenations (MasterDetail, Tabbed, Navigation) implemented their own command bars as part of their control templates, Platform could add a command bar to any page which needed it. 
Now that each of the providers ... er, provides their own command bar, this capability is no longer necessary or in use. This change removes the unused code.
None, just cleaning out unused code.
None
- UWP
None
> [UWP] Remove old appbar code in Platform

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3507.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/ScrollViewRenderer.cs
Check if the Content View or Renderer for the content on the ScrollView is null to avoid an NRE when wiring up 
- fixes #3507 
- UWP
> [UWP] ScrollView will not crash when it has null Content

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.MacOS/FormsApplicationDelegate.cs
Fixes a change made to check existing MenuItems. IF using the old way of not specify a Storyboard wasn+t take in account.
To test one should use the old method of setup the macOS app : 
`Edit info.plist and remove the source entry (NSMainStoryboardFile)`
and On Main.cs 
```
NSApplication.Init();
NSApplication.SharedApplication.Delegate = new AppDelegate();
NSApplication.Main(args);
```
- fixes #3353 
- macOS
> [MacOS] Fix NRE when checking for existing MainMenu, fixes #3353

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3512.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3512.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Throws a XamlParseException on duplicate x:Key on RDs. This will find
duplicate in xaml, but duplicates can still happen if the RD is modified
in code. Those dupes are already detected at runtime.
- helps, but doesn't fixes, #3512
/
/
> [XamlC] Throws on duplicate x:Key

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/ControlGalleryPages/FlowDirectionGallery.cs
- Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs
Reverting some changes done on #1222  .
Start portrait , rotate to landscape , rotate portrait and rotate to landscape again.
Before:
After: 
- fixes #3458 
- iOS
After several rotations on iPad the Master page on MDP should always be visible
> [iOS] Fix sizing issue on MDP 

- Xamarin.Forms.Core/VisualElement.cs
For CSS purposes, the VisibilityConverter was added, and actually
replaced the `Boolean.Parse(str)` call for parsing Visibility.
`Boolean.Parse()` trims input, and the converter was not, so this was a
regression.
This changes Trim() the input, to be fully backward compatible.
- fixes #3554
/
/
> [C] VisibilityConverter Trims input

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GestureBubblingTests.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/InputTransparentTests.cs
The InputTransparentTests and GestureBubblingTests fail occasionally on Android because they find and tap the wrong 'SearchBar' control; this change uses a different identifier for the 'SearchBar' button to avoid this problem.
- Random test failures, hopefully
None
- Android
None
> Change identifier for search bar in tests to avoid confusing UITests

- Xamarin.Forms.Platform.Tizen/Native/TitleViewPage.cs
- Xamarin.Forms.Platform.Tizen/Renderers/NavigationPageRenderer.cs
This change is about supporting the `TitleView` of `NavigationPage` on Tizen
None
None
- Tizen
If you set any `View` of Xamarin.Forms to the navigation bar of a `NavigationPage`, `TitleView` would be shown on top of `Page`.
However,  If pages are pushed before the `TitleView` is set, these pages can not display the `TitleView` due to the platform limitation. 
It is recommend to set the `TitleView` before pushing a `Page`.
> [Tizen] Support the TitleView of NavigationPage

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla56896.cs
The test for Bugzilla56896 is failing intermittently with a `System.IndexOutOfRangeException`; this _might_ be an issue where the UITest query for ConstructorCountId and TimeId is occurring before the elements are actually available to be found by UITest. This change adds a WaitForElement for each of those elements to ensure that they are available before running the queries.
> Ensure ConstructorCountId and TimeId elements are available before querying them

- Xamarin.Forms.Core/StyleSheets/StyleSheet.cs
- Xamarin.Forms.Xaml.UnitTests/StyleSheet.xaml.cs
- Xamarin.Forms.Xaml/MarkupExtensions/StyleSheetExtension.cs
This would allow previewer/designer/reloader to determine the source of a
stylesheet and refresh its content when appropriate.
> Expose the Source for a StyleSheet

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3539.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3539.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] Fix binding compilation fo value types
properly load valuetype arguments of generated setters, using ldarg,
instead of ldarga.
- fixes #3539
/
/
> [XamlC] Fix binding compilation for value types

- Xamarin.Forms.Controls/ControlGalleryPages/AutomationPropertiesGallery.cs
- Xamarin.Forms.Platform.iOS/Cells/CellRenderer.cs
- Xamarin.Forms.Platform.iOS/Cells/TextCellRenderer.cs
Added support AutomationProperty for cells
- fixes #3296 
/
- iOS
All AutomationProperty work correctly and are successfully pronounced for a text cell
> [iOS] AutomationProperty support for cells

- Xamarin.Forms.Platform.UAP/FormsPresenter.cs
- Xamarin.Forms.Platform.UAP/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.UAP/TabbedPageRenderer.cs
When initializing navigation / tabbed pages, the user can not add any child pages. Check it did not exist and threw NullReferenceException.
You can run UITest 2338 for testing.
- fixes #3188
/
- UWP
> [UWP] Fixes crash app when create navigation/tabbed page without children

- Xamarin.Forms.Platform.Android/Forms.cs
Android `ScaledScreenSize` is using the screen width to calculate the height. This change uses the height instead.
- fixes #3609 
None
- Android
> [Android] Use height when determining ScaledScreenSize on Android

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3524.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/BindableObjectExtensions.cs
- Xamarin.Forms.Core/Element.cs
- Xamarin.Forms.Core/Span.cs
- Xamarin.Forms.Core/View.cs
The BindingContext on the span wasn't being propagated down to the Gestures. I took the code that performs this Propagation with Views and centralized it into an extension method
- fixes #3524
> [Core] fixed #3524 - set binding context on Span Gestures

- EmbeddingTestBeds/Embedding.Droid/Embedding.Droid.csproj
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj
- Xamarin.Forms.ControlGallery.Android/Properties/AndroidManifest.xml
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
- Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj
- Xamarin.Forms.Platform.Android.FormsViewGroup/Xamarin.Forms.Platform.Android.FormsViewGroup.csproj
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
AndroidUseLatestPlatformSdk has been deprecated and having it set to true is causing the build server to use a TFV that's inconsistent with what we have specified
API's deprecated by TFV 9.0 are causing the build server to fail because we have Treat Warnings as ERrors set
- Android
None
> [Android] remove deprecated AndroidUseLatestPlatformSdk

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3049.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Platform.cs
The iPad ActionSheet has an implicit cancel when you click outside of the ActionSheet. However, if the user did not supply a text for the Cancel button (which is only relevant for phone), then we did not handle the cancel event. This caused the app to hang on iPad while it waited for the cancel result.
Now adding a cancel event to an ActionSheet whether text is defined or not if the device is an iPad.
- fixes #3049
None
- iOS (iPad only)
None
> [iOS] iPad ActionSheet should always have a Cancel method

- Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
On the initial layout of a scroll view that is set to RTL the ScrollX position needs to be propagated to the cross platform control. Android will just start the Horizontal scroll all the way to the right without through a scrolled event so the value was never propagating to our control
- fixes #3675 
- Android
When set to RTL the ScrollChanged event will now fire once on load to indicate its non zero X position. This brings it in line when running below API 17 as well
> [Android] Set initial ScrollView Scroll values when RTL

- Xamarin.Forms.Platform.WPF/Themes/FormsContentDialog.xaml
Fix DisplayAlert has no Text Wrapping issue
- fixes #3634 
- WPF
> [WPF] Fix DisplayAlert has no Text Wrapping

- Xamarin.Forms.Platform.GTK/GtkToolbarTracker.cs
- Xamarin.Forms.Platform.GTK/Renderers/NavigationPageRenderer.cs
Calling NavigationPage.SetHasNavigationBar after the page is loaded does not update the visibility of the navigation bar correctly
- GTK
> [GTK] Fix navigation bar visibility updates

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2894.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/FormattedString.cs
- Xamarin.Forms.Core/GestureElement.cs
- Xamarin.Forms.Core/Label.cs
- Xamarin.Forms.Core/Span.cs
- Xamarin.Forms.Platform.Android/Renderers/FormattedStringExtensions.cs
- Xamarin.Forms.Platform.UAP/VisualElementTracker.cs
- Xamarin.Forms.Platform.iOS/EventTracker.cs
- Xamarin.Forms.Platform.iOS/Renderers/FormattedStringExtensions.cs
[UWP] - When Multiple gestures were attached to different spans the initial gestures wouldn't wire up, changes to span gestures weren't propagating
[iOS] - condensed some code and fixed issue where changes to Span Gesture Collections weren't propagating. Fixed an issue where clicking really fast in the control gallery would cause an exception because the MainPage gets swapped out after 5 clicks which would dispose of the underlying views prior to the uitouch getting dispatched
iOS testing note - Clicking on the span in iOS will probably be a little quirky but there's already an issue for that that I'm currently working on 
- fixes #2894 
- iOS
- Android
- UWP
> [iOS, UWP] fixes #2894 - Gestures collection changes weren't correctly propagating

- Xamarin.Forms.Platform.Tizen/Renderers/ScrollViewRenderer.cs
This PR fix ScrollView padding issue on Tizen
Padding of ScrollView was not shown properly
- Tizen
None
``` xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
x:Class="WearableUIGallery.TC.TCPopupEntry"
xmlns="http://xamarin.com/schemas/2014/forms"
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
xmlns:w="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms">
<ContentPage.Content>
<ScrollView x:Name="Scroller" Padding="20,40,20,40">
<StackLayout BackgroundColor="Red">
</StackLayout>
</ScrollView>
</ContentPage.Content>
</ContentPage>
```
Before
After
None
> [Tizen] Fix ScrollView Padding issue

- Xamarin.Forms.Platform.WPF/Renderers/ViewRenderer.cs
This PR fix the memory leak when you pop a TabbedPage on WPF
- fixes #3267
- WPF
> [WPF] Memory leak when you pop a TabbedPage

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3343.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UnitTests/EntryUnitTests.cs
- Xamarin.Forms.Core/Entry.cs
- Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.UAP/EntryRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
#2539 added the ability to set `CursorPosition` and `SelectionLength` on `Entry`. It was set up to allow these properties to be set during construction, but that was thwarted by the initial `Text` triggering a `SelectionChanged`, which reverted the `CursorPosition` and `SelectionLength` to default values. This change established a one-time-use bool that will skip the initial `SelectionChanged` work.
Also resolved issue where clearing the set values of CursorPosition/SelectionLength did nothing.
- fixes #3343 
- fixes #3633
None
- iOS
- Android
- UWP
None
1. Open test case 3343.
2. First Entry should have selection. CursorPositon: 4 SelectionLength: 7.
3. Second Entry should have no selection. CursorPostion: 0 SelectionLength: 0.
4. Tap in second Entry. Make selection. CursorPosition and …
> [Android,iOS,UWP] Allow Entry CursorPosition/SelectionLength to be set in ctor

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3413.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs
As of latest versions of iOS11.3 seems that passing the max value to the UISearchBar for sizing breaks.
This only happens when we don't specify any Width request for the SearchBar and the SearchBar is requested to stretch itself. 
We could try to pass a enormous value but I figure this was a best call. 
At the same time we found out iOS10 also wasn't rendering , the issue that is SizeThatFits always is retiring a 0 Width , we override the call and set the width. 
- fixes #3413 
- fixes #2139  
None
- iOS
Should show the Searchbar inside a horizontal StackLayout and blue SearchBar Expanding
Before:
It crashed  and didn't renderer the blue SearchBar with CenterAndExpand
After:
IOS 10
iOS11
> [iOS] Specify a default size for UISearchBar width if needed

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41418.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3398.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.UAP/ViewRenderer.cs
In PR https://github.com/xamarin/Xamarin.Forms/pull/2515 there was a mistake due to which all `Margin` properties inside `StackLayout` / `AbsoluteLayout` were applied twice.
- fixes #3398 
- fixes #3616
- UWP
Labels and other elements with `Margin` property are correctly displayed inside in layouts.
> [UWP] Fixed double set margins in Layouts

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/MultipleClipToBounds.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/VisualElementTracker.cs
The bounds clipping settings for Layouts on Android modify the parent's ClipChildren property; this means that if a Layout contains multiple child Layouts, the clipping setting is effectively the IsClippedToBounds property of the last layout to be processed by the VisualElementTracker; mixed IsClippedToBounds settings among siblings are impossible.
This fix uses the ClipBounds property on the actual Layout (as opposed to the parent) to handle bounds clipping, avoiding the conflict.
This fix only applies to API 18+. The necessary methods don't exist for earlier APIs, so 15-17 will still have the buggy behavior.
This change includes a manual test; can't currently think of a way to automate this test.
- https://bugzilla.xamarin.com/show_bug.cgi?id=36121
None
- Android
None
> [Android] Support multiple clipping settings in single layout

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3408.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Cells/CellTableViewCell.cs
- Xamarin.Forms.Platform.iOS/Cells/EntryCellRenderer.cs
- Xamarin.Forms.Platform.iOS/Cells/ImageCellRenderer.cs
- Xamarin.Forms.Platform.iOS/Cells/SwitchCellRenderer.cs
- Xamarin.Forms.Platform.iOS/Cells/TextCellRenderer.cs
SwitchCellRenderer wasn't unsubscribing when disposed. 
The best way would be to just use the event exposed by our `CellTableViewCell` 
We should use this in other cell renderers, this will allow to control the unsubscribing  when cell's are dispose and reused. 
- fixes #3408 
Changes to `CellTableViewCell`
Add:
`public void HandleCellPropertyChanged(object sender, PropertyChangedEventArgs e)`
`public Action<object, PropertyChangedEventArgs> CellPropertyChanged`
Remove: 
`public Action<object, PropertyChangedEventArgs> PropertyChanged`
- iOS
Doesn't crash when SwitchCells go away (are disposed)
>  [iOS] Unsubscribe CellPropertyChanged when SwitchCellRenderer is disposed

- Xamarin.Forms.Platform.Android/Renderers/TimePickerRenderer.cs
The 24h mode for the pickerdialog was not working.
Version 3.1 was working fine. 
Here is an updated file.
- Android
> [Android] Fixed TimePicker to support 24H mode

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2338.cs
Remove if defs for UWP that are no longer valid because of https://github.com/xamarin/Xamarin.Forms/pull/3514
- UWP
> [UWP] uncomment tests that are now passing for 3188

- Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
#3283 was built on top of #3187 to incorporate the great changes made there in my tests, but I targeted #3283 to master while #3187 was targeted to 3.1.0. When #3187 was merged down to master in a94074463efe263cfe3056f6e1c65e65c2fac86f, the change [here](https://github.com/xamarin/Xamarin.Forms/pull/3187/files#diff-c986fa1fa0e47f337a0dcc0ec16b5d05R269) was taken. We actually needed to keep the changes that were already in master [here](https://github.com/xamarin/Xamarin.Forms/pull/3283/files#diff-c986fa1fa0e47f337a0dcc0ec16b5d05R276). This was an absolutely confusing merge to do, and I doubt I will do such a silly thing again.
While I was in there, I fixed the ugly `global::` namespaces and converted the `foreach`s to `for`s as previously requested in #3283.
- fixes #3705
None
- Android …
> [Android] Revert bad merge

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3624.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/VisualElementPackager.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
- Xamarin.Forms.Platform.iOS/RendererPool.cs
Fixes layout compression causes in Android and iOS.
- fixes #3624
None
- iOS
- Android
None
Not applicable
- Run UITest 3624
- Click on button "With Compression (type 1) --- Crash while scrolling"
- Scroll page. It should not throw an exception
> [Android, iOS] Fixes layout compression causes

- Xamarin.Forms.ControlGallery.WindowsUniversal/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla56771.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3273.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
`CollectionChanged` events are fired, when collection changed in user code.
- fixes #3273 
/
- UWP
> [UWP] Fixes CollectionChanged events in ListView

- Xamarin.Forms.ControlGallery.Android/ColorPicker.cs
- Xamarin.Forms.Platform.Android/AppCompat/PageExtensions.cs
- Xamarin.Forms.Platform.Android/Cells/EntryCellRenderer.cs
- Xamarin.Forms.Platform.Android/Forms.cs
Ignore warning our extension method throws since is returning a deprecated android  api App.Fragment. 
Fix usage of default text color that is also deprecated on API28 SDK
Update provisioning for 15.8
Build issues with API28
- fixes #2128
- fixes #3629 
Obsolete:
`[Obsolete("ContentPage.CreateFragment() is obsolete as of version 3.2. Please use ContentPage.CreateSupportFragment() instead.")]`
- public static global::Android.Support.V4.App.Fragment CreateFragment(this ContentPage view, Context context)
- Android
> [Android] Update Forms to remove API28 deprecated API

- Xamarin.Forms.Platform.WPF/Converters/IconConveter.cs
- Xamarin.Forms.Platform.WPF/Renderers/VisualPageRenderer.cs
- Xamarin.Forms.Platform.WPF/Xamarin.Forms.Platform.WPF.csproj
FIX : Binding an icon in a ToolbarItem in a TabbedPage doesn't refresh when the binding changes. Even changing the icon directly doesn't work. Only way is to remove the ToolbarItem, change it and add it again.
- fixes #3756
- WPF
> WPF - Fix Binding Icon in ToolbarItem in TabbedPage doesn't refresh

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1588.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1588.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3308.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3558.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WPF/Renderers/ViewRenderer.cs
Fix Width and Height measurement when GetDesiredSize
- fixes #1588, #3308, #3558 
- WPF
> WPF - Fix Width and Height measurement when GetDesiredSize

- Xamarin.Forms.Maps.Android/MapRenderer.cs
Add method to retrieve native Marker from a pin in Android MapRenderer.  No tests added as it is a simple Extract Method refactoring.
Eases subclassing of MapRenderer to extend pins.  Needed to build a Skia Maps extension Nuget.
Added:
protected Marker GetMarkerForPin(Pin pin)
Changed:
N/A
Removed:
N/A
- Android
None
N/A
N/A
> [Android Maps] Make markers available to subclasses

- Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs
- Xamarin.Forms.Core.UITests.Shared/Utilities/Gestures.cs
When attempting to scroll during UI Tests, occasionally the timing of the scroll and querying for an element don't match up. This attempts to query a few times before failing.
This attempts to resolve random failures with calls to *App.ScrollForElement*
UI TESTS
> [UITests] wait for element before querying for it

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3541.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.WPF/Deserializer.cs
Fix : Local store not persistant when restarting App in Xamarin Forms WPF
- fixes #3541
> WPF - Fix Local store not persistant when restarting App

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3788.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
Currently when replacing an item in an ObservableCollection it causes the entire list to reload and scroll to the top.  This change correctly implements Replace opposed to just reloading the entire list
- fixes #3788 
- UWP
1) Run Issue3788 in the control gallery
2) click the button 
3) this should replace the last item on the list and the list shouldn't scroll to the top
> [UWP] implement Replace without reloading ListView

- Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs
- Xamarin.Forms.Platform.iOS/Renderers/SwitchRenderer.cs
Use default UIApperance tint color 
- fixes #3111 
None
- iOS
Default color should be respect if set via UIAppereance 
Before
After
Go to Switch cell gallery on iOS and check the default color for the switch is Red
> [iOS] Use UIApperance default color for UISwitch

- Xamarin.Forms.Platform.Android/Renderers/BoxRenderer.cs
Drawing CornerRadius (introduced by #1998) when the CornerRadii are
actually 0 causes scaling artifacts on API < 25.
This fixes the regression when no CornerRadius is set. Expect blurry
border scaling with CornerRadius not empty and API < 25
- fixes #3781
None
- Android
None
Not applicable
> [A] do not draw gradient for empty CornerRadius

- Xamarin.Forms.Platform.Android/Renderers/FormsWebViewClient.cs
- Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
- Extracted WebViewRenderer.WebClient to FormsWebViewClient so that it can be inherited from and overwritten when custom renderers require a custom WebViewClient
- Moved firing of WebView.Navigating event from ShouldOverrideUrlLoading to OnPageStarted in FormsWebViewClient so that it is consistently fired every time a URL is navigated to including initial load
- fixes #3778 
Added:
- public override void FormsWebViewClient.OnPageStarted(WebView view, string url, Bitmap favicon)
- public const string WebViewRenderer.AssetBaseUrl = "file:///android_asset/"
- protected virtual FormsWebViewClient WebViewRenderer.GetFormsWebViewClient()
- FormsWebViewClient WebViewRenderer._webViewClient 
Changed:
- class WebViewRenderer.WebClient => public class FormsWebViewClient
- bool …
> [Android] Fix WebView.Navigating event, make WebViewClient inheritable

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39378.xaml.cs
Added missing `Preserve` attribute to the existing test so the class members can be loaded properly. The issue was not just with the image source but also the background color of the containing grid.
- fixes #2306
None
None
Run UI test 39378
> [All] Added preserve attribute to the view model class of UI test 39378

- Xamarin.Forms.Platform.Android/Renderers/DatePickerRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/TimePickerRenderer.cs
If the Android Date- or TimePicker controls get a focus request while the picker dialog is visible, they launch a second picker dialog which covers the first. 
This change verifies that the picker dialog is not already visible before launching a new one.
- Breaking UI tests 42074/41424 (and following tests, as the dialogs do not dismiss properly).
None
- Android
None
Not applicable
Run UI tests 42074 and 41424; in each one, tap the "Click to focus X" button. Then tap the hardware back button. Without this change, a picker dialog will still be visible. With this change, there will be no picker dialog visible.
> [Android] Prevent double time/date picker dialogs on Android when setting focus

- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
- Xamarin.Forms.Platform.Android/FormsApplicationActivity.cs
- Xamarin.Forms.Platform.Android/Platform.cs
- Xamarin.Forms.Platform.Android/Renderers/MasterDetailRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/NavigationRenderer.cs
Makes the native `Platform` class accessible to the renderers which need it without having to cast `Element.IPlatfrom`. 
None; this is prep work for further cleanup.
None
- Android
None
> [Android] Make native Android Platforms accessible via Context

- Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Toolbar Items on Android do not appear disabled when they are an icon that is not in the overflow menu. There is no visual change between enabled and disabled.
iOS and UWP make changes when disabled.
This change makes them appear with a 50% alpha, similar to disabled text toolbar items.
Fixes #3628 
None
- Android
If the user disables a Toolbar Item with an icon, it will now have a disabled look on Android.
Before:
After:
Go to the ToolbarItems Gallery page. Observe the disabled icon appearance.
I can sure write a test page if someone tells me where they want it and what exactly you would like on it.
> Added a disabled look to Android Toolbar Item images.

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3872.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/DatePickerRenderer.cs
- Xamarin.Forms.Platform.UAP/ITabStopOnDescenants.cs
- Xamarin.Forms.Platform.UAP/ITabStopOnDescendants.cs
- Xamarin.Forms.Platform.UAP/SearchBarRenderer.cs
- Xamarin.Forms.Platform.UAP/StepperRenderer.cs
- Xamarin.Forms.Platform.UAP/TimePickerRenderer.cs
- Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
Complex controls when receive focus send it further to descendant or previous element.
- fixes #3872
None
- UWP
When press `Tab` button or `Shift-Tab` controls immediately getting focus on interactive control.
Not applicable
- run UI test 3872
- press Tab key few times.
- check switching focus control. They should switch the next interactive control on a single click.
- press Shift-Tab keys few times.
- check switching focus control in reverse order. They should switch the next interactive control on a single click.
> [UWP] fixes tabstops of TimePicker, DatePiker. SearchBar, Stepper

- Xamarin.Forms.Platform.UAP/SliderRenderer.cs
For the Slider default value of step is set to `1000` to match Android.
Also removed ToolTip with current value.
- fixes #2955
None
- UWP
> [UWP] Allow setting StepFrequency of the Slider

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1937.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/WindowsBasePlatformServices.cs
- Xamarin.Forms.Platform.UAP/WindowsTicker.cs
Replace ```DispatcherTimer ``` to ```CompositionTarget.Rendering``` event in ```WindowsTicker``` and ```WindowsBasePlatformServices``` . 
- fixes #1937
None
- UWP
These changes would improve animation smoothness.
Not applicable
I checked only on _ScaleTo_ animation and wrote ```Issue1937Test ``` for ```Device.StartTimer```.
> Fix StartTimer and Ticker for UWP

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3884.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/BoxRenderer.cs
- fixes #3884 
None
- Android
Corner radius should look correct on Android
Before
After
Just go to test 3884 and make sure you see a circle
> [Android] Convert corner radius with correct pixel density

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39378.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39378.xaml.cs
Removed automated test
Added on-screen instructions
Switched to using another URL for the image
@hartez wanted to see `ManualReview` category added, but this category is set when `#if UITEST` is true. Why set it if the test is not automated? Should this still be added?
- fixes #2305
> Fix UI test 39378

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ViewClipBoundsShouldUpdate.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/VisualElementTracker.cs
The ClipBounds for Layouts is not being updated when the size of the Layout changes. This change fixes that issue.
- Clipped layouts disappearing entirely if IsClippedToBounds set before they are sized
- Clipped layouts being clipped at the wrong dimensions after rotation/resizing
- fixes #3717
None
- Android
None
Not applicable
> [Android] Update ClipBounds when View bounds changes

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60787.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60787.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/FrameRenderer.cs
This change forces FrameRenderer on Android to rerender of its background Drawable without losing the corner radius..
- fixes #3902 
- [https://bugzilla.xamarin.com/show_bug.cgi?id=60787](https://bugzilla.xamarin.com/show_bug.cgi?id=60787)
Added:
- void FrameRenderer.Element_PropertyChanged(object sender, PropertyChangedEventArgs e);
Changed:
- void Xamarin.Forms.Platform.Android.FrameRenderer.OnElementChanged => now it subscribes and unsubscribe to events.
Removed:
- void Xamarin.Forms.Platform.Android.FrameRenderer.UpdateCornerRadius=> it had a redundant code lines, same as UpdateBackground.
- Android
After dynamic background color change, the corner radius should stay the same before.
[Before](https://drive.google.com/file/d/1ONs_F7AF2MweJvgjn7Zr8ejZy-NX_yRG/view) …
> Fix bugzilla60787

- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Controls/GalleryPages/TitleView.xaml
- Xamarin.Forms.Controls/GalleryPages/TitleView.xaml.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
There are a number of opinionated changes that come along with this PR in order to provide better consistent behavior with iOS 10 vs 11 and with iOS and other platforms.
- fixes #3881
- fixes #3679 
None
- iOS
- If you set the TitleView the back button titles now just get removed completely in order to provide more consistent behavior between ios 10 and ios 11
Left image is before and right image is after
Search Bar also fixed on iOS 12
Left image should have a SearchBar but it doesn't
I've modified the TitleView gallery page to attempt to test all TitleView permutations. To test, click through all the different things you can toggle on that page and see if everything acts as you would expect it to. Test iOS 10 vs 11 and also different Android APIs
> [iOS] fix full width issues for TitleView

- Xamarin.Forms.Platform.GTK/Controls/TableView.cs
- Xamarin.Forms.Platform.GTK/Renderers/TableViewRenderer.cs
Changes in TableView GTK Control and TableViewRenderer to allow refresh the content (updating/removing TableSections).
- fixes #3725 
- GTK
Now, the TableView refresh the content adding or removing TableSections, etc.
When running the Xamarin Forms Control Gallery for GTK the test cases screen doesn't appear to update it's view as you try to filter down issues.
> [GTK] Changes in TableView to allow refresh the content (updating/removing TableSections)

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3809.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Page.cs
- Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
-If platform isn't iOS then don't do anything when the user changes the SafeAreaPadding setting
-Check to see if the user has changed the padding when setting SafeAreaPadding to false so it doesn't overwrite what the user used.  
- fixes #3809 
- fixes #3866
- iOS
- Android
- UWP
Not applicable
-For the issue created click the two buttons provided to set the padding and change whether Safe Area has been enabled. Ensure that the page padding reacts as you'd expect it to
> Only set the Page Padding via SafeAreaInset on iOS

- Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs
By making GetIconDrawable virtual for the Android TabbedPageRenderer it allows for the icon to come from other sources (like glyph fonts). This will work for both top and bottom tabs.
Changed TabbedPageRenderer.GetIconDrawable to virtual.
- fixes #
None
- Android
None
Not applicable
> [Android] Make GetIconDrawable virtual

- Xamarin.Forms.Platform.GTK/Controls/Page.cs
- Xamarin.Forms.Platform.GTK/Platform.cs
- Xamarin.Forms.Platform.GTK/Renderers/NavigationPageRenderer.cs
A modal navigation stacks the new page in the Page's control without hiding the current page or the previous stacked page, so those are still taken in account for redraws and resizes. This change hides the current visible page before showing the new one. Also, the current implementation is iterating over all children and calling ShowAll when the modal is poped, changing the visibility state of the page that's under the modal.
Example:
1. A page has a label that's hidden
2. A modal navigation hide the page and shows the new page
3. The modal is poped, showing again the page with the label
4. The label must remain hidden
None
- Gtk
None
Not applicable
> [GTK] Fix visibility in modal pages

- Xamarin.Forms.Platform.Android/Extensions/TextViewExtensions.cs
- Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/LabelRenderer.cs
MaxLines handling on Android is currently blowing away the settings from LineBreakMode, causing CharacterWrap and WordWrap to fail.
This change addresses that by doing the following:
- If MaxLines is not explicitly set, it is ignored and the values from LineBreakMode handle the native maxLines value.
- If MaxLines is explicitly set, the MaxLines setting wins. 
This change also uses a more reasonable default for native maxLines when handling it via LineBreakMode (the Android default of MaxValue rather than an arbitrary 100). This change also consolidates MaxLines handling code between legacy and fast renderers for less duplication and removes unnecessary calls to SetSingleLine (which only applies to input).
- fixes #3772 
- fixes broken LineBreakMode on Android when using WordWrap and …
> [Android] If MaxLines is not explicitly set, let LineBreakMode handle it

- Xamarin.Forms.Core.UnitTests/TypedBindingUnitTests.cs
- Xamarin.Forms.Core/TypedBinding.cs
Avoid multiple subscription to PropertyChanged on TypedBindings
- fixes #3613
- fixes #3650
None
None
Not applicable
> [XamlC] avoid multiple subscription

- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
[C] add CSS mapping for max-lines
- fixes #3982
None
None
Not applicable
> [C] add CSS mapping for max-lines

- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Application.cs
- Xamarin.Forms.Platform.iOS/VisualElementTracker.cs
Added a platform specific property to iOS that allows you to direct all control layout/rendering updates to the main thread instead of to a background thread. This should be rarely needed, but in some cases, it may prevent crashes.
- fixes #1755
Added:
- `void On<iOS>().GetHandleControlUpdatesOnMainThread() //Platform Specific`
- `bool On<iOS>().SetHandleControlUpdatesOnMainThread(true/false) //Platform Specific`
- iOS
None
Not applicable
Since SkiaSharp.Views.Forms doesn't play well with our ControlGallery, you'll need to use the sample project provided in #1755 and the nuget package produced by the build.
1. Get project from #1755 (CADError).
2. Run project. Verify crash.
3. Update Xamarin.Forms nuget package to the package created by this build.
4. In `App.xaml.cs`, add `using …
> [iOS] Add ability to turn off updates to native controls from another thread

- Xamarin.Forms.Platform.WPF/Renderers/ListViewRenderer.cs
Fixed NotImplementedException refreshing items (addin, clear) in WPF ListView.
- fixes #3309 
- fixes #3737 
- fixes #3648 
- WPF
Now, can clear or change items in WPF ListView.
Before
After
> Fixed NotImplementedException refreshing items in WPF ListView

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3606.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3606.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Sources are usually x:reference that can't be resolved at compilation
time.
- fixes #3606
None
None
Not applicable
> [XamlC] don't compile bindings with Source

- Xamarin.Forms.Build.Tasks/XmlTypeExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/LoaderTests.cs
- Xamarin.Forms.Xaml/XamlParser.cs
XamlLoader should first look for type with the Extension suffix. It used
to be the case, but somehow regressed.
- fixes issue describe in comment https://github.com/xamarin/Xamarin.Forms/issues/3606#issuecomment-422377338
None
None
Not applicable
> [Xaml[C]] resolve Extensions first

- Xamarin.Forms.Platform.MacOS/Extensions/NSViewControllerExtensions.cs
Correcting a very small typo.
Given this is an internal class and never invoked including parameter name explicitly (using named parameters), it should be a safe change.
> Correct minor typo

- Xamarin.Forms.Core/IWebViewController.cs
- Xamarin.Forms.Core/WebView.cs
- Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs
- Xamarin.Forms.Platform.GTK/Controls/WebView.cs
- Xamarin.Forms.Platform.GTK/Renderers/WebViewRenderer.cs
- Xamarin.Forms.Platform.MacOS/Renderers/WebViewRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/WebViewRenderer.cs
- Xamarin.Forms.Platform.UAP/WebViewRenderer.cs
- Xamarin.Forms.Platform.WPF/Renderers/WebViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/WebViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs
Add a way to reload the current URL in WebView control
- fixes #3776 
- iOS
- Android
- UWP
- Mac OS
- WPF
- Tizen
Not applicable
> Added WebView Reload

- Xamarin.Forms.Platform.Tizen/Cells/ImageCellRenderer.cs
- Xamarin.Forms.Platform.Tizen/Forms.cs
- Xamarin.Forms.Platform.Tizen/FormsApplication.cs
- Xamarin.Forms.Platform.Tizen/GestureDetector.cs
- Xamarin.Forms.Platform.Tizen/GestureHandler.cs
- Xamarin.Forms.Platform.Tizen/Log/Log.cs
- Xamarin.Forms.Platform.Tizen/Native/Dialog.cs
- Xamarin.Forms.Platform.Tizen/Native/Entry.cs
- Xamarin.Forms.Platform.Tizen/Native/ListView.cs
- Xamarin.Forms.Platform.Tizen/Native/Scroller.cs
- Xamarin.Forms.Platform.Tizen/Native/Span.cs
- Xamarin.Forms.Platform.Tizen/NativeValueConverterService.cs
- Xamarin.Forms.Platform.Tizen/Platform.cs
- Xamarin.Forms.Platform.Tizen/Renderers/MasterDetailContainer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs
- Xamarin.Forms.Platform.Tizen/ResourcesProvider.cs
- Xamarin.Forms.Platform.Tizen/TizenIsolatedStorageFile.cs
- Xamarin.Forms.Platform.Tizen/TizenPlatformServices.cs
Fixes warnings detected by static code analyzers
- fixes #
None
- Tizen
None
Not applicable
> [Tizen] Cleanup XF.Platform.Tizen

- Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
Fixed iOS editor placeholder font (Size/Family)
- fixes #4004
Changed: private UpdateFont method in iOS EditorRenderer
**iOS**
FontFamily/FontSize is applied for Placeholder as well
[BEFORE]
[AFTER]
Run test sample on iOS and see, that FontSize and FontFamily is applied for Placeholder as well as for Text
```csharp
public App ()
{
InitializeComponent ();
MainPage = new ContentPage
{
Content = new StackLayout
{
Children = {
new Editor
{
Placeholder = "Test Text",
FontSize = 50,
WidthRequest = 200,
VerticalOptions = LayoutOptions.CenterAndExpand,
HorizontalOptions = LayoutOptions.CenterAndExpand
}
}
}
};
}
```
> [iOS] Fixed editor placeholder font

- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3821.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3821.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3821View.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3821View.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/MarkupExtensions/ReferenceExtension.cs
- Xamarin.Forms.Xaml/XamlServiceProvider.cs
As part of #2556, the namescoping tree was assumed to be equiv to the
object tree, which is obviously wrong. This fixes it, while keeping the
old behavior as a fallback.
We might go further, but I can't come up with a reasonable scenario
failing.
- fixes #3821
None
None
Not applicable
> [Xaml] fix Namescope being different than tree

- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
Hi, I noticed an issue with PagesGallery.Droid
I couldn't build it on my Mac
Really, I don't know, whether there is such problem on Windows, but it occurs on VS for mac
After these changes I'm able to build PagesGallery.Droid again
Changed:
- object ListView.SelectedItem => One of ref. in PagesGallery.Droid.csproj
Only sample project, Android
[BEFORE]
[AFTER]
Try to build PagesGallery.Droid project on Mac
> [Sample] [Android] Fixed PagesGallery.Droid build

- Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
Force call UpdateFont after UpdateInputType
- fixes #4018
Changed: private UpdateInputType method (call UpdateFont at end of this method)
- Android
Font isn't affected during changing properties which are described in issue.
Try this changes with #4018 sample
> Fix typeface reset issue

- Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
Uses `ViewCompat` to use `SetLabelFor` and `GetLabelFor` Android Views.
`GetLabelFor` and `SetLabelFor` were introduced in API17. ViewCompat ensures this is done in a proper manner checking whether they API running the app supports this.
- fixes #3953 
- Android
None
Not applicable
> [Android] Use ViewCompat to set and get label for view

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3979.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3979.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/WindowsResourcesProvider.cs
`WindowsResourcesProvider.GetStyle` method previously set the `LineBreakMode` setter of the style. This was inconsistent with all other platforms (including WPF) and caused exceptions when one of the default styles was set to a `Span`.
- fixes #3979 
None
- UWP
The `LineBreakMode` is no longer set on UWP's default Device styles (`TitleStyle`, `SubtitleStyle`, `BodyStyle`, `ListItemTextStyle`, `ListItemDetailTesxtStyle`, `CaptionStyle`). The Windows default was `CharacterWrap` whereas the `Label` default (and other platforms default) is `WordWrap`.
Looking into UWP `LabelRenderer` there is only a slight difference between how these two modes are handled:
```
case LineBreakMode.WordWrap:
textBlock.TextTrimming = TextTrimming.None;
textBlock.TextWrapping = TextWrapping.Wrap;
break;
case …
```
> Removing LineBreakMode support from WindowsResourcesProvider

- Xamarin.Forms.Platform.MacOS/NativeToolbarTracker.cs
On Mojave we will need a different way to check the title frame. 
- fixes #3031
None
- macOs
Text might be not entered on the Titlebar on Mojave
just use the gallery on Mojave it would break without this fix.
> [macOS] Fix NRE on Mojave when aligning the title

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4040.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4040.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
Allow to skip setting Font and/or TextColor for each Span (You may set Label.TextColor and/or FontSize, FontFamily, FontAttributes
- fixes #4040
None (Only internal LabelRenderer logic)
- iOS
None
Described in issue ticket
Described in issue ticket
> [iOS] Label TextColor has no effect with FormattedString

- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4099.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4099.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Compiled converters are invoked, by reflection, at compile time. Any
exception thrown there will be wrapped in a TargetInvocationException.
When that happens, we still want to expose the inner XamlParseException
to the user.
- fixes #4099
None
None
Not applicable
> [Xaml] don't swallow exceptions from converters

- Xamarin.Forms.Platform.UAP/DatePickerRenderer.cs
- Xamarin.Forms.Platform.UAP/Extensions.cs
Native `DatePicker` control allows you to limit only a year. This fix add clamp DateTime after change and updates the visual element if the DateTime is out of limits.
- fixes #3331
None
- UWP
`DatePicker` cannot show date outside the limits
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
- run DatePicker Gallery
- select page `MinimumDate View`
- select on `DatePicker` date less than September 13th 1987
- again select on `DatePicker` date less than September 13th 1987
- check result
- select page `MaximumDate View`
- select on `DatePicker` date over September 13th 2087
- again select on `DatePicker` date over September 13th 2087
- check result
> [UWP] fixed `MinimumDate` and `MaximumDate` properties of DatePicker

- Xamarin.Forms.Platform.MacOS/Cells/CellRenderer.cs
Updated the CellRenderer code with the implementation of ForceUpdateSize for Cell on macOS
None
None
Changed:
- protected void WireUpForceUpdateSizeRequested(ICellController cell, NSView nativeCell, NSTableView tableView)
- macOS
None
Not applicable
> Implementation of method ForceUpdateSize for Cell on macOS

- Xamarin.Forms.Platform.MacOS/Renderers/EntryRenderer.cs
Added null check, prevent crash
- fixes #4076 
Added nullCheck to HandleWindowDidBecomeKey in EntryRenderer
- MacOS
App doesn't crashes
Not applicable
Described in original issue ticket (but I'm able to create test-case for this issue if it's needed)
> [MacOS] EntryRenderer crash when MainWindow get focus

- Xamarin.Forms.Platform.iOS/EventTracker.cs
Prevent enumeration through null collection
Fairy case for real app, but possibly somebody doesn't use NavigationPage and manages screens by setting MainPage... in theory, if user click on span and separate task starting to change MainPage it can cause the same issue like we have in UITest 3525 :) 
- fixes #3930
Added extra null check in ios EventTracker/CreateRecognizerHandler
iOS
UITest 3525 doesn't crash
Not applicable
Open UITest 3525 and click 6 times rapidly
> [iOS] Rapidly clicking span (6 times at least) on UITest 3525 throws a null exception

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4136.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/LabelRenderer.cs
The legacy `LabelRenderer` is not calling `UpdateLineHeight()` when the element is set, so `LineHeight` settings aren't applied until the value is changed.
This change adds the initial call.
Includes a manual test.
- fixes #4136 
None
- Android
None
Not applicable
> Add missing initial call to UpdateLineHeight

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45027.cs
Added UI test to issue #2385 (Bugzilla 45027), but don't was tested using Xamarin.Forms 2.3.2 (where the problem occurs).
A question: How I run this UI test using specific version of Xamarin.Forms in this project? Go back to the release-2.3.2 tag and create this test to certified that this UI test will fail?
- fixes #2385 
None
- Android
None
Not applicable
> Added UI test to B45027

- Xamarin.Forms.Platform.MacOS/Renderers/ActivityIndicatorRenderer.cs
- Xamarin.Forms.Platform.MacOS/Renderers/ProgressBarRenderer.cs
Fixed color reset issue after removing indicator/progressBar and adding again
- fixes #3301 
Changed SetBackgroundColor in ProgressBarRenderer (added color filter check)
Changed UpdateColor in ActivityIndicatorRenderer (added color filter check)
- MacOS
Indicator/Progress don't reset color after adding/removing
```csharp
public App()
{
var indicator = new ActivityIndicator
{
Color = Color.LightGreen,
IsVisible = true,
IsRunning = true,
VerticalOptions = LayoutOptions.CenterAndExpand,
};
MainPage = new ContentPage
{
Padding = new Thickness(50),
Content = indicator
};
Task.Run(async () =>
{
while(true)
{
await Task.Delay(2000);
Device.BeginInvokeOnMainThread(() => {
(MainPage as ContentPage).Content = (MainPage as ContentPage).Content == null ? indicator : null;
});
}
});
}
```
Is there any …
> Fix https://github.com/xamarin/Xamarin.Forms/issues/3301

- Xamarin.Forms.Core.Windows.UITests/WinDriverApp.cs
- Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs
Fixes the selection of controls with `ITabStopOnDescendants` interface from Selenium
- fixes #4159
None
- UWP
Not applicable
- Set yourself up to be able to run UWP UI tests https://github.com/xamarin/Xamarin.Forms#ui-tests
- Try to run a UI Tests
> [UWP] fixes entering text into SearchBar with UI Tests

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4001.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.MacOS/Renderers/WebViewRenderer.cs
Fixed NRE in case "webview is loading, try to push new page and remove webView from prev page"
- fixes #4001 
- Changed WebViewRenderer **Dispose** method (Clean delegates as well)
- Changed FormsWebFrameDelegate **_renderer** field to **Renderer** property
- MacOS
None (No crash)
Not applicable
Test Issue4001 in Control Gallery
Original PR: https://github.com/xamarin/Xamarin.Forms/pull/4163
> [macOS] NRE in WebViewRenderer

- EmbeddingTestBeds/Embedding.Droid/Embedding.Droid.csproj
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
- Xamarin.Forms.Platform.Android.FormsViewGroup/Xamarin.Forms.Platform.Android.FormsViewGroup.csproj
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Currently, on the first build of a "Hello World" Xamarin.Forms app,
you will see this in the build log:
ConvertDebuggingFiles
Parameters
Files
C:\Users\myuser\.nuget\packages\xamarin.forms\3.1.0.697729\lib\MonoAndroid10\FormsViewGroup.pdb
C:\Users\myuser\.nuget\packages\xamarin.forms\3.1.0.697729\lib\MonoAndroid10\Xamarin.Forms.Platform.Android.pdb
OutputItems
_ConvertedDebuggingFiles
C:\Users\myuser\.nuget\packages\xamarin.forms\3.1.0.697729\lib\MonoAndroid10\FormsViewGroup.dll
C:\Users\myuser\.nuget\packages\xamarin.forms\3.1.0.697729\lib\MonoAndroid10\Xamarin.Forms.Platform.Android.dll
The logging is a little weird here, but this `ConvertDebuggingFiles`
MSBuild task takes about 100ms on my machine.
The Mono debugger can support two types of debugging files:
- `mdb` files
- "portable" …
> [msbuild] use portable pdb files on Android

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4130.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4130.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Well, it looks like the order of arguments of InheritOrImplements was
reversed... a totally fine and normal Friday so far
- fixes #4130
None
None
Not applicable
> [XamlC] fix the argument match check for events

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44461.cs
Added instructions and UI test for test Bugzilla44461
- fixes #2380
None
- iOS
None
Not applicable
> Adding instructions and UI tests for Bugzilla44461

- Xamarin.Forms.Core/Xaml/TypeConversionExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4215.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4215.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
if a type defines multiple op_implicit from the same type to different
ones, trying to retrieve it with GetMethod() throws an
AmbiguousMatchException. If this happens, we have to do the resolution
ourself.
- fixes #4215
None
- iOS
- Android
- UWP
None
Not applicable
> [C] avoid AmbiguousMatchexception in Bindings

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2223.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.MacOS/Renderers/EntryRenderer.cs
- fixes #2223
Changed: EntryRenderer (Update control on IsPassword change)
- MacOS
You can change IsPassword for entry
Create entry and button. Change IsPassword of entry on button click. It should work
> [Enhancement] Possibility to change IsPassword for MacOS

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2763.cs
- Xamarin.Forms.Core.UnitTests/StackLayoutUnitTests.cs
- Xamarin.Forms.Core/Layout.cs
This PR update code of `IPaddingElement.OnPaddingPropertyChanged` on Layout
from `InvalidateMeasureInternal(InvalidationTrigger.MeasureChanged)` to `InvalidateLayout()`
Because, When size of layout was not changed by Padding, children element does not re-layouting with `InvalidateMeasureInternal(InvalidationTrigger.MeasureChanged)`
- fixes #4165
None
None
* Before
* After
> [Core] Fix layout padding update issue

- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Controls/GalleryPages/BindableLayoutGalleryPage.xaml
- Xamarin.Forms.Controls/GalleryPages/BindableLayoutGalleryPage.xaml.cs
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Core.UnitTests/BindableLayoutTests.cs
- Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
- Xamarin.Forms.Core/BindableLayout.cs
It allows any `Layout<View>` to generate its content (child views) by binding to an items source, with option to set item template or item template selector:
```
<StackLayout BindableLayout.ItemsSource="{Binding Items}" />
<StackLayout BindableLayout.ItemsSource="{Binding Items}"
BindableLayout.ItemTemplate="{Binding MyItemTemplate}" />
<StackLayout BindableLayout.ItemsSource="{Binding Items}"
BindableLayout.ItemTemplateSelector="{Binding MyItemTemplateSelector}" />
```
In the first example, where neither item template nor item template selector are set, every item is a `Label`. If both item template and selector are set, the item template is used. If `Items` property is set, it is ignored.
- fixes #1718
Added static class BindableLayout with following attached properties to …
> Bindable layouts

- Xamarin.Forms.Platform.GTK/Renderers/SliderRenderer.cs
Modified GTK slider renderer so it does not show a label with the slider value, thus behaving like the other Xamarin.Forms slider backends.
None
None
- GTK+
The slider will no longer show a label with the slider value on Xamarin.Forms.GTK
Before
After
> [GTK] Do not show a label in gtk slider renderer

- Xamarin.Forms.Core/BindableObject.cs
Every call to ApplyBindings is copying the properties `List` to an array before iterating over it, which can result in many thousands of extra `BindableObject[]` allocations. This change iterates over the `List` directly to avoid the extra allocations.
None
None
Not applicable
> Remove unnecessary ToArray to reduce number of BindableObject[] allocations

- Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs
The fix for Android's clipping issues (https://github.com/xamarin/Xamarin.Forms/pull/3559) broke the fast ImageRenderer when using AspectFill, because the cropping caused by `setClipChildren` was no longer in play.
This change adds clipping to the boundaries of the `ImageView` when the `ScaleType` is set to `CENTER_CROP`. 
- fixes #4133
None
- Android
None
See #4133 for 'before' screenshots.
After:
Open the Image Gallery in Control Gallery, select the AspectFill test. The image should look like it does in the "after" screenshot above.
> [Android] Enforce clipping on fast renderer ImageRenderer when using AspectFill

- Xamarin.Forms.Platform.MacOS/ImageSourceHandlers.cs
Implement possibility to set FileImageSource without setting extension (you can set "image" instead of "image.png") 
Added Log warning, if images wasn't found
- fixes #2322 
None
- MacOs
Images is shown
Not applicable
(Without fix you don't see the image, but if you apply it you will see the image)
```csharp
new ContentPage { Content = new Image { Source = "image" } } ;
```
> [MacOs] Image from file not getting searched in the bundle

- Xamarin.Forms.Platform.GTK/Cells/ViewCell.cs
- Xamarin.Forms.Platform.GTK/Controls/DatePicker.cs
- Xamarin.Forms.Platform.GTK/Controls/ImageButton.cs
- Xamarin.Forms.Platform.GTK/Controls/ListView.cs
- Xamarin.Forms.Platform.GTK/Controls/NavigationChildPage.cs
- Xamarin.Forms.Platform.GTK/Controls/OpenGLView.cs
- Xamarin.Forms.Platform.GTK/Controls/Page.cs
- Xamarin.Forms.Platform.GTK/Controls/SearchEntry.cs
- Xamarin.Forms.Platform.GTK/Extensions/VisualElementExtensions.cs
- Xamarin.Forms.Platform.GTK/GtkToolbarTracker.cs
- Xamarin.Forms.Platform.GTK/Platform.cs
- Xamarin.Forms.Platform.GTK/Renderers/AbstractPageRenderer.cs
- Xamarin.Forms.Platform.GTK/Renderers/ListViewRenderer.cs
- Xamarin.Forms.Platform.GTK/Renderers/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.GTK/Renderers/NavigationPageRenderer.cs
- Xamarin.Forms.Platform.GTK/Renderers/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.GTK/ViewRenderer.cs
- Xamarin.Forms.Platform.GTK/VisualElementRenderer.cs
- Xamarin.Forms.Platform.GTK/VisualElementTracker.cs
This serie of patches fixes several memory leaks in the GTK backend.
~~The first one is the MasterDetailPage that is not cleaning up old pages when the Detail or Menu page is changed.~~
Another issue is how disposal of Gtk objects is handled, wich is now incorrectly done using the Dispose function. Gtk objects should be disposed using the Destroy function that will automatically iterate over the children and destroy them too (https://developer.gnome.org/gtk2/stable/GtkWidget.html#gtk-widget-destroy).
The gtk-sharp bindings discourage the use of Dispose and don't even call the base class, leaving it without effect (https://github.com/mono/gtk-sharp/blob/gtk-sharp-2-12-branch/gtk/Object.custom#L98), so that's why Gtk objects should override the Destroy function. Problably the gtk-sharp …
> [GTK] Fix several memory leaks in the GTK backend

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1480.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/VisualElementTracker.cs
Confirm changing CALayer.Transform in Main Thread
- fixes #1480 
<!-- List all API changes here (or just put None), example:
Added:
Changed OnUpdateNativeControl of VisiualElementTracker
- iOS
Fixes bug
Not applicable
Test sample is attached to the issue
> [iOS] Change CALayer.Transform in MainThread

- .Xamarin.forms.sln
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3555.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/Editor.cs
- Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs
- Xamarin.Forms.Platform.UAP/EditorRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
Fixes #3555
Added the `Editor.IsTextPredictionEnabledProperty` field and `Editor.IsTextPredictionEnabled` property. Modified `EditorRenderer.OnElementPropertyChanged()` for Android, iOS and UWP to react to changes to the new `IsTextPredictionEnabled` property.
On Android setting `IsTextPredictionEnabled to false sets the `InputTypes.TextFlagNoSuggestions` flag on the native control's `InputType`.
On UWP the native control's `IsTextPredictionEnabled` will be set to the value of the `Editor.IsTextPredictionEnabled` property.
On iOS the native control's `AutocorrectionType` property will be set to `No` when `Editor.IsTextPredictionEnabled` is `false`.
- Fixes #3555
- iOS
- Android
- UWP
Please note #2038
Not applicable
> Add Editor.IsTextPredictionEnabled property

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
Removed custom entitlements entry for test simulator builds.
Everybody will be able debug test project easily without necessity to disable it in test project.
Now i can't build project as is.
None
- iOS test project
None
Not applicable
Remove your iOS provision profile and try to start debugging of Xamarin.Forms.ControlGallery.iOS
> [iOS] Removed custom entitlements entry for test simulator builds

- Xamarin.Forms.Controls/CoreGalleryPages/CoreGalleryPage.cs
The dismiss page button looks to be based on an older version of the control gallery where it was pushing modal pages and not just a single page swapping out layouts. 
This fix makes that button functional again instead of causing crashing
- Go to any of the control gallery pages that use the Dismiss Button (ImageGallery, Button Gallery, etc..)
- Click move next
- click Dismiss Page
- make sure no crashing happens
> [UITests] fix dismiss page crash

- Xamarin.Forms.Core.UnitTests/ViewUnitTests.cs
- Xamarin.Forms.Core/OnIdiom.cs
[C] Add Default value to OnIdiom
- fixes #4006
- closes #4025
Added:
- `public T OnIdiom<T>.Default {get; set;}`
None
Not applicable
> [C] Add Default value to OnIdiom

- Xamarin.Forms.Platform.Android/Renderers/DatePickerRenderer.cs
Created **ShowPickerDialog** method, which shows picker dialog with proper boundaries
- fixes #2315 
None (private methods only)
- Android
Min and Max date are the same as well as they were before rotating
- Run Issue2987 in the Android Control Gallery
- click the box to open the calendar
- Rotate the phone
> [Android] Changing from Portrait to Landspace while the calendar is open causes MinimumDate and MaximumDate to be visually ignored

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44338.cs
Added UI test to Bugzilla 44338. 
Bugzilla issue is about specific error in iOS, but I made UI tests on Android too.
- fixes #2379
None
- iOS
- Android
None
Not applicable
Run UI test for Android and iOS.
> Added UI test to B44338

- Xamarin.Forms.Platform.GTK/GtkSynchronizationContext.cs
GLib.Idle.Add enqueues functions in the main loop with the lowest priority, so while the UI is updating tasks will be queued in the main loop. Using Gtk.Application.Invoke they are interleaved with UI
updates and handled with more fairness.
None
- Gtk
None
Not applicable
> [GTK] Fix synchronization context fairness

- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/SetValue.xaml
- Xamarin.Forms.Xaml.UnitTests/SetValue.xaml.cs
This is a bug fix. Mono.Cecil accepts only `System.Int32` as an operand for `OpCodes.Ldc_I4` and casting is required for this case.
I didn't find any relevant issue.
None
None
Not applicable
Just try to set a `System.Byte` property with XamlC. For example, the following XAML will cause an exception where `Foo.Bar` is a property whose type is `System.Byte`.
```XAML
<Foo Bar="42" />
```
> [XamlC] Explicitly cast values for ldc.i4

- Xamarin.Forms.Platform.MacOS/Cells/CellNSView.cs
Force expand touch-catcher to cover full size of the cell
- fixes #2881 
None
- MacOs
Now it's possible to call context actions on TextCell
Open test case 31330 and try to right click over any cell
> [macOS] ContextActions on ListView not working (TextCell for example)

- Xamarin.Forms.Core/ToolbarItem.cs
This changes the `ToolbarItem` constructor's `name` parameter to `text`, to match the non-obsolete `Text` that gets the value. Without the change, it's confusing when tracing data flow related to `Text`, since it doesn't appear at first that it's being set.
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> Make ToolbarItem constructor match properties

- Xamarin.Forms.Xaml/XamlLoader.cs
When having a resources provider set, we should return the resource as soon as possible without having to read the original one from assembly.
This fixes live-reload scenarios in which reloading of code is done creating new types in dynamic assemblies, where GetManifestResourceStream is not available.
None
None
Not applicable
> [Xaml] Support correctly custom resource providers

- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4227.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4227.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] resolve properties in base interfaces
- fixes #4227
None
None
Not applicable
> [XamlC] resolve properties in base interfaces

- Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/StaticExtension.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4326.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4326.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] accept internal for x:Static
- fixes #4326
None
None
Not applicable
> [XamlC] allow internal for x:Static

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4348.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4348.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
[XamlC] resolve props on generics for bindings
Somehow, we weren't doing that up to now...
- fixes #4348
None
None
Not applicable
> [XamlC] resolve props on generics for bindings

- Xamarin.Forms.Core/Element_StyleSheets.cs
- Xamarin.Forms.Core/MergedStyle.cs
- Xamarin.Forms.Core/Style.cs
- Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- Xamarin.Forms.Xaml/XamlLoader.cs
- Xamarin.Forms.Xaml/XamlParser.cs
- Xamarin.Forms.Xaml/XamlServiceProvider.cs
Make the Xaml Loader more resilient, and allow loading xaml without compiling the project.
- fixes #
None
None
Not applicable
> VS bug [#706955](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/706955)
> Resilient xaml

- Xamarin.Forms.Core.UnitTests/PreviewerReflectionTests.cs
- Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj
- Xamarin.Forms.Core/Page.cs
Forms Elements used to have an internal API property `Platform` which needed to be set on each Element. That property is no longer needed and has been removed. But the Previewer still sets that property via reflection, which now causes a NullReferenceException.
This change creates a dummy property for the Previewer to set, avoiding the NRE. 
- fixes #4351
None
None
None
Not applicable
Open the previewer.
> Add fake Platform property to Page to keep Previewer happy

- Xamarin.Forms.Controls/GalleryPages/ImageGallery.cs
- Xamarin.Forms.Platform.Android/Extensions/ImageViewExtensions.cs
At some point when merging changes into ImageButton the NativeSizeChanged got removed which causes the image to non re-layout
Also fixed the Legacy Image Gallery to have the correct resource ID name for testing embedded images
- Android
Check the Legacy Image Gallery to make sure all the images (especially the embedded one) load
> [Android] fix removed NativeSizeChanged

- Xamarin.Forms.Platform.Tizen/Native/ToolbarItemButton.cs
- Xamarin.Forms.Platform.Tizen/Renderers/NavigationPageRenderer.cs
This PR is to fix a ToolbarItem issue
- fixes #
- Tizen
The changes of some properties(Text, IsEnabled, Icon) are applied after page loading. But the changes that affect the order of toolbaritems such as Order and Priority are ignored.
- Before
tb1.IsEnabled is false. But It is not applied when the page is loaded.
- After
tb1.IsEnabled is false. tb1 is disabled.
After then, If a user changes tb1.IsEnabeld to true, it will be changed as follow.
> [Tizen] Fix ToolbarItem

- Xamarin.Forms.Core/ToStringValueConverter.cs
#4016 introduce this new public API that I think we shouldn't expose. we could, in the future,  expose a set of commonly used converters, but a single one doesn't make sense.
> [C] ToStringValueConverter shouldn't be public

- Xamarin.Forms.Core/BindingExpression.cs
BindingExpression.TryConvert is a hot path, the string operation should
use the StringComparison. Also (less hot as it's a fallback), we should
avoid throwing for catching the exception a few line later.
N/A
None
- iOS
- Android
- UWP
None
Not applicable
> [C] perf fixes on BindingExpression.TryConvert

- Xamarin.Forms.Core.UnitTests/ToStringValueConverterTests.cs
- Xamarin.Forms.Core/ToStringValueConverter.cs
Fix ListView not calling ToString() when no template is set.
- fixes #4426
- fixes #3715 on 3.4.0
None
- iOS
- Android
- UWP
None
Not applicable
> Cherry-Pick #4016 and #4442 to 3.4.0

- Xamarin.Forms.Core/Items/CollectionView.cs
If `Device.Flags` is `null`, the code supposed to check for the presence of
the flags throws a `NullReferenceException`. Most users will get that
instead of the helpful version of it. Which is not very inclusive of the
people too lazy to read the docs.
None
None
None
Not applicable
> [C] Fix check for CollectionView flag

- Xamarin.Forms.Core/BindingExpression.cs
- Xamarin.Forms.Core/TypedBinding.cs
[XamlC] Port #1035 to comiled bindings
And share the TryConvert implementation to avoid future diverges
/
None
None
Not applicable
> [XamlC] Port #1035 to compiled bindings

- Xamarin.Forms.Core/BindingExpression.cs
- Xamarin.Forms.Core/TypedBinding.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4446.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4446.xaml.cs
Binding type coverter wasn't checking for valuetypes on null inputs.
- fixes #4446
None
None
Not applicable
> [C] Binding can't convert to valueTypes

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4138.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/packages.config
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
If there is no title view present then center the title icon. This is how it used to work before the titleview changes were made for creating a full width titleview
- fixes #4138 
- iOS
refer to #4138 to see how it should look.
- Go to the titleview gallery
- toggle the titleview until there isn't one
- toggle the title icon
- ensure that it is centered
> [iOS] center title icon on ios if there is no titleview

- Xamarin.Forms.ControlGallery.iOS/Properties/AssemblyInfo.cs
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1666.cs
- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Controls/CoreGalleryPages/WebViewCoreGalleryPage.cs
- Xamarin.Forms.Controls/CoreGalleryPages/WkWebViewCoreGalleryPage.cs
- Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs
The default renderer for `WebView` on iOS uses `UIWebView`, which handles Javascript-based user dialogs automatically. With `WKWebView`, these dialogs need to be set up manually with a delate.
This will allow users choosing to "upgrade" to `WkWebView` to retain the functionality of any javascript dialogs their web source may be using.
- Fixes #4253
- iOS
Without this change, dialogs created via Javascript in the `WKWebView` would never appear, now they will appear at the same times as they do when using `UIWebView`.
Use the repro steps mentioned in #4253 and the updated UI test to ensure the dialogs appear and behave correctly (confirm logs a bool, prompt logs an input string, etc).
> [iOS] Add JavaScript dialog delegate to WkWebView

- Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs
On Dispose(), the Renderer is supposed to be cleared on the element.
That's taken care of by VisualElementRenderer`1.Dispose().
Unfortunately, ScrollViewRenderer doesn't inherit from it.
I find it strange that this never was triggered before the Shell, but
I'm learning to live surrounded by strange behaviors.
No tests, as it's hard to reproduce in a UITest
- fixes #4381
None
- iOS
None
Not applicable
> [iOS] ScrollViewRenderer: clear the renderer

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4438.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4438.xaml.cs
[XamlC] comp binding to generic properties
- fixes #4438
None
None
Not applicable
> [XamlC] comp binding to generic properties

- Xamarin.Forms.Core.UnitTests/TypedBindingUnitTests.cs
- Xamarin.Forms.Core/TypedBinding.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4103.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4103.xaml.cs
Call base.GetSourceValue so the TargetNullValue is returned in case of a
null value. I have no idea why the code was there, but commented out,
and I don't want any of you to start digging at the why it wasn't
enabled before.
- fixes #4103
None
None
Not applicable
> [C] support TargetNullValue in TypedBindings

- Xamarin.Forms.Core.UnitTests/BindingUnitTests.cs
- Xamarin.Forms.Core/BindingExpression.cs
[C] Allow recursive parts of binding path
- fixes #3994
None
None
Not applicable
> [C] Allow recursive parts of binding path

- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/TypeReferenceExtensionsTests.cs
Generics can be nested; an argument for a parameter of a generic instance type can be another generic
instance type, which has its own parameters. The parameters in a nested argument must be resolved to specialize such a generic instance type, which `ResolveGenericParameters` basically does.
Consider the following types for example:
```C#
class Foo<T>
{
}
class Bar<T>
{
}
class Quux<T> : Foo<Bar<T>>
{
}
```
Now resolve the base type of `Quux<int>`. The old rash implementation of `ResolveGenericParameters` reads arguments of `Foo`, finds `Bar` is a concrete type, and considers there is nothing to do and returns `Foo<Bar<T>>` as a resolved one. But that is not true. The new implementation checks the argument of `Bar`, finds it is a generic parameter, replaces with a concrete type, `int`, …
> [XamlC] Resolve parameters in nested generics

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla44044.cs
Added UI test to B44044. The test is only for Android because iOS don't have gesture in tabbed page to change tab visualization.
- fixes #2377
None
- Android
None
Not applicable
Run UI test.
> Added UI test to B44044

- Xamarin.Forms.Platform.Tizen/Renderers/CarouselViewRenderer.cs
This PR is to fix the crash issue when ItemSource of CarouselView is null.
Fixes the crash issue when ItemSource of CarouselView is null.
None
- Tizen
None
No Change
Launches SmartHotel360 Application(https://github.com/Microsoft/SmartHotel360-Mobile)
> [Tizen] Fixes the crash issue when the Position of CarouselView is zero

- Xamarin.Forms.Platform.Android/Renderers/FormsWebChromeClient.cs
- Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs
The context is not always an Activity, for example running on the Previewer. Remove the Exception , handle fail gracefully with a Log warning 
- fixes #4107
none
None
- Android
IF running in the previewer you won't be able to open alerts or the file picker for a WebView.
Not applicable
Check if the previewer doesn't crash in a Xaml page with a <WebView>
> VS bug [#730672](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/730672)
> [Android] Remove WebViewRenderer dependency on Activity

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2580.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/LabelRenderer.cs
When setting the `HelpText` for accessibility on a `Label` it causes to set the `Hint` text on a `TextView` . 
Later when we are Measuring it  Android will take the Hint text size in account and return wrong sizes that won't fit just the text but hint also. 
We need to clear the Hint before measure.
Trying to move the calls to set hint to other places is no good because sizing is called sometimes multiple times when text is changing. 
- fixes #2580
None
- Android
Labels with HelpText with size correctly 
BEFORE:
AFTER:
Go to issue 2580 make sure the 2 rows look the same.
> [Android] Fix Label size when using Hint text

- Xamarin.Forms.Core/FontSizeConverter.cs
Enum.TryParse is quite expensive. replace that by simple value check for
known values. Keep the TryParse as a safeguard in case we ever add new
values to it.
/
None
None
Not applicable
> [C] avoid Enum.TryParse for resolving NamedSizes

- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4319.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4319.xaml.cs
- Xamarin.Forms.Xaml/MarkupExtensions/OnIdiomExtension.cs
- Xamarin.Forms.Xaml/MarkupExtensions/OnPlatformExtension.cs
Up to now, OnPlatform and OnIdiom markup extensions were checking for
type converters on
- target type
- the property being set
in case of a bindable property, the converter on the BP getter or
GetBP() static method (for attached BPs) wasn't checked.
This PR adds the check for that, plus a unit test.
- fixes #4319
None
None
Not applicable
> [Xaml] OnIdiomMarkupExt uses converters on BPs

- Xamarin.Forms.Platform.Android/AppCompat/ImageButtonRenderer.cs
ImageButton Renderer for Android didn't provide overrides that are consistent with other renderers for hooking into element and element property change events
Added the following methods to the ImageButtonRenderer
```C#
protected virtual void OnElementChanged(ElementChangedEventArgs<ImageButton> e);
protected virtual void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e);
```
- Android
Add a custom ImageButtonRenderer for Android
> [Android] add Element and Element Property Changed hooks for ImageButton

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4484.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/GalleryPages/TitleView.xaml.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ImageElementManager.cs
Set the ImageViews drawable to null otherwise when the view is removed it tries to recreate the imageview because of leaks
- fixes #4484 
- Android
Run the added UI Test (4484) and rotate the device a bunch
> [Android] set image to null when view is disposed

- Xamarin.Forms.Xaml.UnitTests/ApplyPropertiesVisitorTests.cs
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
There is a line with the following content prior to the changed one:
```C#
ProvideValue(ref value, node, source, XmlName.Empty);
```
`ProvideValue` executes `IMarkupExtension` and `IValueProvider`. However, the modified `value` was ignored and `Values[node]` was used instead. This change fixes the problem.
None
None
None
Not applicable
> [Xaml] Add provided value to collection

- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
Fixes tabulation from element with a `TabStop` is false
None
- Android
Tabulation doesn't stop working on the elements in which the `TabStop` is false
Not applicable
- run UItest 1700
- select text box without TabStop (the page background turns red)
- press `Tab` key on keyboard
- check that the focus has changed
> [Android] fix tabs from element with a tabstop false

- Xamarin.Forms.Core/BindingExpression.cs
- Xamarin.Forms.Core/TypedBinding.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4516.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4516.xaml.cs
This PR does 3 things:
- In case of Binding path with indexer, lookout for
IndexOutOfRangeException in addition to KeyNotFoundException.
- in case of KeyNotFound or IndexOutOfRange, use the FallbackValue if
any.
- in case of an uncaught exception, throw that exception instead of a
TargetInvocationException.
- fixes #4516
None
None
Not applicable
> [C] fallback nicely in case of IndexOutOfRangeEx

- Xamarin.Forms.Platform.MacOS/Renderers/WebViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/WebViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs
Accidentally discovered #2952 on my own while fixing #4254.
On a succesful load, all `WebView`s set the Source property to a new `UrlWebViewSource` with the current url, presumably to keep the Url property of the `UrlWebViewSource` in sync in the case that the provided url resulted in a redirect. On all platform besides iOS/macOS, this behavior is skipped if the value of the current url indicates that the WebView has loaded local html instead of content from a remote server. On iOS/macOS, the source will be converted to a `UrlWebViewSource` even if a `HtmlWebViewSource` is what was used to the load the content.
This fix aligns macOS and iOS with the behavior of the other platforms.
- fixes #2952
None
- macOS
- iOS
A webview that is using `HtmlWebViewSource` that is bound to an element and …
> [iOS, macOS] Fix WebViews using HtmlWebViewSource switching to UrlWebViewSource

- Xamarin.Forms.Controls/ControlGalleryPages/AppearingGalleryPage.cs
- Xamarin.Forms.Platform.Android/AppCompat/CarouselPageRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/CarouselPageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/CarouselPageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
Handling appearing and dissapearing of CarouselPage
- fixes #2951 
None
- iOS
- Android
None
Not applicable
> [iOS,Android] Handle Appearing/Disappearing on CarouselPage

- Xamarin.Forms.Core/Cells/SwitchCell.cs
- Xamarin.Forms.Platform.Android/Cells/SwitchCellRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ActivityIndicatorRenderer.cs
- Xamarin.Forms.Platform.iOS/Cells/SwitchCellRenderer.cs
Added OnColor property for changing color of SwitchCell on Android & iOS
- fixes #4027
Added:
- Color OnColor { get; set; } //Bindable Property
- UpdateOnColor() //Method to set/update the SwitchCell color
- iOS
- Android
> Switchcell oncolor

- Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs
- Xamarin.Forms.Platform.iOS/CollectionView/CollectionViewController.cs
- Xamarin.Forms.Platform.iOS/CollectionView/CollectionViewRenderer.cs
CollectionView on iOS is not watching for changes to entire items source; this change adds the watch and updates the view accordingly.
- fixes #4474
None
- iOS
None
Not applicable
In Control Gallery, navigate to CollectionView Gallery -> Snap Points Gallery and choose any option. In the "Item Count" Entry, change the number and hit the "Update" button. The number of items in the collection should change.
> Add missing update of items source for iOS CollectionView

- Xamarin.Forms.Platform.Android/AppCompat/ImageButtonRenderer.cs
ImageButton sets it's own tag but it doesn't need to for any reason and this is breaking how it interacts with Glide
https://github.com/jonathanpeppers/glidex/issues/16#issuecomment-441718177
- Android
> [Android] don't set the tag on ImageButton

- Xamarin.Forms.Platform.UAP/TitleViewManager.cs
- Xamarin.Forms.Platform.UAP/ViewToRendererConverter.cs
If a control rendered by `ViewToRendererConverter` is off the screen sizes of the control could be negative, which caused an error. To avoid exception a control don't call Arrage and the panel becomes completely transparent.
- fixes #4463 
- fixes #4116
None
- UWP
When you change the width of the TitleView, the width of the control automatically changes.
Not applicable
- Go to Navigation Control Gallery (Legacy) which should render a searchbar in the header
- Size the window down horizontally so that the SearchBar is no longer in view
- Сrash should not be
> [UWP] fixes control render by ViewToRendererConverter in off screen

- Xamarin.Forms.Core/BindingExpression.cs
- Xamarin.Forms.Core/TypedBinding.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2752.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2752.xaml.cs
if the FallbackValue isn't set, returns the value created by the
defaultValueCreator instead of the DefaultValue when a binding can not
be resolved.
- fixes #2752
None
None
Not applicable
> [binding] return defaultValueCreator on failure

- Xamarin.Forms.Core.UnitTests/WeakEventManagerTests.cs
- Xamarin.Forms.Core/WeakEventManager.cs
When an event has two subscriptions to the same handler,
unsubscribing cleared all the handlers, not only one.
I added a break to stop unsubscribing after the first successful one.
I think this was not reported before.
None
Core
Subscribing to a weak event twice and unsubscribing once will unsubscribe only once.
Not applicable
I found the issue in a unit test, where doing a swap of two elements in a modified ObservableCollection made one of them lose all the PropertyChanged subscriptions.
> Fix edge case in unsubscribing weak events

- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewNullGallery.xaml
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewNullGallery.xaml.cs
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Platform.Android/CollectionView/EmptySource.cs
- Xamarin.Forms.Platform.Android/CollectionView/ItemsSourceFactory.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
- Xamarin.Forms.Platform.iOS/CollectionView/CollectionViewController.cs
- Xamarin.Forms.Platform.iOS/CollectionView/CollectionViewRenderer.cs
- Xamarin.Forms.Platform.iOS/CollectionView/EmptySource.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsSourceFactory.cs
- Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
The CollectionView on Android and iOS throws an exception if no `ItemsSource` is set before the renderers kick in. This change allows both platforms to handle a `null` `ItemsSource`.
- fixes #4366 
None
- iOS
- Android
None
Not applicable
In Control Gallery, navigate to CollectionViewGallery -> EmptyView Galleries -> EmptyView (null ItemsSource). Navigation should be successful and the application should not crash.
> Modify Android and iOS adapters to handle null items sources

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4026.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/FormattedString.cs
- Xamarin.Forms.Core/Label.cs
- Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
When the FormattedText was changed we invalidate measure before the Text was update on the control. 
[iOS]
Hook the PropertyChanging event to clear the perfectSize cache
- fixes #4026 
None
The invalidate measure is called after PropertyChanged.
Not applicable
Go to issue 4026 on the gallery, add tab "Add More Text to Span", make sure all text is shown. Click it more times to see new lines are added and it always shows all new texto added.
> [Core]Call invalidate measure after the FormattedText is set

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4314.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4341.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/GalleryPages/EditableList.cs
- Xamarin.Forms.Platform.iOS/ContextActionCell.cs
- Xamarin.Forms.Platform.iOS/ContextScrollViewDelegate.cs
Clear the global closer delegate from ContextActionCell when disposing. 
- fixes #4314 
None
- iOS
None
Not applicable
Use issue 4314 gallery page.
Swipe the 2 cell to reveal content actions and delete both items. 
Should go the other page without crash
>  [iOS] Clear the delegate from ContextActionCell 

- Xamarin.Forms.Maps.WPF/MapRenderer.cs
On WPF, if there are any pins set on the Map, they are not being loaded.
- WPF
> WPF - Map - Fix initial load of pins

- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
In addition to #4579 that check, in the tool, that the extra
method isn't present, this protects the task itself from being ran
twice.
Both fixes are required for extra performance and safety.
This also removes the last reference to the original name of the tool.
But I'll still remember it fondly, and use it in internal conversations.
- fixes #4563
None
None
Not applicable
> [build] add a stamp file to shamehat

- .nuspec/Xamarin.Forms.nuspec
Xamarin Essentials takes a dependency on Custom Tabs 27 and has not yet been updated to 28.  XF MonoAndroid90 takes a dependency on support 28. Because of this, if you install essentials into the shared library it will cause build errors on the android project (or currently it will cause VS to crash)
Once essentials creates a target for MonoAndroid90 and support28 then we can remove this if we want. Though it's probably best to keep it so that the user experience is always maintained
- Android
- create android project from template
- set TFV of android project to 9.0
- install this nuget
- install essentials into netstandard project
> Add custom tabs to MonoAndroid90 nuspec to improve essentials experience

- Xamarin.Forms.Core/Application.cs
- Xamarin.Forms.Core/BindableObject.cs
- Xamarin.Forms.Core/ListView.cs
The fix proposed in #2911 didn't worked with Release build of XF, aka
the majority of the builds used.
This fix allows the developer to set any logger he might like, but the
plan is to add a default one in the template, that uses Debug.WriteLine,
so it will Log if the user application is build with Debug, and not if
XF binaries are.
This also changes 2 remaining `Debug.WriteLine` into `Log.Warning` in the `Core`
- fixes #1517
- fixes #3873
Added:
- `public static Action<(string Category, string Message)> Application.LogWarningsListerner {get; set;}`
None
Not applicable
> [C] Expose Application.LogWarningsListener

- Xamarin.Forms.Core/Shell/Shell.cs
do not crash anymore while navigation to `app:///home/foo` (without a trailing slash)
/
None
None
Not applicable
> [Shell] allow missing trailing slash on uri

- Xamarin.Forms.Core.UnitTests/ShellTests.cs
- Xamarin.Forms.Core/Shell/BaseShellItem.cs
- Xamarin.Forms.Core/Shell/QueryPropertyAttribute.cs
- Xamarin.Forms.Core/Shell/Shell.cs
- Xamarin.Forms.Core/Shell/ShellContent.cs
- Xamarin.Forms.Core/Shell/ShellGroupItem.cs
~~NOTE: please merge #4595 first, and rebase this on top~~
Allow uri navigation with queryParams. queryParams can be applied
to:
- the ShellContent (if inherited)
- the Content (or inflated ContentTemplate) of the ShellContent
- the BindingContext of the Content
those 3 can inherit an interface and handle the queryParams, or
the types can be decorated with some [QueryProperty] attributes.
Attributes are handled on the 3 typesL ShellContent, actual content,
or bindingcontext.
- fixes #4596
None
None
Not applicable
> [Shell] Allow queryParams navigation

- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/GroupHeaderStyle.cs
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/ListView.cs
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
Created possibility to manage group header style from shared code. (Currently it's impossible at all as related class is incapsulated)
fixes https://github.com/xamarin/Xamarin.Forms/pull/4002#issuecomment-431049817
So, it will allow to set Grouped style and avoid such issues
Added: ( Xamarin.Forms.PlatformConfiguration.iOSSpecific.ListView)
- GroupHeaderStyleProperty
- SetGroupHeaderStyle (and 1 override)
- GetGroupHeaderStyle
Added: GroupHeaderStyle enum in the same namespace
- Core
- iOS
Add next line of code to Bugzilla34912 after list declaration and see that Grouped style is applied (like on Android)
```csharp
Xamarin.Forms.PlatformConfiguration.iOSSpecific.ListView.SetGroupHeaderStyle(list, PlatformConfiguration.iOSSpecific.GroupHeaderStyle.Grouped);
```
> [Enhancement] Added GroupHeaderStyle property for iOS specific ListView class

- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Build.Tasks/XamlGenerator.cs
avoid feeding Mono.Cecil with dupes. Removes a negligeable handful
of milliseconds (100ms on average, hard to measure) from XamlC. Even
less from XamlG.
- fixes #4620
None
- Build
None
Not applicable
> [tasks] avoid passing dupe assemblies to Cecil

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2102.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/NavigationPageRenderer.cs
Fixes throws NullReferenceException on empty NavigationPage
- fixes #2102
- start UITest 2102 in ControlGallery
- the application shouldn't throw an exception
/
- UWP
> [UWP] Fixes throws NullReferenceException on empty NavigationPage

- Xamarin.Forms.Build.Tasks/MethodDefinitionExtensions.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Core.UnitTests/TypedBindingUnitTests.cs
- Xamarin.Forms.Core/TypedBinding.cs
- Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4102.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4102.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4103.xaml.cs
Instead of relying on a NRE behing thrown while trying to evaluate a
compiled binding getter, detect the null value and fail faster, without
throwing. This require changing the type of the getter so they return a
(TProperty, bool) value tuple indicating the success.
You can test this by putting a breakpoint on https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/TypedBinding.cs#L201 and make sure it's not hit while debugging the test included in this PR
- fixes #4102
None
None
Not applicable
> [XamlC] test for null in Binding paths

- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
- Xamarin.Forms.Core/XmlnsDefinitionAttribute.cs
- Xamarin.Forms.Core/XmlnsPrefixAttribute.cs
Expose the XmlnsPrefixAttribute, that can be used by external tools to
support object tree serialixation to Xaml.
- fixes #3191
None
None
Not applicable
> [Xaml] expose XmlnsPrefixAttribute

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4187.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/GalleryPages/CarouselPageGallery.cs
- Xamarin.Forms.Platform.Android/AppCompat/PickerRenderer.cs
- Xamarin.Forms.Platform.Android/IPickerRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/DatePickerRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/PickerEditText.cs
- Xamarin.Forms.Platform.Android/Renderers/PickerRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/TimePickerRenderer.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
The picker dialog is shown only if the focus was obtained by tabulation or touch event.
- fixes #4318
- fixes #4187
- fixes #4494
None
- Android
Before
http://recordit.co/IULOwzWY2k
After
http://recordit.co/GjiYmiSFQv
**In cell**
- run UItest 4187
- single click on the Picker and select any option
- click on any TextBox (the dialogue with the options of the picker should't open)
**Carousel page**
- run UItest 4187
- single click on the upper Picker and select any option
- swipe to next page (the dialogue with the options of the picker should't open)
**Tab stops**
- run UItest 1700
- single click on the Picker and select any option
- check that the Picker's dialogue opens if he gets the focus at the tabulation
> [Android] fixes Picker list showing up incorrectly when focus is set on other controls

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4597.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Extensions/ImageViewExtensions.cs
Set the ImageView to null if the ImageSource is set to null. 
Fix ImageCell 
- fixes #4597
- fixes #4584
None
- Android
Go to the included UI test and follow the instructions
> [Android] Fix ImageSource being set to null and fix ImageCell so it loads images

- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4572.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4572.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/LoaderTests.cs
This adds a test for #4572, as we were only testing that case with XamlC off in LoaderTests.
- closes #4572
None
None
Not applicable
> [test] add passing test for #4572

- Xamarin.Forms.Core/Shell/Shell.cs
[Shell] expose CurrentShell
- fixes #4625
None
- Core/XAML
None
Not applicable
> [Shell] expose CurrentShell

- Xamarin.Forms.Platform.Android/Renderers/ColorChangeRevealDrawable.cs
- Xamarin.Forms.Platform.Android/Renderers/ShellItemRenderer.cs
Fixes crashes in Bottom Navigation Tabs
- fixes #4382
None
- Android
None
Not applicable
- run the Shell Control Gallery project
- click between the bottom tabs quickly
- app shouldn't crash
- click `More` button and select any tabs
- app shouldn't crash
> [Shell][Android] fixes crash when switching Bottom Navigation Tabs too fast or click on More menu

- .editorconfig
Added the .NET Foundation code style:
- https://github.com/dotnet/corefx/blob/master/.editorconfig
- https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md
Also added the few variances:
- https://github.com/xamarin/Xamarin.Forms/blob/master/.github/CONTRIBUTING.md
Variances:
```
[*]
insert_final_newline = false
[*.cs]
indent_style = tab
dotnet_style_require_accessibility_modifiers = never:suggestion
csharp_style_var_for_built_in_types = true:none
csharp_style_var_when_type_is_apparent = true:none
csharp_style_var_elsewhere = false:none
dotnet_naming_style.static_prefix_style.capitalization = pascal_case 
[*.{xaml}]
indent_size = 2
```
> Added the style from .NET Foundation plus variances

- .create-nuget.bat
Fix local nuget creation script so https://github.com/xamarin/Xamarin.Forms/issues/4444 can more easily debug, get stack traces, add logging, etc. 
Update .nuspec broke old script. 
```
set nuget_dir=c:\downloads\nuget\etc-to-exe\
.create-nuget.bat [all|droid|ios]
```
> GH 4444; Fix local nuget build script

- Directory.Build.props
- EmbeddingTestBeds/Embedding.XF/Embedding.XF.csproj
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- PagesGallery/PagesGallery.UWP/PagesGallery.UWP.csproj
- PagesGallery/PagesGallery.iOS/PagesGallery.iOS.csproj
- PagesGallery/PagesGallery/PagesGallery.csproj
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Copying `<PropertyGroup>`s on (almost) every .csproj, and get the
relative paths just right is tedious. Starting msbuild 15 (vs2017)
we can use a Directory.Build.props (and Directory.Build.targets)
so I see no reason why we shouldn't.
see https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2017
/
None
/
None
Not applicable
> [build] add a Directory.Build.props

- .nuspec/Xamarin.Forms.props
- .nuspec/Xamarin.Forms.targets
The `$(MSBuildSDKsPath)` is actually *always* set whenever there are MSBuild SDKs 
*installed*, not necessarily when the current project is an SDK-style project itself. 
This means that we're potentially adding duplicate items and otherwise disrupting 
normal operation of the non-SDK style projects with this import. 
So use the well-known properties that are set by the .NET [Sdk.props](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props#L22-L27) file instead, 
which is the first imported target even before nuget-provided .props files.
> Properly detect SDK style projects

- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- removed the no longer used "armeabi" target. DEV16 won't deploy to android with this set
- set ios httpclient implementation to NSUrlSession. This is the default used by the templates
> remove armeabi and set HttpClient Implementation on iOS to NSUrlSession

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4597.cs
Add some delay before testing if images vanished on iOS
> delay ui test a bit so elements can vanish first

- Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj
- Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj
- Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj
- Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
Though not perfectly ideal you can disable only active solution checking so that NUnitTestAdapters work on the Xamarin UI test projects
https://github.com/nunit/nunit-vs-adapter/issues/174
I'm currently using this for Dev16 to run UI Tests
- uninstall vsix for nunit test adapter
- disable active solution checking (based on the picture above)
-make sure UI tests still run
> Add NUnitTestAdapter to xamarin ui test projects so VSIX isn't required for running UI Tests

- Xamarin.Forms.Platform.Android/Renderers/IPopupTrigger.cs
- Xamarin.Forms.Platform.Android/Renderers/PickerEditText.cs
- Xamarin.Forms.Platform.Android/ViewRenderer.cs
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
fixes pop-up dialog in Pickers when you call `Focus()`
- fixes #
None
- Android
None
- test Bugzilla41424 should passes.
> [Android] fixes pop-up dialog in Pickers when you call Focus()

- .nuspec/Xamarin.Forms.Maps.nuspec
- .nuspec/Xamarin.Forms.nuspec
- EmbeddingTestBeds/Embedding.Droid/Embedding.Droid.csproj
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
- Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj
- Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutTemplatedContentRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Update android support libraries to the latest preview9. These also fixed an issue with *IOnOffsetChangedListener* which could now be added back in 
- Android
> update support libraries to preview9 and uncomment no longer broken interface

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4600.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ItemAdder.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ObservableCodeCollectionViewGridGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ObservableCollectionGallery.cs
- Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs
- Xamarin.Forms.Platform.iOS/CollectionView/CollectionViewController.cs
- Xamarin.Forms.Platform.iOS/CollectionView/CollectionViewRenderer.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
- Xamarin.Forms.Platform.iOS/CollectionView/TemplatedCell.cs
- Xamarin.Forms.Platform.iOS/CollectionView/VerticalTemplatedCell.cs
Normally the CollectionView on iOS uses the first available cell as a prototype to determine the estimated size (or exact size) of subsequent cells. But if there is no first available cell when the CollectionView first appears, the estimates remain zero and new cells are added, but are not visible. 
These changes allow the CollectionView to use the first available cell even if there is no data when the CollectionView first appears.
- fixes #4600
None
- iOS
None
Not applicable
Added an automated test; for manual testing, in Control Gallery navigate to CollectionView Gallery -> Observable Collection Galleries -> Add/Remove Items (Grid, Initially Empty) and click the Insert button; an item should appear. Click the button again; another item should appear, and both items should be the same …
> [iOS] Update cell size estimates after empty data source

- Xamarin.Forms.Build.Tasks/MethodReferenceExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/MethodReferenceExtensionsTests.cs
`Xamarin.Forms.Build.Tasks.ResolveGenericParameters` treats generic parameters as special, but return type can also be generic. Handle it in a similar way.
I recommend to merge this before #4238 because it increases probability to encounter a method with such return type.
I have not opened an issue for the problem this issue addresses.
None
None
Not applicable
An automated test is available.
> [XamlC] Resolve generic parameters of a method with generic return type

- Xamarin.Forms.Controls/CoreGalleryPages/PickerCoreGalleryPage.cs
- Xamarin.Forms.Core/Picker.cs
- Xamarin.Forms.CustomAttributes/TestAttributes.cs
- Xamarin.Forms.Platform.Android/AppCompat/PickerRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/PickerRenderer.cs
- Xamarin.Forms.Platform.UAP/PickerRenderer.cs
- Xamarin.Forms.Platform.UAP/Resources.xaml
- Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
The user is now able to set a color for the Picker.Title property.
- fixes #4669
Added:
- Color Picker.TitleColor { get; set; } //Bindable Property
- iOS
- Android
- UWP
As far as I can tell, other platforms do not show a title/placeholder at this time
When using this new property, the title, as visible on the respective platform, will adhere to the color set by the user.
> [C, iOS, AND, UWP] Color for Picker.Title

- Xamarin.Forms.Platform.Tizen/Cells/SwitchCellRenderer.cs
Added `OnColor` property for changing color of `SwitchCell` on Tizen. This PR is an addendum to the changes in #4036.
- implements tizen part of #4027
None
- Tizen
None
Use [SwitchCellListPages](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Controls/GalleryPages/CellsGalleries/SwitchCellListPage.cs)
> [Tizen] Supports SwitchCell.OnColor

- Xamarin.Forms.Platform.Android/ViewRenderer.cs
Fixes a UI test crash in 30935.
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.FormsEditText'.
12-17 13:17:21.290 I/MonoDroid(15560):   at Android.Views.View.RequestFocus () [0x0000a] in <0266c7f7d18f4d3580215846af2399e2>:0 
12-17 13:17:21.290 I/MonoDroid(15560):   at Xamarin.Forms.Platform.Android.ViewRenderer`2[TView,TNativeView].<OnFocusChangeRequested>b__30_0 () [0x00031] in <e7fd999147d542de8f25a4543d0d9869>:0 
12-17 13:17:21.290 I/MonoDroid(15560):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <0266c7f7d18f4d3580215846af2399e2>:0 
12-17 13:17:21.290 I/MonoDroid(15560):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in …
```
> [Android] Avoid acting on a disposed reference

- Xamarin.Forms.Build.Tasks/CompiledConverters/RDSourceTypeConverter.cs
- Xamarin.Forms.Build.Tasks/CompiledMarkupExtensions/ArrayExtension.cs
- Xamarin.Forms.Build.Tasks/CompiledValueProviders/SetterValueProvider.cs
- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Build.Tasks/MethodReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/NodeILExtensions.cs
- Xamarin.Forms.Build.Tasks/SetFieldVisitor.cs
- Xamarin.Forms.Build.Tasks/SetNamescopesAndRegisterNamesVisitor.cs
- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Build.Tasks/VariableDefinitionExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4238.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4238.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/MethodReferenceExtensionsTests.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/TypeReferenceExtensionsTests.cs
XamlC often uses single instruction `ldloc` to load a local variable to stack to use as an argument for a method, but the instruction does not do necessary type conversion. For example, the following XAML code does not work because it does not box value type where `collections` is `clr-namespace:System.Collections;assembly=mscorlib`:
```XAML
<collections:List>
<x:Single>0</x:Single>
</collections:List>
```
Some code emitting `ldloc` emits implicit casting code and boxing/unboxing instructions as well, but such code are duplicated over the codebase and the behavior is inconsistent.
This change introduces an internal method `Xamarin.Forms.Build.Tasks.VariableDefinitionExtensions.LoadAs` rather than duplicating such type conversion code even more after all `ldloc` emission and checking they …
> [XamlC] Always enable implicit casting and boxing and unboxing

- Xamarin.Forms.Build.Tasks/CreateObjectVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4751.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4751.xaml.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
In case of runtime parse, wrap the MissingMethodException in a
XamlParseException, to get lineInfo. In case of XamlC, detect missing
constructor and fail early.
- fixes #4751
None
None
Not applicable
> [X] throw XPE on missing element .ctor

- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4782.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs
- Xamarin.Forms.Platform.Android/AppCompat/ImageButtonRenderer.cs
Forms just sets the default Drawable to "Transparent" so the Drawable is never null. 3rd party libraries that implement their own handlers won't do this though so need to check if Drawable is null. 
- fixes #4782
- Android
There aren't any.  I added a custom renderer UI test to replicate setting Drawable to null but there's no way to manually test outside of just making sure changes don't appear to cause more breaks.
You can check the ImageButtonGallery just to makes sure all seems correct
> [Android] Check if Drawable is null in Draw override on ImageButton

- Xamarin.Forms.Core.UnitTests/WeakEventManagerTests.cs
- Xamarin.Forms.Core/Command.cs
- Xamarin.Forms.Core/ImageSource.cs
- Xamarin.Forms.Core/WeakEventManager.cs
As pointed in https://github.com/xamarin/Xamarin.Forms/issues/4750#issuecomment-447673540,
internal WeakEventManager usage can be simplified.
This also updates the code to ValueTuple, throw expressions, ...
/
None
None
Not applicable
> [C] WeakEventManager minor changes

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4760.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh4760.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/TypeReferenceExtensionsTests.cs
See #4047 for full description. This PR cherry-pick the commit from #4047 and adds a Xaml unit test.
- fixes #4760
- closes #4047
None
None
Not applicable
> [XamlC] instantiate generic parameter on base types

- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewTemplateGallery.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2756.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2756.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3539.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Issue1438.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Issue1549.cs
- Xamarin.Forms.Xaml.UnitTests/MarkupExpressionParserTests.cs
- Xamarin.Forms.Xaml/MarkupExpressionParser.cs
- Xamarin.Forms.Xaml/MarkupExtensionParser.cs
This is a breaking change as we weren't throwing errors on that before.
- fixes #2756
None
None
Not applicable
> [Xaml] require escaping curly braces

- Xamarin.Forms.Build.Tasks/XamlCTask.cs
- Xamarin.Forms.Core/Internals/ResourceLoader.cs
- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
- Xamarin.Forms.Xaml.UnitTests/DesignPropertiesTests.cs
- Xamarin.Forms.Xaml.UnitTests/ResourceLoader.xaml.cs
- Xamarin.Forms.Xaml/Properties/AssemblyInfo.cs
- Xamarin.Forms.Xaml/PruneIgnoredNodesVisitor.cs
- Xamarin.Forms.Xaml/RemoveDuplicateDesignNodes.cs
- Xamarin.Forms.Xaml/XamlLoader.cs
- Xamarin.Forms.Xaml/XamlParser.cs
An alternate xaml resource file provider can request the XamlLoader to
_not_ ignore normally ignored properties in prebuilt XF design xmlns, as
in the following snippet:
```xaml
<ContentPage
xmlns="http://xamarin.com/schemas/2014/forms"
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
xmlns:d="http://xamarin.com/schemas/2014/forms/design"
xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
mc:Ignorable="d">
<Label d:Text="Bar" Text="Foo" x:Name="label" />
</ContentPage>
```
The `d:` should be the prefix used by default for this, but any other
prefix will do too.
The `d:Text` property maps to the exact same property as `Text`, as the
XmllnsDefinitionAttributes are identical (that's convenient from a Intelisense
point of view), but, when (and only when) instructed …
> [X] Design time properties

- Xamarin.Forms.Platform.Tizen/Native/Dialog.cs
- Xamarin.Forms.Platform.Tizen/Native/Watch/WatchDialog.cs
- Xamarin.Forms.Platform.Tizen/Renderers/PickerRenderer.cs
Added `TitleColor` property for setting color for the  `Picker.Title`  and `FontSize`/`FontFamily`/`FontAttributes` as well. This PR is an addendum to the changes in #4701 and #662.
- implements tizen part of #4669 
- implements tizen part of #662 (for Picker)
None
- Tizen
Just like other platforms, on Tizen, the visual representation of a Picker is now similar to a `Entry` (not a `Button`). Plus, `Title` is shown as a placeholder.
| Before  | After |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/1029134/50319643-c1759b00-050b-11e9-816d-71e535e822a0.gif" width="300">  | <img src="https://user-images.githubusercontent.com/1029134/50319671-dd793c80-050b-11e9-834f-1d8ba89073be.gif" width="300">  |
Use `ControlGallery` (Picker Gallery)
> [Tizen] Supports Picker.TitleColor, FontSize, FontFamily and FontAttr

- Xamarin.Forms.Core/ListView.cs
Remove `[EditorBrowsable(EditorBrowsableState.Never)]` attribute from `ListView.CachingStrategy` property. This will make it visible to Intellisense for auto-completion in XAML in Visual Studio.
- fixes #4738 (partially)
None
None
Not applicable
Create a new ContentPage; add a ListView in XAML; CachingStrategy should show up in Intellisense.
> Make ListView CachingStrategy property visible to Intellisense

- Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/TypeReferenceExtensionsTests.cs
tl; dr `Foo<bool>` and `Foo<string>` are different types
The change may be a bit confusing. `InheritsFromOrImplements` compares the results of `ResolvedCached`, but the method strips the generic arguments. . We have already compared the original types at the very beginning of `InheritsFromOrImplements` so we don't have to compare again at all.
I was too lazy to open an issue again.
None
None
Not applicable
> [XamlC] Test generic parameters to evaluate equality of types

- Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs
- implements item movement in observable collection for #3172
None
- iOS
Automated tests will be available once #4697 is merged.
> [iOS] Implement item move on iOS CollectionView

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4748.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.GTK/Renderers/ListViewRenderer.cs
Added case in GTK listviewrender for change of SelectedItem property.
- fixes #4748
none
- GTK
None
Not applicable
I've added Issue4748.cs with basic example. Without fix, clicking button does not update selected item highlight in list. With fix, last item in list become highlighted, as it should.
I didn't understand, how to run UI tests locally, so I didn't made one.
> Added case in GTK listviewrender for change of SelectedItem property

- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/PageRenderer.cs
Once a background is set on the page, it can never be unset.
- fixes #
None
- Android
Setting a page background to an image, and then setting it to null will now actually set the page to no image. Previously, the image stayed.
Not applicable
- Create a page
- Set the background to a valid image
- _observe the image_
- Set the background to null
- _observe the blank page_
> [Android] Allow the page background to be reset

- Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutContentRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ShellItemRenderer.cs
If an Icon is specified on a ShellSection that doesn't exist it was causing an NRE when trying to dispose of it
> [Android] If drawable specified on shell doesn't exist don't dispose of it

- Xamarin.Forms.Platform.Android/AndroidTicker.cs
PR #4177 attempts to fix an issue with disabling the Android timer on a non-UI thread by using BeginInvokeOnMainThread, which posts the action to the main looper to be run later on the UI thread. 
But if the call to DisableTimer is happening because the Ticker itself has finished all of the pending actions, DisableTimer needs to be called immediately in order to end the animations so that awaited animation calls can return. Since the animations are running on the UI thread to begin with, these calls to DisableTimer are _already_ on the UI thread; they don't _need_ to be posted there for later invocation.
This change adds a check in DisableTimer to see if it's already on the UI thread; if so, it is executed immediately. Otherwise, it is posted to the UI thread.
- fixes bug where awaited …
> [Android] Only post DisableTimer to the queue if it's not on the UI thread

- Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs
ListViewRenderer has in the method "UpdateIsRefreshing" that has part that is run asynchronously using post. There is no check in the action if the control has been disposed in the meantime. 
Stacktrace:
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
SwipeRefreshLayout.set_Refreshing (System.Boolean value)
ListViewRenderer.<UpdateIsRefreshing>b__28_0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
None
- Android
None (less crashes)
Not applicable
Be very unlucky. (We just see this happen in our crash reports sometimes)
> [Android] Fix for ListViewRenderer causing ObjectDisposedException

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2818.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailContainer.cs
- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailPageRenderer.cs
fixes Right-to-Left Hamburger icon in MasterDetailPage 
- fixes #2818
None
- Android
None
**Before**
**After**
- In ControllGalery run UItest 2818
- Hamburger icon on the main page should be on the right
> [Android] fixes Right-to-Left Hamburger icon in MasterDetailPage

- Xamarin.Forms.Platform.MacOS/Controls/FormsBoxView.cs
Force BoxViewRenderer to redraw itself after color/corners updates
fixes #4338 
None
- MacOs
Possible to change background color / color of boxView with bindings
Not applicable
Here is test scenario: https://github.com/Abhijit-Revamp/XamIssues
> [macOS] BoxView binding to BackgroundColor broken

- Xamarin.Forms.Platform.WPF/Renderers/BoxViewRenderer.cs
As was mentioned, that BoxView works fine with **Color** but doesn't with **BackgroundColor**
Set the same renderer's handler for both properties.
- fixes #4788 
None
- WPF
Can update BackgroundColor with bindings
Not applicable
Try to bind BackgroundColor of BoxView to VM's property
```xml
<BoxView
BackgroundColor="{Binding Color}"
HeightRequest="100"
WidthRequest="100" />
```
> BoxView.BackgroundColor binding does not work on WPF

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4597.cs
This should also be fine on iOS/Android as the extension is used in the other tests.
> [tests] UWP requires file extensions

- Xamarin.Forms.Platform.iOS/Renderers/DatePickerRenderer.cs
Disables all spellchecking and correction suggestions on iOS for the different Picker controls
- fixes #4629
None
- iOS
The user might've seen red squigglies before but won't now(?)
Not applicable
> Disable suggestions for all Pickers

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3652.cs
- Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
Because ListViews reuse renderers we need to clear the *_perfectSizeValid* value so that the size gets updated when the renderer is reused
- fixes #4957  
- iOS
Run Issue3652 in the control gallery and follow the steps there
> [ios] Clear perfect size on Labels so reused renderers will resize correctly

- Xamarin.Forms.Platform.Android/Extensions/TextViewExtensions.cs
Fixes an `ObjectDisposedException` thrown by `LabelRenderer` due to the `SpannableString` object being disposed in certain cases.
- Fixes #4864
None
Android
None
Not applicable
1. Use a Label inside a ViewCell DataTemplate for a ListView.
2. Add 10 or more rows of data.
3. Rotate the device between portrait and landscape.
4. No crash? Success!
> [Android] Avoid acting on a disposed SpannableString in LabelRenderer

- Xamarin.Forms.Platform.Android/FastRenderers/ImageElementManager.cs
- Due to a regression modify *ImageElementManager* to use *ViewCompat.SetClipBounds* so as to not cause crashing
I realize that there is a ClipBounds here in CollectionView code
https://github.com/xamarin/Xamarin.Forms/blob/154c2d088a385513e2819e524040b8afff8f6f7a/Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs#L48
But CollectionView is new code that only supports >= 19 so it wouldn't set a good precedence to fix CV to be compatible pre api 19
- fixes #4789
- Android
Run ImageButton Gallery on pre api 18 device
> [Android] set ClipBounds to use ViewCompat.SetClipBounds

- .create-nuget.bat
Add maps to private nuget package. 
>set NUGET_DIR=...
>set CREATE_MAP_NUGET=1
>.create-nuget.bat all
While investigating https://github.com/xamarin/Xamarin.Forms/issues/4919, unable run https://github.com/davidortinau/TheLittleThingsPlayground with private nuget packages because they don't include maps. 
Fix adds maps.
> .create-nuget.bat + maps

- Xamarin.Forms.Controls/CoreGalleryPages/SwitchCoreGalleryPage.cs
- Xamarin.Forms.CustomAttributes/TestAttributes.cs
- Xamarin.Forms.Platform.UAP/SwitchRenderer.cs
Implements the `Switch.OnColor` for UWP which was reported as a bug to be not working
- fixes #4460
None
- UWP
`Switch.OnColor` now actually works on UWP!
After: 
Added a case for this in the Switch Gallery app
> [UWP] Implementation of Switch.OnColor

- Xamarin.Forms.Core/FlexLayout.cs
We had null checks in 3 places, not the fourth one. and that case was
hit by #5001.
- fixes #5001
None
- Core (all platforms)
None
Not applicable
> [C] add null check for FlexLayout.OnPropChanged

- Xamarin.Forms.Core/Span.cs
Many have been bitten, including the undersigned, because of Span's default binding to OneTime:
See #2177, but also https://github.com/xamarin/Xamarin.Forms/issues/4451#issuecomment-449577935
A very good and lengthy description is in #3167
- fixes #3167
Changed TextProperty default binding mode from OneTime to OneWay.
None
Not applicable
> Changed Span default binding to OneWay

- Xamarin.Forms.Platform.UAP/CellControl.cs
Fixed bug where the switch in a `SwitchCell` in a `TableView` would disappear on UWP. The method for setting the default color was only called when it was in a `ListView`. Also renamed the method to be more clear.
- fixes #4903
None
- UWP
None
Not applicable
> [UWP] Fixed disappearing Switch on SwitchCell in TableView

- Xamarin.Forms.Platform.UAP/FormsProgressBar.cs
Native size crashes with infinity values.
- fixes #4982
None
- UWP
- Run Activity Indicator Gallery
- Select "Input Transparent View"
- App doesn't crash
> [UWP] fixes crashing ActivityIndicator with COMException

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3139.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.UAP/Platform.cs
In order for ActionSheet to be on top, we need to show it at the dialog box
- fixes #3139 
None
- UWP
- displaying `ActionSheet` on top, when page is the MainPage and it shows the dialog box.
- if page is not in visual tree, displaying `ActionSheet` at main window, instead Application crash.
> [UWP] Fixes hide DisplayActionSheet behind the dialog box

- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4561.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
In our implementation of `TabStop` in Android dropped the keyboard navigation via native settings `NextFocus<direction>Id`. For fix it added check if `NextFocus<direction>Id` property is set on focused view then returns the native function result. So, `NextFocus<direction>Id` takes precedence over the implementation of `TabStop`.
- fixes #4561 
None
- Android
Controls with custom renderer can use `NextFocus<direction>Id` to customize keyboard navigation.
Not applicable
- run UItest 4561
- select any textbox and try using the TAB key navigation
- focus should change from one textbox to another
> [Android] Fixes keyboard navigation in custom view

- Xamarin.Forms.Controls/CoreGallery.cs
This PR does 3 things:
- Adds basic search on the gallery home page _(there is that search box, there are those hundreds of pages, there is a need to find a particular page)_
- Adds context menus to allow the visual to be defined when navigating _(because we really don't want to rewrite all the tests)_
- Adds sorting to the pages list _(to help us find things)_
None.
None.
None.
None.
| Android | iOS |
| :-: | :-: |
| <img src="https://user-images.githubusercontent.com/1096616/51383923-71e2b900-1b23-11e9-8d34-5772e7b7c1ec.png" width="300" /> | <img src="https://user-images.githubusercontent.com/1096616/51385340-a2c4ed00-1b27-11e9-97b0-65604e87bdf7.png" width="300" /> |
> [Control Gallery] Basic Search + Visual Selector

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5030.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
again fixes TabStops.
- fixes #5030
None
- Android
- run UItest 5030 and follow the instructions
> [Android] fixes app crash when next control in FocusSearch isn't focusable

- Xamarin.Forms.Platform.iOS/CollectionView/ScrollToPositionExtensions.cs
Using `MakeVisible` with `ScrollTo` methods on iOS positions the item at the start of the CollectionView (instead of merely getting it onto the screen). This change makes the scrolling behave as expected.
None
- iOS
None
Not applicable
In Control Gallery, navigate to CollectionView Gallery -> ScrollTo Galleries and select any of the options.
> [iOS] Fix ScrollTo MakeVisible positioning

- Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs
- Xamarin.Forms.Xaml.UnitTests/FactoryMethodMissingCtor.xaml.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- Xamarin.Forms.Xaml/XamlLoader.cs
Add a callback when object instantiation or creation fails, so the
previewer can replace it by an educated guess
/
None
None
Not applicable
> VS bug [#783305](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/783305)
> [X] add callback for previewer on failing ctor

- Xamarin.Forms.Xaml/ResourcesLoader.cs
Allow the previewer to use design flag on RDs
This is very unlikely to happen, but why not.
/
None
None
Not applicable
> VS bug [#783307](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/783307)
> Allow the previewer to use design flag on RDs

- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/DataTemplateGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ExampleTemplates.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/VariableSizeTemplateGridGallery.cs
- Xamarin.Forms.Core/Items/ItemSizingStrategy.cs
- Xamarin.Forms.Core/Items/ItemsView.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewRenderer.cs
Add ItemSizingStrategy to CollectionView in Core; 
Create test harness for ItemSizingStrategy changes; 
Handle ItemSizingStrategy and ItemSizingStrategy changes on iOS;
- partially implements #3172
Added:
public enum ItemSizingStrategy;
ItemsView.ItemSizingStrategy // Bindable Property
- iOS
None
Not applicable
Navigate to  CollectionView Gallery -> DataTemplate Galleries -> ItemSizing Strategy, select the different ItemSizingStrategies to see them in action.
> [iOS] Implement ItemSizingStrategy hint property for CollectionView

- Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
Allow the previewer to recover and continue on throwing property setters
or BindableProperties.
/
None
None
Not applicable
> VS bug [#783306](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/783306)
> [Xaml] Better handling of exception on properties

- Xamarin.Forms.Xaml/XamlServiceProvider.cs
avoid NRE
- fixes something in a previewer scenario. waiting for a unit test (@drewgillies )
None
None
Not applicable
> VS bug [#785735](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/785735)
> [Xaml] don't use context before checking it's not null

- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Controls/GalleryPages/MaterialProgressBarGallery.cs
- Xamarin.Forms.Material.iOS/MaterialProgressBarRenderer.cs
- Xamarin.Forms.Platform.Android/Material/MaterialProgressBarRenderer.cs
- Xamarin.Forms.Platform.Android/Resources/drawable/MaterialProgressBar.xml
- Xamarin.Forms.Platform.Android/Resources/values/styles.xml
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
fixes Linear Progress Indicator
- fixes #5008
None
- Android
Not applicable
- run [Material] ProgressBar Gallery
- check Visual Gallery
> [Android Material] Linear Progress Indicator

- Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- fixes #5138
None
None
Not applicable
> VS bug [#786686](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/786686)
> [Previewer] Fallback for factorymethod not found

- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/MultiItemRemover.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/MultiItemReplacer.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ObservableCollectionResetGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ObservableMultiItemCollectionViewGallery.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs
Update INotifyCollectionChanged handling for CollectionView on iOS to handle mutli-item Add, Remove, Replace, and Move notifications. 
- partially implements #3172 
None
- iOS
None
Not applicable
In Control Gallery, navigate to CollectionView Gallery -> Observable Collection Galleries -> [Multi-item add/remove, no index|Multi-item add/remove, with index].
> [iOS] CollectionView multi-item Add/Remove/Replace/Move

- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2756.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh2756.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh3539.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Issue1438.xaml
- Xamarin.Forms.Xaml.UnitTests/MarkupExpressionParserTests.cs
- Xamarin.Forms.Xaml/MarkupExpressionParser.cs
escaping required only if the string starts with `{`
- fixes #5152
None
None
Not applicable
> [X] only require escaping if starts with '{'

- .gitignore
- build.cake
- build.ps1
- build.sh
- build/steps/build-windows.yml
Set of cake targets for easily building/packaging/deploying Forms
- Clean for removing bin/objs
- Build for just building SLN
- NugetPack for packing into nugets 
- ./build.ps1 -Target NugetPack -ScriptArgs '-packageVersion="9.9.9-custom"'
- Currently only works on windows but could create a nuspec for ios or could convert nuspec files to nuspecsettings in cake
- ./build.ps1 -Target NugetPack  uses GitVersion.CommandLine to generate the version from the tag or the branch name if you haven't specified a package version at the command line
- VSMAC builds the correct multi targeted projects and opens the SLN in vmac.
- Currently there's a multi targeting bug with VSM that doesn't let it be opened
- DeployAndroid builds an apk and deploys it to a connected device and starts the gallery. 
- …
> Cake build script

- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
- Xamarin.Forms.Platform.UAP/Resources.xaml
- Fixed `EntryCell.Tapped` fire when EntryCell within a TableView.
- Fixed `Tapped` event for cell in ListView
- fixes #2318
- fixes #4901 
/
- UWP
**Test 1**
* Navigate to the UI test for 32040 in the Control Gallery.
* Tap the "Click Here" Label in the EntryCell.
**Test 2**
* In Control Gallery, navigate to Issue 935.
* Tap on "I have been selected:"
> [UWP] Fixes call Tapped event in EntryCellTextBox

- Xamarin.Forms.Platform.Android/Renderers/PickerRenderer.cs
As described in #4909, when the end-user is fast enough, it is possible to open multiple Picker dialogs. This PR fixes that.
- fixes #4909
None
- Android
None
Not applicable
> [AND] Fix opening of multiple Picker dialogs

- Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj
- Xamarin.Forms.Core.UnitTests/RegistrarUnitTests.cs
- Xamarin.Forms.Core/Registrar.cs
- Xamarin.Forms.Material.iOS/Xamarin.Forms.Material.iOS.csproj
The code was using the wrong key type when accessing the handler dictionary when checking for a default registered renderer.
- There's a UI Test
- Set Visual on Button to some random type (that's not a VisualMarker) and make sure it loads the AppCompatButton
- Download nuget and install it into an Android 8.1 project and set one button to visual and the other not. Make sure they both load appcompat
> Missing visual not falling back to registered default renderer

- Xamarin.Forms.Platform.Android/Renderers/StepperRenderer.cs
partially fixes #4956 [Android]
None
- Android
Stepper don't skipped from with TabStop
- Run Issue3872
- Tab Over controls
- You're able to tab to stepper
> [Android] fixes TabStop on Stepper Control

- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewTemplateGallery.xaml
- Xamarin.Forms.Core.UnitTests/PreviewerReflectionTests.cs
- Xamarin.Forms.Core/Element.cs
- Xamarin.Forms.Core/IElementController.cs
- Xamarin.Forms.Core/IMenuItemController.cs
- Xamarin.Forms.Core/Internals/IPlatform.cs
- Xamarin.Forms.Core/Internals/NavigationRequestedEventArgs.cs
- Xamarin.Forms.Core/MenuItem.cs
- Xamarin.Forms.Core/Page.cs
- Xamarin.Forms.Core/ToolbarItem.cs
- Xamarin.Forms.Platform.Android/AppCompat/Platform.cs
- Xamarin.Forms.Platform.Android/FormsApplicationActivity.cs
- Xamarin.Forms.Platform.Android/Platform.cs
- Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
- Xamarin.Forms.Platform.GTK/Platform.cs
- Xamarin.Forms.Platform.MacOS/Platform.cs
- Xamarin.Forms.Platform.MacOS/PlatformNavigation.cs
- Xamarin.Forms.Platform.Tizen/FormsApplication.cs
- Xamarin.Forms.Platform.Tizen/LightweightPlatform.cs
- Xamarin.Forms.Platform.Tizen/Platform.cs
- Xamarin.Forms.Platform.Tizen/TizenPlatformServices.cs
- Xamarin.Forms.Platform.UAP/Platform.cs
- Xamarin.Forms.Platform.WPF/Platform.cs
- Xamarin.Forms.Platform.iOS/Platform.cs
Reinstate and obsolete various internals that were modified in 3.5.
- fixes https://github.com/xamarin/Xamarin.Forms/pull/4235#issuecomment-461511061
This, but in reverse: https://github.com/xamarin/Xamarin.Forms/pull/4235#issuecomment-461689943
- iOS
- Android
- UWP
None
Not applicable
> Reinstate and obsolete IPlatform, et al

- Xamarin.Forms.Core/Shell/QueryPropertyAttribute.cs
Added `AllowMultiple=true` to the `QueryPropertyAttribute`.
In the process of building a demo app (https://github.com/matthewrdev/xamarin-forms-4), I discovered that I could not apply multiple parameters; doing so would cause a compile-time error.
The usage of this property in [ShellContent.ApplyQueryAttributes](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Shell/ShellContent.cs#L171) indicates that the intended behaviour is to allow users to specify multiple URL arguments that will be applied onto the page. Changing AllowMultiple to true fixes this.
For reference, when AllowMultiple is not explicitly set, it's default value is false. See: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/attributes/attributeusage.
Added …
> Add AllowMultiple=true to QueryPropertyAttribute

- Xamarin.Forms.Platform.MacOS/Renderers/WebViewRenderer.cs
Fix the problem that only the first Navigating event of WebView can be triggered
- macOS
> [macOS] Only the first Navigating event of WebView can be triggered

- Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs
- Xamarin.Forms.Platform.iOS/ViewRenderer.cs
When a ViewRenderer is disposed it sets Element to Null, the Control on the ImageRender was always being created even if the `NewElement` was null.
- fixes failing tests on IOS
None
- iOS
None
Not applicable
> [iOS] Fix ImageRenderer dispose

- Xamarin.Forms.Controls/Controls/ColorPicker.cs
- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Controls/GalleryPages/MaterialProgressBarGallery.cs
- Xamarin.Forms.Core/Slider.cs
- Xamarin.Forms.Material.iOS/MaterialProgressBarRenderer.cs
- Xamarin.Forms.Material.iOS/MaterialSliderRenderer.cs
- Xamarin.Forms.Platform.Android/Material/MaterialColors.cs
- Xamarin.Forms.Platform.Android/Material/MaterialProgressBarRenderer.cs
- Xamarin.Forms.Platform.Android/Material/MaterialSliderRenderer.cs
- Xamarin.Forms.Platform.Android/Resources/color/white_disabled_material.xml
- Xamarin.Forms.Platform.Android/Resources/drawable/MaterialProgressBar.xml
- Xamarin.Forms.Platform.Android/Resources/values/styles.xml
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Added the Material versions of the ProgressBar and Slider.
- fixes #5008 
- fixes #5079 
- fixes #5018 
Added the Material renderers for Slider and ProgressBar for Android and iOS.
The rules for the coloring are as follows:
- All default colors, then use the defaults
- A single color for `ProgressBar.ProgressColor` or `Slider.MinimumTrackColor`, then follow material: a single color throughout (including the slider thumb), but the background has an alpha
- A single background color for `ProgressBar.BackgroundColor` or `Slider.MaximumTrackColor`, then just set the background color
- Both progress and background, then throw material out and set colors explicitly
- A default slider thumb, then fall back to the primary color
- A specific thumb, then use that explicitly
- iOS
- Android
New …
> [Material] [Android, iOS] Added Slider and ProgressBar

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5172.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Extensions/ImageViewExtensions.cs
Don't dispose if newImage set is null. 
- fixes #5172
None
- Android
None
Not applicable
> [Android] Fix ImageRenderer URI

- Xamarin.Forms.Core/Shell/QueryPropertyAttribute.cs
#5180 targeted at 3.6.0
In the process of building a demo app (https://github.com/matthewrdev/xamarin-forms-4), I discovered that I could not apply multiple parameters; doing so would cause a compile-time error.
The usage of this property in ShellContent, specifically in ApplyQueryAttributes, indicates that the intended behaviour is to allow users to specify multiple URL arguments that will be applied onto the page. Changing AllowMultiple to true fixes this.
For reference, when AllowMultiple is not explicitly set, it's default value is false. See: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/attributes/attributeusage.
> Add AllowMultiple=true to QueryPropertyAttribute (#5180)

- Xamarin.Forms.Core/BindingExpression.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5242.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5242.xaml.cs
[C] Binding null on nullable
@kicsiede's fix for #5242, plus unit test, targetted to 3.6.0
- closes #5242
None
None
Not applicable
> [C] Binding null on nullable

- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CollectionViewGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ExampleTemplates.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/PropagateCodeGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/PropagationGallery.cs
- Xamarin.Forms.Core/Internals/PropertyPropagationExtensions.cs
- Xamarin.Forms.Core/Items/ItemsView.cs
- Xamarin.Forms.Platform.Android/CollectionView/ItemsViewAdapter.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
- Xamarin.Forms.Platform.iOS/CollectionView/SelectableItemsViewController.cs
- Xamarin.Forms.Platform.iOS/CollectionView/UICollectionViewDelegator.cs
Attach/detach templated Views as logical child elements of the CollectionView so that the EffectiveFlowDirection (and other properties) propagate down to them.
- fixes #4583 
None
- iOS
- Android
None
Not applicable
In Control Gallery, navigate to CollectionView Gallery -> Propagation Galleries -> Propagate FlowDirection. Toggle the FlowDirection switch and verify that the description below it matches the behavior of the CollectionView.
> Implement FlowDirection propagation to items in CollectionView

- Xamarin.Forms.Platform.Android/AppCompat/MasterDetailPageRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/MasterDetailRenderer.cs
Fix ObjectDisposedException, same thing as PR #4931 but for MasterDetailPage.
When changing the mainPage from a MasterDetailPage sometime a ObjectDisposedException because the update is delayed and the page had changed.
- Fixes : https://github.com/xamarin/xamarin-android/issues/2604
None
- Android
None
Not applicable
Have a MasterDetailPage as MainPage change it, repeat it enough times to trigger the issue
> [Android] Fix ObjectDisposedException on MasterDetailPageRenderer update

- Xamarin.Forms.Platform.iOS/VisualElementTracker.cs
Signature of public constructors can't be changed otherwise they run the risk of breaking libraries built against older versions of forms.
- fixes #5278
> [iOS] add single parameter constructor back

- Xamarin.Forms.Core/ResourcesExtensions.cs
Dynamic resources do not work with merged ResourceDictionaries. When an Element has its parent set, the original stale resource values are used and updated values ignored. This change uses `ResourceDictionary.TryGetValue` to ensure that dictionaries are checked in the correct order to get the most recent value.
Tested manually using the repro in #3661, on iOS.  I couldn't find any unit tests for this extension method, so none have been added/changed.  Happy to go back and amend if you point out what I've missed.
- fixes #3661
- None
None
Before
After
I have a branch, 'repro-3661' which is essentially the repro uploaded in #3661, with the addition of using dynamic resources in a style setter, both defined in merged dictionaries.  I've manually tested on iOS …
> [Core] Fix dynamic resources in merged dictionaries #3661

- Xamarin.Forms.Platform.Android/ResourceManager.cs
When running in the Forms Previewer, `Xamarin.Forms.Platform.Android.ResourceManager.Init()` won't find the expected types if the project has not been built, and `GetId()` will fail with an NRE.
Add a null check to `GetId()` and return 0.
Fixes part of #5300 
None
- Android
None
A sample app sets `ContentPage.BackgroundImage` in a `Style` in `App.xaml`. If the project is not built, currently every page fails to render in the Previewer (Android) as follows:
With this fix in place, all pages render as expected, for example...
Verified Forms XAML pages that failed to render in Previewer now render successfully.
> Fix NRE in Android ResourceManager when reference resource in Previewer

- Xamarin.Forms.Controls/GalleryPages/ButtonLayoutGalleryPage.xaml
- Xamarin.Forms.Platform.iOS/Renderers/ButtonLayoutManager.cs
It appears that iOS has a nice little delay when setting the title to the layout, so we have to use manual measuring.
- fixes #5160
None
- iOS
The images are correctly laid out.
|   | Classic | Material |
| -: | :-: | :-: |
| Before | <img src="https://user-images.githubusercontent.com/1096616/52660484-6eff9c00-2f08-11e9-87f6-885dcbce9b5e.png" width="300" /> | <img src="https://user-images.githubusercontent.com/1096616/52660398-4081c100-2f08-11e9-864d-4008977967e6.png" width="300" /> |
| After | <img src="https://user-images.githubusercontent.com/1096616/52660601-b423ce00-2f08-11e9-93ee-b12681565a26.png" width="300" /> | <img src="https://user-images.githubusercontent.com/1096616/52660446-5b543580-2f08-11e9-934e-4b87ad03755a.png" width="300" /> |
> [iOS] Fix the layout of the button

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5242.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5256.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5256.xaml.cs
avoid InvalidCastException if an event is overriden with the new keyword
to a bindableproperty. Kids, DO NOT EVER DO THIS AT HOME.
- fixes #5256 for XamlC
None
None
Not applicable
> [XamlC] avoid cast exception on overriden members

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5003.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5003.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
- fixes #5003 
- fixes #5149
- fixes #5258
None
- iOS
None
Not applicable
> [iOS] Fixed updating Label TextDecorations when no Text is set

- .nuspec/Xamarin.Forms.Android.targets
- .nuspec/Xamarin.Forms.nuspec
- .nuspec/proguard.cfg
- Xamarin.Forms.sln
Add a default proguard configuration file for when the user enables proguard.  With support 28 projects are hitting the DEX limit a lot faster now. Adding this file will mean that our library works with proguard and the user doesn't have to add any rules themselves.  I'm targeting 3.6.0 since this will help remove some friction with support 28
- fixes #2709
- Android
- Enable proguard and full linking on an XF project
- Install this nuget
- Run Android project and it shouldn't crash
> [Android] Include default proguard file so user doesn't have to create rules for XF

- Xamarin.Forms.Platform.Android/Renderers/SearchBarRenderer.cs
For some crazy reason Android isn't measuring the SearchBar widget height correctly on API24, when we pass a HeightRequest of 0 (so the item provides its own size.  So we give it a default height based on running on the same device on API27.
This should fix UITests on API24
- fixes #5328 
None
- Android
None
> [Android] Fix SearchBar renderer height on API24

- Xamarin.Forms.Build.Tasks/ModuleDefinitionExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/XamlC/ModuleDefinitionExtensionsTests.cs
The old implementation fails to identify generic instance types for typed binding getter, whose type is:
System.Func`2<TSource, ValueTuple<TProperty, bool>>
This fixes the issue by taking generic arguments into account.
None
None
None
Not applicable
Run the automated test.
> [XamlC] Identify generic instance types correctly when importing ctor

- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
remove `vertical-align` that wasn't working, add `-xf-vertical-text-alignment`
- fixes #
None
- iOS
None
Not applicable
> [CSS] fix mapping for vertical-align

- .nuspec/Xamarin.Forms.Visual.Material.nuspec
- Xamarin.Forms.Core/Properties/AssemblyInfo.cs
- Xamarin.Forms.Material.iOS/Properties/AssemblyInfo.cs
- Xamarin.Forms.Material.iOS/Xamarin.Forms.Material.iOS.csproj
- Xamarin.Forms.Platform.iOS/Properties/AssemblyInfo.cs
It doesn't make any sense to have platform specific dlls
If we create Material dlls for netstandard or android then we should just bait and switch them not create multiple dlls
- iOS
> [Material] rename iOS assembly to be non platform specific

- Xamarin.Forms.Controls/ControlGalleryPages/VisualGallery.xaml
- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Controls/GalleryPages/MaterialActivityIndicatorGallery.cs
- Xamarin.Forms.Controls/GalleryPages/MaterialProgressBarGallery.cs
- Xamarin.Forms.Material.iOS/MaterialActivityIndicatorRenderer.cs
- Xamarin.Forms.Platform.Android/Material/MaterialActivityIndicatorRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/CircularProgress.cs
- Xamarin.Forms.Platform.Android/Renderers/SquareLayout.cs
- Xamarin.Forms.Platform.Android/Resources/drawable-v24/MaterialActivityIndicatorBackground.xml
- Xamarin.Forms.Platform.Android/Resources/drawable/MaterialActivityIndicatorBackground.xml
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Fixed the back circle of the activation indicator when resizing. The `ThicknessRatio` of the activator indicator is tied to the width so that the width and height are the same, it is added to the square layout.
- fixes #5261
None
- Android
After
**Android**
**iOS**
- run VisualGallery
> [Android iOS Visual] fixes background in ActivityIndicator

- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewLoadSimulateGallery.xaml
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewLoadSimulateGallery.xaml.cs
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs
The function `GetAdapter` generated a new instance of the `adapter` that is not registered with `DataObserver`. At the same time, when trying to `Unwatch` from it, a exception was thrown.
- fixes #5110
None
- Android
None
Not applicable
- run CollectionView Gallery > EmptyView Galleies > EmptyView (load simulation)
> [Android CollectionView] Fixes crash when ItemSource Changed

- .nuspec/Xamarin.Forms.Android.targets
- .nuspec/Xamarin.Forms.Visual.Material.targets
Currently because of net standard targets you can install Xamarin.Forms into any Android project regardless of how low the Target Framework is set. This will just cause the Android platform DLL to not get added to the android project and nothing will compile. This error gives the user more information about why their particular project isn't compiling.
http://feedback.devdiv.io/458514
Trying to compile an Android target with Target Framework lower than 8.1 will throw an actionable error message
- add nuget into a project with android target framework < 8.1 and you should see a compile error
> [Android] add build error if TargetFramework is too low

- Xamarin.Forms.Core/Visuals/VisualTypeConverter.cs
GetExportedTypes can't be called on a dynamic assembly. I also added a catch for NotSupportException and FileNotFoundException since those are the possible exception that GetExportedTypes can throw
Run Visual Gallery on Windows
> [Visual] Check if assembly is dynamic before calling GetExportedTypes

- Xamarin.Forms.Core/Xaml/TypeConversionExtensions.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5378_1.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5378_1.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5378_2.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5378_2.xaml.cs
[X] wrap typeconverter exceptions in XPE
- fixes #5378
None
None
Not applicable
> [X] wrap typeconverter exceptions in XPE

- Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs
- Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
- Xamarin.Forms.Xaml/FillResourceDictionariesVisitor.cs
Up to now, we were resilient on missing properties(value assignment) for the previewer, This adds supports for resilience on unsupported types (object creation).
- fixes #5171
None
None
Not applicable
> VS bug [#802254](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/802254)
> [previewer] resilience on createvalue

- Xamarin.Forms.Core/BindableObject.cs
- Xamarin.Forms.Core/FlexLayout.cs
- Xamarin.Forms.Core/FontElement.cs
- Xamarin.Forms.Platform.iOS/Renderers/FontExtensions.cs
- Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
Deprecate GetValues, as it no longer make snes now that the properties
store is a Dictionary and no longer a List.
Update the code to be C#7-ish.
Take this refactoring opportunity to move similar method next to each other.
- fixes #5015
None
None
Not applicable
> [C] deprecate GetValues

- Xamarin.Forms.Platform.iOS/Cells/CellRenderer.cs
Modified SetBackgroundColor method.
Instead of https://github.com/xamarin/Xamarin.Forms/pull/5365
```csharp
public virtual void SetBackgroundColor(UITableViewCell tableViewCell, Cell cell, UIColor color)
{
tableViewCell.TextLabel.BackgroundColor = color; // New line
tableViewCell.ContentView.BackgroundColor = color; // New line
tableViewCell.BackgroundColor = color;
}
```
- fixes #5346 
None
- iOS
Actual behavior: you cannot change background color of non-header cell by setting platform-specific property
* Open original issue #5346 
* Run the attached sample on iOS.
* Browse to the ListView/Cell Platform-Specifics page.
> [iOS] Cell.DefaultBackgroundColor iOS platform-specific only works for header cells

- Xamarin.Forms.Core.Design/Xamarin.Forms.Core.Design.csproj
Fix the issue when building on a mac (it would not build)
- certain files were being included
- mac should not build this assembly, but as it has to do so, exclude everything
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> Fix the issue when building on a mac

- Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs
Fixes the iOS FontImageSourceHandler to use any valid UIFont Name which could be the Font Family Name or the Post Script name thereby allowing users to specify the exact font when using multiple Icon fonts within the same Font Family i.e. Font Awesome.
- fixes #5372 
None
- iOS
The FontImageSourceHandler will now locate valid Fonts by PostScript name and not just use the default font for a specified Font Family.
Visual Studio nearly crashed my system just loading Xamarin Forms... I did test the UIFont loading in a separate project though and validated that this will work without throwing exceptions. The `fontsource.FontFamily` is guarded from providing a null value which would throw a NullReferenceException rather than simply providing a null UIFont.
> [iOS] Load specified Font Family or PostScript Font

- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/PreselectedItemGallery.xaml
- Xamarin.Forms.Platform.Android/CollectionView/SelectableItemsViewAdapter.cs
- Xamarin.Forms.Platform.Android/CollectionView/SelectableItemsViewRenderer.cs
ViewHolders which are just off screen do not show up in the RecyclerView's child collection, but have not yet been recycled. So they are not visible to the ClearSelection method, nor are they de-selected during the recycling process.
These changes add tracking of the active ViewHolders so they can be directly de-selected, rather than iterating over the RecyclerView's child collection. 
- fixes #5078
None
- Android
Before:
After:
In Control Gallery, navigate to CollectionView Gallery -> Selection Galleries -> Preselected Item. Scroll down until the selected item is just off screen. Select another item. When you scroll back up, the original item should no longer be selected.
> [Android] Allow Renderer/Adapter to deselect ViewHolders not in child collection

- Xamarin.Forms.Platform.Android/Renderers/AHorizontalScrollView.cs
- Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs
#4522 added some new code paths to ScrollView renderers for Shell that can possibly cause NREs.
- fixes #5161
- fixes #5247
None
- iOS
- Android
None
Not applicable
- For #5161, not quite sure how to repro, but the changes seem self-explanatory.
- For #5247, run Bugzilla 41415 and try to manually scroll the yellow/red ScrollView. If it doesn't crash, success!
> [iOS, Android] Prevent NREs in ScrollViews

- Xamarin.Forms.Platform.iOS/Extensions/ColorExtensions.cs
- Xamarin.Forms.Platform.iOS/Renderers/CarouselPageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PhoneMasterDetailRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs
Previewer team opened https://github.com/xamarin/Xamarin.Forms/issues/5300 which asks we scrub for all places where we throw if an image is not found. So, these change simply ignore missing images.
> previewer; PageRenderer trap for missing bg image

- Xamarin.Forms.Platform.Android/AppCompat/ImageButtonRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ImageElementManager.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs
- Xamarin.Forms.Platform.Android/ILayoutChanges.cs
- Xamarin.Forms.Platform.Android/IVisualElementRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ShellRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Added a new interface to handle LayoutChanges so that IVisualElementRenderer can stay the same and not break older libraries 
- Android
> [Android] Remove changes to IVisualElementRenderer so it remains backwards compatible

- Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs
- Xamarin.Forms.Xaml/XamlParser.cs
[X] allow previewer fallback on rootnode
- fixes #5410
None
None
Not applicable
> [X] allow previewer fallback on rootnode

- Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs
- Xamarin.Forms.Xaml.UnitTests/XStaticException.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/XamlLoaderCreateTests.cs
- Xamarin.Forms.Xaml/CreateValuesVisitor.cs
[X] bubble markup exception to previewer
- fixes #5407
None
None
Not applicable
> [X] bubble markup exception to previewer

- Xamarin.Forms.Platform.iOS/ContextScrollViewDelegate.cs
Changed view to which the `TabGesture` is added. Now it corresponds to the view from which this gesture will be removed after close ContextAction.
- fixes #4987
None
- iOS
None
- run UITest 4314
- open and close menu action
- try to select this cell (they are highlighted)
- remove both cells
> [iOS] Fix tapping a ViewCell after close ContextActionMenu

- Xamarin.Forms.Platform.MacOS/Renderers/ImageRenderer.cs
Prevent creating new native controls if XF Element equals **NULL**
None
- MacOS
No crash
Not applicable
Open ControlGallery and search Issue342. Open it, then try to navigate back.
Actual behavior: crash in ViewRenderer.
> [macOS] Image crashes App during disposing its renderer

- Xamarin.Forms.Platform.WPF/WPFResources.xaml
Also bind IsEnabled
Bind EntryCell.IsEnabled to the rendered FormsTextBox. 
- fixes #5360
None
- WPF
The Rendered FormsTextBox now gets the IsEnabled property data-bound to the EntryCell's IsEnabled property, which fixes that functionality. 
None
Before:
After:
1. Put a TableView on a page, containing an EntryCell. Set its IsEnabled property to false
2. You will notice that the control at runtime, in WPF is enabled.
3. Now fix things
4. You'll notice that the edit is disabled now.
> Fix WPFResources, EntryCell

- Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
CreatePlaceholderLabel is being called even if the new Element is null, which causes a crash on on dispose.
- fixes crash when disposing Editor
None
- iOS
None
Not applicable
> [iOS] Check new element before creating placeholder label

- Xamarin.Forms.Core.Windows.UITests/WinDriverApp.cs
- Xamarin.Forms.Core.Windows.UITests/WindowsTestBase.cs
- Xamarin.Forms.Core.Windows.UITests/WindowsTestServer.cs
If a UI Tests causes the UWP window to crash this will restart it when it tries to run the next test.
Currently if a tests fails all subsequent tests will just fail because the window is closed
- UWP
> Uwp restart uitests on crash

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5330.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5330.xaml.cs
Invalid x:DataType was ignored up to now. Change the behavior so it
throws a XPE.
- fixes #5330
None
None
Not applicable
> [XamlC] throw on invalid DataType

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue935.cs
- Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
The description of why is summarized here
https://github.com/xamarin/Xamarin.Forms/issues/5465
- UWP
- run Issue2927Test and it will no longer crash
> [UWP] Roll back PR 3400 so the correct context is passed into Tapped

- Xamarin.Forms.Platform.Android/Forms.cs
- Xamarin.Forms.Platform.Android/Renderers/PageRenderer.cs
Use `ContextCompat.getColor` if API < 23 per https://stackoverflow.com/questions/31590714/getcolorint-id-deprecated-on-android-6-0-marshmallow-api-23
- fixes part of #5071
None
- Android
None; Without this change, XF Shell throws on load for API under 23
Not applicable
Load Shell Template
> ContextCompat.getColor if API < 23

- Xamarin.Forms.Platform.Tizen/Renderers/CarouselPageRenderer.cs
* Fix bug of CarouselPage focusing
We disallow focus on page that outside of screen, So When CurrentPage was changed on MultPage, We change `AllowTreeFocus` property to false on all others page
We have mistake on this code, so can't change policy when CurrentPage was changed by scrolling
This PR is fix it
- fixes #
None
- iOS
- Android
- UWP
None
Not applicable
> [Tizen] Fix CarouselPage focus issue

- .nuspec/Xamarin.Forms.Maps.nuspec
Put the design.dll for Maps into the Design folder for consistency.
- fixes #5472
None
- iOS
- Android
- UWP
None
Not applicable
None
> [Maps] move design dll to the design folder

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
Fix message for unresolved event handler reference in `DataTemplate`. The old implementation mistakenly showed an anonymous type for the delegate which confused my colleague and wasted his time :joy: .
None
None
None
Not applicable
> [XamlC] Fix message for unresolved event handler reference in DataTemplate

- Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs
- Xamarin.Forms.Xaml/ExpandMarkupsVisitor.cs
- Xamarin.Forms.Xaml/XamlServiceProvider.cs
[X] recover from missing markup type
- fixes #5484
None
None
Not applicable
> VS bug [#813561](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/813561), VS bug [#816607](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/816607)
> [X] recover from missing markup type

- Xamarin.Forms.Sandbox.Android/MainActivity.cs
- Xamarin.Forms.Sandbox.Android/Xamarin.Forms.Sandbox.Android.csproj
- Xamarin.Forms.Sandbox.iOS/Xamarin.Forms.Sandbox.iOS.csproj
- Xamarin.Forms.Sandbox/App.StartHere.cs
- Xamarin.Forms.Sandbox/MainPage.xaml
- Xamarin.Forms.Sandbox/Xamarin.Forms.Sandbox.csproj
- add material reference to android sandbox
- add a XAML dll reference to ios so it runs on previewer
- Add build tasks as non referenced assembly to sandbox can compile XAML files off a clean build
> Fix up Sandbox to work with previewer and add android material reference in

- Xamarin.Forms.Platform.Android/Forms.cs
In the previewer, `TryGetTextAppearance()` returns `-0.5` for all values. Return default value if we get a size of 0 or less.
- fixes https://devdiv.visualstudio.com/DevDiv/_queries/edit/763877
None
- Android
None
Before:
After:
Manual testing in previewer.
> [Android] NamedSize now returns defaultValue instead of -1 if parsing from resource fails

- Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5461.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Extensions/ScrollViewExtensions.cs
- Xamarin.Forms.Platform.Android/IScrollView.cs
- Xamarin.Forms.Platform.Android/Renderers/AHorizontalScrollView.cs
- Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Added code to force the underlying scrollbars on a NestedScrollView control to initialize to avoid crashes during the draw phase 
- fixes #5461
- Android
- there are automated tests
> [Android] ensure scrollbar has been initialized

- Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs
- Xamarin.Forms.Xaml/ExpandMarkupsVisitor.cs
let the previewer intercepts and recover from misformatted markups
- fixes #5508
- closes #5527
None
None
Not applicable
> [X] resilience on markup

- Xamarin.Forms.Platform.Tizen/Native/CollectionView/CollectionView.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/EmptyItemAdaptor.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/GridLayoutManager.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/ICollectionViewLayoutManager.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/ItemAdaptor.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/ItemTemplateAdaptor.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/LinearLayoutManager.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/RecyclerPool.cs
- Xamarin.Forms.Platform.Tizen/Native/CollectionView/ViewHolder.cs
- Xamarin.Forms.Platform.Tizen/Properties/AssemblyInfo.cs
- Xamarin.Forms.Platform.Tizen/Renderers/ItemsViewRenderer.cs
- Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs
Implementation CollectionView Tizen Renderer
Implementation tizen layer CollectionView
* Unsupported feature
* SnapPointsAlignment.Center / SnapPointsAlignment.End
- fixes https://github.com/xamarin/Xamarin.Forms/issues/3172
None
- Tizen
None
> [Tizen] Add CollectionView Tizen Renderer

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5252.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
On iOS, Entry and Editor should have same default placeholder color for consistency
- fixes #5252
None
- iOS
None
Before:
After:
> iOS: Color of Editor Placeholder is different than Entry

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/BindingsCompiler.xaml
- Xamarin.Forms.Xaml.UnitTests/BindingsCompiler.xaml.cs
The intermediate values in compiled binding paths must be loaded as addresses when calling the subsequent property getter. However, the preceding property getters directly return the values if they are value types. This change adds a code to convert those values into addresses.
None
None
None
Not applicable
> Correctly load addresses of intermediate values in compiled binding paths

- Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs
- Xamarin.Forms.Xaml/RegisterXNamesVisitor.cs
Allow the previewer to recover from an x:Name attribute on a element
with unresolved type.
- fixes #5546
- closes #5547
None
None
Not applicable
> [X] resilient to untyped x:Name

- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Controls/CoreGalleryPages/CoreGalleryPage.cs
- Xamarin.Forms.Controls/ViewContainers/StateViewContainer.cs
- Xamarin.Forms.Core.UITests.Shared/Tests/EntryUITests.cs
- Xamarin.Forms.Core.UITests.Shared/Tests/MaterialEntryUITests.cs
- Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs
- Xamarin.Forms.Core.UITests.Shared/Xamarin.Forms.Core.UITests.projitems
- Xamarin.Forms.Material.Android/MaterialFormsTextInputLayoutBase.cs
- Xamarin.Forms.Platform.Android/Cells/TextCellRenderer.cs
- Xamarin.Forms.Platform.Android/ViewRenderer.cs
- Xamarin.Forms.Platform.UAP/Resources.xaml
- Xamarin.Forms.Platform.iOS/Cells/TextCellRenderer.cs
- propagate focus event on nested edit text with material up to parent
- Add automationid to TextCell so that I can use it during UI Test
- Add Material UI Test abilities to Core Gallery Pages
- fixes #5509 
- iOS
- Android
Run Entry Control gallery and test focus pages
> [Android] fix focus event on android and add UI Tests

- Xamarin.Forms.Platform.Android/Extensions/ScrollViewExtensions.cs
- Xamarin.Forms.Platform.Android/Renderers/AHorizontalScrollView.cs
- Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs
Fix issue when Message is null on Android API19 introduced on PR #5462 
None
- Android
None
Not applicable
Run gallery and go to test #5461 or a test with a Scrollview on API19
> [Android] Fix issue when Message is null on Android API19

- Xamarin.Forms.Material.Android/MaterialEntryRenderer.cs
Left over sealed on Material Entry Renderer
- MaterialEntryRenderer is no longer sealed on android
- Android
> remove left over sealed on Material Entry Renderer

- Xamarin.Forms.Material.Android/MaterialActivityIndicatorRenderer.cs
- Xamarin.Forms.Material.Android/MaterialButtonRenderer.cs
- Xamarin.Forms.Material.Android/MaterialDatePickerRenderer.cs
- Xamarin.Forms.Material.Android/MaterialEditorRenderer.cs
- Xamarin.Forms.Material.Android/MaterialEntryRenderer.cs
- Xamarin.Forms.Material.Android/MaterialFrameRenderer.cs
- Xamarin.Forms.Material.Android/MaterialPickerRenderer.cs
- Xamarin.Forms.Material.Android/MaterialProgressBarRenderer.cs
- Xamarin.Forms.Material.Android/MaterialSliderRenderer.cs
- Xamarin.Forms.Material.Android/MaterialStepperRenderer.cs
- Xamarin.Forms.Material.Android/MaterialTimePickerRenderer.cs
- Xamarin.Forms.Material.Android/Properties/AssemblyInfo.cs
Move all default material renderer registration to AssemblyInfo in order to stay consistent
> - Move renderer registration to Assembly Info

- Xamarin.Forms.Platform.Android/Platform.cs
- Xamarin.Forms.Platform.Android/ResourceManager.cs
This will try to retrieve a resource id by using the native GetIdentifier instead of reflection
- Android
- Test any image code to make sure there are no breaking changes
- Install nuget into android project that references an image that's part of the Android project and test that it loads inside the previewer without a build
> [Android] fall back to using native get identifier if reflection fails to retrieve drawable

- Xamarin.Forms.Platform.iOS/Forms.cs
fixes build exception `error CS1061: 'NSApplication' does not contain a definition for 'Appearance'`
None
- Mac
None
Not applicable
> [mac] fix build

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1461.cs
The UI tests on 1461 are only supposed to run for iOS Tablets, but there's no good way to enforce that without actually loading up the test and checking what context it's running in. That's what this test is doing, which is great, except that it's now flaky on iOS 10 and causes the next test in line (1469) to randomly fail because the 1461 page doesn't go away.
Also, since we don't currently run tests on any iOS tablets anyway, as far as I can tell, we're just spinning up 10 tests on every platform for no good whatsoever.
I declare it useless as an automated test right now.
None
None
- Tests
None
Not applicable
Tests should not fail. 🤞
> [UITest] Disable old 1461 test

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5204.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.MacOS/Controls/FormsImageView.cs
- Xamarin.Forms.Platform.MacOS/Extensions/ImageExtensions.cs
- Xamarin.Forms.Platform.MacOS/Renderers/ImageRenderer.cs
- Xamarin.Forms.Platform.MacOS/Xamarin.Forms.Platform.macOS.csproj
- Xamarin.Forms.Platform.iOS/Renderers/IImageVisualElementRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/ImageElementManager.cs
- Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs
Refactor the ImageRenderer to use a NSImageView and use the iOS load image helpers
- fixes #5204 
None
- macOS
None
Not applicable
Can test issue 5204 and existing ImageGallery
> [MacOS] Move ImageRenderer to use NSImageView

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/VisualControlsPage.xaml
- Xamarin.Forms.Material.Android/MaterialActivityIndicatorRenderer.cs
- Xamarin.Forms.Material.Android/MaterialButtonRenderer.cs
- Xamarin.Forms.Material.Android/MaterialContextThemeWrapper.cs
- Xamarin.Forms.Material.Android/MaterialFrameRenderer.cs
- Xamarin.Forms.Material.Android/MaterialProgressBarRenderer.cs
- Xamarin.Forms.Material.Android/MaterialSliderRenderer.cs
- Xamarin.Forms.Material.Android/Resources/values/styles.xml
- Moved the ContextThemeWrapper creation to a factory method which will centralize the wrapper creation plus it won't double wrap things
- Also modified sandbox slightly so that iOS will render with previewer
- Android
- run Visual Gallery in Control Gallery
> Centralize Theme Wrapper and fix sandbox to work with previewer

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1332.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1760.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1760_1.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5184.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core/Layout.cs
- Xamarin.Forms.Platform.Android/VisualElementTracker.cs
Added calling `RequestLayout` on parent Layout when adding child in current Layout.
Related PR https://github.com/xamarin/Xamarin.Forms/pull/4861
- fixes #1760
None
- Android
None
Not applicable
- run UItest 1760
- run UItest 1760 (1)
- run UItest 1332
- run UItest 5184
> [Android] fixes redraw element when changing renderer

- Xamarin.Forms.Platform.GTK/Renderers/AbstractPageRenderer.cs
The loop was exiting before `current` was being set.
- fixes #4713
None
- GTK
None
Before:
After:
Run https://github.com/mfkl/gtk-button-bug
/cc @jsuarezruiz
> [GTK] Fix NavigationBar check for Layout calc

- Xamarin.Forms.Core/HandlerAttribute.cs
- Xamarin.Forms.Core/VisualElement.cs
- Xamarin.Forms.Platform.Android/AppCompat/ImageButtonRenderer.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ImageElementManager.cs
- Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs
- Xamarin.Forms.Platform.Android/ILayoutChanges.cs
- Xamarin.Forms.Platform.Android/IVisualElementRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/ShellRenderer.cs
- Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Cherry picks the IVisualElementRenderer ABI fix into 3.5
Cherry picks the ABI fixes for VisualElement
- fixes #5288 (Release from Sync Fusion still needed in order to fix completely) 
Added:
- public new static readonly BindableProperty NavigationPropert
- public new static readonly BindableProperty StyleProperty
- added back protected HandlerAttribute(Type handler, Type target)  ctor
Removed:
- Removed LayoutChange from IVisualElementRenderer
- Android
- Recommend if we should fix any of the additional ABI changes https://gist.github.com/PureWeen/d6b652955e3240bab260713c25c95a68
> Make the 3.5 ABI compatible with 3.3 and 3.4

- Xamarin.Forms.Platform.UAP/Forms.cs
…onInfo.DeviceFamily
UWP-Xbox sets TV...Surface tablets sets Desktop intead of Phone
fixes #4852
Using previous code, it was missing platforms like Xbox which should be set as TV.
Beside that Surface tablet PCs were getting Idiom as phone. Because ApiInformation.IsTypePresent("Windows.Phone.UI.Input.HardwareButtons")  returns false for Surface. It supposed to be Desktop not Phone as confirmed in the msdn question below. Using DeviceFamily returns Desktop. 
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/0b75ea16-1d2a-4997-bfa2-8cb6f73ff1e8/uwp-what-device-family-is-a-surface-tablet?forum=wpdevelop#39c5d17a-4706-4c24-b3c0-9b17ca60dd4f
- fixes #
Running UWP app on Xbox returns Idiom as TV, Surface returns as Desktop
- UWP
> DetectPlatform Fixed for UWP

- Xamarin.Forms.Platform.iOS/Extensions/LabelExtensions.cs
Suppress warning that CharacterRangeForGlyphRange is obsolete. We can't change this to GetCharacterRange because that method doesn't exist on the current stable Mac SDK Apis
- fixes #5246
- macOS
> Suppress warning for CharacterRangeForGlyphRange is obsolete

- Xamarin.Forms.Core.UnitTests/BindableLayoutTests.cs
- Xamarin.Forms.Core/BindableLayout.cs
In the BindableLayout, when bound to a collection that implements INotifyCollectionChanged,
item inserts are always handled as Add
There is an extension method in Xamarin.Forms.Internals.NotifyCollectionChangedEventArgsExtensions that handles all the events correctly when you pass the callbacks.
I changed BindableLayout.cs to use this extension method when the collection changes.
Also, I removed passing the index to CreateView, since createview doesn't do anything with that.
And, in the reset, I replaced layout.children.clear() with CreateChildren().
CreateChildren clears the layout.children and then checks if it needs to create new ones.
Some libraries (eg DynamicData/ReactiveUI) trigger the reset after a batch update of the collection. It can be disputed if this correct behaviour, but …
> Fix BindableLayout's incorrect layout.children.add -> use insert

- Xamarin.Forms.Platform.UAP/SwitchRenderer.cs
see comment  https://github.com/xamarin/Xamarin.Forms/pull/4883/files#r267342643
fixes #5517
None
- UWP
None
Not applicable
> [UWP] fix throw exception when update switch color

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4356.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4356.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
When setting the EstimatedRowHeight it caused to UITableView to try to reload itself. This is an issue if we are trying to insert rows at the same time. If the row height didn't changed it wasn't a issue as the EstimatedRowHeight didn't change, but if we change that value it will queue a reload of the UITableView. 
We know moved to a better way to set EstimatedRowHeight based on the same fix we did for CollectionVIiew on #4688, this logic is now mostly handle in the DataSource.
Row will try to be estimated when the initial TableVIew is shown,  also before we show a cell we make sure we estimated, because the collection could be empty and this is our first item.
- fixes #4356
On internal `ListViewDataSource`
- `protected virtual void UpdateEstimatedRowHeight(UITableView tableView)`
- …
> [iOS] Better fix for EstimatedRowHeight 

- .nuspec/Xamarin.Forms.nuspec
- build/scripts/generate-docs.ps1
When creating the NuGet package for Forms, include all of the translated Intellisense API docs from the various language-specific subfolders.
> Add translated Intellisense files to NuGet package

- Xamarin.Forms.Material.Android/MaterialEditorRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs
Set `ImeOptions = ImeAction.Done` in `CreateNativeControl()` in Android EditorRenderer.
Alternative to #5320, only fixing the bug without making any API changes.
- fixes #4832
- fixes #5030
None
- Android
Editor will have Done button instead of Next when focused and the phone is in landscape orientation on Android.
Before:
After:
1. Run Control Gallery app.
2. Go to Editor Gallery page.
3.  Focus the Editor.
4. Rotate the device to landscape.
5. Press the Done button.
> Set ImeOptions to Done on Android Editor

- Xamarin.Forms.Xaml.UnitTests/DuplicatePropertyElements.xaml
- Xamarin.Forms.Xaml.UnitTests/DuplicatePropertyElements.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/DuplicateXArgumentsElements.xaml
- Xamarin.Forms.Xaml.UnitTests/DuplicateXArgumentsElements.xaml.cs
- Xamarin.Forms.Xaml.UnitTests/MultipleDataTemplateChildElements.xaml
- Xamarin.Forms.Xaml.UnitTests/MultipleDataTemplateChildElements.xaml.cs
- Xamarin.Forms.Xaml/XamlParser.cs
Throw XamlParseException when a duplicate property is detected.
None
None
None
Not applicable
> [Xaml] Throw XamlParseException when a duplicate property is detected

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5376.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs
- Xamarin.Forms.Platform.Android/ViewRenderer.cs
Fixes disposing of View.
`Dispose` of VisualElementRenderer sets Element to `null`. Because of this, the event of a response to focus was not removed from the Element.
- fixes #5376
None
- Android
None
Not applicable
- run UItest 5376
> [Android] Fixes ObjectDisposedException when call Unfocus of Entry

- Xamarin.Forms.Platform.Android/Renderers/FrameRenderer.cs
Dispose `FrameRenderer`'s `FrameDrawable`.
- fixes #5446
None
- Android
None; Doesn't crash due to OOM.
Not applicable
Run reproduction in fixed issue.
> Dispose FrameRenderer's FrameDrawable

- Xamarin.Forms.Core/Shell/ShellContent.cs
- Xamarin.Forms.Platform.Android/Renderers/ShellSectionRenderer.cs
On android when you navigated away from a page it calls recycle on Shell Content but there's not really a reason to remove the shells internal content page is there?
iOS doesn't have this behavior when navigating away from pages. 
When shell starts up it instantiates all of the content pages that are part of the shell contents so it doesn't seem like this value should ever get set to null 
- fixes #4684
- Android
- if you have a shell with two shell items
- toggle between them
- and now click on one of the tabs in a shell item
HEre's the xaml that I used to test
```
<ShellItem Title="Home" Route="Home">
<ShellSection>
<ShellContent>
<ContentPage />
</ShellContent>
</ShellSection>
</ShellItem>
<ShellItem Title="Connect" Route="connect">
<ShellSection>
<ShellContent Title="Connect"> …
```
> [Android] don't clear shell content because native page isn't visible

- Xamarin.Forms.Core/IElementConfiguration.cs
Currently there appears to be an issue with UWP where a DataContext that implements a covariant generic constrained interface performs very poorly
If you create a native UWP app and use the following ViewModel structure
```C#
public class ViewModel : IElementConfiguration<Element>
{
public string CompositionName { get; set; } = "test class";
}
public class Element
{
}
// Remove the out on the generic or the constraint on the generic and rerun the application
public interface IElementConfiguration<out TElement> where TElement : Element
{
}
uwpListView.ItemsSource = Enumerable.Range(0,1000).Select(x=> new ViewModel()).ToList();
```
You will see the same performance degradation
- Closes #5235
- iOS
- Android
- UWP
- Verify you can run UWP UI Tests
> remove covariant out on IElementConfiguration

- Xamarin.Forms.Core/Shell/Shell.cs
- Xamarin.Forms.Core/Shell/ShellContent.cs
- Xamarin.Forms.Core/Shell/ShellItem.cs
- Xamarin.Forms.Core/Shell/ShellSection.cs
Tab alias for a ShellSection
TabContent alias for a ShellContent
FlyoutItem alias for a ShellItem
Shell has a property now called Flyout that maps to Items
> [C] alias shell names

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewBindingErrors.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewBindingErrors.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CollectionViewGalleryTestItem.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/DataTemplateGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/DataTemplateSelectorGallery.xaml
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/DataTemplateSelectorGallery.xaml.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/DemoFilteredItemSource.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewGalleryFilterInfo.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewTemplateGallery.xaml.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ItemsSourceGenerator.cs
- Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
- Xamarin.Forms.Core.UITests.Shared/Tests/CollectionViewUITests.cs
- Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs
- Xamarin.Forms.Platform.Android/CollectionView/EmptyViewAdapter.cs
- Xamarin.Forms.Platform.Android/CollectionView/ItemContentView.cs
- Xamarin.Forms.Platform.Android/CollectionView/ItemsViewAdapter.cs
- Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs
- Xamarin.Forms.Platform.Android/CollectionView/SelectableItemsViewAdapter.cs
- Xamarin.Forms.Platform.Android/CollectionView/SizedItemContentView.cs
- Xamarin.Forms.Platform.Android/CollectionView/TemplatedItemViewHolder.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
- Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
Modifies the CollectionView on Android and iOS to handle DataTemplateSelectors for ItemTemplate and EmptyViewTemplate.
- fixes #4826
None
- iOS
- Android
None
Not applicable
> Handle DataTemplateSelector on iOS/Android CollectionView

- Xamarin.Forms.Core.UnitTests/DependencyResolutionTests.cs
- Xamarin.Forms.Core.UnitTests/RegistrarUnitTests.cs
- Xamarin.Forms.Core/DependencyResolver.cs
- Xamarin.Forms.Core/Registrar.cs
- Xamarin.Forms.Material.Android/MaterialButtonRenderer.cs
Material Android renderers need to know the style they are being set to on creation so they can be set to the correct style id.  The style on an android element isn't settable at runtime post inception.
The idea is being able to do this via the constructor
```C#
static int getThemeId(BindableObject element)
{
var style = Xamarin.Forms.Material.Button.GetStyle(element);
int themeId = Resource.Style.XamarinFormsMaterialTheme;
switch (style)
{
case Xamarin.Forms.Material.Style.Outline:
themeId = Resource.Style.XamarinFormsMaterialOutlinedButtonTheme;
break;
case Xamarin.Forms.Material.Style.Text:
themeId = Resource.Style.XamarinFormsMaterialTextButtonTheme;
break;
}
return themeId;
}
public MaterialButtonRenderer(Context context, BindableObject element)
: base(new …
```
> [visual] Add extra parameter to android visual constructors

- Xamarin.Forms.Controls/GalleryPages/FontImageSourceGallery.cs
- Xamarin.Forms.Platform.UAP/Extensions/ImageExtensions.cs
- Xamarin.Forms.Platform.UAP/ImageButtonRenderer.cs
- Xamarin.Forms.Platform.UAP/ImageRenderer.cs
- Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
ImageButton was not designed to work with FontImageSource
- fixes #5666
None
- UWP
- run Font ImageSorce Gallery
> [UWP] Fixes crash ImageButton with FontImageSource

- .nuspec/Xamarin.Forms.Pages.Azure.nuspec
- .nuspec/Xamarin.Forms.Pages.nuspec
Removed dependency on modernhttpclient
- fixes #1886 
None
- Xamarin.Forms.Pages
- Xamarin.Forms.Pages.Azure
None
Not applicable
> Removed dependency on modernhttpclient

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5470.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs
- Xamarin.Forms.Platform.iOS/iOSAppLinks.cs
#4733 unified the image loading code but failed to preserve the check to see if an AppLink.Thumbnail was actually specified before throwing an exception. This restores that check.
- fixes #5470 
None
- iOS
None
Not applicable
- Run Issue5470 in Control Gallery. If it doesn't crash, this works!
- Also run AppLinksGallery to make sure that an app link with a thumbnail still works.
> [iOS] Don't crash if no Thumbnail specified for AppLink

- Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
This checks if the parent element is null before checking if the bindable property wants the safe area inset set. 
- iOS
Make sure basic previewer functionality works
> Check if Element parent is null before getting the padding insets

- Xamarin.Forms.Controls/GalleryPages/MapWithItemsSourceGallery.xaml
- Xamarin.Forms.Controls/GalleryPages/MapWithItemsSourceGallery.xaml.cs
- Xamarin.Forms.Core.UnitTests/MapTests.cs
- Xamarin.Forms.Maps/Map.cs
Added ItemTemplateSelector property to Map
See https://github.com/xamarin/Xamarin.Forms/pull/4269#issuecomment-452822221
Added:
- DataTemplateSelector Map.ItemTemplateSelector { get; set; } //Bindable Property
None
Not applicable
> Map with ItemTemplateSelector

- Xamarin.Forms.Core/IElementConfiguration.cs
Fast Renderer UI tests broke because IElementConfiguration<T> can no longer be covariantly cast which makes us realize that removing the out parameter will be too breaking. It'll also be breaking in such a way that's not obvious. 
Reverts #5449
- iOS
- Android
- UWP
> Add covariance back to IElementConfiguration

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4684.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4684.xaml.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/App.cs
- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Controls/TestCases.cs
- Xamarin.Forms.Controls/XamStore/StoreShell.xaml
- Xamarin.Forms.Controls/XamStore/StoreShell.xaml.cs
- Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs
- Xamarin.Forms.Core/Shell/Shell.cs
- Xamarin.Forms.Material.Android/Xamarin.Forms.Material.Android.csproj
- Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs
- Xamarin.Forms.Sandbox.Android/Xamarin.Forms.Sandbox.Android.csproj
- added UI test for Issue4684 to demonstrate UI tests
- Added an internal constructor to shell that lets us disable the flag check. Since all our UI tests have internals visible this makes it easy to circumvent the flag check without changing the flags
- added a TestShell base class to mimic other Test<Pages>. Added some helper methods here for opening flyout and clicking on menus
- Added Store shell to top list of gallery so it can be swapped in for main page
- Changed the base class on store shell to test shell. In theory this should make it so you can create an Issue that just inherits from StoreShell and then write a UI test against StoreShell
- Changed the AccessibilityIdentifier on the app bar button on iOS to be OK like it is on android which is probably wrong in both cases but now …
> Extend Control Gallery to allow for Shell UI Tests

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4600.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ItemInsert.cs
Remove `Ignore` attribute, fix broken test input, and add flag to allow test to run.
Test will _not_ run on UWP, as the underlying CollectionView features have not yet been implemented.
- fixes #4943
None
> Make UI test 4600 run on Android/iOS

- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Controls/GalleryPages/DynamicViewGallery.cs
For convenient visual testing of all public properties of visual elements, it is not always convenient to create a new gallery. This gallery automatically adds universal pikers for manual testing of basic controls.
- run Dynamic ViewGallery
- select any control
> Added dynamic view gallery

- Xamarin.Forms.Core/SearchHandler.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5706.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5706.xaml.cs
Change the default BindingMode for some properties
- fixes #5706
None
- iOS
- Android
- UWP
None
Not applicable
> [C] change searchHandler bindingMode

- Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5510.xaml
- Xamarin.Forms.Xaml.UnitTests/Issues/Gh5510.xaml.cs
XamlC: Resolve generic parameters for indexers 
- fixes #5510
None
None
Not applicable
> [X] resolve generic indexer types

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5535.cs
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewSwapGallery.xaml
- Xamarin.Forms.Platform.Android/CollectionView/EmptyViewAdapter.cs
Prevent crash when displaying EmptyView on Android.
Update EmptyViewAdapter to create a new ViewHolder when the EmptyView or EmptyViewTemplate properties change.
Also adds an automated test for this behavior.
- fixes #5535 
None
- Android
None
Not applicable
> Allow EmptyView swapping in Android CollectionView

- Xamarin.Forms.Platform.MacOS/Renderers/NavigationPageRenderer.cs
Fixed RemovePage method for navigation in MacOs
- fixes #5257
None
- MacOs
No crash during navigation
Not applicable
* Add 3 pages to a NavigationPage stack (A, B, C)
* Remove the page in the middle  (B)
* Pop the last page form the stack (C)
```csharp
private Page _page1 = new ContentPage { BackgroundColor = Color.Red };
private Page _page2 = new ContentPage();
private Page _page3 = new ContentPage { BackgroundColor = Color.Green };
public App()
{
MainPage = new NavigationPage(_page1);
}
protected override async void OnStart()
{
await Task.Delay(3000);
MainPage.Navigation.InsertPageBefore(_page2, _page1);
MainPage.Navigation.InsertPageBefore(_page3, _page2);
await Task.Delay(2000);
MainPage.Navigation.RemovePage(_page2);
await _page1.Navigation.PopAsync();
}
```
> [macOS] NavigationRenderer internal stack reversed after RemovePage

- Xamarin.Forms.Core/Device.cs
These helpers keep popping up on forums/stackoverflow[1][2],
would be nice to include them out of the box.
[1] https://forums.xamarin.com/discussion/51720/wait-for-device-begininvokeonmainthread
[2] https://stackoverflow.com/a/47941859
> [Core] Add some Device.InvokeOnMainThread helpers

- Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs
- Xamarin.Forms.Xaml/XamlLoader.cs
- Xamarin.Forms.Xaml/XamlParser.cs
`XamlLoader.Create()` does not resolve root type if it is a generic. Also, it provides the wrong type name to `FallbackTypeResolver` (it provides the base type name, rather than, for example, ``TypeName`1``). This is because it ignores the `x:TypeArguments` attribute when determining the type name.
- fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/815082
None
None
Not applicable
Manually tested in previewer. Added test to `DesignTimeLoaderTests`.
> XamlLoader should not ignore x:TypeArguments on root node

- Xamarin.Forms.Platform.Android/CollectionView/SelectableViewHolder.cs
`SelectableViewHolder` is using `View.ForeGround` (`setForeground()`) to set the ripple effect on selection; the ripple effect is available on API 21+, but the `setForeground()` method is not available on `View` until API 23. 
This change increases the API check from 21 to 23 for attempting to set the ripple effect.
- fixes #5693 
None
- Android
None
Not applicable
Run the Control Gallery on an Android device with API 22 or lower; navigate to CollectionView Gallery -> Selection Galleries -> Selection Modes, selection "Single", and select an item.
If the application crashes, this fix has failed.
> Increase API level check for setting Android ripple effect on selection

- Xamarin.Forms.Material.Android/MaterialEditorRenderer.cs
- Xamarin.Forms.Material.Android/MaterialFormsTextInputLayoutBase.cs
Removed duplicate material editor placeholder.
- fixes #5822
None
- Android
None
Before
After
- check VisualGallery
- check Editor Gallery
> [Android] fixes material placeholder

- README.md
- build.cake
- copied current master readme back to 3.6.0 
- updated readme to reflect better multi target restoring on Mac
- simplified cake script to no longer rebuild Control Gallery as VSMAC 2019 looks to process the resource files better
> update build script for mac and readme based on vs mac 2019

- Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs
We were changing the default color to White, then when comparing if we should render as origin (with color) we were comparing with the initial color but not with the Color.White we set as default on the platform side. 
This was preventing Shell to tin the FontIcon.
If the user want's to override and provide the color he can use the `Color` on FontImageSource.
- fixes #5071
None
- iOS
Allows to tint `FontImageSource`
Not applicable
> [iOS] Fix when we render the font icon image as original

- Xamarin.Forms.Platform.WPF/Properties/AssemblyInfo.cs
- Xamarin.Forms.Platform.WPF/Renderers/ImageButtonRenderer.cs
- Xamarin.Forms.Platform.WPF/Xamarin.Forms.Platform.WPF.csproj
Implemented ImageButtonRenderer for WPF
- fixes #4991
None
- WPF
None
Not applicable
To test the ImageButton, the image file oasissmall.jpg must be included in the WPF ControlGallery.
> Implemented ImageButtonRenderer for WPF

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41205.cs
Add preserve attributes and automated test for House Keeping Item
- fixes #2353 
Run Bugzilla41205 and make sure the text shows up. This adds UI tests so make sure all UI Tests pass
> Add automated test for Bugzilla41205

- Xamarin.Forms.Core/Switch.cs
- Xamarin.Forms.Platform.Android/AppCompat/SwitchRenderer.cs
- Xamarin.Forms.Platform.Android/Renderers/SwitchRenderer.cs
Add a null check to `TrackDrawable`, which may not be set and thus may be null.
- fixes #5553
None
- Android
None
Not applicable
See if the project attached to #5456 crashes. Spoiler alert: It will, but for a different and totally unrelated reason (https://github.com/xamarin/Xamarin.Forms/issues/5456#issuecomment-481486341).
> [Android] Null check on Switch TrackDrawable

- Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs
Using ViewCompat.SetClipBounds to set clipping bounds for ItemsViewRenderer. 
- fixes #4790
None
- Android
None
Not applicable
> Port fix from 4794 to handle clip bounds on sub-API-19 Android

- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/HomeIndicatorPageiOS.cs
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/MasterDetailPageiOS.cs
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/TabbedPageiOS.cs
- Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGallery.cs
- Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Page.cs
- Xamarin.Forms.Platform.iOS/PlatformRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PhoneMasterDetailRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs
This is a Platform Specific feature which enables setting the visibility of the iOS Home Indicator on a per-view basis.
- fixes #5310 
Added in Xamarin.Forms.PlatformConfiguration.iOSSpecific.Page:
- public static readonly BindableProperty PrefersHomeIndicatorAutoHiddenProperty;
- public static bool GetPrefersHomeIndicatorAutoHidden(BindableObject element);
- public static void SetPrefersHomeIndicatorAutoHidden(BindableObject element, bool value);
- public static bool PrefersHomeIndicatorAutoHidden(this IPlatformElementConfiguration<iOS, FormsElement> config);
- public static IPlatformElementConfiguration<iOS, FormsElement> SetPrefersHomeIndicatorAutoHidden(this IPlatformElementConfiguration<iOS, FormsElement> config, bool value);
- iOS
NavigationPage:
TabbedPage:
MasterDetailPage:
> [iOS] Add Platform Specific features for PrefersHomeIndicatorAutoHidden

- Xamarin.Forms.Platform.Android/Renderers/ShellItemRenderer.cs
- fixes #4758
None
- Android
None
Not applicable
- run Shell control gallery
- select page with tabs. ex: `GamesPage`
- click `Hide tabs` > `Add tab` > `Remove tab`
- tabs should be hidden
> [Android, shell] fixes visibility of tabs after their changes

- .nuspec/Xamarin.Forms.nuspec
References have to specified explicitly otherwise the design package gets added into VS for Mac which causes exceptions
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/846719
> Add explicit references back into nuspec

- Xamarin.Forms.Core/Shell/ShellContent.cs
- Xamarin.Forms.Core/Shell/ShellItem.cs
- Xamarin.Forms.Core/Shell/ShellSection.cs
This hides Shell<things> and just shows the Tab aliases for intellisense.
Set ShellItem, ShellContent, and ShellSection  to EditorBrowsable(false) so that FlyoutItem, TabContent, and Tab are all that show up but won't cause compile exceptions.
> [Shell] Hide Shell types from being browsable

- Xamarin.Forms.Platform.iOS/PlatformRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
- Xamarin.Forms.Platform.iOS/Renderers/PhoneMasterDetailRenderer.cs
Don't call iOS11 APIs on iOS10 or lower.
- None
None
- iOS
None
Not applicable
Should fix iOS10 UITests
> [iOS] Fix usage of iOS11 api

- Xamarin.Forms.Core/Shell/Shell.cs
Removed GroupHeaderTemplate as it has not been implemented yet and we can add it back once the work is done to create it
- fixes #5870
Removed:
- Shell.GroupHeaderTemplate as it has not been implemented.
> remove unused Group Header Template

- Xamarin.Forms.Core/Cells/Cell.cs
- Xamarin.Forms.Platform.iOS/Cells/CellRenderer.cs
Another attempt to resolve the issue with UWP covariance performance. Another option we could go for would be to just convert the UI Test list in control gallery to a collectionview
Though right now it's a TableView
Basically I just move the PlatformConfiguration to an internal class on Cell to proxy the On calls to
- make sure UI Tests work on UWP
- make sure you can change the default background color of a cell on iOS using the platform specific
> Move IElementConfiguration to an internal structure on Cell

- Xamarin.Forms.Platform.MacOS/Renderers/EntryRenderer.cs
Create native entry control only if there is corresponding XF control.
Similar changes with https://github.com/xamarin/Xamarin.Forms/pull/5363
fixes #5881
None
macOS
No crash
Not applicable
See sample attached to original issue
> [macOs] Fixed NRE during EntryRenderer disposing

- Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
All this does is move the code that registers the appcompat renderers at runtime to there own method. The effects of this are
- better organization
- More importantly,  now the previewer can just call into this method to register the necessary appcompat renderers
> [Android] move runtime registration of renderers to its own method

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Helpers/GarbageCollectionHelper.cs
The Issue5555 test is failing about 75% of the time on Android; testing the theory that this is a timing issue because the second Collect call isn't being waited on.
> Testing a theory about an unreliable memory leak test

- Xamarin.Forms.ControlGallery.WindowsUniversal/SecondaryWindowService.cs
- Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
- Xamarin.Forms.Controls/CoreGallery.cs
- Xamarin.Forms.Controls/ISecondaryWindowService.cs
- Xamarin.Forms.Core/Internals/Ticker.cs
- Xamarin.Forms.Platform.UAP/Forms.cs
- Xamarin.Forms.Platform.UAP/Platform.cs
- Xamarin.Forms.Platform.UAP/WindowsBasePlatformServices.cs
- Xamarin.Forms.Platform.UAP/WindowsTicker.cs
Adds a check for the existence of the Forms resources when opening a secondary window and loads them if necessary.
Adds a workaround for using the correct dispatcher from Device.BeginInvokeOnMainThread when there are multiple windows present. Also adds a workaround for using multiple Tickers when multiple windows are present.
- fixes #2229
- closes #2432
Added `protected virtual Ticker GetTickerInstance()` to `Ticker` to allow platforms to modify the number of instances of Tickers available.
- Core
- UWP
None
Not applicable
On UWP, Control Gallery now includes a button to open a secondary window; it will be populated by the test page for issue 2842.
We do not currently have a mechanism for automating tests in a secondary window.
> [UWP] Allow embedding Forms page in secondary window

- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2951.xaml
- Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2951.xaml.cs
Issue2951 occasionally fails UI Tests most likely because the read of the three buttons happens before they actually render. This adds some code that lets the UI Test wait for a prompt that they've finished rendering
Run and rerun the API 28 LR / FR a couple times before merging to see if this test fails at all
> add delay to UI Test 2951

- Xamarin.Forms.Platform.UAP/Platform.cs
If the back button in UWP is pressed, but there's nothing in the backstack, the `Last()` LINQ query will throw `System.InvalidOperationException: 'Sequence contains no elements`
This change avoids that, and just returns false that Forms didn't handle the event.
Exception thrown when turning the backbutton on, but not having anything put in the backstack.
None
None
- UWP
None
Not applicable
> Avoid LINQ exception

- .nuspec/Xamarin.Forms.Maps.nuspec
- .nuspec/Xamarin.Forms.nuspec
- PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj
- Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
- Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj
- Xamarin.Forms.Sandbox.Android/Xamarin.Forms.Sandbox.Android.csproj
Context: https://github.com/xamarin/xamarin-android/issues/2982
The Blank Xamarin.Forms app template in VS 2019 takes longer to build
than in VS 2017. A little research is showing that this is due to use
of the 28.x support libraries... For example, the build includes ~20
*more* jar files in the template from 2019 than 2017. The
`_CompileDex` step alone goes from ~15.2s to ~18.2s.
This lead me down the road of investigating if we can remove any
support libraries by default in Xamarin.Forms apps. I am also seeing
if there is more we can do in Xamarin.Android for this problem, in
general.
It looks like we can remove:
* Xamarin.Android.Support.v7.MediaRouter
* Xamarin.Android.Support.Media.Compat
Neither of these appear to be used, but have been listed as
dependencies of Xamarin.Forms for a …
> Remove Xamarin.Android.Support.v7.MediaRouter

- Xamarin.Forms.Platform.GTK/Renderers/FrameRenderer.cs
Frame's content wrapped into a Gtk.Fixed container since Gtk.Frame itself can't position it's content.
In FrameRenderer.cs Frame's native content wrapped into a Gtk.Fixed container since Gtk.Frame itself can't position it's content. So content view will be positioned by wrapping Gtk.Fixed.
- fixes #5533 
None
- GTK
Padding and margin properties will work when view is a Content of a Frame.
Before
After
Described in the issue #5533
> [GTK] Fix Padding/Margin properties of Frame element (#5533)

- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CollectionViewGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CollectionViewGalleryTestItem.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/DataTemplateGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ExampleTemplates.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ItemSizeGalleries/DynamicItemSizeGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ItemSizeGalleries/ItemsSizeGallery.cs
- Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ItemSizeGalleries/VariableSizeTemplateGridGallery.cs
- Xamarin.Forms.Platform.Android/CollectionView/ItemContentView.cs
- Xamarin.Forms.Platform.Android/CollectionView/TemplatedItemViewHolder.cs
- Xamarin.Forms.Platform.iOS/CollectionView/HorizontalTemplatedCell.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewCell.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
- Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
- Xamarin.Forms.Platform.iOS/CollectionView/TemplatedCell.cs
- Xamarin.Forms.Platform.iOS/CollectionView/UICollectionViewDelegator.cs
- Xamarin.Forms.Platform.iOS/CollectionView/VerticalTemplatedCell.cs
Allow CollectionView items on iOS and Android to dynamically resize as their content changes.
Also fixes some invalidation issues which were causing the problems noted in issues #5521 and #5721.
- fixes #5647
- fixes #5521
- fixes #5721
None
- iOS
- Android
None
In Control Gallery, navigate to CollectionView Gallery -> Item Size Galleries -> Expanding Text
> Allow CollectionView items to resize with their content

- Xamarin.Forms.Core.UnitTests/ShellTestBase.cs
- Xamarin.Forms.Core.UnitTests/ShellTests.cs
- Xamarin.Forms.Core.UnitTests/ShellUriHandlerTests.cs
- Xamarin.Forms.Core/Routing.cs
- Xamarin.Forms.Core/Shell/IShellItemController.cs
- Xamarin.Forms.Core/Shell/IShellSectionController.cs
- Xamarin.Forms.Core/Shell/Shell.cs
- Xamarin.Forms.Core/Shell/ShellItem.cs
- Xamarin.Forms.Core/Shell/ShellNavigationState.cs
- Xamarin.Forms.Core/Shell/ShellSection.cs
- Xamarin.Forms.Core/Shell/ShellUriHandler.cs
- removed GoToPart from the IShellController code parts because there isn't any platform code that uses them so it's not useful at this point
- added an exception if someone tries to do a relative route to a shell section as this behavior hasn't been implemented yet so I don't want the behavior to change once we make it so relative routes push to a stack. I also added an internal overload to turn this on for unit tests so unit tests can continue unhindered with validating behavior
- I fixed  the logic when you use an absolute route to navigation via <routename> / <page>. It was causing an  infinite loop
- removed getroutekeys and a few additional classes added in pre9 that will become exposed later down the road
Removed:
- Routing.GetRouteKeys
- class NavigationRequest
- GotoPart from the …
> fix infinite loops and remove public apis
