Xamarin.Forms.Platform.WPF/Helpers/TreeHelper.cs
`WpfHelper.FindChildren`: Pass `forceUsingTheVisualTreeHelper` to recursive calls.
- fixes #5921 
None
- WPF
If using the visual tree helper, `TreeHelper.FindChildren` now uses the visual tree helper all the way down to the leaf nodes.
Not applicable
As described in #5921
=> WpfHelper.FindChildren: Pass forceUsingTheVisualTreeHelper to recursive calls.

Xamarin.Forms.Controls/ShellContentTest.xaml, Xamarin.Forms.Controls/XamStore/StoreShell.xaml, Xamarin.Forms.Core/Shell/Shell.cs, Xamarin.Forms.Platform.iOS/Platform.cs, Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewController.cs
- Remove Shell.SetPaddingInsets api for now as it's not really serving it's correct purpose
- Fixed iOS so that it just pads the Flyout and page renderer the same on iOS and android which means you don't have to set SafeArea anymore
- Also fixes ios10 to pad the page area content
- fixes #5971
Removed:
- Shell.SetPaddingInsets 
None
- iOS
- Flyout now offsets from notch or status bar on ios10
- when the header scrolls with the list it doesn't show up behind the clock anymore
Before / After
When scrolling I added a mask so it doesn't overlap the status bar
iOS 10
- 4684 should pass on ios10
=> [iOS] remove SetPaddingInsets api and just have it pad content and flyout by default

Xamarin.Forms.Platform.Tizen/Native/ToolbarItemButton.cs, Xamarin.Forms.Platform.Tizen/Shell/ShellRenderer.cs, Xamarin.Forms.Platform.Tizen/Xamarin.Forms.Platform.Tizen.csproj
Tizen didn't have treat warnings as errors set for debug builds (only for release builds) so these errors weren't caught
=> fix tizen obsolete errors

Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs, Xamarin.Forms.ControlGallery.Android/DisposeLabelRenderer.cs, Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs, Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj, Xamarin.Forms.ControlGallery.Android/_1909CustomRenderer.cs, Xamarin.Forms.ControlGallery.Android/_5724CustomRenderers.cs, Xamarin.Forms.ControlGallery.Android/_60122ImageRenderer.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5724.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs, Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs, Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs, Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs, Xamarin.Forms.Platform.Android/Flags.cs
Use Fast Renderers by default. Introduce `UseLegacyRenderers` flag to go back. Unseal fast renderers & add the most common extension points.
- fixes #5724
None
- Android
None
Not applicable
=> [Android] Use Fast Renderers by Default

Xamarin.Forms.Platform.Android/Renderers/PickerRenderer.cs
Dialog needs to be set to null when it's dismissed so that it can live again
- fixes #5945
- Android
Comment out the registering of the appcompat renderer for the picker and then test some pickers
=> [Android] set dialog to null when dismissed

Xamarin.Forms.Platform.Android/Renderers/SwitchRenderer.cs
Copy over nullable check when disposing of track to non appcompat
- fixes #5970
- Android
=> add check for null track drawable

.nuspec/Xamarin.Forms.targets, .nuspec/proguard.cfg, Xamarin.Forms.Sandbox.Android/proguard.cfg
Shell needs some additional help to work with proguard.
I also added a keep for multidex which will be fixed in an upcoming VS release but I figured we might as well just include it for now to remove friction
Also added a property to disable default proguard rules if users want more fine grained control
```xml
<Target Name="IncludeProguardForAndroid" Condition="'$(XFDisableDefaultProguardConfiguration)' != 'True'">
<ItemGroup>
<ProguardConfiguration Include="$(MSBuildThisFileDirectory)MonoAndroid10\proguard.cfg" />
</ItemGroup>
</Target>
```
- fixes #5799 
- Android
install the nuget for this PR into a XF project using shell.  On that project enable multidex, proguard, and set the linker to full. At this point the project should run without any errors
=> additional proguard rules for shell

Xamarin.Forms.Core.UnitTests/ShellUriHandlerTests.cs, Xamarin.Forms.Core/Shell/Shell.cs, Xamarin.Forms.Core/Shell/ShellSection.cs
Pages on shell sections were always just being pushed off. This change correctly interprets the URI request and then pushes or replaces accordingly
- fixes #6016 
Removed:
- Made ShellSection.GoToAsync internal for now. Converted away from public virtual. This will be replaced later with handlers
There is a unit test but you can try doing this
gotoasync("page")
gotoasync("page")
and make sure it creates a stack of two pages
=> fix global routes to push onto stack correctly

Xamarin.Forms.Core/FontSizeConverter.cs, Xamarin.Forms.Core/NamedSize.cs, Xamarin.Forms.Platform.Android/Forms.cs, Xamarin.Forms.Platform.UAP/FontExtensions.cs, Xamarin.Forms.Platform.iOS/Forms.cs
We now use the iOS Prefered Font Scaling stuff so fonts are magical
Added new Named Fonts
fixes #5474
Added:
NamedSize Sizes
Large = 4,
Body = 5,
Header = 6,
Title = 7,
Subtitle = 8,
Caption = 9
- iOS
- Android
- UWP
iOS Font named font sizes now Scale just like Android does.
Use a named font,
Set the Large Font Size  option in iOS, Accessibility options.
=> Added new named Font Sizes, iOS Named fonts now all AutoScale based on Accessibility Options

Xamarin.Forms.Core/PlatformConfiguration/WindowsSpecific/ListView.cs, Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
`UpdateWindowsSpecificSelectionMode` method could not be fired when the `Specifics.SelectionModeProperty` changed. Because the property names `Specifics.SelectionModeProperty` and  `ListView.SelectionModeProperty` were equal.
none
None
- UWP
Can change `Windows.Specifics.SelectionModeProperty`.
Not applicable
=> [UWP] fix  ListView renderer

Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
If you don't store the page container to a local variable then scenarios can happen where it gets collected. The main area we were seeing this issue was when using the previewer on the About page of the MDP template
=> retain local variable of page so not collected

Xamarin.Forms.Build.Tasks/XamlCTask.cs, Xamarin.Forms.Core/Internals/ResourceLoader.cs, Xamarin.Forms.Xaml.UnitTests/ResourceLoader.xaml.cs, Xamarin.Forms.Xaml/XamlLoader.cs
allow resourceprovider to track lifecycle of xaml-generated object
=> [X] pass the instance along the rlq

Xamarin.Forms.Maps/Map.cs
Changed the message of the `NotSupportedException` thrown when the `Map.ItemTemplate` property is set to a `DataTemplateSelector`. Instead of telling the user to just use a single `DataTemplate` it directs them to use the `ItemTemplateSelector` property.
None
None
None
Not applicable
Not applicable
=> Change error message when Map.ItemTemplate is set to a DataTemplateSelector

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/FlagTestHelpers.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5535.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5949.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5949_1.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5949_1.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5949_2.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5949_2.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/CollectionView/SelectableItemsViewRenderer.cs
Missing null check in `SelectableItemsViewRenderer.SetupNewElement` causes an unhandled exception when the CollectionView's renderer is disposed. This change adds the null check and an automated test.
- fixes #5949 
None
- iOS
None
Not applicable
Navigate to the test for Issue 5949 and follow the instructions.
=> [iOS] Add missing null check to `SelectableItemsViewRenderer.SetupNewElement`.

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4915.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4915.xaml.cs, Xamarin.Forms.Platform.Android/AppCompat/ButtonRenderer.cs, Xamarin.Forms.Platform.Android/AppCompat/ImageButtonRenderer.cs, Xamarin.Forms.Platform.Android/ButtonLayoutManager.cs, Xamarin.Forms.Platform.Android/Extensions/ImageViewExtensions.cs, Xamarin.Forms.Platform.Android/IDisposedState.cs, Xamarin.Forms.Platform.Android/ImageCache.cs, Xamarin.Forms.Platform.Android/Renderers/ButtonRenderer.cs, Xamarin.Forms.Platform.Android/ResourceManager.cs, Xamarin.Forms.Platform.Android/VisualElementRenderer.cs, Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
The bulk of this code is to make it so the layout and loading of images doesn't thrash the system as much
- I added a basic lrucache for images loaded from url (Added Peppers and Matt on here to validate my effort)
- I made the button invalidate the measure only after it's been laid out otherwise you get all these repetitive invalidations on initial load
- API 19 doesn't look to clear the image out when it's set to translucent so for < Lollipop I just set the drawable to null
- fixes #6061
- fixes #6010 
- Android
Test all the image loading on android you can
Issue4915 does a lot of different image loading against different types
=> [Android] Image load fixes

Xamarin.Forms.Core.UnitTests/TemplatedViewUnitTests.cs, Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj, Xamarin.Forms.Core/IControlTemplated.cs, Xamarin.Forms.Core/TemplateUtilities.cs, Xamarin.Forms.Core/TemplatedPage.cs, Xamarin.Forms.Core/TemplatedView.cs
Adds a way for templated views (i.e. ContentView, ContentPage) to get template child by name.
When creating custom controls, especially more complex ones, there's the need to get an instance of an element in the template. This is because not everything can be done in the template XAML or it could be harder to achieve some UI logic in XAML than doing it in code:
```
<controls:MyCustomControl... >
<controls:MyCustomControl.ControlTemplate>
<ControlTemplate>
<Label x:Name="myLabel"/>
</ControlTemplate>
<controls:MyCustomControl.ControlTemplate>
</controls:MyCustomControl>
```
```
class MyCustomControl : TemplatedView
{
Label _myLabel;
protected override OnApplyTemplate()
{  
_myLabel = GetTemplateChild("myLabel");
}
}
```
This is a **very** simple example which only shows how the new …
=> Templated view GetTemplateChild(string)

Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutTemplatedContentRenderer.cs, Xamarin.Forms.Sandbox/Xamarin.Forms.Sandbox.csproj
This PR stops trying so hard to make parts work with the designer and just exits early. Knowing what resources will and won't be available at designer runtime is just too inconsistent
=> return from designer earlier

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/VisualControlsPage.xaml, Xamarin.Forms.Material.Android/MaterialColors.cs, Xamarin.Forms.Material.Android/MaterialFrameRenderer.cs, Xamarin.Forms.Material.iOS/MaterialFrameRenderer.cs
Apply shape treatment with corner radius settings
- fixes #5544
Check visual gallery. I modified two of the frames to demonstrate different corner radiuses
=> Apply round corners shape based on radius

Xamarin.Forms.Platform.Android/CollectionView/ItemContentView.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewAdapter.cs, Xamarin.Forms.Platform.Android/CollectionView/TemplatedItemViewHolder.cs
Reuse template Views and Renderers in the Android CollectionView. Significantly reduces the number of allocations and calls to Activator.CreateInstance.
- choppy scrolling because of GC delays
None
- Android
None
Not applicable
Unfortunately, no good way to automate testing for this right now. To test it, in Control Gallery navigate to CollectionView Gallery -> DataTemplate Galleries and run any of the examples; scroll around - the scrolling should be smooth (or at least, _smoother_).
=> Make Android CollectionView smarter about recycling elements/renderers

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/Renderers/ShellRenderer.cs, Xamarin.Forms.Sandbox.Android/Properties/AndroidManifest.xml
Makes shell not crash on ios previewer
- run a normal shell app to a device and make sure that still works
- install the nuget from this PR and make sure designer doesn't crash
=> [iOS] add DesignerFlyoutRenderer when running as previewer

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1583.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4138.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4915.xaml.cs, Xamarin.Forms.Controls/GalleryPages/ImageSourcesGallery.cs, Xamarin.Forms.Controls/GalleryPages/NavigationBarGallery.cs, Xamarin.Forms.Controls/GalleryPages/TitleView.xaml.cs, Xamarin.Forms.Core/Button.cs, Xamarin.Forms.Core/NavigationPage.cs, Xamarin.Forms.Core/Page.cs, Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs, Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs, Xamarin.Forms.Platform.Android/Platform.cs, Xamarin.Forms.Platform.MacOS/Renderers/TabbedPageRenderer.cs, Xamarin.Forms.Platform.UAP/FormsSlider.cs, Xamarin.Forms.Platform.UAP/MasterDetailPageRenderer.cs, Xamarin.Forms.Platform.UAP/NavigationPageRenderer.cs, Xamarin.Forms.Platform.UAP/Platform.cs, Xamarin.Forms.Platform.UAP/SliderRenderer.cs, Xamarin.Forms.Platform.UAP/SliderStyle.xaml, Xamarin.Forms.Platform.UAP/TabbedPageStyle.xaml, Xamarin.Forms.Platform.iOS/Extensions/ColorExtensions.cs, Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
With #4915 we are wanting to keep all the original types the same so as to limit/remove any ABI breaks. This change snuck in 
- fixes #6123
Modified properties:
```diff
-public ImageSource Image { get; set; }
+public FileImageSource Image { get; set; }
```
Removed methods:
```csharp
public static ImageSource GetTitleIcon (BindableObject bindable);
public static void SetTitleIcon (BindableObject bindable, ImageSource value);
```
Modified properties:
```diff
-public FileImageSource BackgroundImage { get; set; }
+public string BackgroundImage { get; set; }
```
Added methods:
```csharp
[Obsolete ("GetIconDrawable is obsolete as of 4.0.0. Please override SetTabIconImageSource instead.")]
protected virtual Android.Graphics.Drawables.Drawable GetIconDrawable (Xamarin.Forms.FileImageSource icon); …
```
=> 4.0 ABI Fixes

Xamarin.Forms.Platform.Android/Elevation.cs, Xamarin.Forms.Platform.Android/FastRenderers/VisualElementRenderer.cs
VisualElementRenderer and ElevationHelper should be public. It's needed for custom fast renderer implementations. Currently, libs like FFImageLoading use reflection to use those classes.
@samhouts Related to this: https://github.com/xamarin/Xamarin.Forms/pull/5926#issuecomment-489590844
- Android
None
Not applicable
=> [Android] VisualElementRenderer and ElevationHelper should be public

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6130.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6130.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6132.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core.UnitTests/WebViewUnitTests.cs, Xamarin.Forms.Core/PlatformConfiguration/AndroidSpecific/WebView.cs, Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs
The EnableZoomControls BP was missing the "s", making it impossible for XAML to pick it up.
The helper methods were supposed to set the values instead of return the values, so fixing that, too.
- fixes #6132 
- fixes #6130 
Removed field:
```csharp
public static Xamarin.Forms.BindableProperty EnableZoomControlProperty;
```
Added field:
```csharp
public static Xamarin.Forms.BindableProperty EnableZoomControlsProperty;
```
Removed methods:
```csharp
public static bool DisplayZoomControls (this Xamarin.Forms.IPlatformElementConfiguration<Xamarin.Forms.PlatformConfiguration.Android,Xamarin.Forms.WebView> config);
public static bool EnableZoomControls (this Xamarin.Forms.IPlatformElementConfiguration<Xamarin.Forms.PlatformConfiguration.Android,Xamarin.Forms.WebView> config);
```
Added methods: …
=> [Android] Fix WebView EnableZoomControls and DisplayZoomControls api

Xamarin.Forms.Core.UnitTests/ShellTests.cs, Xamarin.Forms.Core/Element.cs, Xamarin.Forms.Core/Page.cs, Xamarin.Forms.Core/Shell/Shell.cs, Xamarin.Forms.Core/Shell/ShellSection.cs, Xamarin.Forms.Core/StyleSheets/StyleSheet.cs, Xamarin.Forms.Sandbox/App.StartHere.cs, Xamarin.Forms.Sandbox/MainPage.xaml, Xamarin.Forms.Sandbox/MainPage.xaml.cs, Xamarin.Forms.Sandbox/ShellPage.xaml, Xamarin.Forms.Sandbox/Styles.css
AFAICT you can't add to a logical child structure on page and have it only act in a logical non visual fashion. This creates a structure ActuallyLogicalChildren that's a combination of pages that are real children (visual) and ones that are only logically bound to the page through bindable properties.
At some point we could expose this property which would easily allow people to do the same in custom controls
This also made the code in Element simpler and more consolidated for propagating visual and RTL properties
In reality I think we should make LogicalChildren work in such a way that there's a differentiation between LogicalChildren and Children but this works for now and I don't think it's unacceptably crazy
- fixes #4683
- fixes #5956
n/a
Apply a style …
=> [Shell] propagate css to logical child element

Xamarin.Forms.Controls/XamStore/StoreShell.xaml, Xamarin.Forms.Core.UnitTests/ShellTests.cs, Xamarin.Forms.Core/Shell/MenuShellItem.cs, Xamarin.Forms.Core/Shell/Shell.cs, Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRecyclerAdapter.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewSource.cs
- deleted Shell.MenuItems from the top level Shell class because it serves no purpose. Just add the menuitem to the root
- changed MenuItemTemplate to an attached property so you can attach different templates to menu items
- Fixed Text so that it'll propagate correctly when MenuItem is wrapped as MenuShellItem
- Fixed shell level menu item template so it applies correctly
- set parent of created template to shell like it does on iOS
- fixes #4399
- fixes #5707
Removed:
- made MenuShellItem Internal
- iOS
- Android
Updated shell with a custom menu item template you can see on ios and android
=> fix up shell menu items, fix templates, fix bindings

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2653.cs, Xamarin.Forms.Platform.Android/Elevation.cs, Xamarin.Forms.Platform.Android/VisualElementPackager.cs
If you have an elevation set on a control then that is going to trump a call to BringToFront. With the fastrenderers we unwrapped Button from ViewGroup so now it has a default elevation set. This means that even if you call BringToFront on an element that overlaps button the button will still be visually higher because it has a default elevation. 
This PR attempts to correlate the visual hierarchy to the elevation values set for controls. If a user sets an elevation themselves then that elevation is honored
- fixes #2989
- fixes #3543
- Android
Controls stacked with buttons will now get their elevation set to the same values as button
This PR enables UI Tests that were previously disabled
=> stack the elevation of elements

Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewController.cs
UI Test 5132 was crashing because the FlyoutHeader was null on loading.
n/a
None
- iOS
None
Not applicable
Run G5132. If it doesn't crash, success!
=> [iOS] Shell _headerView can apparently be null

Xamarin.Forms.Platform.iOS/Extensions/UIViewExtensions.cs
Running Shell on iOS10 with get a NRE when trying to get the UIButtons of UISearchBar.
None
- iOS
- Android
- UWP
None
Not applicable
=> [iOS] Fix NRE SearchHandler iOS10

Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewController.cs
The Frame on the tableview already accounted for SafeArea so it was causing too much spacing especially if no header view is present
- iOS
The Tableview should line up against the safe area better
*BEFORE*
*AFTER*
- test without a header view
- test the various scroll options with header view
=> remove safe area from inset

Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj, Xamarin.Forms.Controls/XamStore/StoreShell.xaml, Xamarin.Forms.Controls/XamStore/StoreShell.xaml.cs, Xamarin.Forms.Core/Internals/PropertyPropagationExtensions.cs, Xamarin.Forms.Core/Routing.cs, Xamarin.Forms.Core/Shell/BaseShellItem.cs, Xamarin.Forms.Core/Shell/MenuShellItem.cs, Xamarin.Forms.Core/Shell/Shell.cs, Xamarin.Forms.Core/Shell/ShellContent.cs, Xamarin.Forms.Core/Shell/ShellItem.cs, Xamarin.Forms.Core/Shell/ShellSection.cs, Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRecyclerAdapter.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewSource.cs
- add propagation for navbarvisible and tabbarvisible to propagate down children
- changed Shell.ItemTemplate to be an attached property so it can be attached to any Shell<thing>
- fixed implicit Shell<thing> creations to properly bind additional properties (like flyouticon)
- partially fixes #5940
Changed:
- Shell.ItemTemplate to be an attached property
- iOS
- Android
- UWP
- I added another flyout item to store shell where you can see these properties set at different hierarchies
=> item template attached, fix icon propagations

Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs
Unlike other versions of iOS, 10 needs a explicit call to `invalidateLayout` after reloading items or it will crash if the number of items in the data source has changed.
- fixes UI test 5793 failing on iOS 10
None
- iOS
None
Not applicable
Run UI test 5793 on iOS 10
=> InvalidateLayout after reload to avoid iOS 10 crash

Xamarin.Forms.Platform.Tizen/TizenPlatformServices.cs
This PR is to support new Named Font Sizes (Body, Caption, Header, Subtitle, Title) which are newly added from #5985 for Tizen. So, now Tizen's named font sizes for each `TargetIdiom` (Phone, TV, Watch) are as follows,
NamedSize  | Phone | TV | Watch 
---| ---| ---|---
**Micro** | 19 pt | 24 pt | 24 pt
**Small** | 22 pt| 26 pt | 30 pt
**Medium / Default** | 25 pt | 28 pt | 32 pt
**Large** | 31 pt | 32 pt | 36 pt
**Body** | 28 pt | 30 pt | 32 pt
**Caption** | 22 pt | 26 pt | 24 pt
**Header**| 138 pt | 84 pt | 36 pt
**Subtitle** | 28 pt | 30 pt | 30 pt
**Title** | 40 pt | 42 pt | 36 pt
None
None
- Tizen
The font size of `NamedSize.Large` on `TargetIdiom.TV` has been changed from 84pt to 32pt. If you want to use the existing font size (84pt), please use `NamedSize.Header` instead.
Not …
=> [Tizen] Support new Named Font Sizes for Tizen

Xamarin.Forms.Platform.iOS/CollectionView/HorizontalTemplatedCell.cs
Horizontal templated cell is constraining its width to the measured height instead of width. This change corrects that issue.
- fixes #6168
None
- iOS
None
Not applicable
=> Correctly constrain cell width on iOS

EmbeddingTestBeds/Embedding.XF/Directory.Build.props, EmbeddingTestBeds/Embedding.XF/Directory.Build.targets, EmbeddingTestBeds/Embedding.XF/Embedding.XF.csproj, PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj, PagesGallery/PagesGallery.UWP/PagesGallery.UWP.csproj, PagesGallery/PagesGallery.iOS/PagesGallery.iOS.csproj, PagesGallery/PagesGallery/Directory.Build.props, PagesGallery/PagesGallery/Directory.Build.targets, PagesGallery/PagesGallery/PagesGallery.csproj, Xamarin.Forms.Controls/Directory.Build.props, Xamarin.Forms.Controls/Directory.Build.targets, Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj, Xamarin.Forms.Sandbox/Directory.Build.props, Xamarin.Forms.Sandbox/Directory.Build.targets, Xamarin.Forms.Sandbox/Xamarin.Forms.Sandbox.csproj, Xamarin.Forms.Xaml.UnitTests/Directory.Build.props, Xamarin.Forms.Xaml.UnitTests/Directory.Build.targets, Xamarin.Forms.Xaml.UnitTests/MSBuild/MSBuildTests.cs, Xamarin.Forms.Xaml.UnitTests/MSBuild/_Directory.Build.props, Xamarin.Forms.Xaml.UnitTests/MSBuild/_Directory.Build.targets, Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
Change internal project and tests so they use Directory.Build.props and targets, so the order of execution is as close as what the user experience with NuGet.
=> Props and targets

Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs, Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs, Xamarin.Forms.Xaml.UnitTests/Issues/Gh5486.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh5486.xaml.cs, Xamarin.Forms.Xaml.UnitTests/Issues/Gh5651.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh5651.xaml.cs
This pull request fixes both issues, I have added Unit tests for both issues because there where two fixes necessary
Issue https://github.com/xamarin/Xamarin.Forms/issues/5486 fixed by this
previousPartTypeRef = property.PropertyType.ResolveGenericParameters(propDeclTypeRef);
Generic parameter where not resolved on propertyType
Issue https://github.com/xamarin/Xamarin.Forms/issues/5651 fixed by this
var p = face.InterfaceType.ResolveGenericParameters(typeRef).GetProperty(predicate, out var interfaceDeclaringTypeRef);
Generic Parameters where not resolved on interface
- fixes #5651
- fixes #5486
None
Compiled Bindings work now better for Generic Interfaces, enabeling more cases
Not applicable
Run Unit Tests
=> fixes BindableLayout DataTemplate - XamlC #5486

Xamarin.Forms.Platform.UAP/Platform.cs
If you add the `Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer` nuget package, you'll find the analyzer points out these locations as not correctly guarded against usage.
Potential to hit a type that isn't present.
None
None
- UWP
None
None
Not applicable
Add the `Microsoft.Toolkit.Uwp.PlatformSpecificAnalyzer` nuget package.
You'll still see the analyzer points out the MobileStatusBar property to not be guarded. There's not really away around that except to disable the warning using `#pragma warning disable UWP001 // Platform-specific`. I didn't want to add that though, unless the nuget package gets permanently added to the project, and any usage of the property will get called out by the analyzer, so it would be safe to disable here.
=> Properly guard against statusbar usage

EmbeddingTestBeds/Embedding.Tizen/Embedding.Tizen.csproj, PagesGallery/PagesGallery.Tizen/PagesGallery.Tizen.csproj, Stubs/Xamarin.Forms.Platform.Tizen/Xamarin.Forms.Platform.Tizen (Forwarders).csproj, Xamarin.Forms.ControlGallery.Tizen/Xamarin.Forms.ControlGallery.Tizen.csproj, Xamarin.Forms.Maps.Tizen/Xamarin.Forms.Maps.Tizen.csproj, Xamarin.Forms.Material.Tizen/Xamarin.Forms.Material.Tizen.csproj, Xamarin.Forms.Platform.Tizen/Xamarin.Forms.Platform.Tizen.csproj
Specify the `<TargetFramworkIdentifier>` and `<TargetFrameworkVersion>` to all tizen projects (`*.csproj`) explicitly. This is for resolving the issue occurred in vs2019 `16.1`.
Since VS2019 16.1 version, visual studio ran into an unexpected problem with Tizen projects as shown below. 
None
- Tizen
None
Just open the solution (`Xamarin.Forms.sln`) on VS2019 `16.1`. It is OK if you can't see any error messages of tizen projects.
=> [Tizen] Add TFM identifier and version explicitly for vs2019 16.1

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewBoundMultiSelection.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewBoundSingleSelection.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/BoundSelectionModel.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/MultipleBoundSelection.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/MultipleBoundSelection.xaml.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/SelectionGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/SelectionHelpers.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/SelectionModeGallery.xaml.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/SingleBoundSelection.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/SingleBoundSelection.xaml.cs, Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj, Xamarin.Forms.Core/Items/SelectableItemsView.cs, Xamarin.Forms.Core/Items/SelectionList.cs, Xamarin.Forms.Platform.iOS/CollectionView/SelectableItemsViewController.cs
These changes make the `SelectedItem` property two-way bindable so that binding to the `SelectedItem` property works as expected. 
These changes also update the `SelectedItems` property to be bindable from a viewmodel in an intuitive way.
Also adds automated tests for single and multiple selection binding.
- fixes #6158 
- fixes #5832 
None
None
Not applicable
=> Make CollectionView SelectedItem and SelectedItems binding function correctly

Xamarin.Forms.Platform.GTK/Controls/CustomFrame.cs, Xamarin.Forms.Platform.GTK/Extensions/ColorExtensions.cs, Xamarin.Forms.Platform.GTK/Renderers/FrameRenderer.cs
- Use Xamarin.Forms.Color instead of Gdk.Color for alpha support.
- Add an extension method from Gdk.Color to XF.Color.
- Call `base.OnElementChanged` at the end of the method in `FrameRenderer.cs`
- Remove set Shadow.
- fixes https://github.com/xamarin/Xamarin.Forms/issues/4700
None
- GTK
Having a transparent Frame becomes possible.
Just a basic content page with this 
```
<Frame x:Name="frame1" BackgroundColor="Blue" BorderColor="Red">
<Frame x:Name="frame2" BackgroundColor="Transparent" BorderColor="Transparent"/>
</Frame>
```
Should be enough to see the problem.
Local repro here: https://github.com/mfkl/Gtk-Frame-Background-Bug
Start `Gtk-Frame-Background-Bug\Gtk-Frame-Background-Bug.csproj`
Repro with fix in Xamarin.Forms repo: https://github.com/mfkl/Xamarin.Forms/tree/local-repro …
=> [GTK] Add Alpha support to Frame background

Xamarin.Forms.Platform.Android/CollectionView/SelectableViewHolder.cs
The check for being able to set the Ripple effect on the selection is looking at the wrong API level. While RippleDrawable was added in 21 (Lollipop), the `setForeground` method wasn't added until 23 (Marshmallow).
Automated tests missed it because we test 19 and then skip to 25, this is an issue specifically on 21 & 22.
- fixes #5693 (for real this time)
None
- Android
None
Not applicable
On a Lollipop device, Control Gallery -> Selection Galleries -> Selection Mode, Select "Single" and select an item.
=> Check for correct API version

Xamarin.Forms.Material.Android/MaterialButtonRenderer.cs, Xamarin.Forms.Platform.Android/AppCompat/ButtonRenderer.cs, Xamarin.Forms.Platform.Android/ButtonLayoutManager.cs, Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs, Xamarin.Forms.Platform.Android/IButtonLayoutRenderer.cs
This returns IButtonLayoutRenderer  to how it was defined in 3.6 so that it doesn't introduce ABI breaks for 4.0 
- Android
=> [Android] rollback IButtonLayoutRenderer  to match 3.6

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6260.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Material.Android/MaterialButtonRenderer.cs, Xamarin.Forms.Platform.Android/AppCompat/ButtonRenderer.cs, Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
The invalidate measure call when used with fastrenderers was causing a ping pong effect when loading images
- image loaded
- invalidate measure
- image.updateimage
- image loaded
- invalidate measure
- image.updateimage
- fixes #6260 
- Android
- UI test included
- any additional testing you want to do with button and setting the image and nulling it and just trying to break the layout would be helpful.
=> [Android] Remove call to update Image on button during measure

Version.targets, Xamarin.Forms.Xaml.UnitTests/AssemblyInfoTests.cs
#6068 was supposed to update the `AssemblyFileVersion` to let the DLLs better report the version to third-party libraries. Unfortunately, we accidentally updated the `AssemblyVersion` as well, which breaks all the bindings.
This change reverts the `AssemblyVersion` and changes the unit test to keep us stuck on 2.0.0.0 in perpetuity (or until we decide to add binding redirects or some other solution).
- fixes #6375
None
None
Not applicable
Install the nuget into the test projects supplied on #6375. If they are able to compile, success!
=> Roll back assembly version to 2.0.0.0

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5765.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/ItemContentView.cs
ItemContentView was not respecting MeasureSpecMode.Unspecified in the unconstrained direction, which caused FlexLayouts to always get a size of zero in that direction. These changes allow FlexLayout to measure correctly.
- fixes #5765
- fixes #5782
None
- Android
=> [Android] Pass correct measurement values to item content

Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs, Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
`Xamarin.Forms.Xaml.ApplyPropertiesVisitor.TryConnectEvent` connects an event to an event handler with the following two steps:
1. Find a method by name
2. Try to connect the event to the method, and throw an exception saying the method handler has an incorrect signature if it fails
However, there actually can be several methods with the same name but different signatures. This change solves the issue by iterating methods with the same name.
None
None
None
Not applicable
Unfortunately it is impossible to write a reliable test because the order of methods returned by `System.Reflection.RuntimeReflectionExtensions.GetRuntimeMethods` is not defined.
=> [Xaml[C]] Allow to connect to event handler with overloads

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GestureBubblingTests.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Controls/CoreGalleryPages/CoreGalleryPage.cs, Xamarin.Forms.Core.UITests.Shared/Remotes/BaseViewContainerRemote.cs, Xamarin.Forms.Core.UITests.Shared/Tests/EntryUITests.cs
Allow the core UI tests to jump directly to the relevant test, instead of hitting the "Move Next" button over and over again.
Ensure the presence of target element before querying the property value.
Fix bugs with Entry focus tests on devices with smaller screens and software keyboard enabled.
Avoid edge case with dismissal of Date/Time picker in tap bubbling tests.
=> Speed up core UI tests and reduce flakiness

Xamarin.Forms.Platform.WPF/Properties/AssemblyInfo.cs
Restored missed the Assembly attribute `ThemeInfo`
- fixes #6399
None
- WPF
Before
After
- run ControlGalley
=> [WPF] restored missed assembly attribute

Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs, Xamarin.Forms.ControlGallery.iOS/CustomEffects/GradientEffect.cs, Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6334.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/Renderers/PageContainer.cs, Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
We introduced a wrapper PageContainer and doing so we override the default LoadView of our PageRenderer ViewController. 
The default method provided a UIView with a Frame and Bounds, while our PageContainer doesn't provide one when it's created. Since our effects are attached when we set the elements for reuse on renderers when the user access the Bounds of the container there are not set ,while in previous versions there were (even if wrong ) .
Since these are related with size even previous versions should be using not the attach only but also the OnElementPropertyChanged or other methods to update there frame if the size changes. 
After some testing seems that the default size that was provided was the UIScreen even if inside a NavigationPage, this also is not very important as the …
=> [iOS] Fix Bounds for PageContainer 

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5268.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5268.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs
Caused by #4522 
Enabling `NestedScrollEnabled` for some reason turned off the work `SwipeRefreshLayout` on empty areas of ListView.
- fixes #5268
None
- Android
Refreshing is activated on all areas of ListView
- run UItest 5268
- try refreshing the ListView in a blank area by swiping down
=> [Android] fixes ListView pull-to-refresh gesture in non-data areas

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla26233.cs, Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
Preparation container for item receives an empty object instead `null`. This allows to create an empty container with transparency.
- fixes #6154
- fixes #6233
None
- UWP
None
Before
After
- run UItest 26233
=> [UWP] fixes ListView displays null values black

Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs, Xamarin.Forms.Xaml.UnitTests/BindingsCompiler.xaml, Xamarin.Forms.Xaml.UnitTests/BindingsCompiler.xaml.cs
This is a follow-up of commit 12f5b702ef4c8bcbd343b6272555ba9f01b36438.
None
None
None
Not applicable
Run automated tests.
=> [XamlC] Correctly load addresses of values in more compiled binding paths

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6323.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs, Xamarin.Forms.Platform.UAP/TabbedPageRenderer.cs
Fixes IndexOutOfRangeException when adding page after rendering the `TabbedPage`
- fixes #6323
None
- UWP
- UITest 6323
=> [UWP] Fixes IndexOutOfRangeException on TabbedPage

Xamarin.Forms.ControlGallery.iOS/CustomRenderers/CustomRenderer.cs, Xamarin.Forms.ControlGallery.iOS/CustomRenderers/RoundedLabelRenderer.cs, Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6368.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs, Xamarin.Forms.Platform.iOS/ViewRenderer.cs
By introducing some fixes in how we dispose the children renderers of pages renderes we started passing `Null`on SetElement so we can do some cleanup and detaching effects for example.
`SetNativeControl` is expected to be called when we have Element, for example a NewElement, but since we now pass Null and users don't take that in account in there code they end up creating a new NativeControl when we are disposing. 
Our users are using this [pattern](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/view) that is wrong:
```
protected override void OnElementChanged (ElementChangedEventArgs<NativeListView> e)
{
base.OnElementChanged (e);
if (Control == null) {
// Instantiate the native control and assign it to the Control property with
// the …
```
=> [iOS] Protect against SetNativeControl when no Element is present

Xamarin.Forms.Xaml.UnitTests/DesignTimeLoaderTests.cs, Xamarin.Forms.Xaml/XamlParser.cs
The `FallbackTypeResolver` hander in the Forms previewer does not have access to the `x:TypeArguments` attribute, so if it constructs a proxy generic type from metadata it can't construct it. So the previewer has to create an unconstructed generic type, and Forms will need to construct it.
So we need to move the code that constructs the generic type after the call to `FallbackTypeResolver`.
Part of the fix for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/917689
None
None
Not applicable
Testing requires previewer code that isn't yet merged.
=> Resolve fallback type before trying to make constructed generic type

Xamarin.Forms.Platform.Android/AppCompat/Platform.cs, Xamarin.Forms.Platform.Android/Platform.cs, Xamarin.Forms.Platform.Android/Renderers/FileImageSourceHandler.cs, Xamarin.Forms.Platform.Android/ResourceManager.cs
- PackageName was being retrieved from the non appcompat version of platform so it needed to be updated to use appcompat
- Changed the call to retrieve the bitmap for the fileimagehandler so that it passes in the Android Context
- fixes #6327 
- Android
This one is really weird to test. Your best option for testing is to pull down the repo on the included issues and test there.  The only way to recreate this issues is to:
- create an android library
- move the entire resource library from the head project to the library
- If the head project has even a single resource or drawable in it then the issue can't be recreated.
=> [Android] Retrieve PackageName from the correct Platform instance

Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Application.cs, Xamarin.Forms.Platform.iOS/Flags.cs, Xamarin.Forms.Platform.iOS/Forms.cs
https://github.com/xamarin/Xamarin.Forms/pull/5985
Changed the default behavior of named fontsizes for iOS to make it more in line with how Android and UWP work. This technically is a breaking change but we see it as an acceptable breaking change. That being said we still want to give users the ability to opt out of it if need be.
- iOS
- Create a page where font sizes are being set through named values (or just make one)
- Go to accessibility settings on the iDevice, set large text on, and make the text really large
- run the app
- now set this flag
```C#
Forms.SetFlags("DisableAccessibilityScalingForNamedFontSizes");
global::Xamarin.Forms.Forms.Init();
```
- Rerun the app and the font should now be smaller because it's no longer scaled
=> [iOS] adds a flag to ios if user needs to disable accessibility sizing for named font sizes

Xamarin.Forms.Controls/XamStore/Views/StorePages.cs, Xamarin.Forms.Core/Shell/Shell.cs, Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutTemplatedContentRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutContentRenderer.cs
Allow to set background image for flyout.
The current implementation gives choice how the image will be placed. 
- fixes #4410
Added:
- ImageSource Shell.FlyoutBackgroundImage { get; set; } //Bindable Property
- Aspect Shell.FlyoutBackgroundImageAspect  { get; set; } //Bindable Property
- iOS
- Android
Android http://recordit.co/pny7X2hPfk
iOS http://recordit.co/M8u34dMCE7
- switch to shell control panel
- click on `bg image`
=> [Shell] Allow to set background image for flyout item.

Xamarin.Forms.Platform.iOS/Renderers/FormsCheckBox.cs
Change the FormsCheckbox inheriting from UIBUtton to not use the UIButtonType base constructor which isn't recommended. If you use the UIButtonType base constructor it throws exceptions. This PR changes it to use the default constructor
- iOS
Bring up the CheckBox in the dynamic control gallery and play with the colors and various other settings to make sure it still all works correctly
=> [ios] change checkbox to use default constructor

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3150.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Controls/GalleryPages/DynamicViewGallery.cs, Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs, Xamarin.Forms.Platform.Android/ViewExtensions.cs
- fixes #3150
- fixes #6447 
None
- Android
Before
After
- run UItest 3150
- yellow square should't be clipped
=> [Android] Fixes work IsClippedToBounds on (Fast Renderer) Frame

Xamarin.Forms.Platform.WPF/CellControl.cs
The child layouts where not receiving any notification to re-layout.  This fix calls layout on the children view items.
Grid will now auto expand within a ViewCell
- [] Has automated tests (Visual Tested)
=> Fix for layouts in a cell to expand on resize (WPF) Issue #5682

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6077.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core.UITests.Shared/Tests/CollectionViewUITests.cs, Xamarin.Forms.Platform.iOS/CollectionView/GridViewLayout.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewRenderer.cs
These changes work around a UICollectionViewFlowLayout issue where horizontally-scrolling grid layouts do not display the last column if it is only partial. 
These changes also fix an issue where the CollectionView does not respect the Page's safe area settings on iOS 11+ (which had a side-effect of incorrectly laying out columns in landscape mode).
- fixes #6077
None
- iOS
None
Not applicable
Issue 6077 in Control Gallery (automated).
=> [iOS] Fix missing partial columns in horizontal grid layout

Xamarin.Forms.Platform.GTK/Renderers/NavigationPageRenderer.cs
Fix null reference exception
I think this hasn't been reported yet.
None
- GTK
None
Not applicable
Run `Gtk-BackgroundImage.GTK` from this minimal repro repository https://github.com/mfkl/gtk-repro
It gives
```
Xamarin.Forms.Platform.GTK.dll!Xamarin.Forms.Platform.GTK.Renderers.NavigationPageRenderer.UpdateBackgroundImage()	Unknown
Xamarin.Forms.Platform.GTK.dll!Xamarin.Forms.Platform.GTK.Renderers.NavigationPageRenderer.OnElementChanged(Xamarin.Forms.Platform.GTK.VisualElementChangedEventArgs e)	Unknown
Xamarin.Forms.Platform.GTK.dll!Xamarin.Forms.Platform.GTK.Renderers.AbstractPageRenderer<Gtk.Fixed, Xamarin.Forms.NavigationPage>.SetElement(Xamarin.Forms.VisualElement element)	Unknown
Xamarin.Forms.Platform.GTK.dll!Xamarin.Forms.Platform.GTK.Platform.CreateRenderer(Xamarin.Forms.VisualEl …
```
=> [GTK] Fix NullReferenceException in NavigationPageRenderer

Xamarin.Forms.Controls/CoreGalleryPages/CollectionViewCoreGalleryPage.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/DataTemplateGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/DefaultTextGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ItemSizeGalleries/ItemsSizeGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/PropagationGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ScrollToGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SnapPointsGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SpacingGalleries/ItemsSpacingGallery.cs, Xamarin.Forms.Core.Design/AttributeTableBuilder.cs, Xamarin.Forms.Core.Design/ItemsLayoutDesignTypeConverter.cs, Xamarin.Forms.Core.Design/Xamarin.Forms.Core.Design.csproj, Xamarin.Forms.Core/Items/IItemsLayout.cs, Xamarin.Forms.Core/Items/ItemsLayoutTypeConverter.cs, Xamarin.Forms.Core/Items/ItemsView.cs, Xamarin.Forms.Core/Items/ListItemsLayout.cs
CollectionView provides pre-allocated static instances of the unspaced horizontal and vertical list layouts, but to use them from XAML required doing something like 
```
<CollectionView ItemsLayout="{x:Static ListItemsLayout.HorizontalList}">
```
and the user was given no Intellisense for discoverability. 
These changes provide Intellisense for the basic list options.
None
Changed: 
`public static readonly IItemsLayout VerticalList` -> `public static readonly IItemsLayout Vertical`
`public static readonly IItemsLayout HorizontalList` -> `public static readonly IItemsLayout Horziontal`
Added:
`public class ItemsLayoutTypeConverter`
`public class ItemsLayoutDesignTypeConverter`
None
=> Intellisense for CollectionView basic list options

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6258.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6458.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Controls/ControlGalleryPages/AutomationPropertiesGallery.cs, Xamarin.Forms.Core.UITests.Shared/Tests/ToolbarItemTests.cs, Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs, Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs, Xamarin.Forms.Platform.Android/CellAdapter.cs, Xamarin.Forms.Platform.Android/Extensions/AccessibilityExtensions.cs, Xamarin.Forms.Platform.Android/FastRenderers/AutomationPropertiesProvider.cs, Xamarin.Forms.Platform.Android/Platform.cs, Xamarin.Forms.Platform.Android/ResourceManager.cs
- Images loaded from icons don't have a renderer to work from so needed to update the image loading code to work if no renderer is specified
- Fixed menuitem/toolbaritem to correctly set Automation Id using appcompat 
On Android the AutomationId for Toolbaritems will now set the ContentDescription which makes the UI tests fall more inline with iOS. 
- fixes #6258 
- Android
Run the included UI Test
=> [Android] Fix context actions icon so that it loads

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1905.cs
The screen shot for the 1939 test failure in app center has a picture of the test that runs during 1905 and the screen shot for 1905 is just a screen shot of the control gallery home page.
I added some waits to the 1905 test so that it waits for the test to actually load before screenshot is taken and then waits for it to finish before existing.
=> wait for test to finish so it doesn't break later tests

Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs
`ApplyPropertiesVisitor.SetTemplate()` creates a new `HydrationContext`, but it doesn't set the ExceptionHandler, so exceptions aren't caught in the previewer.
- fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/844877
None
None
Not applicable
Tested exception is correctly caught in previewer.
=> Set ExceptionHandler on HydrationContext in SetTemplate()

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3548.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs
Added *VisualElementRenderer* field as observer of Android Frame renderer (combination of gesture / effects listeners) instead of separate listeners (the same approach with Label's fast renderer.
- fixes https://github.com/xamarin/Xamarin.Forms/issues/3548
None
- Android
It's possible to adjust effects to frames
Not applicable
Described in original issue ticket. Please check: https://github.com/xamarin/Xamarin.Forms/issues/3548
=> [Android] Fixed applying effects to Frames

Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs
When resetting gallery it will occasionally take a bit more than 10 seconds to get back to the gallery home page before it can go to the nest test
=> wait a little bit longer for go to test button to appear

Xamarin.Forms.Platform.MacOS/Renderers/EntryRenderer.cs
`EntryRenderer.cs` for `macOS` is updated in this PR. Checks for if the current `NSWindow` is disposed where added before invoking the `FocusChanged` `EventHandler`. 
Since the renderer already had a member `_disposed`  i used this field for the checks. 
- fixes #4268
None
- macOS
None
Not applicable
I have tested the changes on macOS 10.14.5 by creating a new project adding an entry with `IsVisble=false `and displaying an Alert or ActionSheet after focusing the entry. The main window loses focus whenever an DisplayAlert or DisplayActionSheet ist called so this is a quick way to test it. It's also possible to repro the issue by clicking outside of the main window or switching windows with CMD + Tab while the Entry has focus and clicking back to the app window.
A project with a repro is …
=> EntryRenderer.cs [macOS] updated

Xamarin.Forms.Platform.Android/Renderers/ShellTabLayoutAppearanceTracker.cs
As reported in #6529 the renderer needed for this in Android is not accessible. Seeing that this class is public for iOS and all renderers seem to be public as well, I think this one should be too
- fixes #6529
None
- Android
None
Not applicable
=> Make Android ShellTabLayoutAppearanceTracker public

Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs
For designer purposes android uses a Mock web view (https://stackoverflow.com/a/31984038/953734) that doesn't have a 1:1 version of all the available properties
From the Android source
```
* Mock version of the WebView.
* Only non override public methods from the real WebView have been added in there.
* Methods that take an unknown class as parameter or as return object, have been removed for now.
```
>  * Methods that take an unknown class as parameter or as return object, have been removed for now.
Is the reason we are seeing crashes on No Method found "getSettings"
This is how we would fix this problem in the SDK but if the plan is to just handle it previewer side by using a box view then this change may not be needed.
=> [Android] don't setup webview if running as designer

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2577.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
When using the `FormsAppCompatActivity` the hamburger icon would not respond correctly to `NavigationPage.GetHasBackButton` leaving it to show nothing at all. With this change the hamburger icon will show when `NavigationPage.GetHasBackButton` is set to false.
- fixes #2577
None
- Android
None
Not applicable
=> [Android] Hamburger icon not shown when using FormsAppCompatActivity

Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs
The adapter was not dispose which was causing a leak with the item source.
- fixes #6427
None
- Android
None
Not applicable
Like all other garbage collection issue, it very difficult to produce a reliable reproduction.
I tried to make a reproduction case from the elements of the issue #6427 without success.
=> [Android] Dispose the collection view item adapter

Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
FIxes automation implementation for `ListViewRenderer`
- fixes #5340
None
- UWP
- run UItest B60699
- launch Narrator
- select any item in ListView
- app should't hang
=> [UWP] fixes hangs ListView when using Narrator

Xamarin.Forms.Platform.Android/CollectionView/ItemContentView.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewAdapter.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.Android/CollectionView/TemplatedItemViewHolder.cs
- implements part of #3172
None
- Android
None
Not applicable
Control Gallery, navigate to CollectionView Gallery ->Item Size Galleries ->ItemSizing Strategy
The initial selection is MeasureFirstItem; all of the items should have the same size. If you switch to MeasureAllItems, the items will have varying sizes.
=> Implement ItemSizingStrategy.MeasureFirstItem on Android

Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutTemplatedContentRenderer.cs, Xamarin.Forms.Platform.Android/ViewExtensions.cs
API 28 on Android appears to be a fan of setting the elevation to negative infinity and expects you to use 
float.minvalue
- Android
- Run shell on android api 28 and ensure 5132 is passing on all ui tests
- store shell also has some backgrounds you can interact with for the flyout if you want to test that it all still works to expectation
=> [Android] Change elevation to use float.minvalue instead of negative infinity

Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs, Xamarin.Forms.Xaml.UnitTests/BindingsCompiler.xaml, Xamarin.Forms.Xaml.UnitTests/BindingsCompiler.xaml.cs
Do not try to set a value to bound source property if unavailable and prevent `System.NullReferenceException`.
None
None
None
Not applicable
=> [XamlC] Do not try to set a value to bound source property if unavailable

Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
Unsubscribe from PropertyChanged during Dispose() on ItemsViewLayout (iOS).
Altered the behavior of ItemsViewLayout (iOS) to unsubscribe from the PropertyChanged event of the private _itemsLayout field. It didn't appear this event was unsubscribed from in the ItemsViewLayout.
- fixes #6582 
None
- iOS
None
Not applicable
=> Update ItemsViewLayout.cs to Unsubscribe from itemsLayout PropertyChanged event

Xamarin.Forms.Platform.iOS/ModalWrapper.cs, Xamarin.Forms.Platform.iOS/Platform.cs, Xamarin.Forms.Platform.iOS/PlatformRenderer.cs, Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
Native Forms gives the user a `PlatformRenderer` (as a `UIViewController`) to use for embedding a Forms `Page`. If the user wants to free the resources used by the embedded `Page`, there is currently no way to do so. Disposing of the controller itself is not sufficient, and the actual Platform object which needs to be disposed is inaccessible.
These changes arrange the cleanup so that calling `Dispose` on the returned `UIViewController` object will clean up all the necessary resources.
- fixes #4671
None
- iOS
None
Not applicable
=> [iOS] Clean up Platform on PlatformRenderer disposal

Xamarin.Forms.Platform.WPF/Deserializer.cs, Xamarin.Forms.Platform.WPF/Renderers/ImageRenderer.cs, Xamarin.Forms.Platform.WPF/Renderers/ListViewRenderer.cs, Xamarin.Forms.Platform.WPF/VisualElementTracker.cs, Xamarin.Forms.Platform.WPF/WPFDeviceInfo.cs
Fix these compiler warnings in the WPF platform project:
```
"C:\GitHub\Xamarin.Forms\Xamarin.Forms.Platform.WPF\Xamarin.Forms.Platform.WPF.csproj" (default target) (38:9) ->
Deserializer.cs(18,50): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [C:\GitHub\Xamarin.Forms\Xamarin.Forms.Platform.WPF\Xamarin.Forms.Platform.WPF.csproj]
Renderers\ImageRenderer.cs(148,55): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. …
```
=> Fix compiler warnings in WPF platform project

Xamarin.Forms.Core.UnitTests/ShellTests.cs, Xamarin.Forms.Core/Routing.cs
Checks if a route already exists, if so, it throws an exception.
- fixes #5996
None
None
Not applicable
=> [Shell] Fail when trying to add a duplicated route

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1733.cs
- for test Issue1733 it should be using WaitForElement instead of Query so that it actually waits for it to become visible.
- renamed test so that the name is immediately useful
=> Change Query to WaitForElement

Xamarin.Forms.Core.UITests.Shared/Remotes/BaseViewContainerRemote.cs
- For cases where we are testing changes to Scale, Rotation, etc. it looks like the value being read for testing is being read too early. These changes take readings until the value has settled to improve reliability. 
The ViewUITests still might fail occasionally for unrelated reasons that I think are mostly cleaned up with (https://github.com/xamarin/Xamarin.Forms/pull/6395)
If none of the failures are of the format
*Expected value: 9, Actual Value: 12*
Then we can merge this one in
=> [UITests] wait for animation to complete

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla31333.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1733.cs
Found issues on some tests when running on my local machine.
The test Bugzilla31333 dont wait the input to take focus (so on a fast machine it fail).
The test Issue1733 use the current culture to parse number which can fail (and indeed fail with my machine culture).
- Fix test Bugzilla31333
- Fix test Issue1733
None
- Android
None
Not applicable
- Run test Bugzilla31333
- Run test Issue1733
=> Fix some flaky tests.

Xamarin.Forms.Core/Visuals/VisualTypeConverter.cs
VisualTypeConverter throws a ReflectionTypeLoadException, when using Visual="Material". In my case, An assembly was referenced, that references System.Drawing.Common package.
No issues found.
None
None
Not applicable
None
=> [Bugfix] Catching ReflectionTypeLoadException in the VisualTypeConverter

Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
I have a need to intercept Editor keys on iOS and selectively ignore some like the Return key. The current implementation of `ShouldChangeText` is not open for runtime polymorphism. This change fixes that.
=> [iOS] Make ShouldChangeText virtual

Xamarin.Forms.Core.UnitTests/StyleTests.cs, Xamarin.Forms.Core/MergedStyle.cs
Checks if Style can be set on an element based on the type compatibility between Style TargetType and element's type. In case of type incompatibility, it throws an exception with type names:
```
Style TargetType Xamarin.Forms.Button is not compatible with element target type Xamarin.Forms.Label
```
Includes unit tests.
**This doesn't cover XAMLC.**
- fixes #6268
- fixes #6535
None
None
Not applicable
=> Validate style target at runtime

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6614.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/Element.cs, Xamarin.Forms.Core/TabIndexExtensions.cs
- the results of GetTabIndexesOnParentPage are used as the source of a collection so it needs to just return an empty dictionary instead of null
- Part of this comes up because reparenting an element in the wrong order can have some weird side effects. I've adding a warning to Element so if the element already has a parent it advises the developer to first remove it from that control before adding it to a new one. 
- fixes #6614
Added:
- Warning message if you try to set the parent on a element that is still a child of a different parent
- Android
Run the included test and follow the instructions
=> return empty dictionary instead of null

Xamarin.Forms.Controls/XamStore/Icons.cs, Xamarin.Forms.Controls/XamStore/StoreShell.xaml, Xamarin.Forms.Core/MenuItem.cs, Xamarin.Forms.Core/Shell/MenuShellItem.cs, Xamarin.Forms.Core/Shell/ShellItem.cs
- MenuItem was using FileImageSource and it doesn't work with font icons. I've changed to ImageSource, the same way it's used on ShellItem. 
- There was a missing binding on ShellItem, so I've added it as well.
- fixes #6559
None
None
Before:
After:
1. Run XamControl app
2. Tap "SwapRoot - Store Shell"
3. Check "Redeem" MenuItem's icon on Hamburger menu
=> [Shell] MenuItem font image fix

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6705.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/Device.cs
Don't return a `null` task from `InvokeOnMainThreadAsync`
- fixes https://github.com/xamarin/Xamarin.Forms/issues/6705
None
- Core
None
Not applicable
See issue
=> fix NRE in InvokeOnMainThreadAsync

Xamarin.Forms.Platform.Android/ButtonLayoutManager.cs
https://github.com/xamarin/Xamarin.Forms/pull/6329 added a ForceLayout call when calling GetDesiredSize.  This fixed the text layout issue but it now causes the button to not relayout if the WxH  has changed. So in a case where the button was going from not visible to visible and the height and width would go from zero to not zero then the force layout would just layout the control without redrawing it with the new width and height.
This PR calls ForceLayout only if the height and width haven't changed. If the height and width have changed then it calls RequestLayout if there's not a pending layout request. 
- Android
- ui test 53179 on various APIs with FR's enabled
- ui test Issue6282 on various APIs
- whatever other type of button layout you feel like testing
=> [Android] RequestLayout of button if measure has changed otherwise call force layout to ensure the content will layout correctly

build.cake, build.cmd
Replacement for https://github.com/xamarin/Xamarin.Forms/pull/6618. Same change, but targeting 4.0.0 branch instead of master.
Add `build.cmd` that launches `build.ps1` with the proper execution policy so that it doesn't insta-fail.
Fixes #6617 
None
N/A
None
Not applicable
Build on Windows.
=> Make building easier on Windows by setting PowerShell execution policy (attempt 2)

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3809.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4915.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4915.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5132.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5239.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellInsets.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs, Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs, Xamarin.Forms.Platform.iOS/Renderers/KeyboardInsetTracker.cs, Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellScrollViewTracker.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/TableViewRenderer.cs, Xamarin.Forms.Sandbox.Android/Xamarin.Forms.Sandbox.Android.csproj
- Fix iOS so the content pads correctly for: pages with top tabs, all pages not just scroll views
- Fixed the keyboard focus auto scroll so that when you click off the entry it'll scroll back correctly
- fixed safe area so that if you turn it off content will set to 0,0 (this also applies to page with top tabs)
- fixed safe area padding to include top tabs size as well
- consolidated all the safe area setting logic to a single method so it's easy to follow the logic of why we set it when
- fixes #5239
- fixes #6424
- fixes #6499
- iOS
- prior to this PR if the user set the padding, set safearea to true, then set the safearea to false it would reset the padding to zero. After this PR it'll set the padding back to whatever the user initially set it to
I added a ShellInsets test that has …
=> [ios] Shell inset,  general SafeArea fixes for shell and non shell embedded pages, entry scrolling fixes

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla30353.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla33578.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla42620.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla56896.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla59580.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1414.cs, Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs
- 1414 and 56896 are occasionally failing. This is most likely due to the use of Query opposed to just using WaitForElement 
- Renamed a few other tests that I had seen previous failures on
=> Rename some tests to better identify purpose and change query to WaitForElement

Xamarin.Forms.Platform.GTK/GtkToolbarTracker.cs, Xamarin.Forms.Platform.GTK/Renderers/NavigationPageRenderer.cs
Commit 491947606d03647124bffffcea8547e135869027
introduced this change :
* [GTK] Don't recreate the toolbar on each change
However when changing page, toolbar needs to be recreated.
See commit
- fixes #4409 
None
- GTK
Navigation bar is now visible when changing page.
Not applicable
Created a Xamarin Forms application with navigation and checked if toolbar is still here when changing page. Also checked by @VladislavAntonyuk
=> [GTK] Fix navigation

Xamarin.Forms.Core.UnitTests/ShellTests.cs, Xamarin.Forms.Core/Routing.cs
If you register the same factory or type then it shouldn't throw an exception. This is mainly a scenario that's coming up for the previewer which will rerun some code behind causing an exception about duplicate routes being registered.
- UI Tests Cover this
- run control gallery store shell make sure basic route registration still works
=> [Shell] don't throw exception if registering same route factory to same routename

Xamarin.Forms.Platform.UAP/FrameRenderer.cs
Fixed resetting the background color of the frame
None
- UWP
Before
After
- run `Dynamic ViewGallery`
- select any control
- set any color and reset it (switch off)
- application should't crash & color should be reseted
=> [UWP] Fixed resetting the background color of the frame

Xamarin.Forms.Core/Application.cs, Xamarin.Forms.Platform.iOS/PageExtensions.cs, Xamarin.Forms.Platform.iOS/Platform.cs
Unhook Page from embedded Application on disposal so the Page can be collected. 
This is a supplementary fix to #6636; that change allowed Pages which were not hooked to the current Application object to be collected, but did not allow the most recent Page associated with the Application to be collected. This change allows the most recent page to be collected.
- additional fix for #4671
Application.cs
Added:
`protected internal virtual void CleanUp();`
Modified: 
`public NavigationProxy NavigationProxy { get; }` => `public NavigationProxy NavigationProxy { get; private set; }`
- iOS
None
Not applicable
=> Unhook Page from embedded Application on disposal

Xamarin.Forms.Core.UnitTests/ShellLifeCycleTests.cs, Xamarin.Forms.Core.UnitTests/ShellTests.cs, Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj, Xamarin.Forms.Core/Shell/BaseShellItem.cs, Xamarin.Forms.Core/Shell/Shell.cs, Xamarin.Forms.Core/Shell/ShellContent.cs, Xamarin.Forms.Core/Shell/ShellExtensions.cs, Xamarin.Forms.Core/Shell/ShellItem.cs, Xamarin.Forms.Core/Shell/ShellSection.cs, Xamarin.Forms.Platform.Android/Renderers/ShellSectionRenderer.cs
Currently Appearing only looks to fire for a ContentPage defined as Content but not for any tabs or being pushed
- Add appearing/disappearing events/methods to ShellBaseItem
- propagate these changes to the visible page
- Set these events up when pushing and popping things modally
- Appearing/Disappearing are called from the cross platform code (not the platform code) which means they will fire consistently and before the platform code has made the page visible. 
- Pushing a Modal page will cause all currently visible shell parts to fire Disappearing
- popping the last modal will cause all currently visible shell parts to fire Appearing
- Pushing a page will cause the shellcontent and it's page content to fire disappearing but shellitem and shellsection will still be in "appeared"
- …
=> Shell lifecycle

Xamarin.Forms.Core.UnitTests/ShellTestBase.cs, Xamarin.Forms.Core.UnitTests/ShellTests.cs, Xamarin.Forms.Core/Shell/Shell.cs, Xamarin.Forms.Core/Shell/ShellItem.cs, Xamarin.Forms.Core/Shell/ShellSection.cs
- The code that applies query string parameters wouldn't execute if the user didn't supply any query string parameters. But it should still set whatever parameters the user has to null if no Query String Parameters are specified. 
- Nested content pages are parented to ShellSection not ShellContent so the code that applied query parameters to them wasn't correct. The only reason it worked during the first navigation was a fluke because the Parent hadn't been set yet on the content page
- fixes #6543 
- iOS
- Android
- UI tests cover the scenarios to test
=> [Shell] Apply Query string parameters even if they aren't present and correctly apply them to nested pages

Xamarin.Forms.Platform.UAP/FormsButton.cs
Fixes application crash when resetting `CornerRadius`
None
None
- UWP
None
Not applicable
- ControlGallery
- Dynamic ViewGallery
- Button
- set CornerRadius
- reset CorerRadius
- application should't crashes
=> [UWP] fixes crash after reset corner radius

Xamarin.Forms.Controls/GalleryPages/MapGallery.xaml, Xamarin.Forms.Controls/GalleryPages/MapGallery.xaml.cs, Xamarin.Forms.Maps.Android/MapRenderer.cs, Xamarin.Forms.Maps.iOS/MapRenderer.cs, Xamarin.Forms.Maps/Map.cs
As described in #6222 on iOS and Android, the Map renderer moves map center to last region when device is rotated. Looking at the renderers implementation, it actually moves to the last region on a layout change.
I added a new boolean property which when it's true, it doesn't move to the last region when layout changes.
- fixes #6222
Added:
- bool Map.MoveToLastRegionOnLayoutChange { get; set; } //Bindable Property (default is **true**)
- iOS
- Android
None
Not applicable
See Map Gallery Page. I added a button which toggles the MoveToLastRegionOnLayoutChange property:
IMPORTANT: **Note that you need the fix from #6603 to run it on Android**
=> Map MoveToLastRegionOnLayoutChange Property

Xamarin.Forms.Controls/CoreGalleryPages/SwitchCoreGalleryPage.cs, Xamarin.Forms.Core/Properties/AssemblyInfo.cs, Xamarin.Forms.Core/Switch.cs, Xamarin.Forms.CustomAttributes/TestAttributes.cs, Xamarin.Forms.Platform.Android/AppCompat/SwitchRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/SwitchRenderer.cs, Xamarin.Forms.Platform.UAP/SwitchRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/SwitchRenderer.cs
Adds ThumbColor property to Switch
- fixes #5415
- iOS
- Android
- UWP
See Switch gallery page
=> Switch ThumbColor

Xamarin.Forms.Core.UnitTests/ShellTests.cs, Xamarin.Forms.Core/Shell/ShellSection.cs
Inherited `OnBindingContextChanged` for `ShellSection` and propagate `BindingContext` to `ShellContents`.
- fixes #6444 
None
None
Not applicable
Check #6444.
=> Fix for #6444: Propagate binding context for children of shell sections

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellInsets.cs, Xamarin.Forms.Core.UnitTests/ShellTestBase.cs, Xamarin.Forms.Core/Shell/Shell.cs, Xamarin.Forms.Platform.Android/AppCompat/SwitchRenderer.cs, Xamarin.Forms.Platform.Android/Extensions/DrawableExtensions.cs, Xamarin.Forms.Platform.Android/Renderers/SliderRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/SwitchRenderer.cs, Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
- Since we throw an exception now if you register the same route twice we need to clear the global routes in the teardown of the unit tests
- Global Routes were moved to only be processed if the ShellContent was specified as part of the uri but they should just be processed regardless
- UI tests cover
=> Clear global routes on unit tests and process global routes in the right place

Xamarin.Forms.Build.Tasks/ExpandMarkupsVisitor.cs, Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs, Xamarin.Forms.Xaml.UnitTests/Issues/Gh6648.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh6648.xaml.cs
- fixes #6648
None
None
Not applicable
=> [X] Allow x:Null for x:DataType

Xamarin.Forms.Material.Android/MaterialDatePickerRenderer.cs, Xamarin.Forms.Material.Android/MaterialEditorRenderer.cs, Xamarin.Forms.Material.Android/MaterialEntryRenderer.cs, Xamarin.Forms.Material.Android/MaterialPickerRenderer.cs, Xamarin.Forms.Material.Android/MaterialTimePickerRenderer.cs
Reimplement `ITabStop` on Android Material renderers to return the `EditText` instead of the `TextInputLayout`.
- fixes #5102
Changed: 
Reimplemented `ITabStop` on the following renderers to return `EditText` instead of `Control`:
- MaterialDatePickerRenderer
- MaterialEditorRenderer
- MaterialEntryRenderer
- MaterialPickerRenderer
- MaterialTimePickerRenderer
- Android
Users will be able to correctly tab to/between TextInputLayout-based material controls.
Not applicable
Use the Entry Material Demos page in the Control Gallery to tab between entries.
=> Reimplement ITabStop on Android Material renderers

Xamarin.Forms.Controls/CoreGalleryPages/SwitchCoreGalleryPage.cs, Xamarin.Forms.Platform.Android/AppCompat/SwitchRenderer.cs, Xamarin.Forms.Platform.Android/Extensions/DrawableExtensions.cs, Xamarin.Forms.Platform.Android/Renderers/SliderRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/SwitchRenderer.cs
After #6312 Switch lost shadow on Android, see Shane's comment
fixes #5415
None
- Android
=> Fix for Switch on Android losing shadow

Xamarin.Forms.Controls/CoreGalleryPages/ImageButtonCoreGalleryPage.cs, Xamarin.Forms.CustomAttributes/TestAttributes.cs, Xamarin.Forms.Platform.WPF/Renderers/ButtonRenderer.cs, Xamarin.Forms.Platform.WPF/Renderers/ImageButtonRenderer.cs
See title, nothing more, nothing less.
No additional tests included since existing tests should cover it.
- fixes #6790
None
- WPF
For the default value, nothing changes, but the user is now able to specify and see a padding on a Button for WPF
Before:
After:
=> Implemented Padding on WPF Button

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6738.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/Renderers/ShellItemRendererBase.cs, Xamarin.Forms.Platform.iOS/Platform.cs, Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootRenderer.cs
If you have a tabbed page where one of the tabs has pages pushed to it due to `GoToAsync`, then leaving the tabbed page via the flyout and then returning to that tab will cause a crash. This change resolves the crash and instead allows you to return to that tab in the state that is expected.
- fixes #6738 
- Android
=> [Android] Fix KeyNotFoundException during Shell Navigation

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6609.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/SelectionChangedCommandParameter.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/SelectionChangedCommandParameter.xaml.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/SelectionGallery.cs, Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj, Xamarin.Forms.Core.UnitTests/BindingBaseUnitTests.cs, Xamarin.Forms.Core.UnitTests/MockPlatformServices.cs, Xamarin.Forms.Core/BindingExpression.cs
Binding expression applications are always marshaled to the UI thread using `Device.BeginInvokeOnMainThread()`, without checking to see if they are _already_ executing on the main thread. Aside the slight overhead of `Device.BeginInvokeOnMainThread()`, this is normally not a problem. However, in cases where the property changed handler of the binding is using the information from the updated binding, forcing all of the expressions to queue up causes values to be out of date. 
For example, if the property change causes a command to fire, and the command's parameter is bound to the changed property, forcing the changes to queue means that the parameter's bound value will be out of date when the command executes. 
These changes add a check to determine if the expression is being applied on …
=> Don't force binding expression applications to queue

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6713.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/Page.cs, Xamarin.Forms.Core/PromptArguments.cs, Xamarin.Forms.Platform.Android/PopupManager.cs, Xamarin.Forms.Platform.iOS/Platform.cs
See #6713 for more explanation. This only implements iOS and Android.
- fixes #6713
Added:
- `Task<string> DisplayPromptAsync(string title, string message, string accept, string cancel, string placeholder = null, int? maxLength = null, Keyboard keyboard = default)`
- `PromptArguments(string title, string message, string accept = "OK", string cancel = "Cancel", string placeholder = null, int? maxLength = null, Keyboard keyboard = default)`
- iOS
- Android
=> [Core] Add ability to show modal prompts

Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs, Xamarin.Forms.Xaml.UnitTests/Issues/Gh5240.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh5240.xaml.cs
binding passed as properties don't have a valid datatype, so do not compile those.
- fixes #5240
None
None
Not applicable
=> [X] do not compile binding set as property values

Xamarin.Forms.Core/BindingExpression.cs, Xamarin.Forms.Xaml.UnitTests/Issues/Issue6280.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Issue6280.xaml.cs
Fixes binding to nullable types. 
- fixes #6280
None
None
Not applicable
=> Fix binding to nullable types

Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs, Xamarin.Forms.Xaml.UnitTests/Issues/Gh5330.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh5330.xaml.cs
see discussion on #6492 and related issues
None
None
Not applicable
=> [X] allow x:Type markup as x:DataType value

Xamarin.Forms.Material.iOS/MaterialFormsCheckBox.cs
Fixes rendering mode of the image in material checkbox.
- fixes #6816
None
- iOS
- Control Gallery
- Dynamic ViewGallery with Material visual
- select Checkbox
- try to change Color
=> [iOS] fixes material checkbox color

Xamarin.Forms.Platform.iOS/CollectionView/GridViewLayout.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.iOS/CollectionView/ListViewLayout.cs
The iOS CollectionView layouts should receive the ItemSizeStrategy on the constructor, this is because some methods can be called by the UICollectionView platform and the ItemSizingStrategy was not set yet.
- helps with #5044 
None
- iOS
- Android
- UWP
None
Not applicable
=> [iOS] ItemsViewLayout needs strategy on the ctor

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6286.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs
Unhook WebView.EvaluateJavascriptAsync on Dispose to prevent any crashes.
- fixes #6286 (hopefully--I was unable to reproduce it)
None
- Android
None
Not applicable
Added test case 6286, but it does not exhibit the crash. Will need confirmation from @kwaclaw that this resolves the issue.
=>  [Android] Unhook WebView.EvaluateJavascriptAsync on Dispose

Xamarin.Forms.Core.UnitTests/DeviceUnitTests.cs, Xamarin.Forms.Core.UnitTests/ViewUnitTests.cs, Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj, Xamarin.Forms.Core/Device.cs
Stumbled on https://github.com/xamarin/Xamarin.Forms/pull/5028 as I was considering submitting an equivalent PR myself, and happened to notice a bug: `InvokeOnMainThreadAsync(Func<Task>)` doesn't `await`. I had originally just fixed the bug (note commit timestamps), but figured I might as well practice writing async tests.
**Update:** Apparently this was reported as #6705 and the fix in #6708 was merged an hour ago. Maybe the rest is still useful?
Also:
- Accepted VS suggestion to use local functions (microoptimization)
- Gave `dummyFunc` more useful names
- ~~Renamed `func`/`funcTask` to `function`, in alignment with `Task.Run(...)` overloads~~
- Not sure if you consider renaming public arguments an API change? (It is.)
Changed:
- ~~Names of some public arguments from `func`/`funcTask` …
=> [Core] Missing await in Device.InvokeOnMainThreadAsync(Func<Task>)

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewItemsUpdatingScrollMode.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CollectionViewGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EnumSelector.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ScrollModeGalleries/ScrollModeGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ScrollModeGalleries/ScrollModeTestGallery.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ScrollModeGalleries/ScrollModeTestGallery.xaml.cs, Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj, Xamarin.Forms.Core/Items/ItemsUpdatingScrollMode.cs, Xamarin.Forms.Core/Items/ItemsView.cs, Xamarin.Forms.Platform.Android/CollectionView/DataChangeObserver.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.Android/CollectionView/ScrollHelper.cs, Xamarin.Forms.Platform.iOS/CollectionView/IndexPathExtensions.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
Add `ItemsUpdatingScrollMode` to the CollectionView control. Includes implementations for Android and iOS, plus automated tests for the feature.
(This is a replacement for #6172, which was too much of a nightmare to rebase again.)
- implements part of #3172
Added:
```
public enum ItemsUpdatingScrollMode
{
KeepItemsInView,
KeepScrollOffset,
KeepLastItemInView
}
```
`BindableProperty ItemsView.ItemsUpdatingScrollMode`
- iOS
- Android
None
Not applicable
Automated tests in CollectionViewItemsUpdatingScrollMode.cs
=> Implement CollectionView.ItemsUpdatingScrollMode for Android/iOS

Xamarin.Forms.Platform.MacOS/Renderers/ImageRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ImageElementManager.cs
Similar to iOS fix: https://github.com/xamarin/Xamarin.Forms/pull/6153
Same sample applies: https://github.com/daniel-luberda/XF-PR6153
Background: Third party libs can now be used with `Image` view (after registering `IImageSourceHandler`)
This change won't affect standard image loading. It'll allow third party libs like FFImageLoading to display animated images correctly.
None
- MacOS
=> MacOS: Allow third party libs to display animated images correctly

Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
This change prevent race condition on MainPage change between the old activity OnDestroy and new activity OnCreated.
This case only appear when using a static application, often true when using an IoC container for resolve App object.
I fixed some cases that cause crash in #4707 :
- Missing App PropertyChanged handler unsubscribe
- Wrong dispose place
- Prevent the dispose if it the same page
- Prevent PropertyChanged to be called if the activity is in pause or to be destroyed
It drastically reduced the number of crash but didn't fix it completely.
So I have an edge case of an edge case to fix.
This [post](https://medium.com/androiddevelopers/the-android-lifecycle-cheat-sheet-part-ii-multiple-activities-a411fd139f24) here put me on the right path, it seemed possible that the destroy and …
=> [Android] Prevent race condition between activity create and dispose

EmbeddingTestBeds/Embedding.XF/OpenUri.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla29247.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60691.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2357.xaml.cs, Xamarin.Forms.Core/Device.cs
see #6623 
also fix identation to use tabs
None
None
Not applicable
=> [C] Obsolete Device.OpenUri

Xamarin.Forms.Platform.Android/Renderers/SearchBarRenderer.cs
- fixes #4108
None
- Android
After
Create a Xamarin Forms project
Add `SearchBar` to a Xamarin Forms Page
Try to use the Previewer
> VS bug [#950410](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/950410)
=> [Android] Fix previewer exceptions with SearchBar

Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
As described in #6847, the called API is only available from iOS 9+. While support is expiring for this version in Xamarin.Forms, this was an easy fix to keep it going just a little bit longer.
- fixes #6847
None
- iOS
None
Not applicable
=> [iOS] Wrap iOS 9+ code in version check (get_InputAssistantItem: unrecognized selector sent…)

Xamarin.Forms.Platform.iOS/IOSDeviceInfo.cs
In #5975 code was implemented to take into account the orientation changes on iOS. This code caused the initialisation of the `Device.Info.ScaledScreenSize` (and probably others) to be delayed. To make sure values are filled immediately, I’ve added the update method to the ctor.
Because of timing and app lifecycle (near) impossible to add automated tests.
- fixes #6799
- fixes #6834
- fixes #6645
None
- iOS
None
Not applicable
=> [Bug] Device.Info.ScaledScreenSize Gives 0 Width and Height in iOS

Xamarin.Forms.Platform.Android/AppCompat/Platform.cs, Xamarin.Forms.Platform.Android/Renderers/PageRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/ScrollViewContainer.cs
When the previewer unloads the app process it calls dispose on every single Java.Lang.Object in memory. Meaning dispose will be called on children elements multiple times. We've occasionally been seeing an exception in the dispose call on ScrollViewContainer because dispose will be called directly on ScrollViewContainer and it will be called by the ScrollViewRenderer. If the timing is just wrong it'll throw an exception from ScrollViewContainer since the dispose happens twice
- Android
- Open a forms page with a scrollview, close it, open it, and then close it. Do that a few times and just makes sure it all works
- Run an android app with a page that has a scrollview. Pop the page off the stack and just make sure the dispose calls fro scrollview and scrollviewcontainer seem to work
=> [Android] Add check for multiple dispose calls on scrollview, page,  and platform

Xamarin.Forms.Platform.MacOS/NativeToolbarTracker.cs
Made title centered.
- fixes #5575
None
macOs
macOS title became centered 
Check "before" screenshot in original issue ticket please
Now:
Run macOS samples and check title's behavior
P.S. @davidortinau *challenge* https://twitter.com/Andrik_Just4Fun/status/1154482058229624832
=> In macOS Mojave, navigation bar title text is not centered

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6945.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/VisualElementTracker.cs
At the beginning of a transform cycle the transform on the iOS CALayer would get reset to 0 but it wasn't resetting the anchor. This was causing the Identity transform to layout the view relative to whatever the anchor was changed to. This PR resets the anchor back to default when it starts the transform pass.
- fixes #6945 
- fixes #5610
- iOS
- UI test included
- Test additional transformations like scale and rotate to make sure they still all work
=>  [iOS] Reset anchor point before reapplying transforms

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GitHub6926.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/Renderers/PageContainer.cs
This is #6927 by @beeradmoore rebased on 4.1.0
- fixes #6926
None
- iOS
None
Not applicable
1. To replicate the bug you will first need to disable the [fix which was committed with this PR](https://github.com/beeradmoore/Xamarin.Forms/commit/db67a0c8582a84b7606f89be32459ea5b5638183).
2. Enable VoiceOver on your device. (as far as I know this cant be enabled on the simulator)
3. Launch Xamarin.Forms.Controls.Issues project on iOS device
4. Go into Test Cases.
5. Launch G6926.
6. As stated on the buttons, clicking the first will crash the app, clicking the second will proceed as normal.
=> iOS - Test and fix for VoiceOver crash on a ContentPage not having any Content defined

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6644.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6644.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.Android/CollectionView/SelectableItemsViewRenderer.cs
On Android, there's some issues with how the `ItemsViewRenderer.UpdateAdapter()` works:
1. It just resets to the `ItemsViewAdapter` instance but without taking into account if the empty view adapter is the current adapter.
2. `SelectableItemsViewRenderer` overrides `UpdateAdapter()` and it suffers from issue #1 too 
3. `SelectableItemsViewRenderer` overrides `UpdateAdapter()` it doesn't dispose the previous `ItemsViewAdapter` instance how the base class `ItemsViewRenderer` does in `UpdateAdapter()`
There's also an issue with how `ItemsViewRenderer.UpdateEmptyViewVisibility()` works.
I think it shouldn't reset the adapter and the layout manager without checking what's the current adapter, otherwise it creates issues, one is #6644
- fixes #6644 (it resets the adapter and the layout manager …
=> CollectionView Android - Fix adapter update

Xamarin.Forms.Core/ResourceDictionary.cs, Xamarin.Forms.Xaml/Diagnostics/ResourceDictionaryDiagnostics.cs, Xamarin.Forms.Xaml/Diagnostics/StaticResourceResolvedEventArgs.cs, Xamarin.Forms.Xaml/MarkupExtensions/StaticResourceExtension.cs, Xamarin.Forms.Xaml/Properties/AssemblyInfo.cs, Xamarin.Forms.Xaml/Xamarin.Forms.Xaml.csproj
This allows advanced tracking of SR for debugging purposes. It doesn't affects
apps running without the debugger.
See also https://docs.microsoft.com/en-us/dotnet/api/system.windows.diagnostics.resourcedictionarydiagnostics
/
None
None
Not applicable
=> [X] Allow tracking the assignment of StaticResource

Xamarin.Forms.Platform.UAP/ButtonRenderer.cs, Xamarin.Forms.Platform.UAP/ImageButtonRenderer.cs
By default button loading with no empty padding. Therefore empty padding must be set to the native control.
- fixes #6450
None
- UWP
Before
After
- run Button Layout Gallery
- check button padding
=> [UWP] Fixes default button padding

Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5503.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/Cells/CellRenderer.cs
As described in #5503 the color set in the Appearance API was not respected. Fixed this by adding a check for that in the code of #4002 that caused this behavior.
I added a UI test but could not get the color out of the `ListView` they always returned the same value. Marked it as manual review.
- fixes #5503
None
- iOS
None
Not applicable
=> [iOS] UITableView.Appearance.BackgroundColor ignored or overridden for ListView

Xamarin.Forms.Controls/GalleryPages/CharacterSpacingGallery.xaml, Xamarin.Forms.Controls/GalleryPages/CharacterSpacingGallery.xaml.cs, Xamarin.Forms.Material.iOS/MaterialButtonRenderer.cs, Xamarin.Forms.Material.iOS/MaterialDatePickerRenderer.cs, Xamarin.Forms.Material.iOS/MaterialEditorRenderer.cs, Xamarin.Forms.Material.iOS/MaterialPickerRenderer.cs, Xamarin.Forms.Material.iOS/MaterialTimePickerRenderer.cs, Xamarin.Forms.Platform.iOS/Extensions/Extensions.cs, Xamarin.Forms.Platform.iOS/Renderers/ButtonLayoutManager.cs, Xamarin.Forms.Platform.iOS/Renderers/ButtonRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/DatePickerRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/TimePickerRenderer.cs
PR #5167 introduced a bug with iOS button text where it was setting a `AttributtedTitle`  and the `ButtonLayoutManager.cs ` was setting just the control `Title` when the text was changed.
- iOS
When changing the Text button it should work, you should see the new text
There are several tests on ControlGallery that should pass with this fix, iOS should be green.
Can tests for example with test case  `Bugzilla46458` after clicking the button it should read `Clicked`.
=> [iOS] Fix usage conflict of Title and AttributedTitle on ButtonRenderer

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewHeaderFooterString.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewHeaderFooterTemplate.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewHeaderFooterView.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CollectionViewGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterGrid.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterGrid.xaml.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterString.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterString.xaml.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterTemplate.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterTemplate.xaml.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterView.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterView.xaml.cs, Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj, Xamarin.Forms.Core/Items/ItemsView.cs, Xamarin.Forms.Platform.Android/CollectionView/EmptyViewAdapter.cs, Xamarin.Forms.Platform.Android/CollectionView/GridLayoutSpanSizeLookup.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemContentView.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemViewType.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewAdapter.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.Android/CollectionView/SimpleViewHolder.cs, Xamarin.Forms.Platform.Android/CollectionView/SpacingItemDecoration.cs, Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Implement header/footer for CollectionView on Android.
Note: This only implements static header/footer - this does not include sticky headers.
- implements part of #3172
Added to ItemsView:
```
public static readonly BindableProperty HeaderProperty = BindableProperty.Create(nameof(Header), typeof(object), typeof(ItemsView), null);
public static readonly BindableProperty HeaderTemplateProperty = BindableProperty.Create(nameof(HeaderTemplate), typeof(DataTemplate), typeof(ItemsView), null);
public static readonly BindableProperty FooterProperty = BindableProperty.Create(nameof(Footer), typeof(object), typeof(ItemsView), null);
public static readonly BindableProperty FooterTemplateProperty = BindableProperty.Create(nameof(FooterTemplate), typeof(DataTemplate), typeof(ItemsView), null);
```
- …
=> [Android] CollectionView Header/Footer

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6286.cs
Test is occasionally throwing the following exception
```
System.InvalidOperationException: Page must not already have a parent.
at Xamarin.Forms.Internals.NavigationProxy.PushAsync (Xamarin.Forms.Page root, System.Boolean animated) [0x0000e] in /Users/vsts/agent/2.154.3/work/1/s/Xamarin.Forms.Core/NavigationProxy.cs:116 
at Xamarin.Forms.Internals.NavigationProxy.PushAsync (Xamarin.Forms.Page root) [0x00001] in /Users/vsts/agent/2.154.3/work/1/s/Xamarin.Forms.Core/NavigationProxy.cs:110 
at Xamarin.Forms.Controls.Issues.Issue6286+<>c__DisplayClass2_0.<Init>b__0 () [0x0001c] in /Users/vsts/agent/2.154.3/work/1/s/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6286.cs:37 
at Xamarin.Forms.Forms+IOSPlatformServices+<>c__DisplayClass15_0.<StartTimer>b__0 …
```
=> Modify UI Test 6286 to await push and pop

Xamarin.Forms.Platform.iOS/CollectionView/UICollectionViewDelegator.cs
When you would “bounce” the CollectionView (actually ItemsView) on iOS, the cell going offscreen was marked for removal by iOS and therefor we removed the bindingcontext, etc.
This change prevents that from happening because this would leave us with unwanted empty cells.
Was not reported in an issue yet afaik. #6988 looks somewhat related but has a different cause since bouncing does not happen on Android.
~It might be the fix to #6341, from the movie it looks like this problem.~ Verified it’s not.
None
- iOS
None
Not applicable
=> [iOS] Prevent empty cell on bounce CollectionView

Directory.Build.props, Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj, Stubs/Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS (Forwarders).csproj, Xamarin.Forms.ControlGallery.MacOS/Xamarin.Forms.ControlGallery.MacOS.csproj, Xamarin.Forms.Core.Design/Xamarin.Forms.Core.Design.csproj, Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj, Xamarin.Forms.Core/Xamarin.Forms.Core.csproj, Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj, Xamarin.Forms.Maps.GTK/Xamarin.Forms.Maps.GTK.csproj, Xamarin.Forms.Maps.MacOS/Xamarin.Forms.Maps.macOS.csproj, Xamarin.Forms.Maps.UWP/Xamarin.Forms.Maps.UWP.csproj, Xamarin.Forms.Maps.WPF/Xamarin.Forms.Maps.WPF.csproj, Xamarin.Forms.Maps.iOS/Xamarin.Forms.Maps.iOS.csproj, Xamarin.Forms.Maps/Xamarin.Forms.Maps.csproj, Xamarin.Forms.Material.Android/Xamarin.Forms.Material.Android.csproj, Xamarin.Forms.Material.iOS/Xamarin.Forms.Material.iOS.csproj, Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj, Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj, Xamarin.Forms.Platform.GTK/Xamarin.Forms.Platform.GTK.csproj, Xamarin.Forms.Platform.MacOS/Xamarin.Forms.Platform.macOS.csproj, Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj, Xamarin.Forms.Platform.WPF/Xamarin.Forms.Platform.WPF.csproj, Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj, Xamarin.Forms.Xaml.Design/Xamarin.Forms.Xaml.Design.csproj
Adds SourceLink support to Xamarin.Forms packages
Will work for:
- iOS and Android in VSMac (should be implemented in 8.3)
- UWP, WPF in VS2019, mono debugger support coming
What changed:
- Added some entries in the `Build.props` file to enable SourceLink and link it with out Github repo.
- Removed all `DebugType` tags from the relevant `csproj` files and moved them to the `Build.props` file and changed the debug type to `portable` in the process.
More info: https://github.com/dotnet/sourcelink
- fixes #2165
None
N/A
None
Not applicable
If you have a copy of VSMac which has SourceLink support already enabled, just debug your app as you normally would but notice how you can step into the Xamarin.Forms source code
=> Enable SourceLink for Xamarin.Forms

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CollectionViewGallery.cs, Xamarin.Forms.Controls/GalleryPages/GalleryBuilder.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemContentView.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewAdapter.cs, Xamarin.Forms.Platform.Android/CollectionView/TemplatedItemViewHolder.cs
Replaces use of Android.Util.Size (not available until API 21) with Xamarin.Forms.Size to avoid missing class definition crashes on API < 21.
Also fixes transposed parameters when using ItemSizingStrategy.MeasureFirstItem.
- fixes #6815
None
- Android
None
Not applicable
Launch Control Gallery on API 19, navigate to
CollectionView Gallery -> Item Sizing Gallery -> Item Sizing Strategies. Should no longer crash.
=> Use XF Size instead of Android.Util.Size

Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
Moved the `OnSelectionChanged` call to be included in the `UpdateSelectionMode`.
- fixes #1356
None
- UWP
None
Not applicable
=> [UWP] The SelectedItem in a ListView is not highlighted when set while constructing a page

Xamarin.Forms.Platform.Android/AppCompat/ImageButtonRenderer.cs, Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs, Xamarin.Forms.Platform.Android/BorderBackgroundManager.cs, Xamarin.Forms.Platform.Android/Cells/BaseCellView.cs, Xamarin.Forms.Platform.Android/Cells/SwitchCellRenderer.cs, Xamarin.Forms.Platform.Android/Extensions/FlowDirectionExtensions.cs, Xamarin.Forms.Platform.Android/Extensions/ScrollViewExtensions.cs, Xamarin.Forms.Platform.Android/Forms.cs, Xamarin.Forms.Platform.Android/Platform.cs, Xamarin.Forms.Platform.Android/Renderers/CircularProgress.cs, Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/PageRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/ProgressBarRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/SearchBarRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/SliderRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/SwitchRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/TimePickerRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs, Xamarin.Forms.Platform.Android/ViewExtensions.cs, Xamarin.Forms.Platform.Android/VisualElementTracker.cs
Change `Build.VERSION` to `Forms.SdkInt`. The latter will cache the result of `Build.VERSION` which saves us an interop call which improves startup performance. 
```
internal static BuildVersionCodes SdkInt {
get {
if (!s_sdkInt.HasValue)
s_sdkInt = Build.VERSION.SdkInt;
return (BuildVersionCodes)s_sdkInt;
}
}
```
None
- Android
None
Not applicable
=> Cache Droid SDK ver

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/PropagateCodeGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/PropagationGallery.cs, Xamarin.Forms.Core/Items/ItemsView.cs, Xamarin.Forms.Platform.Android/CollectionView/EmptyViewAdapter.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.Android/CollectionView/SimpleViewHolder.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Currently, if the EmptyView for a CollectionView is a simple Forms View (as opposed to one which uses a DataTemplate), propagated values like FlowDirection are not actually propagated. These changes fix that issue.
None
None
- iOS
- Android
None
Not applicable
In Control Gallery, navigate to CollectionView Gallery -> Propagation Galleries -> Propagate FlowDirection in EmptyView and follow the on-screen instructions.
=> Ensure FlowDirection propagates to EmptyView when not using a template

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla45125.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/PerformanceGallery/PerformanceDataManager.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/PerformanceGallery/PerformanceGallery.cs
- 45125 is currently using Query()[0] which will fail sometimes because of timing issues. Changed this to a WaitForElement so that it Waits for it to show up
- The Performance Gallery has been occasionally crashing from the HttpClient call throwing a TaskCancelException so I changed it to use await/async and wrapped the call in a try/catch
=> [UITest] Change Query to WaitForElement on 45125 and change GetResult to await for Performance Gallery testing

Xamarin.Forms.Platform.Tizen/Renderers/ListViewRenderer.cs
This PR is to fix the ListView Header and Footer disappear issue.
Issue
When the contents of the ListView.Header are updated, they disappear.
Fix
Added header and footer check when update source.
- Tizen
=> [Tizen] Update ListViewRenderer for header and footer

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellGestures.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/AppCompat/FormsViewPager.cs, Xamarin.Forms.Platform.Android/Renderers/ShellSectionRenderer.cs
Disable the ViewPager on Shell from intercepting touches. Shell doesn't use swipe based paging. We also do this on the TabbedPageRenderer.
This PR does not fix scrolling on webview and maps.
- fixes #6310 
- fixes #6060
- Android
- There's a UI test
- Test some gestures with shell that you might think are still broken
=> Disable Touch Intercepting on Android View Pager

Xamarin.Forms.Platform.Android/PickerManager.cs
IMO the check that detects which buttons should trigger the picker to open was inverted causing the volume buttons (among others) to open the picker wrongfully.
Since this is tied to actually pressing a physical button automated tests are absent.
- fixes #5960
None
- Android
Picker is only opened with the buttons defined in the `PickerManager.cs` file
Not applicable
Go to the Gallery app Picker section on a physical device, focus a Picker control and press the volume up and down buttons.
=> [Xamarin.Forms][Android] Pressing Volume up/down hardware buttons on pickers opens them

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/InputTransparentTests.cs
The stepper is currently setup to click on the top left corner of the buttons but it looks like occasionally this is off just enough that it clicks on the layout and not the button. This PR grabs the actual button from the stepper on Android and then clicks the center of it.
=> [Android] Click on the center of the down stepper button

Xamarin.Forms.Core/StyleSheets/StyleSheet.cs
Dispose the disposable readers while parsing StyleSheets
- fixes #6986
None
None
Not applicable
=> [C] Dispose the Disposable

Xamarin.Forms.Build.Tasks/ModuleDefinitionExtensions.cs, Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs, Xamarin.Forms.Xaml.UnitTests/Issues/AB946693.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/AB946693.xaml.cs
When a resource was missing a key (non-implicit resource), XamlC was throwing
an AssemblyResolutionException instead of a proper XamlParseException when the
type of the resource was in a different xmlns than the default Forms one.
All the other cases are fine (default xmlns, or non-compiled Xaml)
- fixes AB#946693
None
None
Not applicable
=> [XamlC] throw XPE on missing resource key

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4187.cs
In relation to #7080, implemented a fix to make this test pass. Seems like a timing issue was going on here.
N/A
None
- Android
None
Not applicable
=> [Android] Added WaitForElement on failing test Issue4187 to make it green

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2499.cs
In relation to #7080, implemented a fix to make this test pass. Seems like a timing issue was going on here.
N/A
None
- Android
None
Not applicable
=> [Android] Added WaitForElement on failing test Issue2499 to make it green

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2577.cs
In relation to #7080, implemented a fix to make this test pass. Seems like a timing issue was going on here.
N/A
None
- Android
None
Not applicable
=> [Android] Added a longer retry frequency on failing test Issue2577 to make it green

Xamarin.Forms.Platform.Android/ContextExtensions.cs
There's no need to check the Context type and then recurse over it ($$$$) 
Just check the static IsDesignModeEnabled for the same information
Make sure previewer still works for all places on Android where IsDesignerContext is used
=> [Android] Just check if IsDesignModeEnabled true instead of checking Context type

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla26993.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Github5623.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2951.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4597.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4915.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6286.cs, Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs
- Fixed 2951 to retry querying for buttons. It looks like the UI tests are querying before the buttons have time to disappear
- Renamed the RetryUntilPresent  to QueryUntilPresent and moved it to the same namespace as Query so when people are using Query they'll see *QueryUntilPresent* and think "Hey I bet that's better to use"
- Automated
=> [UITest] Fix 2951 and moved extension method to be more visible

Xamarin.Forms.Core/Registrar.cs, Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs, Xamarin.Forms.Platform.Android/Forms.cs
Rename `InitializationFlags` to `ActivationFlags` so I could use `ActivationFlags` during activation and `InitializationFlags` during the `Forms.Initialization` call. Duh.
This is technically a breaking change but no one should be using the flags. I introduced them to establish a mechanism whereby we can supply developers a way to disable unused feature initialization at startup. Disabling the one sample feature (css initialization) won't be noticeable by itself so that's why no one is using it. Only when all the perf tweaks are taken together is the gain noticeable. 
Introduce a new `ActivationFlags` with a flag `FixedStatusBarColor`. If the developer specifies the flag, then the developer is asking that we not burn time at startup making a system call whose only purpose is to allow the …
=> Rename InitializationFlags -> ActivationFlags

Xamarin.Forms.Core/Internals/ProfilePage.cs
Xamarin.Forms ships it's own profiler in `Xamarin.Forms.Internals.Profile`. This PR will ship the UI to visualize the profile data. 
The profiler requires manual instrumentation. So it's not a general profiler. It profiles only what we instrument. And right now we've injected sampling points useful for profiling startup performance. And even then, this information is tailored so the Forms team can easily request a profile from a customer and determine if we're the reason the app startup is slow or not. That said, customers are free to submit PRs of sampling points they've injected into Forms they found useful while debugging their startup performance. 
To display the profile, hijack a UI element that appears just after startup and have it call the `ContentPage` extension method …
=> Add ProfilePage.cs

Xamarin.Forms.Core/Internals/Ticker.cs, Xamarin.Forms.Platform.Android/Forms.cs
Optimize `AndroidTicker` initialization to speed up startup. 
Note: The code assumes a ticker can somehow already exist at startup (backgrounding?) but the common case is that the ticker doesn't exist at startup. So I keep the startup check; This logic shouldn't result in any logical difference.
**Expected**: If ticker exists, dispose and null reference (so do nothing in common case). Lazily activate a ticker (again, do nothing as the ticker is not used during startup).
**Actual**: If ticker doesn't exist, then activate (so always activate in the common case). If ticker exists, dispose and null reference (so we throw away the ticker we just created). Eagerly activate a ticker (so we activate a second ticker that we don't immediately use).
We were activating two (count em, two!) tickers …
=> Stop the madness; 

Xamarin.Forms.Platform.GTK/GtkPlatformServices.cs
Implemented missing NamedSize values for GTK.
Fix an exception using Label with a predefined FontSize value.
Related to https://github.com/xamarin/Xamarin.Forms/pull/7116.
None
- GTK
When you now use one of the "new" NamedSize enum values GTK doesn't crash.
Not applicable
Go to the new Issue7111 test case, if it shows and doesn't crash it works.
=> [GTK] Added missing NamedSizes for GTK

Xamarin.Forms.Platform.Android/AndroidTicker.cs
Fixes the issue described in #5421 by disabling AndroidTicker if AnimatorDurationScale is set to 0.
- fixes #5421
None
- Android
None
Not applicable
As given in the "Steps to Reproduce" in #5421:
1. Set Animator duration scale to off in developer settings on an Android device.
2. Call any animation -> var animationTask = label.FadeTo(1)
3. await the resulting task
Without the provided fix, the awaited task will never complete. If the fix is applied, no animation is shown and the task completes immediately.
=> [Android] Disable AndroidTicker if AnimatorDurationScale is equal or below 0

Xamarin.Forms.Platform.Android/Renderers/FormsWebViewClient.cs, Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs
When using webview in Xamarin.Forms on Android whenever the Navigated/Navigating event is fired, in args it always has the same value for all the events i.e. WebNavigationEvent.NewPage. It should return the correct value ([API Doc](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.webnavigationevent?view=xamarin-forms)) based on the event.
Now returning different values for WebNavigationEvent based on event.
Nona
- Android
=> [Android] Update webview to use correct value for WebNavigationEvent

Xamarin.Forms.Platform.Android/Forms.cs
Previewer runs in one main thread. Therefore, it is not necessary to call another "main" thread.
It fixes bugs changes in layout when using `BeginInvokeOnMainThread`
- fixes #5798 
- fixes [AB#837773](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/837773)
None
- Android
Before
After
[Screencast](https://recordit.co/BzhrSh8T6H)
[AB#837773](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/837773)
=> [Android, previewer] fixes layouts in the preview when using InvokeOnMainThread

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla27731.cs
The test only calls WaitForNoElement which isn't very definitive if it hasn't made sure that the test itself hasn't loaded.  When looking at AppCenter runs the test after this had screen shots of this test because this test was just passing before it actually finished running which would then cause the next test to fail
Automated
=> add wait before WaitForNoElement

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7111.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.WPF/WPFPlatformServices.cs, Xamarin.Forms.Platform.WPF/WPFResources.xaml
Implemented missing NamedSize values for WPF.
I could not find any documentation on if and what the official values should be so I just took the ones from UWP.
- fixes #7111
None
- WPF
When you now use one of the "new" NamedSize enum values WPF doesn't crash.
Not applicable
Go to the new Issue7111 test case, if it shows and doesn't crash it works
=> [WPF] Add missing NamedSize

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla29017.cs, Xamarin.Forms.Controls/GalleryPages/MapGallery.xaml, Xamarin.Forms.Controls/GalleryPages/MapGallery.xaml.cs, Xamarin.Forms.Maps.Android/MapRenderer.cs, Xamarin.Forms.Maps.GTK/MapRenderer.cs, Xamarin.Forms.Maps.Tizen/MapRenderer.cs, Xamarin.Forms.Maps.UWP/PushPin.cs, Xamarin.Forms.Maps.WPF/FormsPushPin.cs, Xamarin.Forms.Maps.iOS/MapRenderer.cs, Xamarin.Forms.Maps/Pin.cs, Xamarin.Forms.Maps/PinClickedEventArgs.cs
Replace the `Pin.Clicked` event which has caused much confusion about when it is actually fired with two separate events, `MarkerClicked` and `InfoWindowClicked`.
- fixes #2509 
- fixes #3131
- fixes #5490
Added:
- `public class PinClickedEventArgs`
- Pin
- `public event EventHandler<PinClickedEventArgs> MarkerClicked;`
- `public event EventHandler<PinClickedEventArgs> InfoWindowClicked;`
- `public bool SendMarkerClick()`
- `public bool SendInfoWindowClick()`
- Android MapRenderer
- `protected Pin GetPinForMarker(Marker marker)`
- `void OnMarkerClick(object sender, GoogleMap.MarkerClickEventArgs e)`
- iOS MapRenderer
- `protected Pin GetPinForAnnotation(IMKAnnotation annotation)`
- `void MkMapViewOnAnnotationViewSelected(object sender, MKAnnotationViewEventArgs e)`
Changed:
- Android …
=> Add separate MarkerClick and InfoWindowClick events for Pins

Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.iOS/CollectionView/ListSource.cs, Xamarin.Forms.Platform.iOS/CollectionView/ObservableGroupedSource.cs, Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs
Using .Item instead of .Row for accuracy (horizontal collections don't necessarily have "rows") and consistency.
- fixes #6737
None
- iOS
None
Not applicable
=> Use NSIndexPath.Item instead of .Row in CollectionView

Xamarin.Forms.Platform.iOS/Forms.cs, Xamarin.Forms.Platform.iOS/PlatformRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/PhoneMasterDetailRenderer.cs
Changes check for iOS version >= 11 to a check to see if the `setNeedsUpdateOfHomeIndicatorAutoHidden` selector is available before calling the `SetNeedsUpdateOfHomeIndicatorAutoHidden` method.
No automated test created as there should be no difference in behavior except to avoid a crash due to calling an Obj-C selector that may not be available on all devices running iOS >= 11. In this case, it seems that checking that the selector is available is better than checking for the iOS version as it will be a valid check regardless of iOS version, where as just the version check alone is not guaranteeing the availability of this particular selector as devices pre iPhone X do not have a Home Indicator. 
- fixes #7109 
None
- iOS
Users app won't crash when running on an iPhone 6 with iOS version …
=> Fixes issue #7109 in XF 4.0 branch

Xamarin.Forms.Platform.iOS/Extensions/VisualElementExtensions.cs
This extension is already public on UWP and Android
- fixes #7142
Added:
- IVisualElementRenderer VisualElementExtensions.GetRenderer
- iOS
No testing needed
=> [iOS] make VisualElementExtensions public on iOS

Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellGestures.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/ShellContentFragment.cs, Xamarin.Forms.Platform.Android/Renderers/ShellSectionRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/TableViewRenderer.cs, Xamarin.Forms.Platform.Android/Resources/Layout/RootLayout.axml, Xamarin.Forms.Platform.Android/Resources/Layout/ShellContent.axml, Xamarin.Forms.Platform.Android/ViewExtensions.cs
Scrolling with a WebView and Shell currently doesn't work because all Shell content has a NestedScrollView as a parent.  This breaks scrolling the WebView because the WebView always gets sized to the ViewPort. When the WebView isn't inside a ScrollView this is fine because then all the touch events get passed to the WebView and the WebView control itself scrolls. When it's nested in a ScrollView the ScrollView intercepts all the touches so nothing makes it down to the WebView. If we had fixed this Issue https://github.com/xamarin/Xamarin.Forms/issues/1711 then you could size the WebView to its web content and it would be fine that the NestedScrollView intercepts the touches because then it would just be in charge of scrolling the WebView.
That being said I don't think nesting a WebView …
=> Remove NestedScrollView from the default shell layout

Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs
Tab switching hasn't been working.
The problem is that macOS switched views itself. And KeyUp is called by NEXT view. 
+ it doesn't make sense to switch focus on UP event. Because native behavior is switching on KeyDown
- fixes #6074
- related #6671
None
macOS
Switching via tab seems to be working
Not applicable
Run any sample with entries / editors etc. and try to switch views with Tab and Shift+Tab
=> [macOS] Switch focus on TAB pressed

Xamarin.Forms.Platform.iOS/ContextActionCell.cs, Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
* Setup the selection  from the `ContectActionCell` was causing the Xamarin.Forms previewer to crash.
TL;DR:  The previewer was crashing for a few scenarios, and rendering `ItemPage.xaml` from the Master Detail template.
From stack trace it seems that the `GestureReconizer` of the `ContextActionCell` was collected or disposed, when UIKit calls `GetCell` or `LayoutSubviews`, which calls `SetupSelection` https://github.com/xamarin/Xamarin.Forms/blob/57d507ef0b47d54d4026a07632f88a39a40de0c9/Xamarin.Forms.Platform.iOS/ContextActionCell.cs#L646 the GestureReconizer isn't there anymore, and X.iOS tries to resurrect it, causing a `MissingCtor` exception
https://gist.github.com/viniciusjarina/407952739b7f19eee15df6a5a021192b
The problem seems related to a regression on Mono/Xamarin.iOS, this …
=> [iOS] Moved `UITableView` setup selection to `ListViewRenderer`

Xamarin.Forms.Platform.Android/Platform.cs
The changes is #4915 regressed how the icon is checked on the Master page of the MDP
- fixes #6958 
Test a non appcompat application using MDP
=> NonAppCompat check if MDP IconImageSource is null to avoid NRE exception

Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj, Xamarin.Forms.ControlGallery.WindowsUniversal/_5886DependencyService.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5886.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.UAP/ScrollViewRenderer.cs
When setting the renderer for a second time for the `ScrollView` there was some leftovers in terms of the children that were already added to the visual tree. In the case of this issue (#5886) the `Grid` would stay in existence and when another renderer was added we would get an error on this.
Added a existing cleanup call to the cleanup of the `ScrollViewRenderer` that recursively cleans up all the children which fixes the issue. Also added the reproduction and automated UI tests for it.
- fixes #5886
None
- UWP
None
Not applicable
=> [UWP] Value does not fall with in the expected range Exception while creating NativeView

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6994.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/ListViewAdapter.cs
#6467 disposes the `_labelTextColorDefault` on the fast LabelRenderer for Android. This causes a NullPointerException when attempting to access it later.
This does not happen on the legacy renderer, which now also has the same dispose but a slightly different pattern of setting the value. Using the same pattern does not fix the crash on the Fast Renderer, so the best thing is to remove the dispose and possibly revisit this later.
- fixes #6994 
None
- Android
Not applicable
There is an automated test with instructions.
=> [Android] Don't dispose the _labelTextColorDefault on Label Fast Renderer

.nuspec/Xamarin.Forms.nuspec
Copies `ItemsViewStyles.xbf` to the right target directory.  Targeted at 4.2 since the linked commit has a tag for the 4.2.0-pre3 package.
- fixes #7184 
None
- UWP
None
Not applicable
Install the NuGet with this change and watch it being compiled!
=> [UWP] Fix ItemsViewStyles.xbf compilation error

Xamarin.Forms.Platform.iOS/Extensions/Extensions.cs, Xamarin.Forms.Platform.iOS/ModalWrapper.cs
If running iOS13 then force the ModalPresentationStyle to Full Screen since XF can't handle swipe dismiss. Once we are on xCode 11 and have the necessary APIs then we can more easily react to swipe dismiss
- iOS
Make sure Modal pages work on iOS as expected
=> Force iOS 13 to use Full Screen for Modal

Xamarin.Forms.Platform.iOS/Forms.cs, Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs
iOS 13 changes how the Views associated with a UISplitView get added to the SubViews list.
This PR accounts for those changes
- iOS
Make sure the MDP on iOS 12 still works and make sure that MDP on iOS 13 works
=> Fix MDP for iPads running iOS13

PagesGallery/PagesGallery.Tizen/PagesGallery.Tizen.cs, Xamarin.Forms.ControlGallery.Tizen/ControlGallery.Tizen.cs, Xamarin.Forms.ControlGallery.Tizen/DisposeLabelRenderer.cs, Xamarin.Forms.ControlGallery.Tizen/DisposePageRenderer.cs, Xamarin.Forms.Maps.Tizen/MapRenderer.cs, Xamarin.Forms.Maps.Tizen/Properties/AssemblyInfo.cs, Xamarin.Forms.Material.Tizen/FormsMaterial.cs, Xamarin.Forms.Material.Tizen/MaterialActivityIndicatorRenderer.cs, Xamarin.Forms.Material.Tizen/MaterialButtonRenderer.cs, Xamarin.Forms.Material.Tizen/MaterialCheckBoxRenderer.cs, Xamarin.Forms.Material.Tizen/MaterialEntryRenderer.cs, Xamarin.Forms.Material.Tizen/MaterialFrameRenderer.cs, Xamarin.Forms.Material.Tizen/MaterialProgressBarRenderer.cs, Xamarin.Forms.Material.Tizen/MaterialSliderRenderer.cs, Xamarin.Forms.Platform.Tizen/ExportCellAttribute.cs, Xamarin.Forms.Platform.Tizen/ExportHandlerAttribute.cs, Xamarin.Forms.Platform.Tizen/ExportImageSourceHandlerAttribute.cs, Xamarin.Forms.Platform.Tizen/ExportRendererAttribute.cs, Xamarin.Forms.Platform.Tizen/Extensions/PageExtensions.cs, Xamarin.Forms.Platform.Tizen/Forms.cs, Xamarin.Forms.Platform.Tizen/TizenTitleBarVisibility.cs, Xamarin.Forms.Platform.Tizen/ViewInitializedEventArgs.cs
This PR is for fixing namespace of some classes (such as `Forms`, `ExportRendererAttribute` and so on) correctly.
Replaces #7185 
None
Changed:
- Xamarin.Forms.Platform.Tizen.Forms => Xamarin.Forms.Forms
- Xamarin.Forms.Platform.Tizen.ExportRendererAttribute => Xamarin.Forms.ExportRendererAttribute 
- Xamarin.Forms.Platform.Tizen.ExportCellAttribute => Xamarin.Forms.ExportCellAttribute 
- Xamarin.Forms.Platform.Tizen.ExportImageSourceHandlerAttribute => Xamarin.Forms.ExportImageSourceHandlerAttribute 
- Xamarin.Forms.Platform.Tizen.ExportHandlerAttribute => Xamarin.Forms.ExportHandlerAttribute 
- Xamarin.Forms.Platform.Tizen.ViewInitializedEventArgs => Xamarin.Forms.ViewInitializedEventArgs 
- Xamarin.Forms.Platform.Tizen.TizenTitleBarVisibility => Xamarin.Forms.TizenTitleBarVisibility 
- …
=> [Tizen] Fix Forms namespace correctly

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3475.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/VisualElementPackager.cs
While inspecting this issue in iOS, i noticed that the `Render` property in the `VisualElementPackager` got multiple subscriptions to `OnRendererElementChanged` when using `CompressedLayout.IsHeadless = True`.
So if we had 150 stacklayout with `CompressedLayout.IsHeadless = True`, the `Render` property, get 150 subscriptions to `OnRendererElementChanged`, slowing down a lot the page.
To solve this, i added an optional boolean property in the `VisualElementPackager` constructor, when is set to `True` (for Headless Layouts) we skip the event subscription to `OnRendererElementChanged`.
Default is `False`.
|Compression mode|Time to render|
| -------------------  | :------------------ |
|No compression|1160ms|
|With Compression before the fix|17268ms|
|**With Compression after the …
=> [iOS] Fix LayoutCompression Performance Issues #3475

Xamarin.Forms.Platform.iOS/Renderers/SafeShellTabBarAppearanceTracker.cs
To make Shell work on iOS 9 we need to check if there is support for the unselectedItemTintColor which is only supported from iOS 10 and up.
- fixes #6739
None
- iOS
None
Not applicable
Go to a Shell page on an iOS 9 device/simulator and observe that it does not end in an NRE
=> [iOS9] Check unselectedItemTintColor support

Xamarin.Forms.Platform.Tizen/Forms.cs
This PR introduces a new `Forms.Init()` that allows you to customize initialization options.  (in the same way as android backend - #6087, #6149)
None
Added:
- void Forms.Init(InitializationOptions options)
- Tizen
This change does not affect the behavior of existing `Forms.Init`. It's just an addition to the new `Forms.Init()` having `InitializationOption` to enable partial init. For example, using this, you can register a certain type of renderers at initialization time. 
```cs
// Creates the handler attributes
var assembly = Assembly.GetAssembly(typeof(Forms));
object[] attributes = assembly.GetCustomAttributes(typeof(HandlerAttribute), true);
var handlerAttributes = new HandlerAttribute[attributes.Length];
Array.Copy(attributes, handlerAttributes, attributes.Length);
// Creates the …
```
=> [Tizen] Adds Opt-in Init

Xamarin.Forms.Controls/GalleryPages/PickerGallery.cs, Xamarin.Forms.Platform.iOS/Renderers/DatePickerRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/TimePickerRenderer.cs
Pickers reads like a Button. This is part of PR #3955
- partially fixes #3454
None
- iOS
None
Before
After
- start `PickerGallery - Legacy` in ControlGallery
- run `Accessibility Inspector` or `VoiceOver`
- picker type should be like a button
=> [iOS] fix accessibility of Picker

Xamarin.Forms.Core.Design/toolbox/Xamarin.Forms.toolbox.xml
Fixes toolbox snippet for `CollectionView`. `ItemsLayout` is placed outside of the `ItemTemplate`
None
- XAML (all platforms)
Not applicable
- open Toolbox in code editor
- drag control "CollectionView" into Xaml Editor
> VS bug [#972262](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/972262)
=> [xaml] Fixes toolbox snippet for CollectionView

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellTitleView.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs, Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs
Android wasn't correctly replacing the titleview content on change it would just create a new container over and over again. 
- fixes #7244
- Android
- There are automated UI tests
- Test shell store title view
=> Fix android to not duplicate TitleView with Shell

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/NestedCollectionViews.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CollectionViewGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/NestedGalleries/NestedCollectionViewGallery.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/NestedGalleries/NestedCollectionViewGallery.xaml.cs, Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj, Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs
Closes #6620
At one point, iOS crashed if you tried to use a CollectionView in the ItemTemplate of another CollectionView. That's no longer the case (I suspect this was fixed as a side effect of changes in 4.1).
But while investigating this, it turned out that UWP also had this issue. So this PR fixes that, and adds an automated test so we can prevent this problem in the future.
- fixes #6620
None
- iOS
- UWP
None
Not applicable
Control Gallery, navigate to CollectionView Galleries -> Nested CollectionViews. The app should not crash.
=> Fix crash with nested CollectionViews on UWP

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/FilterSelection.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/FilterSelection.xaml.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/SelectionGallery.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/SelectableItemsViewRenderer.cs
UWP defaults IsSynchronizedWithCurrentItem to `true`, so when changing to a new CollectionViewSource the first item is automatically selected in the UI. 
For reference: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.selector.issynchronizedwithcurrentitem#selection-behavior-and-collectionviewsource
This change disables that option and fixes some minor double-subscription bugs when dealing with native selected item changes.
- fixes #7194
None
- UWP
None
Not applicable
Control Gallery, navigate to CollectionView Gallery -> Selection Galleries -> Filterable Single Selection and follow the on-screen instructions.
=> Disable UWP CollectionViewSource CurrentItem synchronization

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/LabelTextType.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Controls/CoreGalleryPages/LabelCoreGalleryPage.cs, Xamarin.Forms.Core/Label.cs, Xamarin.Forms.Core/TextType.cs, Xamarin.Forms.CustomAttributes/TestAttributes.cs, Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs, Xamarin.Forms.Platform.Android/Forms.cs, Xamarin.Forms.Platform.Android/Renderers/LabelRenderer.cs, Xamarin.Forms.Platform.UAP/LabelHtmlHelper.cs, Xamarin.Forms.Platform.UAP/LabelRenderer.cs, Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj, Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
With the new `TextType` property you can now set HTML formatted content on the `Label`. In the future other types might be added that use pure text formatting like Markdown. Functionality around `FormattedText` is unchanged.
In the discussion below we have been exploring the possibility to solve this with different spans. This is possible on iOS, but from what I can tell not on Android (and thus did not explore other platforms). While talking to @PureWeen we decided this was the best alternative.
Although we do allow HTML (through the native handlers for that on iOS and Android) not all tags are supported. We are limited by the support on the different platforms. I feel that might be something that is going to come up in the future.
- fixes #4504
Added:
- public enum TextType
- TextType …
=> Make Label display HTML from a string

Xamarin.Forms.Xaml.UnitTests/Issues/Gh7156.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh7156.xaml.cs, Xamarin.Forms.Xaml/MarkupExtensions/OnPlatformExtension.cs
If no default is provided for {OnPlatform}, default to DefaultValue if this is targetting a BindableProperty.
Also use other value than null as sentinel, as {x:Null} is a
perfectly valid value.
This is a breaking change, but the risk is very low
- fixes #7156
None
None
Not applicable
=> [X] OnPlatform use BP.DefaultValue

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellFlyoutBehavior.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj, Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj, Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs
The Backbutton Behavior broke the FlyoutBehavior.Disabled setting. This PR fixes that behavior and adds the much needed set of UI tests to make sure this doesn't happen again
- fixes #7238
- fixes #6261
- Introduced by #6762
The Back Button Behavior change incorrectly influenced the Flyout lock modes and the Flyout Behavior never had a proper set of UI tests written for it to ensure that nothing would break them.
- Android
- tests are automated
- with the test page I added you can test all the permutations to see if it all works how you'd expect it to act
- verify this is fixed https://github.com/xamarin/Xamarin.Forms/issues/6261 my tests seem to indicate that it is but #6261 says this is broken on iOS but for me it works fine on iOS
=> Fix Android FlyoutBehavior Disabled and add UI Tests

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6894.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6929.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7053.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/Renderers/IAccessibilityElementsController.cs, Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/WebViewRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs, Xamarin.Forms.Platform.iOS/VisualElementRenderer.cs
#3989 introduced focus order for Screen Readers. For iOS, we needed to implement AccessibilityElements in order to set the read order. 
1. WebViews were excluded from readers because WebViews implement the fast renderers pattern and did not implement ITabStop. We have now made it possible for any view that does not implement ITabStop to work with AccessibilityElements, and we've implemented ITabStop on the WebView renderers.
2. Layouts were explicitly excluded from AccessibilityElements; this was a mistake on my part, as I thought this was how it worked on Android. This change has been reverted.
3. AccessibilityElements was not updated when visibility changed. In addition, the code that was meant to reset AccessibilityElements when TabIndex or IsTabStop changed also wasn't working. Both …
=> [iOS] Fix accessibility regressions with hidden views, WebViews, and layouts

Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
PR #7157 introduced a regression by adding a UITableView delegate. 
Fix this by using the existing method on ListViewSource 
- fixes failing tests on master / 4.3
None
- iOS
Selecting a item on ListView will work, it-s not working right now
Not applicable
=> [iOS] Fix Scrolled, don't use UITableView delegate

Xamarin.Forms.ControlGallery.Android/Environment.txt, Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43941.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutTemplatedContentRenderer.cs
- Check for null on the HeaderContainer
- change the MONO_GC_PARAMS implementation to new because the default one keeps crashing the UI tests
- Adjusted one of the UI Tests that looks to not be collection as fast from the new GC settings
Regression introduced by not checking null on this PR
https://github.com/xamarin/Xamarin.Forms/pull/6970
- Android
- tests are automated
- test shell without a flyout header specified
=> [Android] Check if Shell Flyout header is null before trying to use it

Xamarin.Forms.Platform.Android/AndroidTicker.cs
fixes #7255
fixes #7291
fixes #7278
Same PR as https://github.com/xamarin/Xamarin.Forms/pull/7292 but on the correct branch
I found that if the Animation duration scale setting has never been changed in the developer settings, the scale we get will allways be 0. So instead of defaulting to 0 we default to 1. This means if i havent touched the setting it will behave as it did pre 4.2.
Also if somehow the context is null, we should default to enabling animations since this is far more "normal" than disabling animations.
=> [Android] fix animations not animating

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2338.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4973.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/AppCompat/CarouselPageRenderer.cs, Xamarin.Forms.Platform.Android/AppCompat/FormsFragmentPagerAdapter.cs
Fix the disposing of the TabbedPageRenderer.
There are several problems with the current implementation of the dispose :
- The fragments created by the FragmentPagerAdapter was not removed
- The TabSelected listeners are not correctly cleared
- The PageChange listeners are not cleared
- Fixes #4973
None
- Android
None
Not applicable
- Install the repro App : [issue4973.zip](https://github.com/xamarin/Xamarin.Forms/files/2752742/issue4973.zip)
- Go to the tab of the right
- Go to another tab
=> [Android] Correctly dispose TabbedPageRenderer

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7338.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/CollectionView/GridViewLayout.cs
The `NeedsPartialColumnAdjustment` method was checking the numbers of items in section 0 even if section 0 did not exist, causing a crash. 
Props to @jfversluis, who'd already fixed this in another PR.
- fixes #7338
None
- iOS
None
Not applicable
Automated Test
=> Verify sections exist before calling NumberOfItemsInSection

Xamarin.Forms.Build.Tasks/DebugXamlCTask.cs, Xamarin.Forms.Build.Tasks/SetNamescopesAndRegisterNamesVisitor.cs, Xamarin.Forms.Core/Internals/NameScope.cs, Xamarin.Forms.Xaml.UnitTests/Issues/Gh7097.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh7097.xaml.cs, Xamarin.Forms.Xaml.UnitTests/Issues/Gh7097Base.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh7097Base.xaml.cs, Xamarin.Forms.Xaml.UnitTests/MarkupExpressionParserTests.cs, Xamarin.Forms.Xaml/CreateValuesVisitor.cs, Xamarin.Forms.Xaml/NamescopingVisitor.cs, Xamarin.Forms.Xaml/RegisterXNamesVisitor.cs, Xamarin.Forms.Xaml/XamlNode.cs, Xamarin.Forms.Xaml/XamlServiceProvider.cs
If a xaml control derives from another xaml control, thy both should share the same
NameScope. This add a check if the xaml root already has a NameScope (set by the base)
and reuses it.
This fixes 2 regressions introduced by #7040 and some other unreported edge cases.
- fixes #7097
- fixes #7286
None
None
Not applicable
=> [X] Reuse baseclass namescope if it exists

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterGridHorizontal.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterGridHorizontal.xaml.cs, Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Header/footer wasn't properly adjusting for a horizontal layout.
- fixes #7246
- iOS
When testing this please note that there appears to be a bug (#7309) where if the CV grid doesn't fill the rows and columns then it adds an extra empty column so the footer for the included test looks like it's offset incorrectly but it is not.
=> Fix iOS footer and header to layout left and right for horizontal layout

Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs
The value of **PeekAreaInsets** was set correctly initially. However, in case of any change in the value of the property, the UI was not updated. This PR fixes the issue.
None
- Android
Dynamically changing PeekAreaInsets property must update the UI.
Open Core Gallery Sample and change dynamically the PeekAreaInsets in some of the available CarouselView samples.
=> [CarouselView] Fixed issue updating PeekAreaInsets

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2818.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/ScreenshotConditionalApp.cs, Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs, Xamarin.Forms.Platform.iOS/Extensions/FlowDirectionExtensions.cs, Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs
- When running on iOS13 don't use the width hack when switching from LTR to RTL. It looks like iOS13 fixed whatever issue was causing that width to get set to 0.5 so it's not needed anymore
- When running on iOS 13 if the user changes the FlowDirection of the MDP remove and readd it to the view. From what I can tell the fact that this worked at all in iOS 12 was a bug and may have also been why the width became messed up. 
If you look at the appearance docs
https://developer.apple.com/documentation/uikit/uiappearance
> iOS applies appearance changes when a view enters a window, it doesn’t change the appearance of a view that’s already in a window. To change the appearance of a view that’s currently in a window, remove the view from the view hierarchy and then put it back.
So it seems like …
=> Fix RTL behavior for MasterDetailsPage when running on iOS 13 iPads

Xamarin.Forms.Platform.Android/Anticipator.cs, Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs, Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Speed up startup by making use of any extra processors on the phone to eagerly execute class constructors off the UIThread which we know the UIThread will need during startup.
_This change helps more with non-AOT debug development startup by JITting a big chunk of code off the UIThread (poor man's AOT). So, honestly, this change just lays the ground work for the more significant change (which speeds up release performance) of pre-inflating views off the UIThread by demonstrating how the `Anticipator` works (it's just a hand rolled thread pool)._ 
None.
None
- Android
None
Every UITest is a test. If the app starts, then this worked!
=> Anticipate .cctors

Directory.Build.props, PagesGallery/PagesGallery.Droid/PagesGallery.Droid.csproj, Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj, Xamarin.Forms.Controls/Properties/AssemblyInfo.cs, Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
Context: https://devblogs.microsoft.com/xamarin/optimize-xamarin-android-builds/
The goal here is to improve the developer loop on Android when working
on Xamarin.Forms using a few settings for `Debug` builds:
* Enable Fast Deployment
* `AndroidLinkMode=None`
* `DebugType=portable`
* `ProduceReferenceAssembly=True` in netstandard projects
After these changes changes:
Before:
Time Elapsed 00:00:37.15
After:
Time Elapsed 00:00:15.79
This was just running:
msbuild Xamarin.Forms.ControlGallery.Android\Xamarin.Forms.ControlGallery.Android.csproj
I was using VS 2019 16.2 on Windows, changing a XAML file.
So one thing to note is that `AndroidLinkMode=Full` was used the
UITests running on CI are using `Debug` builds. I used a `Condition`
to check the `$(CI)` variable, so UITests will be …
=> [build] cleanup MSBuild settings for faster builds

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7290.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core.UnitTests/PageTests.cs, Xamarin.Forms.Core/Page.cs
DisplayAlert and DisplayActionSheet can't function until the Page has a renderer attached to it. This change queue's up requests to those methods so that once the element IsPlatformReady (renderer attached) they will execute.
- fixes #7290 
https://github.com/xamarin/Xamarin.Forms/pull/6527
Shell fires OnAppearing events earlier than if the Pages are part of other layouts. 
Because DisplayAlert and DisplayActionSheet  are now queue'd until the page is ready there could be scenarios where people were calling these methods and nothing was happening.  This issue also would have crept up once we implemented the new life cycles event code as well since that code would move OnAppearing earlier on both iOS and Android
- Automated tests included
=> Queue Page.Display actions until platform is ready

.nuspec/Xamarin.Forms.nuspec, .nuspec/Xamarin.Forms.targets, EmbeddingTestBeds/Embedding.UWP/Embedding.UWP.csproj, PagesGallery/PagesGallery.UWP/PagesGallery.UWP.csproj, Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/RefreshViewTests.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/RefreshViewWindows.cs, Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGallery.cs, Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs, Xamarin.Forms.Maps.UWP/Xamarin.Forms.Maps.UWP.csproj, Xamarin.Forms.Platform.UAP/Forms.cs, Xamarin.Forms.Platform.UAP/Platform.cs, Xamarin.Forms.Platform.UAP/Properties/AssemblyInfo.cs, Xamarin.Forms.Platform.UAP/RefreshViewRenderer.cs, Xamarin.Forms.Platform.UAP/Resources.xaml, Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
RefreshView renderers for UWP
- fixes for UWP #5882
- UWP
*In the previous gif, in UWP, a Platform Specific is used to modify the pull direction.*
- Ensure all the Refresh View gallery pages work
- Added Warnings messages if your Target Platform is less than 17763
=> [UWP] RefreshView

Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/ObservableItemTemplateCollection.cs
Makes the CollectionView on UWP responsive to INotifyCollectionChanged Reset, Replace, and Move events; also fixes some issues with Add and Remove handling.
- partially implements #3172
None
- UWP
None
Not applicable
Control Gallery, CollectionView Gallery -> ObservableCollection Galleries -> [all]
=> Implement Move, Replace, and Reset for UWP CollectionView changes

Xamarin.Forms.Platform.Android/Forms.cs, Xamarin.Forms.Platform.Android/StreamWrapper.cs, Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
It appears that a race condition with how fast the stream is returned from HttpResponse leads to an image from a stream sometimes being loaded and then sometimes not
The Dispose on HttpContent class will only dispose of the returned stream if the status on the task returned from *ReadAsStreamAsync* is *RantoCompletion*
https://github.com/dotnet/corefx/blob/d3911035f2ba3eb5c44310342cc1d654e42aa316/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L540
So I think in some cases the stream will run to completion before the dispose is called and in other cases it won't
The call to ReadAsStreamAsync returns an invoked task. It doesn't start reading once awaited
I tried moving the await after the dispose explicitly
```C#
using (var client = new HttpClient())
using (HttpResponseMessage …
```
=> Dispose of HttpResponseMessage after stream is used

Xamarin.Forms.ControlGallery.Android/ApiLabelRenderer.cs, Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj, Xamarin.Forms.ControlGallery.iOS/ApiLabelRenderer.cs, Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Controls/ApiLabel.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7329.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs, Xamarin.Forms.Platform.Android/ViewExtensions.cs
Fixed code to correctly check and return the correct type when walking up the hierarchy searching for a parent. 
Regression: 
https://github.com/xamarin/Xamarin.Forms/pull/7032/files#diff-ef4e030a3614a0c4819c7bffc5fd7b03R114
- fixes #7329 
- Android
- Automated Tests
=> Wrong type checked after casting to type being searched for

Xamarin.Forms.Core/Editor.cs, Xamarin.Forms.Core/Entry.cs, Xamarin.Forms.Core/InputView.cs, Xamarin.Forms.Core/SearchBar.cs
The Entry, Editor, and SearchBar classes are all subclasses of InputView, but each separately implements the interfaces ITextElement and IPlaceholderElement and a Text property. This PR moves these properties into InputView while maintaining ABI backwards compatibility.
- N/A
Changed:
- Moved `Text` property, `TextChanged` event, `OnTextChanged` method, `IPlaceholderElement` implementation, `ITextElement` implementation from `Entry`, `Editor`, and `SearchBar` to `InputView`
None
N/A
N/A
=> [Core] Move TextProperty, ITextElement, and IPlaceholderElement to InputView

Xamarin.Forms.Platform.iOS/Extensions/NSObjectExtensions.cs, Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs, Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
A race condition might cause the Control to get disposed before the await returns so we need to check if the Control still exists after the await. 
I also just removed the await and used InvokeOnMainThread which I think is a bit more explicit and avoids having to mix async awaits into the code
- fixes #7139 
- iOS
I wasn't able to reproduce but the user on #7139 says it resolved the crashing for them. This is also very similar to a fix we did on Android which was also using an await on a Task.Delay(1)
=> move await to Begin Invoke and check for disposed

Xamarin.Forms.Core.UnitTests/ShellTests.cs, Xamarin.Forms.Core/Shell/Shell.cs
Wrong method called to get current page so FlyoutBehavior could effectively be calculated. This change retrieves the visible page and then walks up the tree correctly
- test by setting the Flyout Behavior at different levels of the Shell tree
=> Fix direction of walking when calculating effective FlyoutBehavior 

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6889.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/TemplatedItemViewHolder.cs
TemplatedItemViewHolder is setting the BindingContext of its View to `null` when recycling. This causes the template to update and invalidate, which hurts performance and leads to a race condition with measurement where the layout is measured as if it had empty string content and then laid out incorrectly. (For fast Label renderers; for the legacy Label renderers, the layout eventually displays correctly, but the control flashes blank briefly first).
This change eliminates the unnecessary re-binding to `null` and avoids the race condition.
- fixes #6889
None
- Android
None
Not applicable
Manual test 6889 in Control Gallery
=> [Android] Leave BindingContext intact when recycling TemplatedItemViewHolder

Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs, Xamarin.Forms.Platform.iOS/ViewRenderer.cs
Check if Control has been initialized before react on Text Changes. This fixes the failures on the `ScrollListViewInsideScrollView_apple_iphone_x` test which is being caused by the `ApiLabelRenderer` setting values on the Element before it has been initialized.
- iOS
- Automated Tests
=> Check if Control is ready before interacting with Native control

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselSnapGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselViewGallery.cs
If a CarouselView is created with an ItemsLayout without setting the SnapPointsType, the **CarouselView** does not **snap**. The problem is that, the default value of the **SnapPointsType** property is None. This is correct in the CollectionView but not in the CarouselView.
```
<CarouselView 
Position="0"
CurrentItem="{Binding CurrentItem, Mode=TwoWay}"
ItemsSource="{Binding Items}"
ItemTemplate="{StaticResource ItemTemplate}">
<CarouselView.ItemsLayout>
<ListItemsLayout
Orientation="Horizontal"/>
</CarouselView.ItemsLayout>
</CarouselView>
```
A new sample is also added in Core Gallery to test the different Snap options.
- fixes #7443
None
- iOS
- Android
With this PR, by default, the CarouselView uses a ItemsLayout with horizontal orientation and with snap.
=> [CarouselView] Fix default snap

Xamarin.Forms.Platform.UAP/CollectionView/FormsGridView.cs, Xamarin.Forms.Platform.UAP/CollectionView/FormsListView.cs, Xamarin.Forms.Platform.UAP/CollectionView/IEmptyView.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewStyles.xaml, Xamarin.Forms.Platform.UAP/CollectionView/StructuredItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
Makes the CollectionView EmptyView functionality work on UWP.
- partially implements #3172
None
- UWP
None
Not applicable
Control Gallery, navigate to CollectionView Gallery -> EmptyView Galleries and run everything.
Automated tests exist, but this is UWP.
=> Implement EmptyView on UWP

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7519.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7519Xaml.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7519Xaml.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/Items/CarouselView.cs, Xamarin.Forms.Core/Items/ListItemsLayout.cs, Xamarin.Forms.Core/Items/StructuredItemsView.cs, Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs
Fixes problems with CarouselView/CollectionView ignoring the LinearItemsLayout settings.
- fixes #7519
- fixes #7524
None
- iOS
- Android
- UWP
None
Not applicable
Control Gallery, navigate to issue 7519.
=> Fix horizontal layout issues introduced in 7456

Xamarin.Forms.Core.UnitTests/DeviceUnitTests.cs, azure-pipelines.yml
- TestInvokeOnMainThreadWithAsyncActionError fails occasionally so I increased the wait time
- Fix binlog path "/" direction so binlog files get placed correctly into artifacts directory
=> Tweak unit test so it's more reliable and fix binlog path

Xamarin.Forms.Platform.MacOS/Renderers/DatePickerRenderer.cs, Xamarin.Forms.Platform.MacOS/Renderers/TimePickerRenderer.cs
Using a custom font size leads to clipping issue in the date and time picker since it uses a constant size for the separators. This change enforces to use the default font size for these controls to avoid the clipping issues.
- fixes #6817
None
-macOS
- FontSize does not longer apply to Date/TimePicker on macOS
Old: 
-> This should show 23.11.2019
-> This should show 12:59:59
New
- enter double digit times/dates
=> [macOS] Only use default font size for Time/DatePicker to avoid clipping issues

Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewLayout.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
`CarouselViewLayout` has an `_addInsets` variable, but its value is always set to true. This PR removes that.
=> [iOS] Remove class variable from CarouselViewLayout whose value is always true

Xamarin.Forms.Platform.UAP/FormsCommandBarStyle.xaml
Gets rid of an extra brace in an animation.
- fixes #7545
None
- UWP
None
Not applicable
=> Remove errant brace in FormsCommandBarStyle

Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Verify that the _drawerToggle isn't null when navigating. This is a scenario that only occurs on Tablets
- fixes #7496
- Android
- Run MDP on an Android tablet , hide the back button, and make sure it doesn't crash
=> Check if the Drawer Toggle has been instantiated when using a Tablet and MDP

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterGrid.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterGrid.xaml.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterGridHorizontal.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterGridHorizontal.xaml.cs, Xamarin.Forms.Core/Items/StructuredItemsView.cs, Xamarin.Forms.Platform.Android/CollectionView/RecyclerViewScrollListener.cs, Xamarin.Forms.Platform.Android/CollectionView/SelectableItemsViewAdapter.cs, Xamarin.Forms.Platform.Android/CollectionView/StructuredItemsViewAdapter.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.iOS/CollectionView/StructuredItemsViewController.cs, Xamarin.Forms.Platform.iOS/CollectionView/StructuredItemsViewRenderer.cs, Xamarin.Forms.Platform.iOS/CollectionView/TemplateHelpers.cs, Xamarin.Forms.Platform.iOS/CollectionView/UICollectionViewDelegator.cs
- Fixed iOS and Android so that when you swap out or just null out the header/footer they properly show/hide
- Fixed ContentOffset adjustment on iOS to be correct when said swapping occurs
- Fixed iOS to remeasure header/footer once LayoutSubviews is called on the Adapter. The initial width of the CV when the Header/footer is realized is larger than when it actually gets to the layoutsubviews call
- on iOS dispose of the renderers when header/footer is swapped out
- On Android the Scroll Values weren't being converted back from Device pixels before being returned to Forms
- On iOS fixed the Scroll Values so that if the ContentInset is set on the CollectionView from the header that it doesn't affect the scroll values
- fixes #7453
- fixes #7347 
- iOS
- Android
- PR includes modifications …
=> [Android/iOS] Update CollectionView when user changes out the header/footer

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5728.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7313.cs, Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs
The code added here https://github.com/xamarin/Xamarin.Forms/pull/6473/files#diff-198607f4ce97efcc515a271473524b08R1482 causes a queue'd request to *BeginRefresh*. If some other processes *Begins* and then *Ends* the refresh before this process is able to run then it needs to ignore the queue'd *BeginRefresh*
- fixes #7313
- iOS
- Included automated tests
- Also manually test 5728 
- Test all your favorite iOS ListView refreshing scenarios!! Make sure they all work as expected
=> Check to see if the BeginRefresh request is no longer needed

Xamarin.Forms.Platform.UAP/CollectionView/CarouselViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemContentControl.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemTemplateContext.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemTemplateEnumerator.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewStyles.xaml, Xamarin.Forms.Platform.UAP/CollectionView/ObservableItemTemplateCollection.cs, Xamarin.Forms.Platform.UAP/CollectionView/SelectableItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/StructuredItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/TemplatedItemSourceFactory.cs, Xamarin.Forms.Platform.UAP/Properties/AssemblyInfo.cs, Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
Makes the CarouselView functionality work on UWP.
None
- UWP
None
Not applicable
Launch UWP Core Gallery and try the CarouselView Core sample.
=> Implement CarouselView on UWP

Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
Missing null check is causing NRE under some circumstances.
Fixes #7331
=> Check for null Platform in OnDestroy

Xamarin.Forms.Platform.MacOS/ModalPageTracker.cs
Seems removing modal controller from superview controller is missed.
- fixes #6866
None
macOS
No crash in case of several pushes/pops of modal page.
Not applicable
* Try to push modal page like ```Navigation.PushModalAsync(new NavigationPage(new ModalPage()));```
* Pop from ModalPage like ```Navigation.PopModalAsync();```
* Try to push new modal page again
=> [macOS] PushModalAsync a 2nd time causes a crash

Xamarin.Forms.Core/Visuals/VisualMarker.cs
Removed `MatchParent` value from Property Editor.
None
None
**Before**
**After**
=> [C] Removed MatchParent value from Property Editor

Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs, Xamarin.Forms.Xaml/Diagnostics/DebuggerHelper.cs, Xamarin.Forms.Xaml/Diagnostics/VisualDiagnostics.cs
this fixes a regression introduced in #7474
- fixes #7570
None
None
Not applicable
=> [X] avoid throwing in VisualDiagnostics

Xamarin.Forms.Core.UnitTests/RelativeSourceBindingTests.cs, Xamarin.Forms.Core/Binding.cs, Xamarin.Forms.Core/BindingExpression.cs, Xamarin.Forms.Core/Element.cs, Xamarin.Forms.Core/FormattedString.cs, Xamarin.Forms.Xaml.UnitTests/Issues/Gh7494.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh7494.xaml.cs
Spans, e.g., are no LogicalChildren of FormattedString, which is not a
LogicalChildren of Label. The newly introduced way of propagating the
TemplatedParent was top-down, using LogicalChildren, was not assigning
the correct TemplatedParent on Spans.
This reverts to a bottom-up lookup, hooking on ParentSet, like it used to
be.
As a side effect, the TemplateBindings are no longer updated on reparenting,
but this was the original behavior, and I can't think of a case where this
would be needed.
The regression to `{TemplateBinding}` was introduced by #4375.
- fixes #7494
None
None
Not applicable
=> [C] Fix TemplateBinding for non-logicalchildren

Xamarin.Forms.Build.Tasks/BindablePropertyReferenceExtensions.cs, Xamarin.Forms.Xaml.UnitTests/Issues/Gh7494.xaml.cs, Xamarin.Forms.Xaml.UnitTests/Issues/Gh7559.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh7559.xaml.cs
While looking for a potential TypeConverter attribute on the static getter of a
generic attached BP, resolve the generic return type.
- fixes #7559
None
None
Not applicable
=> [X] do not fail on generic aBP

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7357.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7357.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/SpacingItemDecoration.cs
`ItemSpacing` for the last item in CollectionView should work now. I added a manual test with instructions.
@hartez I noticed that setting `ItemsSpacing` for `LinearItemsLayout` in XAML did not work, but it seems to be working for `ListItemsLayout` in an earlier Nuget. See #7519.
- fixes #7357
=> [Android] Fix ItemSpacing for last item in CollectionView

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CollectionViewGallery.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs, Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs
When a CollectionView on iOS starts out empty, it doesn't have anything to use as a prototype cell for size estimation. When adding new items later, a measurement is never triggered and the CollectionView gets very confused trying to lay out the items.
This change makes sure the prototype item gets measured when the CollectionView transitions from empty to having items.
- fixes #7472 
- fixes #7548
None
- iOS
None
Not applicable
Control Gallery, CollectionView Gallery -> Observable Collection Galleries -> Add items with timer to Empty Collection.
The items should not overlap or shift as they are added.
=> Make sure transition from empty CollectionView measures cell size

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7525.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7525.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs
Fix CarouselView initial position on Android.
- fixes #7525
None
- Android
None
The carousel has three elements (blue, red and green). Position is set to 1. The correct result must be, see the element with a blue background.
Not applicable
Launch Core Gallery and navigate to the test cases. Open test case 7525. If you see a blue background is working. In other case, the test is failing.
=> [CarouselView] Fix CarouselView initial position on Android

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core.UITests.Shared/Tests/EntryUITests.cs
Occasionally the Entry field doesn't load fast enough for the focus test to read the element. This adds retry logic
- If all the android tests pass for the focus tests then merge
=> Add retry logic for IsFocus test

Xamarin.Forms.Core.UITests.Shared/Tests/CarouselViewUITests.cs, Xamarin.Forms.Core/Items/CarouselView.cs, Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs, Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewController.cs, Xamarin.Forms.Platform.iOS/CollectionView/UICollectionViewDelegator.cs
Comparing the floating point is not easy on the scrollview , this is a better approach to check with a error margin the current item.
- fixes failing uitests on iOS
- fixes #7525 
None
- iOS
- Android
- UWP
None
Not applicable
=> [iOS,Android] Better way to get CurrentItem 

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Core.UITests.Shared/Tests/EntryUITests.cs
The Xamarin UI Tests seem to fail occasionally when trying to clear the app data when restarting the app. The iOS tests already don't clear the data so this tells Android to do the same. 
- Android
=> Set do not clear app data on Xamarin UI Tests

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselViewGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CollectionViewGallery.cs
Sometimes, when I tap the top button to enable the `CollectionView` flag in `CarouselViewGallery` and `CollectionViewGallery`, I miss the tappable area of the button while assuming the button was successfully tapped and so the Gallery crashes on me. The changes here will give us a better visual clue that the tap took place.
=> [iOS] Make button click easier to see when turning on CollectionView flag

Xamarin.Forms.Platform.Android/ResourceManager.cs
Improve Android release/AOT startup performance by lazily loading `ResourceManager` Types.
Made `ResourceManager` types immutable. Seems an oversight they were mutable to begin with. If anyone was using them then I'll retire and serve out the rest of my days drinking Mojito's outta coconuts. 
- Android
None
1% at a time! 
Every UITest is a test.
=> Lazily load ResourceManager types

Xamarin.Forms.Platform.Android/FastRenderers/ImageElementManager.cs, Xamarin.Forms.Platform.Android/Renderers/FontExtensions.cs
- Fixed pathing for how to process fontFamily to use *IsNullOrWhiteSpace* opposed to just checking for null
- moved try catch for image loading fail to more generalized location
Regression caused here https://github.com/xamarin/Xamarin.Forms/pull/6470
- fixes #7598
- fixes #7597
- Android
- create new Xamarin Forms template (MDP or Shell)
- Open the Abouts page and some of the font should be bold
- Change the image on the page to an image path that doesn't exist. The image should disappear but the rest of the page should remain visible
=> Previewer fixes for loading font correctly and catching image load exceptions

Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs
This PR improve startup performance by making the initialization of VisualElement's properties more efficient.
As shown below, the initial update time for VisualElement's properties has been reduced from approximately 10ms to 1.34ms.
_This is the result of testing with the [StopWatch](https://github.com/Samsung/Tizen-CSharp-Samples/tree/master/Wearable/XStopWatch) sample app on [Galaxy Watch Actvie](https://www.samsung.com/global/galaxy/galaxy-watch-active/)._
- Before
- After
None
None
- Tizen
None
Not applicable
Every UITest is a test.
=> [Tizen] Improves the initialization of VE's properties

Xamarin.Forms.ControlGallery.Android/_1909CustomRenderer.cs
FlatButtonRenderer sets the elevation but elevation can only be set on lollipop and up
- UI Tests pass
=> Only set elevation on Lollipop and up for FlatButtonRenderer

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs
Nunit3 changed the test runner directory so we need to account for this
https://github.com/nunit/docs/wiki/Breaking-Changes
- run ui tests on windows locally
- run ui tests on ios locally
- make sure ui tests on appcenter startup
=> Fix android apk path for ui tests

Xamarin.Forms.Controls/XamStore/Views/StorePages.cs, Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs
This fixes a regression with the Hamburger Icon on Android not changing its color based on the *Shell.ForegroundColor*
This also has a breaking change on Android which will also set the color of the ToolBarItems which makes it consistent with how iOS works
Regression caused by: https://github.com/xamarin/Xamarin.Forms/pull/6762
- fixes #7577
- Android
- Open the store gallery and click through the bottom tabs. The Home page and the Games page should have a Black hamburger and ToolBarItem
=> Fix Android foreground coloring on Shell

README.md
Added instructions for running Android UI tests on Windows.
@PureWeen @jfversluis @samhouts When I debug the test project on Windows, [ApkPath](https://github.com/xamarin/Xamarin.Forms/blob/65c6e5f59fa1776566f675d6e2e57e7068adb48e/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs#L19) isn't correct for me. We go 3 folders up from the current directory and append a substring to point to the Apk file, but I noticed my current directory does not point to the solution directory. It points to the Temp folder instead.
```
static IApp InitializeAndroidApp()
{
var directory = Directory.GetCurrentDirectory(); // added this line for testing
var app = ConfigureApp.Android.ApkFile(AppPaths.ApkPath).Debug().StartApp();
if …
```
=> Update Android UI test instructions

Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7035.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7035.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/CollectionView/GridViewLayout.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
Instead of returning a fixed UIEdgeInset.Zero, we now take in account the ItemSpacing so the last item will not be offscreen.
- fixes #7035
None
- iOS
None
Not applicable
Go to the Issue7035 case, if you are able to scroll to the right and the last item is fully visible, this worked!
=> [BUG/iOS] Fixed CollectionView Insets ItemSpacing

Xamarin.Forms.Core/Shell/ShellContent.cs, Xamarin.Forms.Core/Shell/ShellItem.cs, Xamarin.Forms.Core/Shell/ShellSection.cs, Xamarin.Forms.Core/Shell/ShellUriHandler.cs, Xamarin.Forms.Platform.iOS/CollectionView/TemplatedCell.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs
**Several fixes for null checks:**
_ShellContent.cs_ - extra null check
_ShellItem.cs_ - added a check for null, as in the previous parameter.
_ShellSection.cs_ - extra null check
_ShellUriHandler.cs_ - added a check for null, as in the previous code block.
_ShellSectionRenderer.cs_ - added a check for null, as in the previous code block.
_TemplatedCell.cs_ - added a check for null
None
- iOS
- Android
- UWP
None
=> [iOS] Fixes for null check for Shell classes

build/steps/build-windows.yml
Fix for running Android builds on CI Server
=> JavaSDK build path fix for 16.3 CI servers

Xamarin.Forms.Core.UnitTests/BindableObjectUnitTests.cs, Xamarin.Forms.Core/BindableProperty.cs, Xamarin.Forms.Core/ToStringValueConverter.cs
Invoke ToString with the CurrentUICulture when seeting a property of type string
from a non-convertible object.
- fixes #6281
None
Text properties (like Label.Text) will have the object ToString() result instead of staying blank. This is a behavioral change, worth indicating in the release notes, and that's why it's targeted to master, and not 4.3.
Not applicable
=> [C] Invoke ToString while setting string BP

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/RefreshViewTests.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs, Xamarin.Forms.Core/RefreshView.cs, Xamarin.Forms.Platform.Android/Renderers/RefreshViewRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/RefreshViewRenderer.cs
Fixes some issues:
- RefreshCommand doesn't fire if you set IsRefreshing.
- Setting IsRefreshing to False inside RefreshCommand doesn't do anything.
- fixes #7388
None
- iOS
- Android
Setting IsRefreshing to true will execute RefreshCommand (if it exists).
(Same behavior on iOS).
Open Core Gallery and navigate to the Test Cases. Search by "Refresh" and open the RefreshView Tests. Pressing the "Toggle Refresh" button or pulling to refresh must change the IsRefreshing property value.
=> [RefreshView] Fire RefreshCommand setting IsRefreshing

Xamarin.Forms.Core/TypeTypeConverter.cs, Xamarin.Forms.Xaml.UnitTests/AppResources/Colors.xaml, Xamarin.Forms.Xaml.UnitTests/AppResources/CompiledColors.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh7531.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh7531.xaml.cs, Xamarin.Forms.Xaml/HydrationContext.cs, Xamarin.Forms.Xaml/ResourcesLoader.cs, Xamarin.Forms.Xaml/ViewExtensions.cs, Xamarin.Forms.Xaml/XamlLoader.cs, Xamarin.Forms.Xaml/XamlServiceProvider.cs
In case of Xaml-only RD, the rootAssembly is different from the assembly
of the rootType
- fixes #7531
None
None
Not applicable
=> [X] Pass the current assembly to parsing context

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2354.cs
This was most likely fixed by this issue
https://github.com/xamarin/Xamarin.Forms/pull/7431
So I just cleaned up the UI test here a bit to be more deterministic 
- fixes #6773
- Android
- Android UI tests pass
- run Issue2354 and make sure the Presidents load
=> Wait for test to load before scrolling images

Xamarin.Forms.Platform.WPF/FormsTextBox.cs
This change makes `Obfuscate` of `FormsTextBox` null safe.
- fixes #7589 
None
Added:
None
Changed:
None
- Wpf
None
=> Fix NullReferenceException in Obfuscate (#7589)

Xamarin.Forms.Platform.WPF/Extensions/ImageExtensions.cs
It would be nice for wpf-implementations, that the helper ToWindowsImageSourceAsync is public.
- fixes #7445
```C#
public static class ImageExtensions
{
public static Stretch ToStretch(this Aspect aspect) {}
public static async Task<WImageSource> ToWindowsImageSourceAsync(this ImageSource source, CancellationToken cancellationToken = default(CancellationToken)) {}
}
```
None
- WPF
None
Not applicable
=> [Enhancement] Xamarin.Forms.Platform.WPF.ImageExtensions to public

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7395.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs
Fixed a bug changing the **ItemTemplate** dynamically. The change of the Template was not applied or partially when scrolling.
- fixes #7395
None
- Android
None
Launch Core Gallery on Android and navigate to the Issue 7395. Press the buttons and see if the CollectionView ItemTemplate changes.
=> [Android] Fixed issue changing the ItemTemplate on CarouselView

Xamarin.Forms.ControlGallery.Android/Environment.txt, Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj, Xamarin.Forms.ControlGallery.Android/_1909CustomRenderer.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43941.cs, Xamarin.Forms.Core.UITests.Shared/Tests/EntryUITests.cs, azure-pipelines.yml, build.cake, build/provisioning/provisioning.csx, build/steps/build-android.yml, build/steps/build-nuget.yml, build/steps/build-osx.yml, build/steps/build-windows.yml
This PR sets up two paths for provisioning
- Public path all public sdks
- This uses Cake to install the sdks versions desired. I realize we had stepped away from using cake for this and just used inline scripts on the YAML file but I'd really prefer to use cake because of the reduced amount of effort it takes to make it work and for it to work cross platform. For example provisioning android APIs is a lot easier with @Redth 's cake plugins than using command line. Plus with cake it makes it easier if people want to run the provision task from the time line
- Internal path for master branches and alpha testing
- This is the path used when we want to use provisionator and need to install things that we can only access internally. This is the path we will use for our weekly tests against …
=> Setup public and provisionator based provisioning of SDKS

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5354.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5354.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.Android/CollectionView/StructuredItemsViewRenderer.cs, Xamarin.Forms.Platform.iOS/CollectionView/StructuredItemsViewRenderer.cs
If you switch between linear and grid layouts, the view should be updated now. Please note that this does not implement UWP.
- fixes #5354
Run the attached test and switch between item layouts. Verify that the spacing was not lost.
=> [Android/iOS] Handle dynamically switching between item layouts in CollectionView

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7563.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs
Fixes #7563
Screenshot from test (previously crashed):
=> Fix crash on iOS with elements that have Layout Compression and VoiceOver active

Xamarin.Forms.Core/Items/SelectableItemsView.cs, Xamarin.Forms.Platform.Android/CollectionView/SelectableItemsViewRenderer.cs, Xamarin.Forms.Platform.Android/CollectionView/SelectableViewHolder.cs
Fixes a visual error with selection mode changes on Android / CollectionView. There is also a change in `Core`, which I'd like to discuss with the team to decide whether it should be merged or dismissed.
- fixes #6051
Please follow the test steps in #6051. I'll update this section with more detailed instructions if the changes in `SelectableItemsView` are approved.
=> [Android] Remove ripple effect on CollectionView item when SelectionMode is None

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7512.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7512.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/Extensions/FlowDirectionExtensions.cs
I was looking at #7512 and noticed the issue is not a `CollectionView` problem. If you go to `FlowDirection` gallery, you'll see that RTL flow is broken. At the level of `VisualElementRenderer`, flow direction is being applied only to the layout direction. This does not seem to be working for `TextView`. Instead, we could use a different method for that.
- fixes #7512
Run the attached test. Also, go to `FlowDirection` gallery and make sure the labels are aligned properly when you change the flow direction.
=> [Android] Fix FlowDirection for Labels

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2354.cs, Xamarin.Forms.Platform.iOS/Cells/CellRenderer.cs, Xamarin.Forms.Platform.iOS/Cells/CellTableViewCell.cs, Xamarin.Forms.Platform.iOS/Cells/ViewCellRenderer.cs
After the ViewCell has already renderered if the measure of the contents has changed then the ViewCell needs to Invalidate its layout so its view can remeasure. In this case the Image would layout empty with zero width. Once it was loaded it wouldn't cause the UITableCell layout to invalidate so the containing frame would still have a width of zero.
I also added some code to unhook some events on dispose to avoid circular reference memory leak issues
- fixes #6773 
- iOS
- run Issue2354 as all the presidents should load. Scroll the ListView and you they will continue to load
=> Invalidate layout on ViewCell if Measurements change

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7556.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs, build/steps/build-windows.yml
The *TabletMasterDetailRenderer* uses a lot of APIs that were deprecated some time ago and it seems like they all finally stopped working with iOS 13
This updates TabletMasterDetailRenderer to use more current APIs to achieve MasterBehavior
- fixes #7556 
- iOS
- Run through the different settings for MasterBehavior on the included test to make sure everything works
=> Update iOS MDP Tablet Renderer to use current APIS for Master Behavior

Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
There is no way currently to listen to scroll changes in a custom renderer. This PR allows us to override setting a scroll listener so that we can add more complex logic to it if needed.
=> [Android/iOS] Expose CollectionView scroll listener

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselItemsGallery.cs, Xamarin.Forms.Core/Items/CarouselView.cs, Xamarin.Forms.Platform.UAP/CollectionView/CarouselViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/FormsGridView.cs, Xamarin.Forms.Platform.UAP/CollectionView/FormsListView.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewStyles.xaml, Xamarin.Forms.Platform.UAP/CollectionView/SelectableItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/StructuredItemsViewRenderer.cs
The CarouselView on UWP does not display in the EmptyView when it's empty. These changes make the EmptyView work.
- EmptyView does not show in UWP CarouselView
- #7717 
None
- UWP
None
Not applicable
Control Gallery, navigate to CarouselView Gallery -> CarouselView (Items) and tap the "Clear Items" button. The empty view (which says "This is the empty view") should display. Adding an item should make the empty view disappear.
=> [UWP] Make EmptyView work in UWP CarouselView

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6127.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs
Fixed that `ToolbarItem.Order` is taken into account when used in conjunction with Shell on Android.
- fixes #6127
None
- Android
When the `ToolbarItem.Order` property is set to `ToolbarItemOrder.Secondary` when using Shell on Android, nothing would happen. From what I can tell this was simply overlooked. Implemented this functionality so it also works correctly when using Shell.
Before:
After:
I've added Issue6127 to the gallery which has a secondary toolbar item and is using shell. In addition added a automated UI test to verify this
=> Fix use of ToolbarItem.Order on Android Shell

Xamarin.Forms.ControlGallery.WindowsUniversal/CustomSwitchRenderer.cs, Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7253.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.UAP/SwitchRenderer.cs
Fix crash on Switch Renderer when a custom renderer provides Color objects instead of Brush to customize the Switch colors.
Some versions ago we introduced the option to customize the ThumbColor: https://github.com/xamarin/Xamarin.Forms/commit/a21caa53899a541a2763b769af811019a94195e8
It was expected to use a Brush (explicit cast) and in this case, a Color was used in the custom renderer (see #7253). Applied changes to allow the use of Color and/or Brush without problems.
- fixes #7253 
None
- UWP
None
Not applicable
Launch Core Gallery and navigate to the Issue 7253. If a custom Switch is rendered without problems, the test passes.
=> [UWP] Fix crash on Switch Renderer when a custom renderer provides Color objects instead of Brush

Xamarin.Forms.Platform.UAP/WindowsBasePage.cs
Fix a crash (NRE) setting the MainPage using the OnStart method on **UWP**.
Adding support to MultiWindow (#2432), changes were made to `WindowsBasePage`: https://github.com/xamarin/Xamarin.Forms/blob/7a9b54dae9605169f0417c168af2cd81f931b2a9/Xamarin.Forms.Platform.UAP/WindowsBasePage.cs
- fixes #7537
None
- UWP
None
Not applicable
Modify Core Gallery to set the MainPage in the OnStart method. If the sample starts without problems, the fix is valid.
=> [UWP] Fix crash setting the MainPage using the OnStart method

Xamarin.Forms.Platform.Tizen/Native/EditfieldEntry.cs, Xamarin.Forms.Platform.Tizen/Renderers/PickerRenderer.cs
This PR is to fix below issues ocurred on Tizen TV.
- Text is not shown
- There is no changes and effects when the picker has focus
Since these issues are caused by the difference of UI between TV and mobile, this changes will be applied on TV profile only.
- None
- None
- Tizen
The text will grow when the picker has focus.
- Before
- After
=> [Tizen] fix picker focus issue in Tizen TV

Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewRenderer.cs
Fixed error updating dynamically the **NumberOfSideItems** in CarouselView.
Testing for another Issue I have detected this issue!.
None
- iOS
None
Launch CarouselView Core Gallery samples. Then, modify the NumberOfSideItems and check if the Carousel updates correctly.
=> [iOS] Fixed error updating dynamically the NumberOfSideItems in CarouselView.

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7283.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs
Fix an exception (crash) changing the Application MainPage.
_NOTE: I will include the commit where we changed this behavior here. The same was working on 4.1 and it stopped working from 4.2._
- fixes #7283
None
- Android
None
```
{System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
at System.Collections.Generic.List1[T].get_Item (System.Int32 index) [0x00009] in <ff07eae8184a40a08e79049bbcb31a0e>:0 at System.Collections.ObjectModel.Collection1[T].get_Item (System.Int32 index) [0x00000] in :0
at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.RegisterToolbar () [0x0004b] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:646
at …
```
=> [Android] Fix crash changing the Application MainPage

Xamarin.Forms.Platform.iOS/Renderers/RefreshViewRenderer.cs
Just a lil typo fix. `_origininalY` -> `_originalY`
=> Fix typo in RefreshViewRenderer

Xamarin.Forms.Core/UriImageSource.cs, Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj
- If the stream returned from the HttpClient is invalid the code was still creating an empty cache file which would cause subsequent calls to just use an empty file for the image instead of retrying to stream
- If the cached file is empty then don't use it and just retry the remote stream. 
- fixes #7751
- iOS
- Android
- UWP
None
Not applicable
- Download the nuget
- Run this sample https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/workingwithimages/ against 4.1.0.709244 which will load an invalid image into cache
- now rerun the sample with the nuget that's part of this sample
- the image should now load
=> Ignore empty cache and don't cache invalid stream

Xamarin.Forms.Platform.UAP/MasterDetailPageRenderer.cs
Minor spelling mistake. Within UWP MasterDetailPageRenderer.cs
UpdateToolbarVisibilty to UpdateToolbarVisibility
- fixes a small source code spelling mistake
None
- UWP
None
Not applicable
=> Spelling fix

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7758.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7758.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewRenderer.cs
#7794 attempts to use the `CollectionView` frame for properly laying out the empty view. However, the comment in the same block of code mentions `_emptyUIView` is measured properly, which is not the case. 
I have noticed that when `ItemsViewController.UpdateEmptyView()` is called in `ItemsViewRenderer`, `CollectionView` is sized to have the entire screen dimensions. A second call to `UpdateEmptyView()` which happens in ItemsViewController -> NumberOfSections -> CheckForEmptySource uses the correct dimensions.
I moved `UpdateEmptyView()` call into `ViewDidLoad` which fixed the issue.
fixes #7251 and #7758
=> [iOS] Alternative proposal for PR 7794

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6640.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6738.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/Shell/ShellSection.cs, Xamarin.Forms.Platform.Android/AppCompat/ShellFragmentContainer.cs, Xamarin.Forms.Platform.Android/Extensions/FragmentManagerExtensions.cs, Xamarin.Forms.Platform.Android/Renderers/ColorChangeRevealDrawable.cs, Xamarin.Forms.Platform.Android/Renderers/ShellBottomNavViewAppearanceTracker.cs, Xamarin.Forms.Platform.Android/Renderers/ShellContentFragment.cs, Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRecyclerAdapter.cs, Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutTemplatedContentRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/ShellFragmentPagerAdapter.cs, Xamarin.Forms.Platform.Android/Renderers/ShellItemRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/ShellItemRendererBase.cs, Xamarin.Forms.Platform.Android/Renderers/ShellRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/ShellSearchView.cs, Xamarin.Forms.Platform.Android/Renderers/ShellSearchViewAdapter.cs, Xamarin.Forms.Platform.Android/Renderers/ShellSectionRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/ShellTabLayoutAppearanceTracker.cs, Xamarin.Forms.Platform.Android/Renderers/ShellToolbarAppearanceTracker.cs, Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs
This PR takes a set of the changes from this PR https://github.com/xamarin/Xamarin.Forms/pull/6715 but in a slightly more subtle way plus it maintains the OnDestroy calls.
If we merge this version of the  PR then if we feel the other PR still has valid changes than we can rebase that one against master. I'd feel more comfortable with those changes living in master instead of just being pushed to 4.2.0. This PR also only has breaking changes with the removal of some constructors
I tested this PR with Xaminals and I'm not able to reproduce the back button bug
- fixes #6640
- closes #6715
- Android
- use these nugets with xaminals and see if you can cause a dispose exception
- Run the control gallery and try to cause a dispose exception by swapping out the Shell Page or hitting back button …
=> Shell android dispose

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7789.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7789.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewController.cs
Fixed **crash** displaying strings in **CarouselView**. Example:
```
<StackLayout Margin="10">
<CarouselView>
<CarouselView.ItemsSource>
<x:Array Type="{x:Type x:String}">
<x:String>Baboon</x:String>
<x:String>Capuchin Monkey</x:String>
<x:String>Blue Monkey</x:String>
</x:Array>
</CarouselView.ItemsSource>
</CarouselView>
</StackLayout> 
```
The crash was on `DequeueReusableCell` because with the CarouselView we was registering the cell used with template in the Carousel https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewController.cs#L62. However, without template (Example: using strings) the cell expected was not registered: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewCont …
=> [iOS] Fixed crash displaying strings in CarouselView

build.cake
I had to look up what "1" meant in the documentation!
(https://cakebuild.net/api/Cake.Common.Tools.MSBuild/MSBuildPlatform/)
=> build.cake: more readable way of using an enum

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewStringGallery.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/GroupingGalleries/ViewModel.cs, Xamarin.Forms.Platform.UAP/CollectionView/CollectionViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/FormsGridView.cs, Xamarin.Forms.Platform.UAP/CollectionView/FormsListView.cs, Xamarin.Forms.Platform.UAP/CollectionView/GroupFooterItemTemplateContext.cs, Xamarin.Forms.Platform.UAP/CollectionView/GroupHeaderStyleSelector.cs, Xamarin.Forms.Platform.UAP/CollectionView/GroupTemplateContext.cs, Xamarin.Forms.Platform.UAP/CollectionView/GroupableItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/GroupedItemTemplateCollection.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemContentControl.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemTemplateContext.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemTemplateContextList.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewStyles.xaml, Xamarin.Forms.Platform.UAP/CollectionView/StructuredItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/TemplatedItemSourceFactory.cs, Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
Implement grouping for CollectionView on UWP.
Also fixes bug in grid layout where Span was not always honored on UWP.
Known Issues: 
- When using a grid layout, group footers do not span all of the columns. We will address that in a separate PR.
- partially implements #3172
None
- UWP
None
Not applicable
Control Gallery, Navigate to CollectionView Gallery -> Grouping
=> Implement grouping for UWP CollectionView

Xamarin.Forms.Core/Items/LinearItemsLayout.cs
Fixed SnapPointsType discrepancy between CarouselView and LinearItemsLayout.
Also renamed ListItemsLayout to LinearItemsLayout.
- fixes #7876
None
None
Not applicable
Launch Core Gallery and test any CarouselView sample to verify that the snap continues working.
=> [Core] Fixed SnapPointsType discrepancy in CarouselView

Xamarin.Forms.Core/FontImageSource.cs
Allows to use named font size for `FontImageSource.Size` property
- fixes #7664
None
Added:
None
Changed:
- Add `FontSizeConverter` attribute to `Size` property of `FontImagesource`
Removed:
None
- iOS
- Android
- UWP
None
Not applicable
N/A
=> Use FontSizeConverter for FontImageSource.Size property

Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs, Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs, Xamarin.Forms.Core/BindingExpression.cs, Xamarin.Forms.Xaml.UnitTests/Issues/Gh7837.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh7837.xaml.cs, Xamarin.Forms.Xaml.UnitTests/MockCompiler.cs
supports having multiple indexers on a bound source, try to invoke the right one.
- fixes #7837
None
None
Not applicable
=> [X] binding find the right indexer

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6963.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/SelectionGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/SelectionSynchronization.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/SelectionSynchronization.xaml.cs, Xamarin.Forms.Platform.UAP/CollectionView/SelectableItemsViewRenderer.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.iOS/CollectionView/SelectableItemsViewController.cs, Xamarin.Forms.Platform.iOS/CollectionView/SelectableItemsViewRenderer.cs
When the CollectionView `SelectedItem` or `SelectedItems` properties contain items which are not in the `ItemsSource`, the native selection updates on iOS and UWP can crash. These changes prevent the crashes.
- fixes #6963
None
- iOS
- UWP
None
Not applicable
=> [UWP] [iOS] Verify selected items exist when updating native selections

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7817.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7817.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs
Fixed **ItemsUpdatingScrollMode** property on **CarouselView**. 
- fixes #7817
None
- iOS
- Android
None
Launch Core Gallery and navigate to the Issue 7817. Change `ItemsUpdatingScrollMode` using the Picker and check if the Carousel scroll behavior changed.
=> [Android/iOS] Fixed ItemsUpdatingScrollMode on CarouselView

Xamarin.Forms.Platform.UAP/SwitchRenderer.cs
Fixed crash on UWP Switch (UpdateThumbColor). We had some options to get a crash mainly with the use of Linq and First. Small refactoring to avoid this problem.
- fixes #7926
None
- UWP
None
Not applicable
Launch Core Gallery and navigate to the Switch Core sample. Change the ThumbColor and verify that works as expected.
=> Fixed crash on UWP Switch (UpdateThumbColor)

Xamarin.Forms.Platform.UAP/CollectionView/CarouselViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/CollectionViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/GroupableItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/SelectableItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/StructuredItemsViewRenderer.cs
The UWP implementation for CollectionView has some awkward casts and unnecessary local typed references to maintain that can be done more cleanly with generics. These changes clean up the code.
None, just makes the code easier to maintain.
None
- UWP
None
Not applicable
=> Move CollectionView UWP implementation to generics

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7898.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.MacOS/Renderers/NavigationPageRenderer.cs
Added Show-Hide logic for previous page in NavigationPageRenderer
Issue happens when any page with transparency pushed to NavigationPage, because new page simply added to ViewController above previous.
- fixes #7898 
None
- macOS
None
Before
After
=> Fix [macOS] navigation page doesn't hide previous page

Xamarin.Forms.Core.UnitTests/DatePickerUnitTest.cs, Xamarin.Forms.Core/DatePicker.cs
When setting min and maxdate on a date picker to DateTime.Now we get an exception on the value binding of the min date. Due to the fact that the whole DateTime part was being validated.
Since the coerce part of the DatePicker will revert to only the Date part of the given DateTime value, it's best to also convert to only Date in the Validate methods of the DatePicker.
- fixes #5784
Changed:
- return (DateTime)value >= ((DatePicker)bindable).MinimumDate;
- return ((DateTime)value).Date >= ((DatePicker)bindable).MinimumDate;
- return (DateTime)value <= ((DatePicker)bindable).MaximumDate;
- return ((DateTime)value).Date <= ((DatePicker)bindable).MaximumDate;
- iOS
- Android
- UWP
None
Not applicable
=> Validate on Date part only

Stubs/Xamarin.Forms.Platform.cs, Xamarin.Forms.ControlGallery.iOS/PerformanceTrackerRenderer.cs, Xamarin.Forms.ControlGallery.iOS/local.html, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla26993.cs, Xamarin.Forms.Platform.iOS/Properties/AssemblyInfo.cs, Xamarin.Forms.Platform.iOS/Renderers/WebViewRenderer.cs
Deprecates the `WebViewRenderer` for iOS and uses the `WkWebViewRenderer` instead.
No (extra) automated tests were added at this stage, the ones in place should succeeded with this replacement.
To reinstate the current behavior just add the line below to the `AssemblyInfo.cs` file of you iOS project. This will register the `WebViewRenderer` again over the `WkWebViewRenderer`.
`[assembly: ExportRenderer(typeof(Xamarin.Forms.WebView), typeof(Xamarin.Forms.Platform.iOS.WebViewRenderer))]`
- fixes #7323 
None
- iOS
None. Everything should function as before. Users should receive build warnings when they reference the `WebViewRenderer` directly. E.g. when there is a custom renderer in place.
Not applicable
=> Make WkWebViewRenderer default for iOS WebView

Version.targets
On windows when trying to rebuild the unit tests it occasionally fails with "process can't access file". I'm guessing this is from parallel builds writing to the file.  Only one process needs win the race to write the file.
- make sure you can run unit tests
- make changes to core code and rebuild unit tests
- run *build.cmd -Target NugetPack* and make sure it creates Nugets with correct versions
=> Set Continue On Error for task that creates version file in case of parallel builds

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7943.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7943.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/DataChangeObserver.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs
Fixed a crash on CollectionView changing ItemsSource. 
When doing the swap of the Adapter I have added changes to not observe the old DataChangeObservers.
- fixes #7943
None
- Android
None
```
at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in :0
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in :0
at Android.Support.V7.Widget.RecyclerView+Adapter.UnregisterAdapterDataObserver (Android.Support.V7.Widget.RecyclerView+AdapterDataObserver observer) [0x00031] in …
```
=> [Android] Fixed a crash on CollectionView changing ItemsSource

Xamarin.Forms.Platform.UAP/CollectionView/CarouselViewRenderer.cs
Doing rebase at https://github.com/xamarin/Xamarin.Forms/pull/7590 I have noticed that some CarouselVIew properties does not work on UWP:
- NumberOfSideItems
- PeekAreaInsets
- Snap
The regression was possibly introduced in https://github.com/xamarin/Xamarin.Forms/commit/f524502aeee444be12c17e25bf103e0d358763b4#diff-49b633c124c929ea2ab8b63dca84ca3d
This PR fixes this issues.
None
- UWP
None
=> [UWP] CarouselView fixes

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselViewGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/EmptyCarouselGallery.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/EmptyCarouselGallery.xaml.cs
Implement CarouselView EmptyView on Android, iOS and UWP.
Android
iOS
UWP
None
- iOS
- Android
- UWP
None
None
Launch CarouselView Core Gallery and test EmptyView sample. By default, without items you should see EmptyView. Add items and EmptyView should hide.
=> Implement CarouselView EmptyView

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/CollectionViewGroupTypeIssue.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/CollectionView/ObservableGroupedSource.cs
Grouped CollectionView on iOS is doing a direct cast to IList in a couple of places where it shouldn't be. These changes fix that, preventing crashes under certain view model conditions.
- crashes when group types are not IList
None
- iOS
None
Not applicable
=> Fix iOS crash when group type is not an IList

Xamarin.Forms.Platform.MacOS/Renderers/ButtonRenderer.cs
Add support for `Padding` on `Button`. 
Overrides `IntrinsicContentSize` property on `FormsNSButton`. Adds `FormsNSButtonCell` with an overridden `DrawTitle` method. 
This does not do anything with `Button.Image`. Comparing macOS to iOS, there seems to be quite a lot of other functionality missing still, especially to do with images.
- fixes #7851 
None public
- macOS
Previously ignored padding on macOS buttons will now do something.
Before:
After:
View the control gallery for Button and Button Layout
=> [macOS] Add padding to Button

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8008.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/Shell/Shell.cs
If the visible shell item is removed then correctly pick the next visible shell item
This also fixes a Hot Reload issue with Shell
- fixes #8008
- https://devdiv.visualstudio.com/DevDiv/_queries/edit/964986/?triage=true
- Tests are automated
=> Fix shell to correctly pick visible item when currently active Shell Item is removed

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5500.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs
After assigning events to the event handler tied to text changes store it to a local variable. If I don't do this then at some point the Delegate just gets nulled out on the material rendererers when launched to a device
- fixes #5500 
- iOS
- Test included with instructions
- Also test Material Entry and that auto size based on text changes works
=> Fix Material Editor so TextChange delegate isn't removed

Xamarin.Forms.Platform.Android/CollectionView/ObservableGroupedSource.cs, Xamarin.Forms.Platform.Android/CollectionView/ObservableItemsSource.cs
`_notifier` was being assigned twice.
=> [Android] Remove duplicate statement in ObservableItemsSource

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7993.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7993.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs
This PR disposes and resets the existing scroll listener on `RecyclerView` upon items source change so that we no longer report the previous horizontal/vertical offsets.
- fixes #7993
=> [Android] Fix RecyclerView offsets upon items source change

Xamarin.Forms.Material.Android/MaterialPickerRenderer.cs, Xamarin.Forms.Material.iOS/MaterialEntryRenderer.cs, Xamarin.Forms.Material.iOS/MaterialPickerRenderer.cs, Xamarin.Forms.Material.iOS/MaterialTextManager.cs, Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs
Character spacing PR started using the title for the placeholder on picker which we originally weren't going to do but at this point I think it's fine. It's what users will expect if they switch to material
Unfortunately (AFAICT) character spacing doesn't work with place holders on the material controls. I poked iOS a bit and couldn't get it to work. I'm hoping once we update material components on android/ios then maybe it'll work?
- Since we're now using Title I replaced the APIs needed for TitleColor
- I added an override for *UpdateAttributedPlaceHolder* on iOS so that the Material implementations can control this field. It's confusing having the non material control set this. If AttributedPlaceHolder start working for material than the Material control can be updated to handle it …
=> Cleanup material controls character spacing interactions

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7700.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7993.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/CollectionView/GroupableItemsViewController.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsSourceFactory.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs, Xamarin.Forms.Platform.iOS/CollectionView/ListSource.cs, Xamarin.Forms.Platform.iOS/CollectionView/ObservableGroupedSource.cs, Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs
If
- a CollectionView is on a tab that has never been displayed
- the CollectionView's `ItemsSource` implements `INotifyCollectionChanged`
- an item is added to that `ItemsSource`
on iOS 13 a layout error will be raised and the CollectionView will be left in a weird state. Pre-13, it'll just crash.
These changes detect that scenario and avoid the crash.
- fixes #7700
None
- iOS
None
Not applicable
=> [iOS] Prevent crash when adding item to source of CollectionView in tab

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7803.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7803.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7993.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/RefreshViewTests.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core.UnitTests/RefreshViewTests.cs, Xamarin.Forms.Core.UnitTests/Xamarin.Forms.Core.UnitTests.csproj, Xamarin.Forms.Core/RefreshView.cs, Xamarin.Forms.Platform.Android/Renderers/RefreshViewRenderer.cs, Xamarin.Forms.Platform.UAP/RefreshViewRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/RefreshViewRenderer.cs
- The check for disabling the RefreshView based on a command was only firing when CommandParameter was set. This PR aligns Refresh View with how Button logic works with IsEnabled
- Add IsRefreshing event to RefreshView
- Clamp IsRefreshing to false if IsEnabled is false
- I moved the Command execution up into the Cross Platform code (much like the ListView Refresh) because it doesn't seem to make sense to have that code spread out between the renderers. This also fixed #7803 
- fixes #7803
- iOS
- Android
- UWP
Added: 
- RefreshView.IsRefreshing
- Tests are Automated
- Added test buttons to RefreshViewTests. Click around and make sure it all works as you'd expect it to
=> Make the Refresh View Respect Command CanExecute and add Refreshing event

Xamarin.Forms.Platform.MacOS/Renderers/EntryRenderer.cs
Added sanity checks. Checking if renderer is `_disposed` or `Control == null` before updating the accessibility label.
- fixes #5612
None
- macOS
None
Not applicable
Steps to Reproduce
- 1
- Control Gallery
- Accessibility
- back button
- **Should not crash**
- 2
- Control Gallery
- AutomationID Gallery
- Test1
- POP
- **Should not crash**
=> GH-5612 Preventing NRE when disposing controls

Xamarin.Forms.ControlGallery.iOS/CustomRenderers/CustomSearchBarRenderer.cs, Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj, Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs
Reopening https://github.com/xamarin/Xamarin.Forms/pull/846
**Note still not sure if this is the right way to go, how will developers now notice this is the way to override the behaviour? Normally you would do stuff in the OnElementChanged method for custom renderers**
Cancel button can appear unwanted on iOS
Changed:
- object SearchBarRenderer => UpdateCancelButton is now Virtual
- iOS
None
Not applicable
Open the ControlGallery app on iOS simulator. Type text in the middle search bar. Notice the cancel button will appear.
Uncomment the CustomSearchBarRenderer in the ControlGallery.iOS part and now when typing in the search bar will no longer show the cancel button.
=> Make UpdateCancelButton virtual

Xamarin.Forms.Platform.MacOS/Renderers/EntryRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
Sometimes when disposing the EntryRender on macOS SetAccessibilityLabel was throwing a NRE 
Check if Element or Control are null before update
- none
None
- macOS
None
Not applicable
=> [MacOS] FIx against NRE on disposing Entry renderer

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6957.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.WPF/WPFPlatformServices.cs
Fixes issue #6957 "Device.StartTimer() won't fire on WPF if it is executed on Non UI thread" which was caused because the DispatcherTimer was invoked on a "dead" thread by using the current dispatcher instead. Read a bit more about the reason here: https://stackoverflow.com/a/8423977
- fixes #6957
None
- WPF
None
Not applicable
Added test case G6957 to control gallery which starts a timer from main and background thread.
=> Fix bug 6957 Device.StartTimer() won't fire on WPF if it is executed on Non UI thread

Xamarin.Forms.ControlGallery.Android/Resources/values/styles.xml, Xamarin.Forms.Platform.Android/PopupManager.cs
Change from using `Android.App.AlertDialog` to `Android.Support.V7.App.AlertDialog` when creating dialogs for `DisplayAlert`, `DisplayActionSheet`, and `DisplayPromptAsync`. 
Fixes display issues when using a custom alertDialogTheme in your Android app theme inheriting from DayNight while in dark mode.
- fixes #8029
None
- Android
If using a custom alertDialogTheme in your Android application theme, the item name should be changed from `android:alertDialogTheme` to `alertDialogTheme`.
Before:
After:
Run the DisplayAlert Gallery page in Control Gallery app in dark mode on a supported Android device.
Comment out this line to get before/after comparisons:
https://github.com/xamarin/Xamarin.Forms/blob/2dcdc319e13e8d77a1a4644ee76eb432c5be7007/Xamarin.Forms.Platform.Android/PopupManager.cs#L10
=> [Android] Use AppCompat AlertDialog

.gitignore, Version.targets, build.cake
Change XamarinFormsVersionFile to a dot file so it's hidden. 
This file is only used by the CI processes and build scripts 
Generate nugets from cake and make sure the *.XamarinFormsVersionFile* is generated but doesn't try to get added to SC.
Also make sure that nuget files are still generated with valid version numbers
=> Change XamarinFormsVersionFile to a dot file so it's hidden

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7825.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.WPF/Renderers/FrameRenderer.cs
Adds opacity mask to clip nested content
- fixes #7825
None
- WPF
None
Before 
After
=> Fix [WPF] Frame cornerRadius doesn't clip content

Xamarin.Forms.Core.UnitTests/GridTests.cs, Xamarin.Forms.Core/GridCalc.cs
When calculating the MinimumWidth for an auto column the code was incorrectly throwing that value away and just using the actual width for the minimum width.
- fixes #7303 
Given the following XAML
```
<Grid>
<Grid.RowDefinitions>
<RowDefinition />
<RowDefinition />
</Grid.RowDefinitions>
<Grid.ColumnDefinitions>
<ColumnDefinition Width="Auto" />
<ColumnDefinition Width="Auto" />
</Grid.ColumnDefinitions>
<BoxView HorizontalOptions="Start" Grid.Row="0" Grid.Column="0" BackgroundColor="Purple" MinimumWidthRequest="1" WidthRequest="500"></BoxView>
<BoxView HorizontalOptions="Start" Grid.Row="0" Grid.Column="1" BackgroundColor="Green" MinimumWidthRequest="450" WidthRequest="500"></BoxView>
<BoxView HorizontalOptions="Start" Grid.Row="1" Grid.Column="0" …
```
=> Set MinimumWidth to the correctly calculated value for Auto Grid Columns

Xamarin.Forms.Platform.Android/FastRenderers/VisualElementRenderer.cs
Android FastRenderers missed effects detaching on dispose.
Exception occurs here: PlatformEffect.OnDetached (in case you try to interact with Control property)
None
- Android
No ObjectDisposedException for custom effects
Not applicable
https://github.com/AndreiMisiukevich/TouchEffect/issues/24
=> [Android] Unregister effects on dispose

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla31255.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla31602.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla32902.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla34632.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1461.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7556.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/ScreenshotConditionalApp.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Core.UITests.Shared/Tests/Legacy-UnevenListTests.cs, Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs, Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs
- Don't force the Master page closed if it's a split view
- When the conversion was made to the ScreenShotConditionalApp on UITests. A lot of the tests that were testing for iOSApp weren't updated to account for this. 
- Now that *Bugzilla34632Test* is actually running it revealed an issue with rotating the iPad when on a Modal Page and set to SplitOnLandscape
- iOS
- Automated test added
- The following PR https://github.com/xamarin/Duplo/pull/3388 is where this code was introduced. The UI test that's part of that PR runs fine with this code. With that knowledge please perform whatever additional scenario testing you see fit to make sure this doesn't cause a regression
=> Don't force the Master page closed on disappear if it's set to always visible

Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs, Xamarin.Forms.Platform.Android/Resources/values/styles.xml
fixed Android scrollview scrollbar visibility issue.
- fixes #7629
- fixes #8015
- Android
**Before**
**After**
=> [Android] fix android scrollbar visibility issue

Xamarin.Forms.Core.UnitTests/ColorUnitTests.cs, Xamarin.Forms.Core/ColorTypeConverter.cs
Fix bug  #8113 and provide changes in Unit Tests where reproduce the bug.
- fixes #8113 
None
N/A
Not applicable
Run Unit Tests before and after changes in `ColorTypeConverter`
=> Convert HSL(A) with Double from InvariantString

Xamarin.Forms.Material.iOS/MaterialButtonRenderer.cs
Fixed material button background colour change issue.
We were updating the color scheme but ApplyTheme() was never called for the backgroundcolor.
- fixes #5747
- fixes #7002
- iOS
=> [iOS] fix Material button set backgroundcolor method

Xamarin.Forms.Controls/CoreGalleryPages/FrameCoreGalleryPage.cs, Xamarin.Forms.CustomAttributes/TestAttributes.cs, Xamarin.Forms.Platform.MacOS/Renderers/FrameRenderer.cs
- Implements Frame CornerRadius for macOS, currently CornerRadius always set to 5
- Adds CornerRadius property to FrameCoreGalleryPage
None
- macOS
- CornerRadius works
Before
After
open FrameCoreGalleryPage
=> [macOs] implements Frame CornerRadius

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7581.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Maps.UWP/MapRenderer.cs
Fixes #7581 by applying the new region on the next layout cycle when the initial move failed.
- fixes #7581 
None
- UWP
None
Not applicable
@stevechadbourne provided a test case in the issue #7581 which I added to the control gallery issue list.
=> Fix bug 7581 - UWP Map not moving to location when map hidden then shown

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7048.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7048.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.UAP/FormsCheckBoxStyle.xaml
Fixes #7048 
Default MinWidth value for CheckBox was defined as 120 in the CheckBox style on UWP.
Best we set this to the same value as MinHeight, so now both are 32.
- fixes #7048
Changed:
- object FormsCheckBoxStyle.xaml MinWidth property 120 => 32
- UWP
Right padding will be gone.
None
Added Issue7048 to Xamarin Controls test app
=> Set correct MinWidth for CheckBox style

Xamarin.Forms.Core/Interactivity/AttachedCollection.cs, Xamarin.Forms.Core/Style.cs
Styles use WeakReferences to track their targets so that the target BindableObjects can be garbage collected. However, the WeakReferences themselves are never removed from the Style; this means that long-lived Styles (e.g., application-wide styles) can accumulate WeakReferences for the entire lifetime of the application, eventually running out of memory.
These changes check the number of accumulated WeakReferences when a new reference is added; if the number of references is over a threshold, the list of references are scanned and references whose targets have already been collected are removed, allowing them to be garbage collected.
- WeakReference memory leak
None
None
Not applicable
Run a Forms application which 
- uses a global Style 
- creates many …
=> Occasionally clean up WeakReferences in Styles whose targets have been collected

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8148.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.WPF/Renderers/EntryRenderer.cs
Foreground color was applied only if initial entry text is not empty.
Now foreground applies independently from text.
- fixes #8148 
None
- WPF
Native TextBox Foreground color equals to Entry TextColor immediately as you start typing.
Not applicable
Run
=> Fix WPF Entry initial TextColor ignored when typing

Xamarin.Forms.Platform.Android/Renderers/ShellSearchView.cs
In my hacktoberfest-y mood, I grabbed #6291, but was surprised when I could not reproduce it. Digging deeper, I saw that its symptoms were resolved by #6198, and #6291 was actually a duplicate of #6197.
Rather than checking the API level and skipping functionality on older platforms, I thought it would be better to change the implementation to use the v7 support package version of `DrawableWrapper`, which would allow this functionality to be used by all relevant api levels.
- fixes #6291 
- Android
API levels < 23 will now able to take advantage of `ClipDrawableWrapper` / `SetDropDownBackgroundDrawable` in Shell search views.
- Launch the Shell store in the Gallery on a device with api < 23.
- Observe a continued lack of crashing.
=> [Android] Use v7 support libs for DrawableWrapper

Xamarin.Forms.Core.UnitTests/AnimatableKeyTests.cs, Xamarin.Forms.Core.UnitTests/ImageButtonUnitTest.cs
Occasionally these UI Tests are failing and my current working theory is that it's due to the usage of WeakReferences.  
For the AnimatableKey I'm thinking once it switches to the lambda those keys go out of scope and the weakreference is occasionally collected.
- I'm up to about 6 runs of this on CI and they haven't failed yet 🤞
=> Store references to local variable so it's not collected

Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootHeader.cs
Fixes #7416
Moved selecting and deselecting UI apparel code from UICollectionView to UICollectionViewCell.
Original version tried to get hold of the selected and deselected cell inside the UICollectionView. But cells that are 'off screen' will not be returned with the GetCellForItem(indexpath) method ( cfr UIKit docs ).
Hence, better to override the Selected property of the cell itself and update UI properties there.
Changed:
- ShellSectionRootHeader
- iOS
Open the Control Gallery app in the Xamarin.Forms repo, move to the Shell Store root page.
Add multiple top bar items so that several are off screen.
Scroll to the right and select the last one, scroll back to the left and select the first one.
Current version will crash with NULL ref exception in the Deselected method ( but even with …
=> Let UICollectionViewCell handle state itself

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7396.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellInsets.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/Renderers/ShellBottomNavViewAppearanceTracker.cs
Fixes #7396 where tabbar icon/text color was changed when change shell backgroundcolor property
- fixes #7396 
None
- Android
Bottom tabbar icon/text color dont change when shell brackground is setted
- Before
<p align="center">
<kbd>
</kbd>
</p>
- After
<p align="center">
<kbd>
</kbd>
</p>
- Run the issues project, go to "ShellInsets" and click on "Entry Inset" button.
- Add a bottom tab
- Click on "Random Shell Background Color" button
=> Fix Bug 7396 - Shell: Setting Shell.BackgroundColor overrides all colors of TabBar

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellAppearanceChange.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellFlyoutBehavior.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/Shell/IShellSectionController.cs, Xamarin.Forms.Core/Shell/Shell.cs, Xamarin.Forms.Core/Shell/ShellContent.cs, Xamarin.Forms.Core/Shell/ShellSection.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs
Flyout Behavior was being calculated before the Content Page was realized so any attached properties on the Content Page were ignored. This change centralizes SendAppearanceChange calls as well so it's being called from a more correct place opposed to just trying to guess everywhere it should be called
- fixes #7985
- Flyout behavior is automated but you can run UI test and make sure it works as you expect
- I also added a manual Appearance change test you can use to verify appearance changes propagate correctly
=> Fix Flyout behavior so it propagates from templated Content Page once it's created

Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs, Xamarin.Forms.Xaml.UnitTests/Issues/Gh8221.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh8221.xaml.cs
The lovely #7837 is trying to be smarter at identifying which indexer to invoke,
by checking the parametertype. Of course, it wasn't tested on generic types...
So this is definitely a regression, I apologize for it.
- fixes #8221
None
None
Not applicable
=> [X] resolve indexers on generic types

Xamarin.Forms.ControlGallery.Android/FormsAppCompatActivity.cs, Xamarin.Forms.Core/Profiler.cs, Xamarin.Forms.Core/Registrar.cs, Xamarin.Forms.Platform.Android/Forms.cs, Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutTemplatedContentRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/ShellRenderer.cs
The profiler depends on `Profiler.FrameBegin()` being paired with a single `Profiler.FrameEnd()`. This change removes an extra `Profiler.FrameEnd()`. The change also enables the profiler for the gallery which should prevent regressions. 
None
- Android
None
Every android gallery startup tests that the profiler calls are properly paired.
=> Remove extra Profiler.FrameEnd()

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8186.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.UAP/RefreshViewRenderer.cs
Calling RequestRefresh before RefreshControl is part of the visual tree throws an exception. I tested updating to 2.2 of WinU, which got rid of the exception but the visualization still didn't quite work correctly.  It wasn't enough to just trigger it after Loaded either so I Queue it up on the UI thread
- fixes #8186
- UWP
- Automated test included
=> [UWP] Delay RequestRefresh until RefreshControl Loaded

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7556.cs, Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs
Fixed *_masterVisible* to be calculated instead of just depending on Disappear/Appear events. There are a bunch of edge cases where Disappear and Appear aren't called.
The main theme of this code change is to keep the cross platform IsPresented better in lined with the reality of the native code. The way events are thrown are also fairly different between iOS 12 and iOS 13
- iOS
Make sure to run all these tests on iOS 13 and iOS 12 as each platform runs fairly different
- run through Issue7556 and test as many combinations of rotating, pushing modal pages, rotating, and making sure Master button still works
- Test through Bugzilla34632Test and make sure it works as expected
=> Better detection of IsCollapsed state/changes on iPad Master View Controller

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5680.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5680.xaml.cs, Xamarin.Forms.Core/BindableObject.cs
As requested in the issue, Added a new method `CoerceValue` to `BindableObject` which when called, it would force coerce the current value of the property if a coerceCallback is set on the property.
- fixes #5680 
Added:
Below methods are added to `BindableObject.cs` of Xamarin.Forms.Core library:
```
public void CoerceValue(BindableProperty property) => CoerceValue(property, checkAccess: true);
public void CoerceValue(BindablePropertyKey propertyKey)
{
if (propertyKey == null)
throw new ArgumentNullException(nameof(propertyKey));
CoerceValue(propertyKey.BindableProperty, checkAccess: false);
}
void CoerceValue(BindableProperty property, bool checkAccess)
{
if (property == null)
throw new ArgumentNullException(nameof(property));
if (checkAccess && property.IsReadOnly)
throw new …
```
=> Fixed 5680 - [Enhancement] Added method to force value coercion

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8145.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/Renderers/ShellItemRenderer.cs
#7768 added additional disposal of Shell elements. However, the `BottomSheetDialog` created for the `More` menu was already being disposed, and after these changes, we were attempting to dispose it twice, causing an ObjectDispsoedException.
- fixes #8145
None
- Android
None
Not applicable
Automated test is provided.
=> [Android, Shell] Don't double dispose the more sheet

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8198.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Controls/GalleryPages/RefreshViewGalleries/RefreshCarouselViewGallery.xaml, Xamarin.Forms.Controls/GalleryPages/RefreshViewGalleries/RefreshCarouselViewGallery.xaml.cs, Xamarin.Forms.Controls/GalleryPages/RefreshViewGalleries/RefreshCollectionViewGallery.xaml, Xamarin.Forms.Controls/GalleryPages/RefreshViewGalleries/RefreshListViewGallery.xaml, Xamarin.Forms.Controls/GalleryPages/RefreshViewGalleries/RefreshViewGallery.cs, Xamarin.Forms.Controls/GalleryPages/RefreshViewGalleries/RefreshWebViewGallery.xaml, Xamarin.Forms.Controls/GalleryPages/RefreshViewGalleries/RefreshWebViewGallery.xaml.cs, Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj, Xamarin.Forms.Platform.Android/Renderers/RefreshViewRenderer.cs
Fixed issue refreshing CollectionView using ScrollView inside DataTemplate. Changed the validation to raise the refresh (the ScrollY is zero).
_NOTE: I have also added new samples related to RefreshView in CoreGallery. Tested the new samples and the same issue on iOS and is working fine._
- fixes #8198
None
- Android
None
Launch Core Gallery and navigate to the Issue 8198. Scroll the CollectionView to end and try to scroll up again. If the Refresh Indicator does not appear until it reaches the top, the test has passed.
=> [Android] Fixed issue refreshing CollectionView using ScrollView inside DataTemplate

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4854.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.MacOS/Renderers/ScrollViewRenderer.cs
Calculation of Y offset in ScrollViewer is improved. Now visual glitch when exiting the full screen with ScrollViewer is gone.
- fixes #4854
None
- macOS
The app returns to the previous state when exiting the full screen.
Not applicable
Manual tests included in Xamarin.Forms.Controls.Issues: Issue4854
=> [macOS] Visual glitch when exiting the full screen with ScrollViewer

Xamarin.Forms.Platform.Android/Renderers/SearchBarRenderer.cs
Fix a regression caused by #8090 , still checking if this would be a issue in more places.
Basically everything that will be expecting a Context that s inside the ScrollViewer will have check if it's a themewrapper, the is special worrying if people want to grab the activity. 
Check we pass the right context not the wrapper to the underlying controls. 
I m still investigating if other controls will suffer from the same when inside the ScrollView
- fixes broken API19 tests on master
None
- Android
None
Not applicable
You should be able to visit the SearchBar gallery
=> [Android] Make sure we use the right Context

Xamarin.Forms.Controls/CoreGalleryPages/ListViewCoreGalleryPage.cs, Xamarin.Forms.Platform.UAP/Resources.xaml, Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
The default style template for ListViewHeaderItem in UWP has a MinHeight value pointing at ListViewHeaderItemMinHeight. This has a default value of 44 on UWP.
Meaning that if you want a grouped header in Xamarin Forms that is smaller that 44 in height you will still end up with 44! Causing extra white space that is not wanted.
You can override this value in the Resources.xaml. So now it is set to 0, that will force the header to be as heigh as defined in the height requests of the view.
**Note that the original issue was wrongly flagged and closed - after mentioning this it never got back out of triage**
- fixes #3959
Changed:
- object Resources.xaml => added ListViewHeaderItemMinHeight
- UWP
Potentially grouped listviews in UWP will now have a smaller header.
Run the gallery app and …
=> Add ListViewHeaderItemMinHeight override in UWP resources.xaml

Xamarin.Forms.ControlGallery.iOS/Info.plist, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla31255.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla31602.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla32902.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla34632.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Helpers/UITestHelper.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1461.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7556.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/ScreenshotConditionalApp.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core.UITests.Shared/Tests/Legacy-UnevenListTests.cs, Xamarin.Forms.Core.UITests.Shared/Utilities/AppExtensions.cs, Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs
Cherry pick of
https://github.com/xamarin/Xamarin.Forms/pull/8164
https://github.com/xamarin/Xamarin.Forms/pull/8181
- Same as test procedures on above PRs
=> Cherry pick of iOS13 fixes for iPad

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1666.cs, Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs
The `WKWebViewRenderer` was not following links that had the `target=_blank` attribute, this PR fixes that.
- fixes #8028
None
- iOS
None
Not applicable
In Issue1666 I've added a link with `target=_blank`. Before this fix, nothing would happen, now it opens the link like any other.
=> WKWebView opens target=_blank links

Xamarin.Forms.Platform.MacOS/Renderers/EntryRenderer.cs
Implement `HorizontalTextAlignmentPlaceholder` on macOS. This is not a standalone property but rather applies the general entry horizontal text alignment for the placeholder.
I'm currently looking into implementing vertical text alignment as well which is neither implemented for the text or placeholder.
Implementing missing property for platform.
None
- macOS
None
**Before:** Horizontal alignment did not apply on placeholders
**After:** 
Start:
Horizontal:
End:
Testable in control gallery
=> [macOS] Implement entry placeholder text alignment

Xamarin.Forms.ControlGallery.iOS/CustomRenderers.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5830.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/Cells/EntryCellRenderer.cs
As mentioned in the ticket #5830, updated access modifier for `EntryCellTableViewCell` to allow for further customization from platform-specific renderers.
- fixes #5830
Changed:
- `class EntryCellTableViewCell : CellTableViewCell` => `public class EntryCellTableViewCell : CellTableViewCell`
- iOS
None
Not applicable
- Just run `Issue5830.cs` from Control Gallery. On iOS, if the Entry Cell displays 'Text from Custom Entry Cell' in 'Red' color, this test has passed.
Please Note: I don't have iOS setup so I'd need help from someone from Xamarin Team to review the above test on iOS. I've tested it on Android device and the page loads fine with the Text set (except the TextColor as Red which is only implemented in iOS custom renderer). I've implemented all the required changes (including …
=> Fixed 5830 - [Enhancement] EntryCellTableViewCell should be public

Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewLayout.cs, Xamarin.Forms.Platform.iOS/CollectionView/GridViewLayout.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs, Xamarin.Forms.Platform.iOS/CollectionView/ListViewLayout.cs
There is no way to inherit from the existing `ItemsViewLayout` implementations, so custom renderers are forced to derive from `ItemsViewLayout` directly. Also changed the accessibility of the constructor for `ItemsViewController`.
=> [iOS] Make ItemsViewLayout implementations accessible

Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
When selecting an item from the List, we need to validate if it's a value type or not. Because KeyValuePair sources won't allow == or != operators, we need to use .Equals().
- fixes #8278
Changed:
- object ListViewRenderer.OnControlSelectionChanged => areEqual check
- UWP
None
Not applicable
In the ListViewCore gallery page, changed the ItemsSource to List<KeyValuePair>. You will notice a stack overflow exception when selecting 1 element in the list.
After the fix, it will just select the item and don't crash.
=> Check for ValueType items to perform equals

Xamarin.Forms.Platform.Android/Anticipator.cs, Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs, Xamarin.Forms.Platform.Android/Forms.cs
Use a thread pool to anticipate calls into the Android OS that the UIThread will make during startup; Use a thread pool thread to race ahead of the UIThread to place calls and cache results to remove that burden from the UIThread and thereby speedup startup.
Calling into the Android OS off the UIThread is a "gray" operation. We know to only modify the UI on the UIThread but what about getting the SDK version? The latter is likely ok and this change demonstrates how that type of call would be made. The particular anticipation in this PR is unlikely to speedup startup by an appreciable degree. That's not the point of the this PR. This PR is meant to demonstrate the pattern for future anticipations.
Doing any work off the UIThread at startup makes the startup code re-entrant. It would be a …
=> Anticipate calls into Android OS during startup

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2271.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs
ScrollView.ScrollToAsync now correctly scrolls to the end on iOS.
- fixes #2271
None
- iOS 
None
Not applicable
Added issue 2271 to control gallery
=> [iOS] Fix scroll to does not scroll to end

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8167.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.UAP/Dispatcher.cs, Xamarin.Forms.Platform.UAP/DispatcherProvider.cs
Off-main-thread binding updates can cause errors/crashes on UWP after some changes which were made in the last two releases.
These changes allow the DispatcherProvider to find the correct dispatcher based on the BindableObject being updated, or, failing that, fall back to the fallback Dispatcher.
- fixes #8167
None
- UWP
None
Not applicable
Automated test added; for UWP, manually run the test for Issue 8167.
=> Prevent UWP error/crash when updating binding off the main thread

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8200.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/ItemsSourceFactory.cs, Xamarin.Forms.Platform.Android/CollectionView/ObservableItemsSource.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsSourceFactory.cs, Xamarin.Forms.Platform.iOS/CollectionView/ObservableGroupedSource.cs, Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs
Fix crash using an object that implements `IEnumerable` and `INotifyCollectionChanged`.
Initially, I only made changes to `ItemsSourceFactory` to use `ListSource` in this case. This would prevent the crash, however, we would ignore `INotifyCollectionChanged`. For that reason, I made changes also in `ObservableItemsSource` (on Android too) to use IEnumerable. In this way, we guarantee the use of IList (have IEnumerable as base class) and IEnumerable.
- fixes #8200
None
- iOS
- Android
None
The app crashes with a NullReferenceException
Launch Core Gallery and navigate to the Issue 8200. If the CollectionView appear with items, the test pass.
=> [iOS] Fix crash using an object that implements IEnumerable and INotifyCollectionChanged

Xamarin.Forms.Controls/XamStore/StoreShell.xaml, Xamarin.Forms.Platform.UAP/Shell/ShellItemRenderer.cs
This PR adds support for icon fonts in bottom tab bar.
First commit:
Illustrates the problem, adds test case for validation to XamStore
Second commit:
Implements support for FontImageSource in class Xamarin.Forms.Platform.UWP.ShellItemRenderer
- fixes #
None
- UWP
None
Before (apply first commit):
After:
Apply first commit and open XamStore Demo project. This commits changes the icon from a png file to icon font. As a result, the Home icon in the bottom tab bar is missing.
Apply second commit, build and run XamStore Demo again. This commit adds code to handle FontImageSource in Xamarin.Forms.Platform.UWP.ShellItemRenderer class.
Side note:
there is an exception thrown in [XamStore.xaml](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Controls/XamStore/StoreShell.xaml) …
=> [UWP] Enables usage of font image source for bottom bar tabs

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8269.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/ItemsSourceFactory.cs
Adds a missing null check before trying to create a grouped data source out of a null ItemsSource.
- fixes #8269
None
- Android
None
Not applicable
Automated test
=> Add missing null check on ItemsSource when IsGrouped is true

Xamarin.Forms.Controls/CoreGalleryPages/LabelCoreGalleryPage.cs, Xamarin.Forms.CustomAttributes/TestAttributes.cs, Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
Specify explicit StringEncoding when creating attributed text from HTML on iOS and macOS.
Also updated the control gallery to demonstrate the other iOS HTML bugs.
- fixes #8156 
None
- iOS
- macOS
Text outside the ASCII range, assumed to be UTF-8 will now display correctly.
Control gallery label page.
=> [iOS] [macOS] Fix HTML string encoding

Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs
iOS FrameRenderer.SetupLayer is now made virtual so users have more control over it
- fixes #7667
Changed:
- private void FrameRenderer.SetupLayer()  => public virtual FrameRenderer.SetupLayer()
- iOS
None, but allows users to override the behavior
Not applicable
=> Make iOS FrameRenderer.SetupLayer virtual

Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs, Xamarin.Forms.Platform.Android/FormsApplicationActivity.cs
Added code to track if the Power Save Mode Broadcast Receiver is registered before unregistering it, which results in an NRE.
I haven't been able to reproduce the actual NRE unfortunately, but I think this should prevent it. In any case, it doesn't hurt.
- fixes #6903
None
- Android
No more NRE when the activity is paused and fails to unregister a not registered power save mode receiver
Not applicable
If you find one, please let me know!
=> Fix NRE in OnPause unregister not-registered broadcast receiver

Xamarin.Forms.Controls/GalleryPages/CharacterSpacingGallery.xaml, Xamarin.Forms.Controls/GalleryPages/CharacterSpacingGallery.xaml.cs, Xamarin.Forms.Platform.MacOS/Extensions/NSAttributedStringExtensions.cs, Xamarin.Forms.Platform.MacOS/Renderers/ButtonRenderer.cs, Xamarin.Forms.Platform.MacOS/Xamarin.Forms.Platform.macOS.csproj, Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
Implements character spacing for button and label on macOS.
I had planned to add character spacing to everything, but encountered issues.
Doing the obvious straightforward thing for DatePicker and TimePicker did nothing.
Doing the obvious straightforward thing for Entry, Editor and SearchBar worked, until the value was edited, which reset the spacing.
Something more will need to be done, possibly with custom Cells.
None
- macOS
Character spacing on macOS is now implemented for Button and Label.
There is a character spacing gallery page. I added color pickers to change the text color and placeholder color (currently irrelevant) to make sure the spacing changes play nicely with color changes.
=> [macOS] Add character spacing to button and label

Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs, Xamarin.Forms.ControlGallery.Android/Issue7249SwitchRenderer.cs, Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7249.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/AppCompat/SwitchRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/SwitchRenderer.cs
Fix **Switch Thumb wrong color on Android**. We introduce an option to change the ThumbColor here https://github.com/xamarin/Xamarin.Forms/pull/6798
We save in a variable the color of the Thumb https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/SwitchRenderer.cs#L87 and use it if ThumbColor is not set https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/SwitchRenderer.cs#L141
The problem is that the default Thumb color is different if the switch is Checked or not (white or pink respectively). Applied changes to set the color of the ThumbColor only when it is not Color.Default. 
- fixes #7249
None
- Android
None
=> [Android] Fix Switch Thumb wrong color

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7181.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs
I've created `ShellToolbarTracker.OnToolbarItemPropertyChanged` to get changes from `ToolbarItem.PropertyChanged` and update view
- fixes #7181
None
- Android
ToolbarItem Text and Icons will be updated, when a new value set, on a shell page.
- Before
<p align="center">
<kbd>
</kbd>
</p>
- After 
<p align="center">
<kbd>
</kbd>
</p>
1. Created Shell application with ContentPage
2. Set OnClicked events of the ToolbarItem, to change the Text property
3. Toolbaritem Text will change
> Or just run the Issue7181 test from ControlGallery
=> Fix 7181 | [Bug] Cannot update ToolbarItem text and icon

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4606.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Material.Android/MaterialButtonRenderer.cs, Xamarin.Forms.Platform.Android/AppCompat/ImageButtonRenderer.cs, Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/BorderDrawable.cs
Clip button and image button so if the user specifies a corner radius the image will get clipped as well.
This is how iOS and UWP already work
- fixes #4606
- Android
```XAML
<StackLayout>
<StackLayout Orientation="Horizontal">
<ImageButton BorderWidth="2" BorderColor="Blue" WidthRequest="50" CornerRadius="25" Source="coffee.png" BackgroundColor="Purple"  />
<ImageButton BorderWidth="2" BorderColor="Blue" WidthRequest="50" CornerRadius="25" Source="coffee.png" BackgroundColor="Purple"  />
</StackLayout>
<StackLayout Orientation="Horizontal" Visual="Material">
<ImageButton BorderWidth="2" BorderColor="Blue" WidthRequest="50" CornerRadius="25" Source="coffee.png" BackgroundColor="Purple"  />
<ImageButton BorderWidth="2" BorderColor="Blue" WidthRequest="50" CornerRadius="25" …
```
=> Fix corner clipping on ImageButton and Button (FR)

Xamarin.Forms.Platform.Android/Renderers/BottomNavigationViewUtils.cs
Make sure we don't use new API for setting Colors, so it won't fail on API19 devices.
- fixes filing test 8145 
None
- Android
Should not crash
Not applicable
Check 8145 on Android API19
=> [Android] Fix API usage on Android19 

Xamarin.Forms.Core.UnitTests/ShellLifeCycleTests.cs, Xamarin.Forms.Core.UnitTests/ShellTestBase.cs, Xamarin.Forms.Core/Shell/ShellContent.cs, Xamarin.Forms.Core/Shell/ShellSection.cs
Certain execution paths would cause OnAppearing to fire before ParentSet. 
This makes adding behavior to OnAppearing difficult because you never know if the Parent is going to be set or not
ParentSet is now consistently fired before OnAppearing so there's a slight behavior change for scenarios where they were reversed
- tests included
=> With Shell ensure that ParentSet fires before OnAppearing

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6713.cs, Xamarin.Forms.Core/Page.cs, Xamarin.Forms.Core/PromptArguments.cs, Xamarin.Forms.Platform.Android/PopupManager.cs, Xamarin.Forms.Platform.iOS/Platform.cs
Allows you to add a predefined value to be set whenever a prompt is opened
- fixes #8346
Changed:
- `Xamarin.Forms.Internals.PromptArguments(string title, string message, string accept = "OK", string cancel = "Cancel", string placeholder = null, int maxLength = -1, Keyboard keyboard = default(Keyboard), string initialValue = "")` (added `initialValue`)
-  `Xamarin.Forms.Page.DisplayPromptAsync(string title, string message, string accept = "OK", string cancel = "Cancel", string placeholder = null, int maxLength = -1, Keyboard keyboard = default(Keyboard), string initialValue = "")` (added `initialValue`)
Deprecated:
- `Xamarin.Forms.Internals.PromptArguments(string title, string message, string accept = "OK", string cancel = "Cancel", string placeholder = null, int maxLength = -1, Keyboard …
=> [C] Added ability to predefine value to prompt

Xamarin.Forms.Controls/GalleryPages/ListPage.cs, Xamarin.Forms.Core/ListView.cs
[Bug] WPF ListViewRenderer fails on item tapped with empty item source #7995
- fixes #7995 
Changed:
- ListView.NotifyRowTapped - check ItemsSource contains search index
- iOS
- Android
- UWP
- WPF
- GTK
None
Not applicable
Execute ControlGallery WPF, open ListView Gallery - Legacy ->Press Clear items -> MouseClick on ListView
=> [Bug] WPF ListViewRenderer fails on item tapped with empty item source #7995

Xamarin.Forms.Core.Design/toolbox/Xamarin.Forms.toolbox.xml
The user does not need to specify an empty `ItemSource` attribute when adding a new item from toolbox.
None
- toolbox in VS
None
Not applicable
=> [previewer] removed empty ItemsSource attribute from toolbox snippets

.nuspec/Xamarin.Forms.nuspec, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8177.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.UAP/FormsComboBox.cs, Xamarin.Forms.Platform.UAP/PickerRenderer.cs, Xamarin.Forms.Platform.UAP/PickerStyle.xaml, Xamarin.Forms.Platform.UAP/Resources.xaml, Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
The PR to introduce the character spacing property broke the UWP Picker - item source updates no longer worked. 
These changes are a re-implementation of character spacing for the Picker on UWP with allows the items source to be updated.
- fixes #8177
- fixes #8333 
- fixed #8307
- fixes part of #8395 
None
- UWP
None
Not applicable
Issue 8177 in Control Gallery.
=> Make character spacing work for UWP Picker without breaking ItemsSource

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7385.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.UAP/VisualElementTracker.cs
When all translations/rotations/scaling is set to zero on a VisualElement, the RenderTransform of the element is set to null. 
- fixes #7385 
None
- UWP
None
Before fix, clicking the 3 buttons in succession:
After fix:
No UI test added (don't know how to do that), but test case showing the issue was added as part of this PR
=> Reset transformation properly on UWP (#7385)

Xamarin.Forms.Platform.Tizen/Properties/AssemblyInfo.cs
This PR just adds the missing `SwipeGestureHandler` registration. See #2727 for implementation.
- fixes #
None
- Tizen
Run ControlGallery - SwipeGesture Gallery
=> [Tizen] Enables SwipeGestureHandler

Version.targets, azure-pipelines.yml
Fix version numbers to ship nugets from YAML
Add counters for old releases with counters starting with existing release numbers
Allows us to drop legacy build pipeline and just use yaml builds.
None
- iOS
- Android
- UWP
None
Not applicable
=> [Build] Update version numbers to ship from yaml

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7361.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.UAP/StepperControl.cs
The UWP StepperControl maintains an internal state for whether the + and - buttons are disabled. But if a button is disabled more than once, a cache of the button's previous state is overwritten, and now holds the disabled state - and therefore never becomes properly disabled, when it should be reset to enabled. This change prevents the buttons from being disabled more than once.
- fixes #7361
None
- UWP
Steppers should now work as expected. (It also did in most use cases, already.)
Not applicable
Go to Test Page 7361
Move Slider to theextreme right. Check that the Stepper + button become disabled.
Move Slider to Center. Check that the Stepper + button becomes enabled again.
Move Slider to Extreme left. Checkt that the Stepper - button becomes disabled.
Move Slider to Center. Check the …
=> Fix 7361 - [UWP] Stepper buttons not becoming enabled again, when disabled more than once.

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8366.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/Items/ItemsView.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs
The CollectionView on UWP doens't actually need any of the packager features, and the packager is "helpfully" adding all of the templated items to the root container, which means they all show up clumped at the top. 
This is basically the same thing as #8189, just for UWP instead of iOS.
- fixes #8366
None
- UWP
None
Not applicable
Control Gallery -> Issue 8366. No automated test, since UI Test doesn't have a `WaitForNoGarbledMess()` method.
=> Disable packager for CollectionView on UWP

Xamarin.Forms.Platform.UAP/TabbedPageRenderer.cs
With the introduction of page icon images inside UWP tabs, the code will not check if an actual data source for the image is given.
So the labels of the tabs are pushed down even if this is not needed...
- fixes #6757
Changed:
- object TabbedPageRenderer => Added DataContext check
- UWP
Tabbar labels are again centered if no image is above them.
Run the Controls gallery app before the PR, click SwapRoot - TabbedPage
Run the same procedure again after the PR to see visual change
=> Keep tab image collapsed if no datasource is available

Xamarin.Forms.ControlGallery.iOS/PerformanceTrackerRenderer.cs, Xamarin.Forms.Core.UITests.Shared/PlatformQueries.cs, Xamarin.Forms.Core.UITests.Shared/Utilities/ParsingUtils.cs
Work around change in behavior with how *Layer.Transform* is being exported to UI Tests
- iOS
- UI tests pass
=> Add export method for transform string on UI Tests

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8417.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8417.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/DataChangeObserver.cs
Fixed a crash in CarouselView using EmptyView assigning ItemsSource with delay and navigating back.
Avoid unregister an `AdapterDataObserver` if the adapter has changed.
- fixes #8417
None
- Android
None
Launch Core Gallery and navigate to the Issue 81417. Wait for the items to appear and hit the on screen back button. If navigate back without crash, the test passes.
=> [Android] Fix crash using the CarouselView and EmptyView

Xamarin.Forms.Platform.iOS/Renderers/IShellSectionRootHeader.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootHeader.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootRenderer.cs, Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
This PR provides overrides at every level when creating the top tabs on iOS which allows developers to inject themselves into any point
- They can replace the entire UICollectionView used
- They can replace the type of Cell used inside the UICollectionView
- fixes #7808
- fixes #8428
Added:
- public interface IShellSectionRootHeader 
- adds the ability to abstract top tabs View
- public IShellSectionRootHeader  ShellSectionRenderer.CreateShellSectionRootRenderer
- Allows users to provide inherited implementation of UICollectionView used for top tabs
- public Type ShellSectionRootHeader.GetCellType
- Allows users to specify a custom cell type for the header
- iOS
- Make sure I didn't break any existing behavior. UI tests should cover it
The following example sizes all the cells so they …
=> Add virtual methods for all the layers required to create the top tabs on iOS

Xamarin.Forms.Platform.iOS/CollectionView/HorizontalTemplatedHeaderView.cs, Xamarin.Forms.Platform.iOS/CollectionView/VerticalSupplementaryView.cs
Navigating away from a page with a grouped CollectionView can cause a NullReferenceException on iOS 10 when it tries to do a final measurement. 
This change adds a null check to prevent the exception.
- Failing tests on 4.4.0 CI 
None
- iOS
None
Not applicable
Covered by CollectionView grouping automated tests
=> Fix NRE when navigating away from grouped CollectionView on iOS 10

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7329.cs
UI Test 7329 occasionally fails because it scrolls past the value it's looking for. This slows down the scroll and then also retries it if the scroll fails just in case it's now scrolling too slow
- iOS
- Android
- UWP
- UI tests for 7329 all pass on iOS and Android
=> Slow down gesture scroll for UI test and let it retry

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6362.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootHeader.cs
- cherry pick https://github.com/xamarin/Xamarin.Forms/pull/7884 which fixes a bug
- make sure to set the Selected/UnSelected color on the HeaderCell so it can toggle when Selected changes
- fixes #6362
- iOS
- follow instructions on UI Test
=> [iOS] Fix top tab highlighting

Xamarin.Forms.Core.UnitTests/CarouselViewTests.cs, Xamarin.Forms.Core/Items/CarouselView.cs, Xamarin.Forms.Core/Items/ItemSizingStrategy.cs, Xamarin.Forms.Core/Items/ItemsView.cs, Xamarin.Forms.Core/Items/StructuredItemsView.cs, Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewAdapter.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.Android/CollectionView/StructuredItemsViewAdapter.cs, Xamarin.Forms.Platform.Android/CollectionView/StructuredItemsViewRenderer.cs, Xamarin.Forms.Platform.Tizen/Renderers/ItemsViewRenderer.cs, Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewLayout.cs, Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewRenderer.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.iOS/CollectionView/StructuredItemsViewRenderer.cs
CarouselView doesn't use it, and `None` doesn't make any sense for the CollectionView.
Confusion
Removed:
- ItemsView.ItemSizingStrategy { get; set; }
Added:
- StructuredItemsView.ItemSizingStrategy { get; set; }
- iOS
- Android
- UWP
None
Not applicable
=> Remove ItemSizingStrategy from CarouselView

Xamarin.Forms.Core.UnitTests/RelativeSourceBindingTests.cs, Xamarin.Forms.Core/Binding.cs, Xamarin.Forms.Core/BindingExpression.cs
See #8450 which describes two issues left over from the original inclusion of the feature in #4375 
Fixes #8450 
None
All
`FindAncestorBindingContext` mode will function correctly with `BindingContext` changes and reparenting. 
`AncestorLevel` will function in accordance with the documentation.
Unit tests for this feature have been revised.
=> RelativeSource Binding Bug Fixes (Gh8450)

Xamarin.Forms.Platform.GTK/Controls/EntryWrapper.cs, Xamarin.Forms.Platform.GTK/Controls/ScrolledTextView.cs, Xamarin.Forms.Platform.GTK/Renderers/ButtonRenderer.cs, Xamarin.Forms.Platform.GTK/Renderers/LabelRenderer.cs
Fix for #4880 -Text not shown as it should Xamarin.Forms.GTK.
Text were being encoded twice, once when they were assigned to Span, and once in`GenerateMarkupText()` method.
- fixes #4880
N/A
Added:
NA
Changed:
-  _placeholder.Text = GLib.Markup.EscapeText(value ?? string.Empty) => _placeholder.Text = value ?? string.Empty;
- Text = GLib.Markup.EscapeText(Element.Text ?? string.Empty) => Text = Element.Text ?? string.Empty
Removed:
None
- GTK
XML/HTML special characters now display correctly.
Before:
After:
Not applicable
There isn't a UITest for the GTK platform yet. So I manually tested the changes by adding known special characters & ' - to one of the labels in the controls projects.
=> [p/gtk]Fix for #4880 -Text not shown as it should Xamarin.Forms.GTK

Xamarin.Forms.Core/CheckBox.cs
avoid calling ChangeVisualState from both the property setter and the BP.Propertychanged
thx @techduggu https://github.com/xamarin/Xamarin.Forms/pull/8271#discussion_r342489591 for pointing this out
/
None
Not applicable
=> [C] avoid calling ChangeVisualState twice

Xamarin.Forms.Platform.UAP/MasterDetailControlStyle.xaml, Xamarin.Forms.Platform.UAP/Resources.xaml
Added correct height for the `CommandBar` to make it use the full height again.
Looks like we've hit this issue on the UWP side: https://github.com/microsoft/microsoft-ui-xaml/issues/275
They decided to just leave it like this, so I implemented the suggested fix from this issue which works.
- fixes #5661
None
- UWP
None
Add/remove this change and go to the Bugzilla 44453 issue in the Gallery app to verify
=> [UWP] Fix MDP Button "Padding" issue

Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs
The fix from #4433 was not applied in the fast renderer. This PR implements the same fix for the fast renderer.
- fixes #7019
None
- Android (FR)
While in other areas there might be some wrong measurements, in this specific case it was when a `Label` was used in the title view. When navigating to a second page with a title view that contains a `Label` it would not show. Now it does.
Unfortunately, I could only repro this by hooking up the repro project to the Sandbox, so if you really want to see it in action you should probably do the same. Or take the Nuget from this PR, install that on the repro project and notice that it now works.
=> [Android] Fix Label size when using Hint text (FR)

Xamarin.Forms.ControlGallery.WPF/Renderers/Issue6693ControlRenderer.cs, Xamarin.Forms.ControlGallery.WPF/Xamarin.Forms.ControlGallery.WPF.csproj, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6693.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6693.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.WPF/Renderers/ViewRenderer.cs, Xamarin.Forms.Platform.WPF/Xamarin.Forms.Platform.WPF.csproj
Refactored ViewRenderer to use Control, which is the TNativeElement where T is FrameworkElement. This replaces the use of _wcontrol (System.Windows.Controls.Control) which was preventing FrameworkElement derived controls' IsEnabled property from working.
Fixes #6693 
None
WPF
None
Not applicable
Added Issue6693.xaml page as well as Issue6693Control with WPF renderer to demonstrate issue fix. Undo changes to ViewRenderer to see issue.
=> Fix 6693 - [Bug] [WPF] ViewRenderer does not work properly with FrameworkElement derived native controls

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1704.cs, Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj
The GIF PR uses an API that isn't on UAP14393 so this just adds an if def to use a different one when compiling for UAP instead of NS
This isn't the 100 percent complete fix but for now it gets UWP back to compiling
Second PR incoming
- pull down branch and make sure UWP CG compiles and something that's not UWP CG compiles
- pull down branch and make sure UWP UI tests compile and something that's not UWP UI tests compiles
=> Fix threadpool call when compiling for 14393

.gitignore, Version.targets
build.cake was synced with master on 4.3 meaning Version.targets needs to be synced as well so that nugets can be generated locally
This also adds *XamarinFormsVersionFile* to gitignore which is useful when switching branches
- generate nugets locally
=> Fix generating nugets on 4.3 branch

Xamarin.Forms.Platform.Tizen/Forms.cs, Xamarin.Forms.Platform.Tizen/GestureDetector.cs, Xamarin.Forms.Platform.Tizen/Native/Image.cs, Xamarin.Forms.Platform.Tizen/Native/ListView.cs, Xamarin.Forms.Platform.Tizen/Platform.cs, Xamarin.Forms.Platform.Tizen/StaticRegistrar.cs, Xamarin.Forms.Platform.Tizen/TizenPlatformServices.cs
This PR introduce a static registrar for improving startup performance for Tizen. As we analyzed various Tizen apps, we found that in most cases they used the default handlers defined in the Xamarin.Forms assembly (e.g. `Xamarin.Forms.Platform.Tizen.dll`) and that the cost of registering the default handler through reflection at runtime is quite expensive (about `100~130ms` in Galaxy Watch environment).
The user has three strategies to choose from when initializing:
- None (Default)
- Do not use `StaticRegistrar`. If you don't make any settings, nothing will change.
- StaticRegistrarOnly
- Use `StaticRegistrar` only. In this case, we use the predefined default handlers statically, without doing any reflection to find the handlers.
- All
- Use `StaticRegistrar` and internal registers …
=> [Tizen] Provides Static Registrar

Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
Currently AndroidManifest.xml is set to *TransformFile* but that's not correct. If you create any new android projects you'll see it's just set to *None*
Having it set to *TransformFile* is causing issues with VS 16.3 and opening the file. 
- Android
- make sure the gallery runs and settings inside AndroidManifest file are being used
=> Change build type on AndroidManifest.XML inside  ControlGallery

Xamarin.Forms.Platform.MacOS/Renderers/SliderRenderer.cs
Adds implementation for `MinimumTrackColorProperty`, `MaximumTrackColorProperty` and `ThumbColorProperty` for macOS.
Missing platform implementation
None
- macOS
macOS now reflects values of this property or uses the default value if a color is default.
Default:
Thumb color set:
Min color set:
Max color set:
Slider control in control gallery
=> [macOS] Implement slider min/max/thumb color

Xamarin.Forms.Platform.Android/AppCompat/Platform.cs, Xamarin.Forms.Platform.Android/Platform.cs
Added some defensive code to prevent an NRE.
Targets 4.3 since it is a regression since 3.4 apparently.
This fix has been proposed a couple of times before but was never implemented. For instance because of what @hartez mentions here: https://github.com/xamarin/Xamarin.Forms/issues/4715#issuecomment-449056787
> There's no check there because a nav model with no elements in it shouldn't be handling a back button press in the first place. So somehow we're getting into an invalid navigation state. You mention that you do some navigation when the app goes to sleep - do you handle Resume at all?
While I do agree, on the other hand I also see no harm in adding it this way to prevent the NRE. But I'm basically opening this PR to get some discussion going around this.
Since no one is able to …
=> [AND] Fix NRE in OnBackPressed

Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs, Xamarin.Forms.Platform.Android/FormsApplicationActivity.cs
Fix regression introduced by #4707.
The OnResume worked before due to a side effect.
#4707 fixed the previous activity destroy which incorrectly triggered the page change.
Now that the event state are consistant, this revealed that OnResume event on the application was not called during Android Resume but during Android Restart event.
This PR modify when the SendResume is triggered to be consistant with the Android lifecycle.
- Fixes #7400
None
- Android
The OnResume method is called on Android Resume
None
Not applicable
[issue7400.zip](https://github.com/xamarin/Xamarin.Forms/files/3600649/issue7400.zip)
The reproduction project has the framework code included. So you can test with and without the modification.
1. Start reproduction project
2. Set a breakpoint on OnResume method in the …
=> Call the application OnResume, on Android Resume instead of Restart.

Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj, Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj, Xamarin.Forms.Core/Internals/LinkerSafeAttribute.cs, Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewRenderer.cs, Xamarin.Forms.Platform.iOS/LinkerSafeAttribute.cs, Xamarin.Forms.Platform.iOS/Properties/AssemblyInfo.cs, Xamarin.Forms.Platform.iOS/Renderers/ButtonRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/CarouselPageRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/CheckBoxRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ImageButtonRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/PhoneMasterDetailRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/RefreshViewRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs, Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
- Removes the Preserve Attribute from the Xamarin.Forms SDK
- Removing the Preserve Attribute will have little to no effect until this change https://github.com/xamarin/xamarin-macios/pull/7165 makes it into Xamarin.iOS SDK
- Ironically the *RenderWith* attribute causes all the renderers to not link out. I've ran this branch against the UI tests and all the UI Tests pass with this change. We'll want to test this change against the Forms Samples and really basic projects to make sure full linking doesn't break those projects. 
- Add Linker Safe Attribute so that (Assembly-level attributed used to inform MonoTouch's linker that this assembly can be safely linked, regardless of the system linker settings.)
This won't really cause anything to get linked out of the forms platform dll but it …
=> IOS Linker fixes inside Xamarin.Forms

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7510.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/AdapterNotifier.cs
Fix a crash related with disposing the old CollectionView Adapter adding items.
**NOTE:** Added _"Do not merge!!!"_ tag to review it with more time.
- fixes #7510 
None
- Android
None
In Core Gallery search the Issue7510, press the button to add items. Without crash, everything is correct.
=> [Android] Fix crash adding items to the CollectionView

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6878.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/Shell/ShellItem.cs, Xamarin.Forms.Platform.Android/Renderers/ShellBottomNavViewAppearanceTracker.cs
I followed another PR (#8079) feedback and create a null check to avoid NullException for `ShellBottomNavViewAppearanceTracker.SetBackgroundColor`
- fixes #6878 
Changed:
- void ShellBottomNavViewAppearanceTracker.SetBackgroundColor
- added this validation:
```C#
var child = menuView.GetChildAt(index);
if (child == null)
return;
```
None
Not applicable
1. Create a ShellItem in that contains tabs and set background-color
2. In code, call Items.Clear() on your ShellItem.
3. No exceptions at this point
- Or just run 6878 issue at Control Galery:
<p align="center">
<kbd>
</kbd>
</p>
=> Fix issue 6878 | [Bug] ShellItem.Items.Clear() crashes when the ShellItem has bottom tabs

Xamarin.Forms.ControlGallery.GTK/Program.cs, Xamarin.Forms.ControlGallery.WPF/MainWindow.xaml.cs, Xamarin.Forms.Platform.GTK/Forms.cs, Xamarin.Forms.Platform.WPF/Forms.cs
Allows you to set experimental flags on WPF and GTK so that the application does not crash.
Added:
- void SetFlags(params string[] flags)
- IReadOnlyList<string> Flags {get;}
- GTK
- WPF
Run ControlGallery, open CollectionView. 
Previous behavior - exception is thrown
Actual behavior - Application is running
=> WPF GTK Set flags

Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs
Unsubscribe OnScrollToRequested earlier.
Add missing SetOnScrollListener reset.
Fix random issues related to dispose.
None
- Android
None
Not applicable
Not specific test applicable, all tests must pass
=> [Android] ListViewRenderer  - Better dispose

Xamarin.Forms.Platform.Android/AppCompat/MasterDetailPageRenderer.cs
I added some missing code in the SetElement method when element change.
I never seen this case happen, but this must not prevent the code to be correct.
I also removed SetAutomationId duplicated call.
Finally, I added a dispose check after the delay in the DeviceInfoPropertyChanged method.
This issue happened once in one of my application.
Fix random issues related to dispose.
None
- Android
None
Not applicable
Not specific test applicable, all tests must pass
=> [Android] MasterDetailPageRenderer - Add guard and add missing unsubscribe

Xamarin.Forms.Core.UnitTests/ShellLifeCycleTests.cs, Xamarin.Forms.Core/Shell/Shell.cs
When navigating to a new Shell Item we were setting the current item from the top down.  This means if the user is navigating to a different shell section on a different shell item then the previously active Shell Section would fire OnAppearing before becoming inactive. 
This change inverts setting current item on each layer of shell. 
- fixes #8624 
Instead of current item being set from the ShellItem down it is now set from the ShellContent up which makes more sense
=> Reverse the order of assigning the Current Items on Shell

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7678.cs, Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs
Both, CollectionView and CarouselView, had a crash when adding items to a binder ObservableCollection (mainly played using asynchronous calls, etc.).
The native error was something like:
_"Invalid update: invalid number of items in section 0. The number of items contained in an existing section after the update (1) must be equal to the number of items contained in that section before the update (1), plus or minus the number of items inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out)"._
_NOTE: We could get the same error in other cases (removing items, etc)._
Using performBatchUpdates the item count returned by collectionView(_:numberOfItemsInSection:) should be sync with the …
=> [CollectionView] Fix crash on iOS adding items (ObservableCollection)

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5518.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Material.iOS/MaterialFrameRenderer.cs
Add EventTracker to MaterialFrameRenderer, and turn Interactable = true if had GestureRecognizers
- fixes #5518 
- iOS
=> fix #5518 | Frame Tap Gesture not working when using Visual="Material" in iOS

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8682.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/DispatcherExtensions.cs
When DispatcherProvider returns null, because context parameter does not inherit from VisualElement, then new instance of FallbackDispatcher is used.
- fixes #8682 
None
- UWP
Issue is fixed in Xamarin.Forms.Core project, but other platforms are not affected, because for other platforms IDispatcherProvider is not implemented and thus method DispatcherExtensions.GetDispatcher already returns FallbackDispatcher instance on line 25.
None
Not applicable
Automated test added; for UWP, manually run the test for Issue 8682.
=> Prevent UWP NullReferenceException when calling SavePropertiesAsync method off the main thread

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla41418.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GitHub1702.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1704.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1724.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3367.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5376.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6282.xaml.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/EmptyViewGalleries/EmptyViewLoadSimulateGallery.xaml.cs
UWP 14393 can't use the Thread class so for our Control Gallery I've replaced all uses of Thread with Task
- make sure changed UI Tests still work
=> Uwp thread to task fixes

Xamarin.Forms.Controls/XamStore/StoreShell.xaml, Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutContentRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewController.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellTableViewSource.cs
- Calculate the height of the templates used on the flyout so that they will size correctly
- Expose the creation of the TableViewController and TableViewSource for the flyout so users can override these and supply custom implementations
- This also fixes a regression on iOS where currently the flyout is unscrollable if content is too large
- fixes #8290 
- iOS
The height behavior will change on iOS if the templates that have been supplied have a HeightRequest specified or if they have a height > 44. This makes the behavior match Android and it is more expected
- compare store shell with and without this change to make sure results makes sense
- verify the menu item with a templated height has specified height
- verify android and ios are consistent
=> Fix dynamic heights for iOS Flyout Item Templates

Xamarin.Forms.Controls/GalleryPages/VisualStateManagerGalleries/VisualStateManagerGallery.cs, Xamarin.Forms.Controls/GalleryPages/VisualStateManagerGalleries/VisualStateSetterTarget.xaml, Xamarin.Forms.Controls/GalleryPages/VisualStateManagerGalleries/VisualStateSetterTarget.xaml.cs, Xamarin.Forms.Core.UnitTests/VisualStateManagerTests.cs, Xamarin.Forms.Core/Setter.cs, Xamarin.Forms.Xaml.UnitTests/VisualStateManagerTests.xaml, Xamarin.Forms.Xaml.UnitTests/VisualStateManagerTests.xaml.cs
Adds the ability to target a child object by name for a Setter for visual state management or styles.
- fixes #4924 
- closes #5034
- closes #5622
Added:
- `public string TargetName { get; set; }`
None
Not applicable
I've added a core gallery page `VisualStateSetterTarget.xaml` which has a button to toggle the VSM state of the `StackLayout`. When it's pressed, the `ALabel` is also triggered because of it's reference through `TargetName`.
=> Add VSM Setter TargetName

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8672.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems
This issue is fixed in https://github.com/xamarin/Xamarin.Forms/pull/7711 already merged. However, I wanted to validate that it was the same. Indeed it is the same so this PR only contains the repro sample. If it is not considered necessary, this PR can be closed.
- fixes #8672
None
- iOS
None
Not applicable
Launch Core Gallery and navigate to the issue 8672. If the CollectionView below loads items, the test has passed.
=> [iOS] CollectionView crashes on iOS 12 for repeated adds

Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.Android/CollectionView/TemplatedItemViewHolder.cs
If a TemplatedItemViewHolder is put into the recycled view pool and then removed from the pool by the RecyclerView (for whatever reason), the view can be collected and disposed while still bound to the underlying data source. At that point, an update to the data source can result in an ObjectDisposedException.
These changes prevent that scenario by setting the BindingContext of the view to null when it is put into the recycled view pool.
- fixes #8435
None
- Android
None
Not applicable
None. We don't have any control over when the RecyclerView ejects views from the pool or when the garbage collector decides to collect them, so setting up a repeatable test is exceedingly difficult.
=> Prevent ObjectDisposed exception when updating item ejected from recycled pool

Xamarin.Forms.Platform.Tizen/Forms.cs, Xamarin.Forms.Platform.Tizen/GestureDetector.cs, Xamarin.Forms.Platform.Tizen/StaticRegistrar.cs
This PR is an improvement over Static Registrar, which was introduced previous PR (#8642). We did various experiments to improve the startup performance of tizen application and provided many improvements by using Static Registrar. But we found some small improvements to the process of creating instances dynamically, and in this PR we're dealing with them.
As everyone knows, we are using expensive `Activator.CreateInstance()` to create a handler for a given view type. Yes, this is much more expensive than initializing with `new` operator. When using static registers, I thought about alternatives, and the experimental results were as follows. 
>_The test measured the time taken to create the instance of `CirclePageRendere` 10 times each in the Galaxy Watch._
- AS-IS. Using …
=> [Tizen] Enhances the Static Registrar

Xamarin.Forms.Platform.Tizen/Forms.cs
This PR removes unnecessary Lazy loading in `Forms.cs` to bring a little performance benefit on application launching time.
- `NaturalOrientation` property is used at application launching period, so using lazy loading for this property just drags the launching time.
- N/A
None
- Tizen
None
Not applicable
=> [Tizen] Remove unnecessary Lazy loading

Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs, Xamarin.Forms.Platform.Android/BackgroundManager.cs, Xamarin.Forms.Platform.Android/BorderBackgroundManager.cs, Xamarin.Forms.Platform.Android/ButtonLayoutManager.cs, Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs, Xamarin.Forms.Platform.Android/Platform.cs, Xamarin.Forms.Platform.Android/RendererPool.cs, Xamarin.Forms.Platform.Android/Renderers/PageContainer.cs, Xamarin.Forms.Platform.Android/VisualElementPackager.cs, Xamarin.Forms.Platform.Android/VisualElementTracker.cs
I have some time to fix an issue, and because I now know relatively well the issues relative to dispose, I choose the issue #3332.
Following my investigations I found several causes of memory leak.
With all these fixes, I'm no longer see any memory leak with the reproduction code provided in the referenced issue.
Below, the list of the differents issues :
- NavigationPageRenderer : Fix a potential memory leak caused by the toolbar which was not correctly disposed.
- BackgroundManager : The element PropertyChanged event is never unsubscribed and cause a leak. (_leak confirmed with the profiler_)
- ButtonLayoutManager : The element PropertyChanged event is never unsubscribed and cause a leak. (_leak confirmed with the profiler_)
- ButtonRenderer (FastRenderer) : The SetTracker call in the …
=> [Android] Fix various memory leaks

Xamarin.Forms.Platform.iOS/Extensions/FontExtensions.cs
The system font on iOS 13 must not be received by name anymore but with `UIFont.SystemFontOfSize(size, weight)`.
- fixes #8035 
None
- iOS
You can use the font family .SFUI again with all weights Apple offers, like `.SFUI-Medium`. Without this change the TimesNewRoman font was returned instead when using e.g. `.SFUI` or `.SFUI-Medium` or `.SFUI-Bold` etc.
Not applicable
=> Fix #8035 - system font on iOS 13

Xamarin.Forms.Platform.Android/Forms.cs
Fix for Issue #7772 [based on code from Essentials](https://github.com/xamarin/Essentials/blob/07cb1f3b728593f0c46529d0f3cb0b3586bac565/Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs#L29)
- fixes #7772 
Device.Idiom return TV for Android TV devices
- Android
Not applicable
build nugets for my change, updated the demo app from #7772 with local nugets, compiled the app and ran it on Fire TV 4k Stick, Android phone and Android tablet. Now Device.Idiom return TV for Android TV devices like Xamarin.Essentials
=> fix for Issue 7772- Device.Idiom return TV for Android TV devices

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzila57749.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla39702.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla43469.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla59172.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla60691.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/GestureBubblingTests.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/InputTransparentTests.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2617.cs, Xamarin.Forms.Core.UITests.Shared/Tests/AutomationIDUITests.cs, Xamarin.Forms.Core.UITests.Shared/Tests/CollectionViewUITests.cs, Xamarin.Forms.Core.UnitTests/DatePickerUnitTest.cs, Xamarin.Forms.Xaml.UnitTests/AssemblyInfoTests.cs
- Fix async void
- Fix TestCaseSource static
- Fix CollectionView test
- Use nameof for TestCaseSource
Fix tests :
- Bugzilla57749
- Bugzilla39702
- Bugzilla43469
- Bugzilla59172
- Bugzilla60691
- GestureBubblingTests
- InputTransparentTests
- Issue2617
- AutomationIDUITests
- CollectionViewUITests
None
- iOS
- Android
- UWP
None
Not applicable
Run UI Tests
=> [Android] Fix some issues in UITests

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8326.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8326.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8449.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8449.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/EmptyViewAdapter.cs, Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.Android/CollectionView/ListSource.cs, Xamarin.Forms.Platform.Android/CollectionView/SimpleViewHolder.cs, Xamarin.Forms.Platform.UAP/CollectionView/FormsGridView.cs, Xamarin.Forms.Platform.UAP/CollectionView/FormsListView.cs, Xamarin.Forms.Platform.UAP/CollectionView/IEmptyView.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewStyles.xaml, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs, Xamarin.Forms.Platform.iOS/CollectionView/StructuredItemsViewController.cs, Xamarin.Forms.Platform.iOS/CollectionView/TemplateHelpers.cs
We had a different behavior managing EmptyView on Android, iOS and UWP.
The behavior we had was the following:
- Android: EmptyView occupied the entire size of the CollectionView. However, we had an issue that it did not appear using Header and/or Footer. This is because we Swap the Adapter to change to `EmptyViewAdapter` when not having items.
- iOS: EmptyView was rendered behind the Header and/or Footer. We used `BackgroundView` to manage EmptyView (that's why it is rendered behind and taking all the space).
- UWP: EmptyView is not rendered. The problem was related to size calcs.
- fixes #8326
- fixes #7457
- fixes #8449 
Other fixes:
- EmptyView does not change its size by changing the size of the window in UWP.
- On some platforms, when using just a text as EmptyView it appeared …
=> Fixed EmptyView issues on CollectionView

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8526.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core.UITests.Shared/UITestCategories.cs, Xamarin.Forms.Core/Page.cs
Uses the same mechanism as DisplayAlert and DisplayActionSheet to queue a DisplayPrompAsync call up for display after the page has finished loading.
- fixes #8526
None
None
Not applicable
=> Queue DisplayPromptAsync for display after pages loads

Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/ScrollViewContainer.cs, Xamarin.Forms.Platform.Android/VisualElementRenderer.cs
When trying to debug some problem relative to dispose on Android I found some issues with some code responsible of the disposal of views.
Some code only dispose the view but not remove them from their parent.
This can cause the disposed renderer to be accessed during layout and cause "NotSupportedException: Unable to activate instance of type ...", so I added the missing RemoveFromParent call.
I also fixed an issue in the ScrollViewContainer, only the first renderer was disposed.
Fix random issues related to dispose.
None
- Android
None
Not applicable
Not specific test applicable, all tests must pass
=> [Android] Fix some views dispose

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CollectionViewGallery.cs, Xamarin.Forms.Platform.UAP/CollectionView/StructuredItemsViewRenderer.cs
Fixes item spacing with the `CollectionView` on UWP.
Also, reinstated the item spacing gallery in the `CollectionView` control galleries.
- fixes #7842 
None
- UWP
Item spacing now works with `CollectionView`.
Not applicable
- Open the Item Spacing Gallery in the Collection View gallery.
- Run the gallery tests
=> [UWP] Fixed CollectionView item spacing

Xamarin.Forms.Platform.Tizen/GestureDetector.cs, Xamarin.Forms.Platform.Tizen/Renderers/LayoutRenderer.cs, Xamarin.Forms.Platform.Tizen/Renderers/ViewRenderer.cs
This PR fixes the creation time of `GestureDetector` so that it can be generated correctly when needed. Existing implementations was to create `GestureDetector` even if View doesn't have any `GestureRecoginzer`. The suggested way is to create `GestureDetector` when the `GestureRecognizer` is added to the View.
None
None
- Tizen
None
Not applicable
=> [Tizen] Creates the GestureDetector on demand

Xamarin.Forms.Platform.Android/Extensions/ImageViewExtensions.cs
Context: https://github.com/jonathanpeppers/glidex/tree/xf-4.4
In the linked sample, the `xf-4.4` branch, I am getting this exception
in the log for any `ImageCell` and no image loads:
[0:] BaseCellView: Error loading image: System.NullReferenceException: Object reference not set to an instance of an object.
at Xamarin.Forms.Platform.Android.ImageViewExtensions.UpdateBitmap (Android.Widget.ImageView imageView, Xamarin.Forms.IImageElement newView, Xamarin.Forms.IImageElement previousView, Xamarin.Forms.ImageSource newImageSource, Xamarin.Forms.ImageSource previousImageSource) [0x000f8] in D:\a\1\s\Xamarin.Forms.Platform.Android\Extensions\ImageViewExtensions.cs:49
at Xamarin.Forms.Platform.Android.BaseCellView.UpdateBitmap (Xamarin.Forms.ImageSource source, Xamarin.Forms.ImageSource …
=> [android] fix NRE in ImageCell / ImageViewExtensions

.nuspec/Xamarin.Forms.AppLinks.nuspec, .nuspec/Xamarin.Forms.Maps.nuspec, .nuspec/Xamarin.Forms.Visual.Material.nuspec, .nuspec/Xamarin.Forms.nuspec, Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj, Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj, Xamarin.Forms.Material.Android/Xamarin.Forms.Material.Android.csproj, Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj, Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
VS2017 places the binary files into *MonoAndroid90\90\*
VS2019 places the binary files into *MonoAndroid90\*
This PR makes VS2017 like VS2019 so that the nuspecs can just stay the same regardless if you're building on vs2017 or vs2019
- test generated nugets
=> Change build output on 2017 to match 2019

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7875.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/FastRenderers/AutomationPropertiesProvider.cs, Xamarin.Forms.Platform.Android/FastRenderers/ButtonRenderer.cs
Applyed the same fix previously added to the default Button renderer
- fixes #7875 
None
- Android
None
- Added a Button to a Page, don't set it's text and set it's Icon;
- Set AutomationProperties.Name of the Button
- The Button size must be the same
=> #7875: Android: Button size changes when setting Accessibility properties

Xamarin.Forms.Controls/CoreGalleryPages/PickerCoreGalleryPage.cs, Xamarin.Forms.Platform.UAP/PickerRenderer.cs
While using a Picker control without a Title provided, on UWP you would still get an empty Header above the dropdown of the Picker. Rendering empty space.
- fixes #8150
Changed:
- object PickerRenderer => Remove code in reference to Header property of UWP ComboBox
- object PickerRenderer => Changed UpdateTitle method
- UWP
No longer empty space above Picker control on UWP.
Before - no title
Before - with title
After - no title
After - with title
Open Controls Gallery app on UWP, go to Picker Gallery, now see that no empty space is rendered above picker.
=> [UWP] Null HeaderTemplate and Header if no Title is provided on Picker.

Xamarin.Forms.Platform.Android/Elevation.cs, Xamarin.Forms.Platform.Android/VisualElementPackager.cs
The elevation property on the android view is scaled to the device density. Currently we are just setting the elevation to the exact same value specified on the platform specific but this will cause different behavior on different devices.
You can see this issue if you try to match the elevation of a control at the xplat level with the native level
For example the code below works fine across APIs and device scales with this change but without it you can't correctly set an Elevation that works across devices
```
<Grid>
<Grid.RowDefinitions>
<RowDefinition Height="300"></RowDefinition>
<RowDefinition Height="*"></RowDefinition>
</Grid.RowDefinitions>
<Grid.ColumnDefinitions>
<ColumnDefinition Width="300"></ColumnDefinition>
<ColumnDefinition Width="*"></ColumnDefinition> …
```
=> Convert elevation platform specific to correct pixel scale

Xamarin.Forms.Build.Tasks/ExpandMarkupsVisitor.cs, Xamarin.Forms.Xaml.UnitTests/MarkupExpressionParserTests.cs, Xamarin.Forms.Xaml/ExpandMarkupsVisitor.cs, Xamarin.Forms.Xaml/MarkupExpressionParser.cs, Xamarin.Forms.Xaml/MarkupExtensionParser.cs
Throw `XamlParseException` in `MarkupExpressionParser.GetNextPiece`.
None
None
A source code location information will be shown for erroneous markup expressions.
Not applicable
Run `Xamarin.Forms.Xaml.UnitTests`.
=> [Xaml] Throw XamlParseException in MarkupExpressionParser.GetNextPiece

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8741.cs
@PureWeen 
There have been some recent changes around the tint color of toolbar/menu items on Android. Such changes being the second aspect of this fix, I'd like us to assert in the issue test that the graying-out works, in order to keep the code around this stable.
=> Fix for 8741: Assert that ToolbarItem is grayed-out (PR 8889)

Xamarin.Forms.Build.Tasks/TypeReferenceExtensions.cs, Xamarin.Forms.Xaml.UnitTests/XamlC/TypeReferenceExtensionsTests.cs
Variance matters even for basic interfaces like `System.Collections.Generic.IEnumerable<T>`. I think XamlC will cover most use cases of generics with this change and previous improvements.
None
None
None
Not applicable
Run the automated tests.
=> [XamlC] Support variance

Xamarin.Forms.Build.Tasks/ExpandMarkupsVisitor.cs, Xamarin.Forms.Xaml.UnitTests/GenericsTests.xaml, Xamarin.Forms.Xaml.UnitTests/GenericsTests.xaml.cs, Xamarin.Forms.Xaml/ExpandMarkupsVisitor.cs, Xamarin.Forms.Xaml/MarkupExpressionParser.cs, Xamarin.Forms.Xaml/MarkupExtensionParser.cs, Xamarin.Forms.Xaml/XamlParser.cs, Xamarin.Forms.Xaml/XamlServiceProvider.cs
[MS-XAML-2009] (page 79) says a markup extension accepts prefixed member names. This change supports the syntax. It is essential to use a generic markup extension, and this includes a test case for such a situation.
None
None
None
Not applicable
=> [Xaml[C]] Accept prefixed property names of markup extensions

Xamarin.Forms.Platform.iOS/Deserializer.cs, Xamarin.Forms.Platform.iOS/NativeBindingService.cs, Xamarin.Forms.Platform.iOS/NativeValueConverterService.cs
Now the iOS platform is marked as "linker safe", the linker can (and will) link out the Deserializer dependency. This change adds a Preserve attribute to avoid that.
- fixes crash in SaveProperties on iOS
None
- iOS
None
Not applicable
Automated test 28709 - if it doesn't crash, this worked.
=> Stop the linker from killing off the Deserializer

.nuspec/Xamarin.Forms.nuspec, Xamarin.Forms.Maps.UWP/Xamarin.Forms.Maps.UWP.csproj, Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj, azure-pipelines.yml, build.cake, build/steps/build-nuget.yml, build/steps/build-windows.yml
- removed all the xbf files from the nuspec and used */p:DisableEmbeddedXbf=false* to ensure that everything gets embedded into the pri file for debug/release builds
- I moved the UWP platform builds to VS 2019 because that's the only way I could produce a nuget tthat worked with VS 2017.  If I build the nuget on our VS 2017 server then use it with VS 2017 it would throw exceptions about a missing XAML file
- UWP
- Maser builds and you can use the nuget
=> Package up everything into the PRI file for debug and release builds

Xamarin.Forms.ControlGallery.iOS/LinkDescription.xml, Xamarin.Forms.Platform.iOS/EventTracker.cs, Xamarin.Forms.Platform.iOS/ShadowEffect.cs
Stop linker removing custom renderers, services, and effects in Control Gallery.
As a bonus, this also fixes TapGestures in Spans on iOS.
=> Stop linker removing custom renderers, services, and effects in Control Gallery

Xamarin.Forms.Platform.Android/AndroidAppIndexProvider.cs
Reviewing the memory report from the Mono profiler:
Allocation summary
Bytes      Count  Average Type name
13776        123      112 System.Reflection.AssemblyName
That is a lot of `AssemblyName` objects!
I found part of the culprit to be in `AndroidAppIndexProvider`:
private Assembly GetAssemblyForAppLinks(string assemblyName)
{
return Device.GetAssemblies().FirstOrDefault(assembly => assembly.GetName().Name == assemblyName);
}
Instead of using `System.Linq` to create an `AssemblyName` for every
.NET assembly, we can just use a fully-qualified name with
`Type.GetType`.
The memory results were a bit better:
Allocation summary
Bytes      Count  Average Type name
8176         73      112 System.Reflection.AssemblyName
Since this avoids a bit of System.Reflection & System.Linq, I was able
to …
=> [android] use Type.GetType() to load AppLinks

UWP.Build.props, UWP.Build.targets, Xamarin.Forms.Maps.UWP/Directory.Build.Props, Xamarin.Forms.Maps.UWP/Directory.Build.targets, Xamarin.Forms.Maps.UWP/Xamarin.Forms.Maps.UWP.csproj, Xamarin.Forms.Platform.UAP/Directory.Build.Props, Xamarin.Forms.Platform.UAP/Directory.Build.targets, Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
Setup conditionals on the UWP Platform project so that it's basically an empty netstandard2.0 project when built on mac
- No popup warnings on VSMAC
- Make sure everything is building correctly on the windows/mac CI
=> Fix UWP Platform project so that it doesn't try to load on VS MAC

Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj, Xamarin.Forms.Core.Android.UITests/Xamarin.Forms.Core.Android.UITests.csproj, Xamarin.Forms.Core.Windows.UITests/Xamarin.Forms.Core.Windows.UITests.csproj, Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj, Xamarin.Forms.Core.macOS.UITests/Xamarin.Forms.Core.macOS.UITests.csproj
Updated Xamarin.UITest and the Cloud Agent
- fixes #8891
- run ui tests locally
- make sure UI tests still run in appcenter
=> Bump Xamarin UI Test packages to fix UI Tests locally

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8821.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/Renderers/AndroidGIFImageParser.cs
Fixed Gif animation loading from local files (no resources).
- fixes #8821
None
- Android
None
Launch Core Gallery and navigate to the issue 8821. Press the "DownloadFile" button and then press the "Animate" button. If the gif is loaded and animated, the test has passed.
=> [Android] Fixed Gif animation loading from files 

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8345.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/CollectionView/GroupableItemsViewController.cs, Xamarin.Forms.Platform.iOS/CollectionView/GroupableItemsViewDelegator.cs
Adds insets to UICollectionView sections when CollectionView is grouped so that group headers/footers respect ItemSpacing.
- fixes #8345
None
- iOS
None
Not applicable
Manual test, Issue 8345
=> Account for item spacing when providing grouped insets

Xamarin.Forms.Platform.iOS/Renderers/ButtonRenderer.cs
ButtonRenderer on iOS is not following the Dispose pattern, which means that deterministic disposal operations can happen from the finalizer, which may not be run on the UI thread; this results in cross-thread exceptions that are very difficult to reproduce.
Seemingly random application crashes.
None
- iOS
None
Not applicable
Nope
=> Fix cross-thread exception when finalizing ButtonRenderer

Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/TabbedPage.cs, Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/TranslucencyMode.cs, Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs
Added one more platform-specific property for iOS
- fixes #7135 
Added:
- Xamarin.Forms.PlatformConfiguration.iOSSpecific.TabbedPage (IsTranslucentTabBarProperty)
- Core (iOS specific stuff)
- iOS
Can change Translucent of TabBar
Not applicable (it's better to use Color meter)
```charp
MainPage = new TabbedPage
{
Children = {
new ContentPage() { BackgroundColor = Color.Red },
new ContentPage()
}
};
Xamarin.Forms.PlatformConfiguration.iOSSpecific.TabbedPage.SetIsTranslucentTabBar(MainPage, false);
```
- Check bar colors with a color meter
=> [Enhancement] Add platform specific property to handle iOS UITabBar Translucent property

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8644.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.WPF/FormsTextBox.cs, Xamarin.Forms.Platform.WPF/Renderers/EntryRenderer.cs
Fixes crash in WPF when:
1. Entry.IsPassword set to true
2. Entry has BindingContext
3. BindingContext changes value of Text to shorter value in TextChanged
- fixes #8644 
None
- WPF
None
Not applicable
Issue8644
=> Fix WPF Entry crashes when IsPassword=true

Xamarin.Forms.Platform.MacOS/NativeToolbarTracker.cs, Xamarin.Forms.Platform.iOS/Forms.cs
Fixes NRE when using Xamarin.Forms with Mac OS on pre-Mojave OS versions with a `NavigationPage`
- fixes #8261
None
- Mac OS
From #6981 we used a property that is available only from Mojave (10.14) and up. This causes an NRE on apps using Xamarin.Forms on OS versions older than that. This change checks the OS version first.
Not applicable
Run the gallery app on a pre-Mojave machine
=> [MacOS] Fix NRE with NavigationPage on pre-Mojave

Xamarin.Forms.Build.Tasks/ExpandMarkupsVisitor.cs, Xamarin.Forms.Xaml.UnitTests/MarkupExpressionParserTests.cs, Xamarin.Forms.Xaml/ExpandMarkupsVisitor.cs, Xamarin.Forms.Xaml/MarkupExpressionParser.cs, Xamarin.Forms.Xaml/MarkupExtensionParser.cs
The behavior introduced with this change conforms to the description of
[MS-XAML-2009] page 80 and 81.
- fixes #6905
None
None
Not applicable
Run the automated tests.
=> [Xaml] Create value from positional argument text of markup extension

Xamarin.Forms.Core/PlatformConfiguration/TizenSpecific/Image.cs, Xamarin.Forms.Platform.Tizen/Extensions/ImageExtensions.cs, Xamarin.Forms.Platform.Tizen/Native/Image.cs, Xamarin.Forms.Platform.Tizen/Renderers/ImageButtonRenderer.cs, Xamarin.Forms.Platform.Tizen/Renderers/ImageRenderer.cs
This PR is about loading local file images on Tizen more efficiently and improving performance. As you know, `Xamarin.Forms.Image` was supposed to load images asynchronously, regardless of the `ImageSource` type. When I measured the performance of loading image files (local file) in Tizen platform, I found that sync loading was about 2~3 times faster than async loading. So, I added the TizenSpecific API - `Image.File` - for this.
This Tizen platform-specific is used to load local file image synchronously. It can be consumed from XAML and C# as follows. If `Image.ImageSource` is set, `Image.File` is ignored. 
- XAML
```xml
<ContentPage ...
xmlns:tizen="clr-namespace:Xamarin.Forms.PlatformConfiguration.TizenSpecific;assembly=Xamarin.Forms.Core">
<StackLayout>
<Image …
```
=> [Tizen] Load image synchronously

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8741.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/Internals/ToolbarTracker.cs, Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs, Xamarin.Forms.Platform.Android/Extensions/ToolbarExtensions.cs, Xamarin.Forms.Platform.Android/Platform.cs, Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs, Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj, Xamarin.Forms.Platform.UAP/Platform.cs, Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs
Fixed Android ToolbarItems so that they update functionally and visually as CanExecuteChages toggles. This addressed both the Text and Icon not changing alpha values when disabled
The code on the NavigationPage was identical to the shell code so I extracted all of that to a reusable Extension method for both of them
- fixes #8741 
- fixes #8327
- Android
- iOS
- UI test included
- run through a few tool bar item tests with navigation page to make sure it works as well
=> Resolve issues with Shell ToolbarItems not reacting to CanExecute Changes

Xamarin.Forms.Platform.iOS/Renderers/BoxRenderer.cs
BoxRenderer's drawing method is constantly recomputing some multiples of pi and casting back and forth between float/nfloat unnecessarily. These changes eliminate some of the unnecessary effort.
None
None
- iOS
None
Not applicable
=> [iOS] Reduce casting and repeat math during BoxView drawing

Xamarin.Forms.Controls/GalleryPages/PickerGallery.cs, Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/DatePicker.cs, Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/TimePicker.cs, Xamarin.Forms.Platform.iOS/Renderers/DatePickerRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/TimePickerRenderer.cs
Add iOS-specific to UpdateMode enum from Picker to DatePicker and TimePicker.
Didn't see any GitHub issues, but some related forum threads:
- https://forums.xamarin.com/discussion/93521/what-is-date-picker-behaviour-in-xamarin-forms
- https://forums.xamarin.com/discussion/98832/add-cancel-button-to-ios-datepicker-and-timepicker-only-change-the-value-when-done-is-clicked
- https://forums.xamarin.com/discussion/94666/cant-detect-ok-button-press-on-datepicker
Added:
- `Xamarin.Forms.PlatformConfiguration.iOSSpecific.DatePicker` class
- `Xamarin.Forms.PlatformConfiguration.iOSSpecific.TimePicker` class
- iOS
When UpdateMode is set to WhenFinished, the Date/Time property will be set when the user closes the picker with the Done button rather than as they scroll.
Not …
=> [iOS] Add UpdateMode platform-specific to DatePicker and TimePicker

Xamarin.Forms.Platform.Tizen/Renderers/ImageRenderer.cs
This PR adds basic GIF image animation support on Tizen. Also, this is an addendum to the changes in #7330. 
fixes #1704
None
- Tizen
Nothing, if the animation play property has not been set then images will be loaded normal. Trying to use animation support on none GIF image sources will fail the load and fallback trying to load as regular image.
=> [Tizen] Gif Animation Support

Xamarin.Forms.Core/DependencyService.cs, Xamarin.Forms.Core/ReflectionExtensions.cs, Xamarin.Forms.Core/Registrar.cs
When profiling startup, I started looking into the number of calls
retrieving custom attributes from assemblies:
Method call summary
Total(ms) Self(ms)      Calls Method name
24        0         301 System.Reflection.RuntimeAssembly:GetCustomAttributes (System.Type,bool)
I saw a pattern such as:
object[] attributes = assembly.GetCustomAttributes(attrType, true);
var handlerAttributes = new HandlerAttribute[attributes.Length];
Array.Copy(attributes, handlerAttributes, attributes.Length);
RegisterRenderers(handlerAttributes);
We can avoid the allocation and copying of the array completely here.
We can simply cast `attributes` to `HandlerAttribute[]`.
The other thing I saw was:
string resolutionName = assembly.FullName;
var resolutionNameAttribute = …
=> [core] perf improvements for Assembly attributes reflection

Xamarin.Forms.Core/Registrar.cs
When the for loop on the registrar exits early it needs to close the profiler frame
- make sure you can launch Android control gallery and run a ui test
=> Registrar frame profile matchup fix

Xamarin.Forms.Core.UnitTests/ShellTests.cs, Xamarin.Forms.Platform.Android/Renderers/ShellItemRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/ShellSectionRenderer.cs, Xamarin.Forms.Platform.UAP/Shell/ShellItemRenderer.cs, Xamarin.Forms.Platform.UAP/Shell/ShellSectionRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellItemRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootRenderer.cs
As mentioned in the issue #8211, Handled Null Reference exceptions in Shell if incorrectly-configured.
- fixes #8211
Changed:
- `ShellSectionRenderer.cs` : Added below condition to handle Null Ref if no Shell Content provided [first usecase]:
```
if (shellSection.CurrentItem == null)
throw new ArgumentException("Active Shell Content not set. Have you added any Shell Content to your Shell?", nameof(ShellSection));
```
- `ShellItemRenderer.cs` : Added below condition to handle Null Ref if no Shell Content provided (this will also handle if no tab provided [second usecase]):
```
if (ShellItem.CurrentItem == null)
throw new ArgumentException("Active Shell Content not set. Have you added any Shell Content to your Shell?", nameof(ShellSection));
```
- Android
None
Not applicable
- I've added …
=> Fixed 8211 - Handled NullRef in Shell if incorrectly-configured

azure-pipelines.yml
Use same nuget counter for all builds. Making the counter based on branch didn't work fine with nightly 
- None
None
- Nuget
None
Not applicable
=> [Build]Use same counter for all builds

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9006.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/TestPages/TestPages.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/Shell/IShellSectionController.cs, Xamarin.Forms.Core/Shell/ShellSection.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs
Detect when PopToRoot occurs from clicking on the active tab and propagate these changes up to cross platform code
- fixes #9006 
- iOS
- uitests includeed
=> Detect when popped to root on iOS after clicking on Tab

Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs
We were reseting the selected tint color to null , so if a user specified some Appearance settings on the iOS head project we would ignore it.
- fixes #9070
None
- iOS
Should allow to set the SelectedTintColor
Run the ControlGallery Tabbed Page, check the color for tint is blue.
Add this line in the iOS project:
```
UITabBar.Appearance.SelectedImageTintColor = UIColor.Red;
``` 
Run the project again and check if the selected tint is now Red
=> [iOS] Take into account the specified UITabBar.Appearance.

Xamarin.Forms.Platform.Android/Renderers/SearchBarRenderer.cs
Once custom SeachBarRenderer, CreateNativeControl will throw NullReference Expection
- fixes #
None
- Android
None
Not applicable
=> Fix Android SeachBarRenderer CreateNativeControl issue

Xamarin.Forms.Platform.Android/CollectionView/PropertyChangedEventArgsExtensions.cs, Xamarin.Forms.Platform.Android/Renderers/ImageRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/SearchHandlerAppearanceTracker.cs, Xamarin.Forms.Platform.UAP/CollectionView/CarouselViewRenderer.cs, Xamarin.Forms.Platform.UAP/PropertyChangedEventArgsExtensions.cs, Xamarin.Forms.Platform.iOS/CollectionView/PropertyChangedEventArgsExtensions.cs
When reviewing code in Xamarin.Forms I noticed the method:
public static bool IsOneOf(this PropertyChangedEventArgs args, params BindableProperty[] properties)
{
foreach (BindableProperty property in properties)
{
if (args.PropertyName == property.PropertyName)
{
return true;
}
}
}
Which is used such as:
else if (e.IsOneOf(Label.TextProperty, Label.FormattedTextProperty, Label.TextTypeProperty))
UpdateText();
The readability is nice, it is an improvement to:
else if (e.PropertyName == Label.TextProperty.PropertyName || e.PropertyName == Label.FormattedTextProperty.PropertyName || e.PropertyName == Label.TextTypeProperty.PropertyName))
UpdateText();
I mean that is so long it goes off the end of my screen!
Unfortunately, the `IsOneOf` method has some impact to performance:
1. A …
=> [platform] improve perf of PropertyChangedEventArgsExtensions

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7924.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7924.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs, Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewController.cs
Update the CarouselView Position setting the **CurrentItem** from a ViewModel. This moves the scroll to the correct position and CurrentItem (object) will be synchronized with Position (int).
- fixes #7924
None
- iOS
- Android
None
_NOTE: The CurrentItem is set in the constructor of the ViewModel, and before the changes of the PR it did not change to the correct position._
Launch Core Gallery and navigate to the Issue 7924. If the initial Position is 3, the test passes.
=> Update the CarouselView Position setting the CurrentItem

Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs, Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Context: https://github.com/jonathanpeppers/anticipator
Context: https://github.com/xamarin/Xamarin.Forms/pull/8245
I was profiling the Blank Xamarin.Forms app template and saw this:
Method call summary
Total(ms) Self(ms)      Calls Method name
40095        0         11 (wrapper runtime-invoke) <Module>:runtime_invoke_void__this___object (object,intptr,intptr,intptr)
40094        0          8 System.Threading.ThreadHelper:ThreadStart (object)
40094        0          8 System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
40094        0          8 System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
40094        0          8 …
=> [android] remove Anticipator.cs for now

Xamarin.Forms.Core/Registrar.cs
Fixes #9134
A reported failure of:
System.InvalidCastException: 'Unable to cast object of type 'System.Attribute[]' to type 'Xamarin.Forms.HandlerAttribute[]'.'
was happening on UWP, @PureWeen also could repro with a new app.
What is weird about this:
* It appears to work with .NET Framework & Mono
* It appears to work for me locally if I just launch the Control
Gallery on UWP.
I suspect something is happening with how Xamarin.Forms is built
(using 2017 and older UWP SDKs), but not really sure?
I think we should just fix this quickly and I will revisit later.
- fixes https://github.com/xamarin/Xamarin.Forms/issues/9134
None
- UWP
None
Not applicable
We should perhaps manually test the NuGet package on UWP?
It is really weird this works for me locally on the …
=> [Core] remove array covariant cast for UWP

Xamarin.Forms.Platform.UAP/Platform.cs, Xamarin.Forms.Platform.UAP/PromptDialog.xaml, Xamarin.Forms.Platform.UAP/PromptDialog.xaml.cs, Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj
Adds UWP Display Prompt
- fixes for UWP #6713 - 
None
- UWP
Adds Display Prompt
Use Issue 6713 with UWP
=> Add UWP display prompt

Xamarin.Forms.Platform.Android/Deserializer.cs, Xamarin.Forms.Platform.Tizen/Deserializer.cs, Xamarin.Forms.Platform.iOS/Deserializer.cs
When profiling startup, I was seeing things like:
Method call summary
Total(ms) Self(ms)      Calls Method name
52        0          3 System.IO.IsolatedStorage.IsolatedStorageFile:GetUserStoreForApplication ()
52        0          3 (wrapper remoting-invoke-with-check) System.IO.IsolatedStorage.IsolatedStorageFile:PostInit ()
51        0          3 System.IO.IsolatedStorage.IsolatedStorageFile:PostInit ()
51        0          2 (wrapper remoting-invoke-with-check) System.IO.IsolatedStorage.IsolatedStorageFile:FileExists (string)
51        0          2 System.IO.IsolatedStorage.IsolatedStorageFile:FileExists (string)
49        0          4 System.IO.IsolatedStorage.IsolatedStorageFile:IsPathInStorage (string)
This app has no `Properties` at all, but it seems to still be doing
the file I/O …
=> [android/ios] improve perf when not using Application.Properties

Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android (Forwarders).csproj, Stubs/Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS (Forwarders).csproj, Xamarin.Forms.ControlGallery.iOS/PlatformSpecificCoreGalleryFactory.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Maps.Android/Xamarin.Forms.Maps.Android.csproj, Xamarin.Forms.Maps.iOS/Xamarin.Forms.Maps.iOS.csproj, Xamarin.Forms.Material.Android/Xamarin.Forms.Material.Android.csproj, Xamarin.Forms.Material.iOS/Xamarin.Forms.Material.iOS.csproj, Xamarin.Forms.Platform.Android.AppLinks/Xamarin.Forms.Platform.Android.AppLinks.csproj, Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj, Xamarin.Forms.Platform.iOS/Renderers/ActivityIndicatorRenderer.cs, Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj, azure-pipelines.yml, build.cake, build/steps/build-osx.yml
This will allow us to build our nuget packages on vs 2019 but they will still work on VS2017
- iOS
- Android
- download the nuget packages and try to run/build android/ios projects on vs2017
=> Apply cecil fixes to make packages 2017 compatible

Xamarin.Forms.Core/NavigationPage.cs
Adds a null check to GetIconColor to avoid a possible NRE.
- fixes: Can't launch Control Gallery (and possibly anything else with a NavigationPage)
None
None
Not applicable
Launch Control Gallery on iOS. If this works, it won't crash with a NullReferenceException.
=> Add null check to GetIconColor

Xamarin.Forms.Controls/CoreGalleryPages/CarouselViewCoreGalleryPage.cs, Xamarin.Forms.CustomAttributes/TestAttributes.cs, Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs
Make control aware of the `IsBounceEnabled` value on initialization on Android.
- fixes #9159
None
- Android
When setting `IsBounceEnabled` from XAML it wouldn't work since the property was not propagated to the native control on initialization, only when the property was set.
Not applicable
Go to CarouselView Core Gallery and find the new IsBounceEnabled option. When swiping from left to right you should not see the Android overscroll animation. On other CarouselView Core Gallery options you should see it.
=> Make CarouselView.IsBounceEnabled work on initialization

Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs
Before this fix, when I use ScrollView with no Content and RightToLeft FlowDirection application crashes after page is loaded. So I added null check for ScrollView.Content in UpdateFlowDirection method in ScrollViewRenderer for iOS.
- iOS
The application will no longer crash with  with changed flow dirrection to RtL and null Content of ScrollView.
Not applicable
Try use ScroolView with any content on iOS with changed flow dirrection to RtL.
=> Add null check in UpdateFlowDirection

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue5596.cs, Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
Force a redraw for right toolbar items by resetting TintColor to prevent toolbar items from being grayed out when canceling swipe to the previous page.
- fixes #5596
None
- iOS
Canceling the swipe gesture to go back to the previous page and then going back either by swiping or clicking the upper-right back button should not gray out the previous page's toolbar item.
Before
https://www.dropbox.com/s/i8wrmxnoq0l9bvr/screen%20recording%202019-11-11%20at%2011.22.12%20am.mov?dl=0
After
https://www.dropbox.com/s/jpgk5dlsog9bevw/screen%20recording%202019-11-11%20at%2011.20.06%20am.mov?dl=0
Find the 5596 test case in the control gallery, click 'Next Page', start a swipe gesture to go back to the previous page but cancel it before it completes. Swipe again or click the back button on the upper …
=> Fix previous page's toolbar item being grayed out when canceling swipe to previous page.

Xamarin.Forms.Core/Interactivity/AttachedCollection.cs
Add a null check when removing dead WeakReferences.
- fixes #9183
None
None
Not applicable
None, unable to repro.
=> Avoid NRE removing WeakReferences (and remove null ones)

Xamarin.Forms.Core/Binding.cs, Xamarin.Forms.Core/BindingBase.cs, Xamarin.Forms.Core/BindingBaseExtensions.cs, Xamarin.Forms.Core/BindingExpression.cs
I made most of these changes through the benchmarks here:
https://github.com/jonathanpeppers/Benchmarks/blob/6725a72844c5f18320a31223b6f37abd7b28ece4/Benchmarks/BindingBenchmarks.cs
1. `Clone()` was doing `new Binding()` but then using the property
setters instead of the ctor parameters. `Clone()` seems to be
called for `DataTemplate`, `ListView`, etc.
2. `BindingBase.ThrowIfApplied()` is called very frequently, so I
added `MethodImplOptions.AggressiveInlining`.
3. `BindingBaseExtensions.GetRealizedMode` is called ~3 times per
binding applied, added `MethodImplOptions.AggressiveInlining`.
4. In `BindingExpression` a `bool isLast` value was always calculated,
even though it was only sometimes used inside an `if`. It can just
do this check inside the `if`.
5. `object value = …
=> [Core] performance improvements around bindings

Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs, Xamarin.Forms.Platform.Android/ContextExtensions.cs
The Previewer doesn't execute any of the code inside FormAppCompatActivity so this code just sets a flag during startup to indicate that we aren't the previewer so you don't need to perform expensive checks
- Android
- @kingces95 will check if this helps startup speed and make sure the IsEdit check doesn't just exchange one slow down for another
- Make sure previewer still works on Android
=> When application is running outside previewer set a flag early on so inspection code doesn't slow down startup

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8902.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8902.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
We need to makse sure that if the bounds of the UICollectionView changes, for example on orientation changes we need to tell our layout and our cells to update base on the new size.
- fixes #8902 
None
- iOS
CollectionView layouts should update on rotation changes
Not applicable
Check the issue 8902 rotate the device check the UI for the Items on the CarouselView updates to the correct size.
=> [iOS] Update CollectionView constrains when Bounds changes

.nuspec/Xamarin.Forms.targets
Add a condition that prevents the execution of the XamlC task when a build is performed for the Live Unit Testing feature of Visual Studio.
- fixes #7862
None
None
Not applicable
=> Disable XamlC task for VS Live Unit Testing

Xamarin.Forms.ControlGallery.Android/Tests/Issues.cs, Xamarin.Forms.Platform.Android/Extensions/ToolbarExtensions.cs, Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs
Revert to always presorting MenuItems and just adding them in sorted order. Android doesn't react very will when you use a really high priority number
- fixes #9185
- Android
- test a few CG pages with toolbar items make sure the display/sort correctly
=> Don't use priority parameter with menu parameter

Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs
The swipe **threshold** set how far the user must swipe before execute a SwipeItem command (Execute Mode).
We used a fixed value to set the swipe threshold which is not correct in all cases. This PR applies changes to set the swipe threshold to the 80% of the SwipeView size. 
None
- iOS
- Android
None
Not applicable
Use any SwipeView sample in a simulator device with large screen.
=> [Android, iOS] Improve the swipe threshold used in Execute Mode

Xamarin.Forms.Core/Element_StyleSheets.cs, Xamarin.Forms.Core/MergedStyle.cs, Xamarin.Forms.Xaml.UnitTests/Issues/Gh2678.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh2678.xaml.cs, Xamarin.Forms.Xaml.UnitTests/Issues/Gh8936.xaml.cs
- fixes #2678
None
None
Not applicable
=> [CSS] reapply Stylesheet on StyleClass changes

Xamarin.Forms.Platform.Android/Forms.cs, Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj
Context: https://github.com/xamarin/Xamarin.Forms/pull/8858
After merging from 4.4.0, etc. this class came back.
@kingces95 did not want to remove the `Anticipator.cs` file. Since
`Xamarin.Forms.Platform.Android.csproj` is now a short-form MSBuild
project, you have to add an explicit:
`<Compile Remove="Anticipator.cs"/>` to remove it.
None
None
- Android
None
Not applicable
CI should be OK
=> [android] remove the Anticipator for 4.5.0 and master

Xamarin.Forms.Platform.Android/PopupManager.cs
4.4.0 breaks Alerts, ActionSheets, and Prompts for pre-AppCompat Android (i.e., apps which use `FormsApplicationActivity` instead of `FormsAppCompatActivity`). These changes add proxy classes for dialog building which choose the correct dialog classes based on the activity type being used. This fixes the crashes in legacy apps while allowing AppCompat apps to use the new dialogs.
- fixes #9214
None
- Android
None
Not applicable
Automated tests for AppCompat; for legacy apps, set the `FORMS_APPLICATION_ACTIVITY` compile directive in the Control Gallery on Android, run the gallery, and navigate to the DisplayAlert gallery. f you can display alerts without crashing, the changes have worked.
=> Add intermediate dialog classes to handle legacy/appcompat dialog

.nuspec/Xamarin.Forms.nuspec, PagesGallery/PagesGallery.UWP/PagesGallery.UWP.csproj, Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj, Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj, build.cake
Bump WinUI to latest released version
- UWP
- make sure you can install nugets into VS2017 and VS2019 and that everything runs
=> Bump WinUI Nuget version if you are using Min target >= 16299

Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs
The `SwipeView` closes automatically when scrolling. It works correctly as long as the start of the scroll is not performed on a `SwipeItem`, in that case it does not work on **Android**.
This PR applies changes to fix this issue.
None
- Android
None
Launch Core Gallery and navigate to the SwipeView samples gallery. Select a sample where SwipeView is used with scroll (BindableLayout, ListView, CollectionView, etc). Open a SwipeView and start the scroll clicking on a SwipeItem. If the SwipeView closes when scrolling, the test has passed.
=> [Android] Fix issue automatically closing the SwipeView when scrolling

Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj
Because of visual differences that occur when setting TargetPlatformVersion to 18362 we should be testing our CG against 18362 . Otherwise we aren't getting the full truth when trying to fix issues
https://github.com/xamarin/Xamarin.Forms/pull/9211#pullrequestreview-344336372
- UWP
- Make sure the gallery runs
=> Bump CG to 18362 for consistency of testing

Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutContentRenderer.cs
Make create shell table view controller virtual on the ShellFlyoutContentRenderer so users can override and supply their own
Changed:
Make CreateShellTableViewController virtual
```C#
class ShellFlyoutContentRenderer
{
protected virtual ShellTableViewController CreateShellTableViewController()
```
- iOS
=> Make create shell table view controller virtual

Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/CustomSwipeItemGallery.cs, Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/NoIconTextSwipeItemGallery.cs, Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeViewGallery.cs, Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs
Centered text and icon in SwipeItem. In case of using a SwipeItem only with text or icon, always center the content (text or icon).
None
- iOS
- Android
None
Launch Core Gallery and navigate to the _"No Text or Icon"_ custom SwipeItem sample.
=> Centered text and icon in SwipeItem

.nuspec/proguard.cfg
Tell Proguard to keep classes around related to our Alert Dialog
- fixes #9031
- Android
- enable proguard on gallery and full linking
or
- recreate issue in a new project and then add the nuget
=> Add Alert Dialog Classes to Proguard.cfg file

Xamarin.Forms.Core.UnitTests/ShellModalTests.cs, Xamarin.Forms.Core.UnitTests/ShellTests.cs, Xamarin.Forms.Core/Shell/ShellSection.cs
During the restructuring of navigation to handle modals the code that applies query string parameters during basing navigation was lost
- fixes #9344 
=> Query parameters were not being applied during simple navigation

Xamarin.Forms.Core/IndicatorView.cs, Xamarin.Forms.Platform.Android/CollectionView/IndicatorViewRenderer.cs
Center indicators on IndicatorView by default. 
On Android API 29 the last item get shrank,   
- fixes #8911 
- fixes #8934 
None
- Android
Should center items by default without HorizontalOptions="Center" .
Last indicator shouldn't be smaller.
Before
After
Not applicable
Run IndicatorsSample on Android
=> [Android] Fix sizing and position on Android of the Indicators

Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs
Refresh main page on activity resume if main page has been changed when activity was paused
In #4707 I added a condition to protect activity to app state change when activity is in background.
It was to fix some lifecycle and dispose issue which caused invalid app state (navigation out of sync, wrong renderer dispose and other nasty things).
This caused a regression for the persons who changed the main page in the OnPause method or after in the lifecycle.
So this change add a flag for this case, and force a main page change during resume if the flag has been set.
- fixes #9093
- fixes #5236
None
- Android
None
Not applicable
Use reproduction case in #9093.
=> [Android] Refresh main page on activity resume if necessary

Xamarin.Forms.Platform.UAP/TitleViewManager.cs
Added null-checks for _titleViewRendererController.TitleViewPresenter and _titleViewRendererController.CommandBar that can be null if there is no corresponding part of the MasterDetailControl template
- fixes #8564 
None
- UWP
None
Not applicable
set _titleViewRendererController.TitleViewPresenter and _titleViewRendererController.CommandBar to null and see that exception goes away
=> fix for #8564 exception "Delegate to an instance method cannot have null 'this'"

build.cake
Versioning the Nuget was moved to msbuild and this code just wasn't deleted when that change was made
- make sure cake generates nugets correctly
- make sure build runs
=> Remove gitversion from cake and fix UWP nugets

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8203.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/Items/SelectableItemsView.cs, Xamarin.Forms.Platform.UAP/CollectionView/SelectableItemsViewRenderer.cs
CollectionView in multi-select mode does not have a mechanism for atomically updating multiple selected items at once with a single change notification. This isn't an issue for platforms where only one item can be added/removed from the selection at a time, but UWP allows multiple selection (e.g., while holding Shift). We need to support that (and possible future multiple-simultaneous-select methods on other platforms). Because of that mechanism, the UWP selection was also firing many extra `SelectionChanged` events for each update of the selected items.
This change adds a method to SelectableItemsView which allows for a list of selected items to be passed in as one atomic update to SelectedItems (while preserving binding to the underlying list).
- fixes #8203
Added: …
=> Allow multiple selection updates with one notification in CollectionView

Xamarin.Forms.ControlGallery.Android/LinkDescription.xml, Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj, Xamarin.Forms.ControlGallery.Android/_9087CustomRenderer.cs, Xamarin.Forms.ControlGallery.WindowsUniversal/Xamarin.Forms.ControlGallery.WindowsUniversal.csproj, Xamarin.Forms.ControlGallery.WindowsUniversal/_9087CustomRenderer.cs, Xamarin.Forms.ControlGallery.iOS/CustomRenderers/_9087CustomRenderer.cs, Xamarin.Forms.ControlGallery.iOS/LinkDescription.xml, Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9087.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/TemplatedItemViewHolder.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemContentControl.cs, Xamarin.Forms.Platform.iOS/CollectionView/TemplatedCell.cs
CollectionView implementations are setting the `BindingContext` of their templated views _after_ creating the renderers, which means that
- The bound data is not available to renderers during `OnElementChanged`
- Each renderer is effectively doing at least two layouts (once for empty data and once for actual data)
Theses changes move the setting of the `BindingContext` earlier in the cell binding lifecycle, which addresses both problems.
- fixes #9087
None
- iOS
- Android
- UWP
None
Not applicable
=> Set BindingContext for CollectionView cells earlier

Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/MasterDetailPageiOS.cs, Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/MasterDetailPage.cs, Xamarin.Forms.Platform.iOS/Renderers/PhoneMasterDetailRenderer.cs
Something that bugs me is the fact that iOS's MasterDetailPage doesn't fade the Detail page when opening the Menu. This leads to a bad UX, since both the menu and the detail are shown at the same z-axis level, with no "background feel" applied to the Detail page. 
Android's implementation doesn't suffer from this, **neither does iOS Shell implementation**.
Once I noticed Shell "fixed" this behavior, I wanted to do the same for the MasterDetailPage on Xamarin.Forms for iOS.
So this PR pretty much uses the same logic used in iOS Shell to fade the Detail page when MasterDetail menu is opened.
- iOS
The visual rendering for MasterDetailPage would change for every Xamarin.Forms application.
I have 2 specific points that I would like to get a review:
* Since this would be a visual breaking …
=> Apply fading effect on DetailPage for MasterDetailPage on iOS

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8777.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs
Allow to use SwipeItem only with text or icon.
- fixes #8777
- fixes #9108
- fixes #9271
None
- iOS
- Android
None
`System.NullReferenceException` has been thrown on iOS, no centered icon on Android.
Launch Core Gallery and navigate to the issue 8777. Open the SwipeView and verify that only appears the centered icon.
=> Allow to use SwipeItem only with text or icon

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7393.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/CollectionView/ObservableGroupedSource.cs
Starting from a completely empty grouped CollectionView on iOS and adding a group results in an internal consistency exception. These changes avoid that by using ReloadData() in that circumstance, which allows the UICollectionView to get its internal accounting correct.
- fixes #7393
None
- iOS
None
Not applicable
Automated test
=> Avoid exception moving from empty to populated grouped CollectionView

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6784.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellItemRenderer.cs
When `SelectedViewController` is called for `MoreNavigationController`, register for `DidShowViewController` to make it possible to set `ShellItem.CurrentItem` when selecting shell sections aggregated in more tab. Implementation is based on this [SO](https://stackoverflow.com/questions/5803352/didselectviewcontroller-not-getting-called-when-in-more-section) thread.
~~Automated test is skipped because lack of information (is there any guidance available?) of how to setup UI tests for XF.~~
- fixes #6784
None
- iOS
Check #6784.
=> Use the MoreNavigationController DidShowViewController callback for shell sections

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9355.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/VisualElementPackager.cs
PR #8745 introduce a regression which for some page structure cause a crash during dispose.
This PR add a dispose check to prevent the crash.
- fixes #9355 
None
- Android
None
Not applicable
Run the UI Test case included in this PR
=> [Android] Add dispose check to prevent crash

Xamarin.Forms.ControlGallery.WindowsUniversal/CustomRenderers.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4459.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4459.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.UAP/BoxViewBorderRenderer.cs, Xamarin.Forms.Platform.UAP/BoxViewRenderer.cs, Xamarin.Forms.Platform.UAP/BoxViewRenderer2.cs, Xamarin.Forms.Platform.UAP/Properties/AssemblyInfo.cs
Xamarin forms BoxView supports individual corner radius settings but the UWP BoxViewRenderer was using the Rectangle class as it's native control which does not.  This PR changes BoxViewRenderer to use the UWP Border class instead, which fully supports a unique radius for each corner.
In researching the various ways in UWP to support this, switching to border control seemed the simplest and least likely solution to cause regressions.  Other solutions I found was to us a clipping rectangle, but that seemed like it would have the same issue of only a radius setting shared on all corners.  There was also a solution that used a brush to achieve this effect, but also seemed more complicated then needed.
My only concern with switching to border is if there would be any performance impact over …
=> Fix 4459 - Update UWP BoxViewRenderer to fully support corner radius

Xamarin.Forms.ControlGallery.Android/Tests/CollectionViewTests.cs, Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj, Xamarin.Forms.Platform.Android/CollectionView/NongreedySnapHelper.cs
The NongreedySnapHelper class uses APIs which aren't available in earlier versions of Android. These changes rewrite that class to use APIs available in earlier versions.
- fixes #9030
None
- Android
None
Not applicable
=> Rewrite NongreedySnapHelper with older APIs

Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs
Fixed SwipeItem tap issue on Android device. When tapping, in certain devices (not happen in emulators) the offset value is validated. Without swipe, just tapping the point when doing touch down and touch up is the same and will break the touch events (execute commands, etc). Added extra validation to verify if the SwipeView is open or closed.
Tested with devices running Android 6, 7.1 and 10.
- fixes #9028
None
- Android
None
Not applicable
Test using any SwipeView sample but must be tested using a **device**.
=> [Android] Fixed SwipeItem tap issue on Android device

Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs, Xamarin.Forms.Platform.Android/ViewExtensions.cs, Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs
Changed code to avoid the usage of some APIs that require a specific API Level on Android.
- addresses parts of #9030
None
- Android
None
Not applicable
Verify the Build and try any SwipeView sample on Android <6.0.
=> [Android] Changes in SwipeView to avoid the use of APIs that require a specific API level

Xamarin.Forms.ControlGallery.Android/CustomRenderers.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9360.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs, Xamarin.Forms.Platform.Android/Extensions/JavaObjectExtensions.cs, Xamarin.Forms.Platform.Android/Extensions/ToolbarExtensions.cs, Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs
- allow navigationpagerenderer to override loading of menu item icons
- when a single item is updated just update the one menuitem opposed to rebuilding the list
- fix a timing issue when loading async drawables which sometimes caused the menuitem to be disposed of and would crash silently with a MenuItemDisposed error
- fixes #9360
- fixes #9278
- Android
- UI tests all pass
=> Let users override behavior on Navigation Renderer

.nuspec/Xamarin.Forms.nuspec, Xamarin.Forms.Maps.UWP/Xamarin.Forms.Maps.UWP.csproj
For some reason when the Maps UWP project builds it started packaging up the layout files included in the platform project into the generated PRI 
Here's the point in time on the build server where this started happening
https://github.com/xamarin/Xamarin.Forms/pull/9327
- UWP
- downloads nugets, installs maps and forms into project, make sure UWP project runs
=> Disable generate library layouts on maps project

.nuspec/Xamarin.Forms.Maps.nuspec, .nuspec/Xamarin.Forms.nuspec, UWP.Build.props, UWP.Build.targets, Xamarin.Forms.Core/ExportFontAttribute.cs, Xamarin.Forms.Maps.UWP/Xamarin.Forms.Maps.UWP.csproj
UWP 16299 nuspec incorrectly copying over NS 1.0 core libraries instead of NS 2.0 versions
- pull down nuget, install into UWP project, set to release, and make sure it builds/releases
=> Fix UWP Nuspec to copy correct NS version

.nuspec/Xamarin.Forms.nuspec, UWP.Build.props, UWP.Build.targets, build/steps/build-windows.yml
Copy xaml files from obj folder to artifacts folder to be used by the nuspec
=> Fix nuspec to copy xaml files from obj directory

.nuspec/Xamarin.Forms.nuspec
Add prompt dialog to nuspec for VS 2017 Compat
- UWP
- Install nugets into VS 2017
=> Add prompt dialog to nuspec for VS 2017 Compat

Xamarin.Forms.Platform.UAP/Forms.cs
If the merged dictionaries already contains the UWP Forms Resources, don't attempt to load them again; this will cause a COM exception.
This is basically just taking the logic from UWP `Platform(Page)` and applying it to `Forms.Init()`.
- fixes #9335
None 
- UWP
None
Not applicable
Create a Forms project with a UWP head. Add a separate Forms project with a base class inheriting from `ContentPage`. In the main Forms project, set your main page to a page which derives from your base class in the other project. Run the application.
Without this fix, the application should crash. With this fix, it should run.
=> Don't attempt to merge UWP resources if they've already been added

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterView.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/HeaderFooterGalleries/HeaderFooterView.xaml.cs, Xamarin.Forms.Platform.Android/CollectionView/StructuredItemsViewAdapter.cs
When creating a simple Forms view (non-template) header/footer for a CollectionView on Android, the header/footer do not inherit the binding context of the CollectionView. These changes fix that issue, so that bindings in the header/footer have a context.
- fixes #8700
None
- Android
None
Not applicable
Repurposing an existing automated test.
=> Propagate CollectionView BindingContext to Header/Footer on Android

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8899.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.UAP/CollectionView/GroupedItemTemplateCollection.cs, Xamarin.Forms.Platform.iOS/CollectionView/GroupableItemsViewController.cs
Clearing out the groups in an ObservableCollection which is the source for a grouped CollectionView throws an exception on iOS and UWP.
These changes fix the issue on iOS by verifying the existence of a group before attempting to measure the group header or footer.
These changes fix the issue on UWP by not manually resetting the internal group list while handling its Reset action.
- fixes #8899
None
- iOS
- UWP
None
Not applicable
Automated test for iOS; for UWP, run Issue 8899 in the Control Gallery.
=> [iOS] Verify first group exists before measuring its header

Xamarin.Forms.Platform.Tizen/Native/CollectionView/CollectionView.cs, Xamarin.Forms.Platform.Tizen/Native/CollectionView/GridLayoutManager.cs, Xamarin.Forms.Platform.Tizen/Native/CollectionView/ItemTemplateAdaptor.cs, Xamarin.Forms.Platform.Tizen/Native/CollectionView/LinearLayoutManager.cs
Resolves bug #8586
To prevent sizeless layout requests when the CollectionView is in a hiding state.
Resolves bug #8587
Remove events on unbinding in CollectionView
- fixes #8586 #8587 
- Tizen
=> Fix 8586 8587 - [Tizen] Added guard for CollectionView

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9092.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.GTK/Renderers/ButtonRenderer.cs
Using buttons on page without navbar causes them to shrink to 1px width on GTK. Two things leading to this:
If a button desired size is bigger than available space, button [would shrink to width constraint](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.GTK/Extensions/WidgetExtensions.cs#L39) and would stay this way on next cycles, even if it could get more space;
Each page starts to allocate children sizes with its initial size 1px X 1px, on next cycles getting real window size. Pages with navbar would subtract navbar height from available size and get negative number, so they won't ask children to allocate space on this cycle. Pages without any navbar would calculate its children sizes on page 1px wide, stucking buttons with width=1px for all next cycles. …
=> [GTK] Fix button shrinking

Xamarin.Forms.Platform.WPF/Controls/FormsProgressRing.xaml, Xamarin.Forms.Platform.WPF/Controls/FormsProgressRing.xaml.cs, Xamarin.Forms.Platform.WPF/Renderers/ActivityIndicatorRenderer.cs, Xamarin.Forms.Platform.WPF/Xamarin.Forms.Platform.WPF.csproj
Replaces the default ProgressBar with a proper Activity spinner to show indeterminate activity. Style is consistent with Windows features and is the same as used throughout Windows 8 and above.
- fixes #9372 
None
- WPF
Before the change an ActivityIndicator is rendered as a progress bar with indeterminate style which doesn't fit with the look across multiple platforms or the control used in various Windows components. After the change the ActivityIndicator is rendered as a circular animated control with multiple dots chasing around. This is similar to the control used on UWP but works on any WPF platform.
Before:-
After:-
The new behaviour can be tested on the existing control gallery project.
=> Replacement ActivityIndicator for WPF

Xamarin.Forms.Core.UnitTests/MotionTests.cs, Xamarin.Forms.Core/Animation.cs, Xamarin.Forms.Core/AnimationExtensions.cs, Xamarin.Forms.Platform.Android/AndroidTicker.cs, Xamarin.Forms.Platform.Android/Forms.cs, Xamarin.Forms.Platform.Android/FormsApplicationActivity.cs, Xamarin.Forms.Platform.Android/PowerSaveModeBroadcastReceiver.cs
Modify animation helpers to return `true` (i.e., "canceled") when force-finishing animations because the ticker is system-disabled; this allows users of the animation methods to react accordingly when their awaited looped animations are returning immediately because animations have been disabled by the system (e.g., because of power saving mode).
These changes also add a public method to the Animation class allowing the user to determine if animations have been disabled by the system.
Finally, for newer API levels (26+), the Android power saving mode check no longer just disables the animations; rather, it makes a check with AreAnimationsEnabled; this allows the animations to continue working if the power saving mode doesn't actually disable them (e.g., on Samsung devices with "medium" …
=> Improve animation behavior with regard to power saving mode

Xamarin.Forms.DualScreen.UnitTests/TwoPaneViewNotSpannedTests.cs, Xamarin.Forms.DualScreen.UnitTests/TwoPaneViewSpannedTests.cs, Xamarin.Forms.DualScreen.UnitTests/Xamarin.Forms.DualScreen.UnitTests.csproj, Xamarin.Forms.DualScreen/DualScreenInfo.shared.cs, Xamarin.Forms.DualScreen/DualScreenService.android.cs, Xamarin.Forms.DualScreen/DualScreenService.uwp.cs, Xamarin.Forms.DualScreen/IDualScreenService.shared.cs, Xamarin.Forms.DualScreen/NoDualScreenServiceImpl.shared.cs, Xamarin.Forms.DualScreen/Properties/AssemblyInfo.cs, Xamarin.Forms.DualScreen/TwoPaneView.shared.cs, Xamarin.Forms.DualScreen/TwoPaneViewLayoutGuide.shared.cs, Xamarin.Forms.DualScreen/Xamarin.Forms.DualScreen.csproj
Fix TPV to always take into account the hinge regardless of size and position
- If any layout is spanned over the hinge it'll correctly size pane1/pane2
- If the hinge is only overlapping the tpv one one of the sides but the tpv doesn't span across the hinge then this will add padding to the tpv so content doesn't flow underneath the hinge
- Added constructor for DualScreenInfo to take a layout so users can supply whatever layout they want to to DualScreenInfo and it will return the calculations for that layout relative to the Hinge
Added:
- public DualScreenInfo(Layout layout)
=> Fixes TPV so it works anywhere on the screen

Xamarin.Forms.Controls/GalleryPages/MediaElementDemoPage.cs, Xamarin.Forms.Platform.Android/FastRenderers/MediaElementRenderer.cs, Xamarin.Forms.Platform.UAP/MediaElementRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/MediaElementRenderer.cs
- fix uwp to set volume after media has loaded otherwise it always starts at 1
- check to see if they've used an empty string with ms-appx:///
- add some null checks on android
- Android
=> Fix UWP volume, mediasource exception, android position

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2674.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/Picker.cs
Adding a null check for items in Picker source and add Empty string for any null item
- fixes #2674 
None
If there are null items in Picker source list, UI will display empty entries instread of crashing
Not applicable
Tested in Android simulator by running test before and after fix
=> Adding null check for picker items

Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs
Added extra null-check
- fixes #9435 
None
- iOS
No crash
Not applicable
- Open screen with a scroll view. Create a delayed task that must scroll to some element inside the scroll view after some time (e.g. 5 seconds). Run that task.
- Leave the page with the scroll view.
- After 5 seconds a NullRefException will occur.
=> [iOS] NullReferenceException at ScrollViewRenderer.cs

Xamarin.Forms.Platform.iOS/Renderers/PhoneMasterDetailRenderer.cs
Fix NRE caused by calling Layout Children method without having the Renderer created yet for the the detail page. 
- fixes failing test 2964 on iOS
None
- iOS
None
Not applicable
iOS test for issue 2964 should pass
=> [iOS] Fix NRE if the detail renderer wasn't created

Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs
When we fire the completed event on the entry on iOS we could also be disposed , so the Element will be set to null.  Since in that event we were checking the ReturnType it could throw a NRE
- fixes #9460 
None
- iOS
None
Not applicable
on App.cs use this code :
```
var page = new ContentPage();
var entry = new Entry();
entry.Completed += (s,e) => SetMainPage(CreateDefaultMainPage());
page.Content = entry;
MainPage = page;
```
=> [iOS] Fix NRE when Entry Completed fires

Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs
Amended iOS version check (should be check for 13 or newer instead of 11 or newer because systemBackground color was introduced in iOS 13 SDK.)
- fixes #9499 
None
- iOS
No crash on iOS 12 during SwipeView using
Not applicable
Please find the steps attached to the bug ticket.
=> [Bug][iOS] SwipeView MonoTouchException in iOS 12 in Forms 4.5-pre3

Xamarin.Forms.Core/FontImageSource.cs, Xamarin.Forms.Xaml.UnitTests/FontImageExtension.xaml, Xamarin.Forms.Xaml.UnitTests/FontImageExtension.xaml.cs
The default size for font was originally set to 30 and removing it causes a regression. Especially on android because it tries to render the font at a size of zero which causes an exception.
If setting default Fontsize isn't an option then we will need to set it to something on Android when it's rendering the image so that it doesn't regress and actually renderers like other platforms
- fixes #9371
https://github.com/xamarin/Xamarin.Forms/pull/8063/files#diff-286d535dfc3a7d8dda9c1f9a78e8130aL28
- iOS
- Android
- UWP
=> Add default fontsize back to size BP on FontImageSource

Xamarin.Forms.Controls/GalleryPages/VisualStateManagerGalleries/StateTriggerEventsGallery.xaml, Xamarin.Forms.Controls/GalleryPages/VisualStateManagerGalleries/StateTriggerEventsGallery.xaml.cs, Xamarin.Forms.Controls/GalleryPages/VisualStateManagerGalleries/StateTriggerGallery.cs, Xamarin.Forms.Controls/GalleryPages/VisualStateManagerGalleries/StateTriggerToggleGallery.xaml, Xamarin.Forms.Controls/GalleryPages/VisualStateManagerGalleries/StateTriggerToggleGallery.xaml.cs, Xamarin.Forms.Controls/GalleryPages/VisualStateManagerGalleries/StateTriggersDirectlyOnElements.xaml
I have done some StateTriggers (AdaptiveTriggers) tests and this PR just adds more samples to Core Gallery testing cases not added before (use of events, use of TargetName, etc).
None
- Core
None
Not applicable
Launch Core Gallery and navigate to the StateTriggers samples. Now, you can find new samples test the events, etc.
=> Added more StateTriggers samples to Core Gallery

Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGalleries/SearchBariOS.cs, Xamarin.Forms.Controls/GalleryPages/PlatformSpecificsGallery.cs, Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/SearchBar.cs, Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/UISearchBarStyle.cs, Xamarin.Forms.Platform.iOS/Extensions/Extensions.cs, Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs
Expose the UISearchBarStyle enum through a platform-specific. See https://developer.apple.com/documentation/uikit/uisearchbar/style for details on the enum values.
- N/A
Added:
- public static class Xamarin.Forms.PlatformConfiguration.iOSSpecific.SearchBar
- public enum Xamarin.Forms.PlatformConfiguration.iOSSpecific.UISearchBarStyle
- iOS
Users must set the value to Minimal for a visual change to occur.
iOS 12:
iOS 13:
On iOS 13, the appearance of the UISearchBar changed, and with it the effects of the SearchBarStyle. While they are identical on a white background, Prominent is a little translucent and Minimal is transparent.
Control Gallery -> Platform Specifics -> SearchBar (iOS)
=> [iOS] Expose UISearchBarStyle through platform-specific

Xamarin.Forms.Platform.Android/Extensions/TextViewExtensions.cs
When using the profiler, I noticed that the RecalculateSpanPositions method caused a lot of string  allocations when accessing to the TextView layout.
In reordering the conditions, this method can be a lot of faster, because in most cases now, this condition will never be evaluated.
So less memory allocation, less GC and more performance.
I also removed the unused ToString call.
None
None
- Android
None
Not applicable
None
=> [Android] Optimize RecalculateSpanPositions method

Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8693.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselItemsGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselXamlGallery.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/IndicatorCodeGallery.cs, Xamarin.Forms.Controls/GalleryPages/IndicatorViewGalleries/IndicatorsSample.xaml, Xamarin.Forms.Controls/GalleryPages/IndicatorViewGalleries/IndicatorsSample.xaml.cs, Xamarin.Forms.Core/IndicatorView.cs, Xamarin.Forms.Core/Items/CarouselView.cs
CarouselView should provide a way to link to a IndicatorView. 
fixes #8992 
Added:
- `public IndicatorView IndicatorView`
None
Not applicable
Try create a custom IndicatorView and provide an override to link to other control.
=> [Core] Allow CarouselView to specify IndicatorView 

Environment.Build.props, Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj, azure-pipelines.yml
- Default locally to running with fast renderers
- don't set /p:DefineConstants as part of the YAML msbuild command because that doesn't allow us to configure the DefineConstants locally. It just replaces them all
- Android
- make sure that CI is indeed still building all the correct permutations of renderers and that ui tests are running
=> Default locally to fast renderers and don't overwrite DefineConstants with msbuild properties

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9196.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9196.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs, Xamarin.Forms.Platform.iOS/CollectionView/StructuredItemsViewController.cs
The EmptyView's UIView frame was not being set immediately upon being added to the UICollectionView, which resulted in layout exceptions if the EmptyView contained a StackLayout with Padding set. 
These changes update the frame immediately after adding the UIView, preventing the issues (and saving an extra layout cycle). These changes also clean up the sizing implementation so that the ItemsViewController doesn't need to know about header/footer tags.
- fixes #9196 
None
- iOS
None
Not applicable
=> Set frame for EmptyView when adding it to UICollectionView

Xamarin.Forms.Platform.Android/CollectionView/IndicatorViewRenderer.cs
Fixes issue qhen changing Shell tabs with indicators.
- fixes #9473 9473
- fixes comment https://github.com/xamarin/Xamarin.Forms/pull/8709#issuecomment-581092711
None
- Android
When changing tabs on a Shell with indicators the position should be kept.
Not applicable
Paste code, and check if changing tabs the indicator stays in the correct position
```
var shell = new Shell();
var tabBar = new TabBar();
var tab = new Tab { Title = "Page 1" };
var tab1 = new Tab { Title = "Page 2" };
tab.Items.Add(new Xamarin.Forms.Controls.GalleryPages.CollectionViewGalleries.CarouselViewGalleries.IndicatorCodeGallery());
tab1.Items.Add(new Xamarin.Forms.Controls.GalleryPages.CollectionViewGalleries.CarouselViewGalleries.IndicatorCodeGallery());
tabBar.Items.Add(tab);
tabBar.Items.Add(tab1); …
```
=> [Android] Remove dead code, fix the indicator position on load

Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
Fixed regression bug on Mac OS. Default color is not converted to Black for macOs.
- fixes #9526
None
- macOS
Default text color of Labels on Mac became BLACK instead of transparent.
Create a content page with a label inside. Run the sample on MacOs. See that label is invisible.
=> [Bug] macOS: 4.4->4.5 regression, labels are invisible (same TextColor as background)

Xamarin.Forms.DualScreen/Xamarin.Forms.DualScreen.csproj
Duplicate NS 2.0 imports on DualScreen breaking intellisense on VS MAC
- verify intellisense still works and DualScreen project is still deploying ok
=> Remove duplicate NS 2.0 on vsmac

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9419.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/Internals/ToolbarTracker.cs, Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs, Xamarin.Forms.Platform.Android/Extensions/ToolbarExtensions.cs, Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs
The NavigationPageRenderer doesn't track the removal of an ToolbarItem.
If the user decide to remove an item, the NavigationPageRenderer will rebuild the menu but not unsubscribe PropertyChange EventHandler subscribed in the ToolbarExtensions class.
When the renderer is disposed it try to dispose items by unsubscribe it, but in this case, they were deleted, so they aren't disposed correctly.
To fix that we have to track when item are removed, but we can't do that with the current event CollectionChange on the ToolbarTracker. So I introduced a new collection to store the current toolbar items.
- fixes #9419 
None
- Android
None
Not applicable
Run UiTest included in this PR
=> [Android] Properly unsubscribe ToolbarItem on removal

Xamarin.Forms.Controls/GalleryPages/TwoPaneViewGalleries/DualScreenInfoGallery.xaml, Xamarin.Forms.Controls/GalleryPages/TwoPaneViewGalleries/DualScreenInfoGallery.xaml.cs, Xamarin.Forms.Controls/GalleryPages/TwoPaneViewGalleries/TwoPaneViewGallery.cs, Xamarin.Forms.Controls/GalleryPages/VisualStateManagerGalleries/DualScreenStateTriggerGallery.xaml, Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj, Xamarin.Forms.DualScreen/DualScreenInfo.shared.cs, Xamarin.Forms.DualScreen/DualScreenService.android.cs, Xamarin.Forms.DualScreen/DualScreenService.uwp.cs, Xamarin.Forms.DualScreen/TwoPaneViewLayoutGuide.shared.cs, Xamarin.Forms.DualScreen/WindowSpanModeStateTrigger.shared.cs, Xamarin.Forms.Platform.Android/DualScreen/IDualScreenService.cs, Xamarin.Forms.Platform.Android/Forms.cs, Xamarin.Forms.Platform.UAP/DualScreen/IDualScreenService.cs, Xamarin.Forms.Platform.UAP/Properties/AssemblyInfo.cs, Xamarin.Forms.Platform.UAP/WindowsDeviceInfo.cs
- IsLandscape wasn't working correctly on Android when not on a dual screen device
- Pulled interfaces into UWP and Android so the platform code could check for an implementation of IDualScreenService and then use that for reporting back landscape/portrait since those values get reported back incorrectly when spanned
- removed IDisposable from DualScreenService because it's a singleton that never goes away
- Fixed issue where relative contentarea used for region calculation opposed to screen relative position
- Changed DualScreenInfo to take Visualelement so it can work for anything
- SpanModeStateTrigger changed to apply to VisualElement it's attached to
- Added WindowSpanModeStateTrigger which watches to see if the entire window has changed to being spanned
- DualScreenInfo now takes a …
=> Fix Landscape Calculations and use DualScreenServices in platform code

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/IndicatorCodeGallery.cs, Xamarin.Forms.Platform.Android/CollectionView/IndicatorViewRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/IndicatorViewRenderer.cs
Make a UIPagerControl that can renderer squares instead of circles 
- fixes #8913
- fixes #8933
None
- iOS
When specifying IndicatorShape as Square it should show squares on tie UIPagerControl
Before:
After:
Visit CarouselView Gallery, Enable IndicatorVIew, click  IndicatorView sample , then change the IndicatorTemplate to Square
=> [iOS] Fix square shape and indicator size on IndicatorView 

Xamarin.Forms.Core.UnitTests/ShellTests.cs, Xamarin.Forms.Core/Shell/ShellContentCollection.cs, Xamarin.Forms.Core/Shell/ShellItemCollection.cs, Xamarin.Forms.Core/Shell/ShellSectionCollection.cs, Xamarin.Forms.sln.DotSettings
When clearing out shell collections the removal of those elements wasn't being propagated out correctly
=> Propagate cleared shell elements correctly

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9329.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs
Disable swipe in SwipeView using the VisualElement IsEnabled property.
- fixes #9329
None
- iOS
- Android
- UWP
None
After
=> Disable swipe in SwipeView with IsEnabled property

Xamarin.Forms.Platform.UAP/WebViewRenderer.cs
**If you plan to make service releases for previous versions of Xamarin.Forms, please, apply this fix to all of them, cause this bug is really-really old and exists since version 2.4.0.**
The problem with the WebView appeared because of `var internalWebView` being garbage-collected. This variable is created inside a method, and once the method is done, the variable may be garbage-collected, and may not be (you never know when it happens, but it happens more often on devices with less memory, I guess). 
Putting this `internalWebView` into a private field fixes this bug.
- fixes #6679 [Bug] WebView UWP not displaying
None
- UWP
None
Not applicable
If you put `GC.Collect()` right after call to `LoadHtml()` (that is [at this line](https://github.com/xamarin/Xamarin.Forms/blob/bd31e1e9fc8b2f9ad …
=> fixes #6679 [Bug] WebView UWP not displaying

Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs
On iOS call UpdateToolBarItems after the page is set on ShellPageRendererTracker. The page is set after an animation effect occurs so the state of the active page on ShellPageRendererTracker is out of sync when appearancechanged notifications are fired
- fixes #9483
- iOS
=> Call UpdateToolBarItems after page is changed

build.cake
Fix build.cake so that it works with the packageVersion parameter
- fixes #9523 
- ensure this works
`./build.ps1 -Target NugetPack -ScriptArgs '-packageVersion="9.9.9-custom"'`
- ensure this still works
`./build.ps1 -Target NugetPack`
=> Fix packageVersion parameter on build.cake

Xamarin.Forms.Core.UITests.Shared/Tests/CollectionViewUITests.cs
These changes add more information to the TestItemsPosition method when a test fails. They also remove the scrolling from the test to make it more reliable.
=> Remove unreliable scroll from TestItemsPosition

Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewController.cs
If the user doesn't provide a template we might not have a View to apply a VisualState
None
None
- iOS
None
Not applicable
=> [iOS] Fix NRE when not using template on CarouselView

.nuspec/proguard.cfg
When 4.4.0 got merged up to 4.5.0 it replaced the support library versions with androidx when it should have just appended them 
- fixes #9696
- test nugets with #9696
=> Add non androidx classes back into Proguard File

Xamarin.Forms.Platform.Android/Renderers/BottomNavigationViewUtils.cs
#9187 broke the following UI tests on master
TabBottomIconsAndTitlesChange_google_pixel_2
AddAndRemovePages_google_pixel_2-8_1_0
BottomTabbedPageWithModalIssueTestsPopFromSecondTab_google_pixel_2-8_1_0
- All Green on Master
=> revert [Android] Fix BottomNavigationItemView issue with MasterDetailPage

Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs
If we aren't using a template we might not have a View to set a state
none
None
- Android
None
Not applicable
=> [Android] Fix NRE when setting the VisualState on the default cell

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselItemsGallery.cs, Xamarin.Forms.Platform.Android/CollectionView/SingleSnapHelper.cs
The SingleSnapHelper was providing the wrong postion, because it was incrementing by one even when getting to the end of the Collection. We should not increment if we are already on the last item.
- fixes #9020 
None
- Android
When getting to the last item and slide left , swiping back to the right should go to the previous item.
Not applicable
Go to CarouselItemsGallery, go to the last time, swipe left again, then swipe right it should go to the previous item, if you need to swipe 2 times the test failed.
=> [Android] Fix getting the position on SingleSnapHelper 

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselItemsGallery.cs, Xamarin.Forms.Core/IndicatorView.cs
The size of the IndicatorView is based on the number of indicators and the size and padding. When the Collection and respective count changes we need to invalidate so a new size is calculated
- fixes #9666 
None
- iOS
Indicators should appeared if setting the ItemSource of a CarousselView in a delayed fashion. 
Not applicable
Visit the IndicatorGallery, make sure you see the Indicators
=> [Core,iOS] Invalidate size when IndicatorView collection/count changes

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8902.xaml, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselCodeGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/PositionControl.cs, Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewController.cs, Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs
Better fix for orientation changes on CollectionView and CarouselView. Monitor the bound changes, for example when we change the orientation.
Also fixes when the visibility changes. Initially the bounds are something like 1,1 when visibility changes we set a new frame to the CollectionView.
- fixes #9583 
- fixes #9609
- fixes #8521
`ItemsViewController<TItemsView> `
Added:
- `protected virtual void BoundsSizeChanged();`
- iOS
CarouselView should update the item size when rotating the device.
Not applicable
Use issue 8902
=> [iOS] Update ItemsViewController constrains when bounds change

Xamarin.Forms.Platform.iOS/Renderers/MediaElementRenderer.cs
Fixed a MediaElement crash trying to reproduce a video from a URL without internet connection.
- fixes #9742
None
- iOS
None
Not applicable
Launch Core Gallery. Make sure you don't have internet connection on the device or simulator. Then, select the MediaElement sample and press the Play Button. If the video does not play but no error occurs (exception), the test has passed.
=> [iOS] Fix MediaElement crash opening URL without connection

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1658.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.MacOS/Cells/CellNSView.cs, Xamarin.Forms.Platform.MacOS/Renderers/ListViewRenderer.cs, Xamarin.Forms.Platform.iOS/EventTracker.cs
CellNSView was adding invisible TrackingClickNSView above all nested views to handle RightMouseDown and context actions. This prevented other gestures to work on Views inside ListItem.
This logic was moved to CellNsView itself.
Also NSGestureProbe now stops propagating event if it was handled by 
tapGestureRecognizer. Otherwise tap events was handled twice - by tapGestureRecognizer and ListView.ItemSelected.
- fixes #1658
None
MacOS
None
Not applicable
=> [macOS] Fix GestureRecognizer on ListView Item not working

Xamarin.Forms.Platform.MacOS/Renderers/SliderRenderer.cs
Replaced broken event handler by working Selector.
I believe regression was introduced in ae72c0adf7
- fixes #9748
None
- macOS
Slider provides consistent value.
Not applicable
1. Put Slider in XAML, name it (slider), set min/max values (from 0 to 100),
2. Bind slider.Value with property in ViewModel (for ex. SliderValue)
3. Bind Label.Text with slider.Value (Label.Text="{Binding Value, Source={x:Reference slider}}")
=> [Bug] [macOS] Slider doesn't update its value

.nuspec/Xamarin.Forms.nuspec, .nuspec/Xamarin.Forms.targets, Stubs/Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS (Forwarders).csproj, Xamarin.Forms.Maps.iOS/Xamarin.Forms.Maps.iOS.csproj, Xamarin.Forms.Material.iOS/Xamarin.Forms.Material.iOS.csproj, Xamarin.Forms.Platform.MacOS/Renderers/ListViewRenderer.cs, Xamarin.Forms.Platform.MacOS/Xamarin.Forms.Platform.macOS.csproj, Xamarin.Forms.Platform.iOS/Renderers/ActivityIndicatorRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs, Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj, azure-pipelines.yml, build.cake, build/steps/build-osx.yml, build/steps/build-windows.yml
Build different ios platform dlls for xcode10 and xcode11 compatibility
The problem with our previous approach for Xcode10 compatibility is that at runtime or link time VS 2017 will encounter types that it doesn't understand. 
So given the scenario of a Xamarin.Forms.iOS application built on VS2017 running on iOS13 you will hit exceptions if you encounter types that VS2017 doesn't understand
This PR doesn't build our DLL on VS 2017 it only if defs out any apis that are iOS13 specific which should produce a dll that will compile on VS2017 and then run/link successfully
I've also included an extra iOS build lane that installs all the VS 2017 sdks and compiles our control gallery to ensure we aren't exposing any APIS that VS 2017 doesn't understand
- iOS
- use this nuget with full linking on …
=> Ios 2017 compatible Xamarin.Forms.Platform.iOS

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6713.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8526.cs, Xamarin.Forms.Core/Page.cs, Xamarin.Forms.Core/PromptArguments.cs
Removes the optional parameters from the obsoleted methods to avoid the CS0121 error when using prompts.
- fixes #9171
Essentially none. Optional parameters are still compiled into non-optional ones, so this does not break ABI. As for API, the new signature still has all the optional parameters, so people still on the obsolete signature should not notice any difference. That is because they technically automatically migrate to the new signature.
Hope this makes sense...
Users upgrading should not notice anything. All parameters have the optional thing going all, transition should happen invisible.
=> [Bug] DisplayPromptAsync overload hurts usability

Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs
Looks like IsVisible=false doesn't hide Frame's shadow.
Seems bug was introduced in e2101e4ea4471ff682525f52d2e393830a03db10
- fixes #9782
None
- iOS
IsVisible=False|True shows/hides the frame
Use this very simple sample:
```csharp
var frame = new Frame() { VerticalOptions = LayoutOptions.CenterAndExpand, Content = new Label { Text = "Text" } };
var btn = new Button
{
Text = "click",
VerticalOptions = LayoutOptions.EndAndExpand,
Command = new Command(() =>
{
frame.IsVisible = !frame.IsVisible;
})
};
MainPage = new ContentPage
{
Content = new StackLayout
{
Children =
{
frame,
btn
}
}
};
```
=> [BUG][iOS] IsVisible=false isn't working with Frame

Xamarin.Forms.Controls/GalleryPages/TwoPaneViewGalleries/TwoPanePropertiesGallery.xaml, Xamarin.Forms.Controls/GalleryPages/TwoPaneViewGalleries/TwoPanePropertiesGallery.xaml.cs, Xamarin.Forms.DualScreen.UnitTests/TwoPaneViewNotSpannedTests.cs, Xamarin.Forms.DualScreen/DualScreenService.android.cs, Xamarin.Forms.DualScreen/DualScreenService.uwp.cs, Xamarin.Forms.DualScreen/TwoPaneView.shared.cs
If a device isn't a Duo then don't initialize any of the duo services.
Fixed an issue where Pane1 was staying non visible after Pane2 was set as priority
- Android
- Use the CG App on an API 29 device (non duo) and make sure you can change the orientation on the device without crashing
- On a duo device set Pane2 as the priority, tweak the minwide/tall mode settings so only pane2 shows up, span the app, unspan the app, and verify both panes are displaying
=> Don't Init DualScreenService on non duo device

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9767.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
Fixed issues related with NavigationBar colors (`BarBackgroundColor` and `BarTextColor`).
- fixes #9767 
- fixes #9790 
None
- iOS
None
To test 9767 launch Core Gallery and navigate to the Issue9767. Press the available button and verify that everything works as expected.
=> [iOS] Fixed issues related with NavigationBar colors

Xamarin.Forms.Material.Android/MaterialButtonRenderer.cs, Xamarin.Forms.Material.Android/MaterialColors.cs, Xamarin.Forms.Material.iOS/MaterialButtonRenderer.cs
Apply Text Color to disabled states on Buttons
- fixes #9261
- iOS
- Android
Disabled buttons will now apply whatever you have set the TextColor to. This is a breaking change but prior to this fix it was impossible to change the color when the button is in a disabled state. 
Below is the visual gallery.
On the left is before and on the right is after
- run the visual gallery and compare ios and android
=> Set text color for disabled states on material buttons

build.cake
When building nugets in debug UWP includes a reference to an extra dll that won't be present with the nugets
Disabling EnableTypeInfoReflection removes the dll from being referenced
The targets file for this property looks like this
```
<EnableTypeInfoReflection Condition="'$(EnableTypeInfoReflection)' == '' AND '$(Configuration)' == 'Debug' AND '$(UseDotNetNativeToolChain)' != 'true'">true</EnableTypeInfoReflection>
<EnableTypeInfoReflection Condition="'$(EnableTypeInfoReflection)' == ''">false</EnableTypeInfoReflection>
```
So basically I just force it to false when building for nugets. 
Pull down debug nugets and test them on vs2017/vs2019
=> Disable EnableTypeInfoReflection for nugets when building for debug

Xamarin.Forms.Platform.WPF/Renderers/SliderRenderer.cs
If you get into a scenario where a set bindable property is queue'd up internally it will cause the Slider to hit an infinite loop. The BP will set the value which then causes the Control to get set, which was then causing a value to get set from the renderer to the element, which would then get queue'd up, etc...
- WPF
- make sure sliders all still work on WPF
- The place I Was seeing this issue was on the TwoPaneView gallery. On the properties gallery if you set both of the MinTall and MinWide values to max then resized the window
=> [WPF] Dont set Slider.Value if it already matches control

Xamarin.Forms.ControlGallery.iOS/Tests/NavigationTests.cs, Xamarin.Forms.ControlGallery.iOS/Xamarin.Forms.ControlGallery.iOS.csproj, Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
The iOS NavigationRenderer, Container, and ParentingViewController classes were not set up to handle multiple calls to `Dispose`. Double disposal of a ParentingViewController (which is triggered by double disposal of Container and/or NavigationRenderer) causes a NullReferenceException on the second call when attempting to call `Child.SendDisappearing()`.
These changes place the call to `Child.SendDisappearing()` inside a null check, and also implement the normal disposal pattern for these classes.
- Fixes #9841
None
- iOS
None
Not applicable
Automated platform test (NavigationRendererDoubleDisposal).
=> Fix disposal pattern for NavigationRenderer and ParentingViewController

.nuspec/Xamarin.Forms.AppLinks.nuspec, .nuspec/Xamarin.Forms.DualScreen.nuspec, .nuspec/Xamarin.Forms.Maps.GTK.nuspec, .nuspec/Xamarin.Forms.Maps.WPF.nuspec, .nuspec/Xamarin.Forms.Maps.nuspec, .nuspec/Xamarin.Forms.Pages.Azure.nuspec, .nuspec/Xamarin.Forms.Pages.nuspec, .nuspec/Xamarin.Forms.Platform.GTK.nuspec, .nuspec/Xamarin.Forms.Platform.WPF.nuspec, .nuspec/Xamarin.Forms.Visual.Material.nuspec, .nuspec/Xamarin.Forms.nuspec
Updated nuspec files to use the package icon instead of URL icon.
More info here: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packageiconurl
- fixes #8619
None
None
None
Not applicable
Try to build nuget package
=> [Housekeeping] NuGet Icon switch to PackageIcon

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9054.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/Renderers/ImageButtonRenderer.cs
Delete the FormsButton because it's not being used. This was code left over when I was trying to get GIF Animations work on Buttons but was unsuccessful. 
- fixes #9054
- iOS
- Added a manual test. Not really sure if this can be automated. The UIImageView is always the same size regardless of the aspect setting.
=> [iOS] Remove unused FormsButton to fix Aspect

Xamarin.Forms.Core/FlexLayout.cs
Avoid NRE in OnMeasure, caused by race conditions
- fixes #9340
We don't have a repro project for that issue, but the fix has been tested by the OP, and it fixes the issue
None
None
Not applicable
=> [C] Avoid NRE in Flex.OnMeasure

Xamarin.Forms.Platform.iOS/Renderers/PhoneMasterDetailRenderer.cs
MasterDetailPage shadow platform-specific not applied when first set
- fixes #9842 
- iOS
Detail page drags with shadow.
=> Fix 9842 [Bug][iOS] MasterDetailPage shadow platform-specific not applied when first set

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9694.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.UAP/SwitchRenderer.cs
Fixed crash setting the OnColor Switch property on UWP. Recently we changed to reference 2.3.191211002 when targeting 16299 or later. This changes the OnColor type from Brush to Color and causes the issue.
- fixes #9694
None
- UWP
None
Launch Core Gallery and navigate to the Issue 9694. If there is no exception, the test has passed.
=> [UWP] Fixed crash setting the OnColor Switch property

Xamarin.Forms.Xaml.UnitTests/Issues/Gh9212.xaml, Xamarin.Forms.Xaml.UnitTests/Issues/Gh9212.xaml.cs, Xamarin.Forms.Xaml/MarkupExpressionParser.cs
consume trailing spaces after quoted string in markup. this was regressed by #8980
- fixes #9212
None
None
Not applicable
=> [X] consume trailing spaces in markup

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue7878.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/UIModalPresentationStyle.cs, Xamarin.Forms.Platform.iOS/Extensions/Extensions.cs, Xamarin.Forms.Platform.iOS/ModalWrapper.cs, Xamarin.Forms.Platform.iOS/PageExtensions.cs, Xamarin.Forms.Platform.iOS/Platform.cs, build.cake
- fixes #7878 
- related #7145 & #7172
- fixes #9307
None
- iOS
Modals presented as a `FormSheet` can now be swiped down and this will trigger the popped event for a modal within Xamarin.Forms. Because of that, the app continues to behave as intended instead of getting stuck because of the modal still being on the navigation stack.
Not applicable
=> iOS13 Fix Modal lifecycle

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9783.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9783.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.UAP/DatePickerRenderer.cs, Xamarin.Forms.Platform.UAP/TimePickerRenderer.cs
Fixed a crash hidden a DatePicker on UWP. Recently we changed to reference 2.3.191211002 when targeting 16299 or later. This has changed the template of the control. Only have one child element called _"FlyoutButton"_ if the control is visible.
- fixes #9783
None
- UWP
None
Launch Core Gallery and navigate to the Issue 9783. If there is no exception, the test has passed.
=> [UWP] Fixed a crash hidden a DatePicker (Xamarin.Forms 4.5-pre4)

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/A11yTabIndex.xaml, Xamarin.Forms.Controls/CoreGallery.cs, Xamarin.Forms.Controls/TabIndexTest/DayView.xaml, Xamarin.Forms.Controls/TabIndexTest/DayView.xaml.cs, Xamarin.Forms.Controls/TabIndexTest/DaysOfWeekView.xaml, Xamarin.Forms.Controls/TabIndexTest/DaysOfWeekView.xaml.cs, Xamarin.Forms.Controls/TabIndexTest/TabIndex.xaml, Xamarin.Forms.Controls/TabIndexTest/TabIndex.xaml.cs, Xamarin.Forms.Controls/TabIndexTest/ViewModels.cs, Xamarin.Forms.Controls/Xamarin.Forms.Controls.csproj, Xamarin.Forms.Core.UnitTests/TabIndexTests.cs, Xamarin.Forms.Core/TabIndexExtensions.cs, Xamarin.Forms.Platform.Android/Renderers/PageRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/ShellFlyoutRecyclerAdapter.cs, Xamarin.Forms.Platform.Android/VisualElementRenderer.cs, Xamarin.Forms.Platform.iOS/Extensions/UIViewExtensions.cs, Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/PageContainer.cs, Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/PhoneMasterDetailRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutRenderer.cs
* iOS MasterDetailPage will no longer read MasterPage contents when the master page is hidden and will no longer read DetailPage contents when the master page is visible.
* iOS can now tab stop on a Frame and can read its contents properly.
* iOS/Android screen readers should no longer skip over layouts and should read all children in declaration order and/or TabIndex order.
* TabIndex should no longer return elements that are `Enabled = false` or `IsAccessibilityElement = false`.
- fixes #9653
- fixes #4220 
- fixes #9191 
- fixes #8613
- fixes #9137
- fixes #8691 
- fixes #7606
- fixes #4270
- fixes #5879
These are breaking API changes, but they drive me crazy. I will revert if someone has an issue with this.
`TabIndexExtensions`:
```diff
-public static SortedDictionary<int, …
```
=> [iOS|Android] Fix screen reader order

Xamarin.Forms.Platform.MacOS/Renderers/ButtonRenderer.cs
Xamarin.Mac (and therefore by extension Xamarin Forms on macOS) doesn't default to any bezel style for buttons, which gives them an unexpected look.
This defaults to `Rounded`.
- fixes #8093
- macOS
Buttons on macOS will look different.
After the change, these two should look roughly equivalent:
```xml
<Button Grid.Column="1" Grid.Row="1" Text="SomeLabel" HorizontalOptions="Start" />
<ContentView Grid.Column="1" Grid.Row="2" VerticalOptions="Center" HorizontalOptions="Start" Padding="0" Margin="0">
<appkit:NSButton Title="SomeLabel" BezelStyle="Rounded" />
</ContentView>
```
I have **not** tested this myself yet.
=> [macOS] Set default bezel style for button

Xamarin.Forms.ControlGallery.iOS/Tests/NavigationTests.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8308.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8308.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/CollectionView/StructuredItemsViewController.cs
The handlers set up to remeasure the Header/Footer when their Forms element sizes changed were not being unhooked on Dispose; this led to the events firing and calling the handlers with a reference to an already disposed UICollectionView.
These changes unhook the handlers on Dispose.
- fixes #8308 
None
- iOS
None
Not applicable
Automated test
=> Unhook Header/Footer measure handlers on Dispose

Xamarin.Forms.Build.Tasks/XamlTask.cs, Xamarin.Forms.Xaml.UnitTests/CecilExtensionsTests.cs, Xamarin.Forms.Xaml.UnitTests/Validation/MissingXClass.xaml, Xamarin.Forms.Xaml.UnitTests/Validation/NotXaml.xaml, Xamarin.Forms.Xaml.UnitTests/X2006Namespace.xaml
Context: https://www.jetbrains.com/profiler/
I was profiling Xamarin.Android project builds with `dotTrace`, and
noticed an `IsXaml` method from XamlC taking time:
0.07%   IsXaml  •  40/0 ms  •  Xamarin.Forms.Build.Tasks.CecilExtensions.IsXaml(EmbeddedResource, ModuleDefinition, out String)
0.07%   Execute  •  Xamarin.Forms.Build.Tasks.XamlCTask.Execute(out IList)
0.07%   Execute  •  Xamarin.Forms.Build.Tasks.XamlTask.Execute
In this build, I had changed only XAML and the netstandard project was
using `<ProduceReferenceAssembly>True</ProduceReferenceAssembly>`.
The project is here:
https://github.com/xamarin/xamarin-android/tree/master/tests/Xamarin.Forms-Performance-Integration
Reviewing `IsXaml`, it uses `XmlDocument` to parse every
`EmbeddedResource` with a `.xaml` extension. The …
=> [XamlC] use XmlReader for detecting XAML and x:Class

Xamarin.Forms.Build.Tasks/SetPropertiesVisitor.cs
see #9294
None
None
Not applicable
> VS bug [#1084040](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1084040)
=> [X] register asm in sourceinfo for xamlc

Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj, Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
[Bug] On().SetHideNavigationBarSeparator(true) does not work on Xamarin.Forms latest stable version (4.5.0.356) and latest preview version (4.6.379-pre1), it works well on 4.4.0.991757. 
- fixes #9952 
None
- iOS
Separator is not visible
=> Fix-9952 On<iOS>().SetHideNavigationBarSeparator(true) does not work on Xamarin.Forms latest stable version (4.5.0.356)

Xamarin.Forms.Platform.WPF/Renderers/PickerRenderer.cs
Picker  background color is not implemented on WPF 
- fixes #9838  
- WPF
BackgroundColor is updated
=> Fix-9838 [WPF] Picker does not respect BackgroundColor

Xamarin.Forms.Core/SwipeView.cs, Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs
Fixed SwipeView icon size using FontImageSource on Android.
None
- Android
None
Launch Core Gallery and navigate to the SwipeView samples. Open the SwipeView Icons sample and verify the icon using FontImageSource.
=> [Android] Fix SwipeView icon size using FontImageSource

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/ShellItemIsVisible.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRootRenderer.cs
Add check inside ShellSectionRenderer on iOS to see if Current Item is set. If it's not set then don't process any renderer changes
- fixes #9801
- iOS
=> [iOS] Check if Current Item on Shell Section is set before proceeding 

Xamarin.Forms.Platform.UAP/CollectionView/CarouselViewRenderer.cs
We need to call the correct position when CarouselView loads.
None
- UWP
Shows go to the correct position on load.
Not applicable
Open CarouselView (Code, Horizontal) and make sure it goes to Position 1.
=> [UWP] Make sure to call UpdateInitialPosition on CarouselView

Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs
Setting a BackgroundColor for a Frame on iOS causes the background color to draw outside of the Frame's rounded corners.
- fixes #9265, #9774
- iOS
Background color does not overflow Frame's rounded corners
=> Fix 9265 [iOS] Frame BackgroundColor overflows CornerRadius

Xamarin.Forms.Core.UnitTests/ColorUnitTests.cs, Xamarin.Forms.Core/Color.cs
This PR adds `Color.FromHsva()` to support **[HSV](https://en.wikipedia.org/wiki/HSL_and_HSV)** (Hue, Saturation, Value- also known as **HSB** - Hue, Saturation, Brightness) color space. Previously, `Xamarin.Forms.Color` could be created from RGB, HSL, HEX, and Uint values, but there was no way to generate them from HSV(HSB) values. 
HSV(HSB) is similar to HSL. They're both based on cylindrical geometries, but HSV is based on a "Hexacone" model while HSL is based on a "Bi-Hexacone" model. Read more about the differences on [wikipedia](https://en.wikipedia.org/wiki/HSL_and_HSV).
I don't want to extend `Color.Mode`, or make it heavier. I'd like to add only `Color.FromHsva()` method that can easily generate a `Color` from HSV values just like `Color.FromHex()` or `Color.FromUint()`.
None …
=> Adds Color.FromHsva

Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/CarouselViewGalleries/CarouselCodeGallery.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/ExampleTemplates.cs, Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/PositionControl.cs, Xamarin.Forms.Platform.UAP/CollectionView/CarouselViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewStyles.xaml, Xamarin.Forms.Platform.UAP/CollectionView/ScrollHelpers.cs
Set the padding do the FormsListView so the CarouselView items are always centered and have the same size, if they are first or last
- fixes #10019 
None
- UWP
Should be able to go to the first and last item when using PeekAreaInsets
Not applicable
Try to go to first and last item on CarouselCodeGallery or IndicatorGallery
=> [UWP] Fix PeekAreaInsets usage on CarouselViewRenderer

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9417.xaml, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue9417.xaml.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/SwipeView.cs, Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs
Fixed SwipeView regression issue adding some View as content without using a Layout on iOS.
- fixes #9417
None
- iOS
None
After
Launch Core Gallery and navigate to the Issue9417. Try to swipe some item from the collection. If you can swipe without problems, the test has passed.
=> [iOS] Fixed SwipeView regression issue 

Xamarin.Forms.Core.UnitTests/ColorUnitTests.cs, Xamarin.Forms.Core/ColorTypeConverter.cs
Enhance existing `ColorTypeConverter` to support **HSVA** color format (newly introduced in #10054).
Supported inputs are as follows. (same as `HSLA`)
- **hsv(120, 100%, 50%)**  
- _h is 0-360, s and l are 0%-100%_
- **hsva(120, 100%, 50%, .8)**
- _opacity is 0.0-1.0_
None
None
None
Go `ColorUnitTests.TestColorTypeConverter`
=> Update ColorTypeConverter to support HSVA

Xamarin.Forms.Core/PlatformConfiguration/TizenSpecific/Application.cs, Xamarin.Forms.Platform.Tizen/Forms.cs, Xamarin.Forms.Platform.Tizen/FormsApplication.cs
This PR is about global circle surface and circle objects for tizen wearable devices.
On Tizen, you can use `CircleSurafce` to rendner various circle objects including circle progress bar and circle slider and so on. Plus, this PR also includes a Tizen Specific API that determines whether app use bezel (or crown) interactions on wearable device like Galaxy Watch. For example, you can decide whether to control the scrolling behavior of the ListView, ScrollView by rotating the bezel. 
This Tizen platform-specific is used to decide whether to use bezel interaction for scrolling or not in your app, The default is `true`, so when you rotate the bezel, it will scroll to list view or scroll view. It's consumed in XAML by setting the `Application.UseBezelInteraction` to `true` or `false` :
```xml …
```
=> [Tizen] Provides global Circle Surface for wearable

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8272.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs
Fix Label **TextDecorations** (Example: Underline) issue on iOS from Xamarin.Forms 4.3.
- fixes #8272
None
- iOS
None
Not applicable
Launch Core Gallery and navigate to the Issue8272. Toggle the Switch. If the text below is underline, the test has passed.
=> [iOS] Fix Label TextDecorations issue

Xamarin.Forms.Platform.Android/CellAdapter.cs
Add a null check in OnActionItemClickedImpl. If items are in the process of being added/removed from the list, it's possible to have the context menu tap race against the actual existence of the underlying Cell.
- fixes #9786
None
- Android
None
Not applicable
This one is painful to test; it's difficult to get the timing right in the original repro, and it requires tapping around in a way that's too fast for a UI test to replicate. Tooks a stab writing a platform test, but the tight coupling between the Android ListView implementation and the OS stuff for context menus makes it a very involved task.
=> Add null check to OnActionItemClickedImpl

Xamarin.Forms.Platform.Android.UnitTests/ShellTests.cs, Xamarin.Forms.Platform.Android.UnitTests/Xamarin.Forms.Platform.Android.UnitTests.csproj, Xamarin.Forms.Platform.Android/Extensions/DrawableExtensions.cs, Xamarin.Forms.Platform.Android/Renderers/IShellBottomNavigationViewAppearanceTracker.cs, Xamarin.Forms.Platform.Android/Renderers/ShellBottomNavViewAppearanceTracker.cs
If user hasn't specified a color then default the tab color to white. Otherwise the ColorChangeDrawable causes a really weird effect if you set any other colors of the TabBar 
- Android
=> Fix Shell to use white as default if no color is specified

Xamarin.Forms.Core.UnitTests/MockPlatformServices.cs, Xamarin.Forms.Core.UnitTests/UriImageSourceTests.cs, Xamarin.Forms.Core/Crc64.cs, Xamarin.Forms.Core/IPlatformServices.cs, Xamarin.Forms.Core/UriImageSource.cs, Xamarin.Forms.DualScreen.UnitTests/MockPlatformServices.cs, Xamarin.Forms.Platform.Android/Forms.cs, Xamarin.Forms.Platform.Android/ResourceManager.cs, Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android.csproj, Xamarin.Forms.Platform.GTK/GtkPlatformServices.cs, Xamarin.Forms.Platform.GTK/Xamarin.Forms.Platform.GTK.csproj, Xamarin.Forms.Platform.MacOS/Xamarin.Forms.Platform.macOS.csproj, Xamarin.Forms.Platform.Tizen/TizenPlatformServices.cs, Xamarin.Forms.Platform.Tizen/Xamarin.Forms.Platform.Tizen.csproj, Xamarin.Forms.Platform.UAP/WindowsBasePlatformServices.cs, Xamarin.Forms.Platform.UAP/Xamarin.Forms.Platform.UAP.csproj, Xamarin.Forms.Platform.WPF/Microsoft.Windows.Shell/Standard/Utilities.cs, Xamarin.Forms.Platform.WPF/WPFPlatformServices.cs, Xamarin.Forms.Platform.WPF/Xamarin.Forms.Platform.WPF.csproj, Xamarin.Forms.Platform.iOS/Forms.cs, Xamarin.Forms.Platform.iOS/Xamarin.Forms.Platform.iOS.csproj
Replace all uses of md5 for creating a hash. The only place we really use this is for hashing a uri so we have a consistent length to use for a hashkey
Added:
- string IPlatformServices.GetHash
- iOS
- Android
- UWP
- UI tests pass
- Images load and are cached
=> Remove all uses of md5

Xamarin.Forms.Platform.Android/Resources/values/styles.xml
Pull the default style into the Android platform project and update it to use DayNight to support Dark Theme.
- related #9804
None
- Android
From what I can think of these would be the scenarios:
- When the user has created customizations in the theme we supply in the templates by default, this should still override whatever we do here.
- If the user has created their own theme altogether, they are not hit by this change
- If the user is still using the default theme from the templates, nothing changes. It will act as an override to the theme we specify here
Basically the only way the user will see this change is if they throw out the current theme in their project and whenever we decide to remove the theme from the template and use this as the default. Whenever that happens, the user …
=> [AND] Default style to DayNight (Dark Theme support)

Xamarin.Forms.Core.UnitTests/ShellTests.cs, Xamarin.Forms.Core/Routing.cs, Xamarin.Forms.Core/Shell/Shell.cs, Xamarin.Forms.Core/Shell/ShellNavigationState.cs
When you make changes to the AppShell file hot reload adds all the items and then removes them. If the current item has been removed this PR will cause shell to look too see if the item has been re-added and then navigate to it
- Added a D_FAULT prefix to routes that are created without a route name so they can be filtered out of the Location representing users current location. This was needed for hotreload because when trying to renavigate I need to strip off the routes that are just generated from a counter
- Navigate to a different flyout item and make a change to AppShell. The same item should stay active
=> Shell hotreload fixes when changing Shell class

Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs, Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs
Fix SwipeView Open issue in iOS.
Validate that there are swipe items and do not reassign the Bounds to the control to fix the programmatically open logic. These are validations that I think we have lost in some rebase. For example: https://github.com/xamarin/Xamarin.Forms/pull/9635/commits/a85ef9f7ef749dffde4dda993151d651143c340b#diff-cdef6ff7f48a8d49afb93057ab79f8c7R1159
- fixes #10095
- fixes #10096 
None
- iOS
None
Not applicable
Launch Core Gallery and navigate to the "Open/Close SwipeView" sample. Try open and close the SwipeView several times with both buttons and gestures. Verify that everything always works as expected.
=> [iOS] Fix SwipeView programmatically Open issue

Xamarin.Forms.Platform.WPF/Renderers/BoxViewRenderer.cs
BoxView is not correctly restored after Navigation.PushAsync(); … Navigation.PopAsync();
This PR is instead of #9745  that was broken and contained incorrect changes.
- fixes #6408 
- WPF
=> Fix6408 [WPF] box view not correctly restored

Xamarin.Forms.Core/Profiler.cs, Xamarin.Forms.Core/Registrar.cs, Xamarin.Forms.Platform.Android/Forms.cs, Xamarin.Forms.Platform.Tizen/Forms.cs, Xamarin.Forms.Platform.UAP/FormsUWP.cs, Xamarin.Forms.Platform.iOS/Forms.cs
Profiling a Blank Forms app template with allocations on Android:
adb shell setprop debug.mono.profile log:calls,alloc
I saw something worrying:
Allocation summary
Bytes      Count  Average Type name
32064          2    16032 Xamarin.Forms.Internals.Profile.Datum[]
24032          1    24032 Xamarin.Forms.Internals.Profile[]
This appears to be ~56KB of objects that are allocated at startup.
`Profile` in general looks like it should be useful, but it shouldn't
impact startup in customer's apps!
The `Profile` struct is a public API, so we can't use `#if` or
`[Conditional]`. I'm thinking a new flag is need to enable the
`Profile` class:
Forms.SetFlags("Profile");
To make everything work, I had to add two public members to `Profile`:
* Profile.Enable()
* Profile.IsEnabled
They can't be …
=> [core] Profile is off by default, save 56KB of allocations

.nuspec/Xamarin.Forms.Visual.Material.nuspec, .nuspec/Xamarin.Forms.nuspec
Copy everything from build to buildTransitive so you can install Xamarin.Forms into a single library and all the build targets will transitively apply 
- fixes #9593
- fixes #9995
- test the nugets and make sure devdiv builds all run
=> Copy build to buildTransitive

.nuspec/proguard.cfg
When a project isn't running androidx migration (so not referencing any support libraries) than the migration doesn't migrate the proguard rules. So we need to have the equivalent androidx proguard rules in place
- Android
- download nugets
- create new forms projects
- update essentials/forms to latest androidx dependent packages
- ensure you're targeting API 29
- enable r8/d8 and linker
- make sure project runs
=> Add equivalent androidx proguard rules

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue8964.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs, Xamarin.Forms.Platform.UAP/CollectionView/CarouselViewRenderer.cs, Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewController.cs
If we are adding a new item we need to keep the position on the CurrentItem. 
Fixes a regression on the new code introduced.
- fixes #8964
None
- iOS
- Android
None
None
=> [iOS,Android] Fix CurrentItem position when adding a item

Xamarin.Forms.Core.UnitTests/ShellTests.cs, Xamarin.Forms.Core/Routing.cs
As part of this https://github.com/xamarin/Xamarin.Forms/pull/10064 I removed all the default routes so that hot reload would be able to reroute to where the user was working.
This introduced a bug where if you've pushed a global route then it'll strip off all routes that are part of shell if everything is default. 
If the user has navigated to a global route than we have to retain the last default route to give an accurate indication of where the user is 
=> Fix route removal to keep one default route if it's needed

Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeItemIconGallery.cs, Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeItemSizeGallery.xaml, Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeItemSizeGallery.xaml.cs, Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeViewGallery.cs, Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs
In iOS, using large icons, the icon does not fit correctly. This PR fix the SwipeItem issue with big icons.
- fixes #10113 
None
- iOS
None
Not applicable
Launch Core Gallery and navigate to the SwipeView samples. Select "SwipeItem Size Gallery". There are several SwipeView's using different icon sizes, etc. Open all the SwipeView's and verify that the icon have the correct size in all the cases.
=> [iOS] Fix SwipeItem issue with big icons

azure-pipelines.yml, build.cake, build/provisioning/provisioning.csx, build/steps/build-android.yml, build/steps/build-osx.yml
- add releaseChannel arg to cake
- force vs2017 build to always use cake regardless of the provision settings
- update provisionator to latest stable bits
- setup OSX Phase to use macOSXVmImage variable
=> Add preview channel args and fixup provisionator

Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs
When using a FlexLayout with a TemplateSelector, rendering of the items in the collection becomes corrupted when switching between different collections.
Actually the problem is not with Flexlayout but with disposing of shadow view for a Frame control.
- fixes #9997 
None
- iOS
None
=> Fix 9997 [Bug] iOS Frame Shadow memory leak

Xamarin.Forms.Platform.Android/Renderers/ShellRenderer.cs, Xamarin.Forms.Platform.Android/Renderers/ShellToolbarAppearanceTracker.cs
- Don't swap out background drawable if nothing has changed
- Don't change any toolbar drawables or colors if nothings has changed
- fixes #8581 
- fixes #6294
- Android
- Test nuget with samples from here https://github.com/xamarin/Xamarin.Forms/issues/8581
- Or using the Gallery push and pop pages and see if there is any weird flickering
=> Only change out colors if they have actually changed

Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue6484.cs, Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Xamarin.Forms.Controls.Issues.Shared.projitems, Xamarin.Forms.Core/Shell/ShellSection.cs, Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs
The renderer on the page was being being removed before the event was propagated down to shell. Shell was using the renderer on the page to access the viewcontroller in order to remove it from the stack. This code makes the platform code less dependent on the ordering of the xplat code. 
- fixes #6484 
- iOS
- automated tests included
=> Remove controller from UINavigationController stack  when page is removed

Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs
This PR fixes an issue that caused the `UINavigationBar.Appearance.BarTintColor` not to be applied in the NavigationBar in iOS 13.
NOTE: Changing other options like `TintColor` or `TitleTextAttributes` works. Changing `BarTintColor` works on iOS <= 12.
- fixes #9765
None
- iOS
None
Not applicable
Open Core Gallery and include the following lines in the `AppDelegate`:
```
UINavigationBar.Appearance.BarTintColor = UIColor.FromPatternImage(UIImage.FromFile("coffee.png"));
UINavigationBar.Appearance.TintColor = UIColor.Orange;
UINavigationBar.Appearance.SetTitleTextAttributes(new UITextAttributes() { TextColor = UIColor.Green });
```
The result must be:
```
UINavigationBar.Appearance.BarTintColor = UIColor.FromPatternImage(UIImage.FromFile("coffee.png"));
UINavigationBar.Appearance.TintColor …
```
=> Fixed not applied BarTintColor in iOS NavBar using iOS 13
